### ISSUE TITLE
ixgbe driver in XDP mode can fail to load when a node has >64 CPUs

### ISSUE THREAD

**Issue by briantopping** [cilium/cilium#14648] opened 2021-01-18 23:32 UTC
When Cilium is installed on a node where the Intel ixgbe driver is used with SR-IOV enabled, the driver will fail to load with a memory error that looks like the following when a node has more than 63 hyperthread CPUs:
```
level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.16.1.104 <nil> direct eno1 eno1 xdpdrv 1500 false <nil> false false false /var/run/cilium/cgroupv2 /sys/fs/bpf true true v2 eno1=0x22000a0a <nil> 72 false]" error="exit status 2" subsys=datapath-loader
```
When `init.sh` fails to load, the logs for the cilium node contain the output of shell script with `level=warning`. The actual error is displayed there:
```
level=warning msg="+ ip -force link set dev eno1 xdpdrv obj bpf_xdp.o sec from-netdev" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Cannot allocate memory" subsys=datapath-loader
level=warning msg="+ RETCODE=2" subsys=datapath-loader
```
At the time of writing (kernel 5.10), the driver creates a XDP queue count for each hyperthread CPU. It is [bounds checked](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/ethernet/intel/ixgbe/ixgbe_main.c#n10136) to `MAX_XDP_QUEUES ` (63) CPUs:
```
	if (nr_cpu_ids > MAX_XDP_QUEUES)
		return -ENOMEM;
```
`MAX_XDP_QUEUES` is a header constant and the value cannot be changed at runtime. 

The only solution for now is to reduce the number of enabled cores on a node by using `nr_cpus=63` as a kernel boot parameter. The issue has been reported to the ixgbe team and we will update this issue as more information is available.

**Comment by borkmann** [comment] 2021-01-18 23:46
(Has been reported to upstream kernel, thus closing from Cilium side given the issue is related to ixgbe driver itself. We can still update if something was fixed from Intel folks later on.)

**Closed as completed by borkmann** 2021-01-18 23:46 UTC
Labels: kind/question, area/kernel

**Comment by briantopping** [comment] 2021-01-19 21:00
An update from intel-wired-lan@lists.osuosl.org:

> Hi Brian,
> we're aware of this issue, thanks for bringing this up. We plan to address
> this in some near future.
> 
>> Any advice what the most practical long term solution is?
>> 
>> Short term, I can dial back the number of usable cores. I haven’t dug
>> into the bits to understand if this constraint is based on hardware
>> limits on the card or this was a choice that was made when processors
>> had fewer cores.
> 
> ixgbe has only 128 Tx HW queues AFAIK, so currently we have a check
> against cpu count and do not load XDP for case when machine has more than
> 64 cpus as XDP needs to have a dedicated HW Tx queue so that it is fully
> operational.
> 
> I think that solution (or workaround, not sure how to relate to that) is
> picking what is left in terms of HW Tx resources and assigning it to XDP.
> 
> If sending happens on a cpu nr 70:
> 
> cpu_nr = 70
> cpu_cnt = 72;
> xdp_tx_cnt = 56;
> 
> then we pick (cpu_nr % xdp_tx_cnt) + cpu_cnt = (70 % 56) + 72 = 86 HW Tx
> queue. At the same time, same queue could be accessed from cpu 14 if I am
> not mistaken, so this brings the need for locking. We would be detecting
> such configuration at the time when XDP prog is being loaded onto
> interface and picking that 'fallback' mode. For < 64 cpu machines, current
> scheme will be picked so we wouldn't be hurting performance via unneeded
> lock acquiring for such systems.
> 
> Maciej
