### ISSUE TITLE
Travis: FAIL: <autogenerated>:1: StoreConsulSuite.TestStoreOperations

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#8609] opened 2019-07-18 06:29 UTC
Travis CI on master reports:

```
store_test.go:204:
    c.Assert(expect(func() bool { return localKey2.deleted() == 0 }), IsNil)
... value *errors.errorString = &errors.errorString{s:"timeout while waiting for expected value"} ("timeout while waiting for expected value")
level=info msg="Waiting for consul to elect a leader" subsys=kvstore
```

**Comment by mrostecki** [comment] 2019-07-18 14:33
Duplicate of #8596

**Closed as completed by mrostecki** 2019-07-18 14:33 UTC
Labels: kind/bug/CI, needs/triage
