### ISSUE TITLE
CFP: Cilium BGP Control Plane LB IPAM Services should respond to ICMP

### ISSUE THREAD

**Issue by olemathias** [cilium/cilium#28458] opened 2023-10-08 00:01 UTC
**Is your proposed feature related to a problem?**

Enabling services to respond to ping requests enhances network troubleshooting.
Currently services utilizing the Cilium BGP Control Plane and LB IPAM in k8s do not reply to ICMP echo requests.

**Describe the feature you'd like**

A service/load-balancer exposed using Cilium BGP Control Plane should respond to ICMP/CMPv6 Echo Requests.

**(Optional) Describe your proposed solution**
Having a option to enable/disable ICMP response for the load balancer.

Additionally it's currently creating a routing loop (cilium v1.14.2):
```
10.10.12.1 is the gateway in the node subnet.
10.10.12.2-4 is the nodes.
185.248.yyy.xxx is the load balancer.

traceroute to 185.248.yyy.xxx (185.248.yyy.xxx), 30 hops max, 60 byte packets
 1  185.248.xxx.xxx (185.248.xxx.xxx)  0.265 ms  0.238 ms  0.222 ms
 2  185.248.xxx.xxx (185.248.xxx.xxx)  0.478 ms  0.463 ms  0.451 ms
 3  10.10.12.4 (10.10.12.4)  0.768 ms  0.746 ms  0.735 ms
 4  10.10.12.1 (10.10.12.1)  0.715 ms  0.695 ms  0.659 ms
 5  10.10.12.4 (10.10.12.4)  0.752 ms  0.742 ms  0.717 ms
 7  * 10.10.12.2 (10.10.12.2)  1.369 ms *
 8  10.10.12.1 (10.10.12.1)  1.320 ms * *
14  * 10.10.12.1 (10.10.12.1)  1.561 ms  1.510 ms
15  10.10.12.3 (10.10.12.3)  1.544 ms  1.528 ms  1.676 ms
16  10.10.12.1 (10.10.12.1)  1.627 ms  1.586 ms  1.269 ms
17  10.10.12.4 (10.10.12.4)  1.368 ms  1.342 ms *
22  10.10.12.1 (10.10.12.1)  1.421 ms * *
```
The same behavior is observed for IPv6 as well.

**Comment by sbogomolov** [comment] 2023-11-18 22:03
I'm currently debugging a weird issue which might be related. Traefik is assigned an IP by LB IPAM. Even though it's (pod's) network adapter MTU is 1500, sometimes it sends packets larger than that. At some point on the network path this packet is dropped and ICMP Destination Unreachable (Fragmentation Needed) is sent back. I have confirmed that the host receives these ICMP packets and then sends them back. I assume that Pod does not receive these packets (I cannot run tcpdump inside it to confirm). It's also weird why the same ICMP packet is reflected back. I guess what I'm trying to say is that this kind of breaks things, so the requested feature will help not only with pings :)

**Comment by YutaroHayakawa** [comment] 2023-11-20 01:49
@olemathias Hi, thanks for your report. Regarding the ICMP echo issue, the IP address of the Service VIP is not assigned to any network device. Thus, the Linux kernel doesn't reply to the ICMP echo. And, Cilium pass through ICMP packet to the service VIP to the Linux stack. That's why no one responds to the ICMP echo.

Regarding the routing loop, Cilium enables IP forwarding on the ingress interface, so if your node has a route, forward the VIP range to the original interface (e.g., default route), the packet will be sent back to the previous hop, then causes a routing loop.

In any case, please provide your sysdump (you can collect it using `cilium sysdump` command). That would be helpful to investigate the issue.

**Comment by YutaroHayakawa** [comment] 2023-11-20 02:02
This is a duplicate of https://github.com/cilium/cilium/issues/14118. Let me reopen the original issue and close this one.

**Closed as completed** 2023-11-20 02:03 UTC
Labels: help-wanted, area/datapath, kind/feature, area/bgp
