### ISSUE TITLE
Have the cilium agent disable Ingress at runtime if l7 proxy is disabled

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#22790] opened 2022-12-19 04:21 UTC
Both Ingress and Gateway API support require the layer 7 proxy to be enabled for them to work, but there are currently some installs that require explicitly disabling the layer 7 proxy (notably Wireguard).

This issue covers having the cilium agent disable CiliumEnvoyConfig reconciliation when the l7 proxy is also disabled. Leaving it enabled can currently cause effects like #22667 (which will also be fixed as part of #22698).

Split out from https://github.com/cilium/cilium/issues/22698.

**Comment by aanm** [comment] 2023-01-16 09:47
@Vishal-Chdhry do you have any update on this? Thank you

**Comment by aanm** [comment] 2023-01-16 09:49
Closing duplicate of https://github.com/cilium/cilium/issues/21354. @Vishal-Chdhry I've assigned you to https://github.com/cilium/cilium/issues/21354 instead.

**Closed as not planned by aanm** 2023-01-16 09:49 UTC
Labels: good-first-issue, area/proxy, area/agent, area/servicemesh
