### ISSUE TITLE
Network Policy not working as expected with configured 

### ISSUE THREAD

**Issue by zbindenren** [cilium/cilium#11095] opened 2020-04-22 07:13 UTC
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by aanm** [comment] 2020-04-22 08:20
Closing, assuming it was intended to be https://github.com/cilium/cilium/issues/11096

**Closed as completed by aanm** 2020-04-22 08:20 UTC
