### ISSUE TITLE
Random jump to extremely high CPU usage

### ISSUE THREAD

**Issue by WoodyWoodsta** [cilium/cilium#29569] opened 2023-12-03 12:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a two node cluster. After some time, all of the cilium agents jump to using an incredibly high amount of CPU. The usage has a very consistent upper limit, and the jump was very square, so it doesn't seem to be scaling with traffic of any kind. There are no difference in logs which appear to correlate with the timing. It always appears to be one of the agents following the other after a few hours.

This has happened before, and the last time the jump occured more than once, leading to almost complete node CPU saturation (as in, can jump from 0-4K m, then from 4-8K m etc). The gaps between these jumps are in the range of 1-5 days. The last time this happened, restarting the agent daemonset reduced the CPU usage to normal levels (~50m).

<img width="1011" alt="image" src="https://github.com/cilium/cilium/assets/8268040/ecc15101-2a30-4cce-a7f6-1e7461719058">

### Cilium Version

v1.14.4

### Kernel Version

5.15.0-89

### Kubernetes Version

v1.28.4

### Sysdump

Way too much sensitive stuff in there - if there is anything specific you might need, I can upload individual files with redacted info.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WoodyWoodsta** [comment] 2023-12-03 12:43
True to the nature of github issue search, I find https://github.com/cilium/cilium/issues/29175 after posting this issue. This is likely a duplicate. Will leave open for opinion.

**Comment by aanm** [comment] 2023-12-04 20:37
Yes, as you said this is duplicate of #29175 which is fixed and will be part of the mid-December release. Thank you

**Closed as not planned by aanm** 2023-12-04 20:37 UTC
Labels: kind/bug, needs/triage, kind/community-report
