### ISSUE TITLE
cilium-operator startup hang syncing more than 128 services to kvstore

### ISSUE THREAD

**Issue by johngmyers** [cilium/cilium#9819] opened 2020-01-07 23:39 UTC
## Bug report

**General Information**

- Cilium version 1.6.5
- Kernel version 4.15.0-70-generic #79~16.04.1-Ubuntu SMP
- Orchestration system version in use Kubernetes v1.14.6
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. Run cilium-operator on cluster with more than 128 services and with 

```
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config", "etcd.operator": "true"}'
```

cilium-operator logs 129 occurrences of `msg="Received service addition &Service{` and then logs nothing until it is killed by the failing liveness check.

Analysis:

`defaults.K8sServiceCacheSize`, which is used to size the channel `k8s.ServiceCache.Event` is 128. It seems likely that `k8s.ServiceCache.UpdateService()` is deadlocking sending to a full channel whose reader won't start until it finishes syncing the service cache.

**Comment by tgraf** [comment] 2020-01-21 11:25
@johngmyers Have you confirmed that this works with less than 128 services? We have tracked down the issue in #9572 but it would deadlock even on a single service.

**Comment by johngmyers** [comment] 2020-01-21 18:09
I have not tried with fewer than 128 services.

**Comment by tgraf** [comment] 2020-01-21 18:17
OK, then this is very likely a duplicate of #9572

**Comment by johngmyers** [comment] 2020-01-21 18:34
I believe this similar, but not duplicate. By my reading of the code, it would be deadlocking after 128 services at https://github.com/johngmyers/cilium/blob/52b2d242c6160bacfada2a5164491dbc713a2856/pkg/k8s/service_cache.go#L150

**Closed as completed** 2020-02-04 09:23 UTC
Labels: kind/community-report, area/operator
