### ISSUE TITLE
Wrong description on certain helm values

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#18248] opened 2021-12-13 11:39 UTC
Some helm values have the wrong description because a flag does not have a description and it's using the description of a previous flag that is commented out.

One example is the `monitor` which has the descrption: "Specify the IPv4 CIDR for native routing (ie to avoid IP masquerade for). This value corresponds to the configured cluster-cidr. ipv4NativeRoutingCIDR:" on [the official docs](https://docs.cilium.io/en/v1.11/helm-reference/)

Which is set here: https://github.com/cilium/cilium/blob/17f42b3b19e45fdda486a1f57bde67c46186181a/install/kubernetes/cilium/values.yaml#L1064-L1068

**Comment by pchaigno** [comment] 2021-12-13 13:33
Duplicate of https://github.com/cilium/cilium/issues/14369.

**Closed as completed by pchaigno** 2021-12-13 13:33 UTC
Labels: good-first-issue, area/helm
