### ISSUE TITLE
Health checks to the pod do not pass if the service has at least one cilium network policy

### ISSUE THREAD

**Issue by Dobry-kot** [cilium/cilium#21044] opened 2022-08-23 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
Health checks to the pod do not pass if the service has at least one cilium network policy
```
kubectl get svc | grep api
api          ClusterIP   10.235.115.82    <none>        8080/TCP                                                    4d

kubectl get deployment | grep api
api             1/1     1            1           20d

kubectl get endpoints | grep api
api          10.212.51.133:8080                                                 4d

kubectl get po -o wide | grep api
api-7c5f7df66c-5dkxq             1/1     Running            0                  20h    10.212.51.133   worker-1    <none>           <none>
```
We see that we have a service deployment in front of it and the service is configured correctly, because it has endpoints.

kubectl get ciliumnetworkpolicies
No resources found in f namespace.

There are no network policies, and we can check the availability of endpoints.
```
test-1) curl 10.212.51.133:8080 from node running under (worker-1) -> 404 page not found
test-2) curl 10.212.51.133:8080 from neighboring node (worker-2) -> 404 page not found
```
Next add the first ciliumnetworkpolicy
```
kubectl get ciliumnetworkpolicies
pfm.auth.to-api   10s
```
```
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: pfm
      k8s:pfm.app: api
      k8s:pfm.project: pfm
      k8s:pfm.unit: pfm
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: pfm
        k8s:pfm.app: auth
        k8s:pfm.project: pfm
        k8s:pfm.unit: pfm
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
 ```
repeat the test
```
test-1) curl 10.212.51.133:8080 from node running under (worker-1) -> curl: (56) Recv failure: Connection timed out
test-2) curl 10.212.51.133:8080 from neighboring node (worker-2) -> 404 page not found
```
Service has identity 745797
->
```
kubectl get svc | grep api
api          ClusterIP   10.235.115.82    <none>        8080/TCP                                                    4d

cilium monitor | grep  745797
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 1733 flow 0x21441b78 , identity host->745797 state new ifindex 0 orig-ip 10.10.47.13: 10.10.47.13:43856 -> 10.212.51.133:8080 tcp SYN
-> stack flow 0xf0c842ea , identity 745797->host state reply ifindex 0 orig-ip 0.0.0.0: 10.212.51.133:8080 -> 10.10.47.13:43856 tcp SYN, ACK
xx drop (Policy denied) flow 0x21441b78 to endpoint 1733, , identity world->745797: 10.10.47.13:43856 -> 10.212.51.133:8080 tcp ACK
xx drop (Policy denied) flow 0x21441b78 to endpoint 1733, , identity world->745797: 10.10.47.13:43856 -> 10.212.51.133:8080 tcp ACK
```
and the fun is that
syn request arrives with host id
syn/ack from 745797 on identity host
ack - identical world->745797

why did my identity change from host to world on ACK?
Apparently, that's why my helchecks don't work. (edited) 

cilium config:
```
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  annotate-k8s-node: "true"
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-algorithm: random
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: snat
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "11"
  cluster-name: pfm-devcustomer
  cluster-pool-ipv4-cidr: 10.212.48.0/20
  cluster-pool-ipv4-mask-size: "25"
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-legacy-routing: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-event-handover: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "true"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-metrics: dns drop tcp flow icmp http
  hubble-metrics-server: :9091
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  ipv4-native-routing-cidr: 10.0.0.0/8
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  proxy-prometheus-port: "9095"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
  unmanaged-pod-watcher-interval: "15"
```

### Cilium Version

1.11.8
1.12.0

### Kernel Version

Linux pfm-dev-msk1-control1.i 5.7.12-1.el7.elrepo.x86_64 #1 SMP Fri Jul 31 16:18:28 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.1-dirty", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"dirty", BuildDate:"2022-01-12T17:56:35Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ernado** [comment] 2022-08-23 14:34
cc @shadowspore PTAL

**Comment by pchaigno** [comment] 2022-09-21 10:11
Could you please share a sysdump?

> why did my identity change from host to world on ACK?
> Apparently, that's why my helchecks don't work. (edited)

That seems weird indeed. Where are you making the requests from?

**Comment by ernado** [comment] 2022-09-21 10:43
@Dobry-kot please close this issue and open another one about iptables as we discussed.

@pchaigno this issue was caused by iptables configuration (on our side) that prevented tracking/tagging of cilium packets (so cilium iptables rule was not executed).

**Closed as completed** 2022-09-21 10:44 UTC
Labels: kind/bug, need-more-info, area/datapath, needs/triage, kind/community-report

**Comment by Dobry-kot** [comment] 2022-09-21 10:47
> Could you please share a sysdump?
> 
> > why did my identity change from host to world on ACK?
> > Apparently, that's why my helchecks don't work. (edited)
> 
> That seems weird indeed. Where are you making the requests from?


Found what the problem is.
This is due to the fact that your traffic is not marked in the mangle, which is why if the rule does not enter the CILIUM chain and does not mark the traffic, and then in hubble observe we see how the host/world blinks on the helchecks traffic.
I would like to see it at the moment.
