### ISSUE TITLE
k8s-1.11.K8sValidatedKafkaPolicyTest Kafka Policy Tests KafkaPolicies: DNS Failure

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4977] opened 2018-07-24 22:56 UTC
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5242/

```
Stacktrace
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Failed to produce to empire-hq on topic empire-announce
Expected
    <*errors.errorString | 0xc42030b980>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-749db985fb-csn7w sh -- -c \"echo 'Happy 40th Birthday to General Tagge' | ./kafka-produce.sh --topic empire-announce\"' failed '' || '[2018-07-24 19:59:06,572] WARN Removing server kafka-service:9092 from bootstrap.servers as DNS resolution failed for kafka-service (org.apache.kafka.clients.ClientUtils)\norg.apache.kafka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:416)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:288)\n\tat kafka.producer.NewShinyProducer.<init>(BaseProducer.scala:40)\n\tat kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:48)\n\tat kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)\nCaused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers\n\tat org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:373)\n\t... 4 more\ncommand terminated with exit code 1\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:172
Standard Output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: [cilium-96l2h cilium-gjkkl]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::cnp-second-namespace 
Endpoint Policy Enforcement:
     empire-outpost-9999-845f585bcd-s5qvf   =>   none
     kafka-broker-6f5f474db-ndcjx           =>   none
     zookeeper-ddbc5c98d-wz74z              =>   none
     cilium-health-k8s1                     =>   none
     cilium-health-k8s2                     =>   none
     coredns-78fcdf6894-x4ppj               =>   none
     empire-outpost-8888-84469c7b8b-29t6v   =>   none
     empire-hq-749db985fb-csn7w             =>   none
     coredns-78fcdf6894-mbgc8               =>   none
     prometheus-core-6546477dc8-j72pv       =>   none
     empire-backup-76dd5cbf7b-x4g5m         =>   none
Cilium agent "cilium-96l2h": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 28 Failed 0
Cilium agent "cilium-gjkkl": Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 55 Failed 0

Standard Error
STEP: Wait for Kafka broker to be up
STEP: Creating new kafka topic empire-announce
STEP: Creating new kafka topic deathstar-plans
STEP: Waiting for DNS to resolve within pods for kafka-service
STEP: Testing basic Kafka Produce and Consume
=== Test Finished at 2018-07-24T19:59:06Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE       IP              NODE
default       empire-backup-76dd5cbf7b-x4g5m         1/1       Running   0          1m        10.10.1.135     k8s2
default       empire-hq-749db985fb-csn7w             1/1       Running   0          1m        10.10.0.181     k8s1
default       empire-outpost-8888-84469c7b8b-29t6v   1/1       Running   0          1m        10.10.1.108     k8s2
default       empire-outpost-9999-845f585bcd-s5qvf   1/1       Running   0          1m        10.10.1.125     k8s2
default       kafka-broker-6f5f474db-ndcjx           1/1       Running   0          1m        10.10.0.246     k8s1
default       zookeeper-ddbc5c98d-wz74z              1/1       Running   0          1m        10.10.1.103     k8s2
kube-system   cilium-96l2h                           1/1       Running   0          28m       192.168.36.11   k8s1
kube-system   cilium-gjkkl                           1/1       Running   0          28m       192.168.36.12   k8s2
kube-system   coredns-78fcdf6894-mbgc8               1/1       Running   0          53m       10.10.1.61      k8s2
kube-system   coredns-78fcdf6894-x4ppj               1/1       Running   0          53m       10.10.1.69      k8s2
kube-system   etcd-k8s1                              1/1       Running   0          52m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running   0          52m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running   0          52m       192.168.36.11   k8s1
kube-system   kube-proxy-5gvfq                       1/1       Running   0          53m       192.168.36.11   k8s1
kube-system   kube-proxy-967lr                       1/1       Running   0          46m       192.168.36.12   k8s2
kube-system   kube-scheduler-k8s1                    1/1       Running   0          52m       192.168.36.11   k8s1
prometheus    prometheus-core-6546477dc8-j72pv       1/1       Running   0          46m       10.10.1.138     k8s2

cmd: kubectl exec -n kube-system cilium-96l2h -- cilium service list
ID   Frontend             Backend                   
1    10.96.0.1:443        1 => 192.168.36.11:6443   
2    10.96.0.10:53        1 => 10.10.1.61:53        
                          2 => 10.10.1.69:53        
3    10.99.190.231:9090   1 => 10.10.1.138:9090     
10   10.110.70.83:2181    1 => 10.10.1.103:2181     

cmd: kubectl exec -n kube-system cilium-96l2h -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                       
22162      Disabled           Disabled          4          reserved:health                                   f00d::a0a:0:0:5692   10.10.0.99    ready   
36205      Disabled           Disabled          62264      k8s:app=empire-hq                                 f00d::a0a:0:0:8d6d   10.10.0.181   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                      
                                                           k8s:zgroup=kafkaTestApp                                                                      
48245      Disabled           Disabled          51666      k8s:app=kafka                                     f00d::a0a:0:0:bc75   10.10.0.246   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                      
                                                           k8s:zgroup=kafkaTestApp                                                                      

cmd: kubectl exec -n kube-system cilium-gjkkl -- cilium service list
ID   Frontend             Backend                   
1    10.96.0.1:443        1 => 192.168.36.11:6443   
2    10.96.0.10:53        1 => 10.10.1.61:53        
                          2 => 10.10.1.69:53        
3    10.99.190.231:9090   1 => 10.10.1.138:9090     
10   10.110.70.83:2181    1 => 10.10.1.103:2181     

cmd: kubectl exec -n kube-system cilium-gjkkl -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                
336        Disabled           Disabled          46829      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:100:0:150    10.10.1.69    ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                           
                                                           k8s:k8s-app=kube-dns                                                                                  
1271       Disabled           Disabled          61612      k8s:app=empire-outpost                                   f00d::a0a:100:0:4f7    10.10.1.108   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:outpostid=8888                                                                                    
                                                           k8s:zgroup=kafkaTestApp                                                                               
23050      Disabled           Disabled          7021       k8s:app=zook                                             f00d::a0a:100:0:5a0a   10.10.1.103   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:zgroup=kafkaTestApp                                                                               
30674      Disabled           Disabled          46829      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:100:0:77d2   10.10.1.61    ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                           
                                                           k8s:k8s-app=kube-dns                                                                                  
39992      Disabled           Disabled          8494       k8s:app=empire-outpost                                   f00d::a0a:100:0:9c38   10.10.1.125   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:outpostid=9999                                                                                    
                                                           k8s:zgroup=kafkaTestApp                                                                               
55813      Disabled           Disabled          64110      k8s:app=prometheus                                       f00d::a0a:100:0:da05   10.10.1.138   ready   
                                                           k8s:component=core                                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                            
56542      Disabled           Disabled          54455      k8s:app=empire-backup                                    f00d::a0a:100:0:dcde   10.10.1.135   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:zgroup=kafkaTestApp                                                                               
64812      Disabled           Disabled          4          reserved:health                                          f00d::a0a:100:0:fd2c   10.10.1.47    ready   

===================== Existing AfterFailed =====================
```

[9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies (1).zip](https://github.com/cilium/cilium/files/2225738/9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.1.zip)

**Comment by ianvernon** [comment] 2018-07-25 16:19
Similar failure: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1288/testReport/junit/k8s-1/11/K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Output:
```
Stacktrace

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Failed to produce to empire-hq on topic empire-announce
Expected
    <*errors.errorString | 0xc4203afdc0>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-749db985fb-mr477 sh -- -c \"echo 'Happy 40th Birthday to General Tagge' | ./kafka-produce.sh --topic empire-announce\"' failed '' || '[2018-07-24 21:43:31,060] WARN Removing server kafka-service:9092 from bootstrap.servers as DNS resolution failed for kafka-service (org.apache.kafka.clients.ClientUtils)\norg.apache.kafka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:416)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:288)\n\tat kafka.producer.NewShinyProducer.<init>(BaseProducer.scala:40)\n\tat kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:48)\n\tat kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)\nCaused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers\n\tat org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:373)\n\t... 4 more\ncommand terminated with exit code 1\n'",
    }
to be nil
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:172
Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 10
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: [cilium-tqx4p cilium-wlhf6]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     empire-hq-749db985fb-mr477             =>   none
     empire-outpost-8888-84469c7b8b-xngdt   =>   none
     cilium-health-k8s1                     =>   
     prometheus-core-6546477dc8-5fx8g       =>   none
     empire-backup-76dd5cbf7b-wfzlm         =>   none
     empire-outpost-9999-845f585bcd-7xxq2   =>   none
     kafka-broker-6f5f474db-z5cvr           =>   none
     zookeeper-ddbc5c98d-rmrf6              =>   none
     cilium-health-k8s2                     =>   
     coredns-78fcdf6894-dw67g               =>   none
     coredns-78fcdf6894-v442p               =>   none
Cilium agent "cilium-tqx4p": Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 39 Failed 0
Cilium agent "cilium-wlhf6": Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 45 Failed 0

Standard Error

STEP: Wait for Kafka broker to be up
STEP: Creating new kafka topic empire-announce
STEP: Creating new kafka topic deathstar-plans
STEP: Waiting for DNS to resolve within pods for kafka-service
STEP: Testing basic Kafka Produce and Consume
=== Test Finished at 2018-07-24T21:43:32Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE       IP              NODE
default       empire-backup-76dd5cbf7b-wfzlm         1/1       Running   0          1m        10.10.1.241     k8s2
default       empire-hq-749db985fb-mr477             1/1       Running   0          1m        10.10.0.78      k8s1
default       empire-outpost-8888-84469c7b8b-xngdt   1/1       Running   0          1m        10.10.1.102     k8s2
default       empire-outpost-9999-845f585bcd-7xxq2   1/1       Running   0          1m        10.10.1.189     k8s2
default       kafka-broker-6f5f474db-z5cvr           1/1       Running   0          1m        10.10.1.57      k8s2
default       zookeeper-ddbc5c98d-rmrf6              1/1       Running   0          1m        10.10.1.215     k8s2
kube-system   cilium-tqx4p                           1/1       Running   0          4m        192.168.36.11   k8s1
kube-system   cilium-wlhf6                           1/1       Running   0          4m        192.168.36.12   k8s2
kube-system   coredns-78fcdf6894-dw67g               1/1       Running   0          10m       10.10.0.159     k8s1
kube-system   coredns-78fcdf6894-v442p               1/1       Running   0          10m       10.10.0.73      k8s1
kube-system   etcd-k8s1                              1/1       Running   0          10m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running   0          9m        192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running   0          10m       192.168.36.11   k8s1
kube-system   kube-proxy-pf9kg                       1/1       Running   0          4m        192.168.36.12   k8s2
kube-system   kube-proxy-ptszv                       1/1       Running   0          10m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                    1/1       Running   0          10m       192.168.36.11   k8s1
prometheus    prometheus-core-6546477dc8-5fx8g       1/1       Running   0          4m        10.10.0.77      k8s1

cmd: kubectl exec -n kube-system cilium-tqx4p -- cilium service list
ID   Frontend              Backend                   
1    10.106.240.203:9090   1 => 10.10.0.77:9090      
2    10.96.0.1:443         1 => 192.168.36.11:6443   
3    10.96.0.10:53         1 => 10.10.0.159:53       
                           2 => 10.10.0.73:53        
5    10.98.142.144:2181    1 => 10.10.1.215:2181     

cmd: kubectl exec -n kube-system cilium-tqx4p -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                              
17326      Disabled           Disabled          40605      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:0:0:43ae   10.10.0.73    ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                         
                                                           k8s:k8s-app=kube-dns                                                                                
25361      Disabled           Disabled          40605      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:0:0:6311   10.10.0.159   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                         
                                                           k8s:k8s-app=kube-dns                                                                                
28105      Disabled           Disabled          32502      k8s:app=prometheus                                       f00d::a0a:0:0:6dc9   10.10.0.77    ready   
                                                           k8s:component=core                                                                                  
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                              
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                          
28450      Disabled           Disabled          4          reserved:health                                          f00d::a0a:0:0:6f22   10.10.0.8     ready   
38733      Disabled           Disabled          47166      k8s:app=empire-hq                                        f00d::a0a:0:0:974d   10.10.0.78    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                     
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=kafkaTestApp                                                                             

cmd: kubectl exec -n kube-system cilium-wlhf6 -- cilium service list
ID   Frontend              Backend                   
1    10.96.0.1:443         1 => 192.168.36.11:6443   
2    10.96.0.10:53         1 => 10.10.0.159:53       
                           2 => 10.10.0.73:53        
3    10.106.240.203:9090   1 => 10.10.0.77:9090      
5    10.98.142.144:2181    1 => 10.10.1.215:2181     

cmd: kubectl exec -n kube-system cilium-wlhf6 -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                         
2592       Disabled           Disabled          4          reserved:health                                   f00d::a0a:100:0:a20    10.10.1.107   ready   
2769       Disabled           Disabled          44891      k8s:app=empire-outpost                            f00d::a0a:100:0:ad1    10.10.1.102   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                        
                                                           k8s:outpostid=8888                                                                             
                                                           k8s:zgroup=kafkaTestApp                                                                        
17263      Disabled           Disabled          32379      k8s:app=zook                                      f00d::a0a:100:0:436f   10.10.1.215   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                        
                                                           k8s:zgroup=kafkaTestApp                                                                        
20179      Disabled           Disabled          63654      k8s:app=kafka                                     f00d::a0a:100:0:4ed3   10.10.1.57    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                        
                                                           k8s:zgroup=kafkaTestApp                                                                        
22794      Disabled           Disabled          13859      k8s:app=empire-backup                             f00d::a0a:100:0:590a   10.10.1.241   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                        
                                                           k8s:zgroup=kafkaTestApp                                                                        
58508      Disabled           Disabled          51107      k8s:app=empire-outpost                            f00d::a0a:100:0:e48c   10.10.1.189   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                        
                                                           k8s:outpostid=9999                                                                             
                                                           k8s:zgroup=kafkaTestApp  
```

Logs: 
[9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2228665/9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by joestringer** [comment] 2018-07-25 16:39
Noticed this warning log several times in the log over the period of about 5 minutes, not sure if it's relevant:

```
2018-07-24T21:39:52.683152499Z level=warning msg="Unable to add ipcache entry of Kubernetes node" error="no/invalid Cilium-Host IP for host 192.168.36.12: "
...
2018-07-24T21:44:27.377062065Z level=warning msg="Unable to update ipcache entry of Kubernetes node" error="no/invalid Cilium-Host IP for host 192.168.36.12: "
```

Filed #4989 to investigate in case it's unrelated. It was only seen in the dump from Ian's post above, not in the dump from the issue description.

**Comment by eloycoto** [comment] 2018-07-25 23:21
Another DNS failure found: 


https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1304/testReport/junit/k8s-1/11/K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running/

[f0c5341e_K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running(3).zip](https://github.com/cilium/cilium/files/2229852/f0c5341e_K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running.3.zip)

**Comment by eloycoto** [comment] 2018-07-25 23:29
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1305/testReport/junit/k8s-1/11/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

[f0c5341e_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies(1).zip](https://github.com/cilium/cilium/files/2229867/f0c5341e_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.1.zip)

**Comment by ianvernon** [comment] 2018-07-27 21:30
Let's see if this reproduces with branches / master builds that include #5001 .

**Comment by ianvernon** [comment] 2018-08-01 20:08
@eloycoto can we close? This issue hasn't reproduced since #5001 has been merged.

**Closed as completed** 2018-08-01 20:23 UTC
Labels: need-more-info, area/CI
