### ISSUE TITLE
L4 policies need FromEndpoints to work correctly

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2204] opened 2017-12-01 18:24 UTC
If you specified an L4 Policy and you don't specify the L3 FromEndpoints the connectivity with them will not work correctly. 

Policy.json
```
{
  "apiVersion": "cilium.io/v2",
  "kind": "CiliumNetworkPolicy",
  "metadata": {
    "name": "4d088f48",
    "test": "L3:No Policy L4:Ingress Port 80 TCP L7:No Policy"
  },
  "specs": [
    {
      "EndpointSelector": {
        "matchlabels": {
          "id": "4d088f48-d04ab55f"
        }
      },
      "Ingress": [
        {
          "ToPorts": [
            {
              "Ports": [
                {
                  "port": "80",
                  "protocol": "TCP"
                }
              ]
            }
          ]
        }
      ],
      "Egress": null
    }
  ]
}
```

The `policy trace` looks good but the connectivity is not working

Logs: 

[endpoint_list.txt](https://github.com/cilium/cilium/files/1522515/endpoint_list.txt)
[monitor.txt](https://github.com/cilium/cilium/files/1522516/monitor.txt)
[trace.txt](https://github.com/cilium/cilium/files/1522517/trace.txt)
[pods_yaml.txt](https://github.com/cilium/cilium/files/1522520/pods_yaml.txt)
[policy_json.txt](https://github.com/cilium/cilium/files/1522521/policy_json.txt)

**Comment by manalibhutiyani** [comment] 2017-12-01 18:37
In addition:

We always  need an fromEndpoint in the policy. Just specifying L4 policy like toPorts does not imply that L3 will allow all L3 traffic.
This can be bypassed by putting an empty fromEndpoint L3 rule.

For example:
Just with toPorts rule and no fromEndpoints:

```
root@k8s2:/# cilium monitor --related-to 53828             
Listening for events on 2 CPUs with 64x4096 of shared memory                                                          
Press Ctrl-C to quit         
xx drop (Policy denied (L3)), to endpoint 53828, identity 400->399: 10.10.1.251:55668 -> 10.10.1.6:80 tcp SYN         
xx drop (Policy denied (L3)), to endpoint 53828, identity 400->399: 10.10.1.251:55668 -> 10.10.1.6:80 tcp SYN         
xx drop (Policy denied (L3)), to endpoint 53828, identity 400->399: 10.10.1.251:55668 -> 10.10.1.6:80 tcp SYN   
```

But the policy trace shows that this should actually we allowed:


```
root@k8s2:/# cilium policy trace --src-identity 400 --dst-identity 399 --dport 80
----------------------------------------------------------------
Tracing From: [k8s:id=4d088f48-83e4f98d, k8s:io.kubernetes.pod.namespace=default, k8s:zgroup=4d088f48] => To: [k8s:zgroup=4d088f48, k8s:id=4d088f48-d04ab55f, k8s:io.kubernetes.pod.namespace=default] Ports: [80/ANY]
* Rule {"matchLabels":{"any:id":"4d088f48-d04ab55f","k8s:io.kubernetes.pod.namespace":"default"}}: selected
1/5 rules selected
Found no allow rule
Label verdict: undecided

Resolving egress port policy for [k8s:id=4d088f48-83e4f98d k8s:io.kubernetes.pod.namespace=default k8s:zgroup=4d088f48]
0/5 rules selected
Found no allow rule
L4 egress verdict: undecided

Resolving ingress port policy for [k8s:zgroup=4d088f48 k8s:id=4d088f48-d04ab55f k8s:io.kubernetes.pod.namespace=default]
* Rule {"matchLabels":{"any:id":"4d088f48-d04ab55f","k8s:io.kubernetes.pod.namespace":"default"}}: selected
    Allows Ingress port [{80 TCP}]
      Found all required labels
1/5 rules selected
Found allow rule
L4 ingress verdict: allowed

Final verdict: ALLOWED
```
There is a discrepancy in what the policy trace reports and whether the L3 traffic being is actually being allowed or denied. The tool also needs to be looked into(the verdict and actual behavior should be consistent), if we need to fix something there, or just fix the current L3 denial behavior to the correct one.


We can bypass this by adding something like:
```
"ingress": [{
        "fromEndpoints": [
            {}
        ]
    }]
```

This will then allow all L3 traffic and the decision to deny/allow will then depend on the L4 rule.

**Comment by joestringer** [comment] 2017-12-04 18:04
This is a duplicate of #1955.

**Closed as completed** 2018-01-10 09:32 UTC
Labels: kind/bug, sig/policy
