### ISSUE TITLE
Cilium segfaults with --enable-l7-proxy=false

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#18773] opened 2022-02-10 19:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A user reports that Cilium hit a segfault when the l7 proxy was disabled.

### Cilium Version

1.11.1

### Kernel Version

n/a

### Kubernetes Version

n/a

### Relevant log output

```shell
[cilium-ptl2k cilium-agent] panic: runtime error: invalid memory address or nil pointer dereference
[cilium-ptl2k cilium-agent] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f6243c]
[cilium-ptl2k cilium-agent]
[cilium-ptl2k cilium-agent] goroutine 887 [running]:
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/proxy.(*Proxy).CreateOrUpdateRedirect(0x0, {0x2c53a30, 0xc00013bf00}, {0xc0044ae750, 0x4}, {0x2cb2e30, 0xc0009ac380}, 0xc0020f3fc0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kimeirik-crayon** [comment] 2022-02-10 19:59
Deployed with this values.yaml with helm, single node.

(intentionally garbled some ipv6 addresses in the copy/paste.)
`bpf:
  hostRouting: false
  lbBypassFIBLookup: false
  lbExternalClusterIP: true
  masquerade: false
  tproxy: true
cluster:
  id: 1
  name: brg-k3s
containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock
devices: enp1s0f0
enableIPv4Masquerade: false
enableIPv6Masquerade: false
externalIPs:
  enabled: true
extraConfig:
  enable-endpoint-routes: "true"
  enable-local-node-route: "false"
  enable-node-port: "true"
  ipv4-node: 10.13.100.11
  ipv4-service-range: 10.13.208.0/20
  ipv6-node: 2a0e:xxxx::11
  ipv6-service-range: 2a0e:xxxxxxxx::/108
  node-port-algorithm: random
  node-port-mode: dsr
  node-port-acceleration: native
  bpf-lb-acceleration: native
  enable-xdp-prefilter: "true"
  enable-icmp-rules: "true"
fragmentTracking: true
hostPort:
  enabled: "true"
hostServices:
  enabled: "true"
  protocols: tcp,udp
installIptablesRules: true
installNoConntrackIptablesRules: false
ipMasqAgent:
  enabled: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList:
    - 10.13.192.0/20
    clusterPoolIPv6MaskSize: 112
    clusterPoolIPv6PodCIDRList:
    - 2a0e:xxxxxx14::/112
    - 2a0e:xxxxxx14::1:0/112
    - 2a0e:xxxxxx14::2:0/112
ipv4:
  enabled: true
ipv6:
  enabled: true
k8sServiceHost: "api.k3s.local"
k8sServicePort: "6443"
kubeProxyReplacement: strict
l2NeighDiscovery:
  enabled: false
l7Proxy: true
loadBalancer:
  algorithm: random
  mode: dsr
localRedirectPolicy: false
nodePort:
  enabled: "true"
operator:
  replicas: 1
sessionAffinity: "true"
tunnel: disabled
image:
  repository: "quay.io/cilium/cilium"
  tag: "v1.11.1"
  useDigest: false
hubble:
  listenAddress: ":4244"
  relay:
    enabled: true
  ui:
    enabled: true`


the "full" stacktrace with some pretext also:

`[cilium-ptl2k cilium-agent] level=info msg="Restored endpoint" endpointID=3462 ipAddr="[10.13.192.217 2a0e:97c0:250:14::b6bb]" subsys=endpoint
[cilium-ptl2k cilium-agent] level=info msg="Rewrote endpoint BPF program" containerID=fa6a2b2bb9 datapathPolicyRevision=0 desiredPolicyRevision=65 endpointID=2189 identity=92217 ipv4=10.13.192.232 ipv6="2a0e:97c0:250:14::8ee7" k8sPodName=kube-system/hubble-ui-7c6789876c-cz7qq subsys=endpoint
[hubble-relay-85664d47c4-8x2pb] level=warning msg="Error while receiving peer change notification; will try again after the timeout has expired" connection timeout=30s error="rpc error: code = Unavailable desc = error reading from server: EOF" subsys=hubble-relay
[cilium-ptl2k cilium-agent] level=info msg="Restored endpoint" endpointID=2189 ipAddr="[10.13.192.232 2a0e:97c0:250:14::8ee7]" subsys=endpoint
[cilium-ptl2k cilium-agent] level=info msg="Rewrote endpoint BPF program" containerID=29402ba7d7 datapathPolicyRevision=0 desiredPolicyRevision=65 endpointID=740 identity=66382 ipv4=10.13.192.24 ipv6="2a0e:97c0:250:14::7927" k8sPodName=kube-system/hubble-relay-85664d47c4-8x2pb subsys=endpoint
[cilium-ptl2k cilium-agent] level=info msg="Restored endpoint" endpointID=740 ipAddr="[10.13.192.24 2a0e:97c0:250:14::7927]" subsys=endpoint
[cilium-ptl2k cilium-agent] level=info msg="Rewrote endpoint BPF program" containerID=ef2919a30d datapathPolicyRevision=0 desiredPolicyRevision=65 endpointID=311 identity=104767 ipv4=10.13.192.133 ipv6="2a0e:97c0:250:14::3ffb" k8sPodName=dns-recursive/recursive-dns-0 subsys=endpoint
[cilium-ptl2k cilium-agent] level=info msg="Restored endpoint" endpointID=311 ipAddr="[10.13.192.133 2a0e:97c0:250:14::3ffb]" subsys=endpoint
[cilium-ptl2k cilium-agent] panic: runtime error: invalid memory address or nil pointer dereference
[cilium-ptl2k cilium-agent] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f6243c]
[cilium-ptl2k cilium-agent]
[cilium-ptl2k cilium-agent] goroutine 887 [running]:
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/proxy.(*Proxy).CreateOrUpdateRedirect(0x0, {0x2c53a30, 0xc00013bf00}, {0xc0044ae750, 0x4}, {0x2cb2e30, 0xc0009ac380}, 0xc0020f3fc0)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/proxy/proxy.go:388 +0x9c
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addVisibilityRedirects(0xc0009ac380, 0x1, 0x27db1bd, 0x6)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:384 +0x439
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addNewRedirects(0xc0009ac380, 0x4179ab)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:470 +0x3c7
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc0009ac380, 0xc0011b9c00)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:834 +0x447
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc0009ac380, 0xc0011b9c00)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:584 +0x19d
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0009ac380, 0xc0011b9c00)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:405 +0x7b3
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0011b16f0, 0x85)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x32c
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x13b
[cilium-ptl2k cilium-agent] sync.(*Once).doSlow(0xffffffffffffff38, 0x0)
[cilium-ptl2k cilium-agent] 	/usr/local/go/src/sync/once.go:68 +0xd2
[cilium-ptl2k cilium-agent] sync.(*Once).Do(...)
[cilium-ptl2k cilium-agent] 	/usr/local/go/src/sync/once.go:59
[cilium-ptl2k cilium-agent] github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0x0)
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:233 +0x45
[cilium-ptl2k cilium-agent] created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
[cilium-ptl2k cilium-agent] 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:229 +0x7b`

**Comment by kimeirik-crayon** [comment] 2022-02-11 07:50
No L7 policies:
``` 
root@k3s01:~# kubectl get ciliumclusterwidenetworkpolicy --all-namespaces -oyaml | grep -i rules
root@k3s01:~# kubectl get ciliumnetworkpolicy --all-namespaces -oyaml | grep -i rules
root@k3s01:~#
```

**Comment by ksekharben** [comment] 2022-03-04 12:35
Hello ,
While investigating this issue, I am unable to reproduce the above error. Please find my values.yaml.

 git diff values.yaml
diff --git a/install/kubernetes/cilium/values.yaml b/install/kubernetes/cilium/values.yaml
index b7dd50ab5b..a4bc3a961f 100644
--- a/install/kubernetes/cilium/values.yaml
+++ b/install/kubernetes/cilium/values.yaml
@@ -85,7 +85,7 @@ rollOutCiliumPods: false
 # -- Agent container image.
 image:
   repository: quay.io/cilium/cilium
-  tag: latest
+  tag: v1.9.13
   pullPolicy: Always
   # cilium-digest
   digest: ""
@@ -1070,7 +1070,7 @@ l2NeighDiscovery:
   arping-refresh-period: "30s"

 # -- Enable Layer 7 network policy.
-l7Proxy: true
+l7Proxy: false

 # -- Enable Local Redirect Policy.
 localRedirectPolicy: false
@@ -1410,8 +1410,8 @@ operator:

   # -- cilium-operator image.
   image:
-    repository: quay.io/cilium/operator
-    tag: latest
+    repository: quay.io/cilium/operator-generic
+    tag: v1.9.13
     # operator-generic-digest
     genericDigest: ""
     # operator-azure-digest
@@ -1603,7 +1603,7 @@ preflight:
   # -- Cilium pre-flight image.
   image:
     repository: quay.io/cilium/cilium
-    tag: latest
+    tag: v1.9.12
     # cilium-digest
     digest: ""
     useDigest: false

Can you please help me here to reproduce the issue.

**Comment by ksekharben** [comment] 2022-03-04 12:39
Hello Team,

I am looking to this issue. I have disabled the l7proxy in values.yaml . But unable to reproduce this issue. Can someone please help me to reproduce this issue. Please find below .

` -1070,7 +1070,7 @@ l2NeighDiscovery:
   arping-refresh-period: "30s"

 # -- Enable Layer 7 network policy.
-l7Proxy: true
+l7Proxy: false

`

**Comment by joestringer** [comment] 2022-03-04 20:18
@ksekharben thanks for trying it out. Which version of Cilium did you deploy? The report above seems to be for 1.11.1.

**Comment by Preisschild** [comment] 2022-03-05 16:09
I can reproduce on 1.11.2 as well

```
level=info msg="Restored endpoint" endpointID=3307 ipAddr="[10.244.2.93 ]" subsys=endpoint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x215825c]

goroutine 881 [running]:
github.com/cilium/cilium/pkg/proxy.(*Proxy).CreateOrUpdateRedirect(0x0, {0x2ece3b0, 0xc00169b020}, {0xc003aeb278, 0x4}, {0x2f2e170, 0xc0002c4700}, 0xc001fa9640)
	/go/src/github.com/cilium/cilium/pkg/proxy/proxy.go:388 +0x9c
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addVisibilityRedirects(0xc0002c4700, 0x1, 0x2a271e9, 0x6)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:384 +0x439
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addNewRedirects(0xc0002c4700, 0xc000181a40)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:470 +0x3c7
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc0002c4700, 0xc00122c400)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:834 +0x447
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc0002c4700, 0xc00122c400)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:584 +0x19d
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0002c4700, 0xc00122c400)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:405 +0x7b3
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc00048c660, 0x4058ea)
	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x32c
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x13b
sync.(*Once).doSlow(0x1, 0x43f585)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0x0)
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:233 +0x45
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:229 +0x7b
```

**Comment by ksekharben** [comment] 2022-03-09 05:06
I have tested with both cilium 1.11.1 and 1.11.2. But unable to reproduce this issue.

kindly let me know any changes required to reproduce the above issue.

I am using helm install for cilium installation.

I have set  the l7proxy value to false in values.yaml to reproduce this issue.

**Comment by Preisschild** [comment] 2022-03-09 06:28
my values.yaml

```yaml
    ipam:
      mode: kubernetes
    kubeProxyReplacement: strict
    k8sServiceHost: "10.0.0.91"
    k8sServicePort: 6443
    l7Proxy: false
    encryption:
      enabled: true
      type: wireguard
```

**Comment by gandro** [comment] 2022-03-09 09:43
@Preisschild Do you have any visibility annotations on your pods? https://docs.cilium.io/en/stable/policy/visibility/

**Comment by ksekharben** [comment] 2022-03-09 10:30
@gandro Are you working on this fix ?

**Comment by gandro** [comment] 2022-03-09 12:43
> @gandro Are you working on this fix ?

Yes, check #19092

**Comment by gandro** [comment] 2022-04-13 15:38
I currently don't have cycles for this. Unassigning. It seems like the fix requires more than just a simple nil check.

**Comment by ti-mo** [comment] 2023-06-21 19:34
Ping, looks like this is still relevant.

**Comment by sayboras** [comment] 2023-08-23 22:09
this issue should be fixed as part of the below PR

https://github.com/cilium/cilium/pull/27597#event-10169729727.

**Closed as completed by sayboras** 2023-08-23 22:09 UTC
Labels: kind/bug, area/proxy, pinned, area/agent
