### ISSUE TITLE
CI: v1.7: Travis, pkg/proxy unit test failing with runtime error

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#13293] opened 2020-09-25 14:16 UTC
Failure observed in #13292, occuring on 1.7 branch (that pull request doesn't modify affected package).

https://travis-ci.com/github/cilium/cilium/builds/186643771

```
=== RUN   Test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1805e8e]
goroutine 8 [running]:
sync.(*RWMutex).RLock(...)
	/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/sync/rwmutex.go:48
github.com/cilium/cilium/pkg/identity/cache.(*localIdentityCache).lookupByID(0x0, 0xc0000003e8, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/local.go:170 +0x3e
github.com/cilium/cilium/pkg/identity/cache.(*CachingIdentityAllocator).LookupIdentityByID(0xc0000d70e0, 0x2155cc0, 0xc0000d0018, 0x3e8, 0x10)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/cache.go:248 +0x90
github.com/cilium/cilium/pkg/proxy.(*defaultEndpointInfoRegistry).FillEndpointIdentityByID(0x31a1500, 0x3e8, 0xc0000343d0, 0xc000056b50)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/epinfo.go:50 +0x57
github.com/cilium/cilium/pkg/proxy/logger.(*LogRecord).fillIngressSourceInfo(0xc000034380, 0xc0000343d0, 0xc000698d60, 0x3e8)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/logger/logger.go:161 +0x74
github.com/cilium/cilium/pkg/proxy/logger.logTags.Addressing.func1(0xc000034380)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/logger/logger.go:238 +0x2db
github.com/cilium/cilium/pkg/proxy/logger.(*LogRecord).ApplyTags(0xc000034380, 0xc000698e60, 0x1, 0x1)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/logger/logger.go:290 +0x49
github.com/cilium/cilium/pkg/proxy.(*kafkaRedirect).handleRequest(0xc000362f90, 0xc0002b6cc0, 0xc00026b890, 0xc0002c0080, 0x211ea20, 0xc0002b6c90, 0x3e8, 0xc000056790, 0xf)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/kafka.go:316 +0x3dd
github.com/cilium/cilium/pkg/proxy.(*kafkaRedirect).handleRequests(0xc000362f90, 0xc0000b3800, 0xc0002b6cc0, 0xc0002c0000, 0xc000699e70)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/kafka.go:443 +0x752
github.com/cilium/cilium/pkg/proxy.(*kafkaRedirect).handleRequestConnection(0xc000362f90, 0xc0002b6cc0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/kafka.go:498 +0x1ee
created by github.com/cilium/cilium/pkg/proxy.(*kafkaListener).Listen
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/proxy/kafka.go:130 +0x922
FAIL	github.com/cilium/cilium/pkg/proxy	0.049s
FAIL
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

**Comment by mrostecki** [comment] 2020-09-25 14:28
Closing. Apparently I can't reproduce it on v1.7 branch, only on my backport PR.

**Closed as completed by mrostecki** 2020-09-25 14:28 UTC
Labels: area/CI, ci/flake
