### ISSUE TITLE
Unable to install Cilium on GKE 1.24

### ISSUE THREAD

**Issue by upodroid** [cilium/cilium#21165] opened 2022-09-01 12:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm unable to install cilium and it seems the flags provided by Helm break the nodes.

```
helm install cilium cilium/cilium --version 1.12.1 \
  --namespace kube-system \
  --set nodeinit.enabled=true \
  --set nodeinit.reconfigureKubelet=true \
  --set nodeinit.removeCbrBridge=true \
  --set cni.binPath=/home/kubernetes/bin \
  --set gke.enabled=true \
  --set ipam.mode=kubernetes \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set ipv4NativeRoutingCIDR=10.200.192.0/18
```

```
 REDACTED  MCW0CDP3YY  tmp  $  kg nodes
W0901 13:13:32.602478   50028 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME                         STATUS     ROLES    AGE     VERSION
gke-dev-main-0806e16a-06d7   NotReady   <none>   8m46s   v1.24.2-gke.1900
gke-dev-main-0806e16a-4sjg   NotReady   <none>   8m44s   v1.24.2-gke.1900
gke-dev-main-19ccc9b4-p0b7   NotReady   <none>   8m47s   v1.24.2-gke.1900
gke-dev-main-19ccc9b4-z116   NotReady   <none>   8m49s   v1.24.2-gke.1900
```

```
 REDACTED  MCW0CDP3YY  tmp  $  kg po -o wide -n kube-system | grep cilium
W0901 13:15:01.806292   50065 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
cilium-4s99g                             0/1     Init:0/5            0          4m17s   10.100.0.21   gke-dev-main-19ccc9b4-p0b7   <none>           <none>
cilium-8c5c5                             0/1     Init:0/5            0          4m16s   10.100.0.23   gke-dev-main-0806e16a-06d7   <none>           <none>
cilium-fk4zg                             0/1     Init:0/5            0          4m17s   10.100.0.18   gke-dev-main-19ccc9b4-z116   <none>           <none>
cilium-node-init-6xnnl                   0/1     ContainerCreating   0          4m18s   10.100.0.18   gke-dev-main-19ccc9b4-z116   <none>           <none>
cilium-node-init-lqbn9                   0/1     ContainerCreating   0          4m18s   10.100.0.22   gke-dev-main-0806e16a-4sjg   <none>           <none>
cilium-node-init-vdnzj                   0/1     ContainerCreating   0          4m18s   10.100.0.21   gke-dev-main-19ccc9b4-p0b7   <none>           <none>
cilium-node-init-zs2j4                   0/1     ContainerCreating   0          4m18s   10.100.0.23   gke-dev-main-0806e16a-06d7   <none>           <none>
cilium-operator-6f5c6f768d-zqwf6         1/1     Running             0          4m18s   10.100.0.23   gke-dev-main-0806e16a-06d7   <none>           <none>
cilium-t8mz6                             0/1     Init:1/5            0          4m18s   10.100.0.22   gke-dev-main-0806e16a-4sjg   <none>           <none>
```

```
 REDACTED  MCW0CDP3YY  tmp  $  kg node gke-dev-main-19ccc9b4-z116 -o yaml | yq '.status.conditions | .[] | select(.status == "True" or .status == "Unknown")'
W0901 13:21:36.942178   50349 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
lastHeartbeatTime: "2022-09-01T12:19:54Z"
lastTransitionTime: "2022-09-01T12:14:52Z"
message: Found 23 matching logs, which meets the threshold of 5
reason: FrequentContainerdRestart
status: "True"
type: FrequentContainerdRestart
lastHeartbeatTime: "2022-09-01T12:19:54Z"
lastTransitionTime: "2022-09-01T12:14:50Z"
message: Found 23 matching logs, which meets the threshold of 5
reason: FrequentKubeletRestart
status: "True"
type: FrequentKubeletRestart
lastHeartbeatTime: "2022-09-01T12:10:20Z"
lastTransitionTime: "2022-09-01T12:11:23Z"
message: Kubelet stopped posting node status.
reason: NodeStatusUnknown
status: Unknown
type: MemoryPressure
lastHeartbeatTime: "2022-09-01T12:10:20Z"
lastTransitionTime: "2022-09-01T12:11:23Z"
message: Kubelet stopped posting node status.
reason: NodeStatusUnknown
status: Unknown
type: DiskPressure
lastHeartbeatTime: "2022-09-01T12:10:20Z"
lastTransitionTime: "2022-09-01T12:11:23Z"
message: Kubelet stopped posting node status.
reason: NodeStatusUnknown
status: Unknown
type: PIDPressure
lastHeartbeatTime: "2022-09-01T12:10:20Z"
lastTransitionTime: "2022-09-01T12:11:23Z"
message: Kubelet stopped posting node status.
reason: NodeStatusUnknown
status: Unknown
type: Ready
```

```
 REDACTED  MCW0CDP3YY  tmp  $  cilium status
level=warning msg="WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead." subsys=klog
level=warning msg="To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke" subsys=klog
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         1 errors, 4 warnings
 \__/¯¯\__/    Operator:       1 errors
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        cilium-operator    Desired: 1, Unavailable: 1/1
DaemonSet         cilium             Desired: 4, Unavailable: 4/4
Containers:       cilium             Pending: 4
                  cilium-operator    Running: 1
Cluster Pods:     0/5 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.12.1@sha256:ea2db1ee21b88127b5c18a96ad155c25485d0815a667ef77c2b7c7f31cab601b: 4
                  cilium-operator    quay.io/cilium/operator-generic:v1.12.1@sha256:93d5aaeda37d59e6c4325ff05030d7b48fabde6576478e3fdbfb9bb4a68ec4a1: 1
Errors:           cilium-operator    cilium-operator    1 pods of Deployment cilium-operator are not ready
                  cilium             cilium             4 pods of DaemonSet cilium are not ready
Warnings:         cilium             cilium-t8mz6       pod is pending
                  cilium             cilium-4s99g       pod is pending
                  cilium             cilium-8c5c5       pod is pending
                  cilium             cilium-fk4zg       pod is pending
```

### Cilium Version

``` 
REDACTED  MCW0CDP3YY  tmp  $  cilium version
level=warning msg="WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead." subsys=klog
level=warning msg="To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke" subsys=klog
cilium-cli: v0.12.2 compiled with go1.19 on darwin/amd64
cilium image (default): v1.12.1
cilium image (stable): v1.12.1
cilium image (running): v1.12.1
```

### Kernel Version

Managed Nodes

### Kubernetes Version

```
 REDACTED  MCW0CDP3YY  tmp  $  k version
W0901 13:12:19.990707   49964 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2-gke.1900", GitCommit:"d95ef8792724f6b489a64fe5c7d8f1fb3f9422bb", GitTreeState:"clean", BuildDate:"2022-07-15T09:24:44Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by upodroid** [comment] 2022-09-01 12:53
Cilium deploys nicely on GKE 1.23

```
 REDACTED  MCW0CDP3YY  tmp  $  cilium status
level=warning msg="WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead." subsys=klog
level=warning msg="To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke" subsys=klog
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 4, Ready: 4/4, Available: 4/4
Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:       cilium             Running: 4
                  hubble-relay       Running: 1
                  hubble-ui          Running: 1
                  cilium-operator    Running: 2
Cluster Pods:     8/8 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.12.1@sha256:ea2db1ee21b88127b5c18a96ad155c25485d0815a667ef77c2b7c7f31cab601b: 4
                  hubble-relay       quay.io/cilium/hubble-relay:v1.12.1@sha256:646582b22bf41ad29dd7739b12aae77455ee5757b9ee087f2d45d684afef5fa1: 1
                  hubble-ui          quay.io/cilium/hubble-ui:v0.9.1@sha256:baff611b975cb12307a163c0e547e648da211384eabdafd327707ff2ec31cc24: 1
                  hubble-ui          quay.io/cilium/hubble-ui-backend:v0.9.1@sha256:c4b86e0d7a38d52c6ea3d9d7b17809e5212efd97494e8bd37c8466ddd68d42d0: 1
                  cilium-operator    quay.io/cilium/operator-generic:v1.12.1@sha256:93d5aaeda37d59e6c4325ff05030d7b48fabde6576478e3fdbfb9bb4a68ec4a1: 2
 REDACTED  MCW0CDP3YY  tmp  $  k version
W0901 13:53:07.278849   52247 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7-gke.1400", GitCommit:"3cdaae9a00a0ebd5b6fe15279d5da23ced7d85ba", GitTreeState:"clean", BuildDate:"2022-06-14T09:26:54Z", GoVersion:"go1.17.10b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aanm** [comment] 2022-09-01 13:02
Duplicate of https://github.com/cilium/cilium/issues/21049

**Closed as not planned** 2022-09-01 13:03 UTC
Labels: kind/bug, needs/triage

**Comment by upodroid** [comment] 2022-09-01 13:26
Thanks, it wasn't clear how 21049 is linked to this issue.

![image](https://user-images.githubusercontent.com/25100905/187925178-ba393653-fe1f-45bf-b148-7b05ceff9a60.png)

On a sidenote, I need to complain to Google about their log severities.
