### ISSUE TITLE
CI: Conformance AKS  - check-log-errors - EndpointPolicyVisibilityEvent event failed

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#31009] opened 2024-02-27 14:25 UTC
## CI failure

Hit on https://github.com/cilium/cilium/pull/30998
Link: https://github.com/cilium/cilium/actions/runs/8062340743/job/22021880556
Sysdump: [cilium-sysdump-final-1.27-eastus2-3-true.zip](https://github.com/cilium/cilium/files/14420955/cilium-sysdump-final-1.27-eastus2-3-true.zip)

```
❌ Found 2 logs in cilium-cilium-8062340743-1-3/kube-system/cilium-mq98p (cilium-agent) matching list of errors that must be investigated:
level=error msg="EndpointNoTrackEvent event failed" ciliumEndpointName=kube-system/hubble-relay-d5b87984f-qhh46 containerID=69963737e3 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=710 error="pod.core \"hubble-relay-d5b87984f-qhh46\" not found" identity=445 ipv4=10.0.1.110 ipv6= k8sPodName=kube-system/hubble-relay-d5b87984f-qhh46 subsys=endpoint (1 occurrences)
level=error msg="EndpointPolicyVisibilityEvent event failed" ciliumEndpointName=kube-system/hubble-relay-d5b87984f-qhh46 containerID=69963737e3 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=710 error="pod.core \"hubble-relay-d5b87984f-qhh46\" not found" identity=445 ipv4=10.0.1.110 ipv6= k8sPodName=kube-system/hubble-relay-d5b87984f-qhh46 subsys=endpoint (1 occurrences)
```

**Comment by tommyp1ckles** [comment] 2024-03-04 22:29
There's a couple similar such EKS (+maybe AKS?) issues going on.  I believe they're caused by incomplete cleanup between cilium installs.  Waiting for a cilium-cli release to fix with this: https://github.com/cilium/cilium-cli/pull/2344

**Comment by tommyp1ckles** [comment] 2024-03-11 05:26
Haven't seen this failure in recent runs, closing as done for now unless it comes up again.

**Closed as completed** 2024-03-11 05:26 UTC
Labels: area/CI, ci/flake
