### ISSUE TITLE
Frequent Pod Unavailability Due to ICMPv4 Destination Unreachable (CommAdminProhibited) Errors

### ISSUE THREAD

**Issue by siddjellali** [cilium/cilium#29344] opened 2023-11-23 07:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am experiencing frequent pod unavailability in my Kubernetes cluster, and after running the hubble observe command, I observed a series of ICMPv4 Destination Unreachable errors with the code "CommAdminProhibited". This issue is impacting the communication between pods, leading to disruptions in the cluster.

### Cilium Version

```
cilium-cli: v0.15.14 compiled with go1.21.4 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.4
cilium image (running): 1.14.4
```

### Kernel Version

`Linux k8s02 5.14.0-362.8.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 8 17:36:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`

### Kubernetes Version

```
# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8", GitCommit:"66fee42707cd7f5a89f1987f7cb81b02dd19161c", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:09Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}

```

### Sysdump

[cilium-sysdump-20231123-080530.zip](https://github.com/cilium/cilium/files/13446866/cilium-sysdump-20231123-080530.zip)

### Relevant log output

```shell
Nov 23 07:03:59.195: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Nov 23 07:04:00.240: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Nov 23 07:04:00.746: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Nov 23 07:04:01.776: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Nov 23 07:04:02.288: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Nov 23 07:04:03.824: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Nov 23 07:04:04.177: 192.168.252.11 (host) <> 192.168.252.13 (remote-node) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
```

### Anything else?

```
# firewall-cmd --get-icmptypes
address-unreachable bad-header beyond-scope communication-prohibited destination-unreachable echo-reply echo-request failed-policy fragmentation-needed host-precedence-violation host-prohibited host-redirect host-unknown host-unreachable ip-header-bad neighbour-advertisement neighbour-solicitation network-prohibited network-redirect network-unknown network-unreachable no-route packet-too-big parameter-problem port-unreachable precedence-cutoff protocol-unreachable redirect reject-route required-option-missing router-advertisement router-solicitation source-quench source-route-failed time-exceeded timestamp-reply timestamp-request tos-host-redirect tos-host-unreachable tos-network-redirect tos-network-unreachable ttl-zero-during-reassembly ttl-zero-during-transit unknown-header-type unknown-option

# firewall-cmd --info-icmptype=echo-request
echo-request
  destination: ipv4 ipv6

# firewall-cmd --query-icmp-block=echo-request
no
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment] 2023-11-23 10:39
How is this related to your other ticket #29250? It's the same issue but you think you've identified another cause?

FWIW I think that dropped ICMP is unlikely to lead to disruptions, most likely it's a symptom of your problem. It's not possible to figure out what the problem is based on the information you have provided. What does "pod unavailability" mean? How does the problem actually manifest in the pod? Packets are dropped outbound, inbound? Something else?

**Comment by siddjellali** [comment] 2023-11-23 12:58
Hello, 

Thanks for your reply.
I'not sure about https://github.com/cilium/cilium/issues/29250 but it's linked.

I have a timeout lasting several minutes on pods for some users but not others, it's a random problem.
Drop are the only error message I have left; after the NAT issue on the previous issue.
Were you able to find some in a sysdump?

**Comment by lmb** [comment] 2023-11-23 15:13
Yup, seems like there are a bunch of errors:

```
$ rg -F =error | wc -l
61
```

Some of them are related to BGP. You might want to look into whether it's misconfigured, the Cilium slack is probably the best place to get help for that.

**Comment by lmb** [comment] 2023-11-24 11:10
Closing for now.

**Closed as completed by lmb** 2023-11-24 11:10 UTC
Labels: kind/bug, needs/triage, kind/community-report, info-completed

**Comment by siddjellali** [comment] 2023-11-29 18:53
I've reinstalled all servers, suspecting the problem was related to CIS hardening, but that doesn't seem to be the case. The issue persists, and my OS is Rocky Linux 9.3. Can you kindly reopen the matter? 
Can someone point me in the right direction?

`cilium sysdump --logs-since-time 24h`
[cilium-sysdump-20231129-195108.zip](https://github.com/cilium/cilium/files/13504467/cilium-sysdump-20231129-195108.zip)
[connectivity.log](https://github.com/cilium/cilium/files/13504470/connectivity.log)


```
📋 Test Report
❌ 5/44 tests failed (28/310 actions), 14 tests skipped, 0 scenarios skipped:
Test [no-policies]:
  ❌ no-policies/pod-to-hostport/curl-0: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> cilium-test/echo-other-node-5c6df4fb89-vg4h7 (192.168.252.11:4000)
  ❌ no-policies/pod-to-hostport/curl-2: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> cilium-test/echo-other-node-5c6df4fb89-vg4h7 (192.168.252.11:4000)
Test [client-egress-l7]:
  ❌ client-egress-l7/pod-to-world/http-to-one.one.one.one-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-http (one.one.one.one:80)
  ❌ client-egress-l7/pod-to-world/https-to-one.one.one.one-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https (one.one.one.one:443)
  ❌ client-egress-l7/pod-to-world/https-to-one.one.one.one-index-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https-index (one.one.one.one:443)
  ❌ client-egress-l7/pod-to-world/http-to-one.one.one.one-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-http (one.one.one.one:80)
  ❌ client-egress-l7/pod-to-world/https-to-one.one.one.one-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https (one.one.one.one:443)
  ❌ client-egress-l7/pod-to-world/https-to-one.one.one.one-index-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https-index (one.one.one.one:443)
Test [client-egress-l7-named-port]:
  ❌ client-egress-l7-named-port/pod-to-world/http-to-one.one.one.one-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-http (one.one.one.one:80)
  ❌ client-egress-l7-named-port/pod-to-world/https-to-one.one.one.one-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https (one.one.one.one:443)
  ❌ client-egress-l7-named-port/pod-to-world/https-to-one.one.one.one-index-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https-index (one.one.one.one:443)
  ❌ client-egress-l7-named-port/pod-to-world/http-to-one.one.one.one-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-http (one.one.one.one:80)
  ❌ client-egress-l7-named-port/pod-to-world/https-to-one.one.one.one-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https (one.one.one.one:443)
  ❌ client-egress-l7-named-port/pod-to-world/https-to-one.one.one.one-index-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https-index (one.one.one.one:443)
Test [dns-only]:
  ❌ dns-only/pod-to-world/http-to-one.one.one.one-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-http (one.one.one.one:80)
  ❌ dns-only/pod-to-world/https-to-one.one.one.one-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https (one.one.one.one:443)
  ❌ dns-only/pod-to-world/https-to-one.one.one.one-index-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https-index (one.one.one.one:443)
  ❌ dns-only/pod-to-world/http-to-one.one.one.one-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-http (one.one.one.one:80)
  ❌ dns-only/pod-to-world/https-to-one.one.one.one-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https (one.one.one.one:443)
  ❌ dns-only/pod-to-world/https-to-one.one.one.one-index-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https-index (one.one.one.one:443)
Test [to-fqdns]:
  ❌ to-fqdns/pod-to-world/http-to-one.one.one.one-0: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-http (one.one.one.one:80)
  ❌ to-fqdns/pod-to-world/https-to-one.one.one.one-0: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https (one.one.one.one:443)
  ❌ to-fqdns/pod-to-world/https-to-one.one.one.one-index-0: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> one.one.one.one-https-index (one.one.one.one:443)
  ❌ to-fqdns/pod-to-world/http-to-one.one.one.one-1: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-http (one.one.one.one:80)
  ❌ to-fqdns/pod-to-world/https-to-one.one.one.one-1: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https (one.one.one.one:443)
  ❌ to-fqdns/pod-to-world/https-to-one.one.one.one-index-1: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> one.one.one.one-https-index (one.one.one.one:443)
  ❌ to-fqdns/pod-to-world-2/https-cilium-io-0: cilium-test/client-75bff5f5b9-zcr8x (10.0.2.19) -> cilium-io-https (cilium.io:443)
  ❌ to-fqdns/pod-to-world-2/https-cilium-io-1: cilium-test/client2-88575dbb7-q79hx (10.0.2.122) -> cilium-io-https (cilium.io:443)
```

**Comment by lmb** [comment] 2023-11-30 09:01
So far I'm not convinced this is a bug, so the issue tracker is not the best place for you to get help. Please try our slack.
