### ISSUE TITLE
CI: Conformance GKE fails on Wait for Cilium to be ready

### ISSUE THREAD

**Issue by brlbil** [cilium/cilium#35693] opened 2024-11-01 13:18 UTC
CI: Conformance GKE fails constantly on Wait for Cilium to be ready. This issue might be related to or the same issue as these #34994 and #35508 

```
Error: Unable to determine status:  timeout while waiting for status to become successful: context deadline exceeded
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       1 errors
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet              cilium-envoy       Desired: 2, Ready: 2/2, Available: 2/2
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay       Desired: 1, Unavailable: 1/1
Containers:            cilium             Running: 2
                       cilium-envoy       Running: 2
                       cilium-operator    Running: 1
                       hubble-relay       Running: 1
Cluster Pods:          0/14 managed by Cilium
Helm chart version:    1.17.0-dev
Image versions         cilium             quay.io/cilium/cilium-ci:e956866f5fef16192836e6280c9ba6529230bc02: 2
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.30.7-1730239547-90b7953f5b6ffe617fa630d42ea6d5b65fba1b9e@sha256:d7db101d856c478a497fc79fab3ce3c732221e80fdf37bfe001672acb155d164: 2
                       cilium-operator    quay.io/cilium/operator-generic-ci:e956866f5fef16192836e6280c9ba6529230bc02: 1
                       hubble-relay       quay.io/cilium/hubble-relay-ci:e956866f5fef16192836e6280c9ba6529230bc02: 1
Errors:                hubble-relay       hubble-relay    1 pods of Deployment hubble-relay are not ready
```

Example runs:
https://github.com/cilium/cilium/actions/runs/11609904397/job/32328150563
https://github.com/cilium/cilium/actions/runs/11627714241/job/32381575897

Artifacts:
[cilium-junits.zip](https://github.com/user-attachments/files/17599913/cilium-junits.zip)
[cilium-sysdumps.zip](https://github.com/user-attachments/files/17599912/cilium-sysdumps.zip)

**Comment by tommyp1ckles** [comment] 2024-11-05 02:46
@brlbil Working off the other issue: https://github.com/cilium/cilium/issues/34994 Going to close this for now as a duplicate.

**Comment by tommyp1ckles** [comment] 2024-11-05 22:12
Realized the other issue is likely something else, as it was opened Sept 20.  Re-opening this as the primary issue relating to the more recent GKE issues and mirroring my findings here (**note** seems to also be happening in AKS)

Added some extra logging for the relay to see what's happening:

```
time="2024-11-05T02:08:21.474889806Z" level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded: connection error: desc = \"transport: error while dialing: dial tcp: lookup hubble-peer.kube-system.svc.cluster.local: i/o timeout\"" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
```

Looks like connection issues are delaying relay startup...causing timeouts.

The issue appears related to svc translation, which is strange as it's on the hubble peer svc which is all host IPs.
 
Looking through various GKE scheduled runs on main branch, this only happens when ipsec is enabled.  From what I can tell the issue begins happening right after: https://github.com/cilium/cilium/pull/35210

**Comment by tommyp1ckles** [comment] 2024-11-05 23:54
I believe the following issues are caused by the same problem:
* https://github.com/cilium/cilium/issues/35692
* https://github.com/cilium/cilium/issues/35508

**Comment by tommyp1ckles** [comment] 2024-11-06 21:10
This should be fixed by: https://github.com/cilium/cilium/pull/35806

**Closed as completed** 2024-11-07 16:18 UTC
Labels: priority/high, area/CI, ci/flake, feature/ipsec
