### ISSUE TITLE
CI: Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23149] opened 2023-01-18 03:48 UTC
### Test Name

```shell
Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests
```

### Failure Output

```shell
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 [20:23:22] make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 [20:23:28] PRIVILEGED_TESTS=true PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/go/src/github.com/cilium/cilium/bpf CGO_ENABLED=0 go test  -mod=vendor -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" \
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
```

### Standard Output

```shell
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 [20:23:22] make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 [20:23:28] PRIVILEGED_TESTS=true PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/go/src/github.com/cilium/cilium/bpf CGO_ENABLED=0 go test  -mod=vendor -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" \
```

### Standard Error

```shell
N/A
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4546/testReport/junit/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/
- ZIP file(s): https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4546/testReport/junit/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/attachments/a567df42_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip

**Comment by joestringer** [comment] 2023-01-18 05:04
When filing an issue for unit test failures, please make sure to include which specific test failed as well, since otherwise we can end up confusing multiple unrelated unit tests.

The failure here is:

```
	 [20:29:11] �[38;5;103m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓�[0m
	 [20:29:11] �[38;5;103m┃�[0m   �[91m�[91mFAIL�[0m�[0m  package: github.com/cilium/cilium/pkg/crypto/certloader   �[38;5;103m┃�[0m
	 [20:29:11] �[38;5;103m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛�[0m
	 [20:29:11] 
	 [20:29:11] �[31m--- FAIL: TestFutureWatchedServerConfig (0.44s)�[0m
	 [20:29:11] 
	 [20:29:11]     server_test.go:97: FutureWatchedServerConfig should be ready one the TLS files exists
	 [20:29:11] 
```

**Comment by joestringer** [comment] 2023-01-18 05:11
Looks like a duplicate of https://github.com/cilium/cilium/issues/22750.

**Closed as not planned by joestringer** 2023-01-18 05:11 UTC
Labels: area/CI, ci/flake
