### ISSUE TITLE
Sometimes logs have a blank k8sPodName

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22242] opened 2022-11-17 22:55 UTC
Example log:

```
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg="344.712µs" bpfWaitForELF="10.29µs" bpfWriteELF="774.213µs" containerID= datapathPolicyRevision=0 desiredPolicyRevision=18 endpointID=229 error="Failed to replace Qdisc for lxc69bc0bfc43ce: Link not found" identity=45981 ipv4= ipv6= k8sPodName=/ mapSync="110.719µs" policyCalculation="76.11µs" prepareBuild="864.166µs" proxyConfiguration="20.04µs" proxyPolicyCalculation="32.43µs" proxyWaitForAck=0s reason="updated security labels" subsys=endpoint total=1m33.651333003s waitingForCTClean=1m33.646810669s waitingForLock="1.85µs"
```

In this log message, the `k8sPodName=/` should really show the full pod namespace+name, but it doesn't.

**Comment by MattSilvaa** [comment] 2022-12-24 04:42
Hello! I would love to help out with this 😄

**Comment by christarazi** [comment] 2022-12-28 20:42
Thanks @MattSilvaa, I've assigned you. Feel free to reach out for help on #development channel on Cilium Slack.

**Comment by christarazi** [comment] 2023-02-01 06:20
@MattSilvaa Are you still planning to work on this?

**Comment by MattSilvaa** [comment] 2023-02-01 06:22
> @MattSilvaa Are you still planning to work on this?

Yes, sorry. I have been really busy with work. I will get on this, this weekend.

**Comment by pchaigno** [comment] 2023-04-03 11:41
Closing as this code was rewritten when we switch BPF loader. The error-handling logic was also changed quite a bit so it's unclear if this specific issue is still happening. We can open a new issue with more details if we re-hit this.

**Comment by christarazi** [comment] 2023-04-03 18:18
I don't think this has been resolved. The issue is more general and not just speciufically about the regeneration failed msg, although that was the example used. Here's a log file that I've just had locally from a very recent build of Cilium off `master`:

<details><summary>Details</summary>
<p>

```
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=505 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=505 identityLabels="k8s:node-role.kubernetes.io/control-plane,k8s:node.kubernetes.io/exclude-from-external-load-balancers,reserved:host" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=505 identity=1 identityLabels="k8s:node-role.kubernetes.io/control-plane,k8s:node.kubernetes.io/exclude-from-external-load-balancers,reserved:host" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.130 76e7889b-60b6-4484-96e9-e8ffa471f5bf  }" containerID=f6cfb10d069c7a821f58748f76e273e03b873f4b2131e2b42e607a8fc8fe02b5 datapathConfiguration="&{false false false false false <nil>}" interface=lxc39e8e3c950d9 k8sPodName=kube-system/coredns-565d847f94-p5c8g labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 identity=112 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.47 eeadb666-5fde-4ed1-a2cf-016a21cfc0fb  }" containerID=cfceb12d487c6c161515311bb91927953fc37cf877f110ba4f8e7bae804b5fb5 datapathConfiguration="&{false false false false false <nil>}" interface=lxcec24e0bf068a k8sPodName=kube-system/hubble-relay-7bf5549b75-nm59x labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 identityLabels="k8s:app.kubernetes.io/name=hubble-relay,k8s:app.kubernetes.io/part-of=cilium,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=hubble-relay,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=hubble-relay" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 identity=51395 identityLabels="k8s:app.kubernetes.io/name=hubble-relay,k8s:app.kubernetes.io/part-of=cilium,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=hubble-relay,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=hubble-relay" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 identity=51395 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.67 ed5f0201-d75c-4ea9-9762-5274221ed51a  }" containerID=a34135507f880d93e60654d667da2b2c26d1b03fbae7faabde4f3c3a13dcbd57 datapathConfiguration="&{false false false false false <nil>}" interface=lxc0e556478a5b3 k8sPodName=kube-system/coredns-565d847f94-vm46p labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 identity=112 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.143 56829550-e872-41d7-a391-59c56dbfe92a  }" containerID=a7083e4330b8fc0259846d7c7718a8053ba74b89d57d009b9e9b4f8a5a4902c3 datapathConfiguration="&{false false false false false <nil>}" interface=lxcf25f06f4566b k8sPodName=local-path-storage/local-path-provisioner-684f458cdd-dqfdn labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 identityLabels="k8s:app=local-path-provisioner,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=local-path-storage,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account,k8s:io.kubernetes.pod.namespace=local-path-storage" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 identity=36312 identityLabels="k8s:app=local-path-provisioner,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=local-path-storage,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account,k8s:io.kubernetes.pod.namespace=local-path-storage" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 identity=36312 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1186 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1186 identityLabels="reserved:health" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1186 identity=4 identityLabels="reserved:health" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3479 identity=51395 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=3479 identity=51395 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=901 identity=36312 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=901 identity=36312 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=1157 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=1157 identity=112 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=1186 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3504 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=3504 identity=112 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=505 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

</p>
</details>

**Comment by christarazi** [comment] 2023-04-03 18:19
I don't think this has been resolved. The issue is more general and not just speciufically about the regeneration failed msg, although that was the example used. Here's a log file that I've just had locally from a very recent build of Cilium off `master`:

<details><summary>Details</summary>
<p>

```
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=505 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=505 identityLabels="k8s:node-role.kubernetes.io/control-plane,k8s:node.kubernetes.io/exclude-from-external-load-balancers,reserved:host" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=505 identity=1 identityLabels="k8s:node-role.kubernetes.io/control-plane,k8s:node.kubernetes.io/exclude-from-external-load-balancers,reserved:host" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.130 76e7889b-60b6-4484-96e9-e8ffa471f5bf  }" containerID=f6cfb10d069c7a821f58748f76e273e03b873f4b2131e2b42e607a8fc8fe02b5 datapathConfiguration="&{false false false false false <nil>}" interface=lxc39e8e3c950d9 k8sPodName=kube-system/coredns-565d847f94-p5c8g labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 identity=112 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3504 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.47 eeadb666-5fde-4ed1-a2cf-016a21cfc0fb  }" containerID=cfceb12d487c6c161515311bb91927953fc37cf877f110ba4f8e7bae804b5fb5 datapathConfiguration="&{false false false false false <nil>}" interface=lxcec24e0bf068a k8sPodName=kube-system/hubble-relay-7bf5549b75-nm59x labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 identityLabels="k8s:app.kubernetes.io/name=hubble-relay,k8s:app.kubernetes.io/part-of=cilium,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=hubble-relay,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=hubble-relay" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 identity=51395 identityLabels="k8s:app.kubernetes.io/name=hubble-relay,k8s:app.kubernetes.io/part-of=cilium,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=hubble-relay,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=hubble-relay" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3479 identity=51395 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.67 ed5f0201-d75c-4ea9-9762-5274221ed51a  }" containerID=a34135507f880d93e60654d667da2b2c26d1b03fbae7faabde4f3c3a13dcbd57 datapathConfiguration="&{false false false false false <nil>}" interface=lxc0e556478a5b3 k8sPodName=kube-system/coredns-565d847f94-vm46p labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 identity=112 identityLabels="k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=coredns,k8s:io.kubernetes.pod.namespace=kube-system,k8s:k8s-app=kube-dns" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1157 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Create endpoint request" addressing="&{10.244.0.143 56829550-e872-41d7-a391-59c56dbfe92a  }" containerID=a7083e4330b8fc0259846d7c7718a8053ba74b89d57d009b9e9b4f8a5a4902c3 datapathConfiguration="&{false false false false false <nil>}" interface=lxcf25f06f4566b k8sPodName=local-path-storage/local-path-provisioner-684f458cdd-dqfdn labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 identityLabels="k8s:app=local-path-provisioner,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=local-path-storage,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account,k8s:io.kubernetes.pod.namespace=local-path-storage" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 identity=36312 identityLabels="k8s:app=local-path-provisioner,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=local-path-storage,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account,k8s:io.kubernetes.pod.namespace=local-path-storage" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=901 identity=36312 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1186 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1186 identityLabels="reserved:health" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1186 identity=4 identityLabels="reserved:health" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3479 identity=51395 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=3479 identity=51395 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=901 identity=36312 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=901 identity=36312 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=1157 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=1157 identity=112 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=1186 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3504 identity=112 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=3504 identity=112 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=505 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

</p>
</details>

**Comment by christarazi** [comment] 2023-07-19 19:04
Yes, the host endpoint (ID: 1) does not have a backing pod as it represents the node (or the Cilium Agent running on the node).

**Comment by pchaigno** [comment] 2023-07-20 10:23
I guess we need a special name for that special endpoint, so that the field isn't empty and clearly indicates it's the host endpoint.

**Comment by vakalapa** [comment] 2023-07-20 16:22
I think i found the issue, when the endpoint and logger is created with it, the field for podname is populated with `logfields.K8sPodName:             e.GetK8sNamespaceAndPodName(),`, but initially this value returns "/" as the endpoint id and pod details are not populated yet. Later Updatelogger is called on the endpoint, but it never reinitializes these field values. 

Multiple approaches here: 

1) not initialize the logger until after pod details are populated ? ( will lose on valuable logging of endpoint state before pod details are populated
2) introduce a force flag in UpdateLogger to reset logger. This can be called from AddEndpoint where we know the pod details are populated. 

@christarazi can you assign this to me ? and do you have any suggestions on which way to go ?

**Comment by christarazi** [comment] 2023-07-20 22:07
The second option sounds reasonable to me. Another option is to update the logger whenever the fields are updated as well. Either one is fine IMO.

**Closed as completed** 2023-07-26 06:24 UTC
Labels: kind/bug, help-wanted, good-first-issue, area/agent
