### ISSUE TITLE
CI: K8sHubbleTest Hubble Observe Test L3/L4 Flow

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#16480] opened 2021-06-08 19:18 UTC
```
Stacktrace
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
Test Panicked
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:455
```

```
Standard Error
20:37:58 STEP: Running BeforeAll block for EntireTestsuite K8sHubbleTest Hubble Observe
20:37:58 STEP: Ensuring the namespace kube-system exists
20:37:58 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
20:37:58 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
20:37:58 STEP: Installing Cilium
20:38:00 STEP: Waiting for Cilium to become ready
20:38:18 STEP: Running JustAfterEach block for EntireTestsuite K8sHubbleTest Hubble Observe
===================== TEST FAILED =====================
20:38:18 STEP: Running AfterFailed block for EntireTestsuite K8sHubbleTest Hubble Observe
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS              RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-w7bvq          1/1     Running             0          50m     10.0.0.208      k8s2   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-dgp8r       1/1     Running             0          50m     10.0.0.224      k8s2   <none>           <none>
	 kube-system         cilium-operator-9f95dfb4d-4mzgp   1/1     Running             0          21s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-9f95dfb4d-d699z   1/1     Running             0          21s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-tj2h8                      1/1     Running             0          21s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-wxtcj                      1/1     Running             0          21s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         coredns-755cd654d4-2mffm          1/1     Running             0          5m18s   10.0.0.247      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                         1/1     Running             0          53m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         hubble-relay-854f6df6d7-fz5sk     0/1     ContainerCreating   0          21s     <none>          k8s2   <none>           <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running             0          53m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running             0          53m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-j46p4                  1/1     Running             0          53m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-pv425                  1/1     Running             0          51m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running             0          53m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-mwwjm                1/1     Running             0          50m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-s7qx8                1/1     Running             0          50m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-rvrlx              1/1     Running             0          51m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-wvz26              1/1     Running             0          51m     192.168.36.12   k8s2   <none>           <none>
	 
Stderr:
 	 
```
[c78d043e_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip](https://github.com/cilium/cilium/files/6619039/c78d043e_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip)

From test-output.log:
```
time="2021-06-04T20:38:18Z" level=debug msg="running command: kubectl -n kube-system get cep hubble-relay-854f6df6d7-fz5sk -o json | jq '.status'"
cmd: "kubectl -n kube-system get cep hubble-relay-854f6df6d7-fz5sk -o json | jq '.status'" exitCode: 0 duration: 48.554508ms stdout:
null

```

**Comment by pchaigno** [comment] 2021-06-08 19:23
@jrajahalme Same root cause as https://github.com/cilium/cilium/issues/16441 (see PR at https://github.com/cilium/cilium/pull/16443) maybe?

**Comment by pchaigno** [comment] 2021-06-09 21:24
Likely the same issue as https://github.com/cilium/cilium/issues/16441, which was recently fixed in https://github.com/cilium/cilium/pull/16443. I'm closing but please reopen or ping here if you hit this again.

**Closed as completed by pchaigno** 2021-06-09 21:24 UTC
Labels: area/CI, ci/flake
