### ISSUE TITLE
cilium cleanup doesn't remove lb maps

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#8036] opened 2019-05-15 13:37 UTC

**Comment by nirmoy** [comment] 2019-05-15 14:13
@borkmann https://github.com/cilium/cilium/pull/8031

**Comment by brb** [comment] 2019-05-15 16:26
It seems that it doesn't remove any file from the `/sys/fs/bpf/tc/globals/` dir.

**Comment by joestringer** [comment] 2019-05-15 21:09
How is `cilium cleanup` being invoked here?

**Comment by borkmann** [comment] 2019-05-16 08:38
> How is `cilium cleanup` being invoked here?

@brb might clarify, but I think it was `cilium cleanup -f`.

**Comment by mrostecki** [comment] 2019-07-17 11:06
I can't reproduce that issue anymore, so I'm closing it.

```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cat deployment.yaml 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cat service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl apply -f deployment.yaml
deployment.apps/nginx-deployment created
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl apply -f service.yaml 
service/my-service created
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ sudo cilium bpf lb list
SERVICE ADDRESS    BACKEND ADDRESS          
172.20.0.82:80     10.16.172.17:80 (6)      
                   10.16.197.182:80 (6)     
                   0.0.0.0:0 (6)            
172.20.0.10:9153   10.16.12.253:9153 (4)    
                   0.0.0.0:0 (4)            
172.20.0.10:53     0.0.0.0:0 (2)            
                   10.16.12.253:53 (2)      
172.20.0.1:443     0.0.0.0:0 (1)            
                   192.168.33.11:6443 (1)
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ sudo cilium cleanup -f
Warning: Destructive operation. You are about to remove:
- all BPF maps in /sys/fs/bpf/tc/globals containing 'cilium_' and 'cilium_tunnel_map'
- mounted bpffs at /sys/fs/bpf
- mounted cgroupv2 at /var/run/cilium/cgroupv2
- library code in /var/lib/cilium
- endpoint state in /var/run/cilium
- CNI configuration at /etc/cni/net.d/10-cilium-cni.conf, /etc/cni/net.d/00-cilium-cni.conf, /etc/cni/net.d/05-cilium-cni.conf
- routes
{Ifindex: 10 Dst: 10.16.116.130/32 Src: <nil> Gw: <nil> Flags: [] Table: 254}

- links
&{{10 1500 1000 cilium_host 3a:d6:2a:99:6c:45 up|broadcast|multicast 69827 9 0 <nil>  0xc00054d820 0 <nil> ether <nil> up 0 1 1 65536 65535 []}  }
&{{9 1500 1000 cilium_net 52:56:fa:c4:36:5f up|broadcast|multicast 69827 10 0 <nil>  0xc00054d328 0 <nil> ether <nil> up 0 1 1 65536 65535 []}  }
&{{11 1500 1000 cilium_vxlan be:53:b2:95:a4:41 up|broadcast|multicast 69699 0 0 <nil>  0xc00054dd14 0 <nil> ether <nil> unknown 0 1 1 65536 65535 []} 0 0 <nil> <nil> 0 0 false false false false false true false false false false true 300 0 8472 0 0}

removed map cilium_calls_00401
removed map cilium_calls_02135
removed map cilium_calls_02363
removed map cilium_calls_03472
removed map cilium_calls_netdev_ns_1
removed map cilium_calls_overlay_2
removed map cilium_ct4_global
removed map cilium_ct6_global
removed map cilium_ct_any4_global
removed map cilium_ct_any6_global
removed map cilium_encrypt_state
removed map cilium_ep_config_00401
removed map cilium_ep_config_02135
removed map cilium_ep_config_02363
removed map cilium_ep_config_03472
removed map cilium_events
removed map cilium_ipcache
removed map cilium_lb4_backends
removed map cilium_lb4_reverse_nat
removed map cilium_lb4_rr_seq_v2
removed map cilium_lb4_services_v2
removed map cilium_lb6_backends
removed map cilium_lb6_reverse_nat
removed map cilium_lb6_rr_seq_v2
removed map cilium_lb6_services_v2
removed map cilium_lxc
removed map cilium_metrics
removed map cilium_policy
removed map cilium_policy_00401
removed map cilium_policy_02135
removed map cilium_policy_02363
removed map cilium_policy_03472
removed map cilium_policy_reserved_1
removed map cilium_policy_reserved_2
removed map cilium_tunnel_map
INFO[0000] Trying to unmount /var/run/cilium/cgroupv2   
removed route {Ifindex: 10 Dst: 10.16.116.130/32 Src: <nil> Gw: <nil> Flags: [] Table: 254}
removed link cilium_host
removed link cilium_vxlan
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ sudo tree /sys/fs/bpf/
/sys/fs/bpf/
├── ip
│   └── globals
├── sa
│   └── globals
├── tc
│   └── globals
└── xdp
    └── globals

8 directories, 0 files
```

**Closed as completed by mrostecki** 2019-07-17 11:06 UTC
Labels: kind/bug
