### ISSUE TITLE
conntrack: updateCT doesn't delete update entries' proxy ports when importing L7 policy

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#3208] opened 2018-03-20 04:07 UTC
The test named `Testing L3-L4-L7 policy while the L3-L4 connection was previously made to confirm L3-L4-L7 policy enforcement over the proxy with the same source port` sometimes fails.
The reason is that importing the L7 policy doesn't result in the conntrack entries for the previous connections to be removed from the map.
This can be easily confirmed by adding those checks:
```
@@ -710,6 +710,15 @@ var _ = Describe("RuntimeValidatedConntrackTable", func() {
                _, err = vm.PolicyRenderAndImport(policyL7)
                Expect(err).To(BeNil(), "Installing an L3-L4-L7 policy")
 
+               By("Checking that CT entries from server-3 to client are properly cleaned up")
+               data, err = countCTINEntriesOf(meta[server3][helpers.IPv6], "80", meta[client][helpers.IPv6], epIdentities[client])
+               Expect(err).To(BeNil())
+               Expect(data).To(BeNumerically(comparator, 0), "CT map should have exactly 0 IPv6 entries between server-3 and client")
+
+               data, err = countCTINEntriesOf(meta[server3][helpers.IPv4], "80", meta[client][helpers.IPv4], epIdentities[client])
+               Expect(err).To(BeNil())
+               Expect(data).To(BeNumerically(comparator, 0), "CT map should have exactly 0 IPv4 entries between server-3 and client")
+
                By("Testing connectivity between client and server-3 on all HTTP endpoints")
                for _, testCase := range testCombinations {
                        assertfn := BeTrue
```

When the test fails, both the IPv6 and IPv4 entries are still in the map after `PolicyRenderAndImport(policyL7)` successfully returns:
```
$ grep "IN \[f00d::a0f:0:0:33b1\]:80" bpf_ct_list.txt 
TCP IN [f00d::a0f:0:0:33b1]:80 -> [f00d::a0f:0:0:c5d0]:54374  expires=63103 rx_packets=6 rx_bytes=614 tx_packets=4 tx_bytes=580 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
TCP IN [f00d::a0f:0:0:33b1]:80 -> [f00d::a0f:0:0:c5d0]:11111  expires=63103 rx_packets=10 rx_bytes=1095 tx_packets=10 tx_bytes=1371 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
TCP IN [f00d::a0f:0:0:33b1]:80 -> [f00d::a0f:0:0:c5d0]:54372  expires=63103 rx_packets=6 rx_bytes=614 tx_packets=4 tx_bytes=580 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
TCP IN [f00d::a0f:0:0:33b1]:80 -> [f00d::a0f:0:0:c5d0]:11112  expires=63103 rx_packets=5 rx_bytes=548 tx_packets=5 tx_bytes=686 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
```
```
$ grep "IN 10.15.113.22:80" bpf_ct_list.txt
TCP IN 10.15.113.22:80 -> 10.15.166.9:11111  expires=63103 rx_packets=10 rx_bytes=879 tx_packets=10 tx_bytes=1171 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
TCP IN 10.15.113.22:80 -> 10.15.166.9:46000  expires=63103 rx_packets=6 rx_bytes=487 tx_packets=4 tx_bytes=501 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
TCP IN 10.15.113.22:80 -> 10.15.166.9:45998  expires=63103 rx_packets=6 rx_bytes=487 tx_packets=4 tx_bytes=501 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
TCP IN 10.15.113.22:80 -> 10.15.166.9:11112  expires=63103 rx_packets=5 rx_bytes=440 tx_packets=5 tx_bytes=586 flags=0 revnat=0 proxyport=16834 src_sec_id=3945
```

The logs show that the policy regeneration succeeds, and that `updateCT()` is called as part of the regeneration.
Therefore, this seems to be a bug in `updateCT()` which results in the entries not getting deleted.

This test failure happens occasionally in PR CI builds, e.g. https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1398/execution/node/55/log/. But it happens more frequently with PR https://github.com/cilium/cilium/pull/2974, so that branch could be a good way to reproduce the issue.

**Comment by ianvernon** [comment] 2018-03-20 05:02
The entries shown have a non-zero value for the proxy port - if it is L3-L4 connections without  L3-L4-L7 with policy, shouldn't the CT table output show a zero-value for the proxy port?

**Comment by jrajahalme** [comment] 2018-03-20 05:15
@ianvernon The logs above are after a new policy with L7 redirect has been installed,  it before any traffic has been sent through it.

**Comment by jrajahalme** [comment] 2018-03-20 17:57
Looking at `pkg/endpointmanager/conntrack.go`, maybe the proxy ports were updated as part of the updateCT(). Maybe the intention is not to remove the CT entries in this case, but to update them instead. I'm running the test again without the added check for 0 CT entires between client/server.

**Comment by rlenglet** [comment] 2018-03-20 17:59
Maybe the update of the entries fails in some cases?

**Comment by ianvernon** [comment] 2018-03-20 19:39
Yeah, seems like the logic in `ResetProxyPort`is to update the ConnTrack entries to contain the new proxy port, which then has traffic sent to the proxy:

`pkg/maps/ctmap/ctmap.go`:

```
func (f *GCFilter) doFiltering(dstIP net.IP, dstPort uint16, nextHdr, flags uint8, entry *CtEntry) (action int) {
...
			} else {
				// If the rule is not L3-only then check if it's allowed by
				// L3-L4 rules.
				if l7Rule, ok := filterRuleCtx[l4RuleCtx]; ok {
					if l7Rule.L4Installed && entry.proxy_port != l7Rule.RedirectPort {
						action = modifyEntry
						entry.proxy_port = l7Rule.RedirectPort
...
```

This entry is then updated in the CT table in `pkg/maps/ctmap/ctmap.go:doGC4` and `pkg/maps/ctmap/ctmap.go:doGC6`, so checking the zero entries in the CT table after adding the L3-L4-L7 policy is incorrect.

**Comment by jrajahalme** [comment] 2018-03-20 19:43
OK, ran the test again, now a earlier test failed, but similar symptoms. nc goes through bypassing the proxy after the L7 policy is instantiated. The proxyport in the CT is 0:

```
TCP IN [f00d::a0f:0:0:dbdb]:80 -> [f00d::a0f:0:0:6035]:11111  expires=128533 rx_packets=15 rx_bytes=1643 tx_packets=15 tx_bytes=2057 flags=0 revnat=0 proxyport=0 src_sec_id=50927
```

This goes through, bypassing the proxy:
```
Failed to httpRequest 'docker exec -i  client bash -c "python ./nc.py 11111 5 f00d::a0f:0:0:dbdb 80 \"/private\" | head -n 1 | grep \"HTTP/1.*200 OK\""' from client to f00d::a0f:0:0:dbdb: HTTP/1.1 200 OK
  
  Expected
      <bool>: true
  to be false
```

`f00d::a0f:0:0:6035` is the client, 50927 is it's security ID.

Based on this we know the test, bpf datapath and proxy are functioning as intended, and it is a problem in updating CT after policy change, if indeed the CT's proxyport should have been updated.

**Comment by rlenglet** [comment] 2018-03-21 23:34
Still seeing the same failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1493/
```
21:48:09 RuntimeValidatedConntrackTable
21:48:09 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:170
21:48:09   Testing L3-L4-L7 policy while the L3-L4 connection was previously made to confirm L3-L4-L7 policy enforcement over the proxy with the same source port [It]
21:48:09   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:202
21:48:09 
21:48:09   Failed to httpRequest 'docker exec -i  client bash -c "python ./nc.py 11111 5 f00d::a0f:0:0:ad 80 \"/private\" | head -n 1 | grep \"HTTP/1.*200 OK\""' from client to f00d::a0f:0:0:ad: HTTP/1.1 200 OK
21:48:09   
21:48:09   Expected
21:48:09       <bool>: true
21:48:09   to be false
21:48:09 
21:48:09   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/ct.go:715
```

The proxyport fields are still set to 0 in the CT map after inserting a proxy redirect:
```
$ grep 'TCP IN.*11111' bpf_ct_list.txt 
TCP IN [f00d::a0f:0:0:ad]:80 -> [f00d::a0f:0:0:72c5]:11111  expires=43888 rx_packets=15 rx_bytes=1637 tx_packets=15 tx_bytes=2057 flags=0 revnat=0 proxyport=0 src_sec_id=28468
TCP IN 10.15.148.173:80 -> 10.15.193.100:11111  expires=43882 rx_packets=10 rx_bytes=881 tx_packets=10 tx_bytes=1171 flags=0 revnat=0 proxyport=0 src_sec_id=28468
```

**Comment by ianvernon** [comment] 2018-04-16 18:48
@tgraf can we close this? We no longer cleanup CT from userspace anymore. Discussed offline with @rlenglet and he said we can.

**Closed as completed** 2018-04-19 03:30 UTC
Labels: kind/bug, area/datapath, area/daemon
