### ISSUE TITLE
CI: Flaky runtime.RuntimeMemcache

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#9812] opened 2020-01-06 17:28 UTC
This test began failing sometime over the new-year break. Some example failures:
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9942/ 
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9951/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9938/

This is most likely a race, as different tests fail. This may be related to other slowdown issues we've been having with the CI, so it may be "fixable" elsewhere.

**Comment by joestringer** [comment] 2020-05-07 23:52
Duplicate of #11412 which is now in the v1.8 disabled CI tests project.

**Closed as completed by joestringer** 2020-05-07 23:52 UTC
Labels: kind/duplicate, kind/bug/CI, area/CI
