### ISSUE TITLE
SIGSEGV: invalid memory address or nil pointer dereference in DeviceNames

### ISSUE THREAD

**Issue by alex-berger** [cilium/cilium#34019] opened 2024-07-25 18:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

Since upgrading to Cilium 1.16.0, I sporadically observe Cilium Agent container crash/restarts caused by below nil pointer error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x2642570]

goroutine 984 [running]:
github.com/cilium/cilium/pkg/datapath/types.(*LocalNodeConfiguration).DeviceNames(...)
	/go/src/github.com/cilium/cilium/pkg/datapath/types/node.go:165
github.com/cilium/cilium/pkg/datapath/linux/config.(*HeaderfileWriter).WriteEndpointConfig(0x4002798000, {0x3dce300, 0x4000da29e0?}, 0x0, {0x3e531f0, 0x4000468c08})
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/config/config.go:1045 +0xf0
github.com/cilium/cilium/pkg/datapath/loader.(*loader).WriteEndpointConfig(0x4000468c08?, {0x3dce300?, 0x4000da29e0?}, {0x3e531f0?, 0x4000468c08?})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:698 +0x50
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile(0x4000468c08, {0x40029fbac0, 0x1a})
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:189 +0x540
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).syncEndpointHeaderFile(0x4000468c08, {0x4001249720, 0x1, 0x1})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2450 +0x294
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0x4002532960)
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x464
created by github.com/cilium/cilium/pkg/trigger.NewTrigger in goroutine 1
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:122 +0x1b4
```

### How can we reproduce the issue?

N/A

### Cilium Version

1.16.0

### Kernel Version

6.1.94

Bottlerocket OS 1.20.4 (aws-k8s-1.29)
containerd://1.6.31

### Kubernetes Version

v1.29.4-eks-036c24b

### Relevant log output

```shell
time="2024-07-25T18:20:29Z" level=info msg="Subscribed to CiliumNode custom resource" name=ip-10-176-21-6.eu-central-1.compute.internal subsys=ipam
time="2024-07-25T18:20:29Z" level=info msg="Creating or updating CiliumNode resource" node=ip-10-176-21-6.eu-central-1.compute.internal subsys=nodediscovery
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x2642570]

goroutine 984 [running]:
github.com/cilium/cilium/pkg/datapath/types.(*LocalNodeConfiguration).DeviceNames(...)
	/go/src/github.com/cilium/cilium/pkg/datapath/types/node.go:165
github.com/cilium/cilium/pkg/datapath/linux/config.(*HeaderfileWriter).WriteEndpointConfig(0x4002798000, {0x3dce300, 0x4000da29e0?}, 0x0, {0x3e531f0, 0x4000468c08})
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/config/config.go:1045 +0xf0
github.com/cilium/cilium/pkg/datapath/loader.(*loader).WriteEndpointConfig(0x4000468c08?, {0x3dce300?, 0x4000da29e0?}, {0x3e531f0?, 0x4000468c08?})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:698 +0x50
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile(0x4000468c08, {0x40029fbac0, 0x1a})
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:189 +0x540
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).syncEndpointHeaderFile(0x4000468c08, {0x4001249720, 0x1, 0x1})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2450 +0x294
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0x4002532960)
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x464
created by github.com/cilium/cilium/pkg/trigger.NewTrigger in goroutine 1
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:122 +0x1b4
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment] 2024-07-25 20:44
@joamaki this seems to be some code that you touched - PTAL!

**Comment by joamaki** [comment] 2024-07-26 08:20
I think what’s going on is that Loader.Reinitialize has not yet completed and the LocalNodeConfiguration is nil. We end up here via the initDNSHistoryTrigger->syncEndpointHeaderFile. In other words, we’re processing endpoints before datapath has been fully initialized. I’ll look into reproing this today and think about how to fix it.

**Comment by 0dragosh** [comment] 2024-08-14 15:06
I still encounter this daily:

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x2c6bde7]

goroutine 408 [running]:
github.com/cilium/cilium/pkg/datapath/types.(*LocalNodeConfiguration).DeviceNames(...)
    /go/src/github.com/cilium/cilium/pkg/datapath/types/node.go:165
github.com/cilium/cilium/pkg/datapath/linux/config.(*HeaderfileWriter).WriteEndpointConfig(0xc001dfb260, {0x4465240, 0xc000ba2220?}, 0x0, {0x44e9e30, 0xc000205408})
    /go/src/github.com/cilium/cilium/pkg/datapath/linux/config/config.go:1045 +0x127
github.com/cilium/cilium/pkg/datapath/loader.(*loader).WriteEndpointConfig(0xc000205408?, {0x4465240?, 0xc000ba2220?}, {0x44e9e30?, 0xc000205408?})
    /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:698 +0x3e
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile(0xc000205408, {0xc0015bd3a0, 0x1a})
    /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:189 +0x6ff
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).syncEndpointHeaderFile(0xc000205408, {0xc000d86d90, 0x1, 0x1})
    /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2454 +0x2c8
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc001dd8460)
    /go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x458
created by github.com/cilium/cilium/pkg/trigger.NewTrigger in goroutine 1
    /go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:122 +0x1d8```

**Comment by gandro** [comment] 2024-08-14 16:58
@0dragosh what version/branch? Note that the fix is only available in v1.16.1 or the `main` branch

**Comment by 0dragosh** [comment] 2024-08-14 17:28
@gandro 1.16.1 on Talos Linux 1.7.6 k8s 1.30.3

**Comment by adamw-linadm** [comment] 2024-08-16 11:57
I have exactly the same problem. Upgrading from 1.15.8 to 1.16.1 (alma linux 8.10, k8s 1.29.6) causes this error. The cilium pods start crashing, but after a few crashes they start normally.
I'm firing up a lot of crons and I suspect the problem is occurring when creating/deleting interfaces for them.

```
time="2024-08-16T10:47:14Z" level=info msg="Reading old endpoints..." subsys=daemon
time="2024-08-16T10:47:14Z" level=info msg="Detected upgrade from Cilium v1.15. Building IPCache metadata from restored FQDN selectors" subsys=fqdn
time="2024-08-16T10:47:14Z" level=info msg="Reusing previous DNS proxy port: 32861" subsys=daemon
time="2024-08-16T10:47:14Z" level=info msg="Retrieved node information from kubernetes node" nodeName=test-kmaster2.node.consul subsys=daemon
time="2024-08-16T10:47:14Z" level=info msg="Received own node information from API server" ipAddr.ipv4=192.168.0.248 ipAddr.ipv6="<nil>" k8sNodeIP=192.168.0.248 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:test-kmaster2.brand24.pl kubernetes.io/os:linux node-role.kubernetes.io/control-plane: node.kubernetes.io/exclude-from-external-load-balancers:]" nodeName=test-kmaster2.node.consul subsys=daemon v4Prefix=172.0.2.0/24 v6Prefix="<nil>"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x2c6bde7]

goroutine 891 [running]:
github.com/cilium/cilium/pkg/datapath/types.(*LocalNodeConfiguration).DeviceNames(...)
	/go/src/github.com/cilium/cilium/pkg/datapath/types/node.go:165
github.com/cilium/cilium/pkg/datapath/linux/config.(*HeaderfileWriter).WriteEndpointConfig(0xc0020653e0, {0x4465240, 0xc000dd1dc0?}, 0x0, {0x44e9e30, 0xc002dbb408})
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/config/config.go:1045 +0x127
github.com/cilium/cilium/pkg/datapath/loader.(*loader).WriteEndpointConfig(0xc002dbb408?, {0x4465240?, 0xc000dd1dc0?}, {0x44e9e30?, 0xc002dbb408?})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:698 +0x3e
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile(0xc002dbb408, {0xc0013ef500, 0x1a})
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:189 +0x6ff
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).syncEndpointHeaderFile(0xc002dbb408, {0xc000f55450, 0x1, 0x1})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2454 +0x2c8
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0020f3b80)
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x458
created by github.com/cilium/cilium/pkg/trigger.NewTrigger in goroutine 1
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:122 +0x1d8

**Comment by rauanmayemir** [comment] 2024-09-16 07:30
I have this issue still happening on 1.16.1, this was not fixed.

**Comment by gandro** [comment] 2024-09-16 07:47
cc @joamaki @bimmlerd

**Comment by joamaki** [comment] 2024-09-16 09:03
The patch was already merged and shipped with v1.16.1, unfortunately it seems I must've missed another code path to end here before `Reinitialize` is done. I'm going to do a patch to make sure we wait for the `nodeConfig` to be finalized and not try to fix the initialization order.

**Comment by rauanmayemir** [comment] 2024-09-18 12:43
@WoodyWoodsta you'll have to cordon and drain your node so that there are no requests to the agent, then it might boot properly.

**Comment by christarazi** [comment] 2024-12-20 20:39
This should be fixed in https://github.com/cilium/cilium/pull/35890 which is in v1.16.4.

**Closed as completed by christarazi** 2024-12-20 20:39 UTC
Labels: kind/bug, priority/high, needs/triage, kind/community-report, area/agent

**Comment by rauanmayemir** [comment] 2024-12-21 07:18
Can confirm it is indeed fixed.
