### ISSUE TITLE
Empty NamespaceSelector in Kubernetes Network Policy allows everything

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4513] opened 2018-06-14 13:06 UTC
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - namespaceSelector: {}
```

>Few remarks about this policy:
>
>This policy applies to pods with app=foo and in Egress (outbound) direction.
>Similar to DENY egress traffic from an application example, this policy allows all outbound traffic on ports 53/udp and 53/tcp for DNS resolution.
>to: specifies an empty namespaceSelector. This will select all pods in all namespaces, so the outbound traffic to pods in the cluster will be allowed.
>And since they are not listed, traffic to the IP addresses outside the cluster are denied.

Source: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/14-deny-external-egress-traffic.md

Reported by @nirmoy 

The `foo-deny-external-egress` policy is translated into
```
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:app": "foo",
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "egress": [
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "reserved:all": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "53",
                "protocol": "UDP"
              }
            ]
          },
          {
            "ports": [
              {
                "port": "53",
                "protocol": "TCP"
              }
            ]
          }
        ]
      },
      {
        "toEndpoints": [
          {}
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "foo-deny-external-egress",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "k8s"
      }
    ]
  }
]
```
Which is then translated into
```
$ sudo cilium bpf policy get -n 3633 | sort -u
DIRECTION   IDENTITY   PORT/PROTO   BYTES   PACKETS   
Egress      1          53/TCP       0       0         
Egress      1          53/UDP       0       0         
Egress      1          ANY          0       0         
Egress      2          53/TCP       0       0         
Egress      2          53/UDP       0       0         
Egress      2          ANY          0       0         
Egress      3          53/TCP       0       0         
Egress      3          53/UDP       0       0         
Egress      3          ANY          0       0         
Egress      4          53/TCP       0       0         
Egress      4          53/UDP       0       0         
Egress      4          ANY          0       0         
Egress      43002      53/TCP       0       0         
Egress      43002      53/UDP       0       0         
Egress      43002      ANY          0       0         
Egress      45501      53/TCP       0       0         
Egress      45501      53/UDP       0       0         
Egress      45501      ANY          0       0         
Egress      5          53/TCP       0       0         
Egress      5          53/UDP       0       0         
Egress      5          ANY          0       0         
Egress      59021      53/TCP       0       0         
Egress      59021      53/UDP       0       0         
Egress      59021      ANY          0       0         
Egress      59467      53/TCP       0       0         
Egress      59467      53/UDP       0       0         
Egress      59467      ANY          0       0         
Ingress     1          ANY          0       0         
Ingress     2          ANY          0       0         
Ingress     3          ANY          0       0         
Ingress     4          ANY          0       0         
Ingress     43002      ANY          0       0         
Ingress     45501      ANY          0       0         
Ingress     5          ANY          0       0         
Ingress     59021      ANY          0       0         
Ingress     59467      ANY          0       0
```

Why is an empty namespace selector is translated into allow everything? Is it because of an empty `toEndpoints`? Should we then translated an empty `toEndpoints` into a `reserverd:cluster`?

Needs to be triaged for 1.0.x. Verified with current master.

**Comment by joestringer** [comment] 2018-06-19 18:56
```
        "toEndpoints": [
          {
            "matchLabels": {
              "reserved:all": ""
            }
          }
        ],
```

I suspect that the above selects absolutely everything.

**Comment by tgraf** [comment] 2018-06-19 19:21
Yes, the reserved:all translation looks wrong.

**Comment by aanm** [comment] 2018-06-19 19:46
@joestringer, @tgraf should then 
```
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
```
be translated to:

```
      matchLabels:
            reserved:cluster
```

or better yet:

```
      matchExpressions:
      - {key: 'k8s:io.kubernetes.pod.namespace', operator: Exists}
```

**Comment by joestringer** [comment] 2018-06-19 21:04
@aanm I like the latter. I don't think that `reserved:cluster` will have the intended behaviour, considering its definition (from the docs):
```
reserved:cluster    Any network endpoint inside of the cluster that is not managed by Cilium. Does not include reserved:host.
```

**Comment by ianvernon** [comment] 2018-08-17 17:16
Looking into this. I presume this will need backport to v1.2 as well; adding the label.

**Comment by ianvernon** [comment] 2018-08-17 21:51
To confirm, based off of the commentary from the link provided in the issue description:

> Similar to DENY egress traffic from an application example, this policy allows all outbound traffic on ports 53/udp and 53/tcp for DNS resolution.
to: specifies an empty namespaceSelector. This will select all pods in all namespaces, so the outbound traffic to pods in the cluster will be allowed.
And since they are not listed, traffic to the IP addresses outside the cluster are denied.

"This policy allows all outbound traffic on ports 53/UDP and 53/TCP for DNS resolution" - the policy that we added above to allow to "reserved:all"  on 53/UDP and 53/TCP does precisely this. The language is ambiguous, because "all outbound traffic" to me implies just that - all outbound traffic, regardless of whether it is to a pod or not. The documentation for the `NetworkPolicyEgressRule` `To` field is documented as such:

https://github.com/kubernetes/api/blob/f5c295feaba2cbc946f0bbb8b535fc5f6a0345ee/networking/v1/types.go#L128-L134

Specifically:

>  If this field is empty or missing, this rule matches all destinations (traffic not restricted by destination). 

Again, 'destination' is not implied here. However, since `[]To` is a list of `NetworkPolicyPeer`, which is made up of `PodSelector`, `NamespaceSelector` and `IPBlock`, then I would assume that 'all destinations' means all destinations inside or outside of the cluster. Thus, the first rule:

```
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
```

should not be translated into:

```
matchLabels:
            reserved:cluster
```

or 

```
matchExpressions:
      - {key: 'k8s:io.kubernetes.pod.namespace', operator: Exists}
```

The point of focus here is the second rule:

```
  - to:
    - namespaceSelector: {}
```

> to: specifies an empty namespaceSelector. This will select all pods in all namespaces, so the outbound traffic to pods in the cluster will be allowed.
And since they are not listed, traffic to the IP addresses outside the cluster are denied.

This rule allows egress traffic to all pods in all namespaces, on all ports.

Is it possible that the linked example policy is not written correctly? These are two separate rules, one which allows egress to all destinations on port 53/UDP and port 53/TCP, and to all pods in all namespaces on all ports:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - namespaceSelector: {}
```

Importing the rule and getting the output in JSON reveals that the policy is incorrect:
```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "extensions/v1beta1",
            "kind": "NetworkPolicy",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"NetworkPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"foo-deny-external-egress\",\"namespace\":\"default\"},\"spec\":{\"egress\":[{\"ports\":[{\"port\":53,\"protocol\":\"UDP\"},{\"port\":53,\"protocol\":\"TCP\"}]},{\"to\":[{\"namespaceSelector\":{}}]}],\"podSelector\":{\"matchLabels\":{\"app\":\"foo\"}},\"policyTypes\":[\"Egress\"]}}\n"
                },
                "creationTimestamp": "2018-08-17T21:26:28Z",
                "generation": 1,
                "name": "foo-deny-external-egress",
                "namespace": "default",
                "resourceVersion": "5983",
                "selfLink": "/apis/extensions/v1beta1/namespaces/default/networkpolicies/foo-deny-external-egress",
                "uid": "3409db89-a264-11e8-8786-0800278b5835"
            },
            "spec": {
                "egress": [
                    {
                        "ports": [
                            {
                                "port": 53,
                                "protocol": "UDP"
                            },
                            {
                                "port": 53,
                                "protocol": "TCP"
                            }
                        ]
                    },
                    {
                        "to": [
                            {
                                "namespaceSelector": {}
                            }
                        ]
                    }
                ],
                "podSelector": {
                    "matchLabels": {
                        "app": "foo"
                    }
                },
                "policyTypes": [
                    "Egress"
                ]
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

To fulfill what the author was intending, I think the YAML should be fixed to be the following:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector: {}
```

Dumping the output in JSON confirms this:
```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "extensions/v1beta1",
            "kind": "NetworkPolicy",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"NetworkPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"foo-deny-external-egress\",\"namespace\":\"default\"},\"spec\":{\"egress\":[{\"ports\":[{\"port\":53,\"protocol\":\"UDP\"},{\"port\":53,\"protocol\":\"TCP\"}],\"to\":[{\"namespaceSelector\":{}}]}],\"podSelector\":{\"matchLabels\":{\"app\":\"foo\"}},\"policyTypes\":[\"Egress\"]}}\n"
                },
                "creationTimestamp": "2018-08-17T21:27:21Z",
                "generation": 1,
                "name": "foo-deny-external-egress",
                "namespace": "default",
                "resourceVersion": "6051",
                "selfLink": "/apis/extensions/v1beta1/namespaces/default/networkpolicies/foo-deny-external-egress",
                "uid": "5331b92d-a264-11e8-8786-0800278b5835"
            },
            "spec": {
                "egress": [
                    {
                        "ports": [
                            {
                                "port": 53,
                                "protocol": "UDP"
                            },
                            {
                                "port": 53,
                                "protocol": "TCP"
                            }
                        ],
                        "to": [
                            {
                                "namespaceSelector": {}
                            }
                        ]
                    }
                ],
                "podSelector": {
                    "matchLabels": {
                        "app": "foo"
                    }
                },
                "policyTypes": [
                    "Egress"
                ]
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

Adding the extra `-` in front of `to` makes it a separate egress rule. Thus, we can't change the matchLabels for the rule applying to port 53. I agree though that if the "fixed" version of the rule I applied above is used, that means that the rule automatically only allows traffic to port 53/TCP and port 53/TCP only to all pods in all namespaces (i.e., not outside the cluster). We should definitely handle the empty `NamespaceSelector` case in our policy plumbing, which we currently don't. I patched the code locally and now we have the `MatchExpression` in `to` referenced above:

```
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:app": "foo",
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "egress": [
      {
        "toEndpoints": [
          {
            "matchExpressions": [
              {
                "key": "k8s:io.kubernetes.pod.namespace",
                "operator": "Exists"
              }
            ]
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "53",
                "protocol": "UDP"
              }
            ]
          },
          {
            "ports": [
              {
                "port": "53",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "foo-deny-external-egress",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "k8s"
      }
    ]
  }
]
```

@aanm @tgraf @joestringer please let me know if this is what you had in mind.

**Comment by tgraf** [comment] 2018-08-18 09:16
@ianvernon Agreed. Good analysis.

**Closed as completed** 2018-08-20 19:21 UTC
Labels: kind/bug, priority/high, area/k8s
