### ISSUE TITLE
Cilium panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by a7i** [cilium/cilium#10846] opened 2020-04-03 14:09 UTC
## Bug report

**General Information**

- Cilium version (run `cilium version`): `v1.6.4`
- Kernel version (run `uname -a`): `Linux prod-nyc3-1w4e 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) DigitalOcean Kubernetes `Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
- Link to relevant artifacts (policies, deployments scripts, ...) Stacktrace below

**How to reproduce the issue**

1. Create a Kubernetes CronJob that runs every minute but lasts only a couple of seconds
2. Observe intermittent crashes in Cilium DS on the node that the job gets provisioned.

The job is provisioned in a Kubernetes namespace that has `istio-injection: enabled` with global policy of disabled autoInject.

```
level=info msg="Resolving identity labels (blocking)" containerID=22522ee9e5 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2506 identityLabels="k8s:controller-uid=46a545f1-75b3-11ea-a547-5e05c5bda9ff,k8s:io.cilium.k8s.namespace.labels.app=kubed,k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled,k8s:io.cilium.k8s.namespace.labels.project=syfer,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=api,k8s:job-name=discovery-doc-1585922340" ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 subsys=endpoint
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="Invalid state transition skipped" containerID=22522ee9e5 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2506 endpointState.from=waiting-for-identity endpointState.to=waiting-to-regenerate file=/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 line=444 subsys=endpoint
level=info msg="Allocated new global key" key="k8s:controller-uid=46a545f1-75b3-11ea-a547-5e05c5bda9ff;k8s:io.cilium.k8s.namespace.labels.app=kubed;k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled;k8s:io.cilium.k8s.namespace.labels.project=syfer;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=api;k8s:job-name=discovery-doc-1585922340;" subsys=allocator
level=info msg="Identity of endpoint changed" containerID=22522ee9e5 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2506 identity=21297 identityLabels="k8s:controller-uid=46a545f1-75b3-11ea-a547-5e05c5bda9ff,k8s:io.cilium.k8s.namespace.labels.app=kubed,k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled,k8s:io.cilium.k8s.namespace.labels.project=syfer,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=api,k8s:job-name=discovery-doc-1585922340" ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID=22522ee9e5 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2506 ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 subsys=daemon
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="Rewrote endpoint BPF program" containerID=22522ee9e5 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2506 identity=21297 ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 subsys=endpoint
level=info msg="Successful endpoint creation" containerID=22522ee9e5 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2506 identity=21297 ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 subsys=daemon
level=info msg="Releasing key" key="[k8s:controller-uid=46a545f1-75b3-11ea-a547-5e05c5bda9ff k8s:io.cilium.k8s.namespace.labels.app=kubed k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled k8s:io.cilium.k8s.namespace.labels.project=syfer k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=api k8s:job-name=discovery-doc-1585922340]" subsys=allocator
level=info msg="Releasing key" key="[k8s:controller-uid=46a545f1-75b3-11ea-a547-5e05c5bda9ff k8s:io.cilium.k8s.namespace.labels.app=kubed k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled k8s:io.cilium.k8s.namespace.labels.project=syfer k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=api k8s:job-name=discovery-doc-1585922340]" subsys=kvstorebackend
level=info msg="Released last local use of key, invoking global release" key="[k8s:controller-uid=46a545f1-75b3-11ea-a547-5e05c5bda9ff k8s:io.cilium.k8s.namespace.labels.app=kubed k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled k8s:io.cilium.k8s.namespace.labels.project=syfer k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=api k8s:job-name=discovery-doc-1585922340]" subsys=kvstorebackend
level=info msg="Removed endpoint" containerID=22522ee9e5 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2506 identity=21297 ipv4=10.244.3.6 ipv6= k8sPodName=api/discovery-doc-1585922340-bbqr2 subsys=endpoint
level=info msg="New endpoint" containerID=8a26a6ff2e datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3590 ipv4=10.244.3.49 ipv6= k8sPodName=api/discovery-doc-1585922400-l98tm subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID=8a26a6ff2e datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3590 identityLabels="k8s:controller-uid=6ab1e8fc-75b3-11ea-a547-5e05c5bda9ff,k8s:io.cilium.k8s.namespace.labels.app=kubed,k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled,k8s:io.cilium.k8s.namespace.labels.project=syfer,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=api,k8s:job-name=discovery-doc-1585922400" ipv4=10.244.3.49 ipv6= k8sPodName=api/discovery-doc-1585922400-l98tm subsys=endpoint
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="Invalid state transition skipped" containerID=8a26a6ff2e datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3590 endpointState.from=waiting-for-identity endpointState.to=waiting-to-regenerate file=/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go ipv4=10.244.3.49 ipv6= k8sPodName=api/discovery-doc-1585922400-l98tm line=444 subsys=endpoint
level=info msg="Allocated new global key" key="k8s:controller-uid=6ab1e8fc-75b3-11ea-a547-5e05c5bda9ff;k8s:io.cilium.k8s.namespace.labels.app=kubed;k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled;k8s:io.cilium.k8s.namespace.labels.project=syfer;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=api;k8s:job-name=discovery-doc-1585922400;" subsys=allocator
level=info msg="Identity of endpoint changed" containerID=8a26a6ff2e datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3590 identity=2864 identityLabels="k8s:controller-uid=6ab1e8fc-75b3-11ea-a547-5e05c5bda9ff,k8s:io.cilium.k8s.namespace.labels.app=kubed,k8s:io.cilium.k8s.namespace.labels.istio-injection=enabled,k8s:io.cilium.k8s.namespace.labels.project=syfer,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=api,k8s:job-name=discovery-doc-1585922400" ipv4=10.244.3.49 ipv6= k8sPodName=api/discovery-doc-1585922400-l98tm oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID=8a26a6ff2e datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3590 ipv4=10.244.3.49 ipv6= k8sPodName=api/discovery-doc-1585922400-l98tm subsys=daemon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x1436b7e]

goroutine 30 [running]:
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).needsQuoting(0xc0000d6780, 0x2, 0x8c, 0x1c)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:268 +0x4e
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendValue(0xc0000d6780, 0xc000932090, 0x2faa800, 0xc001916010)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:294 +0x6d
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendKeyValue(0xc0000d6780, 0xc000932090, 0x33ff9a0, 0x6, 0x2faa800, 0xc001916010)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:285 +0x90
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).Format(0xc0000d6780, 0xc000250620, 0xc0000d24b0, 0xc00195bb18, 0x1359306, 0x33842c0, 0xc00195bb18)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:202 +0xa52
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).write(0xc000250620)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:255 +0x81
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000d2480, 0xc000932060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:231 +0x193
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc000250540, 0xc000000004, 0xc00195bce0, 0x1, 0x1)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:268 +0xed
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Info(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:285
github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints(0xc000932030, 0xc000932030)
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:466 +0x1c1
main.(*Daemon).policyUpdateTrigger(0xc0004685a0, 0xc001916000, 0x1, 0x1)
	/go/src/github.com/cilium/cilium/daemon/policy.go:74 +0xe3
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc00050ebe0)
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:210 +0x2d7
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x130
```

**Comment by brb** [comment] 2020-04-03 14:22
Have you tried upgrading to v1.6.8 which should potentially have the fix for the segfault?

**Comment by aanm** [comment] 2020-04-03 14:22
@a7i Please upgrade to at least 1.6.7 as these issues should be fixed in those versions.

**Comment by a7i** [comment] 2020-04-03 15:07
@brb and @aanm - thank you for your prompt feedback.

I am using DigitalOcean Kubernetes and it seems that the DO team had to downgrade Cilium (from 1.6.7 to 1.6.4) due to an operator crash. With that being said, I will still try this on my development cluster and let you know.

[Changelog](https://www.digitalocean.com/docs/kubernetes/changelog/)
```
1.14.10-do.2 (2020-03-17)
Downgrades to system components:
Downgraded to Cilium v1.6.4
The upgrade to v1.6.7 in the previous release caused cilium-operator to crash loop.
```

**Comment by aanm** [comment] 2020-04-03 17:43
@a7i the operator crash was likely caused by not using the deployment file provided with 1.6.7 as it changed from 1.6.6 to 1.6.7.

**Closed as completed** 2020-04-03 19:25 UTC
Labels: kind/community-report

**Comment by waynr** [comment] 2020-06-01 20:47
@a7i :wave: I work on the DOKS team and happened to come across this issue when researching a stack trace similar to what you shared to support another customer with a similar issue on an older version of DOKS. I just wanted to let you know that our latest `1.14` release, `1.14.10-do.3`, now includes Cilium 1.7.3 which should resolve your issue.

We have also fixed the bug in our release process that led to the erroneous/unstable deployment of Cilium 1.6.7 in `1.14.10-do.1` and subsequent revert to Cilium 1.6.4 in `1.14.10-do.2` so we can confirm that our latest clusters with Cilium 1.7.3 run stably.

Thanks for your patience!
