### ISSUE TITLE
Identities are not re-synced after kvstore is deleted

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#7517] opened 2019-03-26 22:39 UTC
1) create a cluster with at least 2 nodes
2) create new endpoint with a new identity in node-1
3) create another endpoint with a different identity than 2) in node-2
4) delete etcd cluster and restart cilium running on node-2
5) run the command `cilium bpf policy get <endpoint-id-of-step-3> -n` in node-2

Verify the security identity of the endpoint created in node-1 is **not** in the output of 5)

Wait 5 minutes (which is the default time to re-sync identities) and verify the security identity it is still missing from the output of `cilium bpf policy get <endpoint-id-of-3> -n`

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: front-1
  labels:
    k8s-app: test
  namespace: apps
spec:
  containers:
  - name: server
    image: docker.io/library/busybox:1.28.4
    command:
    - sleep
    - 300000s
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: node-1
```

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: front-2
  labels:
    k8s-app: test-2
  namespace: apps
spec:
  containers:
  - name: server
    image: docker.io/library/busybox:1.28.4
    command:
    - sleep
    - 300000s
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: node-2
```

```bash
$ kubectl get cep --all-namespaces -o wide | sort -k 4 -h | grep front
apps          front-2                                   3654          48590         false                 false                ready            10.0.0.77    
apps          front-1                                   2702          51072         false                 false                ready            10.0.0.103
```

```bash
$ #The security ID 48590 exist in the policy map because it's the security id of endpoitn 3654
$ kubectl exec -ti -n cilium cilium-72vsw -- cilium bpf policy get 3654 -n | grep 48590
Ingress     48590      ANY          NONE         0       0         
Egress      48590      ANY          NONE         0       0

$ # The security ID 51072 does not exist in the policy map!
$ kubectl exec -ti -n cilium cilium-72vsw -- cilium bpf policy get 3654 -n | grep 51072
$
```

Version test it so far was with ade72c3e4e305fdedd806ba9c5b55e10291616a3 available in the `scale-testing` branch. If someone can replicate this with master I would appreciate!

**Comment by joestringer** [comment] 2019-04-03 20:54
Identities for pods are synced, but AFAICT the identity -> label mapping itself is *not* periodically synced so I could see how this case leads to the IPCache containing the correct ID mapping, but the cilium instance doesn't actually know what that Identity is (its labels) and therefore can't calculate policy against it.

EDIT: Hmm, maybe the `startLocalKeySync()` is actually supposed to handle this case.. we should convert that into a controller for better visibility.

**Comment by tgraf** [comment] 2019-04-03 23:03
I've tested this with master key protection disabled and by deleting all keys in etcd. The master key got re-created on the next sync iteration.

**Comment by joestringer** [comment] 2019-04-04 05:07
I was wondering if we get stuck talking to the wrong etcd instance somehow and hide connection errors.

**Comment by tgraf** [comment] 2019-04-04 11:32
I was able to reproduce the identity slave keys not being re-created when etcd is restarted with the etcd state being deleted before starting etcd again. The problem was tracked down to the etcd lease not being renewed without a Cilium restart. Confirming that a4b29e8ef758957741b25f6f74b0954a0f83c8c7 and 0c6a9e7571c4d54d537aa80dc352c608689b26b6 which is present in v1.4 branch but not in 1.4.2 fixes that problem.

**Comment by joestringer** [comment] 2019-04-08 21:42
@tgraf So this is resolved in Cilium v1.4.3, v1.5.0?

**Comment by tgraf** [comment] 2019-04-08 22:07
> So this is resolved in Cilium v1.4.3, v1.5.0?

Unclear, yet to be confirmed. I've tested that the slave keys get re-created. I have not yet confirmed whether the nodes correctly regain awareness of the identities in their memory caches.

**Comment by tgraf** [comment] 2019-04-17 09:03
Tested this today and all nodes recovered although it required 2 kvstore interval cycles. Removing release-blocker as improving this will require more effort.

**Comment by tgraf** [comment] 2020-01-22 16:27
We have not seen this since. Closing.

**Closed as completed by tgraf** 2020-01-22 16:27 UTC
Labels: priority/high, sig/policy, kind/community-report
