### ISSUE TITLE
K8sPolicyTest Basic Test TLS policy

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#9903] opened 2020-01-20 15:39 UTC
```
Exitcode: 35 
Stdout:
 	 time-> DNS: '0.060932(104.31.77.248)', Connect: '0.061721',Transfer '0.000000', total '0.066138'
Stderr:
 	 *   Trying 104.31.77.248...
	 * TCP_NODELAY set
	 * Connected to swapi.co (104.31.77.248) port 443 (#0)
	 * ALPN, offering http/1.1
	 * successfully set certificate verify locations:
	   CAfile: /cacert.pem
	   CApath: none
	 * TLSv1.2 (OUT), TLS handshake, Client hello (1):
	 } [512 bytes data]
	 * LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to swapi.co:443 
	 * Closing connection 0
	 command terminated with exit code 35
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10115/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Basic_Test_TLS_policy/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10113/testReport/junit/Suite-k8s-1/11/K8sPolicyTest_Basic_Test_TLS_policy/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10111/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Basic_Test_TLS_policy/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10108/testReport/junit/Suite-k8s-1/11/K8sPolicyTest_Basic_Test_TLS_policy/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10108/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Basic_Test_TLS_policy/

**Comment by gandro** [comment] 2020-01-20 19:26
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2739/testReport/junit/Suite-k8s-1/12/K8sPolicyTest_Basic_Test_TLS_policy/

**Comment by aanm** [comment] 2020-01-23 09:08
duplicate of https://github.com/cilium/cilium/issues/9869

**Closed as completed by aanm** 2020-01-23 09:08 UTC
Labels: kind/bug/CI, area/CI, needs/triage
