### ISSUE TITLE
Kubernetes v1.29.0 + Conformance: [FAIL] [sig-network] Services [It] should serve endpoints on same port and different protocols [Conformance] [sig-network, Conformance]

### ISSUE THREAD

**Issue by hswong3i** [cilium/cilium#29913] opened 2023-12-15 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

According to https://github.com/cilium/cilium/issues/9207, when Cilium working with Kubernetes <= v1.28, we need to have follow setup for passing CNCF conformance test:
* https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kube-proxy-hybrid-modes, with `--set kubeProxyReplacement=false`
* https://docs.cilium.io/en/stable/installation/cni-chaining-portmap, with `--set cni.chainingMode=portmap`

For example [my helm setup](https://github.com/alvistack/ansible-role-kube_cilium/commit/91c2c16d066cb43bc495ac1fe7735ab23290f882):
```
helm template cilium cilium/cilium \
    --version 1.14.5 \
    --namespace kube-system \
    --set bpf.preallocateMaps=false \
    --set cleanBpfState=false \
    --set cleanState=false \
    --set cluster.id=0 \
    --set cluster.name=4e8b0505-4c52-57ab-a7f4-481e7ed3a2e3 \
    --set cni.binPath=/usr/libexec/cni \
    --set cni.chainingMode=portmap \
    --set cni.exclusive=true \
    --set enableIPv4Masquerade=true  \
    --set enableIPv6Masquerade=false \
    --set externalIPs.enabled=true \
    --set hostPort.enabled=true \
    --set hostServices.enabled=true \
    --set hubble.enabled=false \
    --set ipam.mode=cluster-pool \
    --set ipam.operator.clusterPoolIPv4MaskSize=24 \
    --set ipam.operator.clusterPoolIPv4PodCIDRList=10.233.64.0/18 \
    --set ipv4.enabled=true \
    --set ipv6.enabled=false \
    --set kubeProxyReplacement=false \
    --set nodePort.enabled=true \
    --set nodeinit.enabled=true \
    --set nodeinit.securityContext.privileged=true \
    --set operator.replicas=1 \
    --set operator.securityContext.privileged=true \
    --set securityContext.privileged=true \
    --set sessionAffinity=true \
    --set sleepAfterInit=false \
    --set tunnel=vxlan \
    | yq . > templates/etc/kubernetes/addons/60-cilium.yml.j2
```

And the result `cilium status`:
```
root@ohrua3ohgh4e-1:~# kubectl -n kube-system exec ds/cilium -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), wait-for-node-init (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.29 (v1.29.0) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    False   [eth0 192.168.121.253 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            portmap
Cilium:                  Ok   1.14.5 (v1.14.5-85db28be)
NodeMonitor:             Disabled
Cilium health daemon:    Ok   
IPAM:                    IPv4: 3/254 allocated from 10.233.64.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       24/24 healthy
Proxy Status:            OK, ip 10.233.64.228, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Disabled
Encryption:              Disabled        
Cluster health:          3/3 reachable   (2023-12-15T08:46:00Z)
```
But the conformance result is now only failed with Kubernetes v1.29.0:
* PASS, v1.27.8: https://github.com/cncf/k8s-conformance/pull/2933
* PASS, v1.28.4: https://github.com/cncf/k8s-conformance/pull/2935
* FAILED, v1.29.0: https://github.com/cncf/k8s-conformance/pull/2937

Now the test failed with below error message:
```
Summarizing 1 Failure:
  [FAIL] [sig-network] Services [It] should serve endpoints on same port and different protocols [Conformance] [sig-network, Conformance]
  test/e2e/network/service.go:3730

Ran 388 of 7407 Specs in 7188.329 seconds
FAIL! -- 387 Passed | 1 Failed | 0 Pending | 7019 Skipped
```

Which should be newly introduced for v1.29.0: https://github.com/kubernetes/kubernetes/commit/826f3a130ae1ddf9ef525a1757edc321aec72d4d

### Cilium Version

```
root@ohrua3ohgh4e-1:~# kubectl -n kube-system exec ds/cilium -- cilium version
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), wait-for-node-init (init), clean-cilium-state (init), install-cni-binaries (init)
Client: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
Daemon: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
```

### Kernel Version

```
root@ohrua3ohgh4e-1:~# uname -a
Linux ohrua3ohgh4e-1 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
root@ohrua3ohgh4e-1:~# kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

### Sysdump

[cilium-sysdump-20231215-085307.zip](https://github.com/cilium/cilium/files/13683215/cilium-sysdump-20231215-085307.zip)

### Anything else?

As https://github.com/kubernetes/kubernetes/pull/120069 stated:
> One project we know will be affected ishttps://github.com/cilium/cilium/issues/9207, but I already presented a solution to the Cilium community in its weekly meeting and I https://github.com/cilium/cilium/pull/26399and a [document clarifying defining the rollout of the feature to avoid upgrade disruptions](https://docs.google.com/document/d/1USB6KnQA2mdJZYxrXn4vvr86hO8V9ItJTgWV7IgHL1A/edit?usp=sharing) since Jun 23

It should be fixed by https://github.com/cilium/cilium/pull/26399

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by embik** [comment] 2024-01-05 13:06
For everyone ending up because they are running into the same problem (as we did), #29521 seems to be the most recent initiative to fix this.

**Comment by hswong3i** [comment] 2024-01-06 03:44
> For everyone ending up here because they are running into the same problem (as we did), #29521 seems to be the most recent initiative to fix this.

No I don't really think so: #29521 is target for case replacing kube-proxy with eBPF, case here is about traditional with kube-proxy style (a.k.a. Flannel like vxlan overlay) but still failed expectedly...

Since I had already reference my successful flannel deployment concept as much as possible for cilium, there must be something still hidden in our side which case this conformance test failed :-(

**Comment by hswong3i** [comment] 2024-01-08 09:02
> Okay, sorry for the noise then. We are encountering the same conformance test issues and I was following references, but then the problem might be more complex than I realised. My apologies.

The key points are:
* `--set kubeProxyReplacement=false`
* `--set cni.chainingMode=portmap`

I am thinking if that because of my `--set sessionAffinity=true` enabled. Since https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#session-affinity mentioned:
> For users who run with kube-proxy (i.e. with Cilium’s kube-proxy replacement disabled), the ClusterIP service loadbalancing when a request is sent from a pod running in a non-host network namespace is still performed at the pod network interface (until [GH#16197](https://github.com/cilium/cilium/issues/16197) is fixed). For this case the session affinity support is disabled by default. To enable the feature, set config.sessionAffinity=true.

Let me give a try and see if any positive effect :-/

**Comment by hswong3i** [comment] 2024-01-21 00:17
> Let me give a try and see if any positive effect :-/

Well, NO, `--set sessionAffinity=true` is required, else even more FAIL cases:
```
Summarizing 6 Failures:
  [FAIL] [sig-network] Services [It] should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance] [sig-network, Conformance]
  test/e2e/network/service.go:262
  [FAIL] [sig-scheduling] SchedulerPredicates [Serial] [It] validates that there exists conflict between pods with same hostPort and protocol but one using 0.0.0.0 hostIP [Conformance] [sig-scheduling, Serial, Conformance]
  test/e2e/scheduling/predicates.go:1154
  [FAIL] [sig-network] Services [It] should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance] [sig-network, Conformance]
  test/e2e/network/service.go:262
  [FAIL] [sig-network] Services [It] should serve endpoints on same port and different protocols [Conformance] [sig-network, Conformance]
  test/e2e/network/service.go:3730
  [FAIL] [sig-network] Services [It] should have session affinity work for NodePort service [LinuxOnly] [Conformance] [sig-network, Conformance]
  test/e2e/network/service.go:262
  [FAIL] [sig-network] Services [It] should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance] [sig-network, Conformance]
  test/e2e/network/service.go:262
```

**Comment by hswong3i** [comment] 2024-01-21 00:40
@aojea @akhilles with current founding, `[FAIL] [sig-network] Services [It] should serve endpoints on same port and different protocols [Conformance] [sig-network, Conformance]` should be get fixed by #26399 or #29521, with both cases of  `--set kubeProxyReplacement=false` or `--set kubeProxyReplacement=true`.

**Comment by squeed** [comment] 2024-01-26 09:26
Hello all,
This is pretty clearly a duplicate of https://github.com/cilium/cilium/issues/9207. So, unless anyone objects, I'm going to close this just to keep the noise down.

**Comment by julianwiedmann** [comment] 2024-02-05 08:51
Closing as per above.

**Closed as completed by julianwiedmann** 2024-02-05 08:51 UTC
Labels: kind/bug, needs/triage, kind/community-report
