### ISSUE TITLE
tcp connection abnormally interrupted， tcp connect reset

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#30674] opened 2024-02-08 06:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. in this env:
vip is 172.19.206.95, located at  172.19.204.8, this host's cilium_host ip is 245.0.5.212, export by metallb
mysql client is 172.18.191.88
mysql server's pod ip is 245.0.9.149 at host 172.19.204.10
2. I have tcpdump on 172.19.204.10's cluster eth0, and pod's eth0, found some problem:
host_204_10.pcap, is decode with vxlan by port 8472
and both search by  tcp.port==32789

![image](https://github.com/cilium/cilium/assets/6076617/d02156a6-89b6-4b06-8e59-2cde4d07f409)

Here is the pcap file:
[_root_host_204_10.pcap(1).gz](https://github.com/cilium/cilium/files/14205228/_root_host_204_10.pcap.1.gz)

[_root_mysql_204_10.pcap.gz](https://github.com/cilium/cilium/files/14205229/_root_mysql_204_10.pcap.gz)

I used to think that the data packets were too big, but after checking the historical data packets, I found that it was normal to have large packets.

![image](https://github.com/cilium/cilium/assets/6076617/cb693c6e-b3ed-4ad8-be84-e01dae92e77e)

So I think it may be that cilium has an abnormality in packet processing.

### Cilium Version

1.12.7

### Kernel Version

4.19

### Kubernetes Version

1.18.17

### Sysdump

Uploading later

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by llhhbc** [comment] 2024-02-08 11:33
cilium sysdump: https://drive.google.com/file/d/1YFvrzZ998S6UMUxrEuEWdhiySWPijWSC/view?usp=drive_link

**Comment by llhhbc** [comment] 2024-02-08 11:37
@lmb During normal tcp communication, an rst packet suddenly appeared, causing the connection to be disconnected. This rst packet was not initiated by the client, and the data packet returned by the server was not returned normally.

**Comment by lmb** [comment] 2024-02-13 09:33
Have you tried newer versions?

**Comment by llhhbc** [comment] 2024-02-18 01:42
This is a production environment and cannot be upgraded at will.

**Comment by llhhbc** [comment] 2024-02-18 01:43
@lmb What other information do you need? I have already uploaded the relevant information.

**Comment by youngnick** [comment] 2024-02-18 22:05
@llhhbc, since the version you are running, there have been 12 releases, each with more than a hundred fixes. There is a reasonable chance that whatever is causing your issue has already been fixed. Without you upgrading to the latest patch release and checking that the problem still exists, it's not possible to do much troubleshooting.

**Comment by llhhbc** [comment] 2024-02-19 01:54
@youngnick At present, this has affected the customer's production system. We need to give the customer a clear conclusion report, including how the problem occurred and whether it has been fundamentally resolved. I'm not sure if it's caused by too many connections, because we don't know the cause now, and we can't reproduce this problem. 

![企业微信截图_17082626672058](https://github.com/cilium/cilium/assets/6076617/7140e644-f732-47c1-994b-a72b590f191e)

And I'm not sure why this map size is so big? Does cilium automatically expand based on the environment?

**Comment by youngnick** [comment] 2024-02-19 02:00
I'm sorry @llhhbc, but we can't help you troubleshoot an issue with your environment.

We _can_ help if you can confirm that there is a bug, and that it persists in the most recent release of Cilium 1.12, 1.12.7, with a reproduction.

**Comment by llhhbc** [comment] 2024-02-19 02:04
@youngnick Because we don’t understand the underlying logic, we can only know the phenomenon now. Moreover, this problem cannot be reproduced in the test environment, so we cannot be sure and cannot narrow down the scope of the problem. Can you help locate the problem? We also want to confirm if the new version has resolved the issue. Can we communicate on slack?  
<img width="407" alt="image" src="https://github.com/cilium/cilium/assets/6076617/984abf08-d09c-4289-bb7e-4376fcbdcee2">

my slack account is longhui.li

**Comment by youngnick** [comment] 2024-02-19 02:10
I'm sorry @llhhbc, but I cannot interactively troubleshoot this issue with you on Slack either. As I said, if you can find a reproduction, then I can assign this issue out to someone. But I am unable to spend time troubleshooting with you.

**Comment by llhhbc** [comment] 2024-02-19 03:22
<img width="930" alt="image" src="https://github.com/cilium/cilium/assets/6076617/810bec0a-1ac4-417e-8660-2ca18337b88f">

**Comment by jschwinger233** [comment] 2024-02-19 06:56
May be worth a try if you still have no clue:

```
sudo pwru --output-tuple --output-meta --filter-track-skb 'host $mysql_pod_ip and port 3306 and tcp[tcpflags]&tcp-rst!=0'
```

**Comment by llhhbc** [comment] 2024-02-21 01:37
@jschwinger233 pwru require kernel > 5.3, this kernel is 4.19

**Comment by llhhbc** [comment] 2024-02-26 06:04
It has been solved. It was other components that modified the cilium data package.

**Closed as completed** 2024-02-26 06:04 UTC
Labels: kind/question, kind/community-report, info-completed

**Comment by jasonaliyetti** [comment] 2024-04-26 19:23
@llhhbc 
> It has been solved. It was other components that modified the cilium data package.

I think I'm seeing something similar.  Can you elaborate on "other components that modified the cilium data package"?
