### ISSUE TITLE
cilium-ingress autogenerated CEC definition removed on k8s ingress deletion

### ISSUE THREAD

**Issue by kastriotdobratiqi** [cilium/cilium#29306] opened 2023-11-21 09:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am using cilium-ingress in shared LB mode as our ingress controller. When doing an ingress deletion the autogenerated cilium-ingress CEC definition gets removed. This does not happen on Background type deletion, but it does for others types (Foreground and Orphan). 
```
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  creationTimestamp: "2023-11-17T10:00:19Z"
  generation: 234
  name: cilium-ingress
  namespace: kube-system
  resourceVersion: "133239285"
  uid: 1f1ef3c1-126d-4e7c-963d-44cf12e20891
spec:
  services:
  - listener: ""
    name: cilium-ingress
    namespace: kube-system
```

In v1.14.3, the cec was not being recreated, but gone once I deleted an ingress. In v1.14.4 it recreates a non-defined cec. 

The following logs were observed:
```
level=debug msg="Handling ingress updated event" ingress=goldilocks-dashboard k8sNamespace=goldilocks subsys=ingress-controller
level=debug msg="Generated model for ingress" forcedShared=false ingress=goldilocks-dashboard k8sNamespace=goldilocks model="&{[] []}" subsys=ingress-controller
level=debug msg="Translated resources for ingress" ciliumEnvoyConfig="&{{ } {cilium-ingress  kube-system    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []} {[0xc000ca9f80] [] []}}" endpoint=nil ingress=goldilocks-dashboard k8sNamespace=goldilocks service=nil subsys=ingress-controller
level=debug msg="Updated CiliumEnvoyConfig for ingress" subsys=ingress-controller
level=debug msg="Handling ingress deleted event" ingress=goldilocks-dashboard k8sNamespace=goldilocks subsys=ingress-controller
level=debug msg="Deleting CiliumEnvoyConfig for ingress" ingress=goldilocks-dashboard k8sNamespace=goldilocks subsys=ingress-controller
level=debug msg="Generated model for ingress" forcedShared=true ingress=goldilocks-dashboard k8sNamespace=goldilocks model="&{[] []}" subsys=ingress-controller
level=debug msg="Translated resources for ingress" ciliumEnvoyConfig="&{{ } {cilium-ingress  kube-system    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []} {[0xc000cfc900] [] []}}" endpoint=nil ingress=goldilocks-dashboard k8sNamespace=goldilocks service=nil subsys=ingress-controller
level=debug msg="No change for existing CiliumEnvoyConfig" ciliumEnvoyConfigName=kube-system/cilium-ingress subsys=ingress-controller
```

This most likely happens due to ownership references. The ingresses are owners of the cec and for those types of deletion whenever an ingress is deleted, it deletes the cec also.

### Cilium Version

v1.14.4

### Kernel Version

5.15

### Kubernetes Version

v1.27.3-gke.1700

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment] 2023-11-21 15:17
Can you explain what the problem is? How should cilium behave differently in your opinion?

**Comment by kastriotdobratiqi** [comment] 2023-11-21 17:23
if it behaves like this, no traffic will come through the cilium-ingress. Sneak peek of how it looks when adding ingresses below:
```
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  creationTimestamp: "2023-11-17T10:00:19Z"
  generation: 238
  name: cilium-ingress
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    kind: Ingress
    name: hubble-ui
    uid: 04a8f543-d89a-4f76-a83f-7f090ddc0732
  - apiVersion: v1
    kind: Ingress
    name: recsys-ingress
    uid: e657f3c7-8f81-4362-8020-f29028d4f1a2
  - apiVersion: v1
    kind: Ingress
    name: recsys-recsys-ingress-canary
    uid: 19f2dd6c-b084-4bd1-9d2a-741f1b477d90
  - apiVersion: v1
    kind: Ingress
    name: lucy-6355
    uid: f8c23849-0543-4196-bf86-ecfec009a8e6
  - apiVersion: v1
    kind: Ingress
    name: lucy-8238
    uid: 9e792ee2-9048-4981-a70b-2cdb9855a203
  - apiVersion: v1
    kind: Ingress
    name: vmagent
    uid: 205ccd51-f82a-4a81-a6dd-cd01229963dd
  - apiVersion: v1
    kind: Ingress
    name: lucy-8033
    uid: 2477d045-1b8f-4807-8d74-3098d4a826a6
...
Now when an ingress is deleted, a new cilium-ingress cec is generated which is empty as reported above. There are multiple ingress owners and all of them are losing traffic if one gets removed.

**Comment by mhofstetter** [comment] 2023-11-24 14:15
Thanks for reporting @kastriotdobratiqi

I can confirm that foreground deletion of shared Cilium Ingresses is broken in `v1.14.3`, `v1.14.4` & `main`. The shared CiliumEnvoyConfig gets rewritten empty due to a wrong condition that checks whether a shared Ingress should be taken into account when re-building the global model for the shared CiliumEnvoyConfig after deleting a shared Ingress.

Should be fixed with: https://github.com/cilium/cilium/pull/29367

**Closed as completed** 2023-11-24 17:15 UTC
Labels: kind/bug, area/k8s, needs/triage, kind/community-report, area/agent, feature/k8s-ingress, info-completed
