### ISSUE TITLE
Cilium log entry needs appropriate log level (info/warn vs ERROR)

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#2797] opened 2018-02-13 06:06 UTC
While debugging source endpoint labels observed as null in the cilium access log, the following ERROR was observed using `kubectl logs cilium-xxxxx':

```
level=info msg="Endpoint policy recalculated" containerID=16ca9971fc endpointID=9765 policyRevision=56
ERROR: logging before flag.Parse: W0213 01:24:16.672084       1 reflector.go:334] github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/factory.go:71: watch of *v2.CiliumNetworkPolicy ended with: too old resource version: 132262 (132768)
```

This `ERROR` was diagnosed as harmless, thus should be logged at a less severe level, like info or warn, to avoid alarming the operator and saving the operator time for investigating the error.

More environment details:
`cilium/cilium:v0.13.1`
```
$kubectl exec -ti cilium-7bx9l -n kube-system cilium version
Client: 1.0.0-rc4 3523143 2018-01-30T17:03:18+01:00 go version go1.9 linux/amd64
Daemon: 1.0.0-rc4 3523143 2018-01-30T17:03:18+01:00 go version go1.9 linux/amd64
$kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aanm** [comment] 2018-02-13 16:57
Duplicate of: https://github.com/cilium/cilium/issues/1977 https://github.com/cilium/cilium/issues/2523

"expected usage pattern" in upstream k8s: https://github.com/kubernetes/kubernetes/issues/55230#issuecomment-342632961

**Closed as completed by aanm** 2018-02-13 16:57 UTC
Labels: priority/medium
