### ISSUE TITLE
Panic found in Nightly test

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#4121] opened 2018-05-16 08:39 UTC
```
  2018-05-15T11:25:35.440555948Z panic: runtime error: invalid memory address or nil pointer dereference
    2018-05-15T11:25:35.440577063Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x16d187d]
    2018-05-15T11:25:35.440580815Z 
    2018-05-15T11:25:35.440583335Z goroutine 5496132 [running]:
    2018-05-15T11:25:35.440585744Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateL3Policy(0xc423884a00, 0x2e16a80, 0xc4220da280, 0xc42138e580, 0x31f, 0xc42319b770, 0xc424eb6c60, 0x42cbc8, 0x6)
    2018-05-15T11:25:35.440588294Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:391 +0x5d
    2018-05-15T11:25:35.440590864Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc423884a00, 0x2e16a80, 0xc4220da280, 0xc4260d7d50, 0x0, 0x0, 0x0)
    2018-05-15T11:25:35.440593232Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:605 +0x30a
    2018-05-15T11:25:35.440595466Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).TriggerPolicyUpdatesLocked(0xc423884a00, 0x2e16a80, 0xc4220da280, 0x0, 0xc2ef1f8af00, 0xc42558f9e0, 0xc420023f90)
    2018-05-15T11:25:35.440597927Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:855 +0x77
    2018-05-15T11:25:35.440600189Z github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1(0x2e16a80, 0xc4220da280, 0xc423884a00, 0xc425f3ad10)
    2018-05-15T11:25:35.440611873Z 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:256 +0x6e
    2018-05-15T11:25:35.440614346Z created by github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates
    2018-05-15T11:25:35.440616646Z 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:254 +0xb2
    2018-05-15T11:25:35.440619316Z level=panic msg="Agent pipe unexpectedly closed, shutting down"
    2018-05-15T11:25:35.440622158Z level=info msg="Stopped reading cilium agent events"```
```
Link: 

https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/207/testReport/k8s-1/9/NightlyPolicies_PolicyEnforcement_default_L3_Ingress_Label_Invalid_L4_Egress_Port_80_UDP_L7_Egress_policy_to__private__Destination_NodePort/

**Comment by ianvernon** [comment] 2018-05-16 15:54
Investigating.

**Comment by ianvernon** [comment] 2018-05-16 16:09
From that build, the commit in master which the tests were ran against is ccd046cfbe139351bb6c596b4ccc87f485e3b7fc . 

The panic is on line 391 of `regenerateL3Policy`. From the aforementioned commit:

https://github.com/cilium/cilium/blob/ccd046cfbe139351bb6c596b4ccc87f485e3b7fc/pkg/endpoint/policy.go#L388-L410

Thus, the endpoint's security identity is nil, yet this function was called. I suspect that a regression was introduced when we moved from using the `Labels` field in the `Consumable` to the endpoint's security identity. 

`regenerateL3Policy` is only called in `regeneratePolicy`. For context:

https://github.com/cilium/cilium/blob/ccd046cfbe139351bb6c596b4ccc87f485e3b7fc/pkg/endpoint/policy.go#L583-L607


There are no `nil` checks if `e.SecurityIdentity` is nil preceding this call to `e.regeneratePolicy`. This means that an endpoint could have had a `Consumable` with a non-zero ID, yet no SecurityIdentity (which I find surprising).

However, in master, this should not happen anymore. 

The logic for `regenerateL3Policy` is the same as it is above in master currently:

https://github.com/cilium/cilium/blob/b18a6222a00e1d41440f586fbb4d73e828113f3e/pkg/endpoint/policy.go#L254-L276

`regeneratePolicy` is called with the `endpoint.Mutex` held.

Within `regeneratePolicy`, is the following logic:

https://github.com/cilium/cilium/blob/b18a6222a00e1d41440f586fbb4d73e828113f3e/pkg/endpoint/policy.go#L435-L458

Note that the function exits before the call to `e.SecurityIdentity` is `nil`. 

Thus, this is fixed in latest master, because the SecurityIdentity is never set to `nil` unless the endpoint's mutex is held.

The endpoint's security identity is only ever modified in the following places:

https://github.com/cilium/cilium/blob/ccd046cfbe139351bb6c596b4ccc87f485e3b7fc/pkg/endpoint/endpoint.go#L1723-L1763

https://github.com/cilium/cilium/blob/ccd046cfbe139351bb6c596b4ccc87f485e3b7fc/pkg/endpoint/policy.go#L949-L988

So, we should never hit this case again in master. The change to use `e.SecurityIdentity` instead of `c.LabelArray` (c is a `Consumable`) was not backported to v1.0, so this fix does not need backporting. 

@tgraf I think this can be closed given that the fix has already been merged to master.

**Closed as completed** 2018-05-16 16:46 UTC
Labels: kind/bug, priority/high
