### ISSUE TITLE
Cilium native hostport only listens on a internal IP, unlike CNI portmap

### ISSUE THREAD

**Issue by dghubble** [cilium/cilium#12116] opened 2020-06-16 18:37 UTC
## Bug report

Cilium v1.8 release candidates include a native bpf hostport feature to replace CNI [portmap](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap) chaining ([#10359](https://github.com/cilium/cilium/issues/10359)) implemented in https://github.com/cilium/cilium/pull/10592. In testing, it seems this feature is a partial implementation of CNI portmap.

When CNI portmap is used in a CNI conflist (with any CNI provider, not just Cilium), Kubernetes Pods that set a hostPort proxy any traffic on that host port to the container.

```
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
```

For example, a PodSpec above would allow the web app to be accessed via multiple host IPs - hostPort maps multiple interface addresses (unless a single hostIP is set https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core).

```
curl 127.0.0.1:80  (works)
curl 10.135.173.170:80 (works)
curl publicipv4:80 (works)
curl [someipv6]:80 (depends)
```

In Cilium v1.8.0-rc3 the hostport feature works as described in docs, but its always picking the node's own internal IP, which doesn't satisfy the use cases CNI portmap had.

```
curl 127.0.0.1:80  (no)
curl 10.135.173.170:80 (works)
curl publicipv4:80 (no)
curl [someipv6]:80 (no)
```

```
cilium service list
...
13   10.135.173.170:80      HostPort       1 => 10.2.0.214:80
```

So its not a bug per-se, more that the implementation isn't a drop-in for CNI portmap yet, unless the node's internal IP is the only address you are interested in. (imo) Most uses of CNI portmap to support containers with hostPort are using it to listen on any of the available host addresses.

* node with a private IP (kubelet internal IP, tunnels) and public IP (interfacing with LBs)
* health checks may expect the hostPort to be available on 127.0.0.1 or ::1 as well
* node with multiple addresses for other reasons

For myself, I have to fallback to certain pods that could use hostPort to just using full hostNetwork.

**General Information**

- Cilium version: 1.8.0-rc3
- Kernel version: 5.6.11
- Orchestration system version: Kubernetes v1.18.3

**Comment by dghubble** [comment] 2020-06-29 04:10
Workaround attempts by setting an explicit `hostIP` field in the [ContainerPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core) spec as `0.0.0.0` will not actually work either, despite appearances.

```
            - name: http
              hostIP: 0.0.0.0
              containerPort: 80
              hostPort: 80
            - name: https
              hostIP: 0.0.0.0
              containerPort: 443
              hostPort: 443
```

```
kubectl exec -it cilium-agent-rplt6 -n kube-system cilium service list
...
14   0.0.0.0:80          HostPort       1 => 10.2.2.154:80      
15   0.0.0.0:443         HostPort       1 => 10.2.2.154:443     
```

```
curl 127.0.0.1:80  (no)
curl 10.135.173.170:80 (no)
curl publicipv4:80 (no)
curl [someipv6]:80 (no)
```

**Comment by soumynathan** [comment] 2020-06-30 22:19
Yes I did validate and I am seeing the same behavior as well for the Hostport. The service is only accessible through the HostIP:Port combination.

**Comment by borkmann** [comment] 2020-07-09 13:10
@dghubble Fixed via #12446. For testing feel free to use `docker.io/cilium/cilium:latest` for the time being until it ends up in `1.8.2`. Thanks for reporting!

**Comment by povils** [comment] 2020-10-30 10:53
Hey! Could this also affect docker0 bridge compatability?
The I am using portmap i am able to reach `curl 172.17.0.1:hostPort`
With cilium BPF implementation I cannot anymore

**Comment by borkmann** [comment] 2020-11-20 16:11
> Hey! Could this also affect docker0 bridge compatability?
> When I am using portmap i am able to reach `curl 172.17.0.1:hostPort`
> With cilium native hosrtport implementation I cannot anymore

Thanks for the report, how does your pod spec look like?

**Comment by povils** [comment] 2020-11-26 12:50
Hey! thanks for looking into it. This is the spec i used to replicate the issue:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8081
`
And what i tried is curl from other pod:
```
curl 172.17.0.1:8081
```

**Comment by dghubble** [comment] 2020-11-26 20:41
The issue I reported was specific to accessing a host port service from the host in question. And was resolved back in v1.18.2 (checked, still correct with Cilium v1.9.0 and Kubernetes v1.19.4).

You're talking about pod-to-pod (possibly cross-node, firewalls, etc) access to a hostport service, so there are a lot of other cases you'll want to rule out. Might be better as a separate issue.

**Comment by ckuduvalli** [comment] 2021-06-28 00:08
We have Cilium version 1.9.4 setup on our cluster. While trying to run sonobuoy conformance tests, one of them is failing. The testname: SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [Conformance]
3 pods are setup along with another hostNetworking pod. From the hostNetworking pod, while trying to connect to localhost, its not able to connect (Connection refused). However, connecting to hostIp is working fine. We have --enable-host-port set to true by default. Kindly help.

**Comment by zuzzas** [comment] 2022-06-17 08:07
The current implementation differs from the one in the portmap plugin.

[Here](https://github.com/containernetworking/plugins/blob/e3d563b0f0833b3f661f1f82cd3cab3f2698812f/plugins/meta/portmap/portmap.go#L230-L244) is the portmap's implementation. As you can see, the destination filter will only apply if port.HostIP is present.

[Here](https://github.com/cilium/cilium/blob/3cc2dd8b0f1209510ba0ef4657a86bc6549efed3/pkg/k8s/watchers/pod.go#L516-L530) is how Cilium implements the same thing. Notice the iteration over IPs that are physically present on OS interfaces. But what if the Node's ExternalIP is ephemeral and is present only in cloud's networking stack? OpenStack does this with Floating IPs.

**Comment by zuzzas** [comment] 2022-06-17 11:00
Can we, perhaps, add addresses from the Node object to the list? Those are set via cloud-controller-manager and always display the correct configuration on the cloud's side.

**Comment by aspsk** [comment] 2022-06-20 09:04
> Can we, perhaps, add addresses from the Node object to the list? Those are set via cloud-controller-manager and always display the correct configuration on the cloud's side.

Hey @zuzzas, as far as I understand, this is enough to add both—internal and external IPs (if present) for the list, right?

Or an anchor IP for a floating IP can be something else than the internal IP? In this case we need to list all addresses assigned to network devices, not only the internal,external pair

**Comment by zuzzas** [comment] 2022-06-20 09:12
That's what I believe.

It's a job for the cloud-controller-manager's code to write these IPs (even ephemeral ones) onto the Node object. They _should_ be correct and sufficient.

**Comment by joestringer** [comment] 2024-09-05 00:11
Looks like this was resolved years ago, closing. If you see something like this again, please reproduce with v1.16.x or later and file a new issue.

**Closed as completed by joestringer** 2024-09-05 00:11 UTC
Labels: kind/bug, priority/high, area/datapath, kind/community-report
