### ISSUE TITLE
Fedora CoreOS 32.x breaks pod-to-host and pod-to-external

### ISSUE THREAD

**Issue by dghubble** [cilium/cilium#12217] opened 2020-06-21 20:43 UTC
## Bug report

**General Information**

- Cilium version: 1.17.5 and 1.8.0-rc4 d27124066
- Kernel version (run `uname -a`)
- Orchestration system version: Kubernetes v1.18.4
- Generate and upload a system zip: No python, NA

Cilium with recent Fedora CoreOS 32.x images (Jun 16 2020) has broken pod-to-host (e.g. cilium-health) and pod-to-external traffic. For a cluster, the local endpoint is always false. Pod to pod traffic is unaffected.

```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.18 (v1.18.4) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [eth0 (DR)]   [NodePort (SNAT, 30000-32767, XDP: DISABLED), HostPort, ExternalIPs, HostReachableServices (TCP, UDP), SessionAffinity]
Cilium:                 Ok      OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 4/255 allocated from 10.2.2.0/24, 
Masquerading:           BPF   [eth0]   10.2.2.0/24
Controller Status:      24/25 healthy
  Name               Last success   Last error   Count   Message
  cilium-health-ep   51m51s ago     26s ago      53      Get "http://10.2.2.84:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)   
Proxy Status:                  OK, ip 10.2.2.31, 0 redirects active on ports 10000-20000
Hubble:                        Disabled
Cluster health:                2/3 reachable   (2020-06-21T20:33:29Z)
  Name                         IP              Reachable   Endpoints reachable
  ip-10-0-38-243 (localhost)   10.0.38.243     true        false
```

For example, a Pod _can_ ping Pods running on its own or other nodes. A Pod _cannot_ ping the local node's cilium host IP or external addresses (no external access).The same applies for TCP, using ICMP for ease.

Pod traffic can be observed from the host on its interface, but doesn't leave the host. 

```
# pod
ping 8.8.8.8

# host
$ sudo tcpdump -i any -n dst 8.8.8.8
04:19:05.475164 IP 10.2.2.210 > 8.8.8.8: ICMP echo request, id 53, seq 1666, length 64
04:19:06.499158 IP 10.2.2.210 > 8.8.8.8: ICMP echo request, id 53, seq 1667, length 64

$ sudo tcpdump -i lxc7aa54a969b78 -n dst 8.8.8.8
04:19:49.507163 IP 10.2.2.210 > 8.8.8.8: ICMP echo request, id 53, seq 1709, length 64

$ sudo tcpdump -i eth0 -n dst 8.8.8.8
nothing
```

On a working cluster, such pod (10.2.1.217) traffic is masqueraded from the host (10.0.39.237). 

```
sudo tcpdump -n -i any dst 8.8.8.8
04:16:18.185317 IP 10.2.1.217 > 8.8.8.8: ICMP echo request, id 109, seq 1542, length 64
04:16:18.185358 IP 10.0.39.237 > 8.8.8.8: ICMP echo request, id 109, seq 1542, length 64
```

I've also tested both iptables and BPF-based masquerade - both affected.  With BPF, `cilium monitor` shows some maybe related errors:

```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 10.2.0.90 -> 10.2.1.231 TimeExceeded(TTLExceeded)
```

I've tested different Cilium versions and configurations, those don't appear to be a cause. Cilium works well in any configs with Fedora CoreOS 31.x images, but 32.x and beyond are all affected (a large diff unfortunatey).

- Fedora CoreOS stable `31.20200517.3.0` (5.6.11) (ok)
- Fedora CoreOS next `32.20200416.1.0` (5.6.2) (affected)
- Fedora CoreOS stable `32.20200601.3.0` (5.6.14) (affected) 

I'd like to report this to the OS maintainers, but at this stage its not a clear report for them (e.g. they likely don't have Kubernetes clusters with Cilium). Does Cilium have other host-related needs or checks I should perform? 

```
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_NETFILTER_XT_TARGET_TPROXY=m
CONFIG_NETFILTER_XT_MATCH_MARK=m
CONFIG_NETFILTER_XT_MATCH_SOCKET=m
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_JIT=y
CONFIG_CRYPTO_SHA1=y
CONFIG_CRYPTO_USER_API_HASH=y
```

PS: Unknown if this applies to Fedora in general, I don't have a setup for that. And no SELinux avc denies.

**Comment by dghubble** [comment] 2020-06-21 21:47
Diffing lsmod btw OS versions doesn't turn up much (`drm`, `dm_multipath`). Diffing `sysctl -a` btw a working FCOS 31 and FCOS 32 system shows some networking changes:

```
< net.ipv4.conf.all.promote_secondaries = 1                                                                                                                                                   
> net.ipv4.conf.all.promote_secondaries = 0                                                                                                                                                   
< net.ipv4.conf.cilium_host.accept_source_route = 1                                                                                                                                           
> net.ipv4.conf.cilium_host.accept_source_route = 0                                                                                                                                           
< net.ipv4.conf.cilium_host.promote_secondaries = 0                                                                                                                                           
> net.ipv4.conf.cilium_host.promote_secondaries = 1                                                                                                                                           
< net.ipv4.conf.cilium_host.rp_filter = 0                                                                                                                                                     
> net.ipv4.conf.cilium_host.rp_filter = 2                                                                                                                                                     
< net.ipv4.conf.cilium_net.accept_source_route = 1                                                                                                                                            
> net.ipv4.conf.cilium_net.accept_source_route = 0                                                                                                                                            
< net.ipv4.conf.cilium_net.promote_secondaries = 0                                                                                                                                            
> net.ipv4.conf.cilium_net.promote_secondaries = 1                                                                                                                                            
< net.ipv4.conf.cilium_net.rp_filter = 0                                                                                                                                                      
> net.ipv4.conf.cilium_net.rp_filter = 2                                                                                                                                                      
< net.ipv4.conf.cilium_vxlan.accept_source_route = 1                                                                                                                                          
> net.ipv4.conf.cilium_vxlan.accept_source_route = 0                                                                                                                                          
< net.ipv4.conf.cilium_vxlan.promote_secondaries = 0                                                                                                                                          
> net.ipv4.conf.cilium_vxlan.promote_secondaries = 1                                                                                                                                          
< net.ipv4.conf.cilium_vxlan.rp_filter = 0                                                                                                                                                    
> net.ipv4.conf.cilium_vxlan.rp_filter = 2    
...
< net.ipv4.conf.lo.accept_source_route = 1                                                                                                                                                    
> net.ipv4.conf.lo.accept_source_route = 0                                                                                                                                                    
< net.ipv4.conf.lo.promote_secondaries = 0                                                                                                                                                    
> net.ipv4.conf.lo.promote_secondaries = 1                                                                                                                                                    
< net.ipv4.conf.lo.rp_filter = 0                                                                                                                                                              
> net.ipv4.conf.lo.rp_filter = 2                                                                                                                                                              
> net.ipv4.conf.lxc1774dab6f952.accept_local = 0
> net.ipv4.conf.lxc1774dab6f952.accept_redirects = 1
> net.ipv4.conf.lxc1774dab6f952.accept_source_route = 0
> net.ipv4.conf.lxc1774dab6f952.arp_accept = 0
> net.ipv4.conf.lxc1774dab6f952.arp_announce = 0
> net.ipv4.conf.lxc1774dab6f952.arp_filter = 0
> net.ipv4.conf.lxc1774dab6f952.arp_ignore = 0
> net.ipv4.conf.lxc1774dab6f952.arp_notify = 0
> net.ipv4.conf.lxc1774dab6f952.bc_forwarding = 0
> net.ipv4.conf.lxc1774dab6f952.bootp_relay = 0
> net.ipv4.conf.lxc1774dab6f952.disable_policy = 0
> net.ipv4.conf.lxc1774dab6f952.disable_xfrm = 0
> net.ipv4.conf.lxc1774dab6f952.drop_gratuitous_arp = 0
> net.ipv4.conf.lxc1774dab6f952.drop_unicast_in_l2_multicast = 0
> net.ipv4.conf.lxc1774dab6f952.force_igmp_version = 0
> net.ipv4.conf.lxc1774dab6f952.forwarding = 1
> net.ipv4.conf.lxc1774dab6f952.igmpv2_unsolicited_report_interval = 10000
> net.ipv4.conf.lxc1774dab6f952.igmpv3_unsolicited_report_interval = 1000
> net.ipv4.conf.lxc1774dab6f952.ignore_routes_with_linkdown = 0
> net.ipv4.conf.lxc1774dab6f952.log_martians = 0
> net.ipv4.conf.lxc1774dab6f952.mc_forwarding = 0
> net.ipv4.conf.lxc1774dab6f952.medium_id = 0
> net.ipv4.conf.lxc1774dab6f952.promote_secondaries = 1
> net.ipv4.conf.lxc1774dab6f952.proxy_arp = 0
> net.ipv4.conf.lxc1774dab6f952.proxy_arp_pvlan = 0
> net.ipv4.conf.lxc1774dab6f952.route_localnet = 0
> net.ipv4.conf.lxc1774dab6f952.rp_filter = 2
> net.ipv4.conf.lxc1774dab6f952.secure_redirects = 1
> net.ipv4.conf.lxc1774dab6f952.send_redirects = 1
> net.ipv4.conf.lxc1774dab6f952.shared_media = 1
> net.ipv4.conf.lxc1774dab6f952.src_valid_mark = 0
> net.ipv4.conf.lxc1774dab6f952.tag = 0
```

**Comment by dghubble** [comment] 2020-06-21 21:57
This relates to systemd 245 and https://github.com/cilium/cilium/issues/10645

Fedora CoreOS `31.20200517.3.0` is systemd 243.8
Fedora CoreOS  `32.20200601.3.0` is systemd 245.4

Manually setting rp_filter as mentioned can be used to restore pod-to-external connectivity.

**Comment by dghubble** [comment] 2020-06-22 03:55
This writeup should apply to Fedora Server 32. Would be good to have Cilium recommend or mention rp_filter requirements?

**Comment by galexrt** [comment] 2020-06-25 20:57
@dghubble I can confirm that, your instructions regarding modifying the `rp_filter = 0` worked for my Fedora 32 (not CoreOS) Kubernetes cluster.

**Comment by qmonnet** [comment] 2020-07-01 11:13
Thanks a lot for the report, and for pinning down the issue! I'm marking this one as a duplicate of #10645.

**Closed as completed by qmonnet** 2020-07-01 11:13 UTC
Labels: kind/duplicate
