### ISSUE TITLE
CI: K8sVerifier Runs the kernel verifier against Cilium's BPF datapath: libbpf: Error in bpf_object__probe_loading():Operation not permitted(1)

### ISSUE THREAD

**Issue by jibi** [cilium/cilium#20288] opened 2022-06-23 08:44 UTC
### Test Name

```shell
K8sVerifier Runs the kernel verifier against Cilium's BPF datapath
```

### Failure Output

```shell
FAIL: Failed to load BPF program bpf_lxc with datapath configuration:
-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_IPSEC=1 -DIP_POOLS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1
```

### Stack Trace

```shell
Expected command: kubectl exec -n default test-verifier -- env TC_PROGS="" XDP_PROGS="" CG_PROGS="" TC_PROGS="bpf_lxc" ./test/bpf/verifier-test.sh 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
```

### Standard Output

```shell
=> Loading bpf_lxc.c:from-container...
```

### Standard Error

```shell
[..]
	 libbpf: prog '__send_drop_notify': unrecognized ELF section name '2/1'
	 libbpf: prog 'tail_icmp6_send_echo_reply': unrecognized ELF section name '2/3'
	 libbpf: prog 'tail_icmp6_send_time_exceeded': unrecognized ELF section name '2/5'
	 libbpf: prog 'tail_icmp6_handle_ns': unrecognized ELF section name '2/4'
	 libbpf: prog 'tail_handle_ipv6_cont': unrecognized ELF section name '2/26'
	 libbpf: prog 'tail_ipv6_ct_egress': unrecognized ELF section name '2/32'
	 libbpf: prog 'tail_handle_ipv6': unrecognized ELF section name '2/10'
	 libbpf: prog 'tail_handle_ipv4_cont': unrecognized ELF section name '2/25'
	 libbpf: prog 'tail_ipv4_ct_egress': unrecognized ELF section name '2/29'
	 libbpf: prog 'tail_handle_ipv4': unrecognized ELF section name '2/7'
	 libbpf: prog 'tail_handle_arp': unrecognized ELF section name '2/6'
	 libbpf: prog 'handle_xgress': unrecognized ELF section name 'from-container'
	 libbpf: prog 'tail_ipv6_policy': unrecognized ELF section name '2/12'
	 libbpf: prog 'tail_ipv6_to_endpoint': unrecognized ELF section name '2/14'
	 libbpf: prog 'tail_ipv6_ct_ingress_policy_only': unrecognized ELF section name '2/31'
	 libbpf: prog 'tail_ipv6_ct_ingress': unrecognized ELF section name '2/30'
	 libbpf: prog 'tail_ipv4_policy': unrecognized ELF section name '2/11'
	 libbpf: prog 'tail_ipv4_to_endpoint': unrecognized ELF section name '2/13'
	 libbpf: prog 'tail_ipv4_ct_ingress_policy_only': unrecognized ELF section name '2/28'
	 libbpf: prog 'tail_ipv4_ct_ingress': unrecognized ELF section name '2/27'
	 libbpf: prog 'handle_policy': unrecognized ELF section name '1/0xffff'
	 libbpf: prog 'handle_to_container': unrecognized ELF section name 'to-container'
	 libbpf: Error in bpf_object__probe_loading():Operation not permitted(1). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
	 libbpf: failed to load object './test/bpf/../../bpf/bpf_lxc.o'
	 Unable to load program
	 command terminated with exit code 1
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/1911/
- ZIP file(s): 
[test_results_Cilium-PR-K8s-1.16-kernel-4.9_1911_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/8965544/test_results_Cilium-PR-K8s-1.16-kernel-4.9_1911_BDD-Test-PR.zip)

### Anything else?

Only observed on 4.9 so far

**Comment by qmonnet** [comment] 2022-06-29 21:13
Unlikely from bpftool, unless I'm mistaken `bpf_lxc` is loaded with `tc`.

This is quite curious, the `EPERM` on the probe could be a rlimit issue, but I can't figure a case for 4.9 where we would either skip the rlimit bump or (assuming we did the bump) overflow `RLIM_INFINITY` :thinking: .

**Comment by pchaigno** [comment] 2022-07-15 11:29
The failure seems limited to 4.9: https://datastudio.google.com/s/o5Gnv9PhT1k (failures on other kernels are because of a bad merge a week ago). It's already happening on v1.12 and happening a lot on master.

**Comment by qmonnet** [comment] 2022-07-15 13:33
It seems that the rlimit bump is not happening.

I expected either libbpf or tc directly to do it. It turns aout that [the rlimit bump](https://github.com/libbpf/libbpf/commit/216eaa760edf06f3521d5d49a419515607c1f38e) in libbpf is more recent than I thought, and [our libbpf fork](https://github.com/cilium/libbpf) doesn't have it. Then iproute2's tc does have a rlimit bump, but [in lib/bpf_legacy.c](https://github.com/cilium/iproute2/blob/b0f3a1a74ae45efd866b12476a4147de90f43ac6/lib/bpf_legacy.c#L1479).

So what probably happened is that at some point our iproute2 version switched to libbpf and stopped raising the rlimit itself; but the libbpf version it uses is ~4 months too old to have libbpf's rlimit bump. So probably no component raises the rlimit, and sometimes, it's not enough.

> The failure seems limited to 4.9

I'm not aware of any difference about rlimit handling on kernel versions (other than the switch to cgroup-based obviously), although we could imagine that the delay for reclaiming the memory when programs/maps are unloaded could be slightly longer on old kernels due to implementation details. Looks like a race anyway, since it doesn't trigger all the time.

Some potential workarounds:
- `ulimit -l` in terminal before launching the tests?
- Upgrade the libbpf fork, then the iproute2 image

**Comment by pchaigno** [comment] 2022-07-18 21:34
Same flake happened again at https://jenkins.cilium.io/job/cilium-master-k8s-1.18-kernel-4.9/1324/testReport/junit/Suite-k8s-1/18/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/.

**Comment by qmonnet** [comment] 2022-08-05 14:45
Still investigating, still uncertain what's going on.

The `bpf()` syscall is here (we don't get `-ENOSYS`, and the related sysctl knob are present - and I can't imagine CONFIG_BPF_SYSCALL being missing on a random basis).

The `sysctl` knobs are as follows (not that it brings much info):

```
root@k8s1:/tmp# cat /proc/sys/kernel/unprivileged_bpf_disabled  
0
root@k8s1:/tmp# cat /proc/sys/net/core/bpf_jit_enable 
0
root@k8s1:/tmp# cat /proc/sys/net/core/bpf_jit_harden 
0
root@k8s1:/tmp# cat /proc/sys/net/core/bpf_jit_limit   
264241152
```

Then, there are not so many places where we're susceptible to get a `-EPERM` from the system call.

- The [syscall](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/bpf/syscall.c?h=v4.9#n827) has `if (!capable(CAP_SYS_ADMIN) && sysctl_unprivileged_bpf_disabled) return -EPERM;``, but we're root and unprivileged is enabled.
- Then [`bpf_prog_load()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/bpf/syscall.c?h=v4.9#n723) has `if (type != BPF_PROG_TYPE_SOCKET_FILTER && !capable(CAP_SYS_ADMIN)) return -EPERM;` but again, we're root and we do attempt to load a socket filter.
- Then if `err = bpf_prog_charge_memlock(prog);` fails, we return `err`: This is currently the best candidate, although I can't figure out why this would fail, given that we raise the soft and hard rlimit (as shown by the `strace` output above).
- Then the following functions are unlikely to return `-EPERM`, if possible at all. I don't think we're reaching `bpf_check()` anyway, because I updated and recompiled libbpf/iproute2 to pass a `log_level`/`log_buf` but the output is empty.

Note that I also tried creating a map with bpftool (patched so it doesn't require map names): **this fails as well** (`strace` below), again with `-EPERM` on the `bpf()` syscall.

```
root@k8s1:/tmp# strace -e bpf /bpftool/src/bpftool map create /sys/fs/bpf/foo type array key 4 value 4 entries 1
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_SOCKET_FILTER, insn_cnt=2, insns=0x7fffffffe240, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS, prog_btf_fd=0, func_info_rec_size=0, func_info=NULL, func_info_cnt=0, line_info_rec_size=0, line_info=NULL, line_info_cnt=0, attach_btf_id=0, attach_prog_fd=0}, 144) = -1 EPERM (Operation not permitted)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_SOCKET_FILTER, insn_cnt=2, insns=0x7fffffffe100, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS, prog_btf_fd=0, func_info_rec_size=0, func_info=NULL, func_info_cnt=0, line_info_rec_size=0, line_info=NULL, line_info_cnt=0, attach_btf_id=0, attach_prog_fd=0}, 116) = -1 EPERM (Operation not permitted)
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_ARRAY, key_size=4, value_size=4, max_entries=1, map_flags=0, inner_map_fd=0, map_name="", map_ifindex=0, btf_fd=0, btf_key_type_id=0, btf_value_type_id=0}, 72) = -1 EPERM (Operation not permitted)
Error: map create failed: Operation not permitted
+++ exited with 255 +++
```

In [`map_create()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/bpf/syscall.c?h=v4.9#n178) as well, `bpf_map_charge_memlock()` is the only candidate I can think of.

I can't trace with `bpftrace` or `bcc` given that I can't load programs.

**Comment by qmonnet** [comment] 2022-08-08 11:12
I've been playing with the following program:

<details><summary>C code</summary>

```c
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/resource.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <linux/bpf.h>

int main(__attribute__((unused))int argc,
         __attribute__((unused))char **argv)
{
        union bpf_attr attr;
        struct rlimit rlim;

        if (getrlimit(RLIMIT_MEMLOCK, &rlim)) {
                printf("getrlimit (1) failed: %s\n", strerror(errno));
                return -1;
        }
        printf("rlmit: cur %lu, max %lu\n", rlim.rlim_cur, rlim.rlim_max);

        rlim.rlim_cur = RLIM_INFINITY;
        rlim.rlim_max = RLIM_INFINITY;
        if (setrlimit(RLIMIT_MEMLOCK, &rlim)) {
                printf("setrlimit failed: %s\n", strerror(errno));
                return -1;
        }

        printf("-------------\n");

        memset(&attr, 0, sizeof(attr));
        attr.map_type = BPF_MAP_TYPE_ARRAY;
        attr.key_size = sizeof(int);
        attr.value_size = sizeof(int);
        attr.max_entries = 1;

        if (syscall(__NR_bpf, BPF_MAP_CREATE, &attr, sizeof(attr)))
                printf("syscall failed: %s\n", strerror(errno));

        printf("-------------\n");

        if (getrlimit(RLIMIT_MEMLOCK, &rlim)) {
                printf("getrlimit (2) failed: %s\n", strerror(errno));
                return -1;
        }
        printf("rlmit: cur %lu, max %lu\n", rlim.rlim_cur, rlim.rlim_max);

        return 0;
}
```
</details>

The kernel code for map creation in 4.9 is the following.

<details><summary>kernel/bpf/syscall.c in 4.9: map_create</summary>

```c
static int map_create(union bpf_attr *attr)
{
	struct bpf_map *map;
	int err;

	err = CHECK_ATTR(BPF_MAP_CREATE);
	if (err)
		return -EINVAL;

	/* find map type and init map: hashtable vs rbtree vs bloom vs ... */
	map = find_and_alloc_map(attr);
	if (IS_ERR(map))
		return PTR_ERR(map);

	atomic_set(&map->refcnt, 1);
	atomic_set(&map->usercnt, 1);

	err = bpf_map_charge_memlock(map);
	if (err)
		goto free_map_nouncharge;

	err = bpf_map_new_fd(map);
	if (err < 0)
		/* failed to allocate fd */
		goto free_map;

	return err;

free_map:
	bpf_map_uncharge_memlock(map);
free_map_nouncharge:
	map->ops->map_free(map);
	return err;
}
```
</details>

I checked that I could reach `find_and_alloc_map()` in the kernel. The `-EPERM` is returned after that, either from `bpf_map_new_fd()` (but I could not find any path leading to `EPERM`) or from `bpf_map_charge_memlock()` (primary suspect).

But since we did bump the memlock rlimit, I don't understand why this is happening.

**Comment by qmonnet** [comment] 2022-08-09 11:50
More considerations:

- First visible in the CI on 15th June this year.

- 99.9% sure it comes from `bpf_map_charge_memlock()` in the case above. I could not trace that particular function (inlined), but I checked that I can go through `find_and_alloc_map()`, and with perf/kretprobes that I never reach `bpf_map_new_fd()`.

- Does it come from a change
    - In the kernel? Unlikely, [we've been using the same image](https://github.com/cilium/packer-ci-build/blame/master/cilium-ubuntu.json) since mid-March.
    - In the pod image? Unlikely, unchanged between January (I think) and July.
    - In iproute2 or bpftool? No, unchanged as well on the period.
    - In `test/k8s/verifier.go`? No, unchanged since January.
    - In `test/bpf/verifier-test.sh`? No, unchanged since February.
    - In a helper function called from the Go code? I couldn't find anything outstanding committed around mid-June, but maybe?

- Kernel bug? Nothing in `dmesg`.

- The `bpf()` syscall _does_ work when we start the VM. The first runs of `./test/bpf/verifier-test.sh` succeed, but at some point it starts failing (and never works again).

So there is likely something in the Go or shell code that change the state of the kernel.

- Too many BPF objects loaded? Unlikely. We can't use `bpftool` to list the programs on 4.9, but the shell script deletes the `cilium-probe` dummy interface that it uses for attaching the programs with `tc`. There's some reclaim delay for the memlock rlimit, but this wouldn't block the manual tests I've done.

- Raising the rlimit memlock somewhere else??

**Comment by pchaigno** [comment] 2022-08-09 15:14
> In iproute2 or bpftool? No, unchanged as well on the period.

I thought we did change bpftool not long before Jibi's report?

**Comment by qmonnet** [comment] 2022-08-09 16:54
> I thought we did change bpftool not long before Jibi's report?

My bad, the bpftool image was updated on June 15th, but is not involved in the failing test anyway.

**Comment by qmonnet** [comment] 2022-08-09 16:57
So I've got a minimal-ish reproducer (tried to shrink it further but didn't manage).

When the VM boots, everything works fine. Once the test-verifier pod is up, I can trigger the permanent `EPERM` with:

```
$ kubectl exec -n default test-verifier -- make -C bpf clean
$ kubectl exec -n default test-verifier -- make -C bpf bpf_host.o KERNEL=49 MAX_HOST_OPTIONS="-DSKIP_DEBUG=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_IPSEC=1 -DIP_POOLS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1"
$ kubectl exec -n default test-verifier -- env TC_PROGS="" XDP_PROGS="" CG_PROGS="" TC_PROGS="bpf_host" bash -x ./test/bpf/verifier-test.sh
```

All section load correctly, but after `to-host` (specifically) is loaded, all other prog loads and map creations return `EPERM`, from the memlock accounting it seems.

Now the object we load and the compile option _are_ important. Other object files don't cause the issue. _The previous step in `test/k8s/verifier.go`_, identical except it also has `-DENABLE_IPV6` when compiling, passes just fine without causing any trouble.

Based on this and on the Git history, I suspect the issue appeared as a consequence of this PR where Paul updated the options we test: https://github.com/cilium/cilium/pull/19938/commits

As for the exact reproducer or the reason it behaves like this, I'm still at a loss. I tried to reproduce the steps from `test/bpf/verifier-test.sh` manually:

```
$ kubectl exec -n default test-verifier ip link add cilium-probe type dummy
$ kubectl exec -n default test-verifier tc qdisc replace dev cilium-probe clsact
$ kubectl exec -n default test-verifier tc filter replace dev cilium-probe ingress bpf da obj ./test/bpf/../../bpf/bpf_host.o sec to-host
```

The above does _not_ reproduce the issue. I'm not sure what's the difference with the script, other than the programs in the previous sections of `bpf_host.o` not being loaded and attached to the interface yet. I'll try loading them all in order next, but each time I corrupt the VM I have to boot `gingko` from start again and it takes time.

**Comment by borkmann** [comment] 2022-08-10 10:16
Back in the days, there was a kernel bug in rlimit/mlock accounting leading to an underflow with subsequent rejection similar to above:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=003461559ef7a9bd0239bae35a22ad8924d6e9ad

Any idea if our 4.9 is affected?

**Comment by qmonnet** [comment] 2022-08-10 16:06
The change of state (`-EPERM`) occurs when we remove all the maps as well as the cilium-probe interface (and with it the attached programs) used for testing (this is why the manual steps above were not enough - I needed the cleaning steps too).

At this point we are suspected a kernel bug, maybe some underflow on the counter for the memlock rlimit which would end up in comparing the current value with a huge `user->locked_vm`, and permanent `EPERM` failure. As mentioned by Daniel above:

> Any idea if our 4.9 is affected?

Alas it's not the one, the fix from your link is already present in 4.9.270 (it was backported to 4.9.214).

So still trying to confirm and find another candidate bug. I'll probably start rebuilding vagrant images with custom `printk`-packed kernels or to check if this goes better with latest 4.9.*.

As a side note, I was never sure if the rlimit was per user or per process; turns out that even though it's per-process for e.g. `mmap()` , there's another per-user counter for perf and BPF (`789f90fcf6b0 ("perf_counter: per user mlock gift")`). Then I'm not really sure how this plays with the per-process limits that we're raising in the tools (bpftool, libbpf, tc etc.). I'll keep searching.

**Comment by qmonnet** [comment] 2022-08-11 10:31
Quick note while looking at reproducing with a custom kernel: It's not necessary to deploy everything with ginkgo or to install K8s/Cilium, I could quickly reproduce using the base image for the CI (cloning the VM that Virtualbox uses as the base for the ginkgo VM), and with only these few steps:

```
root@vagrant:~# git clone https://github.com/cilium/cilium.git
root@vagrant:~# cd cilium/
root@vagrant:~/cilium# make -C bpf bpf_host.o KERNEL=49 MAX_HOST_OPTIONS="-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_IPSEC=1 -DIP_POOLS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1"
root@vagrant:~/cilium# XDP_PROGS="" CG_PROGS="" TC_PROGS="bpf_host" bash -x ./test/bpf/verifier-test.sh
```

Reboot to have `bpf()` work again.

I'll try updating and rebuilding the kernel in that box.

**Comment by qmonnet** [comment] 2022-08-12 01:50
Got it!!

This is an underflow on the rlimit counter indeed. Adding `printk()`s to the kernel, I can observe four program loads charged for 6 pages, but then uncharged for 7. After uncharging those, the rlimit counter (`user->locked_vm`) is at `18446744073709551612` instead of `0`.

Looking at the kernel code, `prog->pages` (the value changing from 6 to 7) can indeed be modified if the BPF program is reallocated. This happens for example if we add new instructions and they don't fit on the last page used by the program. Looking further, [this has been fixed (hi Daniel!) on newer versions](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=5ccb071e97fbd9ffe623a0d3977cc6d013bee93c):

```
bpf: fix overflow in prog accounting

Commit aaac3ba95e4c ("bpf: charge user for creation of BPF maps and
programs") made a wrong assumption of charging against prog->pages.
Unlike map->pages, prog->pages are still subject to change when we
need to expand the program through bpf_prog_realloc(). [...]
```

It is likely that the change in the compilation options from https://github.com/cilium/cilium/pull/19938/commits brought the number of instructions of a program just under a multiple of `PAGE_SIZE`, and it goes over the threshold when the verifier adds the prologue or patches the context accesses.

Now for the bad news: Daniel's fix is in 4.10, but apparently it was never backported to 4.9. I suppose the cleanest way to fix this would be to send a backport, and to update the image to 4.9.y after the patch has been merged.

**Comment by qmonnet** [comment] 2022-08-12 02:56
I checked that [the backport](https://github.com/qmonnet/linux/commit/7e0a1c71ee8fb2468be81c031ae9849716f1cdee) fixes the issue successfully. I can [submit this to `stable`](https://docs.kernel.org/process/stable-kernel-rules.html#option-3) tomorrow.

**Comment by qmonnet** [comment] 2022-08-12 09:28
[Backport submitted to the stable branch for 4.9](https://lore.kernel.org/stable/20220812092211.14446-1-quentin@isovalent.com/t/#u).

**Comment by qmonnet** [comment] 2022-08-14 21:01
Greg took the patch, it's currently [in the queue for 4.9](https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-4.9/bpf-fix-overflow-in-prog-accounting.patch?id=e808357549149bee8666f986da7bd9f8bce14eb2).

**Comment by tklauser** [comment] 2022-08-26 13:33
v4.9.326 was [released](https://lore.kernel.org/stable/166142082744128@kroah.com/T/#m81a65caa1127f1b85977b98d2d368c46e2e2fe14). I've opened https://github.com/cilium/packer-ci-build/pull/345 to bump our 4.9 CI image.

**Comment by qmonnet** [comment] 2022-08-26 15:35
We have a new image, [here is the PR](https://github.com/cilium/cilium/pull/21106) to use update Vagrant's default.

**Closed as completed** 2022-08-26 21:24 UTC
Labels: area/CI, area/datapath, ci/flake
