### ISSUE TITLE
`controller bpf-map-sync-cilium_tunnel_map is failing: 1 map sync errors` on Cilium install

### ISSUE THREAD

**Issue by charles-d-burton** [cilium/cilium#17073] opened 2021-08-06 16:13 UTC
## Bug report
We're testing cilium on one of our clusters  and running into some interesting failure cases.  We're preferentially using the helm chart as it fits in better with our gitops processes than using a CLI does, however the data provided here is reflected from the CLI tool for troubleshooting purposes.  In our test case we're attempting to characterize the behavior of our software while replacing the AWS cni with cilium.  Once that's complete we attempted to roll back to the AWS cni to test whether it was possible and that's where the problems begin.  We currently cannot roll back to AWS cni without every pod starting to throw errors, I think this is due to something not being cleaned up after removal of cilium.  See this slack thread:

https://cilium.slack.com/archives/C53TG4J4R/p1627071803270600

After further testing we found that the cilium CLI is unable to install cilium on our cluster either.  It cannot install cilium, and it cannot remove cilium effectively making our cluster not have networking.  However, we can install via the helm chart and it seems to work fine but we have no rollback strategy for a production cut over.  See this slack thread for more information:

https://cilium.slack.com/archives/C53TG4J4R/p1628177128061300

When running the command `cilium install` it hangs for quite a while then fails and emits this error message:

```bash
cilium install  
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  using Cilium version "v1.10.2"
🔮 Auto-detected cluster name: eks-staging-us-east-1
🔮 Auto-detected IPAM mode: eni
🔮 Auto-detected datapath mode: aws-eni
🔮 Custom datapath mode: aws-eni
🔑 Generating CA...
2021/08/06 09:28:31 [INFO] generate received request
2021/08/06 09:28:31 [INFO] received CSR
2021/08/06 09:28:31 [INFO] generating key: ecdsa-256
2021/08/06 09:28:31 [INFO] encoded CSR
2021/08/06 09:28:31 [INFO] signed certificate with serial number 220032847014399971055879790646596279737113343061
🔑 Generating certificates for Hubble...
2021/08/06 09:28:31 [INFO] generate received request
2021/08/06 09:28:31 [INFO] received CSR
2021/08/06 09:28:31 [INFO] generating key: ecdsa-256
2021/08/06 09:28:31 [INFO] encoded CSR
2021/08/06 09:28:31 [INFO] signed certificate with serial number 554293038363545058406458979153140431620845077855
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         54 errors
 \__/¯¯\__/    Operator:       1 errors
 /¯¯\__/¯¯\    Hubble:         1 warnings
 \__/¯¯\__/    ClusterMesh:    1 warnings
    \__/

DaemonSet         cilium                   Desired: 55, Ready: 55/55, Available: 55/55
Containers:       cilium                   Running: 55
Image versions    cilium                   quay.io/cilium/cilium:v1.10.2: 55
Errors:           cilium                   cilium-hxvrg             controller bpf-map-sync-cilium_tunnel_map is failing since 9s (42x): 1 map sync errors
                  cilium                   cilium-zzbqg             controller bpf-map-sync-cilium_tunnel_map is failing since 34s (42x): 1 map sync errors
                  cilium                   cilium-7cv7t             controller bpf-map-sync-cilium_tunnel_map is failing since 37s (41x): 1 map sync errors
                  cilium                   cilium-9wcbd             controller bpf-map-sync-cilium_tunnel_map is failing since 40s (41x): 1 map sync errors
                  cilium                   cilium-m8wc4             controller bpf-map-sync-cilium_tunnel_map is failing since 19s (42x): 1 map sync errors
                  cilium                   cilium-t8dpf             controller bpf-map-sync-cilium_tunnel_map is failing since 25s (42x): 1 map sync errors
                  cilium                   cilium-g9ttp             controller bpf-map-sync-cilium_tunnel_map is failing since 3s (42x): 1 map sync errors
                  cilium                   cilium-hthtm             controller bpf-map-sync-cilium_tunnel_map is failing since 14s (42x): 1 map sync errors
                  cilium                   cilium-kpqx2             controller bpf-map-sync-cilium_tunnel_map is failing since 18s (42x): 1 map sync errors
                  cilium                   cilium-p99tf             controller bpf-map-sync-cilium_tunnel_map is failing since 21s (42x): 1 map sync errors
                  cilium                   cilium-4dkdh             controller bpf-map-sync-cilium_tunnel_map is failing since 38s (41x): 1 map sync errors
                  cilium                   cilium-cl8nk             controller bpf-map-sync-cilium_tunnel_map is failing since 5s (42x): 1 map sync errors
                  cilium                   cilium-v2p95             controller bpf-map-sync-cilium_tunnel_map is failing since 26s (42x): 1 map sync errors
                  cilium                   cilium-5zgmd             controller bpf-map-sync-cilium_tunnel_map is failing since 1s (42x): 1 map sync errors
                  cilium                   cilium-xww84             controller bpf-map-sync-cilium_tunnel_map is failing since 18s (42x): 1 map sync errors
                  cilium                   cilium-zhlpc             controller bpf-map-sync-cilium_tunnel_map is failing since 31s (42x): 1 map sync errors
                  cilium                   cilium-9h69x             controller bpf-map-sync-cilium_tunnel_map is failing since 4s (42x): 1 map sync errors
                  cilium                   cilium-26tcf             controller bpf-map-sync-cilium_tunnel_map is failing since 36s (41x): 1 map sync errors
                  cilium                   cilium-497gm             controller bpf-map-sync-cilium_tunnel_map is failing since 36s (41x): 1 map sync errors
                  cilium                   cilium-f2jgx             controller bpf-map-sync-cilium_tunnel_map is failing since 10s (42x): 1 map sync errors
                  cilium                   cilium-f9phb             controller bpf-map-sync-cilium_tunnel_map is failing since 8s (42x): 1 map sync errors
                  cilium                   cilium-kbthn             controller bpf-map-sync-cilium_tunnel_map is failing since 10s (42x): 1 map sync errors
                  cilium                   cilium-txkvw             controller bpf-map-sync-cilium_tunnel_map is failing since 26s (42x): 1 map sync errors
                  cilium                   cilium-w9dz4             controller bpf-map-sync-cilium_tunnel_map is failing since 28s (42x): 1 map sync errors
                  cilium                   cilium-4k497             controller bpf-map-sync-cilium_tunnel_map is failing since 40s (41x): 1 map sync errors
                  cilium                   cilium-55hps             controller bpf-map-sync-cilium_tunnel_map is failing since 1s (42x): 1 map sync errors
                  cilium                   cilium-fmv2s             controller bpf-map-sync-cilium_tunnel_map is failing since 11s (42x): 1 map sync errors
                  cilium                   cilium-r4wmt             controller bpf-map-sync-cilium_tunnel_map is failing since 13s (42x): 1 map sync errors
                  cilium                   cilium-r4wmt             controller endpoint-1886-regeneration-recovery is failing since 14s (29x): regeneration recovery failed
                  cilium                   cilium-sgpbc             controller bpf-map-sync-cilium_tunnel_map is failing since 21s (42x): 1 map sync errors
                  cilium                   cilium-zslm9             controller bpf-map-sync-cilium_tunnel_map is failing since 31s (42x): 1 map sync errors
                  cilium                   cilium-6x8zp             controller bpf-map-sync-cilium_tunnel_map is failing since 1s (42x): 1 map sync errors
                  cilium                   cilium-52ts2             controller bpf-map-sync-cilium_tunnel_map is failing since 25s (41x): 1 map sync errors
                  cilium                   cilium-7nj9f             controller bpf-map-sync-cilium_tunnel_map is failing since 5s (42x): 1 map sync errors
                  cilium                   cilium-k2lk8             controller bpf-map-sync-cilium_tunnel_map is failing since 14s (42x): 1 map sync errors
                  cilium                   cilium-72nml             controller bpf-map-sync-cilium_tunnel_map is failing since 2s (42x): 1 map sync errors
                  cilium                   cilium-7n8pj             controller bpf-map-sync-cilium_tunnel_map is failing since 3s (42x): 1 map sync errors
                  cilium                   cilium-mmnj5             controller bpf-map-sync-cilium_tunnel_map is failing since 20s (42x): 1 map sync errors
                  cilium                   cilium-n7wjv             controller bpf-map-sync-cilium_tunnel_map is failing since 16s (42x): 1 map sync errors
                  cilium                   cilium-t57qs             controller bpf-map-sync-cilium_tunnel_map is failing since 24s (42x): 1 map sync errors
                  cilium                   cilium-b8svt             controller bpf-map-sync-cilium_tunnel_map is failing since 39s (41x): 1 map sync errors
                  cilium                   cilium-ft48p             controller bpf-map-sync-cilium_tunnel_map is failing since 9s (42x): 1 map sync errors
                  cilium                   cilium-h79ft             controller bpf-map-sync-cilium_tunnel_map is failing since 9s (42x): 1 map sync errors
                  cilium                   cilium-js5jz             controller bpf-map-sync-cilium_tunnel_map is failing since 14s (42x): 1 map sync errors
                  cilium                   cilium-tsczg             controller bpf-map-sync-cilium_tunnel_map is failing since 25s (42x): 1 map sync errors
                  cilium                   cilium-x5l8s             controller bpf-map-sync-cilium_tunnel_map is failing since 30s (42x): 1 map sync errors
                  cilium                   cilium-c25ft             controller bpf-map-sync-cilium_tunnel_map is failing since 5s (42x): 1 map sync errors
                  cilium                   cilium-ptdw6             controller bpf-map-sync-cilium_tunnel_map is failing since 9s (42x): 1 map sync errors
                  cilium                   cilium-vc2h7             controller bpf-map-sync-cilium_tunnel_map is failing since 28s (42x): 1 map sync errors
                  cilium                   cilium-nrld9             controller bpf-map-sync-cilium_tunnel_map is failing since 21s (42x): 1 map sync errors
                  cilium                   cilium-6bxkr             controller bpf-map-sync-cilium_tunnel_map is failing since 38s (41x): 1 map sync errors
                  cilium                   cilium-l2pp2             controller bpf-map-sync-cilium_tunnel_map is failing since 11s (42x): 1 map sync errors
                  cilium                   cilium-rsdlk             controller bpf-map-sync-cilium_tunnel_map is failing since 15s (42x): 1 map sync errors
                  cilium                   cilium-vqrjs             controller bpf-map-sync-cilium_tunnel_map is failing since 27s (42x): 1 map sync errors
                  cilium-operator          cilium-operator          context deadline exceeded
Warnings:         hubble-relay             hubble-relay             hubble relay is not deployed
                  clustermesh-apiserver    clustermesh-apiserver    clustermesh is not deployed

↩️ Rolling back installation...

Error: Unable to install Cilium: timeout while waiting for status to become successful: context deadline exceeded
```

The rollback in this case also fail leaving the cluster in an unknown state.  In this case we don't have an effective way to completely remove cilium from our system and put the vpc-cni back in place.  Our only option currently is to keep cilium in place.  It's possible that we could cycle all of the nodes out, however that's a pretty drastic move that I would prefer to avoid.  Per the request above we also took a sysdump of cilium.  The first one was during the installation and the second is after the failed installation and failed uninstallation.

**General Information**

 cilium version
cilium-cli: v0.8.5 compiled with go1.16.5 on linux/amd64
cilium image (default): v1.10.2
cilium image (stable): v1.10.3

- Kernel 5.4.129

- kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

EKS 1.20

**How to reproduce the issue**

Unkown, I can only get this behavior on a single cluster.  More confusing still is that we us an IAC system for all of our clusters so they are functionally identical and we do not see this behavior on the others.
[cilium-sysdump-onenode-installing.zip](https://github.com/cilium/cilium/files/6946724/cilium-sysdump-onenode-installing.zip)
[cilium-sysdump-onenode-postfail.zip](https://github.com/cilium/cilium/files/6946725/cilium-sysdump-onenode-postfail.zip)

**Comment by pchaigno** [comment] 2021-09-10 12:22
This looks like a duplicate of https://github.com/cilium/cilium/issues/16488.

**Comment by ese** [comment] 2021-09-13 10:04
I have the same issue in EKS cluster:
kubernetes: `v1.20.7-eks-135321`
kernel: `5.4.141-67.229.amzn2.x86_64`
cilium: `v1.10.4`

I have experienced how the problem appears and disappears without being able to attach the event with a cause that triggers it.

debug log in cilium-agent
```
level=debug msg="Starting new controller" name=bpf-map-sync-cilium_tunnel_map subsys=controller uuid=777a8ef2-cd6c-41a2-97d7-7fb87e510bb8
level=debug msg="Starting periodic BPF map error resolver" file-path=/sys/fs/bpf/tc/globals/cilium_tunnel_map name=cilium_tunnel_map remaining=25 subsys=bpf
level=debug msg="BPF map error resolver completed" duration="100.511µs" file-path=/sys/fs/bpf/tc/globals/cilium_tunnel_map name=cilium_tunnel_map remaining=1 resolved=24 scanned=24 subsys=bpf
level=debug msg="Controller func execution time: 119.999µs" name=bpf-map-sync-cilium_tunnel_map subsys=controller uuid=777a8ef2-cd6c-41a2-97d7-7fb87e510bb8
level=debug msg="Controller run failed" consecutiveErrors=1 error="1 map sync errors" name=bpf-map-sync-cilium_tunnel_map subsys=controller uuid=777a8ef2-cd6c-41a2-97d7-7fb87e510bb8
```

**Comment by aanm** [comment] 2022-01-07 17:48
If it is a duplicate of #16488 this has been fixed by https://github.com/cilium/cilium/pull/18247

**Closed as completed by aanm** 2022-01-07 17:48 UTC
Labels: kind/bug, needs/triage, kind/community-report
