### ISSUE TITLE
CI: Travis CI - Pull Request Build Failed

### ISSUE THREAD

**Issue by xinyuanzzz** [cilium/cilium#17229] opened 2021-08-24 01:01 UTC
## CI failure

This [PR](https://github.com/cilium/cilium/pull/17147) also failed Travis CI - Pull Request. It passed this test on Friday, I only deleted an extra space which was added by mistake and rebased it to upstream today.

```
----------------------------------------------------------------------
FAIL: node_manager_test.go:564: ENISuite.TestNodeManagerManyNodes
node_manager_test.go:615:
    c.Assert(metricsapi.Nodes("in-deficit"), check.Equals, 0)
... obtained int = 1
... expected int = 0
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Discovered new CiliumNode custom resource" name=node2 subsys=ipam
level=info msg="Resolving IP deficit of node" available=0 availableForAllocation=29 availableInterfaces=8 instanceID=i-testNodeManagerMinAllocate20-1 maxIPsToAllocate=10 name=node2 neededIPs=10 remainingInterfaces=8 selectedInterface=f3e28957-4e2a-473a-af84-4a9890b89509 selectedPoolID=s-1 subsys=ipam used=0
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Synchronized ENI information" numInstances=100 numSecurityGroups=2 numSubnets=4 numVPCs=1 subsys=eni
level=info msg="Resolving IP deficit of node" available=10 availableForAllocation=19 availableInterfaces=8 instanceID=i-testNodeManagerMinAllocate20-1 maxIPsToAllocate=10 name=node2 neededIPs=10 remainingInterfaces=8 selectedInterface=f3e28957-4e2a-473a-af84-4a9890b89509 selectedPoolID=s-1 subsys=ipam used=8
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Synchronized ENI information" numInstances=100 numSecurityGroups=2 numSubnets=4 numVPCs=1 subsys=eni
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Discovered new CiliumNode custom resource" name=node2 subsys=ipam
level=info msg="Resolving IP deficit of node" available=0 availableForAllocation=9 availableInterfaces=3 instanceID=i-testNodeManagerMinAllocateAndPreallocate-1 maxIPsToAllocate=10 name=node2 neededIPs=10 remainingInterfaces=3 selectedInterface=5bdc1611-c758-4818-a8b3-ea973f7ba5a6 selectedPoolID=s-1 subsys=ipam used=0
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Resolving IP deficit of node" available=9 availableForAllocation=0 availableInterfaces=2 instanceID=i-testNodeManagerMinAllocateAndPreallocate-1 maxIPsToAllocate=1 name=node2 neededIPs=1 remainingInterfaces=2 selectedInterface= selectedPoolID= subsys=ipam used=0
level=info msg="No more IPs available, creating new ENI" addresses=1 instanceID=i-testNodeManagerMinAllocateAndPreallocate-1 name=node2 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=ipam
level=info msg="Created new ENI" addresses=1 eniID=72b51d0b-497a-4794-a449-e30d77c1510a instanceID=i-testNodeManagerMinAllocateAndPreallocate-1 name=node2 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=ipam
level=info msg="Attached ENI to instance" addresses=1 attachmentID= eniID=72b51d0b-497a-4794-a449-e30d77c1510a index=1 instanceID=i-testNodeManagerMinAllocateAndPreallocate-1 name=node2 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=ipam
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Resolving IP deficit of node" available=10 availableForAllocation=8 availableInterfaces=2 instanceID=i-testNodeManagerMinAllocateAndPreallocate-1 maxIPsToAllocate=1 name=node2 neededIPs=1 remainingInterfaces=2 selectedInterface=72b51d0b-497a-4794-a449-e30d77c1510a selectedPoolID=s-1 subsys=ipam used=10
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Discovered new CiliumNode custom resource" name=node3 subsys=ipam
level=info msg="Resolving IP deficit of node" available=0 availableForAllocation=14 availableInterfaces=4 instanceID=i-testNodeManagerReleaseAddress-1 maxIPsToAllocate=13 name=node3 neededIPs=10 remainingInterfaces=4 selectedInterface=2bfdbc36-701e-4eff-ae03-6c42eb957e9d selectedPoolID=s-1 subsys=ipam used=0
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Resolving IP deficit of node" available=13 availableForAllocation=1 availableInterfaces=4 instanceID=i-testNodeManagerReleaseAddress-1 maxIPsToAllocate=5 name=node3 neededIPs=2 remainingInterfaces=4 selectedInterface=2bfdbc36-701e-4eff-ae03-6c42eb957e9d selectedPoolID=s-1 subsys=ipam used=13
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Resolving IP deficit of node" available=14 availableForAllocation=0 availableInterfaces=3 instanceID=i-testNodeManagerReleaseAddress-1 maxIPsToAllocate=4 name=node3 neededIPs=1 remainingInterfaces=3 selectedInterface= selectedPoolID= subsys=ipam used=13
level=info msg="No more IPs available, creating new ENI" addresses=4 instanceID=i-testNodeManagerReleaseAddress-1 name=node3 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=ipam
level=info msg="Created new ENI" addresses=4 eniID=293235ab-fc73-41d4-a64b-6cffc164ae28 instanceID=i-testNodeManagerReleaseAddress-1 name=node3 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=ipam
level=info msg="Attached ENI to instance" addresses=4 attachmentID= eniID=293235ab-fc73-41d4-a64b-6cffc164ae28 index=1 instanceID=i-testNodeManagerReleaseAddress-1 name=node3 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=ipam
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
level=info msg="Releasing excess IPs from node" available=18 excess=3 instanceID=i-testNodeManagerReleaseAddress-1 name=node3 releasing="[10.93.229.78 10.149.214.48 10.100.39.74]" selectedInterface=2bfdbc36-701e-4eff-ae03-6c42eb957e9d selectedPoolID=s-1 subsys=ipam used=10
level=info msg="Synchronized ENI information" numInstances=1 numSecurityGroups=2 numSubnets=1 numVPCs=1 subsys=eni
OOPS: 15 passed, 1 FAILED
--- FAIL: Test (2.31s)
FAIL
coverage: 3.8% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/aws/eni	2.392s
FAIL
make: *** [Makefile:205: integration-tests] Error 1
The command "./.travis/build.sh" exited with 2.
Done. Your build exited with 1.
```

https://app.travis-ci.com/github/cilium/cilium/jobs/533345815

**Comment by tklauser** [comment] 2021-08-24 06:29
Thanks for the report. This is a duplicate of #11560.

**Closed as completed by tklauser** 2021-08-24 06:29 UTC
Labels: area/CI, ci/flake
