### ISSUE TITLE
Restart cilium-agent will make the pod connection lost  for a while

### ISSUE THREAD

**Issue by yanhongchang** [cilium/cilium#24323] opened 2023-03-13 05:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1、k8s cluster, install cilium with --enable-bgp-control-plane=true
2、label node cilium/bgp-policy=in
3、create CiliumBGPPeeringPolicy
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy-default
spec:
  nodeSelector:
    matchLabels:
      cilium/bgp-policy: in
  virtualRouters:
  - exportPodCIDR: true
    localASN: 12345
    neighbors:
    - peerASN: 12346
      peerAddress: 10.19.x.x/32
    serviceSelector:
      matchExpressions:
      - key: somekeyThatDoesNotExist
        operator: DoesNotExist
```
and the podCIDR announce   normally.

4、delete one of cilium-agent in cluster and will found those pods on the node will ping down .

### Cilium Version

1.13.0

### Kernel Version

5.10

### Kubernetes Version

1.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment] 2023-03-14 05:38
I think the issue is the same as https://github.com/cilium/cilium/issues/24191. If so, please close those one.

**Comment by yanhongchang** [comment] 2023-03-14 06:37
> I think the issue is the same as #24191. If so, please close those one.

I have checked that issue before I commit, I think my issue is different from that one.  in my case, apps will not restart, only ping down for a while.

**Comment by squeed** [comment] 2023-04-03 09:13
Who is pinging whom?

@dylandreimerink is it expected that restarting cilium will cause the peer router to flap and drop connectivity?

**Comment by dylandreimerink** [comment] 2023-04-03 09:33
Yes, I believe this is expected behavior, when the agent restarts we simply shutdown the embedded GoBGP speaker as well. This is because we do not do a graceful restart which would coordinate with peers so routes stay intact while the agent is restarting.

This has unfortunately been the state of things since its initial implementation, see https://github.com/cilium/cilium/issues/19376

I also noticed that you came to the same conclusion @yanhongchang and opened https://github.com/cilium/cilium/issues/24256 which in my opinion would supersede this issue.

**Comment by yanhongchang** [comment] 2023-04-10 01:09
> Yes, I believe this is expected behavior, when the agent restarts we simply shutdown the embedded GoBGP speaker as well. This is because we do not do a graceful restart which would coordinate with peers so routes stay intact while the agent is restarting.
> 
> This has unfortunately been the state of things since its initial implementation, see #19376
> 
> I also noticed that you came to the same conclusion @yanhongchang and opened #24256 which in my opinion would supersede this issue.

yes， the #24256 is mine， is there any plan to support the graceful restart feature？ sometimes， the feature is very userful during maintenance.

**Comment by dylandreimerink** [comment] 2023-04-11 10:12
This is definitely a feature we need to / want to add, I think the feature issue is a better place for that discussion to take place this we are not dealing with a bug but a missing feature.

Closing this issue in favor of https://github.com/cilium/cilium/issues/24256

**Closed as completed by dylandreimerink** 2023-04-11 10:12 UTC
Labels: kind/bug, need-more-info, needs/triage, kind/community-report, area/bgp
