### ISSUE TITLE
CI: NACK received for version 154; waiting for a version update before sending again

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4850] opened 2018-07-16 10:35 UTC
```
 2018-07-13T20:42:44.447513108Z level=warning msg="NACK received for version 154; waiting for a version update before sending again" xdsClientNode="id:\"host~127.0.0.1~no-id~localdomain\" cluster:\"cluster1\" build_version:\"8b3384409fc586c02dc937b9fd6c6fd838796301/1.7.0/Distribution/RELEASE\" " xdsNonce=1 xdsStreamID=2 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicyHosts xdsVersionInfo=
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4937/testReport/junit/k8s-1/10/K8sValidatedDemosTest_Tests_Star_Wars_Demo/
[9acb0442_K8sValidatedDemosTest_Tests_Star_Wars_Demo.zip](https://github.com/cilium/cilium/files/2197278/9acb0442_K8sValidatedDemosTest_Tests_Star_Wars_Demo.zip)

**Comment by aanm** [comment] 2018-07-18 13:40
More info: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5046/

**Comment by rlenglet** [comment] 2018-07-18 16:56
```
$ grep subsys=envoy pod-kube-system-cilium-*-cilium-agent.log | grep -v level=debug | grep -v level=info
pod-kube-system-cilium-fbl22-cilium-agent.log:2018-07-13T20:42:44.432923146Z level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts update rejected: NetworkPolicyHosts: Duplicate host entry '10.10.1.95' for policy 36457, already mapped to 3" subsys=envoy-upstream threadID=1355
pod-kube-system-cilium-fbl22-cilium-agent.log:2018-07-13T20:42:44.432956271Z level=warning msg="[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts rejected: NetworkPolicyHosts: Duplicate host entry '10.10.1.95' for policy 36457, already mapped to 3" subsys=envoy-config threadID=1355
pod-kube-system-cilium-fbl22-cilium-agent.log:2018-07-13T20:42:44.432985232Z level=warning msg="[cilium_host_map.cc:186] Bad NetworkPolicyHosts Configuration" subsys=envoy-config threadID=1355
pod-kube-system-cilium-n6vht-cilium-agent.log:2018-07-13T20:42:44.886698361Z level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts update rejected: NetworkPolicyHosts: Duplicate host entry '10.10.1.95' for policy 36457, already mapped to 3" subsys=envoy-upstream threadID=1118
pod-kube-system-cilium-n6vht-cilium-agent.log:2018-07-13T20:42:44.886701833Z level=warning msg="[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts rejected: NetworkPolicyHosts: Duplicate host entry '10.10.1.95' for policy 36457, already mapped to 3" subsys=envoy-config threadID=1118
pod-kube-system-cilium-n6vht-cilium-agent.log:2018-07-13T20:42:44.886705333Z level=warning msg="[cilium_host_map.cc:186] Bad NetworkPolicyHosts Configuration" subsys=envoy-config threadID=1118
```
This is https://github.com/cilium/cilium/issues/4803. It's not been fixed.

**Comment by rlenglet** [comment] 2018-07-18 16:57
Closing as duplicate of https://github.com/cilium/cilium/issues/4803.

**Closed as completed by rlenglet** 2018-07-18 16:57 UTC
Labels: kind/bug, area/proxy

**Comment by rlenglet** [comment] 2018-07-18 17:22
Same issue with https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5046/:
```
$ grep subsys=envoy pod-kube-system-cilium-*-cilium-agent.log | grep -v level=debug | grep -v level=info | more
pod-kube-system-cilium-9s77h-cilium-agent.log:2018-07-18T13:36:28.403441563Z level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts update rejected: NetworkPolicyHosts: Duplicate host entry '10.10.0.116' for policy 3, already mapped to 3" subsys=envoy-upstream threadID=13859
pod-kube-system-cilium-9s77h-cilium-agent.log:2018-07-18T13:36:28.403463742Z level=warning msg="[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts rejected: NetworkPolicyHosts: Duplicate host entry '10.10.0.116' for policy 3, already mapped to 3" subsys=envoy-config threadID=13859
pod-kube-system-cilium-9s77h-cilium-agent.log:2018-07-18T13:36:28.403494876Z level=warning msg="[cilium_host_map.cc:186] Bad NetworkPolicyHosts Configuration" subsys=envoy-config threadID=13859
...
```
This is still #4803.
