### ISSUE TITLE
Valid CIDR Identities are getting released upon Cilium Agent restart

### ISSUE THREAD

**Issue by carnerito** [cilium/cilium#27210] opened 2023-08-02 09:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have `CililiumClusterwideNetworkPolicy` deployed and Host Firewall enabled. Among other CCNPs that allow Cilium to function normally, I have CCNP that allows access from trusted subnets (private network, home VPN, etc...) and it looks like this:

````
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "whitelisted-cidrs"
spec:
  description: "Allow access from trusted CIDRs"
  nodeSelector:
    matchLabels: {}
  ingress:
  - fromCIDR:
    - "127.0.0.0/8"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "<trusted public ip>:32"
 ```` 

When this policy is applied for the first time everything works as expected. Problem occur 10 minutes after Cilium agent is restarted and is manifested by loosing connectivity to cluster from addresses defined in `whitelisted-cidrs` CCNP.

Since this is huge problem for me because I'm heavily relaying on Cilium Host Firewall feature, I did some investigation and these are my findings:
- Identities associated with CIDRs in `fromCIDR` list are cleared 10 minutes after Cilium agent starts
- [This part of code is responsible for 10 minutes delay](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/daemon/cmd/daemon_main.go#L1757-L1771)
- What actually releases Identity is [localIdentityCache release function](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/identity/cache/local.go#L122-L151)
- It releases Identity if refcount for provided Identity is equal to 1
- In Cilium versions prior to v1.14.0 this function is called only once, and it's called from that delayed goroutine from second bullet point, [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/daemon/cmd/daemon_main.go#L1768)
- This call does not cause Identity to be released because at that point, refcount for given Identity is 2, as it is increased [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/identity/cache/local.go#L88-L91) beforehand
- Difference between v1.14.0 and v.1.13.4 is that in v.1.14 release function is called once more when refcount is 1 which causes given Identity to be released which makes cluster unavailable
- Release function is called second time from ipcache.InjectLabels, [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/ipcache/metadata.go#L332)
- Reason for this is changed logic inside `releaseIdentity` block, [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/ipcache/metadata.go#L266-L284)
- This change is introduced in [this commit](https://github.com/cilium/cilium/commit/c96b9d81a8a679d77f9929e6ed32559a3d54108d)

After I figured out what is happening, I reverted logic in `releaseIdentity` to look like this:
```
	releaseIdentity:
		if entryExists {
			// ...
			if _, ok := idsToAdd[oldID.ID]; !
				previouslyAllocatedIdentities[prefix] = oldID
			}

			// ...
			if prefixInfo == nil && oldID.createdFromMetadata {
				entriesToDelete[prefix] = oldID
			}
		}
```

This change solved the issue, but since I'm new to Cilium code base, I'm not sure will this have some unwanted side effects. If this change looks good, I can submit PR.

### How to reproduce in local Kind cluster
- Checkout Cilium v1.14.0 tag
- Add following snippet to kind-values.yaml: 

````
extraArgs:
  - '--identity-restore-grace-period'
  - '2m'
hostFirewall:
  enabled: "true"
````
- Run `make kind && make kind-image && make kind-install-cilium`
- Apply CCNP with `fromCIDR` rule (like one from above)
- Restart Cilium Agent
- Wait for 2 minutes
- Cluster should become unavailable since fromCIDR identities are released

### Cilium Version

v1.14.0

### Kernel Version

.

### Kubernetes Version

v1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kimma** [comment] 2023-08-03 08:33
Chiming in to say i'm having the same problems.
Looks like any use of fromCIDR or toCIDR is impossible due to this.

The following network policy:
```
    - fromCIDR:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 2a0e:97c0:250::/44
        - 2a02:2c8:f000::/48
        - fd00::/8
      toPorts:
        - ports:
          - port: "8443"
            protocol: TCP
          - port: "8000"
            protocol: TCP
```

Should allow the following traffic, (and has worked flawlessly until upgrade) but it is now denied.
```
Ethernet	{Contents=[..14..] Payload=[..50..] SrcMAC=b6:6a:89:17:4f:7a DstMAC=ae:9d:38:b9:4a:77 EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..28..] Version=4 IHL=5 TOS=0 Length=48 Id=0 Flags=DF FragOffset=0 TTL=61 Protocol=TCP Checksum=60901 SrcIP=10.12.123.10 DstIP=10.12.192.192 Options=[] Padding=[]}
TCP	{Contents=[..28..] Payload=[] SrcPort=53009 DstPort=8443(pcsync-https) Seq=3964054339 Ack=0 DataOffset=7 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=65535 Checksum=44278 Urgent=0 Options=[TCPOption(MSS:1380 0x0564), TCPOption(SACKPermitted:), TCPOption(EndList:)] Padding=[0]}
CPU 08: MARK 0xc881a88a FROM 3257 DROP: 62 bytes, reason Policy denied, identity 16777228->136429, to endpoint 3257
```

**Comment by jwitko** [comment] 2023-08-03 18:41
I think this is the same or very similar to 
https://github.com/cilium/cilium/issues/27176
https://github.com/cilium/cilium/issues/27210

I have the same issue and basically any change to policies triggers this for me at this point.  The nodes assume a new identity within cilium that isn't properly marked as host/remote-node.  

This seems to get the physical servers wedged and I cannot talk other nodes until I stop/start the host interfaces. When I do that the nodes seem to assume a properly marked identity as `host` or `remote-node` as appropriate.  This can become quite the burden if `hostFirewall` is enabled as the identifying CIDRs that I SSH from can also lose their IDs and therefore don't get picked up on the `cidr:10.0.0.0/8` label. 

This also does nothing to fix all the broken/lost IDs for non-hosts. Those are typically stuck in terminating. If I force terminate I am left with the kublet error:
```Warning  FailedCreatePodSandBox  28s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0869e8a2724dbc910f2ea02fadb47297a1f017663725e3e0832d5af79ff9db68": plugin type="cilium-cni" failed (add): unable to create endpoint: Cilium API client timeout exceeded```


There is also an issue with the floating IP that load balancers between the controlplane nodes via `kube-vip`.  Restarting interfaces does not reset the identity of this IP most likely because it does not belong to any interface directly.

**Comment by joestringer** [comment] 2023-08-06 20:10
Hi folks, thanks for the detailed reports and bisection. I've prepared a PR #27255 to solve these issues, and it appears to locally solve the problem for me. If you are able to test out the fix as well, then that could help for us to confirm that the fixes are resolving your reported issues and not introducing other unintended breakages.

The following hotfix images are also available for testing out this fix. These are derived from https://github.com/cilium/cilium/pull/27305, based on the tip of the v1.14 branch (ie including all other fixes slated for the v1.14.1 release to date):

https://github.com/cilium/cilium/actions/runs/5778136016/job/15659097948

## cilium                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/cilium-dev:cidr-identity-refcnt-fix@sha256:0f3300334b7b4b86042cebe9271d959df8066acfd04f48bb9cdee076965bb946`                                                                                                                                                               
                                                                                                                                                                                                                                                                                           
## clustermesh-apiserver                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/clustermesh-apiserver-dev:cidr-identity-refcnt-fix@sha256:3d76b0d8d985c1569197b7feb4aceb2062d2fe50df6811183a9b8a835fe5abc7`                                                                                                                                                
                                                                                                                                                                                                                                                                                           
## docker-plugin                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/docker-plugin-dev:cidr-identity-refcnt-fix@sha256:0c19480912a38943e2703cd2c1772fbc451778f260816c6a058ef3e8e5158314`                                                                                                                                                        
                                                                                                                                                                                                                                                                                           
## hubble-relay                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/hubble-relay-dev:cidr-identity-refcnt-fix@sha256:1be4a8144c244002ac2c413b0be95e3f54d43ffe67dab2983d3f126f4938e71b`                                                                                                                                                         
                                                                                                                                                                                                                                                                                           
## kvstoremesh                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/kvstoremesh-dev:cidr-identity-refcnt-fix@sha256:8ca77f95995093e8cf0cd5176bb1bcbf32711393ab63e4b426509b2ef4c6883d`                                                                                                                                                          
                                                                                                                                                                                                                                                                                           
## operator-alibabacloud                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/operator-alibabacloud-dev:cidr-identity-refcnt-fix@sha256:86bd658544c51f13c105d3fdf7c2413c3fe423c07e1f1d2e858ac57206ed6692`                                                                                                                                                
                                                                                                                                                                                                                                                                                           
## operator-aws                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/operator-aws-dev:cidr-identity-refcnt-fix@sha256:3dcd0686f799025673dda47665c7471c0036ae6fabe43241d3806f8bc118da50`                                                                                                                                                         
                                                                                                                                                                                                                                                                                           
## operator-azure                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/operator-azure-dev:cidr-identity-refcnt-fix@sha256:edc8c7bdf0913ff7c6f0d5df4a695322a3d65e9be7dc103869d3735e25e326ba`                                                                                                                                                       
                                                                                                                                                                                                                                                                                           
## operator-generic                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/operator-generic-dev:cidr-identity-refcnt-fix@sha256:e0506e8e70e401521ebff51e82f7dbaca625bb5c043d0bf1ed0553fb7c4ae2f7`                                                                                                                                                     
                                                                                                                                                                                                                                                                                           
## operator                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                           
`quay.io/cilium/operator-dev:cidr-identity-refcnt-fix@sha256:6fc76b07e4a59e3bf9eae8c5e8adca9df416bb8c976dc0144cd478b22ca67eaa`

**Comment by kimma** [comment] 2023-08-07 07:03
Has been running now for over 30 minutes without any issues with toCIDR/fromCIDR, so looking good from my end at least!
```
cilium-gtqsf                              1/1     Running   0              36m
cilium-s8fg7                              1/1     Running   0              35m
cilium-ztkgd                              1/1     Running   0              36m
```

**Comment by carnerito** [comment] 2023-08-07 07:22
I'm confirming what @kimma said. Looking good now. I've set `identity-restore-grace-period` to `2m`, all toCIDR/fromCIDR identities are surviving agent restarts and the cluster is operational after a grace period expires.

**Comment by jwitko** [comment] 2023-08-07 15:47
Additionally confirmed.  Set `identity-restore-grace-period` to `5m`.  Pods have been up 20+ minutes and no issues.  Deny logs do not show anything unusual, pod logs all look happy.

**Comment by joestringer** [comment] 2023-08-08 00:59
I've prepared fresh images with my v2 via https://github.com/cilium/cilium/pull/27327.

**Closed as completed** 2023-08-10 09:33 UTC
Labels: kind/bug, sig/policy, kind/community-report, area/agent
