### ISSUE TITLE
CI: Conformance-AKS failure

### ISSUE THREAD

**Issue by brlbil** [cilium/cilium#35508] opened 2024-10-23 10:19 UTC
## CI Conformance-AKS has been failing consistently. It times out waiting for the cluster to be ready or IPSec tests when encryption is enabled.

IPSec test times out
```
+ CILIUM_CLI_IMAGE_REPO=quay.io/cilium/cilium-cli-ci
+ CILIUM_CLI_IMAGE_TAG=latest
++ pwd
+ docker run --network host -v /home/runner/.kube/config:/root/.kube/config -v /home/runner/work/cilium/cilium:/root/app -v /home/runner/.aws:/root/.aws -v /home/runner/.azure:/root/.azure -v /home/runner/.config/gcloud:/root/.config/gcloud quay.io/cilium/cilium-cli-ci:b41831060[25](https://github.com/cilium/cilium/actions/runs/11464036848/job/31899358824#step:25:26)e8d0f948ae63618462db69c015f17 cilium connectivity test --flow-validation=disabled --hubble=false --collect-sysdump-on-failure --external-target bing.com. --external-cidr 8.0.0.0/8 --external-ip 8.8.4.4 --external-other-ip 8.8.8.8 --force-deploy --junit-file 'cilium-junits/Installation and Connectivity Test (1.29, eastus, 3, true) - 2.xml' --junit-property 'github_job_step=Run connectivity test with IPSec (1.29, eastus, 3, true)'
🔥 [cilium-cilium-11464036848-1-3] Deleting connectivity check deployments...
⌛ [cilium-cilium-11464036848-1-3] Waiting for namespace cilium-test-1 to disappear
✨ [cilium-cilium-11464036848-1-3] Creating namespace cilium-test-1 for connectivity check...
✨ [cilium-cilium-11464036848-1-3] Deploying echo-same-node service...
✨ [cilium-cilium-11464036848-1-3] Deploying DNS test server configmap...
✨ [cilium-cilium-11464036848-1-3] Deploying same-node deployment...
✨ [cilium-cilium-11464036848-1-3] Deploying client deployment...
✨ [cilium-cilium-11464036848-1-3] Deploying client2 deployment...
✨ [cilium-cilium-11464036848-1-3] Deploying client3 deployment...
✨ [cilium-cilium-11464036848-1-3] Deploying echo-other-node service...
✨ [cilium-cilium-11464036848-1-3] Deploying other-node deployment...
✨ [host-netns] Deploying cilium-cilium-11464036848-1-3 daemonset...
✨ [host-netns-non-cilium] Deploying cilium-cilium-114640[36](https://github.com/cilium/cilium/actions/runs/11464036848/job/31899358824#step:25:37)848-1-3 daemonset...
ℹ️  Skipping tests that require a node Without Cilium
⌛ [cilium-cilium-11464036848-1-3] Waiting for deployment cilium-test-1/client to become ready...
⌛ [cilium-cilium-11464036848-1-3] Waiting for deployment cilium-test-1/client2 to become ready...
⌛ [cilium-cilium-1146[40](https://github.com/cilium/cilium/actions/runs/11464036848/job/31899358824#step:25:41)36848-1-3] Waiting for deployment cilium-test-1/echo-same-node to become ready...
⌛ [cilium-cilium-11464036848-1-3] Waiting for deployment cilium-test-1/client3 to become ready...
⌛ [cilium-cilium-11464036848-1-3] Waiting for deployment cilium-test-1/echo-other-node to become ready...
⌛ [cilium-cilium-11464036848-1-3] Waiting for pod cilium-test-1/client-d48766cfd-6j48h to reach DNS server on cilium-test-1/echo-same-node-6bbbcd7755-z6fwz pod...
⌛ [cilium-cilium-11464036848-1-3] Waiting for pod cilium-test-1/client2-6b89df6c77-bbnq2 to reach DNS server on cilium-test-1/echo-same-node-6bbbcd7755-z6fwz pod...
⌛ [cilium-cilium-11[46](https://github.com/cilium/cilium/actions/runs/11464036848/job/31899358824#step:25:47)4036848-1-3] Waiting for pod cilium-test-1/client3-7f986c467b-rt9jw to reach DNS server on cilium-test-1/echo-same-node-6bbbcd7755-z6fwz pod...
timeout reached waiting for lookup for localhost from pod cilium-test-1/client3-7f986c467b-rt9jw to server on pod cilium-test-1/echo-same-node-6bbbcd7755-z6fwz to succeed (last error: error with exec request (pod=cilium-test-1/client3-7f986c467b-rt9jw, container=): context deadline exceeded)
```
The cluster is not ready
```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       1 errors
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet              cilium-envoy       Desired: 2, Ready: 2/2, Available: 2/2
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay       Desired: 1, Unavailable: 1/1
Containers:            cilium             Running: 2
                       cilium-envoy       Running: 2
                       cilium-operator    Running: 1
                       hubble-relay       Running: 1
Cluster Pods:          11/11 managed by Cilium
Helm chart version:    1.17.0-dev
Image versions         cilium             quay.io/cilium/cilium-ci:7129ec0fc3ebbb36c17377318a5efef9726f83a4: 2
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.30.6-1729608965-1e298fad5ecff399849a689fb0730551afe42422@sha256:4bf4d4dfd23477666d9d2c05b701954df268902d9f31d691e1a0dc85661ac5ac: 2
                       cilium-operator    quay.io/cilium/operator-generic-ci:7129ec0fc3ebbb36c17377318a5efef9726f83a4: 1
                       hubble-relay       quay.io/cilium/hubble-relay-ci:7129ec0fc3ebbb36c17377318a5efef9726f83a4: 1
Errors:                hubble-relay       hubble-relay    1 pods of Deployment hubble-relay are not ready

Error: Unable to determine status:  timeout while waiting for status to become successful: context deadline exceeded
```

Failures:
- https://github.com/cilium/cilium/actions/runs/11475615658
- https://github.com/cilium/cilium/actions/runs/11470466803
- https://github.com/cilium/cilium/actions/runs/11464036848
 
[cilium-sysdumps-11464036848.zip](https://github.com/user-attachments/files/17489270/cilium-sysdumps-11464036848.zip)
[cilium-sysdumps-11470466803.zip](https://github.com/user-attachments/files/17489271/cilium-sysdumps-11470466803.zip)
[cilium-sysdumps-11475615658.zip](https://github.com/user-attachments/files/17489269/cilium-sysdumps-11475615658.zip)

**Comment by joestringer** [comment] 2024-10-24 23:40
It looks like there are different symptoms reported here, are you sure they are related to one another? I understand that they both occurred as part of the same overall workflow, but it doesn't necessarily mean that the symptoms have the same root cause.

I pulled the sysdump from [here](https://github.com/cilium/cilium/actions/runs/11475615658) and opened the sysdump inside for `cilium-sysdump-final-1.28-eastus2-2`. Since hubble-relay is the daemon reporting it never becomes available, I looked at the hubble-relay-*-prev.log. Here's the content:

```
2024-10-23T08:31:58.076158700Z time="2024-10-23T08:31:58.075876598Z" level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
2024-10-23T08:31:58.076269701Z time="2024-10-23T08:31:58.0761174Z" level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.cluster.local:443 dialTimeout:30000000000 retryTimeout:5000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress: log:0xc00038af50 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc0007e92a8 clusterName:cilium-cilium-11475615658-1-2 insecureClient:false observerOptions:[0x259b940 0x259ba20] grpcMetrics:<nil> grpcUnaryInterceptors:[] grpcStreamInterceptors:[]}" subsys=hubble-relay
2024-10-23T08:32:28.081277439Z time="2024-10-23T08:32:28.079790525Z" level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
2024-10-23T08:33:03.080804991Z time="2024-10-23T08:33:03.080651889Z" level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
2024-10-23T08:33:07.753502117Z time="2024-10-23T08:33:07.753064613Z" level=info msg="Stopping server..." subsys=hubble-relay
2024-10-23T08:33:07.753542418Z time="2024-10-23T08:33:07.753266415Z" level=info msg="Server stopped" subsys=hubble-relay
```

For this specific failure, the cluster never becomes ready and therefore the workflow does not proceed to get to the step where the ipsec test is deployed/run. I'm not sure if this was just poor startup timing or something disrupted the hubble initialization but I think that this should be investigated separately from the ipsec pod provisioning issue.

**Comment by joestringer** [comment] 2024-10-24 23:44
For [this case](https://github.com/cilium/cilium/actions/runs/11475615658/job/31933859169#step:25:50) the GitHub workflow logs report:

> Wed, 23 Oct 2024 08:23:55 GMT
⌛ [cilium-cilium-11475615658-1-3] Waiting for pod cilium-test-1/client3-7f986c467b-p9zdw to reach DNS server on cilium-test-1/echo-same-node-6bbbcd7755-wbqzh pod...
> Wed, 23 Oct 2024 08:24:25 GMT
timeout reached waiting for lookup for localhost from pod cilium-test-1/client3-7f986c467b-p9zdw to server on pod cilium-test-1/echo-same-node-6bbbcd7755-wbqzh to succeed (last error: error with exec request (pod=cilium-test-1/client3-7f986c467b-p9zdw, container=): context deadline exceeded)

Investigating the sysdump, I see the file `k8s-pods-20241023-082426.txt` (timestamp implying 08:24:26) with the following line:

> cilium-test-1   client3-7f986c467b-p9zdw              1/1     Running   0          34s   192.168.0.161   aks-nodepool1-88128901-vmss000000   <none>           <none>

This seems like it lines up for the client3 Pod being created at around 08:24:52, which is just three seconds before the cilium CLI attempts to check for readiness. Are we sure that the Pod was ready to receive requests at that time? Does the CLI have retries or will it try once and time out? In the sysdump, the Pod reports that it is Ready. I didn't investigate exactly what the CLI step was trying to do, but that is probably a good next step. Maybe this is just a race condition that needs a bit more flexibility on accounting for test application startup time?

**Comment by pchaigno** [comment] 2024-11-07 16:23
This should have been fixed by https://github.com/cilium/cilium/pull/35806.

**Closed as completed by pchaigno** 2024-11-07 16:23 UTC
Labels: area/CI, ci/flake
