### ISSUE TITLE
Habble ui does not display flows except in kube-system and test-cilium namespaces

### ISSUE THREAD

**Issue by cyxinda** [cilium/cilium#29316] opened 2023-11-22 03:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I use cilium and hubble at first time today.
I install cilium using helm chart.
I find that  only the flows in the kube-system and cilium-test namespace is displayed on the hubble-ui page, and the flows in other namespaces is not displayed.
It has error log such as "No flows found for xxxx namespace. Will continue to monitor for new flows…". 
![截图 2023-11-20 17-48-25](https://github.com/cilium/cilium/assets/7237898/b3826fca-83e9-4ec4-aace-b6a4b784eb67)
![截图 2023-11-22 11-02-53](https://github.com/cilium/cilium/assets/7237898/f7ce2ca3-1d77-4a54-afb3-d815ee466049)

exclude the  kube-system and cilium-test namespace ,there are nothing on the page of hubble ui.
![截图 2023-11-22 11-03-11](https://github.com/cilium/cilium/assets/7237898/d6444ea4-482f-46d9-a3c3-18f1c1413d3b)

I don't know where I went wrong.Do you know the cause of this problem ?

### Cilium Version

[root@sc-master-1 network]# cilium version
cilium-cli: v0.15.14 compiled with go1.21.4 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.4
cilium image (running): 1.14.4
[root@sc-master-1 cilium]# cilium status 
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium             Desired: 17, Ready: 17/17, Available: 17/17
Containers:            cilium             Running: 17
                       hubble-ui          Running: 1
                       cilium-operator    Running: 2
                       hubble-relay       Running: 1
Cluster Pods:          8/110 managed by Cilium
Helm chart version:    1.14.4
Image versions         cilium             quay.io/cilium/cilium:v1.14.4: 17
                       hubble-ui          quay.io/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.14.4: 2
                       hubble-relay       quay.io/cilium/hubble-relay:v1.14.4: 1

### Kernel Version

[root@sc-master-1 ~]# uname -a
Linux sc-master-1 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

[root@sc-master-1 cilium]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.14", GitCommit:"a5967a3c4d0f33469b7e7798c9ee548f71455222", GitTreeState:"clean", BuildDate:"2023-09-13T09:12:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.14", GitCommit:"a5967a3c4d0f33469b7e7798c9ee548f71455222", GitTreeState:"clean", BuildDate:"2023-09-13T09:04:55Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20231121-213020-1.tar.gz](https://github.com/cilium/cilium/files/13433017/cilium-sysdump-20231121-213020-1.tar.gz)
[cilium-sysdump-20231121-213020-2.tar.gz](https://github.com/cilium/cilium/files/13433018/cilium-sysdump-20231121-213020-2.tar.gz)

`tar -zxvf cilium-sysdump-20231121-213020-1.tar.gz `
`tar -zxvf cilium-sysdump-20231121-213020-2.tar.gz `

My helm values.yaml of cilium is bellow:
[values.yaml](https://github.com/cyxinda/tmp/blob/main/cilium/values.yaml)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coleenquadros** [comment] 2023-11-22 08:48
Was hubble installed after the service was installed? In that case you will have to delete your pods/service for cilium/hubble to pick it up?
Can you try `cilium hubble disable `and then `cilium hubble enable --ui?`

**Comment by cyxinda** [comment] 2023-11-22 09:00
> Was hubble installed after the service was installed? In that case you will have to delete your pods/service for cilium/hubble to pick it up? Can you try `cilium hubble disable `and then `cilium hubble enable --ui?`

I install cilium with helm .
I try it in your way,the problem is still exists.
```bash
[root@sc-master-1 ~]# cilium hubble disable
[root@sc-master-1 ~]# kubectl -n kube-system get po |grep hubble
[root@sc-master-1 ~]# 
[root@sc-master-1 ~]# 
[root@sc-master-1 ~]# cilium hubble enable --ui
[root@sc-master-1 ~]# kubectl -n kube-system get po |grep hubble
hubble-relay-84bbc6849d-c2wvg         1/1     Running   0             2s
hubble-ui-7589578bdc-889mv            2/2     Running   0             2s
```
![截图 2023-11-22 17-00-38](https://github.com/cilium/cilium/assets/7237898/a4e5cb1a-e569-4606-b76e-237092cf370c)

**Comment by coleenquadros** [comment] 2023-11-22 10:15
https://docs.cilium.io/en/stable/network/kubernetes/concepts/ - it says here 

```
In case pods were already running before the Cilium [DaemonSet](https://docs.cilium.io/en/stable/glossary/#term-DaemonSet) was deployed, these pods will still be connected using the previous networking plugin according to the CNI configuration. A typical example for this is the kube-dns service which runs in the kube-system namespace by default.

A simple way to change networking for such existing pods is to rely on the fact that Kubernetes automatically restarts pods in a Deployment if they are deleted, so we can simply delete the original kube-dns pod and the replacement pod started immediately after will have networking managed by Cilium. In a production deployment, this step could be performed as a rolling update of kube-dns pods to avoid downtime of the DNS service
```

**Comment by rolinh** [comment] 2023-11-24 16:55
Duplicate of https://github.com/cilium/hubble/issues/1300, closing. Please, do not open the same issue twice in two different repositories.

**Closed as not planned by rolinh** 2023-11-24 16:55 UTC
Labels: kind/bug, needs/triage, kind/community-report, info-completed

**Comment by cyxinda** [comment] 2023-11-29 02:30
> https://docs.cilium.io/en/stable/network/kubernetes/concepts/ - it says here
> 
> ` In case pods were already running before the Cilium [DaemonSet](https://docs.cilium.io/en/stable/glossary/#term-DaemonSet) was deployed, these pods will still be connected using the previous networking plugin according to the CNI configuration. A typical example for this is the kube-dns service which runs in the kube-system namespace by default.
> 
> A simple way to change networking for such existing pods is to rely on the fact that Kubernetes automatically restarts pods in a Deployment if they are deleted, so we can simply delete the original kube-dns pod and the replacement pod started immediately after will have networking managed by Cilium. In a production deployment, this step could be performed as a rolling update of kube-dns pods to avoid downtime of the DNS service `

Perhaps, I did not clean up the pods of the previous calico network in time, which caused this problem to occur.

When I change some config , and delete the pod with the previous calico network ,there are some flows on the hubble page.
I'm not sure if this has anything to do with the configuration I modified.
My helm config as follow:
[https://github.com/cyxinda/tmp/blob/main/cilium/values2.yaml](https://github.com/cyxinda/tmp/blob/main/cilium/values2.yaml).
But When I add come annotations to the app pod as the [cilium document](https://docs.cilium.io/en/stable/observability/visibility/#proxy-visibility)  ,I found no L7 flows on the page of hubble.
```bash
[root@sc-midware-2 ~]# kubectl annotate pod app-64c69fc99f-zxkgt -n moli-india policy.cilium.io/proxy-visibility="<Egress/80/TCP/HTTP>,<Ingress/80/TCP/HTTP>" --overwrite
pod/app-64c69fc99f-zxkgt annotated
```
I send a http request to the service 
```bash
cyxinda@oldsix:~$ curl --location 'http://india.knowdee.com/greeting?name=Jack'
{"chartInfo":{"chartVersion":"0.0.4","appVersion":"2.0.0","chartName":"app","namespace":"moli-india"},"dbInfo":{"url":"jdbc:mysql://mysql:3306/prometheus-example?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true","username":"root","password":"123456789"},"userInfo":{"id":"Jack","age":38,"height":432,"weight":333}}
```
There are no http flows of the 7 layers except  the tcp flows from the app pod to mysql .
![截图 2023-11-29 10-18-48](https://github.com/cilium/cilium/assets/7237898/346c39f0-e6d1-4083-bcd3-24332d54401c)
