### ISSUE TITLE
Cilium 1.11.2. API Rate limit stopped working

### ISSUE THREAD

**Issue by Antiarchitect** [cilium/cilium#18973] opened 2022-02-28 14:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is Helm chart values.yaml piece:

```
  extraArgs:
    - "--api-rate-limit=endpoint-create=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-delete=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-get=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-list=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endponit-patch=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
```

It worked on 1.11.1 and in 1.11.2 I have:

```
level=fatal msg="unable to parse api-rate-limit: 'endpoint-list=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true,endponit-patch=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true,endpoint-create=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true,endpoint-delete=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true,endpoint-get=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true' is not formatted as key=value,key1=value1" subsys=config
```

How to set API rate limits properly now?

### Cilium Version

1.11.2

### Kernel Version

Linux worker-1.prod.xxx 5.15.7-1.el7.elrepo.x86_64 #1 SMP Mon Dec 6 12:52:14 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment] 2022-02-28 15:10
@Antiarchitect try this instead:
```
  extraArgs:
    - "--api-rate-limit=endpoint-create=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-delete=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-get=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-list=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
    - "--api-rate-limit=endpoint-patch=rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true"
```

**Comment by Antiarchitect** [comment] 2022-02-28 15:15
I saw the typo. Fixed but the same.

**Comment by sayboras** [comment] 2022-03-02 14:07
you are right, the mentioned commit is really the cause here, let me dig deeper.

**Comment by sayboras** [comment] 2022-03-02 14:24
can you try to with below json format as a workaround ? Sorry for any inconvenience caused

```
extraArgs:
  - "--api-rate-limit={\"endpoint-create\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-delete\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-get\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-list\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-patch\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\"}"
```

**Comment by Antiarchitect** [comment] 2022-03-02 14:48
Now it says:

```
cilium-agent level=fatal msg="unable to parse api-rate-limit: invalid character '=' after top-level value" subsys=config
```

**Comment by sayboras** [comment] 2022-03-02 15:18
I just tested locally, extraConfig can be used as per below

```
extraConfig:
  "api-rate-limit": "{\"endpoint-create\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-delete\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-get\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-list\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-patch\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\"}"

```


<details>
<summary>cilium bootstrap logs</summary>

```
level=info msg="option bpf-nat-global-max set by dynamic sizing to 591611" subsys=config
level=info msg="option bpf-neigh-global-max set by dynamic sizing to 591611" subsys=config
level=info msg="option bpf-sock-rev-map-max set by dynamic sizing to 295805" subsys=config
level=info msg="  --agent-health-port='9876'" subsys=daemon
level=info msg="  --agent-labels=''" subsys=daemon
level=info msg="  --allocator-list-timeout='3m0s'" subsys=daemon
level=info msg="  --allow-icmp-frag-needed='true'" subsys=daemon
level=info msg="  --allow-localhost='auto'" subsys=daemon
level=info msg="  --annotate-k8s-node='true'" subsys=daemon
level=info msg="  --api-rate-limit='{\"endpoint-create\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-delete\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-get\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-list\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-patch\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\"}'" subsys=daemon
level=info msg="  --arping-refresh-period='30s'" subsys=daemon
```

</details>

**Comment by Antiarchitect** [comment] 2022-03-02 18:12
@sayboras 

```
level=info msg="  --api-rate-limit='{\"endpoint-create\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-delete\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-get\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-list\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\",,\"endpoint-patch\":,\"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\"}'" subsys=daemon
```

Worked like a charm! Thank you so much @sayboras !

**Comment by aanm** [comment] 2022-03-03 00:02
@Antiarchitect can we close this GH issue?

**Comment by kaworu** [comment] 2022-03-04 10:09
@aanm @sayboras my understanding is that a regression or breaking change was introduced, and the alternative JSON syntax was proposed as a workaround here. If correct, I think this issue should stay open until fixed. In the former case (a regression) then the flag parsing logic should be fixed, and in the latter (a breaking change) then we should have an upgrade note about it and also update our documentation accordingly (at least [here](https://github.com/cilium/cilium/blob/6c15df9a1ad978427fc291c1e3ab681faa8342d0/Documentation/configuration/api-rate-limiting.rst#configuration) and [here](https://github.com/cilium/cilium/blob/6c15df9a1ad978427fc291c1e3ab681faa8342d0/daemon/cmd/daemon_main.go#L1019)). Does that sound reasonable?

**Comment by michi-covalent** [comment] 2022-05-24 00:01
(adding a comment here instead of opening a new issue because the root cause seems to be related)

i have this in configmap:
```
  subnet-tags-filter: |
    {"type":"private"}
```
after upgrading from v1.10.11 to v1.11.5, cilium-operator started failing with this error:
```
level=fatal msg="Incorrect config-map flag subnet-tags-filter" error="{\"type\":\"private\"} must be formatted as key=value" subsys=config
```

changing the value to:
```
  subnet-tags-filter: type=private
```
fixes the issue.

**Comment by sayboras** [comment] 2022-05-24 05:26
Another case reported in cilium OSS slack by community

```
      containers:                                                                                                                                                                            
       - args:                                                                                                                                                                                
         - --config-dir=/tmp/cilium/config-map                                                                                                                                                
         - --debug=$(CILIUM_DEBUG)                                                                                                                                                            
         - --aws-instance-limit-mapping=c6a.2xlarge=4,15,15  
```

**Closed as completed** 2022-05-26 14:57 UTC
Labels: kind/bug

**Comment by ikarlashov** [comment] 2022-11-17 12:51
> I just tested locally, extraConfig can be used as per below
> 
> ```
> extraConfig:
>   "api-rate-limit": "{\"endpoint-create\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-delete\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-get\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-list\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\", \"endpoint-patch\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,auto-adjust:true\"}"
> ```
> 
> cilium bootstrap logs

IMHO, It worth to be documented somewhere. Maybe, even putting this snippet to `values.yaml` as an example.

**Comment by alex-berger** [comment] 2024-05-06 07:44
Thanks to https://github.com/cilium/cilium/pull/28239, `api-rate-limit` can now be set via Helm value `apiRateLimit` as of Cilium version 1.15.0.
