### ISSUE TITLE
Minikube: BPF verifier complexity issue on Linux 4.19

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#11647] opened 2020-05-22 05:43 UTC
- Cilium version (run `cilium version`)
   ```
   Client: 1.7.90 054dd163f 2020-05-20T18:59:30-07:00 go version go1.14.3 linux/amd64
   Daemon: 1.7.90 054dd163f 2020-05-20T18:59:30-07:00 go version go1.14.3 linux/amd64
   ```
- Kernel version (run `uname -a`)
   ```
   Linux minikube 4.19.107 #1 SMP Thu Mar 26 11:33:10 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
   ```
   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
   Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
   ```
   ```
   % minikube version
   minikube version: v1.9.2
   commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393
   ```
- Link to relevant artifacts (policies, deployments scripts, ...)
  [dns visibility policy](https://github.com/cilium/cilium/files/4666243/dns.txt)
- Upload a system dump
[cilium-sysdump-20200521-223831.zip](https://github.com/cilium/cilium/files/4666254/cilium-sysdump-20200521-223831.zip)

**How to reproduce the issue**

apply the dns visibility policy above and check the cilium log. i see errors like this:
```
level=error msg="Command execution failed" cmd="[tc filter replace dev lxcc0406b5e4c63 ingress prio 1 handle 1 bpf da obj 3825_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="Prog section 'from-container' rejected: Argument list too long (7)!" subsys=datapath-loader
```
[cilium.log](https://github.com/cilium/cilium/files/4666260/cilium.log)

**Comment by pchaigno** [comment] 2020-05-22 18:05
I am able to reproduce with the same setup, but also with the kernel version we use in our 4.19.57 CI pipeline (I extracted the object file from minikube's VM and loaded in custom VM).

**Comment by aanm** [comment] 2020-05-25 15:58
related https://github.com/cilium/cilium/issues/11175

**Comment by tgraf** [comment] 2020-06-02 16:50
Duplicate of #11175

**Closed as completed by tgraf** 2020-06-02 16:50 UTC
Labels: kind/bug
