### ISSUE TITLE
annotate pod  policy.cilium.io/proxy-visibility causing cilium to panic with WireGuard

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#27594] opened 2023-08-18 15:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Before 1.14, we can't have l7 proxy with WireGuard. we prevent it from in here https://github.com/cilium/cilium/blob/v1.13/daemon/cmd/daemon_main.go#L1604

However, there is a loophole. if we directly annotate the pod for l7 visibility, that will directly panic cilium. The cilium pod will be in crashloop . I think we should prevent it from panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21b1f90]

goroutine 939 [running]:
github.com/cilium/cilium/pkg/proxy.(*Proxy).CreateOrUpdateRedirect(0x0, {0x31f9e38?, 0x4000f42200}, {0x31fe020, 0x400006f440}, {0x4000efcca8, 0x12}, {0x320fc20, 0x4000f3ce00}, 0x4000191940)
        /go/src/github.com/cilium/cilium/pkg/proxy/proxy.go:491 +0x60
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addVisibilityRedirects(0x4000f3ce00, 0x0, 0x2c414d0?, 0x6?)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:390 +0x35c
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addNewRedirects(0x4000f3ce00, 0x4000edd680?)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:476 +0x308
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0x4000f3ce00, 0x400137c400, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:853 +0x3cc
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0x4000f3ce00, 0x400137c400)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:594 +0x160
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0x4000f3ce00, 0x400137c400)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:457 +0x600
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0x400001e320, 0x40009c0f28?)
        /go/src/github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x2a4
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x108
sync.(*Once).doSlow(0x0?, 0x7e098?)
        /usr/local/go/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0x40009dcd70?)
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:233 +0x48
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:229 +0x7c
```

### Cilium Version

v1.13.6 v.1.14.1

### Kernel Version

Linux minikube 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:29:30 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

I tested with 1.24.15

### Anything else?

you can just use the following helm values
```
cluster:
  name: minikube
encryption:
  enabled: true
  nodeEncryption: false
  type: wireguard
endpointStatus:
  enabled: true
  status: policy
l7Proxy: false
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: vxlan
```
then run 2 nginx pods
```
k run nginx --image=nginx
kubectl annotate pod nginx  policy.cilium.io/proxy-visibility="<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"
k run nginx1 --image=nginx
```
the nginx1 will cause the cilium to crash

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment] 2023-08-18 16:36
Duplicate of https://github.com/cilium/cilium/issues/27442

**Comment by liyihuang** [comment] 2023-08-18 17:37
tested with the image `quay.io/cilium/cilium-ci:735663e000064bd1fc435a2659d15ddf0d298a84` in this PR(https://github.com/cilium/cilium/pull/27453). the issue is still there, and I believe that's a different root cause of the issue but the same symptoms

**Comment by aanm** [comment] 2023-08-18 19:08
@mhofstetter can you take a look?

**Comment by sayboras** [comment] 2023-08-19 00:33
I am working on this one, assigning this to myself.

**Closed as completed** 2023-08-23 12:45 UTC
Labels: kind/bug, needs/triage, kind/community-report, area/agent
