### ISSUE TITLE
CI: Suite-k8s-1.16.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#15621] opened 2021-04-09 13:24 UTC
There seem to be a number of PR failures with this message, so this might be a flake:
 * https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/151/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB/
 * https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/170/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB/
 * https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/172/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB/
 * https://datastudio.google.com/s/k0-jD47OhWk

```
Stacktrace

/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Cannot retrieve LB IP for test-lb
Expected
    <*errors.errorString | 0xc000924af0>: {
        s: "could not get service LoadBalancer IP addr: 30s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:2573

Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 24
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 2 errors/warnings:
Failed to remove route
Unable to update ipcache map entry on pod add
Cilium pods: [cilium-klhbq cilium-xw5g4]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
grafana-7fd557d749-8ch4h               
prometheus-d87f8f984-zz54c             
test-k8s2-5b756fd6c5-j54q9             
testclient-2jtkg                       
testclient-ft6ts                       
testds-6h6hn                           
testds-flft9                           
coredns-5495c8f48d-6j8zt               
Cilium agent 'cilium-klhbq': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 41 Failed 0
Cilium agent 'cilium-xw5g4': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 41 Failed 0

Standard Error

17:06:49 STEP: Running BeforeAll block for EntireTestsuite K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer
17:06:49 STEP: Installing Cilium
17:06:50 STEP: Waiting for Cilium to become ready
17:07:29 STEP: Validating Cilium Installation
17:07:29 STEP: Performing Cilium controllers preflight check
17:07:29 STEP: Performing Cilium health check
17:07:29 STEP: Performing Cilium status preflight check
17:07:30 STEP: Performing Cilium service preflight check
17:07:30 STEP: Performing K8s service preflight check
17:07:31 STEP: Waiting for cilium-operator to be ready
17:07:31 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
17:07:31 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
17:07:31 STEP: Waiting until the Operator has assigned the LB IP
FAIL: Cannot retrieve LB IP for test-lb
Expected
    <*errors.errorString | 0xc000924af0>: {
        s: "could not get service LoadBalancer IP addr: 30s timeout expired",
    }
to be nil
=== Test Finished at 2021-04-08T17:08:01Z====
17:08:01 STEP: Running JustAfterEach block for EntireTestsuite K8sServicesTest
===================== TEST FAILED =====================
17:08:02 STEP: Running AfterFailed block for EntireTestsuite K8sServicesTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-7fd557d749-8ch4h          1/1     Running   0          26m     10.0.0.135      k8s1   <none>           <none>
	 cilium-monitoring   prometheus-d87f8f984-zz54c        1/1     Running   0          26m     10.0.0.61       k8s1   <none>           <none>
	 default             test-k8s2-5b756fd6c5-j54q9        2/2     Running   0          16m     10.0.1.204      k8s2   <none>           <none>
	 default             testclient-2jtkg                  1/1     Running   0          16m     10.0.0.66       k8s1   <none>           <none>
	 default             testclient-ft6ts                  1/1     Running   0          16m     10.0.1.212      k8s2   <none>           <none>
	 default             testds-6h6hn                      2/2     Running   0          8m12s   10.0.1.195      k8s2   <none>           <none>
	 default             testds-flft9                      2/2     Running   0          15m     10.0.0.111      k8s1   <none>           <none>
	 kube-system         cilium-klhbq                      1/1     Running   0          74s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-77f744db4-54xdd   1/1     Running   0          74s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-77f744db4-7lwvw   1/1     Running   0          74s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-xw5g4                      1/1     Running   0          74s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         coredns-5495c8f48d-6j8zt          1/1     Running   0          26m     10.0.1.152      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                         1/1     Running   0          30m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         frr                               1/1     Running   0          75s     192.168.36.13   k8s3   <none>           <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running   0          30m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running   0          30m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running   0          30m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-655wv                1/1     Running   0          27m     192.168.36.13   k8s3   <none>           <none>
	 kube-system         log-gatherer-pfwrx                1/1     Running   0          27m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-z9z77                1/1     Running   0          27m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-qn7rp              1/1     Running   0          27m     192.168.36.13   k8s3   <none>           <none>
	 kube-system         registry-adder-vmttm              1/1     Running   0          27m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-vvqzc              1/1     Running   0          27m     192.168.36.11   k8s1   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-klhbq cilium-xw5g4]
cmd: kubectl exec -n kube-system cilium-klhbq -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend                Service Type   Backend                   
	 1    10.96.0.1:443           ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53           ClusterIP      1 => 10.0.1.152:53        
	 3    10.96.0.10:9153         ClusterIP      1 => 10.0.1.152:9153      
	 4    10.104.214.155:3000     ClusterIP      1 => 10.0.0.135:3000      
	 5    10.101.233.65:9090      ClusterIP      1 => 10.0.0.61:9090       
	 6    10.108.150.230:80       ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 7    10.108.150.230:69       ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 8    10.101.41.78:10069      ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 9    10.101.41.78:10080      ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 10   192.168.36.11:32295     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 11   10.0.2.15:32295         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 12   0.0.0.0:32295           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 13   0.0.0.0:31641           NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 14   192.168.36.11:31641     NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 15   10.0.2.15:31641         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 16   10.106.174.88:10080     ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 17   10.106.174.88:10069     ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 18   10.0.2.15:31322         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 19   192.168.36.11:31322     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 20   0.0.0.0:31322           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 21   192.168.36.11:31128     NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 22   10.0.2.15:31128         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 23   0.0.0.0:31128           NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 24   10.100.153.129:10080    ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 25   10.100.153.129:10069    ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 26   192.168.36.11:31786     NodePort       1 => 10.0.0.111:69        
	 27   192.168.36.11:31786/i   NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 28   10.0.2.15:31786         NodePort       1 => 10.0.0.111:69        
	 29   10.0.2.15:31786/i       NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 30   0.0.0.0:31786           NodePort       1 => 10.0.0.111:69        
	 31   0.0.0.0:31786/i         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 32   192.168.36.11:31595     NodePort       1 => 10.0.0.111:80        
	 33   192.168.36.11:31595/i   NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 34   10.0.2.15:31595         NodePort       1 => 10.0.0.111:80        
	 35   10.0.2.15:31595/i       NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 36   0.0.0.0:31595           NodePort       1 => 10.0.0.111:80        
	 37   0.0.0.0:31595/i         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 38   10.109.87.207:10069     ClusterIP      1 => 10.0.1.204:69        
	 39   10.109.87.207:10080     ClusterIP      1 => 10.0.1.204:80        
	 40   192.168.36.11:30976     NodePort                                 
	 41   192.168.36.11:30976/i   NodePort       1 => 10.0.1.204:69        
	 42   10.0.2.15:30976         NodePort                                 
	 43   10.0.2.15:30976/i       NodePort       1 => 10.0.1.204:69        
	 44   0.0.0.0:30976           NodePort                                 
	 45   0.0.0.0:30976/i         NodePort       1 => 10.0.1.204:69        
	 46   192.168.36.11:30265     NodePort                                 
	 47   192.168.36.11:30265/i   NodePort       1 => 10.0.1.204:80        
	 48   10.0.2.15:30265         NodePort                                 
	 49   10.0.2.15:30265/i       NodePort       1 => 10.0.1.204:80        
	 50   0.0.0.0:30265           NodePort                                 
	 51   0.0.0.0:30265/i         NodePort       1 => 10.0.1.204:80        
	 52   10.101.252.189:10080    ClusterIP      1 => 10.0.1.204:80        
	 53   10.101.252.189:10069    ClusterIP      1 => 10.0.1.204:69        
	 54   192.168.36.11:32042     NodePort       1 => 10.0.1.204:80        
	 55   10.0.2.15:32042         NodePort       1 => 10.0.1.204:80        
	 56   0.0.0.0:32042           NodePort       1 => 10.0.1.204:80        
	 57   10.0.2.15:30394         NodePort       1 => 10.0.1.204:69        
	 58   0.0.0.0:30394           NodePort       1 => 10.0.1.204:69        
	 59   192.168.36.11:30394     NodePort       1 => 10.0.1.204:69        
	 60   10.97.142.59:80         ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 61   192.168.36.11:31419     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 62   10.0.2.15:31419         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 63   0.0.0.0:31419           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 64   10.103.207.186:80       ClusterIP      1 => 10.0.1.204:80        
	 65   192.168.36.11:32283     NodePort                                 
	 66   192.168.36.11:32283/i   NodePort       1 => 10.0.1.204:80        
	 67   10.0.2.15:32283         NodePort                                 
	 68   10.0.2.15:32283/i       NodePort       1 => 10.0.1.204:80        
	 69   0.0.0.0:32283           NodePort                                 
	 70   0.0.0.0:32283/i         NodePort       1 => 10.0.1.204:80        
	 71   10.97.202.59:20080      ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 72   10.97.202.59:20069      ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 73   192.0.2.233:20069       ExternalIPs    1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 74   192.0.2.233:20080       ExternalIPs    1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 75   192.168.36.11:30866     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 76   10.0.2.15:30866         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 77   0.0.0.0:30866           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 78   192.168.36.11:32031     NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 79   10.0.2.15:32031         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 80   0.0.0.0:32031           NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 81   192.168.36.11:20080     ExternalIPs    1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 82   192.168.36.11:20069     ExternalIPs    1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 83   10.105.135.183:80       ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 84   10.0.2.15:31232         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 85   0.0.0.0:31232           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 86   192.168.36.11:31232     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-klhbq -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                   
	 4          Disabled           Disabled          4          reserved:health                                          fd02::c6   10.0.0.250   ready   
	 459        Disabled           Disabled          16140      k8s:io.cilium.k8s.policy.cluster=default                 fd02::b1   10.0.0.66    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                  
	                                                            k8s:zgroup=testDSClient                                                                  
	 749        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                       ready   
	                                                            k8s:node-role.kubernetes.io/master                                                       
	                                                            reserved:host                                                                            
	 1564       Disabled           Disabled          38513      k8s:app=prometheus                                       fd02::cd   10.0.0.61    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                   
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 3193       Disabled           Disabled          20292      k8s:app=grafana                                          fd02::49   10.0.0.135   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 3824       Disabled           Disabled          3080       k8s:io.cilium.k8s.policy.cluster=default                 fd02::c0   10.0.0.111   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                  
	                                                            k8s:zgroup=testDS                                                                        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-xw5g4 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend                Service Type   Backend                   
	 1    10.96.0.1:443           ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53           ClusterIP      1 => 10.0.1.152:53        
	 3    10.96.0.10:9153         ClusterIP      1 => 10.0.1.152:9153      
	 4    10.104.214.155:3000     ClusterIP      1 => 10.0.0.135:3000      
	 5    10.101.233.65:9090      ClusterIP      1 => 10.0.0.61:9090       
	 6    10.108.150.230:80       ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 7    10.108.150.230:69       ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 8    10.101.41.78:10080      ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 9    10.101.41.78:10069      ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 10   192.168.36.12:32295     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 11   10.0.2.15:32295         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 12   0.0.0.0:32295           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 13   192.168.36.12:31641     NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 14   10.0.2.15:31641         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 15   0.0.0.0:31641           NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 16   10.106.174.88:10069     ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 17   10.106.174.88:10080     ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 18   192.168.36.12:31322     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 19   10.0.2.15:31322         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 20   0.0.0.0:31322           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 21   192.168.36.12:31128     NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 22   10.0.2.15:31128         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 23   0.0.0.0:31128           NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 24   10.100.153.129:10080    ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 25   10.100.153.129:10069    ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 26   192.168.36.12:31595     NodePort       1 => 10.0.1.195:80        
	 27   192.168.36.12:31595/i   NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 28   10.0.2.15:31595         NodePort       1 => 10.0.1.195:80        
	 29   10.0.2.15:31595/i       NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 30   0.0.0.0:31595           NodePort       1 => 10.0.1.195:80        
	 31   0.0.0.0:31595/i         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 32   192.168.36.12:31786     NodePort       1 => 10.0.1.195:69        
	 33   192.168.36.12:31786/i   NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 34   10.0.2.15:31786         NodePort       1 => 10.0.1.195:69        
	 35   10.0.2.15:31786/i       NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 36   0.0.0.0:31786           NodePort       1 => 10.0.1.195:69        
	 37   0.0.0.0:31786/i         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 38   10.109.87.207:10080     ClusterIP      1 => 10.0.1.204:80        
	 39   10.109.87.207:10069     ClusterIP      1 => 10.0.1.204:69        
	 40   192.168.36.12:30265     NodePort       1 => 10.0.1.204:80        
	 41   192.168.36.12:30265/i   NodePort       1 => 10.0.1.204:80        
	 42   10.0.2.15:30265         NodePort       1 => 10.0.1.204:80        
	 43   10.0.2.15:30265/i       NodePort       1 => 10.0.1.204:80        
	 44   0.0.0.0:30265           NodePort       1 => 10.0.1.204:80        
	 45   0.0.0.0:30265/i         NodePort       1 => 10.0.1.204:80        
	 46   192.168.36.12:30976     NodePort       1 => 10.0.1.204:69        
	 47   192.168.36.12:30976/i   NodePort       1 => 10.0.1.204:69        
	 48   10.0.2.15:30976         NodePort       1 => 10.0.1.204:69        
	 49   10.0.2.15:30976/i       NodePort       1 => 10.0.1.204:69        
	 50   0.0.0.0:30976           NodePort       1 => 10.0.1.204:69        
	 51   0.0.0.0:30976/i         NodePort       1 => 10.0.1.204:69        
	 52   10.101.252.189:10080    ClusterIP      1 => 10.0.1.204:80        
	 53   10.101.252.189:10069    ClusterIP      1 => 10.0.1.204:69        
	 54   10.0.2.15:32042         NodePort       1 => 10.0.1.204:80        
	 55   0.0.0.0:32042           NodePort       1 => 10.0.1.204:80        
	 56   192.168.36.12:32042     NodePort       1 => 10.0.1.204:80        
	 57   192.168.36.12:30394     NodePort       1 => 10.0.1.204:69        
	 58   10.0.2.15:30394         NodePort       1 => 10.0.1.204:69        
	 59   0.0.0.0:30394           NodePort       1 => 10.0.1.204:69        
	 60   10.97.142.59:80         ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 61   192.168.36.12:31419     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 62   10.0.2.15:31419         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 63   0.0.0.0:31419           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 64   10.103.207.186:80       ClusterIP      1 => 10.0.1.204:80        
	 65   0.0.0.0:32283           NodePort       1 => 10.0.1.204:80        
	 66   0.0.0.0:32283/i         NodePort       1 => 10.0.1.204:80        
	 67   192.168.36.12:32283     NodePort       1 => 10.0.1.204:80        
	 68   192.168.36.12:32283/i   NodePort       1 => 10.0.1.204:80        
	 69   10.0.2.15:32283         NodePort       1 => 10.0.1.204:80        
	 70   10.0.2.15:32283/i       NodePort       1 => 10.0.1.204:80        
	 71   10.97.202.59:20069      ClusterIP      1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 72   10.97.202.59:20080      ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 73   192.0.2.233:20069       ExternalIPs    1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 74   192.0.2.233:20080       ExternalIPs    1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 75   192.168.36.12:32031     NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 76   10.0.2.15:32031         NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 77   0.0.0.0:32031           NodePort       1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 78   0.0.0.0:30866           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 79   192.168.36.12:30866     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 80   10.0.2.15:30866         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 81   192.168.36.12:8080      HostPort       1 => 10.0.1.204:80        
	 82   10.0.2.15:8080          HostPort       1 => 10.0.1.204:80        
	 83   0.0.0.0:8080            HostPort       1 => 10.0.1.204:80        
	 84   192.168.36.12:6969      HostPort       1 => 10.0.1.204:69        
	 85   10.0.2.15:6969          HostPort       1 => 10.0.1.204:69        
	 86   0.0.0.0:6969            HostPort       1 => 10.0.1.204:69        
	 87   192.168.36.11:20069     ExternalIPs    1 => 10.0.1.195:69        
	                                             2 => 10.0.0.111:69        
	 88   192.168.36.11:20080     ExternalIPs    1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 89   10.105.135.183:80       ClusterIP      1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 90   10.0.2.15:31232         NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 91   192.168.36.12:31232     NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 92   0.0.0.0:31232           NodePort       1 => 10.0.1.195:80        
	                                             2 => 10.0.0.111:80        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-xw5g4 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                             
	 6          Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                 ready   
	                                                            reserved:host                                                                      
	 914        Disabled           Disabled          3080       k8s:io.cilium.k8s.policy.cluster=default          fd02::1cd   10.0.1.195   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:zgroup=testDS                                                                  
	 1880       Disabled           Disabled          16140      k8s:io.cilium.k8s.policy.cluster=default          fd02::1a6   10.0.1.212   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:zgroup=testDSClient                                                            
	 1940       Disabled           Disabled          29382      k8s:io.cilium.k8s.policy.cluster=default          fd02::152   10.0.1.204   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:zgroup=test-k8s2                                                               
	 2050       Disabled           Disabled          4          reserved:health                                   fd02::158   10.0.1.208   ready   
	 2371       Disabled           Disabled          11566      k8s:io.cilium.k8s.policy.cluster=default          fd02::134   10.0.1.152   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                        
	                                                            k8s:k8s-app=kube-dns                                                               
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
17:08:18 STEP: Running AfterEach for block EntireTestsuite K8sServicesTest
17:08:18 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|50613b38_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip]]
17:08:22 STEP: Running AfterAll block for EntireTestsuite K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer

```

**Comment by brb** [comment] 2021-04-09 13:41
Duplicate of https://github.com/cilium/cilium/issues/15620.

**Closed as completed by brb** 2021-04-09 13:41 UTC
Labels: area/CI, ci/flake
