### ISSUE TITLE
CI: K8sDatapathConfig Host firewall Check connectivity with IPv6 disabled

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#17363] opened 2021-09-10 11:47 UTC
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Cilium cannot be installed
Expected
    <*errors.errorString | 0xc004e5c9f0>: {
        s: "cannot retrieve node to read IP: ",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/k8sT/assertionHelpers.go:113
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/6368/testReport/junit/Suite-k8s-1/19/K8sDatapathConfig_Host_firewall_Check_connectivity_with_IPv6_disabled/

Looks like this failed [a few times](https://datastudio.google.com/s/i-v_dPkfm1A).

[3a407116_K8sDatapathConfig_Host_firewall_Check_connectivity_with_IPv6_disabled.zip](https://github.com/cilium/cilium/files/7143519/3a407116_K8sDatapathConfig_Host_firewall_Check_connectivity_with_IPv6_disabled.zip)
[test_results_Cilium-PR-K8s-GKE_6368_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/7143520/test_results_Cilium-PR-K8s-GKE_6368_BDD-Test-PR.zip)

**Comment by pchaigno** [comment] 2021-09-10 12:30
> Looks like this failed [a few times](https://datastudio.google.com/s/i-v_dPkfm1A).

All other failures in the past 2 weeks have different error messages and likely different root causes (most of the time, all tests failed). It looks like it only happened in your PR so far. Are you sure it could not be caused by your changes?

**Comment by errordeveloper** [comment] 2021-09-10 12:33
> Are you sure it could not be caused by your changes?

Yes, and it didn't fail on previous iterations. The new codepath in #16926 isn't even being tested (it's debatable whether it should or shouldn't).

**Comment by errordeveloper** [comment] 2021-09-10 12:41
> The new codepath in #16926 isn't even being tested (it's debatable whether it should or shouldn't).

I take this back, it's not exactly true for that PR, I was thinking of my other PR (https://github.com/cilium/cilium/pull/16874). In the case of #16926 there are refactoring changes that are being tested, but the new flag isn't being set to non-default value in the tests. However, all other jobs didn't fail, so I am pretty sure refactoring didn't introduce this failure, and this job passed on previous runs also as the PR was rebased a few times.

**Comment by errordeveloper** [comment] 2021-09-10 12:51
I am really missing this output in the logs to find out what nodes is missing:

https://github.com/cilium/cilium/blob/712af8e26e4afe1f380ee081b152fba1392b3b96/test/helpers/node.go#L199

Are the debug logs from kubectl wrapper deliberately excluded to reduce noise?

**Comment by pchaigno** [comment] 2021-09-10 13:07
Did you check in `test-output.log`, right before `test finished`?

**Comment by errordeveloper** [comment] 2021-09-10 13:14
> Did you check in `test-output.log`, right before `test finished`?

No, I didn't know about this file. Thanks!

**Comment by errordeveloper** [comment] 2021-09-10 13:15
This looks like the API is unresponsive and the command gets timedout few times in a row:
```
time="2021-09-09T16:21:35Z" level=debug msg="running command: kubectl get nodes -l cilium.io/ci-node=k8s1 -o jsonpath='{@.items[*].status.addresses[?(@.type == \"InternalIP\")
].address}'"
time="2021-09-09T16:21:45Z" level=error msg="Error executing command 'kubectl get nodes -l cilium.io/ci-node=k8s1 -o jsonpath='{@.items[*].status.addresses[?(@.type == \"Inter
nalIP\")].address}''" error="signal: killed"
time="2021-09-09T16:21:45Z" level=error msg="Error executing command 'kubectl get nodes -l cilium.io/ci-node=k8s1 -o jsonpath='{@.items[*].status.addresses[?(@.type == \"Inter
nalIP\")].address}''" error="signal: killed"
cmd: "kubectl get nodes -l cilium.io/ci-node=k8s1 -o jsonpath='{@.items[*].status.addresses[?(@.type == \"InternalIP\")].address}'" exitCode: -1 duration: 10.003660737s stdout
:

err:
signal: killed
FAIL: Cilium cannot be installed
Expected
    <*errors.errorString | 0xc004e5c9f0>: {
        s: "cannot retrieve node to read IP: ",
    }
to be nil
```

**Comment by brb** [comment] 2022-05-06 12:13
Haven't seen the failure in awhile. Closing.

**Closed as completed by brb** 2022-05-06 12:13 UTC
Labels: area/CI, area/datapath, ci/flake
