### ISSUE TITLE
JoinEP found in CI build

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#9346] opened 2019-10-04 16:56 UTC
Build link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15278/testReport/junit/(root)/Suite-runtime/RuntimePolicies_L3_L4_Checks/

```
Oct 04 00:35:51 runtime cilium-agent[14354]: level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2282 error="Failed to load tc filter: signal: terminated" file-path=2282_next/bpf_lxc.o identity=4 ipv4=10.15.201.150 ipv6="f00d::a0f:0:0:158c" k8sPodName=/ subsys=datapath-loader veth=lxc_health
Oct 04 00:35:51 runtime cilium-agent[14354]: level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2282 error="Failed to replace Qdisc for lxc_health: Link not found" file-path=2282_next/bpf_lxc.o identity=4 ipv4=10.15.201.150 ipv6="f00d::a0f:0:0:158c" k8sPodName=/ subsys=datapath-loader veth=lxc_health
```

**Comment by joestringer** [comment] 2019-10-04 17:18
Looks like a duplicate of https://github.com/cilium/cilium/issues/9301 ?

**Closed as completed** 2019-10-04 17:19 UTC
Labels: kind/bug, kind/duplicate, area/CI, needs/triage
