### ISSUE TITLE
Geneve DSR not working on DigitalOcean with docs example

### ISSUE THREAD

**Issue by damieneichhorn** [cilium/cilium#27731] opened 2023-08-28 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

From my understanding the Geneve Tunnel mode should work with the Geneve dsrDispatch option on any  cluster where the nodes can reach eachother. I tried setting up cilium on a 2 node(1 server and 1 worker) cluster on DigitalOcean using just the public ip's of the droplets.

### Setting up K3s
I setup the first server node using the following command:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.7+k3s1 sh -s - server --disable local-storage --disable traefik --disable servicelb --flannel-backend none --node-ip $PUBLIC_IP --disable-kube-proxy --disable-network-policy
```

After setting up the server node, I got the server token via `cat /var/lib/rancher/k3s/server/node-token` and used it for joining the worker node:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.7+k3s1 sh -s - agent --server https://$SERVER_IP:6443 --token $TOKEN --node-ip $PUBLIC_IP
```

### Setting up Cilium
After installing k3s, I installed Cilium 1.14.1 using helm with the following command:
```
helm upgrade --install cilium cilium/cilium --version 1.14.1 \
    --namespace kube-system \
    --set routingMode=tunnel
    --set tunnelProtocol=geneve \
    --set kubeProxyReplacement=true \
    --set loadBalancer.mode=dsr \
    --set loadBalancer.dsrDispatch=geneve \
    --set k8sServiceHost=$SERVER_IP \
    --set k8sServicePort=6443
```

Everything up until here looked fine and seemed to be working. All pods started correctly and no warnings are/were displayed in any of the container logs.

### Problem
For testing DSR, a small nginx pod was created with logging(to check the origin ip) alongside a NodePort service 30001
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
  - name: nginx
    image: nginx 
    ports:
      - containerPort: 80 
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: nginx
  type: NodePort
  ports:
  - name: http-web-svc
    nodePort: 30001
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```
But after creating the pod/service, the nginx installation only works from 1 of the 2 node ip's:30001.

![Screenshot 2023-08-28 at 11 22 26](https://github.com/cilium/cilium/assets/9391905/60d0963d-204b-4ea2-bfb2-bf1ef4289e34)

For the node that did respond, the right origin ip showed up in the nginx logs but the other request did not go through at all.

### Cilium Monitor
After getting the endpoint id, I tried checking cilium monitor and for the node that worked, it gave me the following output:
```
root@geneve-dsr-test-02:/home/cilium# cilium monitor --to=593
Listening for events on 1 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 593 flow 0x0 , identity world->34377 state new ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49375 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state established ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49375 -> 10.0.0.80:80 tcp ACK
-> endpoint 593 flow 0x0 , identity world->34377 state established ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49375 -> 10.0.0.80:80 tcp ACK
-> endpoint 593 flow 0x0 , identity world->34377 state new ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49380 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state new ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49381 -> 10.0.0.80:80 tcp SYN
```

The node that didn't work lead to the following output:
```
root@geneve-dsr-test-02:/home/cilium# cilium monitor --to=593
Listening for events on 1 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 593 flow 0x0 , identity world->34377 state new ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49451 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state new ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49457 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state new ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49461 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state established ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49451 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state established ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49436 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state established ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49457 -> 10.0.0.80:80 tcp SYN
-> endpoint 593 flow 0x0 , identity world->34377 state established ifindex lxc4bdfbc7eb6fe orig-ip <my ip>: <my ip>:49461 -> 10.0.0.80:80 tcp SYN
```

### Cilum Status
The `cilium status --verbose` command gives the following output:
```
root@geneve-dsr-test-02:/home/cilium# cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.25 (v1.25.7+k3s1) [linux/amd64]
Kubernetes APIs:        ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   True   [eth0 68.183.5.90, eth1 10.133.114.113]
Host firewall:          Disabled
CNI Chaining:           none
Cilium:                 Ok   1.14.1 (v1.14.1-c191ef6f)
NodeMonitor:            Listening for events on 1 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 3/254 allocated from 10.0.0.0/24, 
Allocated addresses:
  10.0.0.123 (router)
  10.0.0.243 (health)
  10.0.0.80 (default/bruh)
IPv4 BIG TCP:           Disabled
IPv6 BIG TCP:           Disabled
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      24/24 healthy
  Name                                  Last success   Last error   Count   Message
  cilium-health-ep                      1m1s ago       never        0       no error   
  dns-garbage-collector-job             16s ago        never        0       no error   
  endpoint-1306-regeneration-recovery   never          never        0       no error   
  endpoint-1841-regeneration-recovery   never          never        0       no error   
  endpoint-593-regeneration-recovery    never          never        0       no error   
  endpoint-gc                           16s ago        never        0       no error   
  ipcache-inject-labels                 2s ago         10m7s ago    0       no error   
  k8s-heartbeat                         16s ago        never        0       no error   
  link-cache                            17s ago        never        0       no error   
  metricsmap-bpf-prom-sync              6s ago         never        0       no error   
  resolve-identity-1306                 2s ago         never        0       no error   
  resolve-identity-1841                 5m1s ago       never        0       no error   
  resolve-identity-593                  4m6s ago       never        0       no error   
  sync-host-ips                         2s ago         never        0       no error   
  sync-lb-maps-with-k8s-services        10m2s ago      never        0       no error   
  sync-policymap-1306                   5s ago         never        0       no error   
  sync-policymap-1841                   5s ago         never        0       no error   
  sync-policymap-593                    5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (1306)     2s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (1841)     11s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (593)      6s ago         never        0       no error   
  sync-utime                            2s ago         never        0       no error   
  template-dir-watcher                  never          never        0       no error   
  write-cni-file                        10m16s ago     never        0       no error   
Proxy Status:            OK, ip 10.0.0.123, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 432/4095 (10.55%), Flows/s: 0.67   Metrics: Disabled
KubeProxyReplacement Details:
  Status:                 True
  Socket LB:              Enabled
  Socket LB Tracing:      Enabled
  Socket LB Coverage:     Full
  Devices:                eth0 68.183.5.90, eth1 10.133.114.113
  Mode:                   DSR
  Backend Selection:      Random
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  XDP Acceleration:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Auth                          524288
  Non-TCP connection tracking   65536
  TCP connection tracking       131072
  Endpoint policy               65535
  IP cache                      512000
  IPv4 masquerading agent       16384
  IPv6 masquerading agent       16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           131072
  Neighbor table                131072
  Global policy                 16384
  Session affinity              65536
  Sock reverse NAT              65536
  Tunnel                        65536
Encryption:                        Disabled        
Cluster health:                    2/2 reachable   (2023-08-28T09:16:14Z)
  Name                             IP              Node        Endpoints
  geneve-dsr-test-02 (localhost)   68.183.5.90     reachable   reachable
  geneve-dsr-test-01               68.183.5.8      reachable   reachable
  ```
  ### Cilium Health
The `cilium health --status` command gives the following output:
```
root@geneve-dsr-test-02:/home/cilium# cilium-health status  
Probe time:   2023-08-28T09:18:14Z
Nodes:
  geneve-dsr-test-02 (localhost):
    Host connectivity to 68.183.5.90:
      ICMP to stack:   OK, RTT=630.791µs
      HTTP to agent:   OK, RTT=754.01µs
    Endpoint connectivity to 10.0.0.243:
      ICMP to stack:   OK, RTT=635.941µs
      HTTP to agent:   OK, RTT=519.125µs
  geneve-dsr-test-01:
    Host connectivity to 68.183.5.8:
      ICMP to stack:   OK, RTT=643.258µs
      HTTP to agent:   OK, RTT=864.894µs
    Endpoint connectivity to 10.0.1.98:
      ICMP to stack:   OK, RTT=2.487149ms
      HTTP to agent:   OK, RTT=17.337224ms
``` 

### Cilium Version

```
root@geneve-dsr-test-01:/home/cilium# cilium version
Client: 1.14.1 c191ef6f 2023-08-10T18:54:57+02:00 go version go1.20.7 linux/amd64
Daemon: 1.14.1 c191ef6f 2023-08-10T18:54:57+02:00 go version go1.20.7 linux/amd64
```

### Kernel Version

```
root@geneve-dsr-test-01:/home/cilium# uname -r
6.1.0-9-amd64
```

### Kubernetes Version

v1.25.7+k3s1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BurlyLuo** [comment] 2023-08-30 02:43
duplicate with https://github.com/cilium/cilium/issues/26723

**Comment by youngnick** [comment] 2023-09-04 03:59
Thanks for this @damieneichhorn, marking this so that the datapath folks will see it.

**Comment by julianwiedmann** [comment] 2023-09-12 12:10
>Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]

Hi @damieneichhorn! Can you try enabling BPF-driven masquerading (`--enable-bpf-masquerade`), and see if that helps?

(as @BurlyLuo pointed out)

**Comment by damieneichhorn** [comment] 2023-09-12 13:19
> > Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
> 
> Hi @damieneichhorn! Can you try enabling BPF-driven masquerading (`--enable-bpf-masquerade`), and see if that helps?
> 
> (as @BurlyLuo pointed out)

Hey @julianwiedmann I tried bpf masquerade by adding `--set bpf.masquerade=true` on the helm install but that did not change anything.

Cilium monitor gave pretty much the same output as it did before without bpf masquarade

**Comment by julianwiedmann** [comment] 2023-09-15 14:47
Best give the `v1.14.2` release a try then when it's out, maybe https://github.com/cilium/cilium/pull/27381 is what you need. Difficult to tell without a full sysdump.

**Comment by d-uzlov** [comment] 2023-09-16 18:24
I did a quick test with 1.14.2, and I still see this issue.

**Comment by d-uzlov** [comment] 2023-11-16 04:52
Not stale

**Comment by d-uzlov** [comment] 2023-11-16 04:57
@youngnick @julianwiedmann could you remove the "stale" label, please?

**Comment by JamesHawkinss** [comment] 2023-11-17 14:08
I'm a colleague of @damieneichhorn.

An update from our end - it seems that these issues may be caused by IP spoofing being blocked / disabled by the hosting provider. As the other node's IP is not associated with it, the outbound connection seems to be blocked by firewalls.

We are working to have this limitation resolved with our hosting provider. As this IP spoofing is an inherent function of DSR, it seems unlikely at this stage that a patch to Cilium will resolve the issue.

**Comment by julianwiedmann** [comment] 2023-11-17 15:20
> I'm a colleague of @damieneichhorn.
> 
> An update from our end - it seems that these issues may be caused by IP spoofing being blocked / disabled by the hosting provider. As the other node's IP is not associated with the agent machine, the outbound connection seems to be blocked by firewalls.
> 
> We are working to have this limitation resolved with our hosting provider. As this IP spoofing is an inherent function of DSR, it seems unlikely at this stage that a patch to Cilium will resolve the issue.
> 
> It may be possible to resolve this issue with other providers by connecting the machines together in a shared VPC or L2 segment, with floating IPs attached directly to that network (rather than to any individual machine).

Sounds like what's described on https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr:

>In some public cloud provider environments that implement source / destination IP address checking (e.g. AWS), the checking has to be disabled in order for the DSR mode to work.

**Comment by JamesHawkinss** [comment] 2023-11-17 18:48
@julianwiedmann it does indeed sound a lot like that... only surprise here is that OVH perform this IP address checking too, on their bare metal servers.

**Closed as completed** 2023-11-20 14:35 UTC
Labels: kind/question, need-more-info, area/datapath, kind/community-report, area/loadbalancing
