### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16399] opened 2021-06-02 15:10 UTC
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Can not connect to service "http://192.168.1.146" from outside cluster (1/10)
Expected command: kubectl exec -n kube-system log-gatherer-bkwwr -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.1.146 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000018()', Connect: '0.000000',Transfer '0.000000', total '5.001274'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:1026
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/641/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB/

[93fca07c_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip](https://github.com/cilium/cilium/files/6585573/93fca07c_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip)

**Comment by christarazi** [comment] 2021-06-03 01:02
Looking into the sysdump, I see that we have an explicit drop for the traffic from hubble:

```shell
❯ rg SERVICE_BACKEND_NOT_FOUND
cilium-msk9x-hubble_observe.json
115:{"flow":{"time":"2021-06-02T01:59:25.195061289Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:87:3e:67","destination":"08:00:27:3d:23:14"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":46106,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-06-02T01:59:25.195061289Z"}
117:{"flow":{"time":"2021-06-02T01:59:26.205889163Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:87:3e:67","destination":"08:00:27:3d:23:14"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":46106,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-06-02T01:59:26.205889163Z"}
120:{"flow":{"time":"2021-06-02T01:59:28.221878963Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:87:3e:67","destination":"08:00:27:3d:23:14"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":46106,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-06-02T01:59:28.221878963Z"}
```

One potential cause for this is that the service endpoint (backends) pods have not been inserted into the BPF maps. We at least know from userspace that we attempted to insert them into the map as we have the following log msgs in the relevant cilium-agent:

```
2021-06-02T01:59:24.830367454Z level=debug msg="Upserting service entry" backendSlot=1 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="9 (23808) [FLAGS: 0x0]"
2021-06-02T01:59:24.830429213Z level=debug msg="Upserting service entry" backendSlot=2 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="7 (23808) [FLAGS: 0x0]"
2021-06-02T01:59:24.830528447Z level=debug msg="Upserting service entry" backendSlot=0 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="0 (23808) [FLAGS: 0x60]"
```

Cross-referencing that to the `cilium service list` output:

```
93   192.168.1.146:80        LoadBalancer   1 => 10.0.1.141:80        
                                            2 => 10.0.0.182:80        
```

So at a high-level, we expect everything to work properly...so why do we have drops? Could it be that we failed to insert into the maps? There are no errors in the agent logs that would indicate as such.

Let's look at the map dumps. First by looking at the service map. The service maps have keys that start with the IP then follows with the dport, so we're looking for the following hex `c0 a8 01 92 00 50` which translates to `192.168.1.146:80`.

```
key: c0 a8 01 92 00 50 00 00  00 00 00 00  value: 00 00 00 00 02 00 00 5d  60 00 00 00
...
key: c0 a8 01 92 00 50 01 00  00 00 00 00  value: 09 00 00 00 00 00 00 5d  00 00 00 00
...
key: c0 a8 01 92 00 50 02 00  00 00 00 00  value: 07 00 00 00 00 00 00 5d  00 00 00 00
```

We have 3 entries which is what we expect given the log output from earlier. And what we see is that indeed we have backends with IDs 7 and 9 (looking at the map values). Let's look at the backend map.

```
key: 06 00  value: 0a 00 00 14 00 45 00 00
key: 04 00  value: 0a 00 00 7b 00 35 00 00
key: 08 00  value: 0a 00 01 8d 00 45 00 00
key: 03 00  value: 0a 00 00 7b 23 c1 00 00
key: 09 00  value: 0a 00 00 b6 00 50 00 00
key: 02 00  value: 0a 00 00 02 23 82 00 00
key: 0a 00  value: 0a 00 00 b6 00 45 00 00
key: 05 00  value: 0a 00 00 14 00 50 00 00
key: 07 00  value: 0a 00 01 8d 00 50 00 00
key: 01 00  value: c0 a8 24 0b 19 2b 00 00
```

There exist backends with IDs 7 & 9...why did the datapath drop the packets then?

**Comment by christarazi** [comment] 2021-06-04 17:01
I attempted to reproduce this following the [instructions to create a dedicated instance](https://github.com/cilium/cilium/tree/master/test/packet). I was not able to reproduce the issue, which ran for 16h 30m and 196 attempts.

**Comment by christarazi** [comment] 2021-07-21 06:10
Inspecting the a sysdump of another occurrence of this, I found the following in the dump:

```
❯ jq -r .type tests-loadbalancer-hubble-observe-debug-events-k8s* | sort -u
DBG_CT_CREATED4
DBG_CT_LOOKUP4_1
DBG_CT_LOOKUP4_2
DBG_CT_MATCH
DBG_CT_VERDICT
DBG_INHERIT_IDENTITY
DBG_IP_ID_MAP_SUCCEED4
DBG_LOCAL_DELIVERY
```

:cry: I would've expected to see `DBG_LB4_LOOKUP_BACKEND_SLOT_V2_FAIL` or `DBG_LB4_LOOKUP_BACKEND_FAIL` given that the drop reason is `DROP_NO_SERVICE`.

Upon further inspection though, I found the following [commit](https://github.com/cilium/cilium/commit/f3c40a729d7c6c88c21093e63ebfa61d3e0cc3d8) which removes the debug trace for when the _frontend_ entry is not found.

I wonder if these flakes and other "from outside" flakes are due to Cilium just not being able to find the _frontend_ service entry in the BPF maps, and we can't know because we don't have the debug trace msg for it. :thinking_face:

**Comment by brb** [comment] 2021-07-21 08:56
@christarazi Could you attach the sysdump of the failure? I'm interested whether it was the first request again. If it's not, then it might be a different reason than the one in which a service was not provisioned in a timely manner.

**Comment by christarazi** [comment] 2021-07-21 19:13
@brb 

GH is not letting me attach it, but you can find it here: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1125/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB/

**Comment by brb** [comment] 2021-07-22 06:15
@christarazi Thanks. It was the first request. So probably it has to do with timing of the service BPF maps provisioning.

**Comment by christarazi** [comment] 2021-07-26 07:06
Debugging at https://github.com/cilium/cilium/pull/16992

**Comment by brb** [comment] 2021-07-28 15:38
Another issue where the first request from outside fails: https://github.com/cilium/cilium/issues/16971

**Comment by brb** [comment] 2021-07-28 16:09
Hit it in https://github.com/cilium/cilium/pull/17003
The interesting flow:
```
{"flow":{"time":"2021-07-28T10:33:57.089567729Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:7a:94:95","destination":"08:00:27:db:fb:f1"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":60358,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-07-28T10:33:57.089567729Z"}
```
GH doesn't allow to attach the zip, so posting only the link to the CI: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1162/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB/

**Comment by christarazi** [comment] 2021-07-28 18:57
@brb Is there a way to know when a BPF map was actually updated with an entry by timestamp? Maybe we could have a debug log for that. Is it possible that somehow the `bpf()` call could take more than a 1s to update an entry in the map?

**Comment by brb** [comment] 2021-07-30 07:56
@christarazi We could run `strace -f -e bpf -y -yy -t -T $CILIUM_AGENT_PID` in the background for this test as we do (or used to do) with `cilium monitor` in some Services test cases.

I did a quick check of the log msgs in `pkg/lbmap`, and it seems that we log msgs before we actually try do do the bpf() syscall. Moving the log statements after invoking the syscalls (e.g. in `updateServiceEndpoints()`) would help to troubleshoot this too.

**Comment by brb** [comment] 2021-07-30 09:08
@christarazi Regarding the second approach, I've created https://github.com/cilium/cilium/pull/17017.

**Comment by brb** [comment] 2021-09-21 08:37
@christarazi Did we end up merging any PR which would include more debug info wrt the failure?

**Comment by christarazi** [comment] 2021-09-21 18:48
@brb I opened https://github.com/cilium/cilium/pull/16992 but it was still unsuccessful. I ran the test focused many times and was never able to reproduce (see comments on that PR).  I wonder if this failure only happens when other tests have been run previously.

**Comment by jibi** [comment] 2021-09-24 10:44
> @brb I opened #16992 but it was still unsuccessful in terms of getting results. I ran the test focused many times and was never able to reproduce (see comments on that PR). I wonder if this failure only happens when other tests have been run previously.

Same here, I managed to run it locally (see https://github.com/cilium/cilium/issues/17437) but I couldn't reproduce the failure after many runs :confused:

**Comment by jibi** [comment] 2021-09-24 12:23
> Moving the log statements after invoking the syscalls (e.g. in updateServiceEndpoints()) would help to troubleshoot this too.

I checked on the latest sysdump (which includes https://github.com/cilium/cilium/pull/17017) and it looks like the service's been upserted before the requests failed:

```sh
➜  K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB rg 'Upserted service entry.*192.168.1.146' *cilium-agent.log
pod-kube-system-cilium-x6r2p-cilium-agent.log
4318:2021-09-17T09:24:14.938178895Z level=debug msg="Upserted service entry" backendSlot=1 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="8 (23040) [FLAGS: 0x0]"
4319:2021-09-17T09:24:14.938183633Z level=debug msg="Upserted service entry" backendSlot=2 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="10 (23040) [FLAGS: 0x0]"
4320:2021-09-17T09:24:14.938188422Z level=debug msg="Upserted service entry" backendSlot=0 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="0 (23040) [FLAGS: 0x60]"

pod-kube-system-cilium-klt49-cilium-agent.log
4110:2021-09-17T09:24:14.277248633Z level=debug msg="Upserted service entry" backendSlot=1 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="10 (24576) [FLAGS: 0x0]"
4111:2021-09-17T09:24:14.277305377Z level=debug msg="Upserted service entry" backendSlot=2 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="8 (24576) [FLAGS: 0x0]"
4112:2021-09-17T09:24:14.277370788Z level=debug msg="Upserted service entry" backendSlot=0 subsys=map-lb svcKey="192.168.1.146:20480" svcVal="0 (24576) [FLAGS: 0x60]"

```

```sh
➜  K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB rg "DROPPED.*192.168.1.146" *hubble*
cilium-klt49-hubble_observe.json
171:{"flow":{"time":"2021-09-17T09:24:14.933885141Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:c4:41:6c","destination":"08:00:27:9e:b1:17"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":32954,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-09-17T09:24:14.933885141Z"}
172:{"flow":{"time":"2021-09-17T09:24:15.942489029Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:c4:41:6c","destination":"08:00:27:9e:b1:17"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":32954,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-09-17T09:24:15.942489029Z"}
186:{"flow":{"time":"2021-09-17T09:24:17.958432414Z","verdict":"DROPPED","drop_reason":158,"ethernet":{"source":"08:00:27:c4:41:6c","destination":"08:00:27:9e:b1:17"},"IP":{"source":"192.168.36.13","destination":"192.168.1.146","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":32954,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"k8s2","event_type":{"type":1,"sub_type":158},"destination_service":{"name":"test-lb-with-ip","namespace":"default"},"traffic_direction":"INGRESS","drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND","Summary":"TCP Flags: SYN"},"node_name":"k8s2","time":"2021-09-17T09:24:17.958432414Z"}
```

**Comment by christarazi** [comment] 2021-09-24 17:35
@jibi Yep, that was my experience as well. Userspace says the map has been updated before the request, but that doesn't mean that the entry actually made it into the map itself. Meaning `BPF_MAP_UPDATE_ELEM` may have taken longer than we expect. We currently don't have an answer for that question.

**Comment by jibi** [comment] 2021-09-24 17:50
> but that doesn't mean that the entry actually made it into the map itself.

I'm confused :confused:  since we now log `Upserted service entry` after the `bpf()` syscall, does it mean that the syscall can return successfully even if the map has not been updated?

**Comment by christarazi** [comment] 2021-09-24 18:00
> does it mean that the syscall can return successfully even if the map has not been updated?
Oops, I did forgot that https://github.com/cilium/cilium/pull/17017 moved it to after the syscall. I'm probably confusing an earlier theory related to this issue. 

In any case, it's still a mystery unfortunately.

**Comment by brb** [comment] 2021-09-24 18:06
I think it makes sense to break `DROP_NO_SERVICE` into more drop types (e.g., `DROP_NO_BACKEND`). Currently, it's not possible to distinguish which drop in the LB path has happened.

**Comment by jibi** [comment] 2021-09-24 18:14
> I think it makes sense to break `DROP_NO_SERVICE` into more drop types (e.g., `DROP_NO_BACKEND`). Currently, it's not possible to distinguish which drop in the LB path has happened.

Isn't that already in the hubble flow logs?
```
"drop_reason_desc":"SERVICE_BACKEND_NOT_FOUND"
```

**Comment by brb** [comment] 2021-09-24 18:17
Noup:
```
lib/common.h:#define DROP_NO_SERVICE            -158
vendor/github.com/cilium/cilium/api/v1/flow/flow.pb.go:         158: "SERVICE_BACKEND_NOT_FOUND",
```

**Comment by brb** [comment] 2021-09-28 18:30
```
vagrant@k8s1:~$ curl http://192.168.36.11:31609


Hostname: testds-zsppl

Pod Information:
	-no pod information available-
..
```
You are running request from k8s1, so the request is handled by socket-lb.

```
[Can not connect to service "http://192.168.36.11:32543" from outside cluster (1/10)
Expected command: kubectl exec -n kube-system log-gatherer-qftct -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:32543 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To succeed, but it failed:
Exitcode: 28
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000020()', Connect: '0.000000',Transfer '0.000000', total '5.000965'
Stderr:
 	 command terminated with exit code 28
```
Are you saying that once you hit it and hold the environment, it's always failing?

**Comment by jibi** [comment] 2021-09-29 15:08
> You are running request from k8s1, so the request is handled by socket-lb.

I tried both nodes, and curl was working fine from both of them

> Are you saying that once you hit it and hold the environment, it's always failing?

No, what I'm observing is that once the test fails, I can rerun it and it'll keep failing (but when I run curl from the VMs the connections will succeed)

**Comment by aditighag** [comment] 2021-09-29 15:21
>I tried both nodes, and curl was working fine from both of them

You'll need to do the curl from "outside" so that (N-S) nodeport code is exercised. Is there a node not running cilium?

**Comment by jibi** [comment] 2021-09-29 15:26
> > I tried both nodes, and curl was working fine from both of them
> 
> You'll need to do the curl from "outside" so that (N-S) nodeport code is exercised. Is there a node not running cilium?

Makes sense, I'll give it a try from the external node then :+1:

**Comment by brb** [comment] 2021-09-29 17:54
Yeah, that's what I meant with:
> You are running request from k8s1, so the request is handled by socket-lb.

**Comment by jibi** [comment] 2021-09-30 11:43
Reproduced again. I'm connecting to this nodeport service from k8s3 (so from the outside):
```
vagrant@k8s1:~$ ks exec $(cilium_pod k8s1) -- cilium service list | grep 192.168.36.11:32402 -A 1
10   192.168.36.11:32402     NodePort       1 => 10.0.1.95:80
                                            2 => 10.0.0.57:80
```

and the connection only succeeds if the backend that gets selected is on the same node I am connecting to (i.e. k8s1):

```
vagrant@k8s3:~$ curl http://192.168.36.11:32402


Hostname: testds-4grnl
```

```
vagrant@k8s1:~$ k get pods -o wide | grep testds-4grnl
testds-4grnl                 2/2     Running   0          69m   10.0.1.95   k8s1   <none>           <none>
```

```
vagrant@k8s1:~$ sudo tcpdump -i any port 32402 -q
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
11:33:28.084671 IP k8s3.40744 > k8s1.32402: tcp 0
11:33:28.084965 IP k8s1.32402 > k8s3.40744: tcp 0
11:33:28.085268 IP k8s3.40744 > k8s1.32402: tcp 0
11:33:28.085277 IP k8s3.40744 > k8s1.32402: tcp 83
11:33:28.085340 IP k8s1.32402 > k8s3.40744: tcp 0
11:33:28.085646 IP k8s1.32402 > k8s3.40744: tcp 590
11:33:28.085800 IP k8s3.40744 > k8s1.32402: tcp 0
11:33:28.089614 IP k8s3.40744 > k8s1.32402: tcp 0
11:33:28.089839 IP k8s1.32402 > k8s3.40744: tcp 0
11:33:28.089965 IP k8s3.40744 > k8s1.32402: tcp 0
```

while if I end up with the backend on k8s2, I don't even get a syn+ack:

```
vagrant@k8s3:~$ curl http://192.168.36.11:32402

```


```

vagrant@k8s1:~$ sudo tcpdump -i any port 32402 -q
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
11:39:51.541501 IP k8s3.40758 > k8s1.32402: tcp 0
11:39:52.569405 IP k8s3.40758 > k8s1.32402: tcp 0
11:39:54.585040 IP k8s3.40758 > k8s1.32402: tcp 0
```

```
vagrant@k8s3:~$ sudo tcpdump -i any port 32402 -q
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
11:39:51.239015 IP k8s3.40758 > k8s1.32402: tcp 0
11:39:52.266676 IP k8s3.40758 > k8s1.32402: tcp 0
11:39:54.282535 IP k8s3.40758 > k8s1.32402: tcp 0
```

**Comment by brb** [comment] 2021-09-30 13:03
@jibi Nice! Could you check what happens with the request from the cilium monitor POV on k8s1 node?

**Comment by jibi** [comment] 2021-09-30 14:05
After disabling aggregation I can see the SYN packets on the monitor:

```
vagrant@k8s1:~$ ks exec $(cilium_pod k8s1) -- cilium monitor | grep ':32008'
level=info msg="Initializing dissection cache..." subsys=monitor
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.13:47636 -> 192.168.36.11:32008 tcp SYN
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.13:47636 -> 192.168.36.11:32008 tcp SYN
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.13:47636 -> 192.168.36.11:32008 tcp SYN
```

**Comment by brb** [comment] 2021-09-30 14:32
Can you run in the debug-verbose=datapath mode? And then `cilium monitor -D -vv`?

**Comment by jibi** [comment] 2021-09-30 15:18
> Can you run in the debug-verbose=datapath mode? And then `cilium monitor -D -vv`?

I managed to capture this:

```
Ethernet	{Contents=[..14..] Payload=[..62..] SrcMAC=08:00:27:fb:c0:b3 DstMAC=08:00:27:d8:5d:95 EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=18205 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=10806 SrcIP=192.168.36.13 DstIP=192.168.36.11 Options=[] Padding=[]}
TCP	{Contents=[..40..] Payload=[] SrcPort=56144 DstPort=31185 Seq=1725747278 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=64240 Checksum=33367 Urgent=0 Options=[..5..] Padding=[]}
CPU 01: MARK 0x0 FROM 1038 from-network: 74 bytes (74 captured), state new, interface enp0s8, orig-ip 0.0.0.0
CPU 01: MARK 0x0 FROM 1038 DEBUG: Successfully mapped addr=192.168.36.13 to identity=2
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 1/2: src=192.168.36.13:56144 dst=192.168.36.11:31185
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=4
CPU 01: MARK 0x0 FROM 1038 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x0 FROM 1038 DEBUG: Service backend slot lookup: slot=2, dport=31185
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack create: proxy-port=0 revnat=11 src-identity=0 lb=0.0.0.0
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 1/2: src=192.168.36.13:56144 dst=10.0.1.44:80
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 01: MARK 0x0 FROM 1038 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack create: proxy-port=0 revnat=11 src-identity=1 lb=10.0.1.44

[..]

Ethernet	{Contents=[..14..] Payload=[..62..] SrcMAC=08:00:27:fb:c0:b3 DstMAC=08:00:27:d8:5d:95 EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=18206 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=10805 SrcIP=192.168.36.13 DstIP=192.168.36.11 Options=[] Padding=[]}
TCP	{Contents=[..40..] Payload=[] SrcPort=56144 DstPort=31185 Seq=1725747278 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=64240 Checksum=32336 Urgent=0 Options=[..5..] Padding=[]}
CPU 01: MARK 0x0 FROM 1038 from-network: 74 bytes (74 captured), state new, interface enp0s8, orig-ip 0.0.0.0
CPU 01: MARK 0x0 FROM 1038 DEBUG: Successfully mapped addr=192.168.36.13 to identity=2
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 1/2: src=192.168.36.13:56144 dst=192.168.36.11:31185
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=4
CPU 01: MARK 0x0 FROM 1038 DEBUG: CT entry found lifetime=16797977, revnat=11
CPU 01: MARK 0x0 FROM 1038 DEBUG: CT verdict: Reply, revnat=11
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 1/2: src=192.168.36.13:56144 dst=10.0.1.44:80
CPU 01: MARK 0x0 FROM 1038 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 01: MARK 0x0 FROM 1038 DEBUG: CT entry found lifetime=16797977, revnat=11
CPU 01: MARK 0x0 FROM 1038 DEBUG: CT verdict: Established, revnat=11
```

**Comment by jibi** [comment] 2021-09-30 15:37
I don't see any drop or any of the debug printk I added in the datapath :thinking: 

At this point I'm thinking we may be looking at a different failure even though the `K8sServicesTest Checks service across nodes Tests NodePort BPF Tests L2-less with Wireguard provisioned via kube-wireguarder ` test is failing the same way as the `K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB` one :pensive:

**Comment by brb** [comment] 2022-02-04 09:39
The test has been renamed to "K8sBGPTests Tests LoadBalancer Connectivity to endpoint via LB".

**Comment by joestringer** [comment] 2022-02-21 22:00
Hit similar symptoms in [this K8sServicesTest Checks N/S loadbalancing Tests with direct routing and DSR failure]( https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/523/testReport/Suite-k8s-1/23/K8sServicesTest_Checks_N_S_loadbalancing_Tests_with_direct_routing_and_DSR/).

**Comment by brb** [comment] 2022-02-22 07:11
@joestringer This is very likely going to be fixed by https://github.com/cilium/cilium/pull/18859

**Comment by joestringer** [comment] 2022-08-19 20:43
Hit a similar failure in[K8sServicesTest Checks N/S loadbalancing Tests with TC, direct routing and Hybrid](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/521/testReport/junit/Suite-k8s-1/24/K8sServicesTest_Checks_N_S_loadbalancing_Tests_with_TC__direct_routing_and_Hybrid/).

**Comment by pchaigno** [comment] 2023-04-21 14:48
No recent reports that actually match the report here.

**Closed as completed by pchaigno** 2023-04-21 14:48 UTC
Labels: area/CI, area/datapath, ci/flake
