### ISSUE TITLE
Cilium hangs onto old IPs 

### ISSUE THREAD

**Issue by jasonaliyetti** [cilium/cilium#21218] opened 2022-09-06 19:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We've observed repeated instances where a pod is deleted and is still listed in CiliumNode status with a bound ip.  This leads us to scenarios where pods get scheduled on a node but the ip space is exhausted because several IPs are still bound to pods that don't exist anymore that for some reason aren't released.  We also notice that CiliumIdentities aren't always garbage collected.  We have suspicions that this was introduced with [this change](https://github.com/cilium/cilium/commit/959568bc3fc0de093bba3093dbac25ea28136c18).

### Cilium Version

1.12.1

### Kernel Version

 5.10

### Kubernetes Version

EKS 1.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasonaliyetti** [comment] 2022-09-09 19:05
Some additional detail:  We run on EKS using custom cni networking.  We can confirm that we're frequently seeing Cilium hang on indefinitely to identities for pods that no longer exist.  We're not sure if it's related to holding onto the ip allocation.  We also don't see any errors around IPAM in our logs.

**Comment by jasonaliyetti** [comment] 2022-09-12 20:49
Another datapoint: we found a correlation between this occurring and agents that seem to constantly have all endpoint either in the regenerating or waiting_to_regenerate state.

**Comment by pchaigno** [comment] 2022-09-20 12:20
> We have suspicions that this was introduced with [this change](https://github.com/cilium/cilium/commit/959568bc3fc0de093bba3093dbac25ea28136c18).

Did you try a git bisect to confirm?

**Comment by aanm** [comment] 2022-09-21 11:33
@jasonaliyetti can you try with 1.12.2 and upload a sysdump or some reproducible steps so that we can try to see the issue? Thank you

**Comment by jaliyetti-appian** [comment] 2022-09-28 14:04
We upgraded to 1.12.2 last week and this occurred again last night.  When we try to collect a sysdump from impacted agents we get an timeout error -- `Cilium API client timeout exceeded`.  It smells like there's a deadlock somewhere.

I wish I had reproduction steps for you but the only thing I can correlate this with is EKS Control Plane scaling events.  Even then it's not something that always occurs -- this seems to happen on 3-5 nodes out of a few thousand across many clusters every week.

We also uncovered another wrinkle -- while in this state, pods on the nodes with the issue stop being able to communicate. 

I don't think it's cause/effect here but this does seem to somewhat correlate with behavior reported in https://github.com/cilium/cilium/issues/20915.

**Comment by jaliyetti-appian** [comment] 2022-09-28 14:10
This also seems similar to https://github.com/cilium/cilium/issues/11430

**Comment by jasonaliyetti** [comment] 2022-09-28 14:12
We upgraded to 1.12.2 last week and this occurred again last night. When we try to collect a sysdump from impacted agents we get an timeout error -- Cilium API client timeout exceeded. It smells like there's a deadlock somewhere.
I wish I had reproduction steps for you but the only thing I can correlate this with is EKS Control Plane scaling events. Even then it's not something that always occurs -- this seems to happen on 3-5 nodes out of a few thousand across many clusters every week.

We also uncovered another wrinkle -- while in this state, pods on the nodes with the issue stop being able to communicate.

I don't think it's cause/effect here but this does seem to somewhat correlate with behavior reported in [#20915](https://github.com/cilium/cilium/issues/20915).

This also seems similar to [#11430](https://github.com/cilium/cilium/issues/11430)

**Comment by jasonaliyetti** [comment] 2022-09-28 14:26
Is it possible this'd be exacerbated by something like https://github.com/aws/containers-roadmap/issues/1810 ?

**Comment by jasonaliyetti** [comment] 2022-09-28 15:51
<img width="1532" alt="apiserver-failover" src="https://user-images.githubusercontent.com/16091645/192824913-562d70f0-6552-4b42-aac3-6cf2b479ccca.png">
[logs.txt](https://github.com/cilium/cilium/files/9666739/logs.txt)
[cilium-status.txt](https://github.com/cilium/cilium/files/9666777/cilium-status.txt)


I've tried to cull some data from the agent logs and status output here.  Some of it's been redacted and I've commented on that in the file where appropriate.  When we tried to run debuginfo we get the api timeout error.

**Comment by jasonaliyetti** [comment] 2022-09-30 03:04
I was able to get a stack dump when the issue recurred by running cilium-bugtool on the pod. 
[gops.zip](https://github.com/cilium/cilium/files/9680331/gops.zip)

If I grep the stack for "lockAlive" and sort them it appears to me that there are apparent deadlock in the system, but I'll freely admit to being a neophyte when it comes to comprehending gops output.

**Comment by jasonaliyetti** [comment] 2022-10-06 19:14
@aanm apologies for tagging you directly, but is the above information helpful?

**Comment by jasonaliyetti** [comment] 2022-10-10 15:14
This might get fixed with https://github.com/cilium/cilium/pull/21629.

**Comment by joestringer** [comment] 2022-10-10 19:37
@jasonaliyetti I just took a look through the gops stack output from your post above and confirmed that it's the same deadlock as the one that #21629 plans to address. That patch is now queued up for the 1.12.3 release so hopefully this will solve this issue as well, or at least move it forward :crossed_fingers:

**Comment by jasonaliyetti** [comment] 2022-10-10 20:12
@joestringer any idea when 1.12.3 and a 1.11 backport would be available?  We're also dealing with https://github.com/cilium/cilium/issues/20915 and aren't sure if this would help that problem or not and are weighing whether or not it is worth rolling back to 1.11 if this is going to be arriving soon and might help resolve that issue as well.

**Comment by joestringer** [comment] 2022-10-10 20:43
@jasonaliyetti we target bugfix releases for around the middle of the month, so by current planning those releases should be published by roughly the beginning of next week.

**Comment by aanm** [comment] 2022-10-12 08:31
@jasonaliyetti I'm going to close this GH issue since the PR https://github.com/cilium/cilium/pull/21629 has fixed it. Feel free to open a new GH issue or tag me directly to re-open it since GH doesn't allow users to re-open closed GH issues. Thanks for reporting it. /cc @joestringer

**Closed as completed by aanm** 2022-10-12 08:31 UTC
Labels: kind/bug, need-more-info, kind/community-report, area/agent
