### ISSUE TITLE
Rebooting Cilium pods on host with IPv6 node IP results in connectivity loss for pods

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#13553] opened 2020-10-14 06:56 UTC
## Bug report

When we restart the Cilium pods, all connectivity to pods is lost until we completely restart the hosts ( with the exception of pods on the same host.  pods on the same host continue to be able to ping each other )

**General Information**

- Cilium version (run `cilium version`)
Client: 1.9.0-rc1 9ab7bfc94 2020-10-12T16:22:19-07:00 go version go1.15.2 linux/amd64
Daemon: 1.9.0-rc1 9ab7bfc94 2020-10-12T16:22:19-07:00 go version go1.15.2 linux/amd64

*(we also had this issue with 1.8.0)

- Kernel version (run `uname -a`)
 5.8.14-050814-generic #202010070730 SMP Wed Oct 7 07:35:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

(We had this issue on kernel 5.4.0 as well.) 

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

Kubeadm.  

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
We deploy with `helm install -f <valuesfile.yaml> cilium cilium/cilium --version 1.9.0-rc1 --namespace=kube-system`

**How to reproduce the issue**
1) delete all pods matching cilium-*
[ 1) a.  wait for cilium pods to come back up ]
2) test connectivity

**Comment by pchaigno** [comment] 2020-10-14 08:22
Config from `cilium status`:
```
BandwidthManager:    EDT with BPF   [enp6s0, cilium_host]
Masquerading:        IPTables
Controller Status:   36/37 healthy
  Name                                          Last success   Last error   Count   Message
  cilium-health-ep                              23m54s ago     6s ago       30      Get "http://10.192.2.2:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)   
  dns-garbage-collector-job                     1s ago         never        0       no error                                                                                                         
  endpoint-1290-regeneration-recovery           never          never        0       no error                                                                                                         
  endpoint-2998-regeneration-recovery           never          never        0       no error                                                                                                         
  endpoint-378-regeneration-recovery            never          never        0       no error                                                                                                         
  endpoint-3989-regeneration-recovery           never          never        0       no error                                                                                                         
  endpoint-504-regeneration-recovery            never          never        0       no error                                                                                                         
  endpoint-682-regeneration-recovery            never          never        0       no error                                                                                                         
  k8s-heartbeat                                 1s ago         never        0       no error                                                                                                         
  mark-k8s-node-as-available                    23m55s ago     never        0       no error                                                                                                         
  metricsmap-bpf-prom-sync                      1s ago         never        0       no error                                                                                                         
  resolve-identity-1290                         6s ago         never        0       no error                                                                                                         
  restoring-ep-identity (2998)                  23m56s ago     never        0       no error                                                                                                         
  restoring-ep-identity (378)                   23m56s ago     never        0       no error                                                                                                         
  restoring-ep-identity (3989)                  23m56s ago     never        0       no error                                                                                                         
  restoring-ep-identity (504)                   23m56s ago     never        0       no error                                                                                                         
  restoring-ep-identity (682)                   23m56s ago     never        0       no error                                                                                                         
  sync-endpoints-and-host-ips                   56s ago        never        0       no error                                                                                                         
  sync-lb-maps-with-k8s-services                23m56s ago     never        0       no error                                                                                                         
  sync-policymap-1290                           5s ago         never        0       no error                                                                                                         
  sync-policymap-2998                           26s ago        never        0       no error                                                                                                         
  sync-policymap-378                            26s ago        never        0       no error                                                                                                         
  sync-policymap-3989                           26s ago        never        0       no error                                                                                                         
  sync-policymap-504                            26s ago        never        0       no error                                                                                                         
  sync-policymap-682                            26s ago        never        0       no error                                                                                                         
  sync-to-k8s-ciliumendpoint (1290)             6s ago         never        0       no error                                                                                                         
  sync-to-k8s-ciliumendpoint (2998)             6s ago         never        0       no error                                                                                                         
  sync-to-k8s-ciliumendpoint (378)              6s ago         never        0       no error                                                                                                         
  sync-to-k8s-ciliumendpoint (3989)             6s ago         never        0       no error                                                                                                         
  sync-to-k8s-ciliumendpoint (504)              6s ago         never        0       no error                                                                                                         
  sync-to-k8s-ciliumendpoint (682)              6s ago         never        0       no error                                                                                                         
  template-dir-watcher                          never          never        0       no error                                                                                                         
  update-k8s-node-annotations                   24m1s ago      never        0       no error                                                                                                         
  waiting-initial-global-identities-ep (2998)   23m56s ago     never        0       no error                                                                                                         
  waiting-initial-global-identities-ep (378)    23m56s ago     never        0       no error                                                                                                         
  waiting-initial-global-identities-ep (504)    23m56s ago     never        0       no error                                                                                                         
  waiting-initial-global-identities-ep (682)    23m56s ago     never        0       no error                                                                                                         
Proxy Status:   OK, ip 10.192.3.35, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 2256/4096 (55.08%), Flows/s: 1.57   Metrics: Disabled
KubeProxyReplacement Details:
  Status:              Strict
  Protocols:           TCP, UDP
  Devices:             enp6s0, cilium_host (Direct Routing)
  Mode:                Hybrid
  Backend Selection:   Random
  Session Affinity:    Enabled
  XDP Acceleration:    Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
```
The bug also happened on 1.8, so not related to the bandwidth manager. The user also initially tried with BPF masquerading.

This could be related https://github.com/cilium/cilium/issues/13254. Running `tc filter del dev eth0 egress` didn't help though.

**Comment by gpl** [comment] 2020-10-17 04:26
Just for additional information, it looks like the packets get dropped on ingress somehow.  The host itself receives the packets on its interface, but they don't seem to get to the pod.  The packets egress out of the network fine.

**Comment by gpl** [comment] 2020-10-20 18:11
We're seeing this issue on 1.9 rc2 as well.

The packets start being dropped on ingress a while after the cilium containers restart, so something on cilium's startup seems to take down networking -- but I'm unable to track down exactly what it is.

**Comment by aanm** [comment] 2020-10-26 09:18
@gpl can you provide us with a Cilium sysdump? Thanks

**Comment by joestringer** [comment] 2020-11-06 18:14
Additional information that would help to pinpoint the issue:

* The full values file as provided
* `hubble observe -t drop` or `cilium monitor -t drop` output demonstrating the packet drops
* A sysdump if possible, so we can evaluate things like whether routes might be misconfigured to cause drops, or iptables rules are being hit which cause all packets to be dropped, or some other unusual environmental setting

**Comment by gpl** [comment] 2020-11-06 18:57
- Values file -- https://hasteb.in/doxepaqa.yaml
- We don't actually see the drops occurring on the cilium end.  We know from tcpdump on the switch side that packets are making it to the host, but the packet seems to disappear from then on.  Cilium monitor doesn't observe these drops.
- A sysdump was sent to @\pchaigno a few weeks ago, if possible could that be referenced?  We can send another one if needed.

**Comment by joestringer** [comment] 2020-11-06 19:25
I see, if Cilium isn't dropping the traffic then this gets more into Linux debugging territory.

Here's a few additional avenues to investigate:
* Routing diverts the traffic to not be observed by Cilium (`ip rule`, `ip route`, `ip route get <dst>`)
* Iptables rules are dropping the traffic (`iptables-save -c`)
* Early demux is interfering somehow `net.ipv4.ip_early_demux`
* NIC offloads like GRO/LRO are somehow interfering with the traffic
* MTU is causing packets to be dropped as they are received

**Comment by gpl** [comment] 2020-11-06 20:04
We're only observing this behavior after the cilium pod restarted, so I'm not sure if GRO/LRO would be at issue here.  In either case, the issue still exists when offloads are disabled.

We ran the following commands before and after cilium was restarted and connectivity broke to pods on the host.
```
ip a
ip rule
ip route
ip route get 10.192.3.215 # one random pod, connectivity working before cilium was restarted
cat /proc/sys/net/ipv4/ip_early_demux # I'm not sure if there's an ipv6 variant
```

The only thing we saw changed was:

before:
```
	7: lxc_health@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000	
    link/ether ca:d1:b5:c3:f1:b3 brd ff:ff:ff:ff:ff:ff link-netnsid 0	
    inet6 fe80::c8d1:b5ff:fec3:f1b3/64 scope link	
       valid_lft forever preferred_lft forever
```
after:
```
	29: lxc_health@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b6:b0:cd:20:f7:aa brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::b4b0:cdff:fe20:f7aa/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by joestringer** [comment] 2020-11-06 20:14
> Running `tc filter del dev eth0 egress` didn't help though.

Even if specifically deleting the egress filter on eth0 doesn't help, there could still be an issue on the TC side - ingress, or on another device.

Another potential option to explore is using `cilium cleanup` to clear out Cilium state on the node and see if that makes a difference. Note, this is a last resort and should not be executed in important or production environments.

**Comment by gpl** [comment] 2020-11-06 20:33
>> Even if specifically deleting the egress filter on eth0 doesn't help, there could still be an issue on the TC side - ingress, or on another device. 

Is there an easy way to debug this?  I apologize, I'm not quite sure what I should be looking for here.  Pings to the container stop working after we see `restored endpoint` in the log lines.

We reinstalled a node an hour ago to test if there was something stuck in the state that would cause an issue, is `cilium cleanup` still needed?

**Comment by gpl** [comment] 2020-11-06 23:51
I might be completely wrong here, but it looks like the issue no longer persists if I specify the nodeIP as an IPv4 address, instead of an IPv6 address.

**Comment by gpl** [comment] 2021-01-10 06:04
Commenting to leave issue open.  Still occurs.

**Comment by joestringer** [comment] 2021-03-05 18:21
Just acknowledging your most recent post @gpl , that seems like a straightforward reproduction + mitigation. I'm not aware of anyone directly working on this issue today but given the required steps to reproduce, anyone who's interested in digging further should hopefully be able to make some progress from there.

It's likely that some IPv4 assumption has leaked into the datapath at some point, but I'm not familiar with exactly what the issue is. I'd be curious to see what happens if you configure `--debug-verbose=datapath` and run `cilium monitor` for a specific endpoint while sending traffic into it, that may provide some additional information to drive this bug closer to resolution.

**Comment by gpl** [comment] 2021-06-28 23:20
for the stale bot: This issue is still present.

**Comment by gpl** [comment] 2021-08-28 23:47
this issue is still valid

**Comment by gpl** [comment] 2021-12-10 21:25
It looks like this issue is no longer present during my initial testing for 1.11.0.  I went back and checked later versions of 1.10 and it seems to be fixed there as well, so I think this issue can be closed.

**Comment by joestringer** [comment] 2021-12-10 22:51
Thanks for the confirmation @gpl . At a glance I can't think of any particular fixes that would have addressed this, but if you don't observe the problem any more then that is good news. :+1:  We fix a lot of various bugs and it's not always possible to track down how those bugs relate to all of the open issues in the repository.

If anything changes, feel free to respond again and we can reopen, but otherwise for now I will close this issue out.

**Closed as completed by joestringer** 2021-12-10 22:51 UTC
Labels: kind/bug, area/datapath, needs/triage, kind/community-report, pinned
