### ISSUE TITLE
Egress for destination CIDR 0.0.0.0/0 blocks all network connections

### ISSUE THREAD

**Issue by UbiquitousBear** [cilium/cilium#16147] opened 2021-05-14 09:43 UTC
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Use the following egress rule
```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-mailserver
spec:
  egress:
  - podSelector:
      matchLabels:
        # The following label selects default namespace
        io.kubernetes.pod.namespace: mailserver
    # Or use namespace label selector to select multiple namespaces
    # namespaceSelector:
    #  matchLabels:
    #    ns: default
  destinationCIDRs:
  - 0.0.0.0/0
  egressSourceIP: "51.195.x.x" 
```
2. curl http://checkip.amazonaws.com from a pod
 
Expected result: 51.195.x.x
Actual result: bash-5.0# curl http://checkip.amazonaws.com
curl: (6) Could not resolve host: checkip.amazonaws.com

**Comment by pchaigno** [comment] 2021-05-14 10:09
@UbiquitousBear Could you share a sysdump? Also, what's the value of `enable-endpoint-routes` in your cluster?

@anfernee Did you come across this while testing? It looks like such a CIDR will also affect intra-cluster connections when endpoint routes are disabled.

**Comment by UbiquitousBear** [comment] 2021-05-14 10:33
@pchaigno 

`cilium config view | grep enable-endpoint-routes` yields no results... I assume it's disabled?

Sysdump: http://transfer.sh/33tFU/cilium-sysdump-20210514-112945.zip

**Comment by pchaigno** [comment] 2021-05-14 10:50
Attaching the sysdump to the issue so we don't lose it: 
[cilium-sysdump-20210514-112945.7z.zip](https://github.com/cilium/cilium/files/6478287/cilium-sysdump-20210514-112945.7z.zip)

Yes, endpoint routes are disabled. From the Cilium agent logs:
```
2021-05-14T02:39:23.761223973Z level=info msg="  --enable-endpoint-routes='false'" subsys=daemon
```

**Comment by anfernee** [comment] 2021-05-14 16:33
cc @MasterZ40 

It looks like the kube-dns traffic is affected. To @pchaigno we haven't came across this setting. Let's try to reproduce and get back to you.

**Comment by anfernee** [comment] 2021-05-16 04:24
I tried to run `egress-gateway` with `--enable-endpoint-routes='false'` and didn't see any issues. 

@UbiquitousBear One thing I've noticed in the sysdump is that you are running `kube-proxy` together with cilium's `kube-proxy-replacement: strict` mode. That might cause problems. You should be able to remove `kube-proxy` because cilium is going to do the service resolution for you.

**Comment by UbiquitousBear** [comment] 2021-05-16 10:02
@anfernee would it work if cilium was set to probe rather than strict?

**Comment by anfernee** [comment] 2021-05-17 04:46
From the sysdump, the `KubeProxyReplacement` mode is `strict`, and it should be fine. 

Can you check 2 things in your cluster? 
- Does `dig kubernetes.default.svc.cluster.local` work? If it works but `dig checkip.amazonaws.com` doesn't work. It might mean the upstream dns server doesn't work.
- Does the dns resolution work without the egress nat policy rule?

**Comment by UbiquitousBear** [comment] 2021-05-18 21:14
@anfernee 

Without egress policy rule:

```
bash-5.0# dig kubernetes.default.svc.cluster.local

; <<>> DiG 9.16.15 <<>> kubernetes.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45660
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b756c416e1dddac6 (echoed)
;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A	10.96.0.1

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Tue May 18 21:11:20 UTC 2021
;; MSG SIZE  rcvd: 129

bash-5.0# dig checkip.amazonaws.com

; <<>> DiG 9.16.15 <<>> checkip.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5307
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;checkip.amazonaws.com.		IN	A

;; ANSWER SECTION:
checkip.amazonaws.com.	30	IN	CNAME	checkip.check-ip.aws.a2z.com.
checkip.check-ip.aws.a2z.com. 30 IN	CNAME	checkip.us-east-1.prod.check-ip.aws.a2z.com.
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 107.21.162.206
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 3.224.94.38
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 23.21.27.29
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 3.211.138.232
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 3.222.126.94
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 34.193.115.2
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 34.192.7.28
checkip.us-east-1.prod.check-ip.aws.a2z.com. 30	IN A 18.233.3.145

;; Query time: 84 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Tue May 18 21:11:57 UTC 2021
;; MSG SIZE  rcvd: 670
```

With egress policy rules:

```

bash-5.0# dig kubernetes.default.svc.cluster.local

; <<>> DiG 9.16.15 <<>> kubernetes.default.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached

bash-5.0# dig checkip.amazonaws.com

; <<>> DiG 9.16.15 <<>> checkip.amazonaws.com
;; global options: +cmd
;; connection timed out; no servers could be reached

```

pinging dns svc and external IP:

```
bash-5.0# ping 10.96.0.10
PING 10.96.0.10 (10.96.0.10): 56 data bytes
^C^
--- 10.96.0.10 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
bash-5.0# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
```

**Comment by UbiquitousBear** [comment] 2021-05-18 22:34
Edit, after installing 1.10.0-rc2 this feature works as expected.

**Comment by anfernee** [comment] 2021-05-20 05:59
Glad it works for you @UbiquitousBear. 

However, I do have an interesting unexpected observation. I found that when you specify `0.0.0.0/0` as `destinationCIDR` which of course includes `PodCIDR` in it. It will also hijack all the pod to pod traffic to the gateway node. For example, lets's say you have 3 nodes N1, N2, N3. If you configure the egress nat policy to route 0.0.0.0/0 to N2. When pod P1 on N1 talks to P3 on N3, it will be routed to N2 then N3. In your previous case, P3 happens to be the `kubedns`. When gateway node for some reason is not working, it will affect the internal pod to pod traffic.

**Comment by pchaigno** [comment] 2021-05-21 20:38
> I found that when you specify 0.0.0.0/0 as destinationCIDR which of course includes PodCIDR in it. It will also hijack all the pod to pod traffic to the gateway node.

@anfernee I'm guessing that only happens when endpoint routes are enabled?

If endpoint routes are enabled, `ENABLE_ROUTING` is undefined, so we never go through: https://github.com/cilium/cilium/blob/d3b54929c51235850a1132efa558c0554f961886/bpf/bpf_lxc.c#L775-L776
Therefore, pod-to-pod traffic goes through https://github.com/cilium/cilium/blob/d3b54929c51235850a1132efa558c0554f961886/bpf/bpf_lxc.c#L796-L798
matches 0.0.0.0/0 and is redirected to the gateway.

**Comment by anfernee** [comment] 2021-05-25 05:15
I have a different theory, which I am not sure if it's correct though. 

Here when we found the remote endpoint, and save it in `tunnel_endpoint`. 

https://github.com/cilium/cilium/blob/d3b54929c51235850a1132efa558c0554f961886/bpf/bpf_lxc.c#L616-L619

which should be honored here

https://github.com/cilium/cilium/blob/d3b54929c51235850a1132efa558c0554f961886/bpf/bpf_lxc.c#L828 

However, when egress does lookup between them and didn't check if `tunnel_endpoint` is already found. We should probably skip it if `tunnel_endpoint` is non empty. 

https://github.com/cilium/cilium/blob/d3b54929c51235850a1132efa558c0554f961886/bpf/bpf_lxc.c#L796

**Comment by pchaigno** [comment] 2021-06-04 22:38
https://github.com/cilium/cilium/pull/16328 initially meant to fix this, but the fix has been moved to a separate PR.

**Closed as completed** 2021-11-05 08:19 UTC
Labels: kind/bug, needs/triage, kind/community-report, feature/egress-gateway

**Comment by jamallorock** [comment] 2023-05-26 12:25
@UbiquitousBear can you show your full CiliumEgressNATPolicy  ?

**Comment by jamallorock** [comment] 2023-05-26 12:32
@UbiquitousBear  change your manifest from:
`apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-mailserver
spec:
  egress:
  - podSelector:
      matchLabels:
        # The following label selects default namespace
        io.kubernetes.pod.namespace: mailserver
    # Or use namespace label selector to select multiple namespaces
    # namespaceSelector:
    #  matchLabels:
    #    ns: default
  destinationCIDRs:
  - 0.0.0.0/0
  egressSourceIP: "51.195.x.x" `


to:
`apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-mailserver
spec:
  egress:
    **- namespaceSelector:
        matchLabels:
          ns: mailserver**
    # Or use namespace label selector to select multiple namespaces
    # namespaceSelector:
    #  matchLabels:
    #    ns: default
  destinationCIDRs:
  - 0.0.0.0/0
  egressSourceIP: "51.195.x.x" `
