### ISSUE TITLE
Connecting to ClusterIP service not possible from inside service pod with ingress policy

### ISSUE THREAD

**Issue by cyvcloud** [cilium/cilium#22107] opened 2022-11-11 11:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Create a simple pod with a ClusterIP service pointing to it:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```
Connecting to the service from inside the container works as expected:
```
$ kubectl exec -it nginx -- bash
root@nginx:/# curl -v --connect-timeout 5 nginx-service
*   Trying 10.107.234.179:80...
* Connected to nginx-service (10.107.234.179) port 80 (#0)
> GET / HTTP/1.1
> Host: nginx-service
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Fri, 11 Nov 2022 11:08:12 GMT
< Content-Type: text/html
< Content-Length: 615
< Last-Modified: Wed, 19 Oct 2022 08:02:20 GMT
< Connection: keep-alive
< ETag: "634faf0c-267"
< Accept-Ranges: bytes
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Connection #0 to host nginx-service left intact
```
Add a network policy allowing ingress access on port 80:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-networkpolicy
spec:
  ingress:
  - ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: proxy
  policyTypes:
  - Ingress
```
Trying to connect to the service from inside the container now does not work anymore:
```
$ kubectl exec -it nginx -- bash
root@nginx:/# curl -v --connect-timeout 5 nginx-service
*   Trying 10.107.234.179:80...
* Connection timed out after 5001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 5001 milliseconds
```

### Cilium Version

cilium-cli: v0.12.6 compiled with go1.19.1 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3
cilium image (running): v1.12.2

### Kernel Version

```yaml
System Info:
  Machine ID:                 1e3016a9d7c74efdbc4c4102e1b1debf
  System UUID:                1e3016a9-d7c7-4efd-bc4c-4102e1b1debf
  Boot ID:                    9541ba81-63ec-4b84-9578-90df63d3b23c
  Kernel Version:             5.4.0-125-generic
  OS Image:                   Ubuntu 20.04.5 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.5
  Kubelet Version:            v1.24.7
  Kube-Proxy Version:         v1.24.7
```

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20221111-122534.zip](https://github.com/cilium/cilium/files/9989810/cilium-sysdump-20221111-122534.zip)

### Anything else?

The same behaviour does not occur with Cilium 1.11.10. With this version connecting from the pod to the service with the same NetworkPolicy works as expected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment] 2022-11-15 01:43
We are supposed to skip policy enforcement on hairpin traffic - https://github.com/cilium/cilium/commit/52cd6da139c1ac5d67de65a821f953c936034f2e. So this looks like a regression introduced in 1.12. There is a variation of this issue reported here - https://github.com/cilium/cilium/issues/19406#issuecomment-1259821164. 

Based on the traces André shared above, here are some preliminary observations - 

```
-> endpoint 60 flow 0x936eefd0 , identity 2676->2676 state established ifindex lxc55b53e15d98c orig-ip 169.254.42.1: 169.254.42.1:54408 -> 10.0.0.100:80 tcp SYN
Policy verdict log: flow 0xc335eef7 local EP ID 60, remote ID 2676, proto 6, ingress, action deny, match none, 10.108.156.30:80 -> 10.0.0.100:54408 tcp SYN, ACK
```

We can see that the request was correctly SNAT'd, but policy enforcement is happening on the reply which should've been skipped. I suspect that `ct_state.loopback` is somehow lost across tail calls. Regression _potentially_ introduced by commit - https://github.com/cilium/cilium/pull/19818/commits/679047affbe6647deb31583ec91881ee85c9520b.

**Comment by aditighag** [comment] 2022-12-08 22:02
@cyvcloud Thanks for the steps to reproduce the issue. I was able to reproduce the regression (not seen on v1.11.10). As mentioned in the previous comment, we are supposed to skip policy enforcement for hairpin traffic. While the [commit](https://github.com/cilium/cilium/commit/52cd6da139c1ac5d67de65a821f953c936034f2e) fixed it for egress path, the same is expected for the ingress path as well. 

Here is a snippet of cilium monitor output:

```
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Conntrack lookup 1/2: src=10.244.1.81:80 dst=169.254.42.1:42290
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: CT entry found lifetime=20515375, revnat=4
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: CT verdict: Reply, revnat=4
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Successfully mapped addr=169.254.42.1 to identity=2
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Reverse NAT lookup, index=4
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Performing reverse NAT, address=10.96.18.67 port=80
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Loopback reverse SNAT from=169.254.42.1 to=10.244.1.81
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Attempting local delivery for container id 565 from seclabel 7789
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Conntrack lookup 1/2: src=10.96.18.67:80 dst=10.244.1.81:42290
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: CT verdict: New, revnat=0 ------> This should've been CT_REPLY
CPU 00: MARK 0xf9d30080 FROM 565 DEBUG: Policy evaluation would deny packet from 7789 to 7789
Policy verdict log: flow 0xf9d30080 local EP ID 565, remote ID 7789, proto 6, ingress, action deny, match none, 10.96.18.67:80 -> 10.244.1.81:42290 tcp SYN, ACK

```

As we can see from the snippet, packets are getting dropped because after svc rev xlate, policy enforcement is performed. So there are two issues here: 1) the traffic should've been marked as `CT_REPLY` during CT lookup for policy enforcement 2) policy enforcement is not being skipped for hairpin traffic on the ingress path

(1) could be a regression from https://github.com/cilium/cilium/pull/19818/commits/679047affbe6647deb31583ec91881ee85c9520b. The relevant code path: http://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L1705-L1705 which was introduced in v1.12. Although I'm not sure if this is expected: we are doing policy enforcement on a service vip (after rev xlate).

(2) is because we are clearing the skip_policy mark before handing the packet for local delivery - https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L984.

Potential fix: 
There are two ways to allow this traffic: as a CT_REPLY, or policy enforcement should be skipped altogether as we do it on the egress path. For latter approach, we could check for `ctx_load_meta(ctx, CB_POLICY)` in `ipv{4,6}_local_delivery` before doing the tail call for ingress policy enforcement, unless there are conflicts.

**Closed as completed** 2023-01-10 19:32 UTC
Labels: kind/bug, area/datapath, needs/triage, kind/community-report, kind/regression

**Comment by voltagebots** [comment] 2023-02-08 13:51
was this fixed in v[1.12.6](https://github.com/cilium/cilium/releases/tag/v1.12.6). I'm still seeing same behavior even though i'm runnin the latest release v1.12.6.

The pod isn't able top communicate with the cluster ip.

**Comment by Robert-Stam** [comment] 2023-02-14 21:56
We do see this dropping packages as well running 1.12.6, so was this really fixed in that version (we didn't run 1.12.7 to see if that helps)

**Comment by aditighag** [comment] 2023-02-14 22:13
@voltagebots Did you try the latest cilium version (v1.13.0-rc5)?

**Comment by voltagebots** [comment] 2023-02-15 17:02
So, i did a couple of test using v1.12.6, v1.12.7 and v1.13.0-rc5 using our configs (values.yaml) - and i still saw the drops.

I Removed cilium from one of our test env and installed v1.12.6 & v1.12.7 using the default values - and to my surprise, there were no drops. Everything worked as expected.

I'm thinking, its related to a config issue and currently trying to do a diff btw my config against cilium's to try and understand why..

I'll keep you guys updated.

**Comment by voltagebots** [comment] 2023-02-21 12:20
so when using eni-mode, i see the drops. i've followed the config instructions from the docs but i've had no luck...

**Comment by Robert-Stam** [comment] 2023-02-21 13:24
We have the same and as work around we now use IP based communication instead of service based. (Basically we resolve the IP address by getting the Endpoint object from K8s). Hope this helps to get a work around it.

**Comment by voltagebots** [comment] 2023-02-21 13:43
@Robert-Stam , thanks...
to be clear, do you mean using the cluster ip or do you mean the cilium endpoint ip address?

**Comment by aditighag** [comment] 2023-02-21 13:55
@voltagebots As discussed on Slack, please file a new issue, and attach a sysdump from your cluster. Please also highlight the configuration from your cluster. This issue is resolved with the fix linked above. We also have an updated CI test to catch such regressions in future.

**Comment by voltagebots** [comment] 2023-02-21 14:21
@aditighag - i have created [a new issue](https://github.com/cilium/cilium/issues/23911) with the requested info.. thanks
