### ISSUE TITLE
CI: Conformance Runtime - Test_PodIPPoolAdvert failure

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#30237] opened 2024-01-12 23:32 UTC
## CI failure

Hit on https://github.com/cilium/cilium/pull/30183
Link: https://github.com/cilium/cilium/actions/runs/7480430927/job/20359924251

```
--- FAIL: Test_PodIPPoolAdvert (8.07s)
    --- FAIL: Test_PodIPPoolAdvert/matching_ipv4_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 11.1.1.0 24 false []}]
        adverts_test.go:431: received events: [{65001 10.1.1.0 24 false []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/matching_ipv4_pool
            	Messages:   	matching ipv4 pool
    --- FAIL: Test_PodIPPoolAdvert/update_matching_ipv4_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 11.1.1.0 24 true []} {65001 11.2.1.0 24 false []}]
        adverts_test.go:431: received events: [{65001 10.1.2.0 24 false []} {65001 11.1.1.0 24 false []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/update_matching_ipv4_pool
            	Messages:   	update matching ipv4 pool
    --- FAIL: Test_PodIPPoolAdvert/matching_ipv6_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 2001:0:0:1234:5678:: 96 false []} {65001 11.2.1.0 24 true []}]
        adverts_test.go:431: received events: [{65001 10.1.2.0 24 true []} {65001 10.1.1.0 24 true []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/matching_ipv6_pool
            	Messages:   	matching ipv6 pool
    --- FAIL: Test_PodIPPoolAdvert/update_matching_ipv6_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 2001:0:0:1234:5678:: 96 true []} {65001 2002:0:0:1234:5678:: 96 false []}]
        adverts_test.go:431: received events: [{65001 11.2.1.0 24 false []} {65001 11.1.1.0 24 true []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2002:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2002:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/update_matching_ipv6_pool
            	Messages:   	update matching ipv6 pool
```

**Comment by rastislavs** [comment] 2024-02-01 12:20
Hit in https://github.com/cilium/cilium/pull/30440 - job https://github.com/cilium/cilium/actions/runs/7738391682/job/21099140614

**Comment by dylandreimerink** [comment] 2024-02-23 10:18
+1 Hit this just now.
https://github.com/cilium/cilium/actions/runs/8017423656/job/21901426809
Logs: [logs_2067640.zip](https://github.com/cilium/cilium/files/14384094/logs_2067640.zip)

**Comment by christarazi** [comment] 2024-07-17 23:26
Seen again in https://github.com/cilium/cilium/pull/33860 at https://github.com/cilium/cilium/actions/runs/9979635155/job/27579321909.

cc @rastislavs can you take a look?

**Comment by rastislavs** [comment] 2024-07-18 17:52
> Seen again in #33860 at https://github.com/cilium/cilium/actions/runs/9979635155/job/27579321909.

yeah, it seems to be to same flake, looks like the root cause is in something else than what I fixed :(

**Comment by giorio94** [comment] 2024-07-19 11:59
Hit again as well: https://github.com/cilium/cilium/actions/runs/10006033738/job/27657940599

**Comment by rastislavs** [comment] 2024-10-02 07:46
Fixed in https://github.com/cilium/cilium/pull/34270 and already backported to v1.16 & v1.15

**Closed as completed by rastislavs** 2024-10-02 07:46 UTC
Labels: area/CI, ci/flake, area/bgp
