### ISSUE TITLE
panic in GetIdentityCache

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4227] opened 2018-05-23 19:45 UTC
```
goroutine 216 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc42160e290)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc42160e284)
        /usr/local/go/src/sync/rwmutex.go:50 +0x49
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF.func1(0xc42160e280, 0xbeb98eaacf31578a, 0x6e74fef7, 0x2911b60)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:520 +0x3a
panic(0x173e6e0, 0xc421fa2e00)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cilium/cilium/pkg/identity.GetIdentityCache.func1(0x9672, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/identity/cache.go:36 +0xee
github.com/cilium/cilium/pkg/kvstore/allocator.(*Allocator).ForeachCache(0xc4210a0c00, 0xc421ef11e0)
        /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:322 +0xc1
github.com/cilium/cilium/pkg/identity.GetIdentityCache(0x1747e80)
        /go/src/github.com/cilium/cilium/pkg/identity/cache.go:35 +0x56
github.com/cilium/cilium/pkg/endpoint.getLabelsMap(0xc42151e0f0, 0xc421ef13e8, 0x1)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:122 +0x43
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc42160e280, 0x1b6b940, 0xc42042b680, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:429 +0xf7
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc42160e280, 0x1b6b940, 0xc42042b680, 0xc421fab960, 0x20, 0x19b8220, 0x17, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:629 +0x16e9
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc42160e280, 0x1b6b940, 0xc42042b680, 0x19b8220, 0x17, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:610 +0x3aa
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0x19b8220, 0x17, 0x1b6b940, 0xc42042b680, 0xc421f77c60, 0xc42160e280)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:694 +0x216
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:677 +0x137
```

happens locally with consul, compilation with commit 7ec8ebc211de0ec26c2dfef27396987d785ed146

```
$ sudo cat /etc/sysconfig/cilium 

PATH=/usr/lib/llvm-3.8/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
CILIUM_OPTS=--kvstore consul --kvstore-opt consul.address=127.0.0.1:8500 --debug --debug-verbose flow
INITSYSTEM=SYSTEMD
```

**Comment by tgraf** [comment] 2018-05-28 16:12
Possibly related: https://github.com/cilium/cilium/issues/4213

**Comment by tgraf** [comment] 2018-05-30 17:54
Duplicate of #4213

**Closed as completed by tgraf** 2018-05-30 17:54 UTC
Labels: kind/bug, kind/duplicate, needs/triage
