### ISSUE TITLE
CI: Suite-k8s-1.15.K8sDatapathConfig Encapsulation Check iptables masquerading with random-fully

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#14949] opened 2021-02-12 05:29 UTC
## CI failure
- Failing for the past 22 builds (Since #0 ) 
- Observed in https://github.com/cilium/cilium/pull/14930
- Copy-paste the output the test failure.
```
/home/jenkins/workspace/Cilium-PR-K8s-1.15-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Pod "testclient-bkzps" can not connect to "http://google.com"
Expected command: kubectl exec -n 202102110558k8sdatapathconfigencapsulationcheckiptablesmasquera testclient-bkzps -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://google.com -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" --retry 10 
To succeed, but it failed:
Exitcode: -1 
Err: signal: killed
Stdout:
 	 
Stderr:
```

- Upload the zip file generated from that test failure.
[986a2f35_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip](https://github.com/cilium/cilium/files/5969817/986a2f35_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip)

- Copy-paste the link of the CI build where that test failure has happen.

  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.15-kernel-4.9/21/testReport/junit/Suite-k8s-1/15/K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random_fully/

**Comment by pchaigno** [comment] 2021-02-12 07:57
Duplicate of https://github.com/cilium/cilium/issues/13773.

**Closed as completed by pchaigno** 2021-02-12 07:57 UTC
Labels: area/CI, ci/flake
