### ISSUE TITLE
CI: Suite-k8s-1.13.K8sDatapathConfig Encapsulation Check iptables masquerading with random-fully

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#15424] opened 2021-03-22 22:11 UTC
## CI failure

Observed on #15420 

```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
cilium pre-flight checks failed
Expected
    <*errors.errorString | 0xc001a302b0>: {
        s: "Cilium validation failed: 4m0s timeout expired: Last polled error: controllers are failing: cilium-agent 'cilium-97zh7': controller bpf-map-sync-cilium_snat_v6_external is failing: Exitcode: 0 \nStdout:\n \t KVStore:                Ok   Disabled\n\t Kubernetes:             Ok   1.13 (v1.13.12) [linux/amd64]\n\t Kubernetes APIs:        [\"cilium/v2::CiliumClusterwideNetworkPolicy\", \"cilium/v2::CiliumEndpoint\", \"cilium/v2::CiliumNetworkPolicy\", \"cilium/v2::CiliumNode\", \"core/v1::Endpoint\", \"core/v1::Namespace\", \"core/v1::Node\", \"core/v1::Pods\", \"core/v1::Service\", \"networking.k8s.io/v1::NetworkPolicy\"]\n\t KubeProxyReplacement:   Strict   [enp0s8 192.168.36.12 fd04::12 (Direct Routing), enp0s3 10.0.2.15 fd04::12]\n\t Cilium:                 Ok   1.9.90 (v.1.9.90-r.a62c465)\n\t NodeMonitor:            Listening for events on 3 CPUs with 64x4096 of shared memory\n\t Cilium health daemon:   Ok   \n\t IPAM:                   IPv4: 3/255 allocated from 10.0.1.0/24, IPv6: 3/255 allocated from fd02::100/120\n\t BandwidthManager:       EDT with BPF   [enp0s8, enp0s3]\n\t Host Routing:           Legacy\n\t Masquerading:           IPTables [IPv4: Enabled, IPv6: Enabled]\n\t Controller Status:      27/28 healthy\n\t   Name                                          Last success   Last error   Count   Message\n\t   bpf-map-sync-cilium_lxc                       9s ago         never        0       no error            \n\t   bpf-map-sync-cilium_snat_v4_external          9s ago         never        0       no error            \n\t   bpf-map-sync-cilium_snat_v6_external          never          13s ago      22      4 map sync errors   \n\t   bpf-map-sync-cilium_throttle                  9s ago         never        0       no error            \n\t   cilium-health-ep                              1m4s ago       never        0       no error            \n\t   dns-garbage-collector-job                     22s ago        never        0       no error            \n\t   endpoint-1524-regeneration-recovery           never          never        0       no error            \n\t   endpoint-1929-regeneration-recovery           never          never        0       no error            \n\t   endpoint-462-regeneration-recovery            never          never        0       no error            \n\t   endpoint-gc                                   4m22s ago      never        0       no error            \n\t   k8s-heartbeat                                 22s ago        never        0       no error            \n\t   mark-k8s-node-as-available                    4m4s ago       never        0       no error            \n\t   metricsmap-bpf-prom-sync                      7s ago         never        0       no error            \n\t   neighbor-table-refresh                        34s ago        never        0       no error            \n\t   resolve-identity-462                          4m4s ago       never        0       no error            \n\t   restoring-ep-identity (1524)                  4m4s ago       never        0       no error            \n\t   restoring-ep-identity (1929)                  4m5s ago       never        0       no error            \n\t   sync-endpoints-and-host-ips                   5s ago         never        0       no error            \n\t   sync-lb-maps-with-k8s-services                4m4s ago       never        0       no error            \n\t   sync-policymap-1524                           51s ago        never        0       no error            \n\t   sync-policymap-1929                           49s ago        never        0       no error            \n\t   sync-policymap-462                            51s ago        never        0       no error            \n\t   sync-to-k8s-ciliumendpoint (1524)             4s ago         never        0       no error            \n\t   sync-to-k8s-ciliumendpoint (1929)             4s ago         never        0       no error            \n\t   sync-to-k8s-ciliumendpoint (462)              14s ago        never        0       no error            \n\t   template-dir-watcher                          never          never        0       no error            \n\t   update-k8s-node-annotations                   4m21s ago      never        0       no error            \n\t   waiting-initial-global-identities-ep (1524)   4m4s ago       never        0       no error            \n\t Proxy Status:     OK, ip 10.0.1.115, 0 redirects active on ports 10000-20000\n\t Hubble:           Ok              Current/Max Flows: 1367/4095 (33.38%), Flows/s: 5.47   Metrics: Disabled\n\t Cluster health:   2/2 reachable   (2021-03-22T19:16:40Z)\n\t \nStderr:\n \t \n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/helpers/manifest.go:316
```

- Zip Archive: [0b9bde5f_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip](https://github.com/cilium/cilium/files/6185517/0b9bde5f_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip)

- [CI Build](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/1110/testReport/junit/Suite-k8s-1/13/K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random_fully/)

**Comment by pchaigno** [comment] 2021-03-22 22:19
It's a duplicate of https://github.com/cilium/cilium/issues/15337.

**Closed as completed by pchaigno** 2021-03-22 22:19 UTC
Labels: area/CI, ci/flake
