### ISSUE TITLE
CI: RuntimeValidatedLB - Timeout reached: could not import policy

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4638] opened 2018-06-26 06:02 UTC
Hit this flake/bug in the master CI:

```
runtime.RuntimeValidatedLB Services Policies tests with conntrack enabled 

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Expected
    <*errors.errorString | 0xc420341b60>: {
        s: "Timeout reached: could not import policy",
    }
to be nil
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/runtime/lb.go:390
```
```
Jun 25 17:38:50: level=debug msg="sending xDS response with 3 resources" xdsCanary=false xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.api.v2.Listener xdsVersionInfo=3
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:584] [C0][S16474759579739152766] upstream headers complete: end_stream=false" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/async_client_impl.cc:92] async http request response headers (end_stream=false):" subsys=envoy-http threadID=29698
Jun 25 17:38:50: level=debug msg="':status', '200'" subsys=envoy-http threadID=29698
Jun 25 17:38:50: level=debug msg="'content-type', 'application/grpc'" subsys=envoy-http threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:160] Received gRPC message for type.googleapis.com/envoy.api.v2.Listener at version 3" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:511] begin add/update listener: name=34421:egress:TCP:80 hash=16752851717418687127" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:68]   filter #0:" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:69]     name: cilium.bpf_metadata" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:72]   config: {\"bpf_root\":\"/sys/fs/bpf\",\"is_ingress\":false}" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[cilium_host_map.cc:130] PolicyHostMap(cilium.hostmap.1.) created." subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:103] gRPC mux subscribe for type.googleapis.com/cilium.NetworkPolicyHosts" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:51] No stream available to sendDiscoveryRequest for type.googleapis.com/cilium.NetworkPolicyHosts" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:36] Establishing new gRPC bidi stream for rpc StreamNetworkPolicyHosts(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:253] [C0][S6768754963246003451] cluster 'xds-grpc-cilium' match for URL '/cilium.NetworkPolicyHostsDiscoveryService/StreamNetworkPolicyHosts'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:304] [C0][S6768754963246003451] router decoding headers:" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':method', 'POST'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':path', '/cilium.NetworkPolicyHostsDiscoveryService/StreamNetworkPolicyHosts'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':authority', 'xds-grpc-cilium'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':scheme', 'http'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'te', 'trailers'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'content-type', 'application/grpc'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'x-envoy-internal', 'true'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'x-forwarded-for', '10.0.2.15'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/http2/conn_pool.cc:97] [C0] creating stream" subsys=envoy-pool threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:972] [C0][S6768754963246003451] pool ready" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:38]   filter #0:" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:39]     name: cilium.network" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:42]   config: {}" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:38]   filter #1:" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:39]     name: envoy.http_connection_manager" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/listener_manager_impl.cc:42]   config: {\"route_config\":{\"virtual_hosts\":[{\"name\":\"default_route\",\"routes\":[{\"match\":{\"prefix\":\"/\"},\"route\":{\"max_grpc_timeout\":{},\"cluster\":\"cluster1\"}}],\"domains\":[\"*\"]}]},\"http_filters\":[{\"name\":\"cilium.l7policy\",\"config\":{\"denied_403_body\":\"\",\"access_log_path\":\"/var/run/cilium/access_log.sock\",\"policy_name\":\"10.15.236.103\"}},{\"config\":{},\"name\":\"envoy.router\"}],\"stat_prefix\":\"proxy\"}" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/extensions/filters/network/http_connection_manager/config.cc:232]     filter #0" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/extensions/filters/network/http_connection_manager/config.cc:233]       name: cilium.l7policy" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/extensions/filters/network/http_connection_manager/config.cc:237]     config: {\"policy_name\":\"10.15.236.103\",\"access_log_path\":\"/var/run/cilium/access_log.sock\",\"denied_403_body\":\"\"}" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=info msg="Envoy: Accepted access log connection"
Jun 25 17:38:50: level=debug msg="[cilium_network_policy.cc:19] NetworkPolicyMap(cilium.policymap.1.) created." subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:103] gRPC mux subscribe for type.googleapis.com/cilium.NetworkPolicy" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:51] No stream available to sendDiscoveryRequest for type.googleapis.com/cilium.NetworkPolicy" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/config/grpc_mux_impl.cc:36] Establishing new gRPC bidi stream for rpc StreamNetworkPolicies(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:253] [C0][S17018549775723574548] cluster 'xds-grpc-cilium' match for URL '/cilium.NetworkPolicyDiscoveryService/StreamNetworkPolicies'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:304] [C0][S17018549775723574548] router decoding headers:" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':method', 'POST'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':path', '/cilium.NetworkPolicyDiscoveryService/StreamNetworkPolicies'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':authority', 'xds-grpc-cilium'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="':scheme', 'http'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'te', 'trailers'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'content-type', 'application/grpc'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'x-envoy-internal', 'true'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="'x-forwarded-for', '10.0.2.15'" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/http2/conn_pool.cc:97] [C0] creating stream" subsys=envoy-pool threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:972] [C0][S17018549775723574548] pool ready" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/extensions/filters/network/http_connection_manager/config.cc:232]     filter #1" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/extensions/filters/network/http_connection_manager/config.cc:233]       name: envoy.router" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/extensions/filters/network/http_connection_manager/config.cc:237]     config: {}" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=info msg="Envoy: Closing access log connection"
Jun 25 17:38:50: level=debug msg="[cilium_network_policy.h:31] Cilium L7 NetworkPolicyMap(cilium.policymap.1.): NetworkPolicyMap is deleted NOW!" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:917] [C0][S17018549775723574548] resetting pool request" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/codec_client.cc:104] [C0] request reset" subsys=envoy-client threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/http2/conn_pool.cc:189] [C0] destroying stream: 2 remaining" subsys=envoy-pool threadID=29698
Jun 25 17:38:50: level=debug msg="[cilium_host_map.h:59] Cilium PolicyHostMap(cilium.hostmap.1.): PolicyHostMap is deleted NOW!" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/router/router.cc:917] [C0][S6768754963246003451] resetting pool request" subsys=envoy-router threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/codec_client.cc:104] [C0] request reset" subsys=envoy-client threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/http2/conn_pool.cc:189] [C0] destroying stream: 1 remaining" subsys=envoy-pool threadID=29698
Jun 25 17:38:50: level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 34421:egress:TCP:80: cannot bind '[::]:15063': Address already in use" subsys=envoy-upstream threadID=29698
Jun 25 17:38:50: level=warning msg="[bazel-out/k8-fastbuild/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 34421:egress:TCP:80: cannot bind '[::]:15063': Address already in use" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=info msg="[external/envoy/source/server/listener_manager_impl.cc:781] all dependencies initialized. starting workers" subsys=envoy-config threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/http2/codec_impl.cc:501] [C0] stream closed: 0" subsys=envoy-http2 threadID=29698
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/http/http2/codec_impl.cc:501] [C0] stream closed: 0" subsys=envoy-http2 threadID=29698
Jun 25 17:38:50: level=debug msg="received request from xDS stream" xdsClientNode="id:\"host~127.0.0.1~no-id~localdomain\" cluster:\"cluster1\" build_version:\"c61041a51d86443cc6a8bd4157611db82e1b8a39/1.7.0-dev/Modified/DEBUG\" " xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.api.v2.Listener xdsVersionInfo=
Jun 25 17:38:50: level=warning msg="NACK received for version 3; waiting for a version update before sending again" xdsClientNode="id:\"host~127.0.0.1~no-id~localdomain\" cluster:\"cluster1\" build_version:\"c61041a51d86443cc6a8bd4157611db82e1b8a39/1.7.0-dev/Modified/DEBUG\" " xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.api.v2.Listener xdsVersionInfo=
Jun 25 17:38:50: level=debug msg="starting watch on 0 resources" xdsClientNode="id:\"host~127.0.0.1~no-id~localdomain\" cluster:\"cluster1\" build_version:\"c61041a51d86443cc6a8bd4157611db82e1b8a39/1.7.0-dev/Modified/DEBUG\" " xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.api.v2.Listener xdsVersionInfo=
Jun 25 17:38:50: level=debug msg="current resource version is 3, waiting for it to become > 3" xdsClientNode="id:\"host~127.0.0.1~no-id~localdomain\" cluster:\"cluster1\" build_version:\"c61041a51d86443cc6a8bd4157611db82e1b8a39/1.7.0-dev/Modified/DEBUG\" " xdsTypeURL=type.googleapis.com/envoy.api.v2.Listener xdsVersionInfo=0xc423151408
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/worker_impl.cc:91] worker entering dispatch loop" subsys=envoy-main threadID=29710
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/upstream/cluster_manager_impl.cc:682] adding TLS initial cluster cluster1" subsys=envoy-upstream threadID=29710
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/upstream/cluster_manager_impl.cc:682] adding TLS initial cluster xds-grpc-cilium" subsys=envoy-upstream threadID=29710
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/upstream/cluster_manager_impl.cc:776] membership update for TLS cluster xds-grpc-cilium" subsys=envoy-upstream threadID=29710
Jun 25 17:38:50: level=debug msg="[external/envoy/source/server/worker_impl.cc:91] worker entering dispatch loop" subsys=envoy-main threadID=29711
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/upstream/cluster_manager_impl.cc:682] adding TLS initial cluster cluster1" subsys=envoy-upstream threadID=29711
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/upstream/cluster_manager_impl.cc:682] adding TLS initial cluster xds-grpc-cilium" subsys=envoy-upstream threadID=29711
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/upstream/cluster_manager_impl.cc:776] membership update for TLS cluster xds-grpc-cilium" subsys=envoy-upstream threadID=29711
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/grpc/google_async_client_impl.cc:39] completionThread running" subsys=envoy-grpc threadID=29712
Jun 25 17:38:50: level=debug msg="[external/envoy/source/common/grpc/google_async_client_impl.cc:39] completionThread running" subsys=envoy-grpc threadID=29713
Jun 25 17:38:51: level=debug msg="[external/envoy/source/common/upstream/original_dst_cluster.cc:155] Cleaning up stale original dst hosts." subsys=envoy-upstream threadID=29698
Jun 25 17:38:51: level=debug msg="Waiting for proxy updates to complete..." containerID=3ba1a1579a endpointID=16033 ipv4=10.15.251.123 ipv6="f00d::a0f:0:0:3ea1" k8sPodName=":" policyRevision=9
Jun 25 17:38:51: level=debug msg="Wait time for proxy updates: 566.96µs" containerID=3ba1a1579a endpointID=16033 ipv4=10.15.251.123 ipv6="f00d::a0f:0:0:3ea1" k8sPodName=":" policyRevision=9
Jun 25 17:38:51: level=info msg="Regeneration of BPF program has completed" buildDuration=1.673635563s containerID=3ba1a1579a endpointID=16033 ipv4=10.15.251.123 ipv6="f00d::a0f:0:0:3ea1" k8sPodName=":" policyRevision=9
Jun 25 17:38:51: level=info msg="Endpoint policy recalculated" containerID=3ba1a1579a endpointID=16033 ipv4=10.15.251.123 ipv6="f00d::a0f:0:0:3ea1" k8sPodName=":" policyRevision=9
Jun 25 17:38:51: level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID=3ba1a1579a endpointID=16033 endpointState=ready ipv4=10.15.251.123 ipv6="f00d::a0f:0:0:3ea1" k8sPodName=":" policyRevision=9 type=0
Jun 25 17:38:51: level=debug msg="Successfully regenerated endpoint program due to endpoint policy updated & changes were needed" code=OK containerID=3ba1a1579a endpointID=16033 endpointState=ready ipv4=10.15.251.123 ipv6="f00d::a0f:0:0:3ea1" k8sPodName=":" policyRevision=9 type=200
Jun 25 17:38:53: level=debug msg="[external/envoy/source/common/upstream/original_dst_cluster.cc:155] Cleaning up stale original dst hosts." subsys=envoy-upstream threadID=29698
Jun 25 17:38:54: level=debug msg="[external/envoy/source/common/upstream/original_dst_cluster.cc:155] Cleaning up stale original dst hosts." subsys=envoy-upstream threadID=29698
Jun 25 17:38:55: level=debug msg="[external/envoy/source/server/server.cc:118] flushing stats" subsys=envoy-main threadID=29698
Jun 25 17:38:55: level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc421951800 Labels:[]}"
Jun 25 17:38:55: level=debug msg="Found unwatched container" containerID=dc0133d04a subsys=workload-watcher
Jun 25 17:38:55: level=debug msg="Found unwatched container" containerID=3ba1a1579a subsys=workload-watcher
Jun 25 17:38:55: level=debug msg="Found unwatched container" containerID=ecd50dcf43 subsys=workload-watcher
Jun 25 17:38:55: level=debug msg="Found unwatched container" containerID=028efdbd5b subsys=workload-watcher
Jun 25 17:38:55: level=debug msg="Found unwatched container" containerID=254b7a5aac subsys=workload-watcher
Jun 25 17:38:55: level=debug msg="Found unwatched container" containerID=08cc91b994 subsys=workload-watcher
Jun 25 17:38:55: level=debug msg="Trying to associate container with existing endpoint" containerID=dc0133d04a containerName=/httpd3 endpointID=0 identityLabels="container:id.httpd3,container:id.service1" maxRetry=20 retry=1 subsys=workload-watcher willRetry=false
Jun 25 17:38:55: level=debug msg="Refreshing labels of endpoint" containerID=dc0133d04a endpointID=50812 identityLabels="container:id.httpd3,container:id.service1" infoLabels=
Jun 25 17:38:55: level=debug msg="Trying to associate container with existing endpoint" containerID=3ba1a1579a containerName=/httpd2 endpointID=0 identityLabels="container:id.httpd2,container:id.service1" maxRetry=20 retry=1 subsys=workload-watcher willRetry=false
Jun 25 17:38:55: level=debug msg="Refreshing labels of endpoint" containerID=3ba1a1579a endpointID=16033 identityLabels="container:id.httpd2,container:id.service1" infoLabels=
Jun 25 17:38:55: level=debug msg="Trying to associate container with existing endpoint" containerID=08cc91b994 containerName=/app1 endpointID=0 identityLabels="container:id.app1" maxRetry=20 retry=1 subsys=workload-watcher willRetry=false
Jun 25 17:38:55: level=debug msg="Refreshing labels of endpoint" containerID=08cc91b994 endpointID=297 identityLabels="container:id.app1" infoLabels=
Jun 25 17:38:55: level=debug msg="Trying to associate container with existing endpoint" containerID=ecd50dcf43 containerName=/httpd1 endpointID=0 identityLabels="container:id.httpd1,container:id.service1" maxRetry=20 retry=1 subsys=workload-watcher willRetry=false
Jun 25 17:38:55: level=debug msg="Refreshing labels of endpoint" containerID=ecd50dcf43 endpointID=58626 identityLabels="container:id.httpd1,container:id.service1" infoLabels=
Jun 25 17:38:55: level=debug msg="Trying to associate container with existing endpoint" containerID=028efdbd5b containerName=/app3 endpointID=0 identityLabels="container:id.app3" maxRetry=20 retry=1 subsys=workload-watcher willRetry=false
Jun 25 17:38:55: level=debug msg="Refreshing labels of endpoint" containerID=028efdbd5b endpointID=34421 identityLabels="container:id.app3" infoLabels=
Jun 25 17:38:55: level=debug msg="Trying to associate container with existing endpoint" containerID=254b7a5aac containerName=/app2 endpointID=0 identityLabels="container:id.app2" maxRetry=20 retry=1 subsys=workload-watcher willRetry=false
Jun 25 17:38:55: level=debug msg="Refreshing labels of endpoint" containerID=254b7a5aac endpointID=22937 identityLabels="container:id.app2" infoLabels=
Jun 25 17:38:56: level=debug msg="[external/envoy/source/common/upstream/original_dst_cluster.cc:155] Cleaning up stale original dst hosts." subsys=envoy-upstream threadID=29698
Jun 25 17:38:56: level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc421b76400 Labels:[]}"
Jun 25 17:38:57: level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc424355b00 Labels:[]}"
Jun 25 17:38:57: level=debug msg="[external/envoy/source/common/upstream/original_dst_cluster.cc:155] Cleaning up stale original dst hosts." subsys=envoy-upstream threadID=29698
Jun 25 17:38:58: level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc421b76d00 Labels:[]}"
Jun 25 17:38:59: level=debug msg="[external/envoy/source/common/upstream/original_dst_cluster.cc:155] Cleaning up stale original dst hosts." subsys=envoy-upstream threadID=29698
Jun 25 17:38:59: level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc421b77400 Labels:[]}"
Jun 25 17:39:00: level=error msg="destroying BPF maps due toerrors during regeneration" containerID=254b7a5aac endpointID=22937 error="proxy state changes failed: context deadline exceeded" ipv4=10.15.228.56 ipv6="f00d::a0f:0:0:5999" k8sPodName=":" policyRevision=8
Jun 25 17:39:00: level=info msg="Regeneration of BPF program has completed" buildDuration=10.000729991s containerID=254b7a5aac endpointID=22937 ipv4=10.15.228.56 ipv6="f00d::a0f:0:0:5999" k8sPodName=":" policyRevision=8
Jun 25 17:39:00: level=warning msg="Generating BPF for endpoint failed, keeping stale directory." containerID=254b7a5aac endpointID=22937 file-path=22937_next_fail ipv4=10.15.228.56 ipv6="f00d::a0f:0:0:5999" k8sPodName=":" policyRevision=8
```

The test logs for "runtime.RuntimeValidatedLB Services Policies tests with conntrack enabled" can be found in [test_results_master_1117.zip](https://github.com/cilium/cilium/files/2135726/test_results_master_1117.zip)

Assigning @rlenglet and @jrajahalme as initial point of touch for envoy related failures

**Comment by rlenglet** [comment] 2018-06-26 06:06
```
Error adding/updating listener 34421:egress:TCP:80: cannot bind '[::]:15063': Address already in use" subsys=envoy-config threadID=29698
```
This is a duplicate of https://github.com/cilium/cilium/issues/4383.
This will be fixed by https://github.com/cilium/cilium/pull/4535.

**Comment by rlenglet** [comment] 2018-06-26 06:10
Closing since this is a duplicate.

**Closed as completed by rlenglet** 2018-06-26 06:10 UTC
Labels: kind/bug, priority/high, area/proxy
