### ISSUE TITLE
CI: Suite-k8s-1.20.K8sDatapathConfig Host firewall With VXLAN

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#17715] opened 2021-10-27 06:15 UTC
This was observed on master (https://jenkins.cilium.io/job/cilium-master-k8s-1.20-kernel-4.19/1258/testReport/junit/Suite-k8s-1/20/K8sDatapathConfig_Host_firewall_With_VXLAN/), and it seems like a flake.

artifact: [fbcfc768_K8sDatapathConfig_Host_firewall_With_VXLAN.zip](https://github.com/cilium/cilium/files/7423624/fbcfc768_K8sDatapathConfig_Host_firewall_With_VXLAN.zip)

The test is terminated due to a `panic()`

```
Host firewall
/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
  With VXLAN [It]
  /home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
  Test Panicked
  stop execution
  /usr/local/go/src/runtime/panic.go:1038
  Full Stack Trace
  panic({0x186eee0, 0x1ddb090})
  	/usr/local/go/src/runtime/panic.go:1038 +0x215
  github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).pollActual.func1.1({0xc00072a280, 0x25e}, {0xc0021a3cf0, 0xc00140d440, 0x0})
  	/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:95 +0x10d
  github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc000f15e60, {0x1e0b8f8, 0x2e2cbb0}, 0x1, {0xc000f15e30, 0x3, 0x3})
  	/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:79 +0x1bd
  github.com/onsi/gomega/internal/assertion.(*Assertion).Should(0xc000f15e60, {0x1e0b8f8, 0x2e2cbb0}, {0xc000f15e30, 0x3, 0x3})
  	/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:28 +0x95
  github.com/cilium/cilium/test/k8sT.testHostFirewallWithPath(0x1bc1877, {0xc000b00080, 0x32}, {0x1b78bd5, 0x1}, {0x1b80e98, 0x15}, 0xe5)
  	/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:952 +0x5d0
  github.com/cilium/cilium/test/k8sT.testHostFirewall.func1()
  	/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:901 +0xcf
  created by github.com/cilium/cilium/test/k8sT.testHostFirewall
  	/home/jenkins/workspace/cilium-master-k8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:897 +0x371
```

SHA of failure seems to be: da26d0ae6f25c1fa28ba1d686e5505eb245e4908

We seem to be hitting the  panic here: https://github.com/cilium/cilium/blob/da26d0ae6f25c1fa28ba1d686e5505eb245e4908/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go#L94-L95

And our test is failing at:
https://github.com/cilium/cilium/blob/da26d0ae6f25c1fa28ba1d686e5505eb245e4908/test/k8sT/DatapathConfiguration.go#L952-L953

**Comment by tklauser** [comment] 2021-12-06 17:20
This looks like a duplicate of #17661, the panic is at the exact same position. The panic was caused an issue in Ginkgo which has since been resolved by updating Ginkgo, see https://github.com/cilium/cilium/issues/17661#issuecomment-983967186 for a detailed analysis. Thus also closing this issue.

**Closed as completed by tklauser** 2021-12-06 17:20 UTC
Labels: area/CI, ci/flake
