### ISSUE TITLE
CI: Cilium IPsec upgrade (ci-ipsec-upgrade) - v1.12

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#29755] opened 2023-12-08 20:04 UTC
Happened in https://github.com/cilium/cilium/actions/runs/7144075205/job/19456943865

```
📋 Test Report
❌ 1/53 tests failed (0/309 actions), 13 tests skipped, 1 scenarios skipped:
connectivity test failed: 1 tests failed
Test [no-interrupted-connections]:
Error: Process completed with exit code 1.
```

[logs_1959064.zip](https://github.com/cilium/cilium/files/13620513/logs_1959064.zip)

**Comment by pchaigno** [comment] 2023-12-08 20:07
I believe this is a duplicate of https://github.com/cilium/cilium/issues/28088, which AFAIK affects all stable branches in addition to main.

**Closed as completed by pchaigno** 2023-12-08 20:07 UTC
Labels: area/CI, area/encryption, ci/flake
