### ISSUE TITLE
hostPort does not work when between node(host) and another host with network policy.

### ISSUE THREAD

**Issue by mog422** [cilium/cilium#31522] opened 2024-03-20 12:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

reproduction environment
```
kubeadm init --control-plane-endpoint "10.7.255.4:6443" --upload-certs --skip-phases=addon/kube-proxy --service-cidr 10.3.0.0/16,fd02:3:1::/108

helm install cilium cilium/cilium --version 1.15.2 --namespace kube-system --set autoDirectNodeRoutes=true --set enableIPv4Masquerade=false --set enableIPv6Masquerade=false --set ipam.operator.clusterPoolIPv4PodCIDRList=10.4.0.0/16 --set ipam.operator.clusterPoolIPv6PodCIDRList=fd02:3:2::/112 --set ipv6.enabled=true --set k8sServiceHost=10.7.255.4 --set k8sServicePort=6443 --set kubeProxyReplacement=true --set routingMode=native

helm install ingress-nginx ingress-nginx/ingress-nginx --version 4.10.0 --namespace ingress-nginx --set controller.hostPort.enabled=true --set controller.kind=DaemonSet --create-namespace
```

```
root@testclustermaster:~# kubectl get node -o wide
NAME                STATUS   ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
testcluster1        Ready    <none>          6h42m   v1.29.3   10.7.255.5    <none>        Ubuntu 22.04.4 LTS   5.15.0-101-generic   containerd://1.6.28
testcluster2        Ready    <none>          6h42m   v1.29.3   10.7.255.6    <none>        Ubuntu 22.04.4 LTS   5.15.0-101-generic   containerd://1.6.28
testclustermaster   Ready    control-plane   6h42m   v1.29.3   10.7.255.4    <none>        Ubuntu 22.04.4 LTS   5.15.0-101-generic   containerd://1.6.28
```

```
root@testcluster1:~# curl -v 10.7.255.6
*   Trying 10.7.255.6:80...
* Connected to 10.7.255.6 (10.7.255.6) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.7.255.6
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 20 Mar 2024 12:34:43 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host 10.7.255.6 left intact
root@testcluster1:~# kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
EOF
networkpolicy.networking.k8s.io/nginx created
root@testcluster1:~# curl -v 10.7.255.6
*   Trying 10.7.255.6:80...
* connect to 10.7.255.6 port 80 failed: Connection timed out
* Failed to connect to 10.7.255.6 port 80 after 130236 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to 10.7.255.6 port 80 after 130236 ms: Connection timed out
root@testcluster1:~# kubectl delete -n ingress-nginx netpol/nginx
networkpolicy.networking.k8s.io "nginx" deleted
root@testcluster1:~# curl -v 10.7.255.6
*   Trying 10.7.255.6:80...
* Connected to 10.7.255.6 (10.7.255.6) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.7.255.6
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 20 Mar 2024 12:41:02 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host 10.7.255.6 left intact
root@testcluster1:~#
```

### Cilium Version

Client: 1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64
Daemon: 1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64

### Kernel Version

Linux testcluster1 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment] 2024-03-26 16:18
Right, host IPs are special. By default, they cannot be matched with CIDR selectors... and they cannot be matched with label selectors. It's a serious gap in the Cilium policy engine.

You can fix this by setting the Helm value `policyCIDRMatchMode: nodes`.

If this fixes your problem, please let me know! We are debating whether this should be the default.

**Comment by mog422** [comment] 2024-03-26 16:54
Does that mean this is by design?
But, In the above example, curl to same host ip with NetworkPolicy will succeed. (```curl 10.7.255.5``` on testcluster1 (10.7.255.5))

and ```policyCIDRMatchMode: nodes``` fixes this problem.

**Comment by squeed** [comment] 2024-03-27 12:59
This is by design, yes. The problem is that CIDR identities for nodes can consume quite some memory, at least until https://github.com/cilium/cilium/pull/30897 is merged. Then we probably switch this to the default.

The reason it works on the same-node is that local node traffic is always allowed by default.

**Closed as completed** 2024-03-28 03:54 UTC
Labels: kind/bug, needs/triage, kind/community-report, info-completed
