### ISSUE TITLE
Unable to use Cilium in a k3s env

### ISSUE THREAD

**Issue by CiraciNicolo** [cilium/cilium#20603] opened 2022-07-20 17:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Unable to configure Cilium, while wanting to replace kubeproxy with Cilium, on a k3s enviroment with 1 master + 3 agents. DaemonSet just fall in Crashloopbackoff with the following error:

`level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to setup base devices in mode tunnel: invalid argument" subsys=daemon`

Current config:

```
---
debug:
  enabled: true

k8sServiceHost: 172.16.68.65
k8sServicePort: 6443

devices: eth0
enableRuntimeDeviceDetection: true

encryption:
  enabled: false
  nodeEncryption: false

ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDR: "10.69.0.0/16"
    clusterPoolIPv4MaskSize: 24

kubeProxyReplacement: "strict"
kubeProxyReplacementHealthzBindAddr: "[::]:10256"

operator:
  replicas: 1
  rollOutPods: false
  nodeSelector:
    node-role.kubernetes.io/master: "true"
```

### Cilium Version

cilium-cli: v0.11.11 compiled with go1.18.3 on linux/amd64
cilium image (default): v1.11.6
cilium image (stable): v1.12.0
cilium image (running): -ci:latest

### Kernel Version

Linux redacted 5.18.11-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 09:44:11 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+k3s2", GitCommit:"a237260237b549b90dd3aae449de09231caf1351", GitTreeState:"clean", BuildDate:"2022-07-06T20:08:22Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+k3s2", GitCommit:"a237260237b549b90dd3aae449de09231caf1351", GitTreeState:"clean", BuildDate:"2022-07-06T20:08:22Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.11.11, args: [-n cilium sysdump]
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Kubernetes namespaces
🔍 Collecting Cilium network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Ingresses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the 'clustermesh-apiserver' deployment
⚠️ Deployment "hubble-relay" not found in namespace "kube-system" - this is expected if Hubble is not enabled
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting 'cilium-bugtool' output from Cilium pods
⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting platform-specific data
🔍 Collecting Hubble flows from Cilium pods
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [11] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource (get ciliumegressnatpolicies.cilium.io)
⚠️ [12] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [17] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [18] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ [20] Collecting the Cilium configuration: failed to collect the Cilium configuration: configmaps "cilium-config" not found
⚠️ [21] Collecting the Cilium daemonset(s): failed to find Cilium daemonsets with label "k8s-app=cilium" in namespace "kube-system"
⚠️ [23] Collecting the Hubble Relay configuration: failed to collect the Hubble Relay configuration: configmaps "hubble-relay-config" not found
⚠️ [26] Collecting the Cilium operator deployment: failed to collect the Cilium operator deployment: deployments.apps "cilium-operator" not found
⚠️ Please note that depending on your Cilium version and installation options, this may be expected

### Relevant log output

```shell
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to setup base devices in mode tunnel: invalid argument" subsys=daemon
```

### Anything else?

Deployed with Helm, and custom namespace (cilium)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment] 2022-07-20 23:30
> ### Relevant log output
> ```shell
> level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to setup base devices in mode tunnel: invalid argument" subsys=daemon
> ```

oddly, I grep and search string `mode tunnel` in cilium source, could not find any error log contains `mode tunnel`

**Comment by vincentmli** [comment] 2022-07-21 00:04
I build image based on the master branch with above code, run in 2 node k3s, no problem

**Comment by vincentmli** [comment] 2022-07-21 00:19
commit `c3adaec9dc` removed IPVLAN code but probably forgot to remove `nativeDevs` that is no longer used in `setupBaseDevice()`, so we should remove `nativeDevs`, but  since I build image with it, cilium runs fine, so not sure if it is related to `nativeDevs` not being used, I will send PR to cilium to remove `nativeDevs`

**Comment by CiraciNicolo** [comment] 2022-07-21 07:15
Hi,

this is the cmdline to start k3s (master node):

```
/usr/local/bin/k3s \
        server \
        '--cluster-init' \
        '--node-name=node.name.tld' \
        '--pause-image=private-registry.tld/rancher/pause:3.1' \
        '--cluster-cidr=10.69.0.0/16' \
        '--flannel-backend=none' \
        '--disable-kube-proxy' \
        '--disable-network-policy' \
        '--disable-cloud-controller' \
        '--disable=traefik' \
        '--disable=servicelb' \
        '--disable=coredns' \
        '--kube-apiserver-arg' \
        'service-node-port-range=135-65535'
```

I'm using the latest helm, without compiling cilium itself but using the latest image provided on quay.io. Other info about the environment, we have multiple ifaces for node but only eth0 should be used since the other are mgmt only.

**Comment by CiraciNicolo** [comment] 2022-07-21 10:11
We tried to follow the codepath given the error, as you suggested we think the issues is located at https://github.com/cilium/cilium/blob/8bcc5fe2c594b5fb4b9d2966906c490dea215d83/pkg/datapath/loader/base.go#L423. But the called function is CORRECTLY setupping the ifaces as shown by `ip l`:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 5a:29:29:5c:06:41 brd ff:ff:ff:ff:ff:ff
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
    link/none
4: tun1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
    link/none
7: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2a:e2:27:bf:86:04 brd ff:ff:ff:ff:ff:ff
8: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 16:3c:c6:d5:b8:46 brd ff:ff:ff:ff:ff:ff
```

**Comment by CiraciNicolo** [comment] 2022-07-21 13:44
We were able to understand the issue; our infrastructure is embedding a VPN and therefore an ip is assigned to loopback iface. The lo iface is running an MTU of 65536 and therefore cilium detect that the "node ip" is attached on the lo iface and use that MTU; the strange thing is that the k3s has as internal-ip the one assigned to eth0.

Let me explain better, so you can try to repro:
- k3s internal node ip is x.x.x.x
- x.x.x.x is assigned to eth0
- y.y.y.y is assigned to loopback
- cilium on startup use y.y.y.y to retrieve MTU value but, x.x.x.x should be used

The workaround is to specify an MTU of 1500 to loopback, this should not impact anything since MTU is set to MAX_VALUE for efficiency reasons.

**Comment by vincentmli** [comment] 2022-07-21 13:54
so you mean if manually assign an ip to loopback interface and set loopback interface MTU to 65536 would reproduce the issue?

**Comment by CiraciNicolo** [comment] 2022-07-21 14:04
Yes, at least in our case we noticed this line in the logs:

`level=info msg="Inheriting MTU from external network interface" device=lo ipAddr=100.127.202.4 mtu=65526 subsys=mtu`

and therefore setting the MTU of lo to 1500 fixed the issue. The main issues is understanding why cilium use that iface even if the node ip IS NOT the one assigned to lo.

**Comment by vincentmli** [comment] 2022-07-21 14:53
based on pkg/mtu/mtu.go, you could also workaround the issue by specifying `mtu` in option through helm

```
100 // NewConfiguration returns a new MTU configuration. The MTU can be manually
101 // specified, otherwise it will be automatically detected. if encapEnabled is
102 // true, the MTU is adjusted to account for encapsulation overhead for all
103 // routes involved in node to node communication.
104 func NewConfiguration(authKeySize int, encryptEnabled bool, encapEnabled bool, wireguardEnabled bool, mtu int, mtuDetectI    P net.IP) Configuration {
105         encryptOverhead := 0
106 
107         if mtu == 0 {
108                 var err error
109 
110                 if mtuDetectIP != nil {
111                         mtu, err = getMTUFromIf(mtuDetectIP)
112                 } else {
113                         mtu, err = autoDetect()
114                 }
115                 if err != nil {
116                         log.WithError(err).Warning("Unable to automatically detect MTU")
117                         mtu = EthernetMTU
118                 }
119         }

```

the problem here is for some reason `mtuDetectIP` is the IP assigned to your loopback interface, thus `mtu` get `65526`.  this code path is when `if mtu == 0` which means cilium does not have mtu option configured by user, so if you configure cilium mtu option, it should workaround it.

in daemon/cmd/daemon.go, question is why `externalIP` gets loopback interface IP address.

```
        var mtuConfig mtu.Configuration
        externalIP := node.GetIPv4()
        if externalIP == nil {
                externalIP = node.GetIPv6()
        }
        // ExternalIP could be nil but we are covering that case inside NewConfiguration
        mtuConfig = mtu.NewConfiguration(
                authKeySize,
                option.Config.EnableIPSec,
                option.Config.TunnelExists(),
                option.Config.EnableWireguard,
                configuredMTU,
                externalIP,
        )
```

**Comment by vincentmli** [comment] 2022-07-21 15:32
I attempted to quick repro but no success

ip a s dev lo
```

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.3.72.111/24 scope global lo<=============
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```
 kubectl rollout restart ds/cilium -n kube-system

```
level=info msg="  Local node-name: cilium-demo-1" subsys=daemon
level=info msg="  Node-IPv6: <nil>" subsys=daemon
level=info msg="  External-Node IPv4: 10.169.72.9" subsys=daemon
level=info msg="  Internal-Node IPv4: 10.0.0.113" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.0.0.0/24" subsys=daemon
level=info msg="  Loopback IPv4: 169.254.42.1" subsys=daemon
level=info msg="  Local IPv4 addresses:" subsys=daemon
level=info msg="  - 10.3.72.111" subsys=daemon. <====DETECTED HERE, but not used for ExternalIP
level=info msg="  - 10.3.72.9" subsys=daemon
level=info msg="  - 10.169.72.9" subsys=daemon
level=info msg="  - 10.0.0.113" subsys=daemon
level=info msg="Adding local node to cluster" node="{cilium-demo-1 default [{ExternalIP 10.3.72.9} {InternalIP 10.169.72.9} {CiliumInternalIP 10.0.0.113}] 10.0.0.0/24 [] <nil> [] 10.0.0.28 <nil> <nil> <nil> 0 local 0 map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:k3s beta.kubernetes.io/os:linux egress.k3s.io/cluster:true kubernetes.io/arch:amd64 kubernetes.io/hostname:cilium-demo-1 kubernetes.io/os:linux node-role.kubernetes.io/control-plane:true node-role.kubernetes.io/master:true node.kubernetes.io/instance-type:k3s] 1 }" subsys=nodediscovery
level=info msg="Creating or updating CiliumNode resource" node=cilium-demo-1 subsys=nodediscovery
```

@CiraciNicolo  could you please share your cilium agent log like above when the issue happens?

**Comment by vincentmli** [comment] 2022-07-22 03:01
> based on pkg/mtu/mtu.go, you could also workaround the issue by specifying `mtu` in option through helm
> 
> ```
> 100 // NewConfiguration returns a new MTU configuration. The MTU can be manually
> 101 // specified, otherwise it will be automatically detected. if encapEnabled is
> 102 // true, the MTU is adjusted to account for encapsulation overhead for all
> 103 // routes involved in node to node communication.
> 104 func NewConfiguration(authKeySize int, encryptEnabled bool, encapEnabled bool, wireguardEnabled bool, mtu int, mtuDetectI    P net.IP) Configuration {
> 105         encryptOverhead := 0
> 106 
> 107         if mtu == 0 {
> 108                 var err error
> 109 
> 110                 if mtuDetectIP != nil {
> 111                         mtu, err = getMTUFromIf(mtuDetectIP)
> 112                 } else {
> 113                         mtu, err = autoDetect()
> 114                 }
> 115                 if err != nil {
> 116                         log.WithError(err).Warning("Unable to automatically detect MTU")
> 117                         mtu = EthernetMTU
> 118                 }
> 119         }
> ```

based on above code, could you run `ip route get 1.1.1.1` ? because another possibility is `mtu, err = autoDetect()` where `mtuDetectIP` is `nil` and `autoDetect()` get `mtu` based host default route to ip `1.1.1.1`

**Comment by vincentmli** [comment] 2022-07-22 03:37
continue to read the code and I strongly suspect `mtuDetectIP is nil`, probably your loopback interface is the interface has the default route to `1.1.1.1`

 code  path likely to prove that

```
daemon/cmd/daemon.go 

 365 // NewDaemon creates and returns a new Daemon with the parameters set in c.
 366 func NewDaemon(ctx context.Context, cancel context.CancelFunc, epMgr *endpointmanager.EndpointManager, dp datapat     h.Datapath) (*Daemon, *endpointRestoreState, error) {


 468         var mtuConfig mtu.Configuration
 469         externalIP := node.GetIPv4() <==HERE addrs.ipv4Address populated by SetIPv4() 
 470         if externalIP == nil {
 471                 externalIP = node.GetIPv6()
 472         }
 473         // ExternalIP could be nil but we are covering that case inside NewConfiguration
 474         mtuConfig = mtu.NewConfiguration(
 475                 authKeySize,
 476                 option.Config.EnableIPSec,
 477                 option.Config.TunnelExists(),
 478                 option.Config.EnableWireguard,
 479                 configuredMTU,
 480                 externalIP,
 481         )




 871                 if err := k8s.WaitForNodeInformation(d.ctx, d.k8sWatcher); err != nil {
 872                         log.WithError(err).Error("unable to connect to get node spec from apiserver")
 873                         return nil, nil, fmt.Errorf("unable to connect to get node spec from apiserver: %w", err)
 874                 }
 875 



1250         return &d, restoredEndpoints, nil
1251 }


pkg/node/address.go

282 // SetIPv4 sets the IPv4 node address. It must be reachable on the network.
283 // It is set based on the following priority:
284 // - NodeInternalIP
285 // - NodeExternalIP
286 // - other IP address type
287 func SetIPv4(ip net.IP) {
288         addrsMu.Lock()   
289         addrs.ipv4Address = clone(ip)
290         addrsMu.Unlock()
291 }        
292 
293 // GetIPv4 returns one of the IPv4 node address available with the following
294 // priority:
295 // - NodeInternalIP
296 // - NodeExternalIP
297 // - other IP address type.
298 // It must be reachable on the network.
299 func GetIPv4() net.IP {
300         addrsMu.RLock()
301         defer addrsMu.RUnlock()
302         return clone(addrs.ipv4Address)
303 }        


 **SetIPv4()  get called if line 1453 config is set below, not  apply to your config.**

daemon/cmd/daemon_main.go

1453         if option.Config.IPv4NodeAddr != "auto" {
1454                 if ip := net.ParseIP(option.Config.IPv4NodeAddr); ip == nil {
1455                         log.WithField(logfields.IPAddr, option.Config.IPv4NodeAddr).Fatal("Invalid IPv4 node addr     ess")      
1456                 } else {
1457                         node.SetIPv4(ip)
1458                 }
1459         }

**SetIPv4() get called in line 263 below but WaitForNodeInformation() is called after MTU setting in
Above NewDaemon(), so address.ipv4Address is likely empty and GetIPv4() get nil**

pkg/k8s/init.go:


220 // WaitForNodeInformation retrieves the node information via the CiliumNode or
221 // Kubernetes Node resource. This function will block until the information is
222 // received. nodeGetter is a function used to retrieved the node from either
223 // the kube-apiserver or a local cache, depending on the caller.
224 func WaitForNodeInformation(ctx context.Context, nodeGetter nodeGetter) error {

238         if n := waitForNodeInformation(ctx, nodeGetter, nodeName); n != nil {
239                 nodeIP4 := n.GetNodeIP(false)
240                 nodeIP6 := n.GetNodeIP(true)

256                 // Note: Node IPs are derived regardless of
257                 // option.Config.EnableIPv4 and
258                 // option.Config.EnableIPv6. This is done to enable
259                 // underlay addressing to be different from overlay
260                 // addressing, e.g. an IPv6 only PodCIDR running over
261                 // IPv4 encapsulation.
262                 if nodeIP4 != nil {
263                         node.SetIPv4(nodeIP4). <=======
264                 }
265 
266                 if nodeIP6 != nil {
267                         node.SetIPv6(nodeIP6)
268                 }

}
```

**Comment by vincentmli** [comment] 2022-07-22 04:27
I attempted to add default route through loopback interface `lo` with IP assigned, still no success to repro

**Comment by CiraciNicolo** [comment] 2022-07-22 18:23
Hello, sorry for the silence. We don't have 1.1.1.1 as default route for loopback, but the loopback iface has an assigned ip because we make use of a redundant VPN (2 servers are connected) and therefore we assign the "vip" to loopback interface. I'm also unable to repro right now, we are doing stuff with this k3s instances and I cannot break them right now 😁

Regarding the mtu parameter, I didn't find any references about it in both the docs and default values.yaml; is the documentation updated? I'll testing it since this workaround is not complete, because in this way we are unable to bind NodePorts to the loopback iface - the VPN vip is used for mgmt and we need to reach some service.

**Comment by vincentmli** [comment] 2022-07-22 21:02
the cilium agent has an argument here  https://docs.cilium.io/en/stable/cmdref/cilium-agent
`--mtu int                                                 Overwrite auto-detected MTU of underlying network`
it seems not supported in helm install though

**Comment by CiraciNicolo** [comment] 2022-07-25 14:04
Awesome! Now we are able to bind on lo for MGMT stuff! I think we can close this issues since the problem is very specific to our infrastructure.

**Closed as completed** 2022-07-25 14:42 UTC
Labels: kind/bug, needs/triage
