### ISSUE TITLE
CI: K8sDatapathConfig Iptables [It] Skip conntrack for pod traffic 

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#32920] opened 2024-06-05 20:29 UTC
Hit on - https://github.com/cilium/cilium/actions/runs/9387517265/job/25855278974/.

The test failed with one of the cilium agent pods in crashloopbackoff state. 

`2024-06-05T18:32:12.289648586Z time="2024-06-05T18:32:12Z" level=fatal msg="Timeout while waiting for initial conntrack scan" subsys=ct-nat-map-gc`

[cilium-sysdumps (1).zip](https://github.com/user-attachments/files/15596215/cilium-sysdumps.1.zip)

**Comment by brlbil** [comment] 2024-06-06 07:13
Duplicate of #32913

**Closed as completed by brlbil** 2024-06-06 07:13 UTC
Labels: area/CI, ci/flake
