### ISSUE TITLE
Cilium performance issue - cilium-envoy-starter uses too much CPU

### ISSUE THREAD

**Issue by volatilemolotov** [cilium/cilium#30617] opened 2024-02-04 15:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Process 
```cilium-envoy-starter -l info -c /var/run/cilium/envoy/bootstrap.pb --base-id 0 --log-format %t|%l|%n|%v```
uses too much cpu on all nodes (40 - 68%)

### Cilium Version

1.15.0

### Kernel Version

6.5.11

### Kubernetes Version

v1.27.4

### Sysdump

file too big for github 

### Relevant log output

```shell
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
level=info msg="[lds: add/update listener 'kube-system/cilium-ingress/listener'" subsys=envoy-upstream threadID=55
```

### Anything else?

On 1.14.6 that process does not run and the repeating log lines for add/update listener do not appear

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment] 2024-02-04 23:44
Thanks for your issue. 

Do you observe the same with Cilium 1.14.x ? Basically, I am trying to scope down if the issue if related to cilium-envoy-starter script or is it due to envoy process?

**Comment by volatilemolotov** [comment] 2024-02-05 10:25
No, when reverting to 1.14.6 the issue is not there. With 1.14 i see a cilium-envoy script with the same arguments but with normal cpu usage.

Only on 1.15.0 with cililum-envoy-starter i get the issue

**Comment by sayboras** [comment] 2024-02-05 10:34
Thanks for your reply. 

In 1.15, we are using controller-runtime with more aggressive and frequent reconciliation loops for Ingress features, this might lead to more logs updating listener, and probably some short CPU spike. 

Just curious if CPU usage is only happening for a short duration, and reduce later or is it consistently high? Thanks.

**Comment by sayboras** [comment] 2024-02-05 10:50
Also, can you share logs for cilium agent and operator for further analysis?

**Comment by volatilemolotov** [comment] 2024-02-05 14:32
It seems like the load is constantly high. Let me update again to 1.15 , let it rip some time and come back with more definitive answer and logs

**Comment by volatilemolotov** [comment] 2024-02-05 15:14
40 minutes later its still high usage. 

[agent.log](https://github.com/cilium/cilium/files/14167522/agent.log)
[operator.log](https://github.com/cilium/cilium/files/14167523/operator.log)


Fun fact: power usage across the cluster is 80W higher with 1.15 :laughing:

**Comment by sayboras** [comment] 2024-02-06 09:36
Thanks for your log. 

It seems like there are some triggers, which make the reconciliation of seudo-ingress non-stop. Do you have some other components fighting to own this Ingress resource ? 

```
level=info msg="Reconciling Ingress" controller=ingress resource=kube-system/pseudo-ingress subsys=ingress
```

**Comment by volatilemolotov** [comment] 2024-02-06 10:49
I should not have. Looking at the ingressClass i see cilium only registered. 
What is a pseudo-ingress?

**Comment by sayboras** [comment] 2024-02-25 11:41
:wave: 

> What is a pseudo-ingress?

I don't think pseudo_ingress is created by Cilium at all, is it something you provisioned before ?

**Comment by volatilemolotov** [comment] 2024-02-26 10:50
Not that im aware of. 
I use flux for git ops and there is no reference of that ingress. I do happen to install something manually from time to time but nothing seems to have pseudo-ingress. Its not currently in API (nor in ETCD) so im not sure where it comes from

**Comment by mhofstetter** [comment] 2024-02-29 08:41
Hey @volatilemolotov :wave: 

As the name kind of indicates, the Ingress `pseudo-ingress` doesn't actually exist in the API server and is used to optimize triggering a reconciliation in case there's a change in the shared `CiliumEnvoyConfig` in the cilium namespace.

https://github.com/cilium/cilium/blob/main/operator/pkg/ingress/ingress.go#L104-L114

```
// Watching shared CiliumEnvoyConfig and reconcile a non-existing pseudo Cilium Ingress.
// Its not necessary to reconcile all shared Cilium Ingresses as they all will update the
// shared CEC with the complete model that includes all shared Cilium Ingresses.
// This will cover the following cases
// - Manual deletion of shared CEC
//   -> Pseudo Cilium Ingress reconciliation will re-create it
// - Manual update of shared CEC
//   -> Pseudo Cilium Ingress reconciliation will enforce an update of the shared CEC
// - Deletion of shared Cilium Ingresses during downtime of the Cilium Operator
//   -> pseudo Cilium Ingress reconciliation will enforce an update of the shared CEC after the restart
Watches(&ciliumv2.CiliumEnvoyConfig{}, r.enqueuePseudoIngress(), r.forSharedCiliumEnvoyConfig()).
```

It looks like something is constantly deleting/updating this shared CiliumEnvoyConfig which triggers a reconciliation with the `pseudo-ingress`. (The reconciliation itself should not trigger an endless reconciliation by itself).

I assume you don't have this shared CIliumEnvoyConfig in your Flux GitOps?

Maybe it's worth to get a Cilium Operator log with debug level enabled. This should output the diff in the CiliumEnvoyConfig if the operator itself would try to constantly modify it.

**Comment by volatilemolotov** [comment] 2024-03-05 16:08
In flux i only got l2annoucementpolicy, gateway, loadbalancerippool. 

Regarding debug i cannot send you the output as a lot of domains are there but i see a LOT of 
```level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]:  {\n  name:  \"node-red:node-red-node-red:1880\"\n  type:  EDS\n  eds_cluster_config:  {\n    service_name:  \"node-red/node-red-node-red:1880\"\n  }\n  connect_timeout:  {\n    seconds:  5\n  }\n  typed_extension_protocol_options:  {\n    key:  \"envoy.extensions.upstreams.http.v3.HttpProtocolOptions\"\n    value:  {\n      [type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions]:  {\n        common_http_protocol_options:  {\n          idle_timeout:  {\n            seconds:  60\n          }\n        }\n        use_downstream_protocol_config:  {\n          http2_protocol_options:  {}\n        }\n      }\n    }\n  }\n  outlier_detection:  {\n    split_external_local_origin_errors:  true\n  }\n}\n" subsys=k8s-apis-cilium.io-v2
```

The same is for all other services that are referenced by an Ingress source

**Comment by jackmaninov** [comment] 2024-03-17 23:54
I am seeing the same or a similar issue causing an infinite CiliumEnvoyConfig ingress reconciliation loop on 1.15.2 with 3 nodes. Two datapoints I can add:

1) This issue is triggered by either of 2 of the 11 ingresses I have running on my current test environment. I migrated the configuration for this environment from another one, which was not displaying this issue. If I delete these 2 ingresses, cilium-operator stops reconciling ingresses and envoy calms down.

2) The issue is somehow related to TLS. If I remove the tls section from either of the 2 affected ingresses, the reconcile loop terminates and CPU usage goes down. All my TLS secrets are generated by lets-encrypt, so there should be nothing special about these 2 ingresses. The secrets themselves seem OK, as if I re-request them, the issue persists.

**Comment by jackmaninov** [comment] 2024-03-18 07:10
Here's some (clipped) debug output from cilium-operator while in the reconcile loop. This block repeats every 100ms or so, and the timing seems to coincide with the Generation count on the CiliumEnvoyConfig, which seems to increase by about 10 per second:

```2024-03-18T06:59:42.603390757Z level=info msg="Reconciling Ingress" controller=ingress resource=kube-system/pseudo-ingress subsys=ingress
2024-03-18T06:59:42.603460713Z level=debug msg="Trying to cleanup potentially existing resources of deleted Ingress" controller=ingress resource=kube-system/pseudo-ingress subsys=ingress
2024-03-18T06:59:42.694439709Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.listener.v3.Listener]: {\n  name: \"listener\"\n  filter_chains: {\n    filter_chain_match: {\n      transport_protocol: \"raw_buffer\"\n    }\n    filters: {\n
2024-03-18T06:59:42.694980192Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.route.v3.RouteConfiguration]: {\n  name: \"listener-insecure\"\n  virtual_hosts: {\n    name: \"crm.asgard.testhost.com\"\n    domains: \"crm.asgard.testhost.com\"\n    d
2024-03-18T06:59:42.695353954Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.route.v3.RouteConfiguration]: {\n  name: \"listener-secure\"\n  virtual_hosts: {\n    name: \"crm.asgard.testhost.com\"\n    domains: \"crm.asgard.testhost.com\"\n    dom 
2024-03-18T06:59:42.695799795Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.listener.v3.Listener]: {\n  name: \"listener\"\n  filter_chains: {\n    filter_chain_match: {\n      transport_protocol: \"raw_buffer\"\n    }\n    filters: {\n
2024-03-18T06:59:42.695981439Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-argocd:argocd-server:443\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-argocd/argocd-server:443\"\n  }\
2024-03-18T06:59:42.696286627Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-crm:server:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-crm/server:80\"\n  }\n  connect_timeout: {\ 
2024-03-18T06:59:42.696638231Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.route.v3.RouteConfiguration]: {\n  name: \"listener-insecure\"\n  virtual_hosts: {\n    name: \"crm.asgard.testhost.com\"\n    domains: \"crm.asgard.testhost.com\"\n    d 
2024-03-18T06:59:42.696654365Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-frontend:coming-soon:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-frontend/coming-soon:80\"\n  }\n  
2024-03-18T06:59:42.696865905Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-kas:8150\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-kas:8150\"\n  }\n  c 
2024-03-18T06:59:42.697167183Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-kas:8154\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-kas:8154\"\n  }\n  c 
2024-03-18T06:59:42.697202583Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-minio-svc:9000\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-minio-svc:9000 
2024-03-18T06:59:42.697480536Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.route.v3.RouteConfiguration]: {\n  name: \"listener-secure\"\n  virtual_hosts: {\n    name: \"crm.asgard.testhost.com\"\n    domains: \"crm.asgard.testhost.com\"\n    dom 
2024-03-18T06:59:42.697664875Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-argocd:argocd-server:443\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-argocd/argocd-server:443\"\n  }\ 
2024-03-18T06:59:42.697911087Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-crm:server:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-crm/server:80\"\n  }\n  connect_timeout: {\ 
2024-03-18T06:59:42.697959840Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-frontend:coming-soon:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-frontend/coming-soon:80\"\n  }\n  
2024-03-18T06:59:42.698034695Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-kas:8150\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-kas:8150\"\n  }\n  c 
2024-03-18T06:59:42.698202956Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-kas:8154\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-kas:8154\"\n  }\n  c 
2024-03-18T06:59:42.698368401Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-minio-svc:9000\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-minio-svc:9000 
2024-03-18T06:59:42.698437126Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-registry:5000\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-registry:5000\" 
2024-03-18T06:59:42.698548605Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-webservice-default:8181\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-webse 
2024-03-18T06:59:42.698669480Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-longhorn:longhorn-frontend:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-longhorn/longhorn-frontend: 
2024-03-18T06:59:42.698844756Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-openunison:kube-oidc-proxy-openunison:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-openunison/kube- 
2024-03-18T06:59:42.698853109Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-openunison:openunison-openunison:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-openunison/openunison 
2024-03-18T06:59:42.698966471Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-sealed-secrets:sealed-secrets-controller:http\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-sealed-secr
2024-03-18T06:59:42.699105080Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"kube-system:hubble-ui:http\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"kube-system/hubble-ui:http\"\n  }\n  connect
2024-03-18T06:59:42.699460811Z level=debug msg="CiliumEnvoyConfig kube-system/cilium-ingress has been updated" subsys=ingress2024-03-18T06:59:42.699470535Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-registry:5000\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-registry:5000\" 
2024-03-18T06:59:42.699588463Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-gitlab:gitlab-webservice-default:8181\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-gitlab/gitlab-webse 
2024-03-18T06:59:42.699680452Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-longhorn:longhorn-frontend:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-longhorn/longhorn-frontend: 
2024-03-18T06:59:42.699791118Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-openunison:kube-oidc-proxy-openunison:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-openunison/kube- 
2024-03-18T06:59:42.699886251Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-openunison:openunison-openunison:80\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-openunison/openunison 
2024-03-18T06:59:42.699959534Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-sealed-secrets:sealed-secrets-controller:http\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-sealed-secr 
2024-03-18T06:59:42.700100737Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"kube-system:hubble-ui:http\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"kube-system/hubble-ui:http\"\n  }\n  connect 
2024-03-18T06:59:42.700239991Z level=info msg="Reconciling Ingress" controller=ingress resource=kube-system/pseudo-ingress subsys=ingress                                                                                                                                              
2024-03-18T06:59:42.700269416Z level=debug msg="Trying to cleanup potentially existing resources of deleted Ingress" controller=ingress resource=kube-system/pseudo-ingress subsys=ingress
```

Individual `CEC unmarshaled XDS Resource` lines look like:

`2024-03-18T07:07:37.601187680Z level=debug msg="CEC unmarshaled XDS Resource: [type.googleapis.com/envoy.config.cluster.v3.Cluster]: {\n  name: \"testhost-sealed-secrets:sealed-secrets-controller:http\"\n  type: EDS\n  eds_cluster_config: {\n    service_name: \"testhost-sealed-secrets/sealed-secrets-controller:http\"\n  }\n  connect_timeout: {\n    seconds: 5\n  }\n  typed_extension_protocol_options: {\n    key: \"envoy.extensions.upstreams.http.v3.HttpProtocolOptions\"\n    value: {\n      [type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions]: {\n        common_http_protocol_options: {\n          idle_timeout: {\n            seconds: 60\n          }\n        }\n        use_downstream_protocol_config: {\n          http2_protocol_options: {}\n        }\n      }\n    }\n  }\n  outlier_detection: {\n    split_external_local_origin_errors: true\n  }\n}\n" subsys=k8s-apis-cilium.io-v2`

**Comment by volatilemolotov** [comment] 2024-03-18 09:56
@jackmaninov What is specific to those two ingress resources ? Perhaps i can somehow figure out what ingresses cause it on my side

**Comment by jackmaninov** [comment] 2024-03-18 23:21
@volatilemolotov There's nothing obvious that stands out about the 2 that give me trouble. One is from hubble generated by helm, the other is from cert-manager.

**Comment by jackmaninov** [comment] 2024-03-22 19:28
After more testing, it seems to only be the number of Ingresses that trigger the reconcile loop behaviour for me. So for example, if I delete my way down to 2 Ingresses in total, then add back the 3rd, I may get 2 log entries in cilium-operator about reconciling the pseudo-ingress, the 4th gives 9 entries, at the 5th there are more than 30 entries, etc. 

The "difficulty" in concluding the resolution does not seem to be consistent (e.g. in this test run, adding the 6th Ingress only gave about 5 log entries), but generally increases with the number of Ingresses, until I get to around 9, at which point the reconciliation never seems to complete (maybe it would after several minutes, but this is difficult to test).

I also sometimes come across log entries like:

`cilium-operator-574659d5f6-5l7v5 level=error msg="Reconciler error" Ingress="{gitlab-webservice-default testdomain-gitlab}" controller=ingress controllerGroup=networking.k8s.io controllerKind=Ingress error="failed to create or update CiliumEnvoyConfig: Operation cannot be fulfilled on ciliumenvoyconfigs.cilium.io \"cilium-ingress\": the object has been modified; please apply your changes to the latest version and try again" name=gitlab-webservice-default namespace=testdomain-gitlab reconcileID="\"f323bfd2-a0bd-4335-9cfd-05c58e0476af\"" subsys=controller-runtime`

One thing I should note is that all my Ingresses are for sub-domains under the same domain (e.g. www.testdomain.com, gitlab.testdomain.com, kas.testdomain.com, etc), perhaps this makes a difference. 

Also, while I am stuck in a reconciliation loop, if I examine my CiliumEnvoyConfig, over time the order of the virtualHosts under the `type.googleapis.com/envoy.config.route.v3.RouteConfiguration`  `listener-insecure` and `listener-secure` objects seems to be randomized on each update. Perhaps this ordering being non-deterministic is the source of the issue in reconciling the object?

**Comment by jackmaninov** [comment] 2024-03-22 19:30
I have also validated that argo-cd is not causing the issue; I can reproduce it event after uninstalling it.

**Comment by jackmaninov** [comment] 2024-03-22 20:24
It also seems that the reconciliation rate can be controlled with the k8sClientRateLimit value in the helm chart. Increasing and decreasing it controls the rate of reconciliation log entries.

I have lowered qps to 1 for the time being to control the cpu usage. You may wish to try this @volatilemolotov

**Comment by mhofstetter** [comment] 2024-03-23 07:26
Thanks for the additional information.

> Also, while I am stuck in a reconciliation loop, if I examine my CiliumEnvoyConfig, over time the order of the virtualHosts under the type.googleapis.com/envoy.config.route.v3.RouteConfiguration listener-insecure and listener-secure objects seems to be randomized on each update. Perhaps this ordering being non-deterministic is the source of the issue in reconciling the object?

I observed the same (in another case) and opened the following PRs some days ago. 

- https://github.com/cilium/cilium/pull/31493
- https://github.com/cilium/cilium/pull/31494

This can definitely be a reason for your experienced behaviour. Even though i wasn't able to reproduce a never ending reconciliation loop on my side.

**Comment by volatilemolotov** [comment] 2024-03-23 16:59
> It also seems that the reconciliation rate can be controlled with the k8sClientRateLimit value in the helm chart. Increasing and decreasing it controls the rate of reconciliation log entries.
> 
> I have lowered qps to 1 for the time being to control the cpu usage. You may wish to try this @volatilemolotov

Lowering k8sClientRateLimit does help. Not sure why i did raise it , think it was something when configuring cilium for l2annoucements

**Comment by jackmaninov** [comment] 2024-03-24 01:20
Ok, I have a simple test setup to demonstrate the reconciliation loop. Using Rancher Desktop (I believe it's k3s under the hood) with default settings and cilium 1.28.7, I install helm with:

`helm install cilium cilium/cilium --values values.yaml --namespace kube-system`

and values: 
[values.txt](https://github.com/cilium/cilium/files/14734034/values.txt)

Once a cilium operator comes up I apply these Ingresses pulled from my dev environment:
[ingress-test.txt](https://github.com/cilium/cilium/files/14734040/ingress-test.txt)

At this point the reconciliation loop can be observed in the operator log. Deleting two or three of the ingresses will cause it to stop. Note that the cilium-agent and other pods depending on CNI won't come up, and there is no cert-manager or TLS secrets, so this isn't a very useful environment.

**Comment by mhofstetter** [comment] 2024-03-25 07:55
> > I observed the same (in another case) and opened the following PRs some days ago.
> > 
> > * [ingress/gateway-api: sort virtual hosts in CEC #31493](https://github.com/cilium/cilium/pull/31493)
> > * [ingress: sort all shared ingresses during model generation #31494](https://github.com/cilium/cilium/pull/31494)
> 
> Thanks for the info! I've pulled your PRs, but they don't resolve the issue for me. I do see the listener objects being sorted now, but the filterChainMatches under filterChain are still showing up in a different order on each regeneration of the CEC.
> 
> > This can definitely be a reason for your experienced behaviour. Even though i wasn't able to reproduce a never ending reconciliation loop on my side.
> 
> I'll see if I can generate a Talos config/image that reproduces the issue on a single node, but no guarantee that I can get something simple to work.

Thanks for the confirmation. Indeed, the filterchains are also effected (and currently randomly ordered).

I opened: https://github.com/cilium/cilium/pull/31572

**Comment by jackmaninov** [comment] 2024-03-25 12:21
> Thanks for the confirmation. Indeed, the filterchains are also effected (and currently randomly ordered).
> 
> I opened: #31572

This PR seems to have done the trick (along with the previous 2). Thanks!

**Comment by mhofstetter** [comment] 2024-03-27 21:47
All 3 PR's have been merged to `main`. Unfortunately, their backports to `v1.15` missed the latest release `v1.15.3` - but they will land in the next patch release `v1.15.4`.

Thanks a lot for the help and patience @jackmaninov & @volatilemolotov .

I close this issue - feel free to re-open or create a new issue if you face similar problems when testing with the fixed releases. (Let's hope we catched all ordering issues :crossed_fingers: )

**Closed as completed by mhofstetter** 2024-03-27 21:47 UTC
Labels: kind/bug, area/proxy, kind/community-report, area/agent, area/servicemesh
