### ISSUE TITLE
CI: client-ingress-from-other-client-icmp-deny (ConformanceAKS)

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#22572] opened 2022-12-06 13:23 UTC
## CI failure

I ran into [this](https://github.com/cilium/cilium/actions/runs/3628789904/jobs/6120542047) failure on PR #22551 which is so minimal 
 and unrelated to network policy that this must be flake.

```
[=] Test [client-ingress-from-other-client-icmp-deny]
..
  ℹ️  📜 Applying CiliumNetworkPolicy 'allow-all-egress' to namespace 'cilium-test'..
  ℹ️  📜 Applying CiliumNetworkPolicy 'allow-all-ingress' to namespace 'cilium-test'..
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-ingress-from-other-client-icmp-deny' to namespace 'cilium-test'..
  [-] Scenario [client-ingress-from-other-client-icmp-deny/client-to-client]
  [.] Action [client-ingress-from-other-client-icmp-deny/client-to-client/ping-0: cilium-test/client-7[84](https://github.com/cilium/cilium/actions/runs/3628789904/jobs/6120542047#step:22:85)c67ffc4-4lr7d (10.0.1.88) -> cilium-test/client2-67754cb6fb-x7smh (10.0.1.25:0)]
  [.] Action [client-ingress-from-other-client-icmp-deny/client-to-client/ping-1: cilium-test/client2-67754cb6fb-x7smh (10.0.1.25) -> cilium-test/client-784c67ffc4-4lr7d (10.0.1.88:0)]
  ❌ command "ping -w 3 -c 1 10.0.1.[88](https://github.com/cilium/cilium/actions/runs/3628789904/jobs/6120542047#step:22:89)" succeeded while it should have failed: PING 10.0.1.88 (10.0.1.88) 56(84) bytes of data.

  ℹ️  ping output:
  PING 10.0.1.88 (10.0.1.88) 56(84) bytes of data.
  
  📄 No flows recorded during action ping-1
  📄 No flows recorded during action ping-1

[...]

📋 Test Report
❌ 1/26 tests failed (1/166 actions), 5 tests skipped, 8 scenarios skipped:
Test [client-ingress-from-other-client-icmp-deny]:
  ❌ client-ingress-from-other-client-icmp-deny/client-to-client/ping-1: cilium-test/client2-67754cb6fb-x7smh (10.0.1.25) -> cilium-test/client-784c67ffc4-4lr7d (10.0.1.88:0)
```

[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/10166803/cilium-sysdumps.zip)

**Comment by pchaigno** [comment] 2022-12-12 22:38
Duplicate of https://github.com/cilium/cilium/issues/22162#issuecomment-1341696494.

**Closed as completed by pchaigno** 2022-12-12 22:38 UTC
Labels: area/CI, ci/flake
