### ISSUE TITLE
LB service (pod) backend deletion breaks existing connections

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#14844] opened 2021-02-03 07:21 UTC
Consolidate discussion/proposals for 

[ ] https://github.com/cilium/cilium/issues/12859 (forceful termination of existing connections)
[ ] https://github.com/cilium/cilium/issues/10217 (graceful handling of existing connections)

### Desired goal 
Upon removal of a service backend, drain all the existing connections to the backend, and ensure that the backend is not selected for new connections. 

### Current behavior
What happens when a service backend is deleted, and we immediately remove it from the `lb` maps?

- Socket-based load balancing 

TCP (Connected UDP) : 

(Broken) 
Backend is selected at the time of the socket `Connect` call via a lookup in the `lb` map. As a result, existing connections are likely to trigger re-transmissions, and eventually give up.  The onus is on applications to recover from the failure (e.g., keep-alives).

(Ok) 
The deleted backend won't be selected for new connections.
If the backend pod hangs around for the duration of `terminationGracePeriod`, then connections could terminate gracefully.

UDP: 

(Broken) 
Backend selection happens on per packet in the sendmsg call (similar to per packet load balancing). Daniel mentioned that socket cookie could help pick the same backend, but if the backend is deleted, then a new backend will be selected.
This logic also breaks when the number of service backends change (either increase/decrease). 

(Ok) 
The deleted backend won't be selected for new connections.

-  Per packet load balancing  

TCP/ Connected UDP/ UDP:

(Broken) 
Backend is selected on a per packet basis. For the first packet in a flow, a new CT entry is created, which also stores the selected backend id. The backend selection involves `lb` services map lookup. For subsequent packets, a lookup is issued to the `ct` map to retrieve the selected backend id. This is followed by a lookup to the `lb` backend map to get the backend metadata. When a backend is deleted, we end up selecting a wrong backend, and the existing connections are likely to receive a `RST`. 

(Ok) 
The deleted backend won't be selected for new connections.
RSTs could enable fast recovery for active connections. 

### Potential solutions :

- Graceful termination

  * Modified backend ref counting (selected)
Backend selection is done using `lb service` map lookups, and backend info retrieval via `lb backend` maps. Could we remove a backend entry from the former, but not the latter until a configured graceful termination timeout? Backend ref counting logic would need to be updated. 
	
  * Weights based backend selection
Keep entry in both the maps. Use weights in the backend selection logic. When a backend is being deleted, its weight will be set to `0` by cilium agent, and such backends won't be selected by the datapath. How do we handle the case where this backend is selected for new connections? Re-do the process?

- Abrupt termination 
A backend can disappear without honoring the graceful termination timeout configured by Kubernetes. In such scenarios, there is no way to gracefully terminate existing connections to the backend. We can, however, facilitate faster recovery from failures by sending `RST`s. For active connections, create a `SOCKMAP`, and use `bpf_sk_assign` to redirect packets to a terminator socket?
How do we handle inactive connections???
What about socket-based load balancing???

### Optimizations:

- Keep a backend entry in the lb backend map only when the backend has existing connections. Conntrack could be one place to get this information from.

 
### Open questions :
- ~Does Kubernetes expose `terminationGracePeriod` for an Endpoint?~
No, the configuration is only available in the `pod Spec`. Use the terminating state introduced in Kubernetes v1.20 by the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints).
- ~Clean up of CT entries~
It's not needed for now as LRU will clean up such entries. 
- How does the Linux stack handle an incoming packet destined to a socket that doesn't exist?
- Test environment to reproduce the issue

Discussed during the sig-datapath meeting on 02/03 - https://docs.google.com/document/d/1IZZ-FTM_U3zN06-M_mDOgep_DcDM0Oe3YOFVM1BTIt8/edit#heading=h.b4c02eltf70i

**Comment by brb** [comment] 2021-02-11 06:14
@aditighag Would you mind adding a comment to this issue saying which approach you are going to take?

**Comment by aditighag** [comment] 2021-02-11 16:14
Discussed proposal (1) with @borkmann and @brb, and we have a consensus now. 

>Modified backend ref counting
Backend selection is done using lb service map lookups, and backend info retrieval via lb backend maps. Could we remove a backend entry from the former, but not the latter until a configured graceful termination timeout? Backend ref counting logic would need to be updated.

**Comment by aanm** [comment] 2021-02-19 12:14
The requirement is as simple as:
a) do not serve new connections for backends with `terminating != nil && *terminating == true` where this value is available in EndpointSlice k8s structure.
Regarding the implementation, it should be as:
a) if we receive an endpoint event with `terminating != nil && *terminating == true`, keep it in the list of backends which should not be selected for new connections (i.e. weight=0)
b) if we receive a delete endpoint event, simply remove it from the list of backends.

**Comment by aditighag** [comment] 2021-02-19 16:05
> The requirement is as simple as:
> a) do not serve new connections for backends with `terminating != nil && *terminating == true` where this value is available in EndpointSlice k8s structure.
> Regarding the implementation, it should be as:
> a) if we receive an endpoint event with `terminating != nil && *terminating == true`, keep it in the list of backends which should not be selected for new connections (i.e. weight=0)
> b) if we receive a delete endpoint event, simply remove it from the list of backends.

To add more context, this is marked as Alpha in v1.20 that we recently upgraded Cilium to, and part of a new [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints). It looks like this condition already accounts for the `GracePeriod` for pods. Regardless, I found that the termination grace period is indeed included in the `ObjectMeta` structure as part of the Endpoint structure in case we need to reference that field.

**Comment by aanm** [comment] 2021-02-19 16:17
> > The requirement is as simple as:
> > a) do not serve new connections for backends with `terminating != nil && *terminating == true` where this value is available in EndpointSlice k8s structure.
> > Regarding the implementation, it should be as:
> > a) if we receive an endpoint event with `terminating != nil && *terminating == true`, keep it in the list of backends which should not be selected for new connections (i.e. weight=0)
> > b) if we receive a delete endpoint event, simply remove it from the list of backends.
> 
> To add more context, this is marked as Alpha in v1.20 that we recently upgraded Cilium to, and part of a new [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints). It looks like this condition already accounts for the `GracePeriod` for pods. Regardless, I found that the termination grace period is indeed included in the `ObjectMeta` structure as part of the Endpoint structure in case we need to reference that field.

> To add more context, this is marked as Alpha in v1.20 that we recently upgraded Cilium to

Similarly to our feature which would be alpha/beta and we would have to support 2 mechanisms, the k8s way and our way. Kubernetes 1.21 will be released in ~2 months, luckily by then the release will be stable.

The problem is that we can't simply watch for all Pods from all nodes as it does not scale so I would suggest to use a feature that is already available in Kubernetes upstream and adjust our code to it.

**Comment by aditighag** [comment] 2021-02-19 16:20
> > > The requirement is as simple as:
> > > a) do not serve new connections for backends with `terminating != nil && *terminating == true` where this value is available in EndpointSlice k8s structure.
> > > Regarding the implementation, it should be as:
> > > a) if we receive an endpoint event with `terminating != nil && *terminating == true`, keep it in the list of backends which should not be selected for new connections (i.e. weight=0)
> > > b) if we receive a delete endpoint event, simply remove it from the list of backends.
> > 
> > 
> > To add more context, this is marked as Alpha in v1.20 that we recently upgraded Cilium to, and part of a new [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints). It looks like this condition already accounts for the `GracePeriod` for pods. Regardless, I found that the termination grace period is indeed included in the `ObjectMeta` structure as part of the Endpoint structure in case we need to reference that field.
> 
> > To add more context, this is marked as Alpha in v1.20 that we recently upgraded Cilium to
> 
> Similarly to our feature which would be alpha/beta and we would have to support 2 mechanisms, the k8s way and our way. Kubernetes 1.21 will be released in ~2 months, luckily by then the release will be stable.
> 
> The problem is that we can't simply watch for all Pods from all nodes as it does not scale so I would suggest to use a feature that is already available in Kubernetes upstream and adjust our code to it.

Yes, the new k8s feature addresses the problem I've stated above so I'll be using that.

**Comment by aditighag** [comment] 2021-03-18 15:59
Related required fix - https://github.com/cilium/cilium/issues/11301.

**Comment by jhead-slg** [comment] 2021-08-24 21:56
With `EndpointSliceTerminatingCondition` being promoted to beta in k8s v1.22 is work ready to begin on this issue? I have to say this is our only long standing issue with Cilium and it would be great to have it fixed.

**Comment by aditighag** [comment] 2021-08-24 22:21
@jhead-slg We've planned it for the next release (v1.11). You can monitor this issue for updates.

**Comment by andrewsykim** [comment] 2021-09-11 00:42
Just a quick FYI that in v1.22 we merged the alpha implementation of this behavior in kube-proxy (https://github.com/kubernetes/kubernetes/pull/97238). We're looking for feedback on if this is the right approach and if there are improvements to be made. I'm curious to see how Cillium will implements this and there's anything we can change in the core APIs to make our implementions more elegant.

**Comment by aditighag** [comment] 2021-09-13 17:33
@andrewsykim Thanks for the note. We'll be watching the terminating endpoints API, and update the datapath BPF maps storing service pods information accordingly. More updates to follow.

**Closed as completed** 2021-11-12 16:37 UTC
Labels: area/datapath, kind/feature, kind/meta
