### ISSUE TITLE
[BUG] Ingress Controller unexpected behavior with "PathType=ImplementationSpecific"

### ISSUE THREAD

**Issue by Syntax3rror404** [cilium/cilium#30071] opened 2023-12-29 15:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am encountering an issue with the Cilium Ingress Controller when using the `pathType: ImplementationSpecific` setting in my Ingress configuration. This setting seems to cause problems, particularly when dealing with paths behind a subpath. The controller does not function as expected, leading to difficulties in accessing resources.

Note: There are a bunch of helm chart, which punch the pathType to ImplementationSpecific and don't support templating to`Prefix`. For example the Rancher Helm Chart.

### Expected Behavior:
When using `pathType: ImplementationSpecific`, the Cilium Ingress Controller should correctly interpret and route traffic to the appropriate services, including those located behind subpaths, like the NGINX Ingress Controller.

### Actual Behavior with example:
The controller fails to properly handle paths behind a subpath, resulting in inaccessible resources and connection issues.

pathType: ImplementationSpecific -> https://isovalent.iscool.com/dashboard/ -> 404 Error!
pathType: Prefix -> https://isovalent.iscool.com/dashboard/ -> OK!

### Cilium Version

1.14.5

### Kernel Version

Linux rancher-w2 5.14.0-362.13.1.el9_3.x86_64 https://github.com/cilium/cilium/pull/1 SMP PREEMPT_DYNAMIC Wed Dec 13 14:07:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.8+rke2r1 with Rancher 2.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackmaninov** [comment] 2024-01-12 15:41
I've noticed this as well today on 1.15.0-rc.0, but I'm confused as to why helm charts would choose to use ImplementationSpecific by default, since the whole point seems to be that matching behaviour is undefined and left up to the ingress controller.

**Comment by Syntax3rror404** [comment] 2024-01-13 02:40
I dont, why there are helm charts which hard coding ImplementationSpecific as value.

But in NGINX ImplementationSpecific == Prefix

> The path supports different matching rules with the new field pathType, which takes the following values: Prefix for prefix-based matching, Exact for exact matching and ImplementationSpecific, which is the default type and is the same as Prefix.
>
> Source: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/

**Comment by squeed** [comment] 2024-01-25 11:22
Right, that's what nginx says. However, the k8s [docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) are clear that `ImplementationSpecific` can be either `Path`, `Prefix`, or something else. 

So it seems there are a lot of buggy charts out there :-(

**Comment by squeed** [comment] 2024-01-25 11:25
@youngnick should we consider backporting https://github.com/cilium/cilium/pull/29381 to v1.14?

**Comment by youngnick** [comment] 2024-01-29 01:45
Yes, #29381 should be considered for backport - although there has been some refactoring in the Ingress code, so I'm not sure how big a lift it will be.

Additionally, for Cilium, ImplementationSpecific paths in Ingress v1 objects are actually handled as Regex paths (which I think was a previous request), but as of #29381 are sorted so that they match last.

For clarity, the ordering is:
- Exact path matches
- Prefix path matches
- ImplementationSpecific path matches
- Prefix path matches where the path is `/`.

I agree that having Helm charts use ImplementationSpecific is a poor choice - the whole point of that value is that the behavior can be different per implementation.

That said, a value like `/prefix` should still work with ImplementationSpecific (since there aren't any regex specific characters anyway), so @Syntax3rror404, if you could supply some sample YAMLs, we can see if there is something missing there.

When I was testing #29381, to fix #28852, I saw cert-manager using some ImplementationSpecific paths that worked, so it's not _completely_ broken. Sample YAMLs should help zero in on what the problem is.

**Comment by youngnick** [comment] 2024-01-29 04:12
Using another issue (#30119) for some source YAML, I found that, because we treat ImplementationSpecific as a Regex match, it works like an Exact match in the absence of special characters, _not_ as a Prefix match.

So what I said just above is incorrect, and it's likely that the use of ImplementationSpecific is the problem. To be honest, using ImplementationSpecific to mean Prefix in a Helm chart is a bug and should be fixed. We already have people relying on our version of ImplementationSpecific to get regex matching functionality, so unfortunately we can't change it.

But if Helm chart authors want Prefix, they should use Prefix.

Sorry to not be able to provide better news, I will see if I can do a PR to our docs to make this behavior more clear.

**Comment by julianwiedmann** [comment] 2024-02-05 08:14
(I tweaked the labels based on Nick's awesome feedback. Sounds like all we want/need is a doc update.)

**Comment by Syntax3rror404** [comment] 2024-04-06 01:45
ping

**Comment by youngnick** [comment] 2024-05-06 06:42
@Syntax3rror404, as I said earlier, because Cilium implements ImplementationSpecific as a Regex match, not a Prefix match, that means that rules _without_ any regex characters are treated as _exact_ matches, which is why subpaths don't work.

I'm sorry that this has bitten you, but ImplementationSpecific means exactly that, and since Cilium is already doing Regex here (requested by other users), we can't change it now for compatibility reasons. I recommend that you contact Helm chart authors and get them to use the correct Prefix path type, since that will work with any implementation.

**Closed as not planned** 2024-06-20 11:26 UTC
Labels: kind/question, kind/community-report, feature/k8s-ingress

**Comment by paimonsoror** [comment] 2024-12-08 15:13
Oh man, ran into this same bug!  Using Cilium as ingress

**Comment by Syntax3rror404** [comment] 2024-12-08 16:11
Thats for sure because nothing has changed. It could be fixes just to use Prefix as impl specific as also nginx. 

Just remove the Cilium Ingress and use nginx and Cilium as lb and cni. Otherwise some Helm apps Are broken
