### ISSUE TITLE
Failure to install Cilium on GKE 1.24: cilium-node-init pods stuck in ContainerCreating

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22608] opened 2022-12-07 23:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction Steps
```
gcloud container clusters create gke-124-repro-cluster --num-nodes 2 --machine-type n1-standard-4 --zone europe-west4-a --node-taints node.cilium.io/agent-not-ready=true:NoSchedule --cluster-version=1.24
cilium install --rollback=false
```
This last step will fail with the cilium-node-init pods stuck in ContainerCreating.

The CLI uses hostns pods to collect bugtool reports when the agents are done. Even those hostns pods can't be run; they are stuck in Pending state (see `cilium-sysdump.log`).

### Cilium Version

```
$ ./cilium version
cilium-cli: v0.12.7-39-g63857e29 compiled with go1.19 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.4
cilium image (running): v1.12.2
```

### Kernel Version

COS

### Kubernetes Version

GKE 1.24

### Sysdump

[cilium-sysdump-20221208-000408.zip](https://github.com/cilium/cilium/files/10180727/cilium-sysdump-20221208-000408.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment] 2022-12-07 23:14
Hi @pchaigno thanks for reporting, this looks like a duplicate of https://github.com/cilium/cilium/issues/21049. Please try it out with a more recent Cilium version. Thank you.

**Closed by aanm** 2022-12-07 23:14 UTC
Labels: kind/bug, sig/k8s, needs/triage, kind/community-report, integration/cloud, sig/agent
