### ISSUE TITLE
lb: Change backend ID from u16 to u32

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16110] opened 2021-05-12 08:20 UTC
Revive the PR https://github.com/cilium/cilium/pull/8041 which changes the backend ID size from u16 to u32. Otherwise, max unique service endpoints count is 64k.

**Comment by aanm** [comment] 2021-05-12 21:45
duplicate of https://github.com/cilium/cilium/issues/14398

**Closed as completed by aanm** 2021-05-12 21:45 UTC
Labels: area/datapath, kind/feature
