### ISSUE TITLE
CI: K8sFQDNTest Restart Cilium validate that FQDN is still working

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#7105] opened 2019-02-15 16:45 UTC
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
"app2-cd69fd9f6-mtxhh" cannot curl to "http://world1.cilium.test"
Expected command: kubectl exec -n default app2-cd69fd9f6-mtxhh -- curl -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://world1.cilium.test -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.030538()', Connect: '0.000000',Transfer '0.000000', total '5.001671'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/fqdn.go:150
```

[38ca2f89_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip](https://github.com/cilium/cilium/files/2870014/38ca2f89_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip)

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9927/testReport/junit/k8s-1/8/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by ianvernon** [comment] 2019-02-18 17:45
This one has been occurring a lot in the CI:

Builds that were kicked off from merged PRs:

* [5920](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5920/)
* [5930](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5930/)
* [5937](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5937/)

Builds that run every 2 hours against master:

* [2375](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2375/)

**Comment by ianvernon** [comment] 2019-02-18 17:47
Marked this as high priority since we are hitting this frequently in the CI, and this will impact developer productivity / agility to merging.

**Comment by ianvernon** [comment] 2019-02-18 19:24
@eloycoto said in the Cilium testing Slack channel that he has added debug logs to a PR which will help provide the root cause for this issue.

**Comment by brb** [comment] 2019-02-19 09:31
A few more:

- https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2398/testReport/junit/k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/
- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5942/testReport/junit/k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by eloycoto** [comment] 2019-02-19 09:36
Added this new PR to be able to track what looks like a race on restart:
 
https://github.com/cilium/cilium/pull/7138/files

**Comment by ianvernon** [comment] 2019-02-19 20:27
Another failure: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5950/

**Comment by brb** [comment] 2019-02-20 09:37
One more: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5961/testReport/junit/k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by brb** [comment] 2019-02-21 08:19
And more: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5968/testReport/junit/k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by ianvernon** [comment] 2019-02-21 18:34
@eloycoto can you please keep this issue updated w.r.t. what you did to debug this / what you think the cause is? it's helpful to have the status of what the timeline on the fix is, what the RCA is for future developers to debug, etc.

**Comment by brb** [comment] 2019-02-22 10:21
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5974/testReport/junit/k8s-1/8/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by brb** [comment] 2019-02-22 10:23
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5981/

**Comment by eloycoto** [comment] 2019-02-22 10:31
@ianvernon is a race on PolicyAdd AFAIK, I made a PR but I close due does not fix all the issues. Open a new draft PR https://github.com/cilium/cilium/pull/7183 let's see if I can get it merged in the following days.

**Comment by eloycoto** [comment] 2019-02-22 18:20
I'll try to explain this a little bit, I had long discussion with @raybejjani around this.


The main issue is that in the RuleGen we keep a copy of the api.Rules this is
ok, but to update a Policy we need to call to PolicyAdd with this rules. The
main problem, this system is feeding also by Kubernetes CNP/KNP so the rule can
be updated, but the FQDN can overwrite the policy if the CNP does not finish.

I made this plantuml diagram to understand it better:

![image](https://user-images.githubusercontent.com/868013/53262439-d8389980-36d6-11e9-8bb6-b255d8c93b84.png)

```
@startuml

participant "K8sWathcer" as K8s
participant "FQDN Proxy" as Proxy

K8s -> PolicyAdd: New Policy is added.
PolicyAdd -> PolicyRepo: Policy RULE A has been added.
== Pod Make a request ==
Proxy -> PolicyAdd: Rule A has been updated with new IP
PolicyAdd -> PolicyRepo: Policy RULE A has been added.

== User update the CNP ==
K8s -> PolicyAdd: New Policy is added RULEB.

== Pod Make a request ==
Proxy -> PolicyAdd: Rule A has been updated with new IP (Request ZZ)
hnote over PolicyAdd :This Proxy has the old Rules, because PolicyAdd from CNP is not finish

PolicyAdd -> PolicyRepo: Policy **RULE B** has been added.

PolicyAdd -> PolicyRepo: Policy **RULE A** has been added (Request ZZ).
hnote over PolicyAdd #FFAAAA: **NEW Policy has been added and CNP is not working correctly**.

@enduml
```

The main reason, atomic is hard because before doing the ToCIDR  allocations
FQDN need to be in place. Lock is expensive here, so it's not a easy fix that we
can add here.

I made a PR to avoid stopDNS, so it's only two operations. The next step that we
thought is related to the `AddGeneratedRules` try to lock in there, but this
locks the FQDN proxy, so things can be super weird with this situation.

Try to figure multiple solutions in this problem, but all has a big caveats and
I'm still don't know how to fix it.

Ray also mentioned to have a policyVersion in the PolicyAdd, this may works, but
it'll be hard on reconcile policies in case that K8sCNP updates the policy.

Sorry!

**Comment by brb** [comment] 2019-02-25 10:05
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2422/

**Comment by brb** [comment] 2019-02-25 10:24
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2432/testReport/junit/k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by eloycoto** [comment] 2019-02-26 09:30
New diagram with the issue: 

![image](https://user-images.githubusercontent.com/868013/53402152-7798ad80-39b1-11e9-8812-72eaa99ed85e.png)


```
@startuml

participant K8s
participant DNS1
participant DNS2
participant PolicyAdd
participant policyRepo

-[#blue]> K8s: New CNP
K8s -[#blue]> PolicyAdd: Send rules to PolicyAdd
PolicyAdd -[#blue]> PolicyAdd: MarkToFQDNsRules
PolicyAdd -[#blue]> PolicyAdd: Populate local/in-function rule copy IPs from DNS Cache
PolicyAdd -[#blue]> PolicyAdd: Allocate IPs
PolicyAdd -[#blue]> policyRepo: lock
PolicyAdd -[#blue]> policyRepo: Delete old rules from repo
PolicyAdd -[#blue]> PolicyAdd: StopManageDNSName
PolicyAdd -[#blue]> PolicyAdd: Remove references to old rules
PolicyAdd -[#blue]> policyRepo: Add new rules
PolicyAdd -[#blue]> PolicyAdd: StartManageDNSName
PolicyAdd -[#blue]> policyRepo: unlock

== With multiple request ==

-[#gold]> K8s: New CNP
K8s -[#gold]> PolicyAdd: Send rules to PolicyAdd
DNS1 -[#green]> PolicyAdd: Send rules to PolicyAdd
PolicyAdd -[#gold]> PolicyAdd: MarkToFQDNsRules
PolicyAdd -[#gold]> PolicyAdd: Populate local/in-function rule copy IPs from DNS Cache
PolicyAdd -[#gold]> PolicyAdd: Allocate IPs
PolicyAdd -[#green]> PolicyAdd: MarkToFQDNsRules
PolicyAdd -[#green]> PolicyAdd: Populate local/in-function rule copy IPs from DNS Cache
PolicyAdd -[#green]> PolicyAdd: Allocate IPs
PolicyAdd -[#gold]> policyRepo: lock
PolicyAdd -[#gold]> policyRepo: Delete old rules from repo
PolicyAdd -[#gold]> PolicyAdd: StopManageDNSName
PolicyAdd -[#gold]> PolicyAdd: Remove references to old rules
PolicyAdd -[#gold]> policyRepo: Add new rules
PolicyAdd -[#gold]> PolicyAdd: StartManageDNSName
PolicyAdd -[#gold]> policyRepo: unlock
PolicyAdd -[#green]> policyRepo: lock
PolicyAdd -[#green]> policyRepo: Delete old rules from repo
PolicyAdd -[#green]> PolicyAdd: StopManageDNSName
PolicyAdd -[#green]> PolicyAdd: Remove references to old rules
PolicyAdd -[#green]> policyRepo: Add new rules
PolicyAdd -[#green]> PolicyAdd: StartManageDNSName
hnote over PolicyAdd #FFAAAA: **OLD Policy has been added and CNP is not working correctly something is lost**.
PolicyAdd -[#green]> policyRepo: unlock
@enduml
```

**Comment by jrajahalme** [comment] 2019-03-01 20:17
https://jenkins.cilium.io/job/cilium-master-K8s-all/169/

**Comment by joestringer** [comment] 2019-03-07 00:59
Removing `needs/triage` label as I believe that @eloycoto is actively working on a fix and has triaged the root cause at this point.

**Comment by jrfastab** [comment] 2019-03-07 14:10
For reference, this is still occurring in CI,
  https://jenkins.cilium.io/job/cilium-master-K8s-all/176/

**Comment by jrajahalme** [comment] 2019-03-08 15:33
Also in: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10622

**Comment by joestringer** [comment] 2019-03-11 21:17
Latest master failure:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2523/

**Comment by eloycoto** [comment] 2019-03-27 16:28
Fixed!

**Comment by nebril** [comment] 2019-05-24 07:48
Seems like we are hitting this again: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2924/

**Comment by raybejjani** [comment] 2019-05-27 14:44
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7130/testReport/junit/Suite-k8s-1/14/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by borkmann** [comment] 2019-06-26 15:07
Also still hitting in 1.5 branch: https://jenkins.cilium.io/view/Cilium-v1.5/job/cilium-v1.5-K8s-all/29/testReport/junit/Suite-k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by ianvernon** [comment] 2019-10-17 23:19
We haven't observed this in months. Closing.

**Closed as completed by ianvernon** 2019-10-17 23:19 UTC
Labels: priority/high, area/CI
