### ISSUE TITLE
Debug message "stale identity observed" is frequently printed in logs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15283] opened 2021-03-09 22:30 UTC
Cilium latest, during v1.10 dev cycle.

Seen in a failed PR, this message is frequently printed to the log:

```
2021-03-09T21:05:11.508381379Z level=debug msg="stale identity observed" identity=6 ipAddr=10.0.0.112 oldIdentity=1 subsys=hubble
```

It's just a debug message, but given how frequently it's being logged it seems like it's trying to draw attention to something being out-of-place compared to how the code was written. Just filing this to follow up and see if it's surprising to anyone. CC @cilium/hubble 

Example CI job:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.14-kernel-4.9/113/testReport/junit/Suite-k8s-1/14/K8sConformance_Portmap_Chaining_Check_connectivity_check_compliance_with_portmap_chaining/

[71a2aa28_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip](https://github.com/cilium/cilium/files/6111782/71a2aa28_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip)

**Comment by pchaigno** [comment] 2022-10-31 10:21
I believe bug https://github.com/cilium/cilium/issues/21844 has caused an increase of these debug messages, specifically for former remote-node IP addresses:
```
2022-10-21T14:51:01.983100689Z level=debug msg="stale identity observed" identity=2 ipAddr=10.164.0.29 oldIdentity=6 subsys=hubble
```

https://github.com/cilium/cilium/issues/21844 was introduced by 454df0c065bd94aa30a9d703732d64a24d3b6073 (Jun. 2022), so it doesn't explain the first report of this debug message (Mar. 2021).

**Comment by gandro** [comment] 2022-11-01 08:43
Unrelated to Paul's comment: I agree with the original sentiment, that the message can be quite spammy. I think the biggest offender is due to a conceptual mismatch between Hubble and the datapath: https://github.com/cilium/cilium/issues/14427

I wonder if we somehow could filter out messages caused by #14427 and leave the rest in place. It should then only be emitted temporarily when an identity of a prefix changes, or consistently if we have an actual bug (which I think is useful to log).

**Comment by giorio94** [comment] 2023-04-03 11:36
It looks like that something changed recently and made this even worse. The following entries were printed +16K and +1K times respectively in less than 1h (latest on master):

```
level=debug msg="stale identity observed" identity=2 ipAddr=10.1.0.7 oldIdentity=1 subsys=hubble
level=debug msg="stale identity observed" identity=6 ipAddr=10.1.0.7 oldIdentity=1 subsys=hubble
```

`10.1.0.7` is the IP address of `cilium_host` on the same node.

**Comment by pchaigno** [comment] 2023-12-13 10:18
This is now affecting our GitHub-based CI as well, making it difficult to see what failures are about:
- https://github.com/cilium/cilium/actions/runs/7180493466/job/19552893847
- https://github.com/cilium/cilium/actions/runs/7184772269/job/19566622341

**Comment by mathpl** [comment] 2023-12-13 16:24
@rolinh as default assignee for Hubble. If you have a place for a backlog you look at let me know. :)

**Comment by gandro** [comment] 2023-12-13 16:26
As mentioned offline to Paul, I believe this was addressed by  https://github.com/cilium/cilium/pull/27894  

The reason why it's still occurring in CI is that those tests are using stable Cilium versions (e.g. v1.14/v1.13 etc). I've marked that PR for backport.

**Comment by pchaigno** [comment] 2023-12-16 13:35
I am still observing such `stale identity observed` floods in a Cilium build that contains the commit from https://github.com/cilium/cilium/pull/27894:
```
2023-12-16T12:09:34.875108956Z level=debug msg="stale identity observed" identity=23647 ipAddr=10.244.1.136 oldIdentity=1 subsys=hubble
2023-12-16T12:09:34.875384419Z level=debug msg="stale identity observed" identity=10255 ipAddr=10.244.1.136 oldIdentity=1 subsys=hubble
2023-12-16T12:09:34.875791208Z level=debug msg="stale identity observed" identity=10255 ipAddr=10.244.1.136 oldIdentity=1 subsys=hubble
2023-12-16T12:09:34.876616977Z level=debug msg="stale identity observed" identity=10255 ipAddr=10.244.1.136 oldIdentity=1 subsys=hubble
```
I can share a sysdump offline (it's on a build that isn't open sourced yet).

**Comment by gandro** [comment] 2023-12-18 09:41
A sysdump would be appreciated. In particular I think it's important to understand why the datapath believes something is `localhost`, where as Hubble sees it as a pod IP.

**Closed as completed** 2023-12-18 18:53 UTC
Labels: kind/cleanup, pinned, area/agent
