### ISSUE TITLE
CFP: DNS entry in multi-cluster 

### ISSUE THREAD

**Issue by HamzaZo** [cilium/cilium#19454] opened 2022-04-15 08:08 UTC
**Is your feature request related to a problem?**

 I'm starting testing Cilium cluster mesh to enable multi-cluster communication.  I've noticed it only works when both k8s clusters have the same namespaces and service objects. Let's take the following example :

->Service A is placed in Cluster A, and needs to call --> Service B residing at Cluster B

Currently, this scenario is not possible because  `serviceb.namespaceb.svc.cluster.local`  is not present at the cluster A.

Would be possible that the cluster mesh listens to the updates of cluster B and creates a DNS entry in Cluster A to route the traffic to Service B? 

Thanks!
**Describe the feature you'd like**

Create DNS entry in multi-cluster

**Comment by aanm** [comment] 2022-05-24 11:17
@HamzaZo This seems to be a duplicate of https://github.com/cilium/cilium/issues/19701

**Closed as completed by aanm** 2022-05-24 11:17 UTC
Labels: kind/feature, area/clustermesh, kind/cfp

**Comment by xmulligan** [comment] 2022-06-27 19:42
@HamzaZo Would you mind adding to the Cilium users doc? 🐝 We need it for CNCF graduation https://github.com/cilium/cilium/blob/master/USERS.md
