### ISSUE TITLE
Catch malformed releases table before merging

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13366] opened 2020-10-01 04:55 UTC
These lines don't handle version substitution in a way that retains the valid structure of the table:

https://github.com/cilium/cilium/blob/3bb016ffd4f574ea04e70a8509295a2f0dd36f27/contrib/release/bump-readme.sh#L37-L39

As a result, we can unintentionally break the table and make it disappear entirely. It's easily fixed, for example:

https://github.com/cilium/cilium/pull/13365

However it would be better to catch before we merge it.

Possible paths:
* Fix the script to make it understand the table better, or
* Add a simple .RST validator for the README.rst to make sure that if we break the table, the CI will complain.

**Comment by pchaigno** [comment] 2020-10-01 06:42
https://github.com/myint/rstcheck seems to do a good enough job:
```
$ rstcheck README.rst 
README.rst:34: (ERROR/3) Malformed table.
$ echo $?
1
```
Are there other files besides `README.rst` we would like to check? I'm guessing we don't need to do that for `Documentation/` since we already have a renderer there.

We could run on all other `.rst` files, just in case:
```
$ find -path ./Documentation -prune -false -o -name "*.rst"
./MAINTAINERS.rst
./examples/minikube/README.rst
./examples/getting-started/README.rst
./examples/policies/l3/simple/README.rst
./FURTHER_READINGS.rst
./README.rst
$ find -path ./Documentation -prune -false -o -name "*.rst" | xargs rstcheck
./README.rst:34: (ERROR/3) Malformed table.
```

**Comment by pchaigno** [comment] 2021-02-03 14:27
This new check could be added as a GitHub action.

**Comment by geyslan** [comment] 2021-05-28 17:26
It should use the `--report error` flag

```bash
❯ rstcheck --report error README.rst
```

Otherwise we would have kind of false positives
```bash
❯ rstcheck README.rst 
README.rst:269: (INFO/1) Duplicate implicit target name: "getting started".
```
This is the cause of the INFO/1 warning
```
Getting Started
===============
...
* `Getting Started`_ 
```

**Comment by pchaigno** [comment] 2021-05-28 22:24
@geyslan Done. Don't hesitate to reach out on Slack (e.g., in #development) if you have any question.

**Comment by joestringer** [comment] 2021-07-08 19:29
Reopening since we reverted the fix. Proposed new solution is presented here:
https://github.com/cilium/cilium/pull/16786#issuecomment-876491875

**Comment by geyslan** [comment] 2021-07-20 20:54
> Reopening since we reverted the fix. Proposed new solution is presented here:
> [#16786 (comment)](https://github.com/cilium/cilium/pull/16786#issuecomment-876491875)

I think the solution is being addressed by @qmonnet, right? If so, I suppose that's ok to unassign me? Thanks.

**Comment by joestringer** [comment] 2021-07-20 21:18
I don't think that @qmonnet has picked this up, but if you don't plan to work on this then we can unassign you :thumbsup:

**Comment by geyslan** [comment] 2021-07-20 21:52
@joestringer, said that, no worries, I can continue this work. I suppose that this proposal could solve the issue related to new branches: https://github.com/cilium/cilium/pull/16387#issuecomment-874184376

As I commented, it seems to work at my forked repo: https://github.com/geyslan/cilium/runs/2991422456?check_suite_focus=true

What do you suggest for testing it without the need to remotely merge this workflow?

**Comment by qmonnet** [comment] 2021-07-21 09:19
Please refer to [my comment on the reverting PR](https://github.com/cilium/cilium/pull/16786#issuecomment-876491875). We _already_ have rstcheck running on the RST files, and I don't think the current PR brings anything more other than checking README.rst (which is easy to add to the current rstcheck run we have). If I'm wrong, please convince me. I also believe that the current version of rstcheck is not usable to detect malformed tables, because it breaks on tables containing substitution references.

I would love the maintainer of rstcheck to merge the pending PR for that, but sadly it doesn't look like the project is very active. So that leaves us with a few solutions:

- Wait more
- Use our own rstcheck fork with the fix (but is it worth the trouble?)
- Use yet another tool (is it desirable?)

But please let's not add a second rstcheck run if it brings no additional verifications.

**Comment by ti-mo** [comment] 2023-06-22 12:11
Wondering if this is still an issue today and if so, if it's worth addressing and if we can get this scheduled for 1.15. If not, we should consider closing.

**Comment by qmonnet** [comment] 2023-06-22 12:43
I got my fix merged in rstcheck in https://github.com/rstcheck/rstcheck/pull/82, released in v6.0.0. We use v6.1.1 for our checks, so we should be able to detect malformed tables (we stopped skipping related messages in e90df2f1a103b1e363ab215eba8fa9647918c870).

So I think we're all good, and can close this issue.

**Closed as completed by qmonnet** 2023-06-22 12:43 UTC
Labels: area/CI, good-first-issue, area/CI-improvement, area/build

**Comment by joestringer** [comment] 2023-06-22 18:29
@qmonnet did we end up adding `README.rst` to the rstcheck action?

**Comment by qmonnet** [comment] 2023-06-23 09:40
Ah no, sorry, I didn't go through the whole discussion again and forgot we were talking of the README.rst. But this is an easy fix: https://github.com/cilium/cilium/pull/26454
