### ISSUE TITLE
NodePort BPF is not accessible via ExternalIP on GKE and EKS

### ISSUE THREAD

**Issue by AnishShah** [cilium/cilium#14765] opened 2021-01-28 06:04 UTC
## Bug report

There is no Service resolution happening when a client inside the cluster tries to connect to a NodePort Service via ExternalIP of the local k8s node.

**General Information**

- Cilium version (run `cilium version`) - 1.8.2
- Kernel version (run `uname -a`) 5.4
- kubeproxyReplacement=strict

**How to reproduce the issue**

1. Create a GKE cluster with Cilium
2. Create a Deployment.

```
cat <<EOF | k apply -f -                                                                                                                                                              
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx  
spec:      
  replicas: 2 
  selector:
    matchLabels:   
      app: nginx
  template:         
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
EOF
```
3. Create a NodePort Service

```
cat <<EOF | kubectl apply -f -                                                                                                                                                        
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
EOF
```

4. Check public IPs of your Nodes and NodePort of `nginx-service`

```
kubectl get nodes -o wide |  awk {'print $1" " $2 " " $7'} | column -t                                                                                                                

NAME                                        STATUS  EXTERNAL-IP
gke-cilium-test-default-pool-ef74a9bc-5lb2  Ready   a.b.c.d
gke-cilium-test-default-pool-ef74a9bc-llzm  Ready   w.x.y.z
```

```
kubectl get svc nginx-service -owide                                                                                                                                                  
NAME            TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE   SELECTOR
nginx-service   NodePort   10.112.12.31   <none>        80:31474/TCP   14s   app=nginx
```

5. Create a test pod that runs on Node with public IP `w.x.y.z` and try to reach NodePort service using public IPs of the node.

```
kubectl run -l app=foo --image=alpine --restart=Never --rm -i -t test
# wget -qO- a.b.c.d:31474
Welcome to nginx!
# wget -qO- w.x.y.z:31474
Connection timeout
```

I used Hubble to observe the packets of `test` pod. It looks like Cilium performed Service resolution for one public IP but not for the other. 

```
TIMESTAMP             SOURCE                                         DESTINATION                                    TYPE          VERDICT     SUMMARY
Jan 28 05:54:14.696   default/test:57540                             w.x.y.z:31474                            to-stack      FORWARDED   TCP Flags: SYN
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: SYN
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: SYN
Jan 28 05:54:28.937   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-stack      FORWARDED   TCP Flags: SYN, ACK
Jan 28 05:54:28.937   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-endpoint   FORWARDED   TCP Flags: SYN, ACK
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.938   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-stack      FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.938   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-endpoint   FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-stack      FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-endpoint   FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK
```

```
# cilium service list
8    10.128.0.28:31474   NodePort       1 => 10.108.1.4:80        
                                        2 => 10.108.0.9:80        
9    0.0.0.0:31474       NodePort       1 => 10.108.1.4:80        
                                        2 => 10.108.0.9:80  
```

Is this an expected behaviour? If yes, then what's the reason for this? If this is a bug, please help me and I can work on fixing this quickly.

**Comment by AnishShah** [comment] 2021-01-28 06:05
Not sure if this is same as #14728

**Comment by brb** [comment] 2021-01-28 06:09
Could you attach cilium sysdump? Also, does sending a HTTP request from the client pod to both of the nginx pods work if you use pod IPs instead?

**Comment by AnishShah** [comment] 2021-01-28 06:21
> sending a HTTP request from the client pod to both of the nginx pods work if you use pod IPs instead

yes

```
kubectl run -l app=foo --image=alpine --restart=Never -i -t test   
# wget -q0- 10.108.0.9
Welcome to nginx!
# wget -q0- 10.108.1.4
Welcome to nginx!
```

Could you attach cilium sysdump? 
This is GKE. So `anetd` ds is same as `cilium`. 
[cilium.zip](https://github.com/cilium/cilium/files/5885243/cilium.zip)

I was able to reproduce this on AWS cluster too.

**Comment by AnishShah** [comment] 2021-01-28 06:30
Following things work correctly.

1. DNS name works

```
kubectl run -l app=foo --image=alpine --restart=Never -i -t test 
# wget -qO- nginx-service
Welcome to nginx!
```

2. Internal IP of Nodes work.

```
# wget -qO- 10.128.0.28:31474
Welcome to nginx!
# wget -qO- 10.128.0.27:31474
Welcome to nginx!
```

3. One of the public IP of Node works.
```
# wget -qO- a.b.c.d:31474
Welcome to nginx!
# wget -qO- w.x.y.z:31474
Connection timeout
```

**Comment by brb** [comment] 2021-01-28 06:54
Thanks for the info!

> I was able to reproduce this on AWS cluster too.

Do nodes on AWS have both k8s InternalIP and ExternalIP?

**Comment by AnishShah** [comment] 2021-01-28 06:57
> Do nodes on AWS have both k8s InternalIP and ExternalIP?

yes. The same behaviour. It doesn't work for only one ExternalIP.

**Comment by brb** [comment] 2021-01-28 07:21
The problem is that cilium-agent prefers InternalIP over ExternalIP in your case, as the latter is not assigned to any of network devices on the node. The IP addr is used to provision the service in the BPF map. Currently, you have:
- `0.0.0.0:NodePort` - accessible from inside a cluster via any IP addr assigned to a client pod node or a loopback addr.
- `InternalIP:NodePort` - accessible from outside.

The fix would be to extend https://github.com/cilium/cilium/blob/master/pkg/datapath/linux/node_addressing.go#L90 by adding ExternalIP/InternalIP addr to the list if it already doesn't exist.

Are you willing to work on the fix?

**Comment by AnishShah** [comment] 2021-01-28 08:05
Hi Martynas, Thanks for investigating. I can work on the fix.

> The problem is that cilium-agent prefers InternalIP over ExternalIP in your case, as the latter is not assigned to any of network devices on the node.

I didn't understand this. As we see in Hubble output (comment#1), service resolution happens for ExternalIP `a.b.c.d` but not `w.x.y.z`.

**Comment by brb** [comment] 2021-01-28 09:05
> I didn't understand this. As we see in Hubble output (comment#1), service resolution happens for ExternalIP a.b.c.d but not w.x.y.z.

That's a good question. For some reasons ExternalIP of the remote node was in the local IPCache (`cilium-bpf-lb-list.md`) with the remote node identity, while ExternalIP of the local node was not there. So, for `a.b.c.d` (which is remote node's ExternalIP) this https://github.com/cilium/cilium/blob/master/bpf/bpf_sock.c#L249 made the service translation to happen. So the real fix is to add local ExternalIP entry into the IPCache, so that the bpf_sock translation can take place.

**Comment by brb** [comment] 2021-01-28 09:50
https://github.com/cilium/cilium/blob/ea15d37fa298ad8e3f46cd444ca0de63e6369546/daemon/cmd/datapath.go#L205 this is where the IPCache insert happens. I'd check why `addrs, err := d.datapath.LocalNodeAddressing().IPv4().LocalAddresses()` didn't return ExternalIP.

**Comment by AnishShah** [comment] 2021-01-28 21:45
Thanks. looking into it.

**Comment by AnishShah** [comment] 2021-01-29 01:49
@brb Thanks for helping. I added log statements in various files and I was able to find the issue I think.

The IPCache insert of ExternalIPs of nodes is happening in NodeManager -
https://github.com/cilium/cilium/blob/dc0841e2d89c19f836588ff44ba20973fd49af35/pkg/node/manager/manager.go#L388

For remote nodes, `ExternalIP`, `InternalIP` and `CiliumInternalIP` are added to IPCache. But for local node, only `InternalIP` and `CiliumInternalIP` is added.

LocalNode is added to NodeManager here -
https://github.com/cilium/cilium/blob/dc0841e2d89c19f836588ff44ba20973fd49af35/pkg/nodediscovery/nodediscovery.go#L233

I notice something weird - `ExternalIPv4` is used as `InternalIP`. Why is that?

https://github.com/cilium/cilium/blob/dc0841e2d89c19f836588ff44ba20973fd49af35/pkg/nodediscovery/nodediscovery.go#L181-L186

`ExternalIPv4` is set to InternalIP here - 

https://github.com/cilium/cilium/blob/dc0841e2d89c19f836588ff44ba20973fd49af35/pkg/k8s/init.go#L239 

https://github.com/cilium/cilium/blob/dc0841e2d89c19f836588ff44ba20973fd49af35/pkg/node/types/node.go#L216-L232


This looks weird. Any idea why is it like this? `GetExternalIPv4` is being used in many different places to get `InternalIP` in the codebase.

**Comment by AnishShah** [comment] 2021-01-29 01:51
The fix is to append ExternalIP of local node here - 

https://github.com/cilium/cilium/blob/dc0841e2d89c19f836588ff44ba20973fd49af35/pkg/nodediscovery/nodediscovery.go#L170-L207

But not sure what's the clean way to do it.

**Closed as completed** 2021-02-05 19:16 UTC
Labels: kind/bug, kind/community-report
