### ISSUE TITLE
Nodeport is not working on Kubernetes 1.9

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2505] opened 2018-01-12 15:04 UTC
Report from Adrian on slack. 

On kubernetes 1.9 the Nodeport is not working.  I tested and it does not work for me either. 

iptables output: 

```
sudo iptables-save -c
# Generated by iptables-save v1.4.21 on Thu Jan 11 19:44:13 2018
*raw
:PREROUTING ACCEPT [403632:359698784]
:OUTPUT ACCEPT [357430:158972411]
COMMIT
# Completed on Thu Jan 11 19:44:13 2018
# Generated by iptables-save v1.4.21 on Thu Jan 11 19:44:13 2018
*mangle
:PREROUTING ACCEPT [425398:372755767]
:INPUT ACCEPT [393764:364062348]
:FORWARD ACCEPT [31630:8687703]
:OUTPUT ACCEPT [383055:230067225]
:POSTROUTING ACCEPT [414685:238754928]
COMMIT
# Completed on Thu Jan 11 19:44:13 2018
# Generated by iptables-save v1.4.21 on Thu Jan 11 19:44:13 2018
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [15:900]
:POSTROUTING ACCEPT [15:900]
:CILIUM_POST - [0:0]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-2WTOLLNIWYNADKA7 - [0:0]
:KUBE-SEP-5LVWUGCLHN3U7GUU - [0:0]
:KUBE-SEP-A3XIH6QCKBVXPWD2 - [0:0]
:KUBE-SEP-IM5U45I3EWPWMXCH - [0:0]
:KUBE-SEP-JAGSSZNUSPMKIZIE - [0:0]
:KUBE-SEP-JLDLD4IAI5VCAE4M - [0:0]
:KUBE-SEP-SF2L47YKQKYQLKA7 - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-P4U35MOJNIBTZFIS - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
[709:45942] -A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
[634:30408] -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
[11885:704284] -A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
[211:10116] -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
[11893:704764] -A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
[0:0] -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
[11841:701612] -A POSTROUTING -m comment --comment "cilium-feeder: CILIUM_POST" -j CILIUM_POST
[0:0] -A CILIUM_POST ! -s 10.233.67.44/32 -o cilium_host -m comment --comment "cilium host->cluster masquerade" -j SNAT --to-source 10.233.67.44
[4:240] -A CILIUM_POST -s 10.233.67.0/24 ! -d 10.233.67.0/24 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
[0:0] -A DOCKER -i docker0 -j RETURN
[0:0] -A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
[0:0] -A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
[0:0] -A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/dex:dex" -m tcp --dport 32000 -j KUBE-MARK-MASQ
[0:0] -A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/dex:dex" -m tcp --dport 32000 -j KUBE-SVC-P4U35MOJNIBTZFIS
[0:0] -A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
[0:0] -A KUBE-SEP-2WTOLLNIWYNADKA7 -s 10.233.67.32/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-2WTOLLNIWYNADKA7 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.233.67.32:53
[0:0] -A KUBE-SEP-5LVWUGCLHN3U7GUU -s 10.233.67.66/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-5LVWUGCLHN3U7GUU -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.233.67.66:53
[0:0] -A KUBE-SEP-A3XIH6QCKBVXPWD2 -s 172.29.248.133/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-A3XIH6QCKBVXPWD2 -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-A3XIH6QCKBVXPWD2 --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 172.29.248.133:6443
[0:0] -A KUBE-SEP-IM5U45I3EWPWMXCH -s 10.233.67.66/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-IM5U45I3EWPWMXCH -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.233.67.66:53
[0:0] -A KUBE-SEP-JAGSSZNUSPMKIZIE -s 172.29.244.19/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-JAGSSZNUSPMKIZIE -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-JAGSSZNUSPMKIZIE --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 172.29.244.19:6443
[0:0] -A KUBE-SEP-JLDLD4IAI5VCAE4M -s 10.233.65.38/32 -m comment --comment "kube-system/dex:dex" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-JLDLD4IAI5VCAE4M -p tcp -m comment --comment "kube-system/dex:dex" -m tcp -j DNAT --to-destination 10.233.65.38:5556
[0:0] -A KUBE-SEP-SF2L47YKQKYQLKA7 -s 10.233.67.32/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-SF2L47YKQKYQLKA7 -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.233.67.32:53
[0:0] -A KUBE-SERVICES ! -s 10.233.64.0/18 -d 10.233.0.3/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
[0:0] -A KUBE-SERVICES -d 10.233.0.3/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
[0:0] -A KUBE-SERVICES ! -s 10.233.64.0/18 -d 10.233.0.3/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
[0:0] -A KUBE-SERVICES -d 10.233.0.3/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
[0:0] -A KUBE-SERVICES ! -s 10.233.64.0/18 -d 10.233.49.70/32 -p tcp -m comment --comment "kube-system/dex:dex cluster IP" -m tcp --dport 5556 -j KUBE-MARK-MASQ
[0:0] -A KUBE-SERVICES -d 10.233.49.70/32 -p tcp -m comment --comment "kube-system/dex:dex cluster IP" -m tcp --dport 5556 -j KUBE-SVC-P4U35MOJNIBTZFIS
[0:0] -A KUBE-SERVICES ! -s 10.233.64.0/18 -d 10.233.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
[0:0] -A KUBE-SERVICES -d 10.233.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
[0:0] -A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
[0:0] -A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-2WTOLLNIWYNADKA7
[0:0] -A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-5LVWUGCLHN3U7GUU
[0:0] -A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-JAGSSZNUSPMKIZIE --mask 255.255.255.255 --rsource -j KUBE-SEP-JAGSSZNUSPMKIZIE
[0:0] -A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-A3XIH6QCKBVXPWD2 --mask 255.255.255.255 --rsource -j KUBE-SEP-A3XIH6QCKBVXPWD2
[0:0] -A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-JAGSSZNUSPMKIZIE
[0:0] -A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-A3XIH6QCKBVXPWD2
[0:0] -A KUBE-SVC-P4U35MOJNIBTZFIS -m comment --comment "kube-system/dex:dex" -j KUBE-SEP-JLDLD4IAI5VCAE4M
[0:0] -A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-SF2L47YKQKYQLKA7
[0:0] -A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-IM5U45I3EWPWMXCH
COMMIT
# Completed on Thu Jan 11 19:44:13 2018
# Generated by iptables-save v1.4.21 on Thu Jan 11 19:44:13 2018
*filter
:INPUT ACCEPT [355:141823]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [348:57848]
:CILIUM_FORWARD - [0:0]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
:KUBE-SERVICES - [0:0]
[253795:292852854] -A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
[255190:293124793] -A INPUT -j KUBE-FIREWALL
[24714:6854318] -A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD
[28:1680] -A FORWARD -m comment --comment "cilium-feeder: CILIUM_FORWARD" -j CILIUM_FORWARD
[231816:44982217] -A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
[233410:47930386] -A OUTPUT -j KUBE-FIREWALL
[24:1440] -A CILIUM_FORWARD -o cilium_host -m comment --comment "cilium: clear masq bit for pkts to cilium_host" -j MARK --set-xmark 0x0/0x4000
[24:1440] -A CILIUM_FORWARD -d 10.0.0.0/8 -o cilium_host -m comment --comment "cilium: any->cluster forward accept" -j ACCEPT
[0:0] -A CILIUM_FORWARD -s 10.0.0.0/8 -i cilium_host -m comment --comment "cilium: cluster->any forward accept" -j ACCEPT
[0:0] -A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
[0:0] -A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
[16:916] -A KUBE-FORWARD -s 10.233.64.0/18 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[16:7108] -A KUBE-FORWARD -d 10.233.64.0/18 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Thu Jan 11 19:44:13 2018
```

**Comment by eloycoto** [comment] 2018-01-12 16:26
The main issue looks like that it is the new `KUBE-FORWARD` rules: 

```
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 10.10.0.0/16 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 10.10.0.0/16 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

**Comment by tgraf** [comment] 2018-01-13 01:45
OK, so the new `-j ACCEPT` in the `KUBE-FORWARD` chain will skip the following important rule:

```
-A CILIUM_FORWARD -o cilium_host -m comment --comment "cilium: clear masq bit for pkts to cilium_host" -j MARK --set-xmark 0x0/0x4000
```

**Comment by manalibhutiyani** [comment] 2018-01-19 18:34
This is a duplicate of GH #2495

**Closed as completed** 2018-02-08 15:56 UTC
Labels: kind/bug, priority/high, area/k8s, kind/community-report
