### ISSUE TITLE
kube-dns does not come up with cilium

### ISSUE THREAD

**Issue by mellotron** [cilium/cilium#831] opened 2017-05-27 14:40 UTC
When using cilium as a CNI, kube-dns never comes up, it seems to be trying to get to the kubernetes ClusterIP:

```
I0527 14:36:53.880904       1 dns.go:49] version: v1.5.2-beta.0+$Format:%h$
I0527 14:36:53.881704       1 server.go:70] Using configuration read from directory: /kube-dns-config%!(EXTRA time.Duration=10s)
I0527 14:36:53.881739       1 server.go:112] FLAG: --alsologtostderr="false"
I0527 14:36:53.881752       1 server.go:112] FLAG: --config-dir="/kube-dns-config"
I0527 14:36:53.881758       1 server.go:112] FLAG: --config-map=""
I0527 14:36:53.881761       1 server.go:112] FLAG: --config-map-namespace="kube-system"
I0527 14:36:53.881764       1 server.go:112] FLAG: --config-period="10s"
I0527 14:36:53.881774       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
I0527 14:36:53.881777       1 server.go:112] FLAG: --dns-port="10053"
I0527 14:36:53.881783       1 server.go:112] FLAG: --domain="cluster.local."
I0527 14:36:53.881788       1 server.go:112] FLAG: --federations=""
I0527 14:36:53.881793       1 server.go:112] FLAG: --healthz-port="8081"
I0527 14:36:53.881796       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
I0527 14:36:53.881800       1 server.go:112] FLAG: --kube-master-url=""
I0527 14:36:53.881805       1 server.go:112] FLAG: --kubecfg-file=""
I0527 14:36:53.881807       1 server.go:112] FLAG: --log-backtrace-at=":0"
I0527 14:36:53.881814       1 server.go:112] FLAG: --log-dir=""
I0527 14:36:53.881820       1 server.go:112] FLAG: --log-flush-frequency="5s"
I0527 14:36:53.881823       1 server.go:112] FLAG: --logtostderr="true"
I0527 14:36:53.881827       1 server.go:112] FLAG: --nameservers=""
I0527 14:36:53.881830       1 server.go:112] FLAG: --stderrthreshold="2"
I0527 14:36:53.881834       1 server.go:112] FLAG: --v="2"
I0527 14:36:53.881838       1 server.go:112] FLAG: --version="false"
I0527 14:36:53.881844       1 server.go:112] FLAG: --vmodule=""
I0527 14:36:53.881891       1 server.go:175] Starting SkyDNS server (0.0.0.0:10053)
I0527 14:36:53.882051       1 server.go:197] Skydns metrics enabled (/metrics:10055)
I0527 14:36:53.882057       1 dns.go:147] Starting endpointsController
I0527 14:36:53.882060       1 dns.go:150] Starting serviceController
I0527 14:36:53.882163       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0527 14:36:53.882186       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0527 14:36:54.382179       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
I0527 14:36:54.882461       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
...
I0527 14:37:23.882430       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
E0527 14:37:23.882913       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0527 14:37:23.883027       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0527 14:37:24.382333       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
...
```

Cilium is up and running:

```
kube-system   cilium-bgwc0                    1/1       Running   0          3h
kube-system   cilium-consul-rf3rp             1/1       Running   0          3h
kube-system   etcd-arosa                      1/1       Running   0          3h
kube-system   kube-apiserver-arosa            1/1       Running   0          6m
kube-system   kube-controller-manager-arosa   1/1       Running   0          3h
kube-system   kube-dns-3913472980-2sq7m       2/3       Error     7          6m
...
```

**Comment by tgraf** [comment] 2017-05-28 21:33
This was most likely due to lack of policy which would not allow `kube-dns` to talk to the API server. We just merged #815 which should resolve this.

**Comment by tgraf** [comment] 2017-05-30 16:31
After further debugging with with goloxina on Slack:

The issue is that Cilium does not pick up the existing k8s service that is already configured and thus `kube-dns` cannot communicate with the k8s API server.

**Comment by tgraf** [comment] 2017-05-31 00:52
> After further debugging with with goloxina on Slack:
> 
> The issue is that Cilium does not pick up the existing k8s service that is already configured and thus kube-dns cannot communicate with the k8s API server.

In the case of goloxina, the issue has been tracked down to the TPR resource not being able to be created and thus k8s resources not being watched at all.

**Comment by tgraf** [comment] 2017-06-06 18:23
@mellotron For the environment for goloxina, we tracked down the issue to a lacking RBAC permission which prevented the TPR to be created. Can you confirm that this is the case for you as well?

**Closed as completed** 2017-07-10 10:43 UTC
Labels: kind/bug
