### ISSUE TITLE
"Bad file descriptor" after cilium agent restart

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1372] opened 2017-08-24 23:40 UTC
We have observed "Bad file descriptor" errors when updating the BPF policy map after the agent has been restarted and recovered state.

**Comment by borkmann** [comment] 2017-08-25 10:16
Related issue is #1031 by the way. If I'm not missing anything, I recently had a discussion with @aanm on this, and the issue is that recovery cannot use old, inactive (map etc) fd numbers, and needs to reopen those.

**Comment by tgraf** [comment] 2017-08-25 15:42
> Related issue is #1031 by the way.

It was obvserved with the fix from #1031 included.

**Comment by borkmann** [comment] 2017-08-25 19:34
I don't think #1135 and #1031 were related to each other. Second part that #1031  talked about was fixed in #1206 though.

**Closed as completed** 2017-09-18 14:13 UTC
Labels: kind/bug
