### ISSUE TITLE
v1.9: Cilium is broken due to a kernel complexity issue when using Kind and a recent kernel

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#14960] opened 2021-02-12 14:05 UTC
## Bug report

With recent kernels (it's the case with at least kernel 5.10), when using Kind, Cilium is broken on v1.9 due to a kernel complexity issue. The default options as suggested in [the kind installation page](https://docs.cilium.io/en/v1.9/gettingstarted/kind/#install-cilium) instruct to disable host services (`--set hostServices.enabled=false`) as this is not supported with Kind.

As PR #14951, marked for backport to v1.9, removes this limitation,  the installation documentation for Kind should be updated to instruct to instead enable host services which allows to bypass the kernel complexity issue.

**Comment by pchaigno** [comment] 2021-02-12 14:11
I think this is a duplicate of https://github.com/cilium/cilium/issues/14726, no?

**Comment by Ankurk99** [comment] 2021-04-29 13:27
I would like to take up this issue.

**Comment by pchaigno** [comment] 2021-06-28 12:49
The fix for this complexity issue has been backported to v1.9 and will be released as part of v1.9.9.

**Closed as completed by pchaigno** 2021-06-28 12:49 UTC
Labels: kind/bug, kind/complexity-issue
