### ISSUE TITLE
Verifier errors (complexity) when deploying latest master on AWS EKS

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#13995] opened 2020-11-12 03:33 UTC
## Bug report

**General Information**

- `master`
- Kernel: 
```
❯ ks exec -it cilium-75tj9 -- uname -a
Linux ip-192-168-40-159.us-west-2.compute.internal 4.14.198-152.320.amzn2.x86_64 #1 SMP Wed Sep 23 23:57:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- AWS EKS K8s

**How to reproduce the issue**

1. Deploy latest `master` of Cilium to EKS following standard EKS guide: https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-eks/#k8s-install-eks
2. Inspect logs for verifier errors like so:

```
level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 2621_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="Prog section 'from-container' rejected: Argument list too long (7)!" subsys=datapath-loader
level=warning msg=" - Type:         3" subsys=datapath-loader
level=warning msg=" - Attach Type:  0" subsys=datapath-loader
level=warning msg=" - Instructions: 3031 (0 over limit)" subsys=datapath-loader
level=warning msg=" - License:      GPL" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="Verifier analysis:" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="Skipped 9219443 bytes, use 'verb' option for the full verbose log." subsys=datapath-loader
level=warning msg="[...]" subsys=datapath-loader
level=warning msg=" *)(r0 +8)" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R1=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="1319: (0f) r1 += r7" subsys=datapath-loader
level=warning msg="1320: (7b) *(u64 *)(r0 +8) = r1" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R1=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="1321: (05) goto pc+178" subsys=datapath-loader
level=warning msg="1500: (18) r7 = 0xffff8881c6b66800" subsys=datapath-loader
level=warning msg="1502: (bf) r1 = r6" subsys=datapath-loader
level=warning msg="1503: (bf) r2 = r7" subsys=datapath-loader
level=warning msg="1504: (b7) r3 = 1" subsys=datapath-loader
level=warning msg="1505: (85) call bpf_tail_call#12" subsys=datapath-loader
level=warning msg="1506: (05) goto pc-1360" subsys=datapath-loader
level=warning msg="147: (b7) r8 = 2" subsys=datapath-loader
level=warning msg="148: (bf) r0 = r8" subsys=datapath-loader
level=warning msg="149: (95) exit" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="from 1314 to 1489: R0=inv0 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="1489: (7b) *(u64 *)(r10 -56) = r7" subsys=datapath-loader
level=warning msg="1490: (b7) r1 = 1" subsys=datapath-loader
level=warning msg="1491: (7b) *(u64 *)(r10 -64) = r1" subsys=datapath-loader
level=warning msg="1492: (bf) r2 = r10" subsys=datapath-loader
level=warning msg="1493: (07) r2 += -136" subsys=datapath-loader
level=warning msg="1494: (bf) r3 = r10" subsys=datapath-loader
level=warning msg="1495: (07) r3 += -64" subsys=datapath-loader
level=warning msg="1496: (18) r1 = 0xffff8881fb2a0000" subsys=datapath-loader
level=warning msg="1498: (b7) r4 = 0" subsys=datapath-loader
level=warning msg="1499: (85) call bpf_map_update_elem#2" subsys=datapath-loader
level=warning msg="1500: safe" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="from 1292 to 148: R1=inv0 R2=inv0 R3=inv1076582406 R4=inv(id=0,umin_value=1536,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv4294967162 R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="148: (bf) r0 = r8" subsys=datapath-loader
level=warning msg="149: (95) exit" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="from 1288 to 1290: R1=inv2 R2=inv1 R3=inv1076582406 R4=inv(id=0,umin_value=1536,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv4294967162 R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="1290: (77) r1 >>= 31" subsys=datapath-loader
level=warning msg="1291: (4f) r1 |= r2" subsys=datapath-loader
level=warning msg="1292: safe" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="from 25 to 102: R1=pkt_end(id=0,off=0,imm=0) R2=inv4294967157 R3=inv(id=0) R4=inv(id=0,umin_value=1536,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=inv0 R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="102: (b7) r1 = 2" subsys=datapath-loader
level=warning msg="103: (63) *(u32 *)(r6 +64) = r1" subsys=datapath-loader
level=warning msg="104: (18) r1 = 0x4" subsys=datapath-loader
level=warning msg="106: (63) *(u32 *)(r6 +48) = r1" subsys=datapath-loader
level=warning msg="107: (63) *(u32 *)(r6 +60) = r7" subsys=datapath-loader
level=warning msg="108: (63) *(u32 *)(r6 +56) = r2" subsys=datapath-loader
level=warning msg="109: (63) *(u32 *)(r6 +52) = r7" subsys=datapath-loader
level=warning msg="110: (61) r8 = *(u32 *)(r6 +0)" subsys=datapath-loader
level=warning msg="111: (7b) *(u64 *)(r10 -56) = r7" subsys=datapath-loader
level=warning msg="112: (7b) *(u64 *)(r10 -64) = r7" subsys=datapath-loader
level=warning msg="113: (b7) r1 = 512" subsys=datapath-loader
level=warning msg="114: (7b) *(u64 *)(r10 -136) = r1" subsys=datapath-loader
level=warning msg="115: (87) r2 neg 0" subsys=datapath-loader
level=warning msg="116: (73) *(u8 *)(r10 -136) = r2" subsys=datapath-loader
level=warning msg="117: (bf) r2 = r10" subsys=datapath-loader
level=warning msg="118: (07) r2 += -136" subsys=datapath-loader
level=warning msg="119: (18) r1 = 0xffff8881fb2a0000" subsys=datapath-loader
level=warning msg="121: (85) call bpf_map_lookup_elem#1" subsys=datapath-loader
level=warning msg="122: (15) if r0 == 0x0 goto pc+7" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="123: (79) r1 = *(u64 *)(r0 +0)" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="124: (07) r1 += 1" subsys=datapath-loader
level=warning msg="125: (7b) *(u64 *)(r0 +0) = r1" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R1=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="126: (79) r1 = *(u64 *)(r0 +8)" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R1=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="127: (0f) r1 += r8" subsys=datapath-loader
level=warning msg="128: (7b) *(u64 *)(r0 +8) = r1" subsys=datapath-loader
level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R1=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="129: (05) goto pc+11" subsys=datapath-loader
level=warning msg="141: (18) r7 = 0xffff8881c6b66800" subsys=datapath-loader
level=warning msg="143: (bf) r1 = r6" subsys=datapath-loader
level=warning msg="144: (bf) r2 = r7" subsys=datapath-loader
level=warning msg="145: (b7) r3 = 1" subsys=datapath-loader
level=warning msg="146: (85) call bpf_tail_call#12" subsys=datapath-loader
level=warning msg="147: (b7) r8 = 2" subsys=datapath-loader
level=warning msg="148: (bf) r0 = r8" subsys=datapath-loader
level=warning msg="149: (95) exit" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="from 122 to 130: R0=inv0 R6=ctx(id=0,off=0,imm=0) R7=inv0 R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=pkt(id=0,off=0,r=14,imm=0) R10=fp0" subsys=datapath-loader
level=warning msg="130: (7b) *(u64 *)(r10 -56) = r8" subsys=datapath-loader
level=warning msg="131: (b7) r1 = 1" subsys=datapath-loader
level=warning msg="132: (7b) *(u64 *)(r10 -64) = r1" subsys=datapath-loader
level=warning msg="133: (bf) r2 = r10" subsys=datapath-loader
level=warning msg="134: (07) r2 += -136" subsys=datapath-loader
level=warning msg="135: (bf) r3 = r10" subsys=datapath-loader
level=warning msg="136: (07) r3 += -64" subsys=datapath-loader
level=warning msg="137: (18) r1 = 0xffff8881fb2a0000" subsys=datapath-loader
level=warning msg="139: (b7) r4 = 0" subsys=datapath-loader
level=warning msg="140: (85) call bpf_map_update_elem#2" subsys=datapath-loader
level=warning msg="141: safe" subsys=datapath-loader
level=warning msg="BPF program is too large. Processed 131073 insn" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="Error fetching program/map!" subsys=datapath-loader
level=warning msg="Unable to load program" subsys=datapath-loader
```

Because all endpoints are failing to compile, this leads to `cilium-health status` reporting:

```
❯ ks exec -it cilium-75tj9 -- cilium-health status
Probe time:   2020-11-12T01:36:28Z
Nodes:
  ip-192-168-40-159.us-west-2.compute.internal (localhost):
    Host connectivity to 192.168.40.159:
      ICMP to stack:   OK, RTT=285.256µs
      HTTP to agent:   OK, RTT=417.697µs
    Endpoint connectivity to 192.168.33.69:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://192.168.33.69:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  ip-192-168-6-117.us-west-2.compute.internal:
    Host connectivity to 192.168.6.117:
      ICMP to stack:   OK, RTT=3.132166ms
      HTTP to agent:   OK, RTT=1.409103ms
    Endpoint connectivity to 192.168.127.144:
      ICMP to stack:   OK, RTT=3.106842ms
      HTTP to agent:   Get "http://192.168.127.144:4240/hello": dial tcp 192.168.127.144:4240: connect: connection refused
```

The same Cilium version deployed on GKE running 4.19 kernel is fine. This seems to be an issue with < 4.19 kernels, likely 4.9.

**Comment by borkmann** [comment] 2020-11-12 07:45
If you revert the two recent commits ...
- https://github.com/cilium/cilium/commit/1ed1db1b943582afadca64b8477fcfdd94a7252c
- https://github.com/cilium/cilium/commit/a7999315286d203fae2614ce7ed10c640dc4d13c
... is the complexity issue gone?

**Comment by jibi** [comment] 2020-11-12 09:06
I _suspect_ after we merge #13347 (which includes some changes to reduce the complexity also on older kernels) this issue should go away.
Let me first try to reproduce it locally

**Comment by christarazi** [comment] 2020-11-12 16:54
Sysdump: 
[cilium-sysdump-20201112-085216.zip](https://github.com/cilium/cilium/files/5532025/cilium-sysdump-20201112-085216.zip)

**Comment by sakharovaan** [comment] 2020-11-13 00:24
I can observe the same issue with cilium 1.9.0, ubuntu 20.04.1 and kernels 5.9.8-050908-generic and 5.8.18-050818-generic:

**Comment by pchaigno** [comment] 2020-11-13 08:51
@sakharovaan Did you deploy with the same Helm flags as @christarazi? Could you post a sysdump?

**Comment by sakharovaan** [comment] 2020-11-13 15:42
@pchaigno sure, here is sysdump and helm values
[cilium-sysdump-20201113-183708.zip](https://github.com/cilium/cilium/files/5537825/cilium-sysdump-20201113-183708.zip)

[values.yaml.txt](https://github.com/cilium/cilium/files/5537835/values.yaml.txt)

**Comment by jibi** [comment] 2020-11-18 17:31
@christarazi's issues seem to be gone on latest master on EKS

@sakharovaan: I'm not sure how to reproduce your EKS setup, so you could either test an image based on master or wait a few days for the changes (which hopefully should solve also your issue) to get backported to 1.9

**Comment by sakharovaan** [comment] 2020-11-18 18:03
@jibi that's actually not an EKS, but a on-premises setup with same error message.

**Comment by pchaigno** [comment] 2020-11-18 18:37
@sakharovaan Could you open a new issue with steps to reproduce?

It looks like the issue _may_ be different from the bug reported at the beginning of this thread. Providing reproduction steps (e.g., what Helm/cilium-agent command you used to deploy) would help us validate that.

If the bug is the same, then v1.9.1 should fix it. You can already test the fix today with `cilium/cilium:latest`.

**Comment by jibi** [comment] 2020-11-19 09:31
I'm closing this ticket for now as I can't reproduce the EKS issues anymore

**Closed as completed by jibi** 2020-11-19 09:31 UTC
Labels: kind/bug, area/datapath, kind/regression, kind/complexity-issue
