### ISSUE TITLE
CFP: Egress gateway support for IPv6 traffic.

### ISSUE THREAD

**Issue by jackmaninov** [cilium/cilium#36201] opened 2024-11-27 08:48 UTC
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

According to https://docs.cilium.io/en/stable/network/egress-gateway/egress-gateway/, "Egress gateway is not supported for IPv6 traffic." 

I run a dual stack cluster with isolated workers that communicate with the outside world via "ingress" nodes, but which communicate over Wireguard on the public internet. Egress gateway works perfectly for my IPv4-only clients. I am already using IPv6 masquerading as my pod/service are ULA CIDRs. At present IPv6 connections are masqueraded to my workers' public IPv6 addresses, but this access will eventually be firewalled off.

Given IPv4 address exhaustion, I would like to be able to offer my clients transit to external IPv6 addresses in a similar manner to IPv4 on Cilium Egress Gateway. 

**Describe the feature you'd like**

Some sort of IPv6 support for Cilium Egress Gateway. Is this planned?

**(Optional) Describe your proposed solution**

**Comment by julianwiedmann** [comment] 2024-11-28 15:36
Closing as duplicate of https://github.com/cilium/cilium/issues/36201, please add any missing context there. Thank you!

**Closed as not planned by julianwiedmann** 2024-11-28 15:36 UTC
Labels: kind/feature, kind/cfp

**Comment by julianwiedmann** [comment] 2024-11-28 15:44
> > Closing as duplicate of [#36201](https://github.com/cilium/cilium/issues/36201), please add any missing context there. Thank you!
> 
> You've linked back to this same issue. Is there another issue requesting this feature, as I didn't find it when I searched.

haha sorry 🤦 . Yep it's https://github.com/cilium/cilium/issues/17908.
