### ISSUE TITLE
Pod traffic get interrupted when upgrading from 1.7.x to 1.8.x

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#13015] opened 2020-08-31 06:56 UTC
### Symptoms

Tested that when upgrading from `1.7.4` to `1.8.2`, Pod traffic will get interrupted for `1~10` seconds, or even longer.

Clarify that this does not relate to the NAT、CT configuration changes as specified in [1.8 upgrade guide](https://docs.cilium.io/en/v1.8/install/upgrade/#upgrade-notes).

### Affected version

According to the code (see blow), we assume that upgrading from `1.7.x` -> `1.8.x` will encounter this problem.

## Digging inside

Taking `1.8.2` and `1.7.4` implementation as references in the below.

## 1. Agent removes `cilium_policy` map on start, before `cilium_call_policy` is correctly setup

Endpoints rely on this BPF map for tail calls.

This map is renamed from `cilium_policy` (1.7.4) to `cilium_call_policy` (1.8.2), but [this commit](https://github.com/cilium/cilium/pull/10845/files) removes the old one on startup - before the new one correctly sets up. All endpoints on this node will get interrupted immediately.

As a quick test, reverting this commit could solve this interruption.

## 2. Agent created `cilium_call_policy` map before all endpoints' maps reloaded

There are two sequential steps in 1.8.2:

1. Reload BPF for host device (e.g. `bond1` of the node, or `cilium_host`), this will create `cilium_call_policy`.
2. Reloads BPF for all the endpoints (pods) on this node. This will update the `endpoint -> entrypoint of tail call` mappings in `cilium_call_policy`.

As step 1 happens before step 2, `cilium_call_policy` will miss all the tail calls before an endpoint is reloaded, which is another reason that leads to pod traffic interruption.

We could see the drop types are indeeded `Missed tail calls` either in the metrics, or with `cilium monitor --type=drop`:

```shell
$ cilium monitor --type=drop
xx drop (Missed tail call) flow 0x0 to endpoint 0, identity 2->0: 10.5.2.91 -> 10.6.8.106 EchoRequest
xx drop (Missed tail call) flow 0x0 to endpoint 0, identity 2->0: 10.5.2.91 -> 10.6.8.93 EchoRequest
xx drop (Missed tail call) flow 0x0 to endpoint 0, identity 2->0: 10.5.2.91 -> 10.6.8.106 EchoRequest
...
```

where `10.6.8.106` and `10.6.8.93` are IP addresses of Pods running on this node.

CC @jaffcheng

**Comment by pchaigno** [comment] 2020-08-31 18:22
Thanks for the report @ArthurChiao and @jaffcheng!

I think the issue is a bit more subtle than it appears. AFAIK, removing `cilium_policy` from the file system doesn't actually delete the map; the map will only be deleted once all references (including BPF programs) to it have been deleted.

However, in the time between the removal of that file and the reloading of all endpoints, the new `cilium_call_policy` map referenced by (among others) `bpf_host` (the program attached to `cilium_host` and native devices) will not have all entries for the endpoints, resulting in missed tail calls and packet drops.

I'm not sure what the correct solution would be. We may need to populate the new map with the content of the old before loading the base programs (i.e., `bpf_host` & co.).

It's also unclear why the upgrade/downgrade test missed this. It could be a matter of timing where most missed tail calls are coming from `bpf_host` because it is reloaded before the endpoints and the `init.sh` call. Then, since we have tunneling enabled in that test, maybe we don't have enough packets going towards endpoints via `bpf_host` to trigger a fail.

**Comment by joestringer** [comment] 2020-09-01 00:04
> I think the issue is a bit more subtle than it appears. AFAIK, removing cilium_policy from the file system doesn't actually delete the map; the map will only be deleted once all references (including BPF programs) to it have been deleted.

I believe this is true for all other map types, but `BPF_MAP_TYPE_PROG_ARRAY` has special rules here which I believe is in fact the behaviour that Arthur and Jaff report above: Once it is unpinned, it is cleaned up immediately.

In this case, it would be I think a matter of deferring the deletion of the old map until we are sure that all base programs & endpoint programs have been successfully reloaded after startup.

**Comment by jaffcheng** [comment] 2020-09-01 04:07
Hi, about fixing this, what comes to our minds first is the same as @pchaigno 

> I'm not sure what the correct solution would be. We may need to populate the new map with the content of the old before loading the base programs (i.e., `bpf_host` & co.).

To prove our idea, we've made a quick try (introduces other problems but enough to prove the idea) that:

- keeps old call map `cilium_policy`
- makes the reload of per-endpoint tc-ebpf earlier than cilium-host/native-device tc-ebpf

The packet drops by `ping -i 0.01 $ep_ip` during cilium upgrade decreased from around 300 to 1, that is from about 3 seconds to 0.1 second. Just FYI.

**Comment by borkmann** [comment] 2020-09-01 06:37
> I believe this is true for all other map types, but BPF_MAP_TYPE_PROG_ARRAY has special rules here which I believe is in fact the behaviour that Arthur and Jaff report above: Once it is unpinned, it is cleaned up immediately.

That is correct.

@jaffcheng @ArthurChiao have a chance to test fix in #13032 ?

**Comment by jaffcheng** [comment] 2020-09-01 07:07
@borkmann Hi Daniel, thanks for the quick fix! Haven't tested this fix, I think this fix keeps the old pinned tail call map, not sure if I'm right, but AFAIK, once new tc ebpf (1.8.x) is reloaded on cilium-host/native-device, tail calls to endpoints would look for elem at the index `endpoint id` from the newly created `cilium_call_policy` tail call map, which is still empty at this point.
https://github.com/cilium/cilium/blob/master/bpf/lib/l3.h#L136

**Comment by pchaigno** [comment] 2020-09-07 07:55
- #13051 should fix the drops due to missed tail calls on upgrades from v1.7 to v1.8. We will backport it to v1.8.
- #13032 will fix another bug causing missed tail calls for a much shorter period of time. We will backport it to at least v1.8.
- #13052 will fix the equivalent bug on downgrades from v1.8 to v1.7. It will be applied on v1.7 only.
- #13097 extends an existing test to detect such issues going forward. We will backport it to v1.7 and v1.8.

These four pull requests should resolve the present issue. I'm hoping to get the upgrade path fixed in the next 1.8.4 release and the downgrade path in the next 1.7.10 release.

**Comment by ArthurChiao** [comment] 2020-09-08 01:58
Hi @pchaigno, according to our discussion yesterday, we have tested #13051 and confirmed that **it is able to eliminate the traffic disruption problem** as described in the beginning of this issue.

Thanks a lot for your efforts! @pchaigno @borkmann

**Comment by pchaigno** [comment] 2020-09-09 13:15
Closing this issue as both the 1.8 and the 1.7 fixes have been merged and backported. They will likely make it into Cilium 1.7.10 and 1.8.4.

Thanks for the help debugging and testing the fixes @ArthurChiao!

**Closed as completed by pchaigno** 2020-09-09 13:15 UTC
Labels: kind/bug, priority/high, kind/community-report, needs/e2e-test
