### ISSUE TITLE
CI: Check VXLAN mode test fails with error ` Cilium not able to get into ready state`

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#4392] opened 2018-06-06 22:08 UTC
Build Link:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/972/execution/node/69/log/?consoleFull

StackTrace:
```
22:56:41   checks cilium-health status between nodes
22:56:41   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
22:56:41 ------------------------------
22:56:41 SSSSSSSSSSS
22:56:41 ------------------------------
22:56:41 K8sValidatedTunnelTest VXLan 
22:56:41   Check VXLAN mode
22:56:41   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
23:07:08 ===================== TEST FAILED =====================
23:07:08 cmd: kubectl get pods -o wide --all-namespaces
23:07:08 NAMESPACE     NAME                           READY     STATUS    RESTARTS   AGE       IP              NODE
23:07:08 default       testclient-7jl16               1/1       Running   1          10m       10.10.0.15      k8s1
23:07:08 default       testclient-fs0gg               1/1       Running   1          10m       10.10.1.210     k8s2
23:07:08 default       testds-k8l7t                   1/1       Running   1          10m       10.10.0.14      k8s1
23:07:08 default       testds-s3dzf                   1/1       Running   1          10m       10.10.1.203     k8s2
23:07:08 kube-system   cilium-1wdgg                   1/1       Running   0          10m       192.168.36.12   k8s2
23:07:08 kube-system   cilium-s900s                   0/1       Running   1          10m       192.168.36.11   k8s1
23:07:08 kube-system   etcd-k8s1                      1/1       Running   0          52m       192.168.36.11   k8s1
23:07:08 kube-system   kube-apiserver-k8s1            1/1       Running   0          51m       192.168.36.11   k8s1
23:07:08 kube-system   kube-controller-manager-k8s1   1/1       Running   0          51m       192.168.36.11   k8s1
23:07:08 kube-system   kube-dns-1992960195-hz76v      3/3       Running   0          51m       10.10.1.52      k8s2
23:07:08 kube-system   kube-proxy-0gnpj               1/1       Running   0          51m       192.168.36.11   k8s1
23:07:08 kube-system   kube-proxy-jcq2v               1/1       Running   0          24m       192.168.36.12   k8s2
23:07:08 kube-system   kube-scheduler-k8s1            1/1       Running   0          51m       192.168.36.11   k8s1
23:07:08 
23:07:08 cmd: kubectl exec -n kube-system cilium-1wdgg -- cilium bpf tunnel list
23:07:08 TUNNEL              VALUE           
23:07:08 10.10.0.0           192.168.36.11   
23:07:08 f00d::a0a:100:0:0   192.168.36.12   
23:07:08 10.10.1.0           192.168.36.12   
23:07:08 f00d::a0a:0:0:0     192.168.36.11   
23:07:08 
23:07:10 cmd: kubectl exec -n kube-system cilium-1wdgg -- cilium endpoint list
23:07:10 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                   IPv6                   IPv4          STATUS   
23:07:10            ENFORCEMENT        ENFORCEMENT                                                                                                     
23:07:10 5911       Disabled           Disabled          37424      k8s:io.kubernetes.pod.namespace=default       f00d::a0a:100:0:1717   10.10.1.203   ready   
23:07:10                                                            k8s:zgroup=testDS                                                                          
23:07:10 22753      Disabled           Disabled          41344      k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:100:0:58e1   10.10.1.52    ready   
23:07:10                                                            k8s:k8s-app=kube-dns                                                                       
23:07:10 25841      Disabled           Disabled          4          reserved:health                               f00d::a0a:100:0:64f1   10.10.1.183   ready   
23:07:10 31282      Disabled           Disabled          56756      k8s:io.kubernetes.pod.namespace=default       f00d::a0a:100:0:7a32   10.10.1.210   ready   
23:07:10                                                            k8s:zgroup=testDSClient                                                                    
23:07:10 
23:07:12 cmd: kubectl exec -n kube-system cilium-s900s -- cilium bpf tunnel list
23:07:12 TUNNEL              VALUE           
23:07:12 10.10.1.0           192.168.36.12   
23:07:12 f00d::a0a:0:0:0     192.168.36.11   
23:07:12 10.10.0.0           192.168.36.11   
23:07:12 f00d::a0a:100:0:0   192.168.36.12   
23:07:12 
23:07:16 cmd: kubectl exec -n kube-system cilium-s900s -- cilium endpoint list
23:07:16 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])               IPv6                 IPv4          STATUS   
23:07:16            ENFORCEMENT        ENFORCEMENT                                                                                               
23:07:16 21566      Disabled           Disabled          56756      k8s:io.kubernetes.pod.namespace=default   f00d::a0a:0:0:543e   10.10.0.15    ready   
23:07:16                                                            k8s:zgroup=testDSClient                                                              
23:07:16 24997      Disabled           Disabled          37424      k8s:io.kubernetes.pod.namespace=default   f00d::a0a:0:0:61a5   10.10.0.14    ready   
23:07:16                                                            k8s:zgroup=testDS                                                                    
23:07:16 47003      Disabled           Disabled          4          reserved:health                           f00d::a0a:0:0:b79b   10.10.0.177   ready   
23:07:16 
23:09:54 ===================== EXITING REPORT GENERATION =====================
23:10:28 [[ATTACHMENT|9acb0442_K8sValidatedTunnelTest_VXLan_Check_VXLAN_mode.zip]]
23:10:28 
23:10:28 • Failure [824.264 seconds]
23:10:28 K8sValidatedTunnelTest
23:10:28 /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
23:10:28   VXLan
23:10:28   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
23:10:28     Check VXLAN mode [It]
23:10:28     /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
23:10:28 
23:10:28     cilium was not able to get into ready state
23:10:28     Expected
23:10:28         <*errors.errorString | 0xc420dfedd0>: {
23:10:28             s: "Timeout reached: could not get Pods",
23:10:28         }
23:10:28     to be nil
23:10:28 
23:10:28     /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Tunnels.go:86
23:10:28 ------------------------------
23:10:28 K8sValidatedTunnelTest Geneve 
23:10:28   Check Geneve mode
23:10:28   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
23:12:46 Sending interrupt signal to process
23:12:46 Sending interrupt signal to process
```

Logs: 
[test_results.zip](https://github.com/cilium/cilium/files/2078310/test_results.zip)

**Comment by ianvernon** [comment] 2018-06-07 00:49
Behavior looks similar to #4329 .

**Comment by ianvernon** [comment] 2018-06-07 00:57
Pod `cilium-s900s` is not ready, let's see why:

```
    State:		Running
      Started:		Tue, 05 Jun 2018 22:57:49 +0000
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Tue, 05 Jun 2018 22:57:08 +0000
      Finished:		Tue, 05 Jun 2018 22:57:46 +0000
    Ready:		False
    Restart Count:	1
    Liveness:		exec [cilium status] delay=120s timeout=1s period=10s #success=1 #failure=10
    Readiness:		exec [cilium status] delay=5s timeout=1s period=5s #success=1 #failure=3
...
Events:
  FirstSeen	LastSeen	Count	From		SubObjectPath				Type		Reason			Message
  ---------	--------	-----	----		-------------				--------	------			-------
  12m		12m		1	kubelet, k8s1	spec.initContainers{clean-cilium-state}	Normal		Pulling			pulling image "busybox"
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "docker-socket" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "etc-cni-netd" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "cilium-run" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "bpf-maps" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "etcd-config-path" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "etcd-secrets" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "cilium-token-tc9h4" 
  12m		12m		1	kubelet, k8s1						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "cni-path" 
  12m		12m		1	kubelet, k8s1	spec.initContainers{clean-cilium-state}	Normal		Pulled			Successfully pulled image "busybox"
  12m		12m		1	kubelet, k8s1	spec.initContainers{clean-cilium-state}	Normal		Created			Created container
  12m		12m		1	kubelet, k8s1	spec.initContainers{clean-cilium-state}	Normal		Started			Started container
  12m		11m		4	kubelet, k8s1	spec.containers{cilium-agent}		Warning		Unhealthy		Readiness probe failed: Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?

  12m	11m	2	kubelet, k8s1	spec.containers{cilium-agent}	Normal	Pulling	pulling image "k8s1:5000/cilium/cilium-dev:latest"
  12m	11m	2	kubelet, k8s1	spec.containers{cilium-agent}	Normal	Pulled	Successfully pulled image "k8s1:5000/cilium/cilium-dev:latest"
  12m	11m	2	kubelet, k8s1	spec.containers{cilium-agent}	Normal	Created	Created container
  12m	11m	2	kubelet, k8s1	spec.containers{cilium-agent}	Normal	Started	Started container
```

But, the API is being served as indicated by the fact that the CLI returns results:
```
23:07:16 cmd: kubectl exec -n kube-system cilium-s900s -- cilium endpoint list
23:07:16 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])               IPv6                 IPv4          STATUS   
23:07:16            ENFORCEMENT        ENFORCEMENT                                                                                               
23:07:16 21566      Disabled           Disabled          56756      k8s:io.kubernetes.pod.namespace=default   f00d::a0a:0:0:543e   10.10.0.15    ready   
23:07:16                                                            k8s:zgroup=testDSClient                                                              
23:07:16 24997      Disabled           Disabled          37424      k8s:io.kubernetes.pod.namespace=default   f00d::a0a:0:0:61a5   10.10.0.14    ready   
23:07:16                                                            k8s:zgroup=testDS                                                                    
23:07:16 47003      Disabled           Disabled          4          reserved:health                           f00d::a0a:0:0:b79b   10.10.0.177   ready   
23:07:16 
```

Similar to #4329 , the pod restarted because `cilium-health` could not be started. From `cilium-s900s-logs-previous.log`:

```
2018-06-05T22:57:40.318285717Z level=debug msg="Cannot establish connection to local cilium instance" error="Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory"
2018-06-05T22:57:41.500502931Z level=debug msg="Cannot establish connection to local cilium instance" error="Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory"
2018-06-05T22:57:42.619851493Z level=debug msg="Cannot establish connection to local cilium instance" error="Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory"
2018-06-05T22:57:43.688943656Z level=debug msg="Cannot establish connection to local cilium instance" error="Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory"
2018-06-05T22:57:44.558127832Z level=fatal msg="Cilium endpoint failed to run" error="stat /var/run/cilium/state/health-endpoint.pid: no such file or directory"
```

I'm convinced this is the same issue as #4329 .

**Comment by eloycoto** [comment] 2018-06-07 07:06
Dupe of #4329

**Closed as completed by eloycoto** 2018-06-07 07:06 UTC
Labels: area/CI
