### ISSUE TITLE
Fragmented ICMP packets dropped on sending host with error: Unsupported protocol for NAT masquerade

### ISSUE THREAD

**Issue by ruicao93** [cilium/cilium#25085] opened 2023-04-24 13:10 UTC
### What happened?

- Ping from NodeA to NodeB using payload size larger than MTU. Fragmented packets(ICMP) are dropped on sender host with error: **Unsupported protocol for NAT masquerade**
- Cilium running on routing mode.

Cilium config:

```
tunnel: disabled
autoDirectNodeRoutes: true\
ipv4NativeRoutingCIDR: 10.0.0.0/8
enableIPv4Masquerade: false
```

```
# ping -s 1800 172.18.0.3
PING 172.18.0.3 (172.18.0.3) 1800(1828) bytes of data.
^C
--- 172.18.0.3 ping statistics ---
0 packets transmitted, 0 received


# cilium monitor -t drop
Listening for events on 16 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 56, file nodeport.h:2505, , identity unknown->unknown: 172.18.0.2 -> 172.18.0.3
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 56, file nodeport.h:2505, , identity unknown->unknown: 172.18.0.2 -> 172.18.0.3
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 56, file nodeport.h:2505, , identity unknown->unknown: 172.18.0.2 -> 172.18.0.3

```

### Cilium Version

1.13.90(build from master branch)

### Kernel Version

> Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Kind v1.25.3

**Comment by ruicao93** [comment] 2023-04-24 13:31
@borkmann I noticed that you had contribute a lot for the datapath. Could you help take a look?

Do you know why datapath try to do `snat` in egress path?

```
# "to-netdev"
__handle_nat_fwd_ipv4
  |-nodeport_rev_dnat_fwd_ipv4 # Nodeport LB reverse DNAT for reply packets
  # if !ctx_snat_done(ctx), Nodeport SNAT and FWD for forwarded request packets
  |-ep_tail_call(ctx, CILIUM_CALL_IPV4_NODEPORT_SNAT_FWD) 
      |-tail_handle_snat_fwd_ipv4
          |-nodeport_snat_fwd_ipv4
             |-snat_needed = snat_v4_prepare_state(ctx, &target); // if ip4->saddr == IPV4_DIRECT_ROUTING) return true
             |-snat_v4_nat(ctx, &target) # if snat_needed
                 |-check protocol
                 |-check snat_v4_nat_can_skip(target, &tuple, icmp_echoreply)
                 |-snat_v4_nat_handle_mapping # if dont skip nat  <======= Non-first fragment packets should be dropped here.
                 |-snat_v4_rewrite_egress
```

**Comment by ti-mo** [comment] 2023-04-26 14:49
Hi @ruicao93, this is a known issue and a duplicate of https://github.com/cilium/cilium/issues/23955, please keep an eye on that one. Closing this.

**Closed as completed by ti-mo** 2023-04-26 14:49 UTC
Labels: kind/bug, area/datapath, kind/community-report

**Comment by liuyuan10** [comment] 2023-04-29 00:32
this is a different issue fro m#23955. This one is because SNAT doesn't support fragmented packets.  https://github.com/cilium/cilium/blob/main/bpf/lib/nat.h#L951 We don't check if it's a fragmented packets before loading the l4 headers.

It should be the same as #11180 and #22624
