### ISSUE TITLE
CI: Suite-k8s-1.15.K8sDatapathConfig Encapsulation Check vxlan connectivity with per-endpoint routes

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#14948] opened 2021-02-12 05:27 UTC
## CI failure 

- Failing for the past 22 builds (Since #0 ) 
- observed in https://github.com/cilium/cilium/pull/14930

- Copy-paste the output the test failure.

  ```
  /home/jenkins/workspace/Cilium-PR-K8s-1.15-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
  Kubernetes DNS did not become ready in time
  /home/jenkins/workspace/Cilium-PR-K8s-1.15-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:634
  ```

- Upload the zip file generated from that test failure.
[450f39e0_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip](https://github.com/cilium/cilium/files/5969803/450f39e0_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip)

- Copy-paste the link of the CI build where that test failure has happen.

  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.15-kernel-4.9/21/testReport/junit/Suite-k8s-1/15/K8sDatapathConfig_Encapsulation_Check_vxlan_connectivity_with_per_endpoint_routes/

**Comment by pchaigno** [comment] 2021-02-12 07:56
This is a duplicate of https://github.com/cilium/cilium/issues/13774 and will be fixed once we backport #14913.

**Closed as completed by pchaigno** 2021-02-12 07:56 UTC
Labels: area/CI, ci/flake
