### ISSUE TITLE
[It] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]

### ISSUE THREAD

**Issue by slzcc** [cilium/cilium#22221] opened 2022-11-17 03:01 UTC
## CI failure

- Set title to be in the format `CI: <test-name>`.
- Copy-paste the output the test failure.
- Upload the zip file generated from that test failure.
- Copy-paste the link of the CI build where that test failure has happen.
- Include any output from logs that you think may be relevant (to ease GitHub searches).

I had a problem using k8s-conformance, A request timed out while executing the command!

```
$ curl -g --connect-timeout 5 --interface 10.170.0.4 http://127.0.0.1:31692
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

$ curl -g --connect-timeout 5 --interface 10.170.0.4 http://127.0.0.1:31692
curl: (28) Connection timed out after 5000 milliseconds
```

1. [Busybox Test Server](https://mirror.shileizcc.com/Report/2022_11_17/cilium/busybox_deploy.yaml)
2. [Cilium Deploy File](https://mirror.shileizcc.com/Report/2022_11_17/cilium/cilium_deploy.yaml)
3. [K8s Conformance Error File](https://mirror.shileizcc.com/Report/2022_11_17/cilium/k8s_conformance_error.xml)

CIlium Status: 

```
$ kubectl exec -it cilium-zr7hd -n kube-system cilium status
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.25 (v1.25.4) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Probe   [ens4 10.170.0.4, tunl0 192.168.56.0]
Host firewall:           Disabled
CNI Chaining:            portmap
Cilium:                  Ok   1.12.3 (v1.12.3-1c466d2)
NodeMonitor:             Disabled
Cilium health daemon:    Ok
IPAM:                    IPv4: 6/254 allocated from 172.208.1.0/24,
ClusterMesh:             0/0 clusters ready, 0 global-services
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            BPF   [ens4, tunl0]   172.208.1.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       35/35 healthy
Proxy Status:            OK, ip 172.208.1.142, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Disabled
Encryption:              Disabled
Cluster health:          2/2 reachable   (2022-11-17T02:59:32Z)
```

```
$ kubectl exec -it cilium-zr7hd -n kube-system cilium service list
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
ID    Frontend             Service Type   Backend
1     10.16.0.1:443        ClusterIP      1 => 10.170.0.4:5443 (active)
                                          2 => 10.170.0.5:5443 (active)
2     10.16.0.10:53        ClusterIP      1 => 172.208.1.216:53 (active)
                                          2 => 172.208.1.96:53 (active)
3     10.16.0.10:9153      ClusterIP      1 => 172.208.1.216:9153 (active)
                                          2 => 172.208.1.96:9153 (active)
7     10.28.52.89:80       ClusterIP      1 => 10.170.0.5:4244 (active)
                                          2 => 10.170.0.4:4244 (active)
8     10.25.161.242:80     ClusterIP
9     10.23.120.195:80     ClusterIP
10    10.20.251.77:8080    ClusterIP      1 => 172.208.1.217:8080 (active)
288   10.19.182.12:80      ClusterIP      1 => 172.208.0.36:80 (active)
                                          2 => 172.208.1.28:80 (active)
289   0.0.0.0:31692        NodePort       1 => 172.208.0.36:80 (active)
                                          2 => 172.208.1.28:80 (active)
290   192.168.56.0:31692   NodePort       1 => 172.208.0.36:80 (active)
                                          2 => 172.208.1.28:80 (active)
291   10.170.0.4:31692     NodePort       1 => 172.208.0.36:80 (active)
                                          2 => 172.208.1.28:80 (active)
```

**Comment by aanm** [comment] 2022-11-19 00:54
Duplicate of https://github.com/cilium/cilium/issues/21060

**Closed as not planned by aanm** 2022-11-19 00:54 UTC
Labels: area/CI, ci/flake
