### ISSUE TITLE
Documentation: some dead links to commands generated via cmdref 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3756] opened 2018-04-16 19:00 UTC
If I want to access a specific command from the latest documentation for the [Command Reference](http://docs.cilium.io/en/latest/cmdref/cilium/), for instance [cilium bpf](http://docs.cilium.io/en/latest/cmdref/cilium_bpf/), the link works ( http://docs.cilium.io/en/latest/cmdref/cilium_bpf/ ) . However, if I go to the following link http://docs.cilium.io/en/latest/cmdref/cilium/ , none of the links under `SEE ALSO` work correctly.

**Comment by joestringer** [comment] 2018-04-16 23:12
Duplicate of https://github.com/cilium/cilium/issues/3260

**Closed as completed** 2018-04-17 15:31 UTC
Labels: kind/bug, area/documentation
