### ISSUE TITLE
BGP Control Plane not advertising IPv6 routes

### ISSUE THREAD

**Issue by denefoster** [cilium/cilium#30773] opened 2024-02-14 21:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When adding an IPv6 LoadBalancerIP to a service, a route should be pushed out via BGP to reach that IPv6. The route does not appear to be advertised upstream however:

```
kubectl -n static-sites get svc/nginx-svc

NAME        TYPE           CLUSTER-IP       EXTERNAL-IP                       PORT(S)        AGE
nginx-svc   LoadBalancer   10.106.239.113   192.168.239.37,fc00:ac2::ffff:3   80:31521/TCP   54m
```
The service acquires an address fine.

```
cilium bgp routes available ipv6 unicast
Node   VRouter   Prefix                 NextHop   Age      Attrs
cn1    65552     fc00:ac2::ffff:3/128   ::        21m41s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [fc00:ac2::ffff:3/128]}}]
cn2    65552     fc00:ac2::ffff:3/128   ::        21m41s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [fc00:ac2::ffff:3/128]}}]
```
The route appears as available

```
cilium bgp routes advertised ipv6 unicast
Node   VRouter   Peer   Prefix   NextHop   Age   Attrs
```

The IPv6 route does not get advertised. IPv4 seems to work fine:

```
cilium bgp routes advertised ipv4 unicast 
Node   VRouter   Peer           Prefix              NextHop        Age      Attrs
cn1    65552     192.168.1.11   192.168.239.37/32   192.168.1.51   39m49s   [{Origin: i} {AsPath: 65552} {Nexthop: 192.168.1.51}]
cn2    65552     192.168.1.11   192.168.239.1/32    192.168.1.52   39m49s   [{Origin: i} {AsPath: 65552} {Nexthop: 192.168.1.52}]
       65552     192.168.1.11   192.168.239.37/32   192.168.1.52   39m49s   [{Origin: i} {AsPath: 65552} {Nexthop: 192.168.1.52}]
```

The far side router also confirms no IPv6 routes received:
```
stick2# show ip bgp neigh cn2 received-routes
BGP table version is 3, local router ID is 192.168.1.11, vrf id 0
Default local pref 100, local AS 65554
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

    Network          Next Hop            Metric LocPrf Weight Path
 *> 192.168.239.1/32 192.168.1.52                           0 65552 i
 *> 192.168.239.37/32
                    192.168.1.52                           0 65552 i

Total number of prefixes 2
```

### Cilium Version

1.15.0

### Kernel Version

Linux cn1 6.1.77-flatcar #1 SMP PREEMPT_DYNAMIC Mon Feb 12 19:37:08 -00 2024 x86_64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz GenuineIntel GNU/Linux

### Kubernetes Version

Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1+k0s

### Sysdump

[cilium-sysdump-20240215-104858.zip](https://github.com/cilium/cilium/files/14288902/cilium-sysdump-20240215-104858.zip)

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denefoster** [comment] 2024-02-14 21:57
I should also add, cilium bap peers thinks it *is* advertising the route:

```
Node   Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
cn1    65552      65554     192.168.1.11   established     45m17s   ipv4/unicast   2          2
                                                                    ipv6/unicast   0          1
cn2    65552      65554     192.168.1.11   established     45m11s   ipv4/unicast   0          3
                                                                    ipv6/unicast   0          1
cn3    65552      65554     192.168.1.11   established     45m17s   ipv4/unicast   0          1
                                                                    ipv6/unicast   0          1
```

Note the ipv6/unicast line claiming 1 advertised route.

**Comment by YutaroHayakawa** [comment] 2024-02-15 00:52
At least, I couldn't reproduce this with our [dev environment](https://docs.cilium.io/en/latest/contributing/development/bgp_cplane/)

```
$ cilium version
cilium-cli: v0.15.20-10-g43fd0072 compiled with go1.21.6 on linux/amd64
cilium image (default): v1.14.5
cilium image (stable): v1.14.6
cilium image (running): 1.15.0
```

```
$ kc get svc httpbin
NAME      TYPE           CLUSTER-IP        EXTERNAL-IP                 PORT(S)        AGE
httpbin   LoadBalancer   fd00:10:2::3775   10.0.10.1,fd00:10:0:10::1   80:32217/TCP   5m10s
```

```
$ cilium bgp peers
Node                                Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
bgp-cplane-dev-dual-control-plane   65001      65000     10.0.1.1       established     5s       ipv4/unicast   3          2
                                                                                                 ipv6/unicast   3          2
bgp-cplane-dev-dual-worker          65002      65000     10.0.2.1       established     6s       ipv4/unicast   3          1
                                                                                                 ipv6/unicast   3          1                                                                                              ```

```
$ docker exec -it clab-bgp-cplane-dev-dual-router0 vtysh -c "show bgp ipv6 unicast"

   Network                                      Next Hop          Metric LocPrf Weight Path
*> fd00:10:0:10::1/128                          ::ffff:a00:102                       0 65001 i
```

Could you provide the following additional information?

1. Is your peer advertising IPv6 capability?
2. You make a peer with IPv4 and try to advertise the IPv6 route over it. This requires Extended NextHop Capability. Is your peer configured to enable it?

In Cisco-like routers, you can validate both with `show bgp neighbors`.

**Comment by denefoster** [comment] 2024-02-15 02:40
1. Is your peer advertising IPv6 capability?

Fun, no, it wasn't. Swapped out to a newer version of bird and it now is, and now have the routes as expected. Feel free to close!

**Comment by YutaroHayakawa** [comment] 2024-02-15 02:42
Great! Closing...

**Closed as completed by YutaroHayakawa** 2024-02-15 02:42 UTC
Labels: kind/bug, area/datapath, needs/triage, kind/community-report, area/bgp, feature/lb-ipam
