### ISSUE TITLE
CI: RuntimeMemcache Testing binary memcache Tests policy allowing all actions

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#11412] opened 2020-05-07 18:53 UTC
Seems like a test setup failure, memcache client container is not running, all memcache tests fail because of that.

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10121/

**Comment by christarazi** [comment] 2020-05-07 22:11
Ran this test focused locally 117 times without failure

**Comment by joestringer** [comment] 2020-05-07 23:10
Potential duplicate of https://github.com/cilium/cilium/issues/9812 ?

**Comment by christarazi** [comment] 2020-05-07 23:40
Ah, yes it is. I converted this issue from the "Disabled tests" project.

**Comment by joestringer** [comment] 2020-05-07 23:52
Cool, I marked the other one as duplicate and closed it.

**Comment by christarazi** [comment] 2020-05-19 20:34
Dropping this for now as it's not as high priority as https://github.com/cilium/cilium/issues/11512

**Closed as completed** 2022-01-07 23:17 UTC
