### ISSUE TITLE
The cluster is stuck on "Waiting for initial connection to be established"

### ISSUE THREAD

**Issue by farcaller** [cilium/cilium#26137] opened 2023-06-12 19:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cluster is stuck on waiting for the initial connection:

```
ClusterMesh:            1/2 clusters ready, 1 global-services
   ingress-istio: not-ready, 1 nodes, 0 identities, 7 services, 1 failures (last: 213h50m17s ago)
   └  Waiting for initial connection to be established
```

If I restart the cilium agent pod, it immediately gains connectivity so there's no networking issue. It just never retries on the initial failure, it seems.

The most easy way to repro it is to have 2 VMs with single-node clusters and restart them both at the same time. I can reliably get one of the clusters to not see the identities from the other one.

### Cilium Version

1.14.0-snapshot.3

### Kernel Version

5.15.11

### Kubernetes Version

v1.26.4+k3s1

### Relevant log output

```shell
There's nothing specific that would stand out in the logs so any advice on better troubleshooting this is welcome.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment] 2023-06-13 14:05
Hi @farcaller, could you please collect a sysdump on both clusters after observing the issue? I've tried reproducing it restarting the clustermesh-apiservers, but without luck (all connections got restarted correctly).

**Comment by farcaller** [comment] 2023-06-13 15:13
@giorio94 there you go: https://drive.google.com/file/d/10l8NmB25_3zgYX90KIwGBCFiTiS_BxIH/view?usp=sharing and https://drive.google.com/file/d/1lJLPmyPTKsXu9t6_NaCASNhd23GThIPB/view?usp=sharing.

Actually looking through the agent logs you can see something interesting (etcd auth issues), but just restarting the pod is enough to clear those, and FWIW the certs do not rotate in that window.

**Comment by giorio94** [comment] 2023-06-13 16:26
@farcaller It seems that the sysdumps are not accessible. Could you please check the sharing options.

**Comment by farcaller** [comment] 2023-06-13 16:31
My bad, fixed.

**Comment by giorio94** [comment] 2023-06-14 12:58
Looking at the sysdumps, my guess is that you hit https://github.com/cilium/cilium/issues/24692. TL;DR; When KPR is enabled, if a service with the same NodePort exists both in the local and the remote cluster, all traffic originating from inside the cluster and targeting the corresponding NodePort will be redirected to a local backend, regardless of whether the destination node belongs to the local or the remote cluster.

The logs contain a set of authentication errors because you are using the new `cluster` authentication mode (i.e., each cluster uses a different username for auth against remote etcd instances). When (due to the above bug) the agent connects to the local etcd instance rather than the remote one, authentication will fail, since the corresponding user is not present. If the legacy mode was used, the connection would be established successfully (since the username would be the same), but then the synchronization would not work properly (obviously).

You can workaround this issue [configuring a different clustermesh-apiserver NodePort](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L2664-L2671) in each cluster.

**Comment by farcaller** [comment] 2023-06-15 08:16
> You can workaround this issue [configuring a different clustermesh-apiserver NodePort](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L2664-L2671) in each cluster.

After making the ports different I no longer can reproduce the issue. I think that was it, thanks!

**Comment by giorio94** [comment] 2023-06-15 08:25
Perfect, thanks for the feedback. I'm closing this issue, but feel free to reopen it in case it reproduces again.

**Closed as completed by giorio94** 2023-06-15 08:25 UTC
Labels: kind/bug, kind/community-report, area/clustermesh

**Comment by giorio94** [comment] 2023-07-11 08:59
Hi @zeuikli, there are multiple reasons for the agents not being able to connect to a given remote cluster, including network connectivity issues or certificates mismatch. Please double-check that the given nodeport is reachable from the other clusters, and that there's no AWS firewall rule that prevents the communication.

**Comment by ikewabo** [comment] 2023-08-14 20:24
This below fixed it for me: 
kubectl rollout restart deployment clustermesh-apiserver  -n kube-system
