### ISSUE TITLE
CI: K8sFQDNTest Restart Cilium validate that FQDN is still working

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16723] opened 2021-07-01 04:43 UTC
### Test Name
```test-name
K8sFQDNTest Restart Cilium validate that FQDN is still working
```

### Failure Output
```failure-output
FAIL: Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-58757b7dd5-cjvcp: ;; connection timed out; no servers could be reached
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-58757b7dd5-cjvcp: ;; connection timed out; no servers could be reached

command terminated with exit code 1

Expected
    <*errors.errorString | 0xc0032341b0>: {
        s: "error looking up kube-dns.kube-system.svc.cluster.local from default/app2-58757b7dd5-cjvcp: ;; connection timed out; no servers could be reached\n\ncommand terminated with exit code 1\n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/fqdn.go:89
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output
Cilium pods: [cilium-64kjn cilium-lhsks]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                        Ingress   Egress
app1-6bf9bf9bd5-4ch7r                
app1-6bf9bf9bd5-sgznf                
app2-58757b7dd5-cjvcp                
app3-5d69599cdd-xjqc4                
coredns-755cd654d4-ph9g9             
Cilium agent 'cilium-64kjn': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 36 Failed 0
Cilium agent 'cilium-lhsks': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 25 Failed 0


```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
16:26:31 STEP: Running BeforeAll block for EntireTestsuite K8sFQDNTest
16:26:31 STEP: Ensuring the namespace kube-system exists
16:26:32 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
16:26:32 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
16:26:32 STEP: Installing Cilium
16:26:32 STEP: Waiting for Cilium to become ready
16:26:41 STEP: Validating if Kubernetes DNS is deployed
16:26:41 STEP: Checking if deployment is ready
16:26:41 STEP: Checking if kube-dns service is plumbed correctly
16:26:41 STEP: Checking if DNS can resolve
16:26:41 STEP: Checking if pods have identity
16:26:42 STEP: Kubernetes DNS is up and operational
16:26:42 STEP: Validating Cilium Installation
16:26:42 STEP: Performing Cilium controllers preflight check
16:26:42 STEP: Performing Cilium health check
16:26:42 STEP: Performing Cilium status preflight check
16:26:44 STEP: Performing Cilium service preflight check
16:26:44 STEP: Performing K8s service preflight check
16:26:44 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-64kjn': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

16:26:44 STEP: Performing Cilium status preflight check
16:26:44 STEP: Performing Cilium controllers preflight check
16:26:44 STEP: Performing Cilium health check
16:26:45 STEP: Performing Cilium service preflight check
16:26:45 STEP: Performing K8s service preflight check
16:26:45 STEP: Performing Cilium controllers preflight check
16:26:45 STEP: Performing Cilium health check
16:26:45 STEP: Performing Cilium status preflight check
16:26:50 STEP: Performing Cilium service preflight check
16:26:50 STEP: Performing K8s service preflight check
16:26:50 STEP: Performing Cilium controllers preflight check
16:26:50 STEP: Performing Cilium status preflight check
16:26:50 STEP: Performing Cilium health check
16:26:51 STEP: Performing Cilium service preflight check
16:26:51 STEP: Performing K8s service preflight check
16:26:51 STEP: Performing Cilium controllers preflight check
16:26:51 STEP: Performing Cilium health check
16:26:51 STEP: Performing Cilium status preflight check
16:26:52 STEP: Performing Cilium service preflight check
16:26:52 STEP: Performing K8s service preflight check
16:26:52 STEP: Performing Cilium controllers preflight check
16:26:52 STEP: Performing Cilium health check
16:26:52 STEP: Performing Cilium status preflight check
16:26:53 STEP: Performing Cilium service preflight check
16:26:53 STEP: Performing K8s service preflight check
16:26:53 STEP: Performing Cilium status preflight check
16:26:53 STEP: Performing Cilium controllers preflight check
16:26:53 STEP: Performing Cilium health check
16:26:54 STEP: Performing Cilium service preflight check
16:26:54 STEP: Performing K8s service preflight check
16:26:54 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-64kjn': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

16:26:54 STEP: Performing Cilium status preflight check
16:26:54 STEP: Performing Cilium controllers preflight check
16:26:54 STEP: Performing Cilium health check
16:26:56 STEP: Performing Cilium service preflight check
16:26:56 STEP: Performing K8s service preflight check
16:26:56 STEP: Performing Cilium controllers preflight check
16:26:56 STEP: Performing Cilium health check
16:26:56 STEP: Performing Cilium status preflight check
16:26:57 STEP: Performing Cilium service preflight check
16:26:57 STEP: Performing K8s service preflight check
16:26:57 STEP: Performing Cilium controllers preflight check
16:26:57 STEP: Performing Cilium health check
16:26:57 STEP: Performing Cilium status preflight check
16:26:58 STEP: Performing Cilium service preflight check
16:26:58 STEP: Performing K8s service preflight check
16:26:59 STEP: Waiting for cilium-operator to be ready
16:26:59 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
16:26:59 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
16:26:59 STEP: Applying demo manifest
16:26:59 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp")
16:27:06 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp") => <nil>
FAIL: Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-58757b7dd5-cjvcp: ;; connection timed out; no servers could be reached

command terminated with exit code 1

Expected
    <*errors.errorString | 0xc0032341b0>: {
        s: "error looking up kube-dns.kube-system.svc.cluster.local from default/app2-58757b7dd5-cjvcp: ;; connection timed out; no servers could be reached\n\ncommand terminated with exit code 1\n",
    }
to be nil
===================== TEST FAILED =====================
16:31:07 STEP: Running AfterFailed block for EntireTestsuite K8sFQDNTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-bmjjz           0/1     Running   0          47m     10.0.1.95       k8s2   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-hcx9p        1/1     Running   0          47m     10.0.1.105      k8s2   <none>           <none>
	 default             app1-6bf9bf9bd5-4ch7r              2/2     Running   0          4m10s   10.0.1.53       k8s1   <none>           <none>
	 default             app1-6bf9bf9bd5-sgznf              2/2     Running   0          4m10s   10.0.1.43       k8s1   <none>           <none>
	 default             app2-58757b7dd5-cjvcp              1/1     Running   0          4m10s   10.0.1.87       k8s1   <none>           <none>
	 default             app3-5d69599cdd-xjqc4              1/1     Running   0          4m10s   10.0.1.106      k8s1   <none>           <none>
	 kube-system         cilium-64kjn                       1/1     Running   0          4m37s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-lhsks                       1/1     Running   0          4m37s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-5dd4564f68-j6qxx   1/1     Running   0          4m37s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-5dd4564f68-j9p9k   1/1     Running   0          4m37s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         coredns-755cd654d4-ph9g9           1/1     Running   0          6m6s    10.0.0.205      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          50m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          50m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          50m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-j8xbl                   1/1     Running   0          49m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-qk62q                   1/1     Running   0          48m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          50m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-7spmb                 1/1     Running   0          47m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-q4vj8                 1/1     Running   0          47m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-jvkqz               1/1     Running   0          48m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-vb225               1/1     Running   0          48m     192.168.36.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-64kjn cilium-lhsks]
cmd: kubectl exec -n kube-system cilium-64kjn -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                   
	 1    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53        ClusterIP      1 => 10.0.0.205:53        
	 3    10.96.0.10:9153      ClusterIP      1 => 10.0.0.205:9153      
	 4    10.99.72.50:3000     ClusterIP                                
	 5    10.96.196.234:9090   ClusterIP      1 => 10.0.1.105:9090      
	 6    10.105.188.19:69     ClusterIP      1 => 10.0.1.53:69         
	                                          2 => 10.0.1.43:69         
	 7    10.105.188.19:80     ClusterIP      1 => 10.0.1.53:80         
	                                          2 => 10.0.1.43:80         
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-64kjn -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                              IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                    
	 354        Disabled           Disabled          4          reserved:health                                                          fd02::13c   10.0.1.98    ready   
	 1191       Disabled           Disabled          15376      k8s:id=app1                                                              fd02::1d0   10.0.1.53    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 1878       Disabled           Disabled          15376      k8s:id=app1                                                              fd02::116   10.0.1.43    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 2281       Disabled           Disabled          18873      k8s:id=app3                                                              fd02::16a   10.0.1.106   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 2578       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                                        ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                                 
	                                                            k8s:node-role.kubernetes.io/master                                                                        
	                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers                                               
	                                                            reserved:host                                                                                             
	 3938       Disabled           Disabled          43932      k8s:appSecond=true                                                       fd02::112   10.0.1.87    ready   
	                                                            k8s:id=app2                                                                                               
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-lhsks -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                   
	 1    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:9153      ClusterIP      1 => 10.0.0.205:9153      
	 3    10.96.0.10:53        ClusterIP      1 => 10.0.0.205:53        
	 4    10.99.72.50:3000     ClusterIP                                
	 5    10.96.196.234:9090   ClusterIP      1 => 10.0.1.105:9090      
	 6    10.105.188.19:80     ClusterIP      1 => 10.0.1.53:80         
	                                          2 => 10.0.1.43:80         
	 7    10.105.188.19:69     ClusterIP      1 => 10.0.1.53:69         
	                                          2 => 10.0.1.43:69         
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-lhsks -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                       
	 1697       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                                           ready   
	                                                            reserved:host                                                                                                
	 2363       Disabled           Disabled          4          reserved:health                                                              fd02::70   10.0.0.3     ready   
	 3175       Disabled           Disabled          18132      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   fd02::79   10.0.0.205   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                     
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                              
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                  
	                                                            k8s:k8s-app=kube-dns                                                                                         
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 

===================== Exiting AfterFailed =====================
16:31:20 STEP: Running AfterEach for block EntireTestsuite K8sFQDNTest
16:31:20 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|c0fd7095_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip]]


```
</details>

ZIP Links: 
<details><summary>Click to show.</summary>

 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/869/artifact/45b3af4b_K8sLRPTests_Checks_local_redirect_policy.zip/45b3af4b_K8sLRPTests_Checks_local_redirect_policy.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/869/artifact/7ee537f9_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip/7ee537f9_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/869/artifact/c0fd7095_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip/c0fd7095_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/869/artifact/test_results_Cilium-PR-K8s-1.21-kernel-4.9_869_BDD-Test-PR.zip/test_results_Cilium-PR-K8s-1.21-kernel-4.9_869_BDD-Test-PR.zip
 
</details>

Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/869/

**Comment by aanm** [comment] 2021-07-01 04:46
Assigned Tom based on https://github.com/cilium/cilium/pull/16662#event-4963402990 and https://github.com/cilium/cilium/pull/16662#issuecomment-871913271

**Comment by pchaigno** [comment] 2021-07-01 10:08
Duplicate of https://github.com/cilium/cilium/issues/16717. @aanm Please check https://docs.google.com/spreadsheets/d/1o86z3zec53vTobY5DwtZSdGF6j-_6VSrIddXgF81t18/edit#gid=1572159041.

**Closed as completed by pchaigno** 2021-07-01 10:08 UTC
Labels: area/CI, ci/flake
