### ISSUE TITLE
Cilium connectivity test failure on pod-to-ingress-service

### ISSUE THREAD

**Issue by VxDlH** [cilium/cilium#28837] opened 2023-10-27 14:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,

 I systematically get the following error when I execute the following command `cilium connectivity test` on a fresh installation : 
```
[=] Test [pod-to-ingress-service]
.
  [-] Scenario [pod-to-ingress-service/pod-to-ingress-service]
  [.] Action [pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client2-59b578d4bb-s695h (10.244.3.165) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client2-59b578d4bb-s695h during action curl-0
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-0
  [.] Action [pod-to-ingress-service/pod-to-ingress-service/curl-1: cilium-test/client-78f9dffc84-vtpqr (10.244.3.158) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client-78f9dffc84-vtpqr during action curl-1
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-1
[=] Test [pod-to-ingress-service-deny-all]
..
[=] Test [pod-to-ingress-service-allow-ingress-identity]
.
  ℹ️  📜 Applying CiliumNetworkPolicy 'all-ingress-deny' to namespace 'cilium-test'..
  ℹ️  📜 Applying CiliumNetworkPolicy 'allow-from-cilium-ingress' to namespace 'cilium-test'..
  [-] Scenario [pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service]
  [.] Action [pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-0: cilium-test/client-78f9dffc84-vtpqr (10.244.3.158) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client-78f9dffc84-vtpqr during action curl-0
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-0
  [.] Action [pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-1: cilium-test/client2-59b578d4bb-s695h (10.244.3.165) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client2-59b578d4bb-s695h during action curl-1
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-1
  ℹ️  📜 Deleting CiliumNetworkPolicy 'all-ingress-deny' from namespace 'cilium-test'..
  ℹ️  📜 Deleting CiliumNetworkPolicy 'allow-from-cilium-ingress' from namespace 'cilium-test'..
```

SVC List

` kubectl -n cilium-test get svc`

```
NAME                             TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress-ingress-service   NodePort   10.110.72.120   <none>        80:31000/TCP,443:31001/TCP   61m
echo-other-node                  NodePort   10.109.38.91    <none>        8080:32195/TCP               61m
echo-same-node                   NodePort   10.104.47.13    <none>        8080:32119/TCP               61m

```

SVC Describe

`kubectl -n cilium-test describe svc/cilium-ingress-ingress-service`

```
Name:                     cilium-ingress-ingress-service
Namespace:                cilium-test
Labels:                   cilium.io/ingress=true
Annotations:              <none>
Selector:                 <none>
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.110.72.120
IPs:                      10.110.72.120
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  31000/TCP
Endpoints:                
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  31001/TCP
Endpoints:                
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
I see there are no endpoints. Is this normal? Maybe it's a headless svc ?

when i run this cmd

```
kubectl -n cilium-test exec -it pods/client2-59b578d4bb-s695h -- curl -w '%{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} ' --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80
```

i got
 
```
curl: (22) The requested URL returned error: 503
10.244.3.165:49284 -> 10.110.72.120:80 = 503 command terminated with exit code 22
```

**What to do to ensure that all tests pass ?**

### Cilium Version

cilium-cli: v0.15.11 compiled with go1.21.3 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.3
cilium image (running): 1.14.3

### Kernel Version

Linux: 6.1.58

`talosctl read /etc/os-release`
```
NAME="Talos"
ID=talos
VERSION_ID=v1.5.4
PRETTY_NAME="Talos (v1.5.4)"
HOME_URL="https://www.talos.dev/"
BUG_REPORT_URL="https://github.com/siderolabs/talos/issues"
VENDOR_NAME="Sidero Labs"
VENDOR_URL="https://www.siderolabs.com/"
```

### Kubernetes Version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

### Sysdump

[cilium-sysdump-20231027-161153.zip](https://github.com/cilium/cilium/files/13189835/cilium-sysdump-20231027-161153.zip)

### Relevant log output

```shell
ℹ️  Monitor aggregation detected, will skip some flow validation steps
✨ [vdk8s] Deploying echo-same-node service...
✨ [vdk8s] Deploying DNS test server configmap...
✨ [vdk8s] Deploying same-node deployment...
✨ [vdk8s] Deploying client deployment...
✨ [vdk8s] Deploying client2 deployment...
✨ [vdk8s] Deploying echo-other-node service...
✨ [vdk8s] Deploying other-node deployment...
✨ [host-netns] Deploying vdk8s daemonset...
✨ [host-netns-non-cilium] Deploying vdk8s daemonset...
✨ [vdk8s] Deploying echo-external-node deployment...
✨ [vdk8s] Deploying Ingress resource...
⌛ [vdk8s] Waiting for deployment cilium-test/client to become ready...
⌛ [vdk8s] Waiting for deployment cilium-test/client2 to become ready...
⌛ [vdk8s] Waiting for deployment cilium-test/echo-same-node to become ready...
⌛ [vdk8s] Waiting for deployment cilium-test/echo-other-node to become ready...
⌛ [vdk8s] Waiting for CiliumEndpoint for pod cilium-test/client-78f9dffc84-vtpqr to appear...
⌛ [vdk8s] Waiting for CiliumEndpoint for pod cilium-test/client2-59b578d4bb-s695h to appear...
⌛ [vdk8s] Waiting for pod cilium-test/client-78f9dffc84-vtpqr to reach DNS server on cilium-test/echo-same-node-749cbccd75-65bbs pod...
⌛ [vdk8s] Waiting for pod cilium-test/client2-59b578d4bb-s695h to reach DNS server on cilium-test/echo-same-node-749cbccd75-65bbs pod...
⌛ [vdk8s] Waiting for pod cilium-test/client-78f9dffc84-vtpqr to reach DNS server on cilium-test/echo-other-node-6887b5b99c-gfp66 pod...
⌛ [vdk8s] Waiting for pod cilium-test/client2-59b578d4bb-s695h to reach DNS server on cilium-test/echo-other-node-6887b5b99c-gfp66 pod...
⌛ [vdk8s] Waiting for pod cilium-test/client-78f9dffc84-vtpqr to reach default/kubernetes service...
⌛ [vdk8s] Waiting for pod cilium-test/client2-59b578d4bb-s695h to reach default/kubernetes service...
⌛ [vdk8s] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-6887b5b99c-gfp66 to appear...
⌛ [vdk8s] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-749cbccd75-65bbs to appear...
⌛ [vdk8s] Waiting for Service cilium-test/echo-other-node to become ready...
⌛ [vdk8s] Waiting for Service cilium-test/echo-other-node to be synchronized by Cilium pod kube-system/cilium-xg965
⌛ [vdk8s] Waiting for Service cilium-test/echo-same-node to become ready...
⌛ [vdk8s] Waiting for Service cilium-test/echo-same-node to be synchronized by Cilium pod kube-system/cilium-xg965
⌛ [vdk8s] Waiting for NodePort 10.0.0.37:32195 (cilium-test/echo-other-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.37:32119 (cilium-test/echo-same-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.21:32195 (cilium-test/echo-other-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.21:32119 (cilium-test/echo-same-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.29:32195 (cilium-test/echo-other-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.29:32119 (cilium-test/echo-same-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.40:32119 (cilium-test/echo-same-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.40:32195 (cilium-test/echo-other-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.26:32195 (cilium-test/echo-other-node) to become ready...
⌛ [vdk8s] Waiting for NodePort 10.0.0.26:32119 (cilium-test/echo-same-node) to become ready...
ℹ️  Skipping IPCache check
🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  Cilium version: 1.14.3
🏃 Running tests...
[=] Test [no-policies]
..................................
[=] Test [no-policies-extra]
....................
[=] Test [allow-all-except-world]
....................
[=] Test [client-ingress]
..
[=] Test [client-ingress-knp]
..
[=] Test [allow-all-with-metrics-check]
....
[=] Test [all-ingress-deny]
........
[=] Test [all-ingress-deny-knp]
........
[=] Test [all-egress-deny]
................
[=] Test [all-egress-deny-knp]
................
[=] Test [all-entities-deny]
........
[=] Test [cluster-entity]
..
[=] Test [host-entity]
..........
[=] Test [echo-ingress]
....
[=] Test [echo-ingress-knp]
....
[=] Test [client-ingress-icmp]
..
[=] Test [client-egress]
....
[=] Test [client-egress-knp]
....
[=] Test [client-egress-expression]
....
[=] Test [client-egress-expression-knp]
....
[=] Test [client-with-service-account-egress-to-echo]
....
[=] Test [client-egress-to-echo-service-account]
....
[=] Test [to-entities-world]
......
[=] Test [to-cidr-external]
....
[=] Test [to-cidr-external-knp]
....
[=] Test [echo-ingress-from-other-client-deny]
......
[=] Test [client-ingress-from-other-client-icmp-deny]
......
[=] Test [client-egress-to-echo-deny]
......
[=] Test [client-ingress-to-echo-named-port-deny]
....
[=] Test [client-egress-to-echo-expression-deny]
....
[=] Test [client-with-service-account-egress-to-echo-deny]
....
[=] Test [client-egress-to-echo-service-account-deny]
..
[=] Test [client-egress-to-cidr-deny]
....
[=] Test [client-egress-to-cidr-deny-default]
....
[=] Test [health]
.....
[=] Skipping Test [north-south-loadbalancing] (Feature node-without-cilium is disabled)
[=] Skipping Test [pod-to-pod-encryption] (Feature encryption-pod is disabled)
[=] Skipping Test [node-to-node-encryption] (Feature encryption-pod is disabled)
[=] Skipping Test [egress-gateway-excluded-cidrs] (Feature enable-ipv4-egress-gateway is disabled)
[=] Skipping Test [pod-to-node-cidrpolicy] (Feature cidr-match-nodes is disabled)
[=] Skipping Test [north-south-loadbalancing-with-l7-policy] (Feature node-without-cilium is disabled)
[=] Test [echo-ingress-l7]
............
[=] Test [echo-ingress-l7-named-port]
............
[=] Test [client-egress-l7-method]
............
[=] Test [client-egress-l7]
..........
[=] Test [client-egress-l7-named-port]
..........
[=] Skipping Test [client-egress-l7-tls-deny-without-headers] (Feature secret-backend-k8s is disabled)
[=] Skipping Test [client-egress-l7-tls-headers] (Feature secret-backend-k8s is disabled)
[=] Skipping Test [client-egress-l7-set-header] (Feature secret-backend-k8s is disabled)
[=] Skipping Test [echo-ingress-auth-always-fail] (Feature mutual-auth-spiffe is disabled)
[=] Skipping Test [echo-ingress-mutual-auth-spiffe] (Feature mutual-auth-spiffe is disabled)
[=] Test [pod-to-ingress-service]
.
  [-] Scenario [pod-to-ingress-service/pod-to-ingress-service]
  [.] Action [pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client2-59b578d4bb-s695h (10.244.3.165) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client2-59b578d4bb-s695h during action curl-0
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-0
  [.] Action [pod-to-ingress-service/pod-to-ingress-service/curl-1: cilium-test/client-78f9dffc84-vtpqr (10.244.3.158) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client-78f9dffc84-vtpqr during action curl-1
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-1
[=] Test [pod-to-ingress-service-deny-all]
..
[=] Test [pod-to-ingress-service-allow-ingress-identity]
.
  ℹ️  📜 Applying CiliumNetworkPolicy 'all-ingress-deny' to namespace 'cilium-test'..
  ℹ️  📜 Applying CiliumNetworkPolicy 'allow-from-cilium-ingress' to namespace 'cilium-test'..
  [-] Scenario [pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service]
  [.] Action [pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-0: cilium-test/client-78f9dffc84-vtpqr (10.244.3.158) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client-78f9dffc84-vtpqr during action curl-0
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-0
  [.] Action [pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-1: cilium-test/client2-59b578d4bb-s695h (10.244.3.165) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://cilium-ingress-ingress-service:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  
  
  📄 No flows recorded for peer cilium-test/client2-59b578d4bb-s695h during action curl-1
  📄 No flows recorded for peer cilium-test/cilium-ingress-ingress-service during action curl-1
  ℹ️  📜 Deleting CiliumNetworkPolicy 'all-ingress-deny' from namespace 'cilium-test'..
  ℹ️  📜 Deleting CiliumNetworkPolicy 'allow-from-cilium-ingress' from namespace 'cilium-test'..
[=] Test [dns-only]
..........
[=] Test [to-fqdns]
........

📋 Test Report
❌ 2/45 tests failed (4/323 actions), 11 tests skipped, 0 scenarios skipped:
Test [pod-to-ingress-service]:
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client2-59b578d4bb-s695h (10.244.3.165) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-1: cilium-test/client-78f9dffc84-vtpqr (10.244.3.158) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)
Test [pod-to-ingress-service-allow-ingress-identity]:
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-0: cilium-test/client-78f9dffc84-vtpqr (10.244.3.158) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-1: cilium-test/client2-59b578d4bb-s695h (10.244.3.165) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service:80)
connectivity test failed: 2 tests failed
```

### Anything else?

Cilium installation method : 

```
helm upgrade --install \
    cilium \
    cilium/cilium \
    --version ${CNI_CILIUM_VERSION} \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set bpf.autoMount.enabled=true \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 \
    --set bpf.masquerade=true \
    --set bandwidthManager.enabled=true \
    --set bandwidthManager.bbr=true \
    --set prometheus.enabled=true \
    --set operator.prometheus.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set hubble.enabled=true \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
    --set ingressController.enabled=true \
    --set ingressController.default=true \
    --set ingressController.loadbalancerMode=shared \
    --set loadBalancer.l7.backend=envoy \
    --set l2announcements.enabled=true \
    --set l2announcements.leaseDuration=3s \
    --set l2announcements.leaseRenewDeadline=1s \
    --set l2announcements.leaseRetryPeriod=200ms \
    --set k8sClientRateLimit.qps=${QPS} \
    --set k8sClientRateLimit.burst=${BURST} \
    --set envoy.enabled=true \
    --set envoy.prometheus.enabled=true \
    --set loadBalancer.algorithm=maglev \
    --set maglev.tableSize=65521 \
    --set maglev.hashSeed=${SEED} \
    --set autoDirectNodeRoutes=true \
    --set routingMode=native \
    --set ipv4NativeRoutingCIDR=10.0.0.0/8 \
    --set loadBalancer.mode=hybrid \
    --set tunnelProtocol=geneve \
    --set hostFirewall.enabled=true \
    --set policyEnforcementMode=default \
    --set debug.enabled=false \
    --set gatewayAPI.enabled=true \
    --set envoy.prometheus.serviceMonitor.enabled=true \
    --values <(cat <<EOF
ingressController:
  service:
    labels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
    annotations:
      io.cilium/lb-ipam-ips: 10.0.0.153
EOF
)
```

with 
```
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-gateway-pool
spec:
  disabled: false
  cidrs:
    - cidr: 10.0.0.152/30
  serviceSelector:
    matchLabels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ingress-gateway-pool-announcement-policy
spec:
  loadBalancerIPs: true
  interfaces:
  - eth0
  serviceSelector:
    matchLabels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincedihub** [comment] 2023-10-27 15:50
I don't think it's related, but you never know : 

![image](https://github.com/cilium/cilium/assets/5277569/2e9b54ac-e8ed-49b2-b225-a3b3604a0e50)

`k -n cilium-test describe pods/echo-external-node-669b679d`

```
Name:             echo-external-node-669b679d-whl4z
Namespace:        cilium-test
Priority:         0
Service Account:  echo-external-node
Node:             <none>
Labels:           external=echo
                  kind=echo-external-node
                  name=echo-external-node
                  pod-template-hash=669b679d
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/echo-external-node-669b679d
Containers:
  echo-external-node:
    Image:      quay.io/cilium/json-mock:v1.3.5@sha256:d5dfd0044540cbe01ad6a1932cfb1913587f93cac4f145471ca04777f26342a4
    Port:       8080/TCP
    Host Port:  8080/TCP
    Readiness:  http-get http://:8080/ delay=1s timeout=2s period=1s #success=1 #failure=3
    Environment:
      PORT:        8080
      NAMED_PORT:  http-8080
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-d9trl (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-d9trl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              cilium.io/no-schedule=true
Tolerations:                 op=Exists
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  30m (x21 over 130m)  default-scheduler  0/5 nodes are available: 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling..

```

**Comment by kid** [comment] 2023-11-01 16:39
Seems to be the same issue as #20942
I` faced the same issue today on a single node k3s cluster, when setting `routingMode: native`, traffic does not flow if the envoy proxy and the destination pod are on the same node
setting `routingMode: tunnel` fixes it for me
Same issue with the gateway api

**Comment by samos667** [comment] 2023-11-04 20:01
I can confirm this on 1.14.3 and 1.15.pre2, service mesh isn't compatible with native routing on my k3s single node.

Deployment that doesn't work:
``` bash
	--namespace kube-system \
	--set ipam.mode=cluster-pool \
	--set kubeProxyReplacement=true \
        --set k8sServiceHost=172.16.66.99 \
	--set k8sServicePort=6443 \
	--set hubble.relay.enabled=true \
	--set hubble.ui.enabled=true \
	--set hubble.peerService.clusterDomain=cluster \
	--set operator.replicas=1 \
	--set localRedirectPolicy=true \
	--set bpf.masquerade=true \
	--set bgpControlPlane.enabled=true \
	--set ipam.operator.clusterPoolIPv4PodCIDRList='10.66.0.0/16' \
	--set ipam.operator.clusterPoolIPv4MaskSize=18 \
	--set ingressController.enabled=true \
	--set ingressController.loadbalancerMode=shared \
        --set envoy.enabled=true \
	--set tunnel=disabled \
	--set routingMode=native \
	--set ipv4NativeRoutingCIDR=10.0.0.0/8 \
	--set autoDirectNodeRoutes=true
```

Deployment that works:
``` bash
helm install cilium cilium/cilium --version 1.14.3 \
	--namespace kube-system \
	--set ipam.mode=cluster-pool \
	--set kubeProxyReplacement=true \
	--set k8sServiceHost=172.16.66.99 \
	--set k8sServicePort=6443 \
	--set hubble.relay.enabled=true \
	--set hubble.ui.enabled=true \
	--set hubble.peerService.clusterDomain=cluster \
	--set operator.replicas=1 \
	--set localRedirectPolicy=true \
	--set bpf.masquerade=true \
	--set bgpControlPlane.enabled=true \
	--set ipam.operator.clusterPoolIPv4PodCIDRList='10.66.0.0/16' \
	--set ipam.operator.clusterPoolIPv4MaskSize=18 \
	--set ingressController.enabled=true \
	--set ingressController.loadbalancerMode=shared \
	--set envoy.enabled=true
```

With the 1st deployment connectivity test of "pod-to-ingress-service" failed.

And follow the documentation of [ingress/gateway](https://docs.cilium.io/en/stable/network/servicemesh/) usage doesn't work when requesting the external IP of ingress resulting by a 503 code.

Maybe is necessary to use [tunnel mode](https://docs.cilium.io/en/stable/network/concepts/routing/) for be able to use service mesh ?
![image](https://github.com/cilium/cilium/assets/50653464/cfa60373-6e3f-4362-b1f6-6700d00c28f3)

**Comment by hwaastad** [comment] 2023-11-12 16:14
Hi, not sure if its 100% the same, but I have almost similar setup:
1. CiliumBGPPeeringPolicy
2. CiliumLoadBalancerIPPool
3. Gateway API

For test, Im running only 1 BGP peer.
bpf.masquerade=true
routingMode=native
autoredirectroutes=true

Exposing a deployment with pods on every node, connections via a HTTPRoute works fine to all pods.
If I set bpf.hostLegacyRouting=false connections to pod running on the ingress/loadbalancer node is failing. Not sure how to debug this further.

**Comment by 0xAlcibiades** [comment] 2023-12-25 07:29
Seeing something very similar here as well.

**Comment by ahmedwarsama** [comment] 2024-01-09 16:10
I am seeing the exact same problem with cilium 1.14.4 (also tried 1.14.3). It works perfectly when the http traffic hits an envoy proxy that sits on a different node to the web server pod.

**Comment by ahmedwarsama** [comment] 2024-01-09 16:59
My current workaround is that i only enable bgp peering with the control plane nodes and not workers, so the external traffic is never routed to the nodes running the webserver pods...

**Comment by MagicRB** [comment] 2024-02-16 22:07
I am hitting the same issue on cilium 1.15.0 on NixOS with a single node k3s cluster.
cilium.yaml:

```yaml
bpf:
  masquerade: 'true'
cni:
  binPath: "/run/cilium/cni"
  install: true
containerRuntime:
  integration: containerd
envoy:
  enabled: 'true'
hubble:
  relay:
    enabled: 'true'
  ui:
    enabled: 'true'
ingressController:
  enabled: true
  loadbalancerMode: shared
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 22
    clusterPoolIPv4PodCIDRList:
    - 10.64.52.0/22
kubeProxyReplacement: true
localRedirectPolicy: 'true'
operator:
  replicas: 1
securityContext:
  privileged: true
```

k3s config, (it's Nix but close enough)
```nix
  {
    disable = [
      "traefik"
      "servicelb"
    ];
    cluster-cidr = "10.64.48.0/22";
    service-cidr = "10.64.48.0/23";
    flannel-iface = "eno1";
    container-runtime-endpoint = "unix:///run/containerd/containerd.sock";
    flannel-backend = "none";
    disable-network-policy = true;
    node-ip = "10.64.2.1";
    node-external-ip = "10.64.2.1";
    disable-kube-proxy = true;
  }
```

**Comment by zviratko** [comment] 2024-03-26 13:27
Same issue with Talos 1.6.6/1.6.7/1.7.0alpha1 and Cilium 1.15.2/1.16pre

How is this still not fixed??

**Comment by siddjellali** [comment] 2024-04-09 20:25
Up thanks 👍

**Comment by MagicRB** [comment] 2024-08-04 07:39
Maybe stale, but not fixed or commented on with a official workaround

**Comment by zviratko** [comment] 2024-08-04 09:53
> Maybe stale, but not fixed or commented on with a official workaround, if only i knew how to remove the label

Not exactly
https://github.com/cilium/cilium/commit/c67cf2dc0206357f79087249ab5fa48cf69bb26d

But it's sad that with so many people hitting this issue, it still doesn't have a real solution or a more visible acnkowledgment.

**Comment by MagicRB** [comment] 2024-08-04 10:16
Yeah it do be sad, made me switch to istio because I spent 4 days fighting cilium, meanwhile istio just worked tm. But not like I have the finances to donate to either, so I cannot complain too much :)

**Comment by joestringer** [comment] 2024-09-05 00:29
Is this only occurring in native routing mode? Is it because the Ingress IP is not routable on the underlying network? That would make sense why it could be solved with either tunneling mode, BGP or L2 announcements for Ingress IPs in the network.

**Comment by MagicRB** [comment] 2024-11-24 11:53
@hwaastad what environment are you on? Bare metal? Some cloud?

**Comment by hwaastad** [comment] 2024-11-24 12:12
> [@hwaastad](https://github.com/hwaastad) what environment are you on? Bare metal? Some cloud?

Hi,
Baremetal (Flatcar 4081.2.0),
k8s: v1.28.15+rke2r1

**Comment by sayboras** [comment] 2024-12-11 07:40
I think this should be fixed now. Closing the issue, feel free to re-open if it still happens.

Relates: https://github.com/cilium/cilium/pull/35418

**Closed as completed by sayboras** 2024-12-11 07:40 UTC
Labels: kind/bug, kind/community-report, area/agent, area/servicemesh
