### ISSUE TITLE
CI: ipset v7.5: The set with the given name does not exist

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#18787] opened 2022-02-11 14:40 UTC
### Test Name

```shell
K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining
```

### Failure Output

```shell
Found 1 k8s-app=cilium logs matching list of errors that must be investigated: level=error
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-K8s-1.16-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:427
Found 1 k8s-app=cilium logs matching list of errors that must be investigated:
level=error
/home/jenkins/workspace/Cilium-PR-K8s-1.16-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:425
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
⚠️  Found "level=error" in logs 2 times
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 2
⚠️  Number of "level=warning" in logs: 7
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Command execution failed
Failed to add IP to ipset cilium_node_set_v4
Unable to restore endpoint, ignoring
Found incomplete restore directory /var/run/cilium/state/433_next. Removing it...
ipset v7.5: The set with the given name does not exist
Cilium pods: [cilium-h5f72 cilium-kslcn]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::echo-c default::pod-to-a-allowed-cnp default::pod-to-a-denied-cnp default::pod-to-a-intra-node-proxy-egress-policy default::pod-to-a-multi-node-proxy-egress-policy default::pod-to-c-intra-node-proxy-to-proxy-policy default::pod-to-c-multi-node-proxy-to-proxy-policy default::pod-to-external-fqdn-allow-google-cnp 
Endpoint Policy Enforcement:
Pod                                                          Ingress   Egress
echo-b-6c864d75d7-snsjh                                                
echo-c-688dcdfd44-rwdfg                                                
pod-to-a-57c7db48fd-ljt2r                                              
pod-to-a-allowed-cnp-548f548798-lrjq2                                  
pod-to-b-multi-node-headless-595bf6dfb-xdwfl                           
pod-to-c-intra-node-proxy-to-proxy-policy-5b6c8c6ddd-2mt6l             
pod-to-b-intra-node-hostport-5c58cb8758-tfhgf                          
pod-to-c-multi-node-proxy-ingress-policy-749956dc6d-252l7              
pod-to-c-multi-node-proxy-to-proxy-policy-75dc998c79-wm2kl             
pod-to-external-1111-694c4c87dd-dcq2b                                  
pod-to-external-fqdn-allow-google-cnp-7b6c5d747b-7x8z8                 
echo-a-6954f488f5-h7586                                                
pod-to-a-denied-cnp-64b85f46b8-p486h                                   
pod-to-a-multi-node-proxy-egress-policy-5466dc57db-s59tf               
pod-to-b-intra-node-nodeport-7b59546c64-nhvv9                          
pod-to-b-multi-node-hostport-869554778-kkbh8                           
pod-to-b-multi-node-nodeport-658b99d8-f9bqh                            
pod-to-c-intra-node-proxy-ingress-policy-64c77b5979-p7mbn              
pod-to-a-intra-node-proxy-egress-policy-7f46cf4857-mqq92               
pod-to-b-multi-node-clusterip-6c74fdb4b8-mt7pn                         
coredns-8cfc78c54-8z922                                                
Cilium agent 'cilium-h5f72': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 75 Failed 0
Cilium agent 'cilium-kslcn': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 70 Failed 0
```

### Standard Error

```shell
06:46:48 STEP: Running BeforeAll block for EntireTestsuite K8sConformance Portmap Chaining
06:46:48 STEP: Ensuring the namespace kube-system exists
06:46:48 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
06:46:48 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
06:46:48 STEP: Deleting pods [deathstar-6dbf86fd5c-djnpk,deathstar-6dbf86fd5c-hqxgw,deathstar-6dbf86fd5c-j2rdz,spaceship-6d9c645dc7-7j74v,spaceship-6d9c645dc7-d8rbp,spaceship-6d9c645dc7-mk6w5,spaceship-6d9c645dc7-s4rpj,xwing-7969df96d4-9n6tz,xwing-7969df96d4-gdtl4,xwing-7969df96d4-z7hkk] in namespace default
06:46:48 STEP: Waiting for 10 deletes to return (deathstar-6dbf86fd5c-djnpk,deathstar-6dbf86fd5c-hqxgw,deathstar-6dbf86fd5c-j2rdz,spaceship-6d9c645dc7-7j74v,spaceship-6d9c645dc7-d8rbp,spaceship-6d9c645dc7-mk6w5,spaceship-6d9c645dc7-s4rpj,xwing-7969df96d4-9n6tz,xwing-7969df96d4-gdtl4,xwing-7969df96d4-z7hkk)
06:46:48 STEP: Deleting cep [deathstar-6dbf86fd5c-djnpk,deathstar-6dbf86fd5c-hqxgw,deathstar-6dbf86fd5c-j2rdz,spaceship-6d9c645dc7-7j74v,spaceship-6d9c645dc7-d8rbp,spaceship-6d9c645dc7-mk6w5,spaceship-6d9c645dc7-s4rpj,xwing-7969df96d4-9n6tz,xwing-7969df96d4-gdtl4,xwing-7969df96d4-z7hkk] in namespace default
06:46:48 STEP: Waiting for 10 deletes to return (deathstar-6dbf86fd5c-djnpk,deathstar-6dbf86fd5c-hqxgw,deathstar-6dbf86fd5c-j2rdz,spaceship-6d9c645dc7-7j74v,spaceship-6d9c645dc7-d8rbp,spaceship-6d9c645dc7-mk6w5,spaceship-6d9c645dc7-s4rpj,xwing-7969df96d4-9n6tz,xwing-7969df96d4-gdtl4,xwing-7969df96d4-z7hkk)
06:46:58 STEP: Unable to delete pods xwing-7969df96d4-gdtl4 with 'kubectl -n default delete pods xwing-7969df96d4-gdtl4': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "xwing-7969df96d4-gdtl4" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods xwing-7969df96d4-z7hkk with 'kubectl -n default delete pods xwing-7969df96d4-z7hkk': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "xwing-7969df96d4-z7hkk" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods spaceship-6d9c645dc7-mk6w5 with 'kubectl -n default delete pods spaceship-6d9c645dc7-mk6w5': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "spaceship-6d9c645dc7-mk6w5" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods spaceship-6d9c645dc7-s4rpj with 'kubectl -n default delete pods spaceship-6d9c645dc7-s4rpj': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "spaceship-6d9c645dc7-s4rpj" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods xwing-7969df96d4-9n6tz with 'kubectl -n default delete pods xwing-7969df96d4-9n6tz': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "xwing-7969df96d4-9n6tz" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods spaceship-6d9c645dc7-7j74v with 'kubectl -n default delete pods spaceship-6d9c645dc7-7j74v': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "spaceship-6d9c645dc7-7j74v" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods deathstar-6dbf86fd5c-hqxgw with 'kubectl -n default delete pods deathstar-6dbf86fd5c-hqxgw': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "deathstar-6dbf86fd5c-hqxgw" deleted
	 
Stderr:
 	 

06:46:58 STEP: Unable to delete pods spaceship-6d9c645dc7-d8rbp with 'kubectl -n default delete pods spaceship-6d9c645dc7-d8rbp': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "spaceship-6d9c645dc7-d8rbp" deleted
	 
Stderr:
 	 

06:46:58 STEP: Installing Cilium
06:46:59 STEP: Waiting for Cilium to become ready
06:47:14 STEP: Validating if Kubernetes DNS is deployed
06:47:14 STEP: Checking if deployment is ready
06:47:14 STEP: Checking if kube-dns service is plumbed correctly
06:47:14 STEP: Checking if pods have identity
06:47:14 STEP: Checking if DNS can resolve
06:47:18 STEP: Kubernetes DNS is up and operational
06:47:18 STEP: Validating Cilium Installation
06:47:18 STEP: Performing Cilium health check
06:47:18 STEP: Performing Cilium status preflight check
06:47:18 STEP: Performing Cilium controllers preflight check
06:47:19 STEP: Performing Cilium service preflight check
06:47:19 STEP: Performing K8s service preflight check
06:47:19 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-h5f72': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

06:47:19 STEP: Performing Cilium controllers preflight check
06:47:19 STEP: Performing Cilium status preflight check
06:47:19 STEP: Performing Cilium health check
06:47:20 STEP: Performing Cilium service preflight check
06:47:20 STEP: Performing K8s service preflight check
06:47:20 STEP: Performing Cilium status preflight check
06:47:20 STEP: Performing Cilium controllers preflight check
06:47:20 STEP: Performing Cilium health check
06:47:21 STEP: Performing Cilium service preflight check
06:47:21 STEP: Performing K8s service preflight check
06:47:23 STEP: Waiting for cilium-operator to be ready
06:47:23 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
06:47:23 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
06:47:23 STEP: Making sure all endpoints are in ready state
06:47:24 STEP: WaitforPods(namespace="default", filter="")
06:47:42 STEP: WaitforPods(namespace="default", filter="") => <nil>
=== Test Finished at 2022-02-11T06:47:42Z====
06:47:42 STEP: Running JustAfterEach block for EntireTestsuite K8sConformance Portmap Chaining
FAIL: Found 1 k8s-app=cilium logs matching list of errors that must be investigated:
level=error
===================== TEST FAILED =====================
06:47:42 STEP: Running AfterFailed block for EntireTestsuite K8sConformance Portmap Chaining
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                                                         READY   STATUS    RESTARTS   AGE    IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-7fd557d749-mxtsb                                     0/1     Running   0          73m    10.0.1.109      k8s2   <none>           <none>
	 cilium-monitoring   prometheus-d87f8f984-2z92z                                   1/1     Running   0          73m    10.0.1.85       k8s2   <none>           <none>
	 default             echo-a-6954f488f5-h7586                                      1/1     Running   0          19s    10.0.0.33       k8s2   <none>           <none>
	 default             echo-b-6c864d75d7-snsjh                                      1/1     Running   0          19s    10.0.0.67       k8s2   <none>           <none>
	 default             echo-b-host-fdb854bd-sp7mb                                   1/1     Running   0          19s    192.168.56.12   k8s2   <none>           <none>
	 default             echo-c-688dcdfd44-rwdfg                                      1/1     Running   0          19s    10.0.0.196      k8s2   <none>           <none>
	 default             echo-c-host-5d6b79658c-vgcmk                                 1/1     Running   0          19s    192.168.56.12   k8s2   <none>           <none>
	 default             host-to-b-multi-node-clusterip-6868bbd4f8-tlkff              1/1     Running   0          17s    192.168.56.11   k8s1   <none>           <none>
	 default             host-to-b-multi-node-headless-69c9465576-lr7dn               1/1     Running   0          16s    192.168.56.11   k8s1   <none>           <none>
	 default             pod-to-a-57c7db48fd-ljt2r                                    1/1     Running   0          19s    10.0.0.42       k8s2   <none>           <none>
	 default             pod-to-a-allowed-cnp-548f548798-lrjq2                        1/1     Running   0          19s    10.0.1.197      k8s1   <none>           <none>
	 default             pod-to-a-denied-cnp-64b85f46b8-p486h                         1/1     Running   0          19s    10.0.0.1        k8s2   <none>           <none>
	 default             pod-to-a-intra-node-proxy-egress-policy-7f46cf4857-mqq92     2/2     Running   0          18s    10.0.0.139      k8s2   <none>           <none>
	 default             pod-to-a-multi-node-proxy-egress-policy-5466dc57db-s59tf     2/2     Running   0          18s    10.0.1.95       k8s1   <none>           <none>
	 default             pod-to-b-intra-node-hostport-5c58cb8758-tfhgf                1/1     Running   0          16s    10.0.0.147      k8s2   <none>           <none>
	 default             pod-to-b-intra-node-nodeport-7b59546c64-nhvv9                1/1     Running   0          16s    10.0.0.128      k8s2   <none>           <none>
	 default             pod-to-b-multi-node-clusterip-6c74fdb4b8-mt7pn               1/1     Running   0          17s    10.0.1.143      k8s1   <none>           <none>
	 default             pod-to-b-multi-node-headless-595bf6dfb-xdwfl                 1/1     Running   0          17s    10.0.1.31       k8s1   <none>           <none>
	 default             pod-to-b-multi-node-hostport-869554778-kkbh8                 1/1     Running   0          16s    10.0.1.23       k8s1   <none>           <none>
	 default             pod-to-b-multi-node-nodeport-658b99d8-f9bqh                  1/1     Running   0          16s    10.0.1.250      k8s1   <none>           <none>
	 default             pod-to-c-intra-node-proxy-ingress-policy-64c77b5979-p7mbn    2/2     Running   0          18s    10.0.0.50       k8s2   <none>           <none>
	 default             pod-to-c-intra-node-proxy-to-proxy-policy-5b6c8c6ddd-2mt6l   2/2     Running   0          17s    10.0.0.151      k8s2   <none>           <none>
	 default             pod-to-c-multi-node-proxy-ingress-policy-749956dc6d-252l7    2/2     Running   0          18s    10.0.1.28       k8s1   <none>           <none>
	 default             pod-to-c-multi-node-proxy-to-proxy-policy-75dc998c79-wm2kl   2/2     Running   0          17s    10.0.1.135      k8s1   <none>           <none>
	 default             pod-to-external-1111-694c4c87dd-dcq2b                        1/1     Running   0          19s    10.0.1.52       k8s1   <none>           <none>
	 default             pod-to-external-fqdn-allow-google-cnp-7b6c5d747b-7x8z8       1/1     Running   0          18s    10.0.1.105      k8s1   <none>           <none>
	 kube-system         cilium-h5f72                                                 1/1     Running   0          44s    192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-kslcn                                                 1/1     Running   0          44s    192.168.56.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-c997568f4-h9h66                              1/1     Running   0          44s    192.168.56.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-c997568f4-qbp25                              1/1     Running   0          44s    192.168.56.12   k8s2   <none>           <none>
	 kube-system         coredns-8cfc78c54-8z922                                      1/1     Running   0          109s   10.0.0.250      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                                                    1/1     Running   0          74m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                                          1/1     Running   0          74m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1                                 1/1     Running   0          74m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-dqhxv                                             1/1     Running   0          75m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-drkpj                                             1/1     Running   0          74m    192.168.56.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1                                          1/1     Running   0          75m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-lqs2m                                           1/1     Running   0          73m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-wpcdt                                           1/1     Running   0          73m    192.168.56.12   k8s2   <none>           <none>
	 kube-system         registry-adder-7ns49                                         1/1     Running   0          73m    192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-krg66                                         1/1     Running   0          73m    192.168.56.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-h5f72 cilium-kslcn]
cmd: kubectl exec -n kube-system cilium-h5f72 -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                          IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                               
	 51         Disabled           Disabled          46579      k8s:io.cilium.k8s.policy.cluster=default             fd02::1d   10.0.0.33    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=echo-a                                                                      
	 211        Disabled           Enabled           27101      k8s:io.cilium.k8s.policy.cluster=default             fd02::35   10.0.0.151   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-c-intra-node-proxy-to-proxy-policy                                   
	 240        Disabled           Enabled           27728      k8s:io.cilium.k8s.policy.cluster=default             fd02::49   10.0.0.139   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-a-intra-node-proxy-egress-policy                                     
	 259        Disabled           Disabled          25626      k8s:io.cilium.k8s.policy.cluster=default             fd02::f    10.0.0.67    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=echo-b                                                                      
	 611        Disabled           Enabled           36713      k8s:io.cilium.k8s.policy.cluster=default             fd02::74   10.0.0.1     ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-a-denied-cnp                                                         
	 635        Disabled           Disabled          9154       k8s:io.cilium.k8s.policy.cluster=default             fd02::6f   10.0.0.50    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-c-intra-node-proxy-ingress-policy                                    
	 817        Disabled           Disabled          25301      k8s:io.cilium.k8s.policy.cluster=default             fd02::47   10.0.0.42    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-a                                                                    
	 1011       Disabled           Disabled          39744      k8s:io.cilium.k8s.policy.cluster=default             fd02::af   10.0.0.147   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-b-intra-node-hostport                                                
	 1341       Enabled            Disabled          32221      k8s:io.cilium.k8s.policy.cluster=default             fd02::92   10.0.0.196   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=echo-c                                                                      
	 1503       Disabled           Disabled          23713      k8s:io.cilium.k8s.policy.cluster=default             fd02::96   10.0.0.128   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                              
	                                                            k8s:name=pod-to-b-intra-node-nodeport                                                
	 1900       Disabled           Disabled          48647      k8s:io.cilium.k8s.policy.cluster=default             fd02::7c   10.0.0.250   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                      
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                          
	                                                            k8s:k8s-app=kube-dns                                                                 
	 2204       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                   ready   
	                                                            reserved:host                                                                        
	 3532       Disabled           Disabled          4          reserved:health                                      fd02::4f   10.0.0.93    ready   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-kslcn -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                          IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                
	 26         Disabled           Disabled          25745      k8s:io.cilium.k8s.policy.cluster=default             fd02::178   10.0.1.28    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-c-multi-node-proxy-ingress-policy                                     
	 28         Disabled           Enabled           30326      k8s:io.cilium.k8s.policy.cluster=default             fd02::1c2   10.0.1.95    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-a-multi-node-proxy-egress-policy                                      
	 152        Disabled           Disabled          36898      k8s:io.cilium.k8s.policy.cluster=default             fd02::11b   10.0.1.143   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-b-multi-node-clusterip                                                
	 235        Disabled           Disabled          48891      k8s:io.cilium.k8s.policy.cluster=default             fd02::1e5   10.0.1.23    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-b-multi-node-hostport                                                 
	 619        Disabled           Disabled          4          reserved:health                                      fd02::165   10.0.1.10    ready   
	 1484       Disabled           Enabled           11502      k8s:io.cilium.k8s.policy.cluster=default             fd02::1ae   10.0.1.197   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-a-allowed-cnp                                                         
	 1490       Disabled           Disabled          7362       k8s:io.cilium.k8s.policy.cluster=default             fd02::1a7   10.0.1.52    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-external-1111                                                         
	 1492       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                    ready   
	                                                            k8s:node-role.kubernetes.io/master                                                    
	                                                            reserved:host                                                                         
	 1779       Disabled           Disabled          27176      k8s:io.cilium.k8s.policy.cluster=default             fd02::112   10.0.1.250   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-b-multi-node-nodeport                                                 
	 2319       Disabled           Enabled           31716      k8s:io.cilium.k8s.policy.cluster=default             fd02::1cf   10.0.1.105   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-external-fqdn-allow-google-cnp                                        
	 2846       Disabled           Disabled          23053      k8s:io.cilium.k8s.policy.cluster=default             fd02::1e4   10.0.1.31    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-b-multi-node-headless                                                 
	 3786       Disabled           Enabled           64472      k8s:io.cilium.k8s.policy.cluster=default             fd02::177   10.0.1.135   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                               
	                                                            k8s:name=pod-to-c-multi-node-proxy-to-proxy-policy                                    
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
06:47:59 STEP: Running AfterEach for block EntireTestsuite K8sConformance Portmap Chaining
06:48:46 STEP: Running AfterEach for block EntireTestsuit
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/789/testReport/junit/Suite-k8s-1/16/K8sConformance_Portmap_Chaining_Check_connectivity_check_compliance_with_portmap_chaining/
- ZIP file(s): 
[f3a59c11_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip](https://github.com/cilium/cilium/files/8049384/f3a59c11_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip)

### Anything else?

relevant log messages:
```
2022-02-11T06:47:09.575968003Z level=debug msg="Adding IP to ipset cilium_node_set_v4" ipAddr=192.168.56.12 subsys=iptables
2022-02-11T06:47:09.581847559Z level=error msg="Command execution failed" cmd="[ipset add cilium_node_set_v4 192.168.56.12 -exist]" error="exit status 1" subsys=iptables
2022-02-11T06:47:09.581993756Z level=warning msg="ipset v7.5: The set with the given name does not exist" subsys=iptables
2022-02-11T06:47:09.582105371Z level=error msg="Failed to add IP to ipset cilium_node_set_v4" error="exit status 1" ipAddr=192.168.56.12 subsys=iptables
```

**Comment by pchaigno** [comment] 2022-02-11 16:40
I think this is caused by a race between `AddToNodeIpset()` and `removeRulesAndIpsets()`.

These two functions are called from the agent with the following summarized stack trace:
```
runDaemon()
- NewDameon()
  - InitK8sSubsystem()
    - EnableK8sWatcher()
      * ciliumNodeInit()
        - NodeUpdated()
          - iptables.AddToNodeIpset()
  [...]
  - d.init()
    - d.Datapath().Loader().Reinitialize()
      - InstallRules()
        - removeRulesAndIpsets()
```
The initialization of k8s watchers uses goroutines so both function may execute at the same time.

`AddToNodeIpset` creates the ipset then adds the given IP address to that ipset. At the same time, `InstallRules` renames ipsets to a backup name, creates new ipsets, and removes the backups. Depending on timings, `AddToNodeIpset` may therefore attempt to add IPs to a nonexistent ipset.

This is made worse by the fact that `AddToNodeIpset` is called when we shouldn't need an ipset (when tunneling is enabled), in which case `InstallRules` simply removes the old ipsets without creating new ones.

I think we can fix this without introducing new locking:
- [ ] Fix the bug to call `AddToNodeIpset` only if ipsets are actually needed, i.e. if tunneling is disabled.
- [ ] Modify `InstallRules` to remove ipsets only if they are not needed anymore. This recreation with a backup system makes sense for iptables rules because we may need to change the rules depending on configuration. But for ipsets, it's much simpler: either we use it or not; the contents don't change based on configuration.

**Comment by pchaigno** [comment] 2022-03-13 14:30
The two pull requests mentioned above have been merged. This can be closed.

**Closed as completed by pchaigno** 2022-03-13 14:30 UTC
Labels: area/CI, area/datapath, ci/flake
