### ISSUE TITLE
can i pin the ip of the pod？

### ISSUE THREAD

**Issue by ChainsDW** [cilium/cilium#19182] opened 2022-03-18 07:33 UTC
I want to pin my pod's ip through cilium, but I don't know how to do it. can someone help me

**Comment by aanm** [comment] 2022-03-22 21:45
No, it's currently not possible. Closing this issue since it's a duplicate of https://github.com/cilium/cilium/issues/17026

**Closed as completed by aanm** 2022-03-22 21:45 UTC
