### ISSUE TITLE
kube-proxy-replacement: drop LB traffic which is not in the service definition

### ISSUE THREAD

**Issue by travisghansen** [cilium/cilium#14176] opened 2020-11-25 17:53 UTC
## Bug report

I'm making ICMP requests to an LB IP (from a node external to the cluster) and the result is routing loop.

I'm running with metallb + bgp. In our scenario the primary router is `172.28.96.{9,10}`, a secondary router (what the nodes are peered to for metallb) is `172.28.96.32`, and the last node `172.28.43.62` is one of the cluster nodes.

`172.28.44.34` is a LB IP provisioned by metallb and is only running tcp ports 80 and 443.

MetalLB advertises /32 routes to the secondary router and the secondary router advertises a full/single /24 to the primary router.
```
tracepath 172.28.44.34
 1?: [LOCALHOST]                                         pmtu 1500
 1:  172.28.96.9                                           1.170ms 
 1:  172.28.96.9                                         112.167ms 
 2:  172.28.96.32                                          0.249ms asymm  1 
 3:  172.28.43.62                                          0.361ms asymm  2 
 4:  172.28.43.9                                           1.722ms asymm  1 
 5:  172.28.96.32                                          0.311ms asymm  1 
 6:  172.28.43.62                                          0.306ms asymm  2 
 7:  172.28.43.10                                          0.767ms asymm  1 
 8:  172.28.96.32                                          0.462ms asymm  1 
 9:  172.28.43.62                                          0.410ms asymm  2 
10:  172.28.43.10                                          1.804ms asymm  1 
11:  172.28.96.32                                          0.642ms asymm  1 
12:  172.28.43.62                                          0.644ms asymm  2 
13:  172.28.43.10                                          2.213ms asymm  1 
14:  172.28.96.32                                          0.651ms asymm  1 
15:  172.28.43.62                                          0.663ms asymm  2 
16:  172.28.43.10                                          2.159ms asymm  1 
17:  172.28.96.32                                          0.734ms asymm  1 
18:  172.28.43.62                                          0.772ms asymm  2 
19:  172.28.43.9                                           3.249ms asymm  1 
20:  172.28.96.32                                          1.194ms asymm  1 
21:  172.28.43.62                                          1.043ms asymm  2 
22:  172.28.43.9                                           1.352ms asymm  1 
23:  172.28.96.32                                          1.326ms asymm  1 
24:  172.28.43.62                                          1.141ms asymm  2 
25:  172.28.43.9                                           2.119ms asymm  1 
26:  172.28.96.32                                          1.439ms asymm  1 
27:  172.28.43.62                                          1.225ms asymm  2 
28:  172.28.43.10                                          1.640ms asymm  1 
29:  172.28.96.32                                          1.479ms asymm  1 
30:  172.28.43.62                                          1.290ms asymm  2 
```

**General Information**

- Cilium version (run `cilium version`) `1.8.3`
- Kernel version (run `uname -a`) `5.8.1-1.el7.elrepo.x86_64`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) `kube 1.18.6`
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

helm values

```
# if the configmap is updated cilium will *NOT* pickup the changes automatically and must be forced to restart
# kubectl -n kube-system patch ds cilium -p '{"spec":{"template":{"spec":{"containers":[{"name":"cilium-agent","env":[{"name":"RESTART_","value":"'$(date +%s)'"}]}]}}}}'


# automatically restarts pods to ensure controlled by new CNI driver
operator:
  enabled: true

config:
  bpfMasquerade: false
  ipam: kubernetes

global:
  k8sServiceHost: "127.0.0.1"
  k8sServicePort: "6443"
  # https://docs.cilium.io/en/v1.8/concepts/networking/masquerading/
  nativeRoutingCIDR: "10.42.0.0/16"
  ipam:
    operator:
      clusterPoolIPv4PodCIDR: "10.42.0.0/16"

  enableXTSocketFallback: false

  #tag: "latest"
  #pullPolicy: "Always"

  prometheus:
    enabled: true

  bpf:
    preallocateMaps: true
    waitForMount: true

  # disabling not ready for primetime yet
  # https://github.com/cilium/cilium/projects/93#column-7748410
  installIptablesRules: true

  # https://docs.cilium.io/en/latest/architecture/#arch-guide
  # https://cilium.io/blog/2019/02/12/cilium-14/#sockmap-bpf-based-sidecar-acceleration-alpha
  # https://www.youtube.com/watch?v=ER9eIXL2_14
  sockops:
    #enabled: true
    enabled: true

  k8s:
    # cilium pods will not start on node until pod CIDR has been assigned
    requireIPv4PodCIDR: true

  # eliminates need for any kind of BGP stuff
  # automatically addes routes to each node
  autoDirectNodeRoutes: true

  tunnel: disabled
  kubeProxyReplacement: strict
  hostServices:
    enabled: true
  nodePort:
    enabled: true
    # dsr or snat
    mode: dsr
    #mode: snat
  hostPort:
    enabled: true
  externalIPs:
    enabled: true

  # dev purposes only
  cleanState: false
  cleanBpfState: false
```

Steps to reproduce are above. I've confirmed the behavior with several clusters using similar options. If you need further info just let me know.

I guess I'm not entirely sure what the behavior should be here, but on the surface my expectations are that if traffic arrives to the cluster for an LB IP to a port/protocol not defined in the service the node would simply drop the packet.

Thoughts?

**Comment by brb** [comment] 2020-11-25 18:25
This is a duplicate of https://github.com/cilium/cilium/issues/14118.

**Closed as completed by brb** 2020-11-25 18:25 UTC
Labels: kind/bug
