### ISSUE TITLE
Cluster service load balancing (php-fpm, fastcgi)

### ISSUE THREAD

**Issue by messiahUA** [cilium/cilium#10343] opened 2020-02-26 12:29 UTC
## Bug report

**General Information**

- Cilium version: 1.6.1 161ffdb46 2019-09-09T13:14:29-07:00 go version go1.12.8
- Kernel version: 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: kubernetes v1.15.9 (AWS kops with default cilium networking)

**How to reproduce the issue**

1. create php-fpm configmap (to enable status):
```
  wget https://raw.githubusercontent.com/messiahUA/cilium/master/www.conf
  kubectl create cm php-fpm-config --from-file=www.conf
```

2. create a deployment and a service:
```
  kubectl apply -f https://raw.githubusercontent.com/messiahUA/cilium/master/php-fpm.yaml
  kubectl apply -f https://raw.githubusercontent.com/messiahUA/cilium/master/php.yaml
```

3. run some quick&dirty pod to create a load and let it run for a few minutes:
```
  kubectl run debian --restart=Never --image=debian --command -- bash '-c' 'apt-get update && apt-get install -y libfcgi0ldbl && while true; do SCRIPT_FILENAME=/ REQUEST_URI=/ QUERY_STRING= REQUEST_METHOD=GET cgi-fcgi -bind -connect php:9090; done > /dev/null'
```

4. Scale the deployment and wait for a few minutes:
```
  kubectl scale --replicas=3 deploy/php-fpm
```

5. One can check the corresponding prometheus/grafana visualization for the metric _phpfpm_accepted_connections_total_ or manually scrape each pod and see such a picture:
![image](https://user-images.githubusercontent.com/3277444/75342880-f44db880-589f-11ea-875e-f6afa9c226b5.png)

As you can see two initial pods receive all the traffic and new pod receives almost none. If you will start a new pod to generate traffic it will correctly distribute it among the 3 php-fpm pods.

**Comment by messiahUA** [comment] 2020-02-26 13:26
Not sure what to grep exactly and which ports.

Here is a snippet of when everything is ok:
```
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:33068 service expires=1666732 RxPackets=0 RxBytes=293 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645132 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:33516 service expires=1666733 RxPackets=0 RxBytes=293 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645133 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:39646 service expires=1666662 RxPackets=0 RxBytes=293 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645062 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:39764 service expires=1666701 RxPackets=0 RxBytes=292 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645101 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:40132 service expires=1666702 RxPackets=0 RxBytes=292 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645102 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
```

After adding additional php-fpm pod:

```
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:40804 service expires=1667019 RxPackets=0 RxBytes=292 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645419 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:53974 service expires=1667080 RxPackets=0 RxBytes=292 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645480 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:58122 service expires=1667087 RxPackets=0 RxBytes=293 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645487 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:44616 service expires=1667064 RxPackets=0 RxBytes=293 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645464 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:48066 service expires=1667070 RxPackets=0 RxBytes=292 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645470 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
```

and one specific port from the first snippet:
```
TCP OUT 100.67.5.76:9090 -> 100.96.5.165:40132 service expires=1667211 RxPackets=0 RxBytes=292 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=1645611 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=48 SourceSecurityID=0 
```

There are on average 450 records.

**Comment by brb** [comment] 2020-02-27 11:30
- Check how many CT `TCP OUT` entries there are for the client pod IPs vs how many requests you made.
- Does your client load generator runs long enough so that the third service pod gets a chance to receive some requests?

**Comment by messiahUA** [comment] 2020-02-27 11:48
100 requests = 0-1 CT record
1000 requests = 12-44 CT records

I'm specifying ranges because this number changes on each execution.

As for the second question: long enough is relative, but I suppose the answer is yes. As you can see on the screenshot in the head post it was 15 minutes and nothing changed. And there is such a problem on the production cluster where this can last for hours. In any case, I think this is fundamental functionality and it should not take any time to "warm-up" or whatever, because it is critical to distribute the load on scaling (otherwise there is no point).

**Comment by brb** [comment] 2020-02-27 12:38
> 100 requests = 0-1 CT record
> 1000 requests = 12-44 CT records

OK, then the problem is indeed the port reuse which leads to using the same service endpoints. Does `cgi-fcgi` tries to set itself a source port, or it asks the kernel to pick?

**Comment by messiahUA** [comment] 2020-02-27 13:42
> Does cgi-fcgi tries to set itself a source port, or it asks the kernel to pick it?

Unfortunately, I don't know. How can I check this?

bpf-ct-timeout-service-tcp and conntrack-gc-interval set to 1m and restarted all pods: traffic almost evens out but only after 20 minutes approximately

![Screenshot from 2020-02-27 15-41-25](https://user-images.githubusercontent.com/3277444/75450519-a99f6f80-5977-11ea-840b-2aed77542861.png)

**Comment by brb** [comment] 2020-02-27 13:46
> Unfortunately, I don't know. How can I check this?
Either check the source code or run strace and inspect `bind(2)` parameters.

**Comment by messiahUA** [comment] 2020-02-27 13:49
I see socket and connect only:
```
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(9090), sin_addr=inet_addr("100.67.5.76")}, 16) = 0
```

**Comment by brb** [comment] 2020-03-05 15:36
Another workaround is to use the host-reachable services feature which bypasses the problem.

**Comment by messiahUA** [comment] 2020-03-05 15:46
> 
> 
> Another workaround is to use the host-reachable services feature which bypasses the problem.

Do you mean headless service?

**Comment by brb** [comment] 2020-03-05 15:47
No, I meant: https://docs.cilium.io/en/v1.7/gettingstarted/host-services/.

**Comment by errordeveloper** [comment] 2020-11-10 12:01
@borkmann I can see you have a branch that references this, is something blocking completion? Also, a high-level summary of the issue would be quite helpful.

**Comment by ti-mo** [comment] 2021-08-12 13:29
Closing since this is well over a year old, has had a workaround suggested, and there's been a more recent case here (https://github.com/cilium/cilium/issues/14250) with more context.

Please ping if this needs to be re-opened, thanks!

**Closed as completed by ti-mo** 2021-08-12 13:29 UTC
Labels: needs/triage, kind/community-report, pinned
