### ISSUE TITLE
Egress bandwidth limits not enforced

### ISSUE THREAD

**Issue by bmcustodio** [cilium/cilium#16790] opened 2021-07-05 16:16 UTC
## Bug report

Egress bandwidth limits do not seem to be enforced on an EKS cluster in ENI mode:

```
(eks_bruno-eks-1) ➜  ~ kubectl exec netperf-client -- netperf -t TCP_MAERTS -H "${NETPERF_SERVER_IP}"
MIGRATED TCP MAERTS TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.100.101.98 (10.100.) port 0 AF_INET
Recv   Send    Send
Socket Socket  Message  Elapsed
Size   Size    Size     Time     Throughput
bytes  bytes   bytes    secs.    10^6bits/sec

131072  20480  20480    10.00    4851.91
```

The contents of `cilium-config` (not sure if important, but WireGuard was previously enabled in this cluster):

```
apiVersion: v1
data:
  auto-create-cilium-node-resource: "true"
  auto-direct-node-routes: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "1"
  cluster-name: bruno-eks-1
  custom-cni-conf: "false"
  debug: "false"
  devices: eth+
  disable-cnp-status-updates: "true"
  ec2-api-endpoint: ""
  egress-masquerade-interfaces: eth0
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-l7-proxy: "false"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-wireguard: "false"
  enable-xt-socket-fallback: "true"
  eni-tags: '{}'
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-metrics: dns:query;ignoreAAAA drop tcp flow icmp http
  hubble-metrics-server: :9091
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: kvstore
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: eni
  kube-proxy-replacement: disabled
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  proxy-prometheus-port: "9095"
  sidecar-istio-proxy-image: cilium/istio_proxy
  subnet-ids-filter: ""
  subnet-tags-filter: ""
  tunnel: disabled
  wait-bpf-mount: "false"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2021-07-05T10:19:18Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
  resourceVersion: "80027"
  uid: 7b975af1-93a0-4372-b88b-1d3f1a20993b
```

Info requested by @borkmann:

```
root@ip-10-100-1-82:/home/cilium# cilium bpf bandwidth list
IDENTITY   EGRESS BANDWIDTH (BitsPerSec)
1128       20M
root@ip-10-100-1-82:/home/cilium# tc filter show dev eth2 egress
root@ip-10-100-1-82:/home/cilium# tc filter show dev eth1 egress
root@ip-10-100-1-82:/home/cilium# tc filter show dev eth0 egress
```

**General Information**

- Cilium version (run `cilium version`)

```
Client: 1.10.2 319d2ac 2021-07-02T03:00:06+02:00 go version go1.16.5 linux/amd64
Daemon: 1.10.2 319d2ac 2021-07-02T03:00:06+02:00 go version go1.16.5 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux ip-10-100-1-82.eu-west-2.compute.internal 5.4.117-58.216.amzn2.x86_64 #1 SMP Tue May 11 20:50:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, ...)

EKS 1.20

```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

N/A

- Generate and upload a system zip:

N/A

**How to reproduce the issue**

1. Create an EKS cluster and deploy Cilium in ENI mode:

    ```
    helm upgrade --install cilium cilium/cilium --version 1.10.2 \
      --namespace kube-system \
      --set cluster.name="bruno-eks-1" \
      --set cluster.id="1" \
      --set egressMasqueradeInterfaces=eth0 \
      --set eni.enabled=true \
      --set hubble.listenAddress=":4244" \
      --set hubble.metrics.enabled="{dns:query;ignoreAAAA,drop,tcp,flow,icmp,http}" \
      --set hubble.metrics.serviceMonitor.enabled="false" \
      --set hubble.relay.enabled=true \
      --set hubble.ui.enabled=true \
      --set identityAllocationMode=kvstore \
      --set ipam.mode=eni \
      --set masquerade=false \
      --set nodeinit.enabled=true \
      --set prometheus.enabled=true \
      --set prometheus.serviceMonitor.enabled="false" \
      --set tunnel=disabled \
      --set l7Proxy=false \
      --set encryption.enabled=true \
      --set encryption.type=wireguard
    ```

1. Create the `netperf-server` and `netperf-client` pods according to https://github.com/cilium/cilium/pull/16783, and run the provided test commands.

**Comment by pchaigno** [comment] 2022-02-07 10:29
I've been able to reproduce and debug this issue. It's specific to EKS as far as I can see.

As shown by the `tc filter show` commands, the issue here is that the BPF program is not attached to the egress of the native devices. There are two reasons for that.

### Device Changes at Runtime
By default, in v1.10 and v1.11, device autodetection fails and finds a single interface, `eth0`.
```
level=info msg="Detected devices" devices="[eth0]" subsys=daemon
```
Unfortunately, traffic between pods on different nodes doesn't go through that interface, but through the other interfaces (eth1 and up). Passing something such as `devices=eth+` is not enough because on EKS interfaces are added and removed at runtime, as shown below:
```
level=info msg="  --devices='eth+'" subsys=daemon
level=info msg="Detected devices" devices="[eth0 eth1 eth2]" subsys=daemon
level=info msg="Setting qdisc to mq with fq leafs" device=eth0 subsys=bandwidth-manager
level=info msg="Setting qdisc to mq with fq leafs" device=eth1 subsys=bandwidth-manager
level=info msg="Setting qdisc to mq with fq leafs" device=eth2 subsys=bandwidth-manager
level=debug msg="Didn't find existing device" error="Link not found" subsys=cilium-health-launcher veth=cilium_health
level=debug msg="Didn't find existing device" error="Link not found" subsys=cilium-health-launcher veth=lxc_health
level=warning msg="Link does not exist" device=eth1 error="Link not found" subsys=datapath-loader
```
Interfaces eth0, eth1, and eth2 are initially found, but by the time the BPF programs are loaded, eth1 has been deleted. https://github.com/cilium/cilium/pull/17460 by @joamaki aims to solve this issue.

### Missing Egress Attachment
Even when the correct interfaces are detected (e.g., eth0 above), the BPF program is not attached to the egress of the interface, only to the ingress:
```
$ ks exec ds/cilium -- bpftool net | grep eth
eth0(2) clsact/ingress bpf_netdev_eth0.o:[from-netdev] id 1280
eth1(21) clsact/ingress bpf_netdev_eth1.o:[from-netdev] id 1287
```
This is because of [this code](https://github.com/cilium/cilium/blob/v1.11/pkg/datapath/loader/loader.go#L241), which we need to fix. I'll send a pull request for that.

**Comment by borkmann** [comment] 2022-02-07 14:43
> Interfaces eth0, eth1, and eth2 are initially found, but by the time the BPF programs are loaded, eth1 has been deleted. https://github.com/cilium/cilium/pull/17460 by @joamaki aims to solve this issue.

Yeah, we need to resume work on it as this is definitely needed with dynamic device additions. Agent needs to be aware when new devices come and go during runtime as well as when they down / up cycle.

> This is because of [this code](https://github.com/cilium/cilium/blob/v1.11/pkg/datapath/loader/loader.go#L241), which we need to fix. I'll send a pull request for that.

Thanks a ton!

**Comment by sergeyshevch** [comment] 2022-07-15 08:08
@bmcustodio @pchaigno Looks like this issue is solved and can be closed

**Comment by wer-anders** [comment] 2022-11-15 14:43
I still got the issue that bandwith limits are not enforced but on my **bare-metal** server. So far I figured out that this must be connected to wireguard encryption.
If I disable wireguard encryption, the netperf example from [Bandwidth Manager Cilium Documentation](https://docs.cilium.io/en/v1.12/gettingstarted/bandwidth-manager/) is working.
As soon as I enable wireguard encryption, pod to pod traffic is not limited anymore (I took care that the pods are running on different nodes). Traffic leaving the cluster is still limited.
So maybe not only all eth* interfaces must be included, but also the cilium_wg0?

My cluster is on Debian 11 with Kernel 5.10.0-18-amd64, k8s-v1.24.6 and Cilium v1.12.3

**Comment by pchaigno** [comment] 2022-11-15 16:29
>  So maybe not only all eth* interfaces must be included, but also the cilium_wg0?

That sounds like the likely cause, yes.

@wer-anders Could you open an issue (or even a PR if you know what to change) to track this issue with bandwidth manager + WireGuard? It's different from the present issue so I'd rather track it somewhere else and close this for clarity.

**Closed as completed** 2024-07-15 10:29 UTC
Labels: kind/bug, area/datapath, integration/cloud, feature/bandwidth-manager
