### ISSUE TITLE
Graceful shutdown not working when externalTrafficPolicy=Local or when replica count is 1 

### ISSUE THREAD

**Issue by jonahmurphy** [cilium/cilium#23744] opened 2023-02-14 15:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

0. Running in kube proxy replacement strict mode , with graceful termination enabled.
1.  Create a deployment and LoadBalancer service as per below examples
     - Service either has to have externalTrafficPolicy=Local, and only one pod is allowed to run on a node at a given time
     - Or if set to Cluster, the deployment must only have one replica running 
3. To simplify testing and debug, we connect directly to the nodePort for the service  and bypass the LB,
	-  send a message to verify connectivity
4. Delete the pod gracefully
5. Send another message over the existing connection whilst the pod is in a terminating state
7. Client gets a TCP RST. A tcpdump shows the RST originating from the nodeIP:nodePort

I've looked at hubble, and monitor logs, and neither show the packet that triggers the RST, nor are any drops shown.

```
----
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-service
  namespace: default
  labels:
    app: test-echo-server
spec:
  externalTrafficPolicy: Local 
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 5001
      protocol: TCP
      name: tcp
  selector:
    app: test-echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-echo-server
  namespace: default
  labels:
    app: test-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-echo-server
  template:
    metadata:
      labels:
        app: test-echo-server
    spec:
      terminationGracePeriodSeconds: 3600
      affinity:
        podAntiAffinity:                                 
          requiredDuringSchedulingIgnoredDuringExecution:   
          - topologyKey: kubernetes.io/hostname  
            labelSelector:                               
              matchLabels:                             
                app: test-echo-server
      containers:
        - name: echo-server
          image: "vhiribarren/echo-server:latest"
          ports:
            - name: tcp
              containerPort:  5001
              protocol: TCP
          lifecycle:
            preStop:
              exec: 
                command:
                  ['/bin/sh', '-c', 'echo preStop executing && sleep 3600']
```

### Cilium Version

Client: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64
Daemon: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64

### Kernel Version

Linux 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.23.5

### Sysdump

I can provide selective output from sysdump on request.

### Relevant log output

```shell
The following output and the log files were gathered after starting termination of the test pod, and before sending a packet which triggers the RST.

//NodePort=4300
>>kubectl exec -it -n kube-system cilium-xg5nt -- cilium service list | grep 4300

Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
                                                                                                                                                                                       431   10.241.93.59:4300      NodePort       1 => 172.18.2.158:5001 (terminating)
433   172.31.248.52:4300     NodePort       1 => 172.18.2.158:5001 (terminating)
435   0.0.0.0:4300           NodePort       1 => 172.18.2.158:5001 (terminating)
--------
// PodIP=172.18.2.158
>> kubectl exec -it -n kube-system cilium-xg5nt  -- cilium bpf ct list global | grep 172.18.2.158

Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
TCP IN 10.148.82.115:62451 -> 172.18.2.158:5001 expires=7827090 RxPackets=8 RxBytes=555 RxFlagsSeen=0x1a LastRxReport=7805489 TxPackets=7 TxBytes=629 TxFlagsSeen=0x1a LastTxReport=7805489 Flags=0x0030 [ SeenNonSyn NodePort ] RevNAT=0 SourceSecurityID=2 IfIndex=0
TCP OUT 10.148.82.115:62451 -> 172.18.2.158:5001 expires=7827090 RxPackets=7 RxBytes=629 RxFlagsSeen=0x1a LastRxReport=7805489 TxPackets=8 TxBytes=555 TxFlagsSeen=0x1a LastTxReport=7805489 Flags=0x0030 [ SeenNonSyn NodePort ] RevNAT=431 SourceSecurityID=2 IfIndex=3
--------
// NodePort=4300
>>  kubectl exec -it -n kube-system cilium-xg5nt  -- cilium bpf ct list global | grep 4300

Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
TCP OUT 10.241.93.59:4300 -> 10.148.82.115:62451 service expires=7827090 RxPackets=0 RxBytes=1444 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1a LastTxReport=7805489 Flags=0x0010 [ SeenNonSyn ] RevNAT=431 SourceSecurityID=0 IfIndex=0
TCP OUT 172.31.248.52:34300 -> 172.31.248.74:4240 expires=7827599 RxPackets=236902 RxBytes=19188898 RxFlagsSeen=0x1a LastRxReport=7805999 TxPackets=142137 TxBytes=11844706 TxFlagsSeen=0x1a LastTxReport=7805999 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=0 IfIndex=0
UDP OUT 172.20.0.3:53 -> 172.18.2.130:43007 service expires=7805992 RxPackets=0 RxBytes=162 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x00 LastTxReport=7805932 Flags=0x0000 [ ] RevNAT=98 SourceSecurityID=0 IfIndex=0
UDP OUT 172.18.2.130:43007 -> 172.18.0.47:53 expires=7805992 RxPackets=1 RxBytes=172 RxFlagsSeen=0x00 LastRxReport=7805932 TxPackets=1 TxBytes=79 TxFlagsSeen=0x00 LastTxReport=7805932 Flags=0x0000 [ ] RevNAT=98 SourceSecurityID=59251 IfIndex=0
--------
```

### Anything else?

[endpoint.log](https://github.com/cilium/cilium/files/10734167/endpoint.log)
[agent-log.log filtered on endpointID=27](https://github.com/cilium/cilium/files/10734175/agent-log.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment] 2023-02-14 15:59
>433   172.31.248.52:4300     NodePort       1 => 172.18.2.158:5001 (terminating)

Looks like the terminating backend is still present in the list. You can check if the backend is present in the backends BPF map. Please attach a sysdump. If you've set externalTrafficPolicy=Local, the traffic will only be forwarded to the node-local backend, else, it'll be dropped. 

>I've looked at hubble, and monitor logs, and neither show the packet that triggers the RST, nor are any drops shown.

So what's happening with the request? Is it getting forwarded to the terminating backend? Is the client external to the cluster?

**Comment by jonahmurphy** [comment] 2023-02-14 19:53
Thanks for looking into this @aditighag 

> So what's happening with the request? Is it getting forwarded to the terminating backend? Is the client external to the cluster?

The client is external to the cluster.  Its connected via the nodePort  (10.241.93.59:4300). It seems that packet is not getting forwarded at all, a tcpdump shows the RST originating from 10.241.93.59:4300. 

>  If you've set externalTrafficPolicy=Local, the traffic will only be forwarded to the node-local backend, else, it'll be dropped.
The pod is running on the node where the client is connected to.
Also, I see the same behaviour if externalTrafficPolicy=Cluster, and there is just one replica.

> You can check if the backend is present in the backends BPF map. 

```
// podIP=172.18.2.139
// nodeIP = eth1=10.241.93.59, eth0=172.31.248.52
>> kubectl exec -it -n kube-system cilium-xg5nt -- cilium map get cilium_lb4_backends_v2                                                                                     
...
1448   ANY://172.18.2.139:5001    sync
..
```

-----
```
>> kubectl exec -it -n kube-system cilium-xg5nt -- cilium bpf lb list | grep -A1 4300
                                                                                                                                                                                                              
172.31.248.52:4300     0.0.0.0:0 (433) (0) [NodePort]
                                       172.18.2.139:5001 (433) (1)
--               
0.0.0.0:4300           172.18.2.139:5001 (435) (1)
                                  0.0.0.0:0 (435) (0) [NodePort, non-routable]
--
10.241.93.59:4300       172.18.2.139:5001 (431) (1)
                                       0.0.0.0:0 (431) (0) [NodePort]
```

> Please attach a sysdump

I'll try get this later, or tomorrow.

**Comment by jonahmurphy** [comment] 2023-02-15 12:59
Here's the sysdump.

`cilium sysdump --logs-since-time 30m --node-list istio-ingress1.xxxxxxx`

[cilium-sysdump-20230214-200116-filtered.zip](https://github.com/cilium/cilium/files/10743101/cilium-sysdump-20230214-200116-filtered.zip)

Note, I've had to sanitise and filter  it quiet heavily - if anything useful is missing, let me know.

**Comment by jonahmurphy** [comment] 2023-02-15 14:07
I've noticed that the issue does not occur when externalTrafficPolicy=Local as  long as there is one other replica running on the same  node -  the connection to the terminating pod is persisted. 
It's easier to reproduce if the anti affinity is set on the pod to prevent more than one pod running on, hence I've updated the example deployment in the description to reflect this.

**Comment by aditighag** [comment] 2023-02-17 14:36
Thanks! Can you also attach Hubble/cilium monitor output for the traffic in question?

**Comment by jonahmurphy** [comment] 2023-02-18 13:25
Apologies, it looks like it wasn't captured.

I'm attaching monitor log for new reproduction,  but there is nothing captured after the pod is in terminating state.

Flow:
1. Create a new connection
2. Send the message ffffffff
3. Kill the pod - pod enters terminating state..
4. Send xxxxxxx 
5. connection is reset

[monitor.log](https://github.com/cilium/cilium/files/10774325/monitor.log)

**Comment by jonahmurphy** [comment] 2023-03-01 06:39
I thought a potential workaround maybe to set `publishNotReadyAddresses: true` on the service, but unfortunately it does not work. Is there anything else we could try?

**Comment by aditighag** [comment] 2023-03-02 05:46
https://github.com/cilium/cilium/issues/23744#issuecomment-1435669333

I suppose 10.209.0.136 is the external client IP address, and 172.18.2.137 is the node ip and 5001 is the node port?

I don't see SNAT/DNAT flows in the monitor log. How did you capture the monitor logs? What filter did you use? Can you run `cilium monitor` on the local backend, and check if the traffic to the nodeport was DNAT'd, and received by the backend?

**Comment by jonahmurphy** [comment] 2023-03-02 08:40
NodeIP:  172.31.248.52 (eth0)
External NodeIP: 10.241.93.59 (eth1)
Pod IP: 172.18.2.137

10.209.0.136 is the source of the client connection.

This was what I ran.  
```
kubectl exec -it -n kube-system cilium-xg5nt -- cilium monitor -vv --hex -D --related-to 517
```

What commands exactly should I run ?

**Comment by jonahmurphy** [comment] 2023-03-02 12:20
I've been testing again, and running the monitor as above but unfiltered. 
Should I expect to see specific logs for DNAT/SNAT ? Also notice that not all packets are logged, if send a couple of consecutive messages not all of them appear in the log, is that expected?

**Comment by adamgreenhalgh** [comment] 2023-03-03 12:13
I've been testing a little bit too. I modified the tcp echo server to re-echo the same text it received again after 30 seconds, terminated the service as described above and waited. The text is sent out again after 30 seconds, the external client sends an ACK, its this that causes the RST to be sent by the service. So packets flow from the inside to the outside, but as soon as a packet flows inside again, the RST is triggered.

**Comment by aojea** [comment] 2023-03-06 07:35
/assign

> Looks like the terminating backend is still present in the list. You can check if the backend is present in the backends BPF map. Please attach a sysdump. If you've set externalTrafficPolicy=Local, the traffic will only be forwarded to the node-local backend, else, it'll be dropped.

yeah, but it seems that the Terminating staet of the. LB  in Cilium means "do no accept new connections but don't break existing"

Since https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-proxy-terminating-endpoints   in Kubernetes the expectaction is that Terminating endpoint is able to serve New requests if there are no more endpoints, this is needed to handle scenarios like this and avoid traffic drops

**Comment by aditighag** [comment] 2023-03-06 23:54
>Terminating endpoint is able to serve New requests if there are no more endpoints, this is needed to handle scenarios like this and avoid traffic drops

But @jonahmurphy reported drops for existing connections:

>Send another message over the existing connection whilst the pod is in a terminating state

**Comment by aditighag** [comment] 2023-03-06 23:58
Hey @jonahmurphy 

> NodeIP: 172.31.248.52 (eth0) External NodeIP: 10.241.93.59 (eth1) Pod IP: 172.18.2.137
> 
> 10.209.0.136 is the source of the client connection.
> 
> 5001 is the container port, the nodePort is 4300.
> 
> This is was what I ran.
> 
> ```
> kubectl exec -it -n kube-system cilium-xg5nt -- cilium monitor -vv --hex -D --related-to 517
> ```
> 
> What commands exactly should I run ?

I suppose `517` is the endpoint id of the service backend pod? If yes, you'll only see the SNAT/DNAT'd traffic. This can be a bit tricky to filter with `cilium monitor`, and you may want to use Hubble as it has more filtering options. 

> Also notice that not all packets are logged, if I send a couple of consecutive messages not all of them appear in the log, is that expected?

Yes, you'll need to disable monitor aggregation just for testing. 

Can you collect full monitor/Hubble logs, and highlight the ones related to the test traffic? Also, please provide a snippet of `cilium bpf ct list global` and `cilium bpf nat list ` so that we can check if SNAT or DNAT isn't happening as expected. You'll need to note the source port for the test traffic so that we know which flows to track in the ct and nat output.

**Comment by aojea** [comment] 2023-03-07 00:02
> But @jonahmurphy reported drops for existing connections:
> 
> >

upps, that should not happen indeed, I quickled to jump into conclusions sorry

**Comment by adamgreenhalgh** [comment] 2023-03-07 09:05
> @aojea
> 
> > Terminating endpoint is able to serve New requests if there are no more endpoints, this is needed to handle scenarios like this and avoid traffic drops
> 
> But @jonahmurphy reported drops for existing connections:
> 
> > Send another message over the existing connection whilst the pod is in a terminating state
> 
> @jonahmurphy What command did you use to send traffic over the existing connection?

When I reproduced it, I telnet'd into a modified echo server which just takes the message you sent it sends it back out on the inbound tcp sock, waits 30 seconds, and then sends the message back on the same socket before exiting the routine. During the 30s sleep I terminated the pod running the echo server as Jonah described above. So the pod was in the terminating state before the second repeated message was sent.

On the host running the telnet client I was running tcpdump. This approximately gave

outbound : message sent by echo server 
inbound : ack
<pod terminated whilst sleep 30>
outbound : message sent again on same socket by echo server 
inbound : ack
outbound : rst

The observation was that the first inbound packet even if its an ack caused the outbound rst, I didn't test more outbound packets because the packet after the terminate causes an inbound ack which triggers the rst. 

https://github.com/vhiribarren/docker-echo-server/blob/master/echo-server.py 
to modify the echo server I added 

line 5: import time
line 35: time.sleep(30)
line 36: self.transport.write(out_msg.encode())

I'm sorry I don't have the patch and pcap on this machine but the reproduction is easy.

**Comment by jonahmurphy** [comment] 2023-03-07 17:14
@aditighag 

> I suppose 517 is the endpoint id of the service backend pod?

Correct.

> Yes, you'll need to disable monitor aggregation just for testing.

>Can you collect full monitor/Hubble logs, and highlight the ones related to the test traffic? Also, please provide a snippet of >cilium bpf ct list global and cilium bpf nat list  so that we can check if SNAT or DNAT isn't happening as expected. You'll >need to note the source port for the test traffic so that we know which flows to track in the ct and nat output.

I disabled log aggregation and ran some tests, now I can see the packet coming into "from-network", but it doesn't get as far as the conntrack lookup, or at least it doesn't log if it does.

Details of the scenario tested:

```
pod: test-echo-server-c65f4c45f-kt7j6
endpointID=118 identity=27289
pod ip: 172.18.2.155
Container port: 5001
nodeIP cluster network (eth0): 172.31.248.52
nodeIP external (eth1): 10.241.93.59
nodePort: 4300
clientIP:port: 10.148.82.194:55935
````

1. With telnet start a connection from the clientIP:port as above
2. Client sends 3  consecutive messages `1111111`.   `2222222`   `3333333` (from 10.148.82.194:55935 to -> 10.241.93.59:4300)
    - For each message sent to the echo server, it responds with a "TCP: <pod-name> received <message>"
4. Start terminating the pod
5. Client Sends 4444444


I tried capturing with `hubble observe` it looks like the last packet sent whilst in terminating state is not captured by hubble, also doesn't show up in hubble ui.

I captured the monitor log with `kubectl exec -it -n kube-system cilium-b6hbd  -- cilium monitor -vv --hex -D`

I ran `cilium bpf ct list global` and `cilium bpf nat list` whilst the pod is in  a terminating state before sending the last message, but I  did not see any entries for the clients source port in the output from `bpf nat list`. 

The monitor logs were several hundred MB's so I had to snip out a few chunks to get the size down for upload. If anything is missing let me know.

[logs.tar.gz](https://github.com/cilium/cilium/files/10912037/logs.tar.gz)

**Comment by aojea** [comment] 2023-04-14 08:54
for visibility, I think this may be solved by https://github.com/cilium/cilium/pull/24174 , but I don't have time to test it, I can confirm that graceful shutdown is working fine with my patch, but I don't know if there are edge cases

**Comment by jonahmurphy** [comment] 2023-04-19 11:09
> for visibility, I think this may be solved by #24174 , but I don't have time to test it, I can confirm that graceful shutdown is working fine with my patch, but I don't know if there are edge cases

Thanks @aojea Im planning to test this soon, hopefully before the end of the week.

**Comment by aditighag** [comment] 2023-05-19 16:40
>Im planning to test this soon, hopefully before the end of the week.

@jonahmurphy 👋 Any update on the testing?

**Comment by jonahmurphy** [comment] 2023-05-23 08:19
> > Im planning to test this soon, hopefully before the end of the week.
> 
> @jonahmurphy 👋 Any update on the testing?

@aditighag Apologies for the delay, Im planning to get to it this week. As soon as I have an update I'll post it.

**Comment by jonahmurphy** [comment] 2023-05-25 17:20
@aojea  @aditighag 

I did a little testing today, and observed that while existing connections are persisted whilst a pod is in a terminating state,  new connections are allowed.  I expected that new connections would be rejected. Whats that the expected behaviour?

I guess this behaviour could be desirable when combined with an in place hitless upgrade on a node, such that new connections towards a given node are always handled by either the old or new pod, otherwise the application needs to stop accepting new connections.

I'll try to do some further with an LoadBalancer in front, to see if this can work.

**Comment by aditighag** [comment] 2023-05-25 17:59
> I expected that new connections would be rejected. Whats that the expected behaviour?

If a service has only 1 backend, and that's terminating, the backend will be selected for LB. That's the change that above linked @aojea's PR introduced.

**Comment by jonahmurphy** [comment] 2023-05-25 18:48
> If a service has only 1 backend, and that's terminating, the backend will be selected for LB. 
Right, or in the case where the externalTrafficPolicy=Local, and there's only 1 backend on a given node. 

I think this makes sense, and solves this issue - as long as the backend's affinity rules are setup to force an in-place upgrade, and or the backend stops accepting new connections after some time in order to eventually shutdown gracefully.

**Comment by aditighag** [comment] 2023-06-05 21:10
@jonahmurphy Thanks for the update: I'm closing the issue.

**Closed as completed** 2023-06-05 21:10 UTC
Labels: kind/bug, needs/triage, kind/community-report
