### ISSUE TITLE
cilium status doesn't include cluster nodes in json output

### ISSUE THREAD

**Issue by anjmao** [cilium/cilium#13171] opened 2020-09-15 06:06 UTC
## Bug report

Command `cilium status` is inconsistent when using plaintext and json output format. In json format cluster nodes health info is missing. 

**General Information**

- Cilium version (run `cilium version`)
Client: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
Daemon: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64

**How to reproduce the issue**

1. `cilium status --verbose` outputs all cluster nodes health correctly.
```
Cluster health:                    4/4 reachable   (2020-09-15T06:02:15Z)
  Name                             IP              Node        Endpoints
  node1 (localhost)              10.10.X.X     reachable   reachable
  node2                          10.20.X.X        reachable   reachable
  node3                          10.0.X.X          reachable   reachable
  node4                          10.10.X.X   reachable   reachable
```
2. `cilium status --verbose -o json` json output cluster nodes shown as null. Nodes info is attached only if default plain text output is used here https://github.com/cilium/cilium/blob/master/cilium/cmd/status.go#L109
```json
 "cluster": {
    "ciliumHealth": {
      "state": "Ok"
    },
    "nodes": null,
    "self": "node1"
  },
```

**Comment by qmonnet** [comment] 2020-09-15 10:10
Right, I can reproduce it. Thanks for filling the issue!

I'm unsure if the `nodes` should be filled when we call the `client.Daemon.GetHealthz(params)`, or if we need to make a second request to `client.Connectivity.GetStatus(nil)` as is done for plain text. @joestringer, I see you wrote the code for plain text (back in 2018), do you have any insight?

**Comment by joestringer** [comment] 2020-09-15 18:26
Yeah so the cluster connectivity is coming from the `cilium-health status` API, when I added this into `cilium status` it was just for plaintext overview convenience. I always figured that if you wanted cluster connectivity status, you would separately call the cilium-health API for it. Some time back these were in separate daemons but IIRC we merged them a while back. 

We would welcome patches to fix this up in the `cilium status` API, or in the mean time you should be able to call the cilium-health API directly for this info.

**Comment by aanm** [comment] 2020-09-15 20:59
Just to add some notes here, I think the `nodes` field was removed from the `status` command to avoid the load of checking all nodes' result on the daemon side for large clusters.

**Comment by joestringer** [comment] 2020-09-15 21:29
@aanm ah, in that case is there anything that can be done for this issue? Or the user should just use `cilium-health status -o json`?

**Comment by aanm** [comment] 2020-09-16 08:30
@anjmao 
The change that made this optimization is in https://github.com/cilium/cilium/commit/57fa7a626db1246f769557821ec721caf4d3d1e7

As an alternative, the list of nodes can be obtained by `cilium node list -o json`. If you are using the API directly, you can use 
```
$ curl --unix-socket /var/run/cilium/cilium.sock http://localhost/v1/cluster/nodes
```

If you want to have some optimization on the client side, the list of nodes added / removed can be kept in memory by the cilium agent. You just need to pass the `client-id` header with `0` and re-use the returned `client-id` given by the agent.

```
$ curl -H client-id:0 --unix-socket /var/run/cilium/cilium.sock http://localhost/v1/cluster/nodes
{"client-id":5878504947050967049,"nodes-added":[{"health-endpoi[...]
```

```
$ curl -H client-id:5878504947050967049 --unix-socket /var/run/cilium/cilium.sock http://localhost/v1/cluster/nodes
{"client-id":5878504947050967049,"nodes-added":null,"nodes-removed":null,"self":"k8s2"}
```

If a node is added or removed between API calls with the same client-id, the `nodes-added` and `nodes-removed` field will be populated with such nodes.

**Comment by joestringer** [comment] 2020-09-17 17:40
Given Andre's message above, this is working as intended. Feel free to ask further questions or open a new issue if there is another problem with fetching this information using the instructions above.

**Closed as completed by joestringer** 2020-09-17 17:40 UTC
Labels: kind/bug, area/cli, kind/community-report
