### ISSUE TITLE
R1 invalid mem access 'inv'

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#16571] opened 2021-06-16 20:12 UTC
## Bug report
While attempting to rewrite ctx destination MAC in tunnel mode, the generated byte code fail to pass verifier and result in **_"R1 invalid mem access 'inv'"_**

the complete C code that has been changed is only in **_encap_and_redirect_lxc()_** as below, the diff is here https://github.com/cilium/cilium/issues/16517#issuecomment-861077716

It appears the code change below caused the compiler to re-arrange the code ?, and result in invalid memory access ?

<pre>
static __always_inline int
encap_and_redirect_lxc(struct __ctx_buff *ctx, __u32 tunnel_endpoint,
                       __u8 encrypt_key __maybe_unused,
                       struct endpoint_key *key, __u32 seclabel, __u32 monitor)
{
        struct endpoint_key *tunnel;
#define VTEP_MAC  { .addr = { 0xce, 0x72, 0xa7, 0x03, 0x88, 0x58 } }
        union macaddr vtep_mac = VTEP_MAC;

        if (tunnel_endpoint) {
#ifdef ENABLE_IPSEC
                if (encrypt_key)
                        return encap_and_redirect_ipsec(ctx, tunnel_endpoint,
                                                        encrypt_key, seclabel);
#endif
#if !defined(ENABLE_NODEPORT) && (defined(ENABLE_IPSEC) || defined(ENABLE_HOST_FIREWALL))
                /* For IPSec and the host firewall, traffic from a pod to a remote node
                 * is sent through the tunnel. In the case of node --> VIP@remote pod,
                 * packets may be DNATed when they enter the remote node. If kube-proxy
                 * is used, the response needs to go through the stack on the way to
                 * the tunnel, to apply the correct reverse DNAT.
                 * See #14674 for details.
                 */
                return __encap_with_nodeid(ctx, tunnel_endpoint, seclabel, monitor);
#else
                return __encap_and_redirect_with_nodeid(ctx, tunnel_endpoint, seclabel, monitor);
#endif /* !ENABLE_NODEPORT && (ENABLE_IPSEC || ENABLE_HOST_FIREWALL) */
        }

        tunnel = map_lookup_elem(&TUNNEL_MAP, key);
        if (!tunnel)
                return DROP_NO_TUNNEL_ENDPOINT;

#ifdef ENABLE_IPSEC
        if (tunnel->key) {
                __u8 min_encrypt_key = get_min_encrypt_key(tunnel->key);

                return encap_and_redirect_ipsec(ctx, tunnel->ip4,
                                                min_encrypt_key,
                                                seclabel);
        }
#endif
        if (eth_store_daddr(ctx, (__u8 *) &vtep_mac.addr, 0) < 0)
                return DROP_WRITE_ERROR;
        return __encap_and_redirect_with_nodeid(ctx, tunnel->ip4, seclabel, monitor);
}
</pre>

**General Information**

### the byte code that matches above function and code change
the  error 
level=warning msg=**_"2198: (71) r3 = *(u8 *)(r1 +22)"_** subsys=datapath-loader
level=warning msg=**_"R1 invalid mem access 'inv'"_** subsys=datapath-loader

the instruction path I think it happens

1.  1994:	15 01 c2 00 00 00 00 00	if r1 == 0 **goto +194  LBB3_274**
2. 0000000000004468  **LBB3_274**
3. 00000000000044a8  **LBB3_275** 

**_0000000000003de0  LBB3_254 :_**
; 		struct endpoint_key key = {};
    1980:	63 9a 60 ff 00 00 00 00	*(u32 *)(r10 - 160) = r9
    1981:	63 9a 5c ff 00 00 00 00	*(u32 *)(r10 - 164) = r9
    1982:	63 9a 58 ff 00 00 00 00	*(u32 *)(r10 - 168) = r9
    1983:	63 9a 54 ff 00 00 00 00	*(u32 *)(r10 - 172) = r9
; 		key.family = ENDPOINT_KEY_IPV4;
    1984:	73 6a 60 ff 00 00 00 00	*(u8 *)(r10 - 160) = r6
; 		key.ip4 = orig_dip & IPV4_MASK;
    1985:	57 08 00 00 ff ff ff 00	r8 &= 16777215
    1986:	63 8a 50 ff 00 00 00 00	*(u32 *)(r10 - 176) = r8
    1987:	18 01 00 00 ce 72 a7 03 00 00 00 00 88 58 00 00	r1 = 97341200102094 ll
;         union macaddr vtep_mac = VTEP_MAC;
    1989:	7b 1a d0 ff 00 00 00 00	*(u64 *)(r10 - 48) = r1
    1990:	79 a4 18 ff 00 00 00 00	r4 = *(u64 *)(r10 - 232)
; 	if (tunnel_endpoint) {
    1991:	bf 41 00 00 00 00 00 00	r1 = r4
    1992:	67 01 00 00 20 00 00 00	r1 <<= 32
    1993:	77 01 00 00 20 00 00 00	r1 >>= 32
    **_1994:	15 01 c2 00 00 00 00 00	if r1 == 0 goto +194  LBB3_274_** 
; 	key.tunnel_id = seclabel;
    1995:	18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r2 = 0 ll
    1997:	67 02 00 00 20 00 00 00	r2 <<= 32
    1998:	77 02 00 00 20 00 00 00	r2 >>= 32
    1999:	b7 01 00 00 06 00 00 00	r1 = 6
    2000:	79 a6 48 ff 00 00 00 00	r6 = *(u64 *)(r10 - 184)
    2001:	15 02 02 00 01 00 00 00	if r2 == 1 goto +2  LBB3_257 
    2002:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0 ll

**_0000000000004468  LBB3_274_** 
    2189:	bf a2 00 00 00 00 00 00	r2 = r10
; 	tunnel = map_lookup_elem(&TUNNEL_MAP, key);
    2190:	07 02 00 00 50 ff ff ff	r2 += -176
    2191:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0 ll
    2193:	85 00 00 00 01 00 00 00	call 1
    2194:	bf 07 00 00 00 00 00 00	r7 = r0
    2195:	79 a6 48 ff 00 00 00 00	r6 = *(u64 *)(r10 - 184)
; 	if (!tunnel)
    2196:	55 07 94 00 00 00 00 00	if r7 != 0 goto +148  LBB3_289 

**_00000000000044a8  _LBB3_275 :_**
; 	__u8 new_ttl, ttl = ip4->ttl;
    **_2197:	79 a1 38 ff 00 00 00 00	r1 = *(u64 *)(r10 - 200)_**
    **_2198:	71 13 16 00 00 00 00 00	r3 = *(u8 *)(r1 + 22)_**
; 	if (ttl <= 1)
    2199:	25 03 01 00 01 00 00 00	if r3 > 1 goto +1  LBB3_277 
    2200:	05 00 20 ff 00 00 00 00	goto -224  LBB3_253 

### Here is the byte code for the same encap_and_redirect_lxc() that has not been changed, we don't even see **_new_ttl, ttl = ip4->ttl;_**  in below byte code path

0000000000006dd0  **_LBB13_510 :_**
    3514:       b7 01 00 00 00 00 00 00 r1 = 0
;               struct endpoint_key key = {};
    3515:       63 1a 58 ff 00 00 00 00 *(u32 *)(r10 - 168) = r1
    3516:       63 1a 54 ff 00 00 00 00 *(u32 *)(r10 - 172) = r1
    3517:       63 1a 50 ff 00 00 00 00 *(u32 *)(r10 - 176) = r1
    3518:       63 1a 4c ff 00 00 00 00 *(u32 *)(r10 - 180) = r1
;               key.ip4 = orig_dip & IPV4_MASK;
    3519:       57 08 00 00 ff ff 00 00 r8 &= 65535
    3520:       63 8a 48 ff 00 00 00 00 *(u32 *)(r10 - 184) = r8
    3521:       b7 01 00 00 01 00 00 00 r1 = 1
;               key.family = ENDPOINT_KEY_IPV4;
    3522:       73 1a 58 ff 00 00 00 00 *(u8 *)(r10 - 168) = r1
    3523:       79 a4 38 ff 00 00 00 00 r4 = *(u64 *)(r10 - 200)
;       if (tunnel_endpoint) {
    3524:       bf 42 00 00 00 00 00 00 r2 = r4
    3525:       67 02 00 00 20 00 00 00 r2 <<= 32
    3526:       77 02 00 00 20 00 00 00 r2 >>= 32
    3527:       79 a1 40 ff 00 00 00 00 r1 = *(u64 *)(r10 - 192)
;       if (tunnel_endpoint) {
    **_3528:       15 02 d2 00 00 00 00 00 if r2 == 0 goto +210 <LBB13_538>_**
;       key.tunnel_id = seclabel;
    3529:       18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 r2 = 0 ll
    3531:       67 02 00 00 20 00 00 00 r2 <<= 32
    3532:       77 02 00 00 20 00 00 00 r2 >>= 32
    3533:       b7 03 00 00 06 00 00 00 r3 = 6
    3534:       15 02 02 00 01 00 00 00 if r2 == 1 goto +2  LBB13_513 
    3535:       18 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 r3 = 0 ll

00000000000074d8  **_LBB13_538 :_**
    3739:       bf a2 00 00 00 00 00 00 r2 = r10
;       tunnel = map_lookup_elem(&TUNNEL_MAP, key);
    3740:       07 02 00 00 48 ff ff ff r2 += -184
    3741:       18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 r1 = 0 ll
    3743:       85 00 00 00 01 00 00 00 call 1
    3744:       79 a1 40 ff 00 00 00 00 r1 = *(u64 *)(r10 - 192)
    3745:       79 a5 30 ff 00 00 00 00 r5 = *(u64 *)(r10 - 208)
;       if (!tunnel)
    3746:       15 00 f7 00 00 00 00 00 if r0 == 0 goto +247  LBB13_571 
;       key.tunnel_id = seclabel;
    3747:       18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 r2 = 0 ll
    3749:       67 02 00 00 20 00 00 00 r2 <<= 32
    3750:       77 02 00 00 20 00 00 00 r2 >>= 32
    3751:       b7 01 00 00 06 00 00 00 r1 = 6
    **_3752:       15 02 02 00 01 00 00 00 if r2 == 1 goto +2  LBB13_541_** 
    3753:       18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 r1 = 0 ll

0000000000007558  **_LBB13_541 :_**
;       return __encap_and_redirect_with_nodeid(ctx, tunnel->ip4, seclabel, monitor);

- Cilium version (run `cilium version`)
Client: 1.10.90 35f28766c 2021-06-16T03:55:39+02:00 go version go1.16.5 linux/amd64
Daemon: 1.10.90 35f28766c 2021-06-16T03:55:39+02:00 go version go1.16.5 linux/amd64

- Kernel version (run `uname -a`)
4.18.0-305.3.1.el8.x86_64

- Orchestration system version in use (e.g. `kubectl version`, ...)

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
cilium deployment yaml file
https://github.com/vincentmli/docs/blob/master/cilium-vtep.yaml.txt

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1  make above code changes and deploy cilium in tunnel mode without kube-proxy or deploy the image vli39/cilium:vtep
2. deploy the the cilium deployment yaml example

invalid memory access byte code
[bpf_lxc-invalid-mem.txt](https://github.com/cilium/cilium/files/6665570/bpf_lxc-invalid-mem.txt)
good byte code
[bpf_lxc-origin.txt](https://github.com/cilium/cilium/files/6665571/bpf_lxc-origin.txt)

**Comment by joestringer** [comment] 2021-07-06 19:07
Duplicate of https://github.com/cilium/cilium/issues/16571, closing.

**Closed as completed by joestringer** 2021-07-06 19:07 UTC
Labels: kind/duplicate, kind/community-report
