### ISSUE TITLE
CI: GKE e2e broken

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#20013] opened 2022-05-30 21:20 UTC
```
2022-05-30T20:52:02.727624604Z level=debug msg="Compiling datapath" clang="clang version 10.0.0 (https://github.com/llvm/llvm-project.git 425a44e84b18e222cc38ac40603db1653a80a6cb)\nTarget: x86_64-unknown-linux-gnu\nThread model: posix\nInstalledDir: /usr/bin\n" debug=true llc="LLVM (http://llvm.org/):\n  LLVM version 10.0.0\n  Optimized build.\n  Default target: x86_64-unknown-linux-gnu\n  Host CPU: broadwell\n\n  Registered Targets:\n    bpf   - BPF (host endian)\n    bpfeb - BPF (big endian)\n    bpfel - BPF (little endian)\n" subsys=datapath-loader
2022-05-30T20:52:02.727653676Z level=debug msg="Launching compiler" args="[-emit-llvm -g -O2 -target bpf -std=gnu89 -nostdinc -D__NR_CPUS__=2 -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -Wimplicit-int-conversion -Wenum-conversion -I/var/run/cilium/state/globals -I/var/run/cilium/state/templates/8743fb584f8329a934ae5daf7c5e9e8d091fadabc143ffc04aa3be81963f43da -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -c /var/lib/cilium/bpf/bpf_host.c -o -]" subsys=datapath-loader target=clang
2022-05-30T20:52:02.910445133Z level=info msg="Initializing Cilium API" subsys=daemon
2022-05-30T20:52:02.910479123Z level=error msg="Failed to compile bpf_host.dbg.o: exit status 1" compiler-pid=329 linker-pid=330 subsys=datapath-loader
2022-05-30T20:52:02.910486313Z level=debug msg="/var/lib/cilium/bpf/bpf_host.c:420:10: error: implicit declaration of function 'lookup_ip4_remote_endpoint' [-Werror,-Wimplicit-function-declaration]" subsys=datapath-loader
2022-05-30T20:52:02.910523452Z level=debug msg="                info = lookup_ip4_remote_endpoint(ip4->saddr);" subsys=datapath-loader
2022-05-30T20:52:02.910532829Z level=debug msg="                       ^" subsys=datapath-loader
2022-05-30T20:52:02.910538147Z level=debug msg="/var/lib/cilium/bpf/bpf_host.c:420:10: note: did you mean 'lookup_ip4_endpoint'?" subsys=datapath-loader
2022-05-30T20:52:02.910542994Z level=debug msg="/var/lib/cilium/bpf/lib/eps.h:41:1: note: 'lookup_ip4_endpoint' declared here" subsys=datapath-loader
2022-05-30T20:52:02.910548533Z level=debug msg="lookup_ip4_endpoint(const struct iphdr *ip4)" subsys=datapath-loader
2022-05-30T20:52:02.910554932Z level=debug msg=^ subsys=datapath-loader
2022-05-30T20:52:02.910563230Z level=debug msg="/var/lib/cilium/bpf/bpf_host.c:420:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]" subsys=datapath-loader
2022-05-30T20:52:02.910570939Z level=debug msg="                info = lookup_ip4_remote_endpoint(ip4->saddr);" subsys=datapath-loader
2022-05-30T20:52:02.910578010Z level=debug msg="                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" subsys=datapath-loader
2022-05-30T20:52:02.910585280Z level=debug msg="2 errors generated." subsys=datapath-loader
2022-05-30T20:52:02.910610943Z level=debug msg="JoinEP: Failed to compile" debug=true error="Failed to compile bpf_host.dbg.o: exit status 1" params="&{Source:bpf_host.c Output:bpf_host.dbg.o OutputType:obj Options:[]}" subsys=datapath-loader
2022-05-30T20:52:02.910631079Z level=error msg="BPF template object creation failed" bpfHeaderfileHash=8743fb584f8329a934ae5daf7c5e9e8d091fadabc143ffc04aa3be81963f43da error="failed to compile template program /var/run/cilium/state/templates/8743fb584f8329a934ae5daf7c5e9e8d091fadabc143ffc04aa3be81963f43da: Failed to compile bpf_host.dbg.o: exit status 1" subsys=datapath-loader
2022-05-30T20:52:02.910636199Z level=warning msg="BPF template compilation unsuccessful" bpfHeaderfileHash=8743fb584f8329a934ae5daf7c5e9e8d091fadabc143ffc04aa3be81963f43da error="Could not locate previously compiled BPF template" subsys=datapath-loader
```

commit sha 6a8fe290930f73da0311813259f93ac244b7004a

The issue goes away if the cilium container is restarted on the node. The issue only happens on new nodes.

Steps to reproduce:
```
CLUSTER_NAME=cluster1
CLUSTER_ZONE=europe-west6-a
image_type="COS_CONTAINERD"
gcloud container clusters create $CLUSTER_NAME --image-type ${image_type} --num-nodes 2 --zone $CLUSTER_ZONE \
--enable-ip-alias \
--create-subnetwork="" \
--image-type COS_CONTAINERD \
--num-nodes 2 \
--machine-type e2-custom-2-4096 \
--disk-type pd-standard \
--disk-size 10GB \
--node-taints node.cilium.io/agent-not-ready=true:NoExecute \
--preemptible \
--version=1.22.8-gke.201

gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE

cilium install --cluster-name=$CLUSTER_NAME --chart-directory=install/kubernetes/cilium --helm-set=image.repository=quay.io/cilium/cilium-ci --helm-set=image.useDigest=false --helm-set=image.tag=6a8fe290930f73da0311813259f93ac244b7004a --helm-set=operator.image.repository=quay.io/cilium/operator --helm-set=operator.image.suffix=-ci --helm-set=operator.image.tag=6a8fe290930f73da0311813259f93ac244b7004a --helm-set=operator.image.useDigest=false --helm-set=clustermesh.apiserver.image.repository=quay.io/cilium/clustermesh-apiserver-ci --helm-set=clustermesh.apiserver.image.tag=6a8fe290930f73da0311813259f93ac244b7004a --helm-set=clustermesh.apiserver.image.useDigest=false --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci --helm-set=hubble.relay.image.tag=6a8fe290930f73da0311813259f93ac244b7004a --wait=false --rollback=false --config monitor-aggregation=none --base-version=v1.12 --config=debug=true --version=
```

```
$ cilium version
cilium-cli: v0.11.7 compiled with go1.18 on linux/amd64
cilium image (default): v1.11.5
cilium image (stable): v1.11.5
cilium image (running): -ci:6a8fe290930f73da0311813259f93ac244b7004a
```

```
$ uname -a
Linux gke-cluster1-default-pool-584196dd-rsbl 5.10.90+ #1 SMP Sat Mar 5 10:09:49 UTC 2022 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```

**Comment by aanm** [comment] 2022-05-30 21:26
The same goes for the lxc program:
```
2022-05-30T20:52:03.724622475Z level=debug msg="Compiling datapath" clang="clang version 10.0.0 (https://github.com/llvm/llvm-project.git 425a44e84b18e222cc38ac40603db1653a80a6cb)\nTarget: x86_64-unknown-linux-gnu\nThread model: posix\nInstalledDir: /usr/bin\n" debug=true llc="LLVM (http://llvm.org/):\n  LLVM version 10.0.0\n  Optimized build.\n  Default target: x86_64-unknown-linux-gnu\n  Host CPU: broadwell\n\n  Registered Targets:\n    bpf   - BPF (host endian)\n    bpfeb - BPF (big endian)\n    bpfel - BPF (little endian)\n" subsys=datapath-loader
2022-05-30T20:52:03.724655785Z level=debug msg="Launching compiler" args="[-emit-llvm -g -O2 -target bpf -std=gnu89 -nostdinc -D__NR_CPUS__=2 -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -Wimplicit-int-conversion -Wenum-conversion -I/var/run/cilium/state/globals -I/var/run/cilium/state/templates/aea21ba18d245490d4d8babcfdd3cedf0e46ef31633b1cb8c246539d0d2d3f04 -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -c /var/lib/cilium/bpf/bpf_lxc.c -o -]" subsys=datapath-loader target=clang
2022-05-30T20:52:03.819193726Z level=error msg="Failed to compile bpf_lxc.dbg.o: exit status 1" compiler-pid=341 linker-pid=342 subsys=datapath-loader
2022-05-30T20:52:03.819267007Z level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:629:10: error: implicit declaration of function 'lookup_ip4_remote_endpoint' [-Werror,-Wimplicit-function-declaration]" subsys=datapath-loader
2022-05-30T20:52:03.819277318Z level=debug msg="                info = lookup_ip4_remote_endpoint(tuple.daddr);" subsys=datapath-loader
2022-05-30T20:52:03.819324798Z level=debug msg="                       ^" subsys=datapath-loader
2022-05-30T20:52:03.819365576Z level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:629:10: note: did you mean 'lookup_ip4_endpoint'?" subsys=datapath-loader
2022-05-30T20:52:03.819372781Z level=debug msg="/var/lib/cilium/bpf/lib/eps.h:41:1: note: 'lookup_ip4_endpoint' declared here" subsys=datapath-loader
2022-05-30T20:52:03.819378384Z level=debug msg="lookup_ip4_endpoint(const struct iphdr *ip4)" subsys=datapath-loader
2022-05-30T20:52:03.819383951Z level=debug msg=^ subsys=datapath-loader
2022-05-30T20:52:03.819389577Z level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:629:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]" subsys=datapath-loader
2022-05-30T20:52:03.819394769Z level=debug msg="                info = lookup_ip4_remote_endpoint(tuple.daddr);" subsys=datapath-loader
2022-05-30T20:52:03.819399678Z level=debug msg="                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" subsys=datapath-loader
2022-05-30T20:52:03.819404960Z level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:1742:10: error: implicit declaration of function 'lookup_ip4_remote_endpoint' [-Werror,-Wimplicit-function-declaration]" subsys=datapath-loader
2022-05-30T20:52:03.819454738Z level=debug msg="                info = lookup_ip4_remote_endpoint(ip4->saddr);" subsys=datapath-loader
2022-05-30T20:52:03.819462758Z level=debug msg="                       ^" subsys=datapath-loader
2022-05-30T20:52:03.819468124Z level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:1742:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]" subsys=datapath-loader
2022-05-30T20:52:03.819473283Z level=debug msg="                info = lookup_ip4_remote_endpoint(ip4->saddr);" subsys=datapath-loader
2022-05-30T20:52:03.819478258Z level=debug msg="                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" subsys=datapath-loader
2022-05-30T20:52:03.819483506Z level=debug msg="4 errors generated." subsys=datapath-loader
2022-05-30T20:52:03.819533366Z level=debug msg="JoinEP: Failed to compile" debug=true error="Failed to compile bpf_lxc.dbg.o: exit status 1" params="&{Source:bpf_lxc.c Output:bpf_lxc.dbg.o OutputType:obj Options:[]}" subsys=datapath-loader
2022-05-30T20:52:03.819570226Z level=error msg="BPF template object creation failed" bpfHeaderfileHash=aea21ba18d245490d4d8babcfdd3cedf0e46ef31633b1cb8c246539d0d2d3f04 error="failed to compile template program /var/run/cilium/state/templates/aea21ba18d245490d4d8babcfdd3cedf0e46ef31633b1cb8c246539d0d2d3f04: Failed to compile bpf_lxc.dbg.o: exit status 1" subsys=datapath-loader
2022-05-30T20:52:03.819581598Z level=warning msg="BPF template compilation unsuccessful" bpfHeaderfileHash=aea21ba18d245490d4d8babcfdd3cedf0e46ef31633b1cb8c246539d0d2d3f04 error="Could not locate previously compiled BPF template" subsys=datapath-loader
2022-05-30T20:52:03.819654119Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3436 error="Could not locate previously compiled BPF template" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

**Comment by aanm** [comment] 2022-05-30 21:31
[cilium-bugtool-20220530-212925.537+0000-UTC-3467896499.zip](https://github.com/cilium/cilium/files/8800769/cilium-bugtool-20220530-212925.537%2B0000-UTC-3467896499.zip)

**Comment by pchaigno** [comment] 2022-05-31 07:21
What gcloud version are you using?

I'm getting:
```
ERROR: (gcloud.container.clusters.create) unrecognized arguments: --version=1.22.8-gke.201 (did you mean '--node-version'?)
```
And once I change that flag as suggested:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Node version "1.22.8-gke.201" must not have a greater minor version than master version "1.21.11-gke.1100".
```
If I remove that flag altogether, then the Cilium installation works fine and I can't reproduce.

**Comment by aanm** [comment] 2022-06-01 15:18
```
$ gcloud --version
Google Cloud SDK 387.0.0
alpha 2022.05.20
beta 2022.05.20
bq 2.0.74
bundled-python3-unix 3.9.12
core 2022.05.20
gsutil 5.10
```

**Comment by pchaigno** [comment] 2022-06-07 08:12
@aanm I have the exact same gcloud version and am hitting the errors above. Are you sure about the reproduction steps? Any chance you updated gcloud since you reproduced?

**Comment by pchaigno** [comment] 2022-06-07 10:17
Seems `bpf_features.h` is wrong somehow:
```
# cat globals/bpf_features.h | grep -i LRU
#define NO_HAVE_LRU_HASH_MAP_TYPE
#define NO_HAVE_LRU_PERCPU_HASH_MAP_TYPE
# bpftool feature probe macro | grep -i LRU
#define HAVE_LRU_HASH_MAP_TYPE
#define HAVE_LRU_PERCPU_HASH_MAP_TYPE
```

**Comment by DolceTriade** [comment] 2022-06-07 21:08
I bisected the issue earlier and found this to be the offending commit:
```
commit 8cfe7596af7b12d1e4a370421313717c1a7db157
Author: Yafang Shao <laoar.shao@gmail.com>
Date:   Sat Apr 9 12:59:57 2022 +0000

    bpftool: Use libbpf 1.0 API mode instead of RLIMIT_MEMLOCK
    
    We have switched to memcg-based memory accouting and thus the rlimit is
    not needed any more. LIBBPF_STRICT_AUTO_RLIMIT_MEMLOCK was introduced in
    libbpf for backward compatibility, so we can use it instead now.
    
    libbpf_set_strict_mode always return 0, so we don't need to check whether
    the return value is 0 or not.
    
    Signed-off-by: Yafang Shao <laoar.shao@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20220409125958.92629-4-laoar.shao@gmail.com

 src/common.c     | 8 --------
 src/feature.c    | 2 --
 src/main.c       | 6 +++---
 src/main.h       | 2 --
 src/map.c        | 2 --
 src/pids.c       | 1 -
 src/prog.c       | 3 ---
 src/struct_ops.c | 2 --
 8 files changed, 3 insertions(+), 23 deletions(-)
 ```

**Comment by pchaigno** [comment] 2022-06-14 12:38
I've set `release-blocker/1.12` given we need to fix this to fix all GKE (in GitHub and in Jenkins) CI. I think we want to do that before releasing. There is a patch in review upstream; I'll pick it up in Cilium as soon as it's merged.

**Closed as completed** 2022-06-20 07:15 UTC
Labels: priority/high, area/CI, ci/flake
