### ISSUE TITLE
K8sHealthTest checks cilium-health status between nodes

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#12445] opened 2020-07-07 14:26 UTC
```
/home/jenkins/workspace/cilium-master-K8s-all/1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Expected
    <string>: 
not to be empty
/home/jenkins/workspace/cilium-master-K8s-all/1.17-gopath/src/github.com/cilium/cilium/test/k8sT/Health.go:110/
```

https://jenkins.cilium.io/job/cilium-master-K8s-all/348/testReport/junit/Suite-k8s-1/17/K8sHealthTest_checks_cilium_health_status_between_nodes/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.18-Pipeline/641/testReport/junit/Suite-k8s-1/18/K8sHealthTest_checks_cilium_health_status_between_nodes/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.18-Pipeline/672/testReport/junit/Suite-k8s-1/18/K8sHealthTest_checks_cilium_health_status_between_nodes/
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/5101/testReport/junit/Suite-k8s-1/18/K8sHealthTest_checks_cilium_health_status_between_nodes/

logs from last link:
[74058caf_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/4885419/74058caf_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by christarazi** [comment] 2020-07-16 17:30
Is this a duplicate of https://github.com/cilium/cilium/issues/6728?

**Closed as completed** 2020-09-07 09:38 UTC
Labels: kind/bug/CI
