### ISSUE TITLE
wireguard: use TRACE_REASON_ENCRYPTED

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#34659] opened 2024-09-03 09:48 UTC
Flag Cilium's wireguard traffic with `TRACE_REASON_ENCRYPTED`, similar as we do today for IPsec.

**Comment by smagnani96** [comment] 2024-09-03 09:58
I can get assigned to this issue :smiley:

**Comment by gandro** [comment] 2024-09-19 14:45
Regarding the **Expected Behavior**: Does it really make sense to only declare the UDP packets with with `encrypted` bit? I mean, technically it is correct, but is it also useful? If you see UDP traffic with port 51871 then you can somewhat safely assume that it is WireGuard traffic. But as a user, we have no clue what kind of packet this was, since the inner saddr/daddr are completely lost.

I think much more useful would be if we had a trace event with *the inner* packet that says if the packet was send to or received from the WireGuard device. Basically emit an event when a packet is redirected to the cilium_wg0 device - and emit an event if a packet is received on cilium_wg0 (I think we attach `from_netdev` to `cilium_wg0` for reverse NAT, so maybe there is a trace opportunity there)

**Comment by julianwiedmann** [comment] 2024-09-19 17:33
>Which mark should be used? Right now I would insert a new #define MARK_MAGIC_WG_DECRYPT 0x2D00 that overlaps with k8s space, but should be safe to use. However, my ideal solution would be to remove both MARK_MAGIC_WG_DECRYPT and MARK_MAGIC_WG_ENCRYPTED in favor of MARK_MAGIC_ENCRYPT and MARK_MAGIC_DECRYPT, 

There's a minor chance that some parts of the datapath (BPF, netfilter, routing?) are checking for `MARK_MAGIC_ENCRYPT` / `MARK_MAGIC_DECRYPT`, and are not properly guarded by an "is IPsec enabled?" check. But agree, ideally we share the magic values between WG and IPsec.

**Comment by julianwiedmann** [comment] 2024-09-19 17:34
@gandro I feel what you're suggesting is more along new `TRACE_{TO_FROM}_{XFRM,WIREGUARD}` observation points?

**Comment by smagnani96** [comment] 2024-09-20 07:23
> There's a minor chance that some parts of the datapath (BPF, netfilter, routing?) are checking for MARK_MAGIC_ENCRYPT / MARK_MAGIC_DECRYPT, and are not properly guarded by an "is IPsec enabled?" check. But agree, ideally we share the magic values between WG and IPsec.

This is indeed true, a few portions are not guarded now with the "is IPSec enabled" check, but it shouldn't take a lot to change, let me have a look on this too :muscle:

**Comment by smagnani96** [comment] 2024-09-20 07:50
> @ gandro I feel what you're suggesting is more along new TRACE_{TO_FROM}_{XFRM,WIREGUARD} observation points?

I wanted to implement this later, at first I though that marking the outer packet as encrypted would be enough. But as Sebastian mentioned, from the user-perspective that could be poorly informative.

So now I'm thinking of using `TRACE_{TO,FROM}_CRYPTO_DEV` and of course the TRACE_REASON_ENCRYPTED. For the ingress packet, that would make the `cilium-dbg` output as follows:

```bash
:<- crypt_dev encrypted flow 0x0 , identity 46095->unknown state unknown ifindex cilium_vxlan orig-ip 0.0.0.0: 10.244.1.195 -> 10.244.2.169 EchoReply
```

Still, I need to figure out how to log the egress path...

This wouldn't need to introduce the parsing logic on incoming packets to check whether is WG traffic, but would rely on on the WG device marking the packets: if succeeding, that means those packets were valid WG traffic and, when being fwd after enc/dec to the host again, we can emit the trace.

Many thanks to both of you for the feedback!

**Comment by gandro** [comment] 2024-09-24 09:01
> @gandro I feel what you're suggesting is more along new `TRACE_{TO_FROM}_{XFRM,WIREGUARD}` observation points?

I think my point mainly centers around the fact that I believe we want to provide Hubble the context (source and destination pods) of packets before they are encrypted, not after encryption where this information is lost. 

If there is another way to mark plaintext packets in the existing observation points then that would be great. But it seems like that's not the case (at least for ingress), so yeah maybe this is only possible by adding additional trace points.

**Comment by smagnani96** [comment] 2024-09-25 12:39
> > @gandro I feel what you're suggesting is more along new `TRACE_{TO_FROM}_{XFRM,WIREGUARD}` observation points?
> 
> I think my point mainly centers around the fact that I believe we want to provide Hubble the context (source and destination pods) of packets before they are encrypted, not after encryption where this information is lost and there is no added value anymore. Basically the use case I have in mind is that the user can query Hubble "show me that the traffic from pod X is encrypted" - which is not possible if we only trace the encrypted packet which no longer has source addr X.
> 
> If there is another way to mark plaintext packets in the existing observation points then that would be great. But it seems like that's not the case (at least for ingress), so yeah maybe this is only possible by adding additional trace points.

I see your point, and I think it is possible to provide the required context (source and destination pods) while tracing packet in native routing. I'm currently working on this and it seems fairly possible.

However, things change when Overlay is enabled, especially for egress path, for which the flow of a packet is `endpoint -> overlay -> host -> wireguard -> host  -> outside`:  to provide the correct context for the outgoing packets, we'd need to trace before the packet gets encap in the overlay, but tracing the `encrypt` event so early in time this seems a huge assumption ...

**Comment by smagnani96** [comment] 2024-09-27 21:34
I just updated the investigation above (https://github.com/cilium/cilium/issues/34659#issuecomment-2360392328) and the related PR. Happy to further discuss :smiley:

**Comment by smagnani96** [comment] 2024-10-02 12:05
After discussing with @jschwinger233 (who started reviewing the PR https://github.com/cilium/cilium/pull/34958, we agreed that these additions should be discussed in a separate issue and be introduced in a different PR. The context of this issue is to provide an aligned behavior between IPSec and Wireguard while using the TRACE_REASON_ENCRYPTED. So far, in the IPSec datapath we trace with the encrypted reason the actually encrypted packet. The changes proposed in the PR seems to be useful, but we should treat them as a separate topic.

For this reason, I'm converting back the PR to draft and will use it to address a new issue that I will open.
For this issue, I'll soon propose a PR with the mere tracing with the encrypted flag of incoming/outgoing WG-encrypted packets.

**Closed as completed** 2024-10-10 12:57 UTC
Labels: kind/enhancement, area/datapath, area/monitor, area/encryption, feature/wireguard
