### ISSUE TITLE
BGP CP: Add `externalTrafficPolicy: Local` support for service announcements

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#23035] opened 2023-01-11 10:42 UTC
PR #22397 added the ability to announce LoadBalancer IPs of services, but this implementation lacks support for the `externalTrafficPolicy` field.
 
 The description of this field according to the reference in the [k8s docs](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/) is:
 > externalTrafficPolicy describes how nodes distribute service traffic they receive on one of the Service's "externally-facing" addresses (NodePorts, ExternalIPs, and LoadBalancer IPs). If set to "Local", the proxy will configure the service in a way that assumes that external load balancers will take care of balancing the service traffic between nodes, and so each node will deliver traffic only to the node-local endpoints of the service, without masquerading the client source IP. (Traffic mistakenly sent to a node with no endpoints will be dropped.) The default value, "Cluster", uses the standard behavior of routing to all endpoints evenly (possibly modified by topology and other features). Note that traffic sent to an External IP or LoadBalancer IP from within the cluster will always get "Cluster" semantics, but clients sending to a NodePort from within the cluster may need to take traffic policy into account when picking a node.

So if the user sets the `externalTrafficPolicy` to `Local` we should assume that ECMP is implemented and configured on the BGP peers according to the wishes of the user and only announce routes with next hops of nodes which have a service-endpoint for the given service.

NOTE: Currently the BGP Control Plane only announces next hops of the nodes with BGP speakers, if the subset of nodes with speakers and service-endpoints don't overlap, no announcement will be made. This should be mentioned in the documentation associated with the feature until the BGP Control Plane is able to produce next-hops for nodes without speakers.

**Comment by Jean-Daniel** [comment] 2023-01-14 15:16
While designing this feature, would it be possible to consider supporting **Weighted ECMP over BGP**.

This feature has a good description in the [FRR documentation](http://docs.frrouting.org/en/latest/bgp.html#weighted-ecmp-using-bgp-link-bandwidth), and is supported by most hardware ([Cisco](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus3000/sw/unicast/93x/configuration/guide/b-cisco-nexus-3000-series-nx-os-unicast-routing-configuration-guide-93x/b-cisco-nexus-3000-series-nx-os-unicast-routing-configuration-guide-93x_chapter_01101.html#id_69077), …).

When using Local traffic policy, it should be use to direct more traffic to a node that has multiple pods matching the service.

For instance, with a replica of 3 pods, if a node `A` has 2 pods, and a node `B` has 1 pod, 2 third of the traffic should be send to node `A` and one third to node `B`.

If can be done by announcing the path from node A with twice the bandwidth of node B.

**Comment by dylandreimerink** [comment] 2023-01-14 16:34
@Jean-Daniel I can imagine a few scenarios where weighted ECMP can be really useful, thanks for the suggestion, wasn't on my radar yet. I did a quick peek at what we need to do from a BGP perspective to make this work. 

Seems that the feature is based on [this](https://datatracker.ietf.org/doc/html/draft-ietf-idr-link-bandwidth) draft. The draft standard proposed an extended community be used to transfer an indication of link speed which would be encoded as bytes/s in 32-bit IEEE float format in that community.

According to the spec the ratio between the next hop capacities would be used for the weighting in a resolution from 1 to 100. 

While there is some overlap in implementation (both features will need to look at the location of service backends), I think weighted ECMP deserves its own issue and incremental PR. For one, I think that weighted ECMP has a place in if the external traffic policy is set to `Cluster` as well for a number of reasons. 

Secondly, announcing "fake" bandwidth information might have some implications. Ideally we would want to use actual bandwidth information from the nodes, just in case a router implementation gets funny ideas about artificially limiting based on this indication, which is additional work. Moreover, we would have to coordinate these fractions over multiple nodes which might be tricky, again work or at least not something we can easily tack onto the current issue.

Please feel free to open a [CFP](https://github.com/cilium/cilium/issues/new?assignees=&labels=kind%2Ffeature&template=feature_template.md&title=CFP%3A+) for this though, seems promising.

**Comment by camrossi** [comment] 2023-01-15 19:56
I would also suggest that weighted ECMP if/when implemented should be an optional feature  as I can imagine not every switch vendor might support this :)

**Comment by rwagoner** [comment] 2023-02-15 15:38
I've been testing the BGP Control Plane service announcement feature in v1.13.0-rc5, but without the `externalTrafficPolicy: Local` support I won't be able to migrate to it. Are there plans to implement this request in a future version?

**Comment by raymonddejong** [comment] 2023-04-04 07:46
IKEA asked what release this would be available. From this [thread](https://isovalent.slack.com/archives/C036D1MNKNG/p1680544082554719) I understand it will be in 1.14 OSS en CEE releases.

**Comment by CRASH-Tech** [comment] 2023-04-11 12:16
Any progress?

**Comment by log1cb0mb** [comment] 2023-05-05 22:36
Lack of this feature in some environments also affects using loadbalancer mode: DSR and forced to use SNAT instead. This is a crucial functionality.

**Comment by J0n4t4n** [comment] 2023-05-23 08:27
Just ran into an issue with this, as I mindlessly set `externalTrafficPolicy: Local` on a Service and Cilium kept advertising all of my 3 nodes as possible targets for the Service via BGP.
My Router then send the traffic to Node 2, while the Pod with the Service was on Node 3 and thus no traffic could be received.
Having the BGP announcement align with where the Pod is actually scheduled would be very nice.

**Comment by log1cb0mb** [comment] 2023-05-26 23:18
https://github.com/cilium/cilium/pull/25477

**Comment by YutaroHayakawa** [comment] 2023-06-07 05:58
Now we have merged https://github.com/cilium/cilium/pull/25477. Closing.

**Closed as completed by YutaroHayakawa** 2023-06-07 05:58 UTC
Labels: kind/enhancement, area/datapath, area/bgp

**Comment by camrossi** [comment] 2023-06-07 20:09
Just tested with the latest image and I can confirm it works perfectly fine!

```
kubectl -n gb get pod -o wide -l tier=frontend
NAME                        READY   STATUS    RESTARTS   AGE     IP              NODE       NOMINATED NODE   READINESS GATES
frontend-556f857fb9-7dmq2   1/1     Running   0          6d15h   192.168.19.93   pi-k8s-3   <none>           <none>**

Leaf203# show ip route 192.168.21.186 vrf rpi-k8s:vrf
192.168.21.186/32, ubest/mbest: 1/0
    *via 192.168.18.3%rpi-k8s:vrf, [20/0], 00:03:19, bgp-65002, external, tag 65003
         recursive next hop: 192.168.18.3/32%rpi-k8s:vrf

kubectl -n gb get pod -o wide -l tier=frontend
NAME                        READY   STATUS    RESTARTS   AGE     IP              NODE       NOMINATED NODE   READINESS GATES
frontend-556f857fb9-7dmq2   1/1     Running   0          6d15h   192.168.19.93   pi-k8s-3   <none>           <none>
frontend-556f857fb9-b4fhw   1/1     Running   0          12s     192.168.19.3    pi-k8s-2   <none>           <none>
frontend-556f857fb9-rmf6d   1/1     Running   0          12s     192.168.19.59   pi-k8s-1   <none>           <none>

Leaf203# show ip route 192.168.21.186 vrf rpi-k8s:vrf
IP Route Table for VRF "rpi-k8s:vrf"

192.168.21.186/32, ubest/mbest: 3/0
    *via 192.168.18.2%rpi-k8s:vrf, [20/0], 00:00:38, bgp-65002, external, tag 65003
         recursive next hop: 192.168.18.2/32%rpi-k8s:vrf
    *via 192.168.18.1%rpi-k8s:vrf, [20/0], 00:00:38, bgp-65002, external, tag 65003
         recursive next hop: 192.168.18.1/32%rpi-k8s:vrf
    *via 192.168.18.3%rpi-k8s:vrf, [20/0], 00:07:10, bgp-65002, external, tag 65003
         recursive next hop: 192.168.18.3/32%rpi-k8s:vrf

```
Thank you @YutaroHayakawa for working on this feature!

**Comment by log1cb0mb** [comment] 2023-06-08 08:17
@YutaroHayakawa  Is it safe to assume that this feature by design will work with any LB type (specifically) service? I am trying to understand how this will behave with for e.g GatewayAPI gateway service and same for cilium's integrated ingress controller where essentially attached service i.e cilium-agent is on every node so will the proxy to target backend service will follow this Local policy?

**Comment by YutaroHayakawa** [comment] 2023-06-09 10:03
This feature is all about the `type: LoadBalancer` service VIP advertisement. So, not relevant to `NodePort` or `ClusterIP`. I'm not fully sure about the Ingress/GatewayAPI, but if you are using the `type: LoadBalancer` service to direct traffic from an external client to Ingress/Gateway proxy, then the answer is yes in theory. I don't know if it makes sense to advertise the VIP of the services behind the Ingress/Gateway.

**Comment by YutaroHayakawa** [comment] 2023-06-16 08:17
@log1cb0mb If you are talking about the services that are automatically created by Ingress/GatewayAPI (the service to reach the Ingress/Gateway itself), I wouldn't recommend you set `externalTrafficPolicy: Local` to those services, because they don't have any endpoints, so it just stops advertisement.

**Comment by log1cb0mb** [comment] 2023-06-16 10:28
Yes, that is exactly what I was after. Those automatic LB services created by GWAPI and Cilium's Ingress controller but makes sense.

I was just trying to confirm if there is a further way to eliminate potential extra hop with those services.
