### ISSUE TITLE
Issues running with --sockops-enable, can no longer access k8s API

### ISSUE THREAD

**Issue by amshinde** [cilium/cilium#7327] opened 2019-03-07 00:10 UTC
On using sockops feature with 
```
https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/1.13/cilium-crio.yaml
```
While cilium is being brought up, k8s api is no longer accessible
```
$ kubectl get pods 
Unable to connect to the server: EOF
```

**Comment by amshinde** [comment] 2019-03-07 00:11
@jrfastab Can you take a look?

**Comment by jrfastab** [comment] 2019-03-07 14:07
I'll take a look thanks.

**Comment by nirmoy** [comment] 2019-03-08 09:05
@amshinde I couldn't reproduce it on my setup, what version of kernel are you using ?

**Comment by amshinde** [comment] 2019-03-08 21:05
@nirmoy I am running kernel 4.19.24. Can you let me know what kernel version you are using. 
Can you post your kernel config as well?

**Comment by nirmoy** [comment] 2019-03-10 14:26
I am using 4.20.10-1, I think 4.19.24 should work.
kernel config: https://gist.github.com/nirmoy/8d79fbb77b1533f5926a71e51b578bb9

**Comment by amshinde** [comment] 2019-03-27 23:52
@nirmoy Didtnt get a chance to take another look at this until today.
So I tried this on a different machine with 5.0.5 kernel and got it working.
Will try to see what was causing the issue on the other machine. I did have all necessary kernel configs in there.

**Comment by jrfastab** [comment] 2019-04-22 16:21
@amshinde there has been a few fixes on sockmap side is this working on your side now?

**Comment by Jean-Daniel** [comment] 2022-12-12 09:24
I'm running a cluster on a Ubuntu node, and got hit by the same bug with the last LTS kernel update (`5.15.0-56-generic #62-Ubuntu`):

Trying to accessing the locally running api-server fails with the following error:

```
* Failed sending HTTP2 data
* Connection #0 to host 172.22.0.13 left intact
curl: (16) OpenSSL SSL_write: Broken pipe, errno 32
```

The error occurs with both cilium 1.12.4 and cilium 1.13-rc03.

The previous Kernel I was using was `5.15.0-52-generic #58-Ubuntu`, so this is caused by a change between this 2 releases.

I can reliably reproduce the issue by creating a simple empty cluster with kubeadm, and just installing cilium after that.

**Comment by brb** [comment] 2023-05-24 14:18
The sockops feature was removed from Cilium (https://github.com/cilium/cilium/issues/23556). Closing the issue.

**Closed as completed by brb** 2023-05-24 14:18 UTC
Labels: kind/bug, area/datapath
