### ISSUE TITLE
Applying CiliumNetworkPolicy `client-egress-to-cidrgroup-deny` from connectivity test `client-egress-to-cidrgroup-deny` crashes v1.14.15 agent

### ISSUE THREAD

**Issue by jpayne3506** [cilium/cilium#36494] opened 2024-12-11 00:30 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

- v0.16.12 CLI
- v1.14.15 Agent 

### What happened?

When using multiple cilium clusters I expect test failures from the CLI and agent mismatch. In this case 
- v0.16.12 CLI
- v1.14.15 Agent 

The cilium connectivity test `client-egress-to-cidrgroup-deny` applies a cnp that sig faults the agent
>   ℹ️  Cilium agent kube-system/cilium-7mgwg logs since 2024-12-10 15:46:50.922914513 -0800 PST m=+122.065138308:
2024-12-10T23:47:03.095353564Z time="2024-12-10T23:47:03Z" level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"k8s:io.kubernetes.pod.namespace\":\"cilium-test-1\"}} NodeSelector:{} Ingress:[] IngressDeny:[] Egress:[{EgressCommonRule:{ToEndpoints:[{\"matchLabels\":{\"k8s:io.kubernetes.pod.namespace\":\"cilium-test-1\"}}] ToRequires:[] ToCIDR: ToCIDRSet:[] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[]} ToPorts:[] ToFQDNs:[] ICMPs:[] Authentication:<nil>} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR:[0.0.0.0/0] ToCIDRSet:[] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc000875aa0 requirements:0xc00011b548 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{reserved.world: ,},MatchExpressions:[]LabelSelectorRequirement{},}} {LabelSelector:0xc000ea59e0 requirements:0xc001eae900 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.0.0.0.0/0: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[] ToFQDNs:[] ICMPs:[] Authentication:<nil>}] EgressDeny:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=CiliumNetworkPolicy k8s:io.cilium.k8s.policy.name=allow-all-egress k8s:io.cilium.k8s.policy.namespace=cilium-test-1 k8s:io.cilium.k8s.policy.uid=79f6ab08-29a5-4209-89d9-fb4920a961e9] Description:}]" policyAddRequest=bbb7f2f8-9ee2-48f9-b385-febb532d5e6e subsys=daemon
2024-12-10T23:47:03.104710511Z time="2024-12-10T23:47:03Z" level=info msg="Policy imported via API, recalculating..." policyAddRequest=bbb7f2f8-9ee2-48f9-b385-febb532d5e6e policyRevision=3 subsys=daemon
2024-12-10T23:47:03.104727211Z time="2024-12-10T23:47:03Z" level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=allow-all-egress k8sApiVersion= k8sNamespace=cilium-test-1 subsys=k8s-watcher
2024-12-10T23:47:03.107108323Z time="2024-12-10T23:47:03Z" level=info msg="Re-pinning map with ':pending' suffix" bpfMapName=cilium_calls_00674 bpfMapPath=/sys/fs/bpf/tc/globals/cilium_calls_00674 subsys=bpf
2024-12-10T23:47:03.108104729Z time="2024-12-10T23:47:03Z" level=info msg="Re-pinning map with ':pending' suffix" bpfMapName=cilium_calls_02673 bpfMapPath=/sys/fs/bpf/tc/globals/cilium_calls_02673 subsys=bpf
2024-12-10T23:47:03.268005135Z time="2024-12-10T23:47:03Z" level=info msg="Unpinning map after successful recreation" bpfMapName=cilium_calls_00674 bpfMapPath="/sys/fs/bpf/tc/globals/cilium_calls_00674:pending" subsys=bpf
2024-12-10T23:47:03.268344536Z time="2024-12-10T23:47:03Z" level=info msg="Rewrote endpoint BPF program" containerID=80feebf414 datapathPolicyRevision=2 desiredPolicyRevision=3 endpointID=674 identity=13485 ipv4=192.168.1.145 ipv6= k8sPodName=cilium-test-1/echo-same-node-ff6f76ccc-6zqg4 subsys=endpoint
2024-12-10T23:47:03.284024415Z time="2024-12-10T23:47:03Z" level=info msg="Unpinning map after successful recreation" bpfMapName=cilium_calls_02673 bpfMapPath="/sys/fs/bpf/tc/globals/cilium_calls_02673:pending" subsys=bpf
2024-12-10T23:47:03.284840219Z time="2024-12-10T23:47:03Z" level=info msg="Rewrote endpoint BPF program" containerID=8b28e5e6a0 datapathPolicyRevision=2 desiredPolicyRevision=3 endpointID=2673 identity=14046 ipv4=192.168.1.235 ipv6= k8sPodName=cilium-test-1/client2-57cf4468f-gh7fd subsys=endpoint
2024-12-10T23:47:03.287392432Z time="2024-12-10T23:47:03Z" level=info msg="Re-pinning map with ':pending' suffix" bpfMapName=cilium_calls_00283 bpfMapPath=/sys/fs/bpf/tc/globals/cilium_calls_00283 subsys=bpf
2024-12-10T23:47:03.430177652Z time="2024-12-10T23:47:03Z" level=info msg="Unpinning map after successful recreation" bpfMapName=cilium_calls_00283 bpfMapPath="/sys/fs/bpf/tc/globals/cilium_calls_00283:pending" subsys=bpf
2024-12-10T23:47:03.430206452Z time="2024-12-10T23:47:03Z" level=info msg="Rewrote endpoint BPF program" containerID=bf14f005b9 datapathPolicyRevision=2 desiredPolicyRevision=3 endpointID=283 identity=25905 ipv4=192.168.1.149 ipv6= k8sPodName=cilium-test-1/client-7b7776c86b-cj26x subsys=endpoint
2024-12-10T23:47:03.797727305Z panic: runtime error: invalid memory address or nil pointer dereference
2024-12-10T23:47:03.797981406Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x541120]
2024-12-10T23:47:03.798023107Z
2024-12-10T23:47:03.798028507Z goroutine 337 [running]:
2024-12-10T23:47:03.798032207Z net.networkNumberAndMask(0xc0033f0f38?)
2024-12-10T23:47:03.798036107Z  /usr/local/go/src/net/ip.go:425
2024-12-10T23:47:03.798039407Z net.(*IPNet).Contains(0xc0033f0f38?, {0xc0033f0f3c, 0x4, 0xc0033f0f34?})
2024-12-10T23:47:03.798043207Z  /usr/local/go/src/net/ip.go:449 +0x25
2024-12-10T23:47:03.798046707Z github.com/cilium/cilium/pkg/ip.RemoveCIDRs({0xc003120630, 0x1, 0x1}, {0xc000774088, 0x1, 0x1})
2024-12-10T23:47:03.798050507Z  /go/src/github.com/cilium/cilium/pkg/ip/ip.go:172 +0x16c
2024-12-10T23:47:03.798123507Z github.com/cilium/cilium/pkg/policy/api.ComputeResultantCIDRSet({0xc000ea6c80?, 0x369acc0?, 0x1?})
2024-12-10T23:47:03.798130107Z  /go/src/github.com/cilium/cilium/pkg/policy/api/cidr.go:157 +0x10e
2024-12-10T23:47:03.798134107Z github.com/cilium/cilium/pkg/policy/api.CIDRRuleSlice.GetAsEndpointSelectors({0xc000ea6c80?, 0xc000ea6c80?, 0x1?})
2024-12-10T23:47:03.798137507Z  /go/src/github.com/cilium/cilium/pkg/policy/api/cidr.go:128 +0x18
2024-12-10T23:47:03.798141007Z github.com/cilium/cilium/pkg/policy/api.(*EgressCommonRule).getAggregatedSelectors(0xc000d64780)
2024-12-10T23:47:03.798144407Z  /go/src/github.com/cilium/cilium/pkg/policy/api/egress.go:225 +0x2a9
2024-12-10T23:47:03.798147707Z github.com/cilium/cilium/pkg/policy/api.(*EgressCommonRule).SetAggregatedSelectors(...)
2024-12-10T23:47:03.798217408Z  /go/src/github.com/cilium/cilium/pkg/policy/api/egress.go:258
2024-12-10T23:47:03.798222808Z github.com/cilium/cilium/pkg/k8s/apis/cilium.io/utils.parseToCiliumEgressDenyRule({0xc0033f0ee0, 0xd}, {0xc000490da0?, 0xc001d321f8?, {0xc000de6070?, 0x1b7?}}, {0xc000d644b0, 0x1, 0x8000109db?})
2024-12-10T23:47:03.798226108Z  /go/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/utils/utils.go:273 +0x3c5
2024-12-10T23:47:03.798229808Z github.com/cilium/cilium/pkg/k8s/apis/cilium.io/utils.ParseToCiliumRule({0xc0033f0ee0, 0xd}, {0xc000e100a0, 0x1f}, {0xc001de4000, 0x24}, 0xc002b38000)
2024-12-10T23:47:03.798233008Z  /go/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/utils/utils.go:329 +0x6b0
2024-12-10T23:47:03.798236108Z github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNetworkPolicy).Parse(0xc0004948c0)
2024-12-10T23:47:03.798239208Z  /go/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/cnp_types.go:222 +0x1d0
2024-12-10T23:47:03.798260108Z github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumNetworkPolicyV2(0xc001e80008, {0x7fb088048490, 0xc0009f96b0}, 0xc000774030, {0x35cd7c0?, 0x0?, 0x5dba740?}, {0xc001442400, 0x31})
2024-12-10T23:47:03.798264808Z  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:309 +0x2b5
2024-12-10T23:47:03.798270908Z github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).onUpsert(0xc001e80008, 0xc0014ffae8, 0xc003121eb8, {{0xc000e100a0, 0x1f}, {0xc0033f0ee0, 0xd}}, 0xc0014ffd38, {0x3d8f848, 0xc0009f96b0}, ...)
2024-12-10T23:47:03.798274308Z  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:269 +0x491
2024-12-10T23:47:03.798277508Z github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNetworkPoliciesInit.func1()
2024-12-10T23:47:03.798280608Z  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:138 +0xca5
2024-12-10T23:47:03.798287908Z created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNetworkPoliciesInit in goroutine 1
2024-12-10T23:47:03.798291508Z  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:89 +0x109

### How can we reproduce the issue?

1. Create AKS BYOCNI or Azure CNI Powered by Cilium AKS cluster
2. Install v1.14.15 cilium via helm or consume v1.14.15 through AKS
3. Install CLI v0.16.21
4. run `cilium connectivity test --test 'client-egress-to-cidrgroup-deny' `

### Cilium Version

v1.14.15

### Kernel Version

5.15.0-1074-azure #83-Ubuntu SMP Wed Oct 2 18:14:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.30.6

### Sysdump

[cilium-sysdump-20241210-162357.zip](https://github.com/user-attachments/files/18087759/cilium-sysdump-20241210-162357.zip)

### Relevant log output

```shell
time="2024-12-11T00:12:34Z" level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"k8s:app\":\"konnectivity-agent\",\"k8s:io.kubernetes.pod.namespace\":\"kube-system\"}} NodeSelector:{} Ingress:[] IngressDeny:[] Egress:[{EgressCommonRule:{ToEndpoints:[{}] ToRequires:[] ToCIDR: ToCIDRSet:[] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[]} ToPorts:[] ToFQDNs:[] ICMPs:[] Authentication:<nil>}] EgressDeny:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=NetworkPolicy k8s:io.cilium.k8s.policy.name=konnectivity-agent k8s:io.cilium.k8s.policy.namespace=kube-system k8s:io.cilium.k8s.policy.uid=c9903ae3-8159-405e-a9ce-d1dac519bdcc] Description:}]" policyAddRequest=b61d2e9d-9a38-4bac-9a37-6e25a493cb9e subsys=daemon
time="2024-12-11T00:12:34Z" level=info msg="Policy imported via API, recalculating..." policyAddRequest=b61d2e9d-9a38-4bac-9a37-6e25a493cb9e policyRevision=2 subsys=daemon
time="2024-12-11T00:12:34Z" level=info msg="NetworkPolicy successfully added" k8sApiVersion= k8sNetworkPolicyName=konnectivity-agent subsys=k8s-watcher
time="2024-12-11T00:12:34Z" level=info msg="Node updated" clusterName=jpaynepoc1-1 nodeName=aks-nodepool1-22864064-vmss000000 subsys=nodemanager
time="2024-12-11T00:12:34Z" level=info msg="Node updated" clusterName=jpaynepoc1-1 nodeName=aks-nodepool1-22864064-vmss000001 subsys=nodemanager
time="2024-12-11T00:12:34Z" level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"k8s:io.kubernetes.pod.namespace\":\"cilium-test-1\"}} NodeSelector:{} Ingress:[] IngressDeny:[] Egress:[{EgressCommonRule:{ToEndpoints:[{\"matchLabels\":{\"k8s:io.kubernetes.pod.namespace\":\"cilium-test-1\"}}] ToRequires:[] ToCIDR: ToCIDRSet:[] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[]} ToPorts:[] ToFQDNs:[] ICMPs:[] Authentication:<nil>} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR:[0.0.0.0/0] ToCIDRSet:[] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0007d8da0 requirements:0xc000010be8 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{reserved.world: ,},MatchExpressions:[]LabelSelectorRequirement{},}} {LabelSelector:0xc0003b3320 requirements:0xc000b3f5a8 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.0.0.0.0/0: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[] ToFQDNs:[] ICMPs:[] Authentication:<nil>}] EgressDeny:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=CiliumNetworkPolicy k8s:io.cilium.k8s.policy.name=allow-all-egress k8s:io.cilium.k8s.policy.namespace=cilium-test-1 k8s:io.cilium.k8s.policy.uid=0bfd0753-2f60-411c-9d82-490c0cde02fe] Description:}]" policyAddRequest=28a22cd9-132b-49ff-81be-ab07fbbae3bb subsys=daemon
time="2024-12-11T00:12:34Z" level=info msg="Policy imported via API, recalculating..." policyAddRequest=28a22cd9-132b-49ff-81be-ab07fbbae3bb policyRevision=3 subsys=daemon
time="2024-12-11T00:12:34Z" level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=allow-all-egress k8sApiVersion=cilium.io/v2 k8sNamespace=cilium-test-1 subsys=k8s-watcher
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x541120]
```

### Anything else?

Issue originally raised on AKS: https://github.com/Azure/AKS/issues/4691 

Test does not exist in CLI v0.15.22. 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2024-12-12 18:07
Thanks for the report. Definitely a bug, Cilium shouldn't crash when given invalid input.

For what it's worth I tried to reproduce this with the latest versions and I could not reproduce it, but primarily because the latest CLI attempts to detect that Cilium version 1.17.0 or later is used before running the test. When I switched to CLI v0.16.21 I could reproduce the issue you report, with Cilium v1.14.17 and v1.15.11. I could not reproduce with v1.16.4.

I suspect what's going on is that a policy with a CIDRGroup and an `except` clause was never intentionally supported (or tested), but it is expressible in the API. As a result, if you create a network policy that has a valid reference to a cidr group as well as an except statement, but no primary CIDR match, then Cilium attempts to subtract the "except" CIDR from the "main" CIDR (which doesn't exist), leading to the crash.

We probably need to do a few things here to solve this issue:
- Avoid setting the aggregated selectors before validation/sanitization of rules (should be applied on `main` and backported to all branches)
- Ensure that the validation/sanitization of rules detects and rejects this combination (specifically targeted to v1.14/v1.15 branches)
- Add tests for this pattern (ideally via unit or integration tests) (also for `main`)

**Comment by pippolo84** [comment] 2024-12-13 10:05
Fixed by https://github.com/cilium/cilium/pull/36559

**Closed as completed by pippolo84** 2024-12-13 10:05 UTC
Labels: kind/bug, sig/policy, kind/community-report, area/agent

**Comment by joestringer** [comment] 2024-12-13 13:20
Thanks for the quick fix @pippolo84 🙏 . Given the timing of the fix I would expect this to be fixed in the January patch releases for each maintained branch. The v1.15 version can be found here: https://github.com/cilium/cilium/pull/36560.

**Comment by tamilmani1989** [comment] 2024-12-17 18:38
Thanks @pippolo84 . can this be backported to 1.14 too?

**Comment by pippolo84** [comment] 2024-12-17 18:40
> Thanks @pippolo84 . can this be backported to 1.14 too?

Yep, https://github.com/cilium/cilium/pull/36559 targeted v1.14 branch.
