### ISSUE TITLE
CI: Conformance AKS: QuotaExceeded

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#31859] opened 2024-04-09 11:21 UTC
From: https://github.com/cilium/cilium/actions/runs/8604699997/job/23579380133 and https://github.com/cilium/cilium/actions/runs/8559275029/job/23455717594 most recently.
```
ERROR: (QuotaExceeded) Preflight validation check for resource(s) for container service cilium-cilium-8559275029-1-3 in resource group MC_cilium-cilium-8559275029-1-3_cilium-cilium-8559275029-1-3_eastus2 failed. Message: Operation could not be completed as it results in exceeding approved standardBSFamily Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus2, Current Limit: 50, Current Usage: 48, Additional Required: 4, (Minimum) New Limit Required: 52. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22986ec55c-1e77-4e2e-9ca5-dcbb34c7a110%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22eastus2%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22standardBSFamily%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:52,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22standardBSFamily%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests. Details: 
Code: QuotaExceeded
Message: Preflight validation check for resource(s) for container service cilium-cilium-8559275029-1-3 in resource group MC_cilium-cilium-8559275029-1-3_cilium-cilium-8559275029-1-3_eastus2 failed. Message: Operation could not be completed as it results in exceeding approved standardBSFamily Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus2, Current Limit: 50, Current Usage: 48, Additional Required: 4, (Minimum) New Limit Required: 52. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22986ec55c-1e77-4e2e-9ca5-dcbb34c7a110%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22eastus2%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22standardBSFamily%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:52,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22standardBSFamily%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests. Details: 
Error: Process completed with exit code 1.
```

**Comment by brlbil** [comment] 2024-04-09 12:58
The quotas have been increased. We can keep the issue open until we can confirm the problem is not recurring.

**Comment by brlbil** [comment] 2024-04-11 09:31
The problem is not recurring. I am closing the issue.

**Closed as completed by brlbil** 2024-04-11 09:31 UTC
Labels: area/CI, ci/flake
