### ISSUE TITLE
Running geneve ends in nil pointer dereference on kind

### ISSUE THREAD

**Issue by darox** [cilium/cilium#28245] opened 2023-09-21 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Create kind cluster
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
```
2. Install Cilium
```
helm install cilium cilium/cilium --version 1.14.2 \
--namespace kube-system \
--set tunnel=geneve 
```
3. Check status of pods
```
kubectl get pods -A
```

### Cilium Version

1.14.2

### Kernel Version

Linux ubuntu 6.4.16-orbstack-00103-g02b40eb69695 #1 SMP Wed Sep 13 10:13:30 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: v1.27.3

### Sysdump

[cilium-sysdump-20230921-143250.zip](https://github.com/cilium/cilium/files/12684544/cilium-sysdump-20230921-143250.zip)

### Relevant log output

```
level=fatal msg="failed to start: daemon creation failed: error while initializing daemon: failed while reinitializing datapath: exit status 1" subsys=daemon
level=warning msg="Failed to apply L7 proxy policy changes. These will be re-applied in future updates." error="context cancelled before waiting for proxy updates: context canceled" subsys=endpoint-manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee7168]

goroutine 575 [running]:
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Observe(0x34316e8?, {0x34316b0?, 0x40003bf590?}, 0x2220202020202020?, 0x226d756d696e696d?)
        <autogenerated>:1 +0x28
github.com/cilium/cilium/pkg/stream.First[...]({_, _}, {_, _})
        /go/src/github.com/cilium/cilium/pkg/stream/sinks.go:25 +0x164
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Get(...)
        /go/src/github.com/cilium/cilium/pkg/node/local_node_store.go:116
github.com/cilium/cilium/pkg/node.getLocalNode()
        /go/src/github.com/cilium/cilium/pkg/node/address.go:49 +0x84
github.com/cilium/cilium/pkg/node.GetIPv4()
        /go/src/github.com/cilium/cilium/pkg/node/address.go:282 +0x24
github.com/cilium/cilium/pkg/datapath/ipcache.(*BPFListener).OnIPIdentityCacheChange(0x4001d73380, {0x2e7ddc4, 0x6}, {{{{0x0, 0xffff0a0001c4}, 0x400000c030}, 0x20}, 0x0}, {0x0, 0x0, ...}, ...)
        /go/src/github.com/cilium/cilium/pkg/datapath/ipcache/listener.go:156 +0x6d4
github.com/cilium/cilium/pkg/ipcache.(*IPCache).upsertLocked(0x40010e4600, {0x40010c3100, 0xd}, {0x40010c2f4c, 0x4, 0x4}, 0x0, 0x0, {0x6, {0x2ea6a9b, ...}, ...}, ...)
        /go/src/github.com/cilium/cilium/pkg/ipcache/ipcache.go:426 +0x1534
github.com/cilium/cilium/pkg/ipcache.(*IPCache).InjectLabels(0x40010e4600, {0x34316b0, 0x40003bf4f0}, {0x4001fc6900, 0xc, 0xc})
        /go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:320 +0x1100
github.com/cilium/cilium/pkg/ipcache.(*IPCache).TriggerLabelInjection.func1({0x34316b0, 0x40003bf4f0})
        /go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:590 +0x50
github.com/cilium/cilium/pkg/controller.(*controller).runController(0x4000d60120, {0x4000d639f0, 0x0, 0x30811e8, 0x0, 0xdf8475800, 0x0, 0x0, {0x34316b0, 0x40003bf4f0}})
        /go/src/github.com/cilium/cilium/pkg/controller/controller.go:201 +0xf8
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
        /go/src/github.com/cilium/cilium/pkg/controller/manager.go:97 +0x88c
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment] 2023-09-22 02:07
Please assign to me. 

/assign @chaunceyjiang

**Comment by lmb** [comment] 2023-09-26 10:14
cc @joamaki since I know you were looking at LocalNodeStore a while ago.

**Comment by chaunceyjiang** [comment] 2023-10-09 04:02
I have tried many times, but I cannot reproduce this error.

**Comment by joamaki** [comment] 2023-10-10 09:16
Hey, took a look at this. The sysdumps show an issue with setting up the geneve device, so that's the actual problem. The crash itself is a bug in the shutdown. The panic occurs as a background goroutine access the "node.localNode" variable after LocalNodeStore has been stopped (I'm intentionally setting it to nil to catch these sort of cases!). I took a look at the code and all seems correct there: In NewPolicyTrifecta, IPcache depends on LocalNodeStore (meaning it'll get stopped after it) and the IPcache stop hook calls `RemoveControllerAndWait` which should make sure the controller is gone after stopping.

I don't have time to look deeper into this right now, but what I would do is validate that `RemoveControllerAndWait` works correctly (extending pkg/controller tests and using `goleak` to check) and I would carefully check the start and stop hooks for IPcache to make sure they are correctly cleaning up. A useful resource here could be to use `test/controlplane/suite/agent.go` to write up a test that runs the the agent and simulate what happens when the starting fails similarly to this Geneve case. Again using `goleak` to check what background goroutines are left running when starting is aborted.

**Comment by joestringer** [comment] 2023-10-11 17:48
I agree it'd be better not to segfault during shutdown, but that's not the original cause of the issue.

If you pull the full agent logs, here's the actual underlying error:

```

2023-09-21T12:31:05.196123865Z level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh <nil> /var/run/cilium/state /host/proc/sys/net /sys/class/net 10.0.3.196 <nil> tunnel geneve 6081 <nil> cilium_host cilium_net 1500 <nil> <nil> <nil> <nil> false <nil> <nil> <nil> false true <nil> 2 100]" error="exit status 1" subsys=datapath-loader
2023-09-21T12:31:05.196220832Z level=warning msg="+ set -o pipefail" subsys=datapath-loader
2023-09-21T12:31:05.196271587Z level=warning msg="+ rm /var/run/cilium/state/encap.state" subsys=datapath-loader
2023-09-21T12:31:05.196293006Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.196315050Z level=warning msg="+ '[' true = true ']'" subsys=datapath-loader
2023-09-21T12:31:05.196332718Z level=warning msg="+ move_local_rules" subsys=datapath-loader
2023-09-21T12:31:05.196353762Z level=warning msg="+ '[' 10.0.3.196 '!=' '<nil>' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196370846Z level=warning msg="+ move_local_rules_af 'ip -4'" subsys=datapath-loader
2023-09-21T12:31:05.196437478Z level=warning msg="+ IP='ip -4'" subsys=datapath-loader
2023-09-21T12:31:05.196464855Z level=warning msg="++ ip -4 rule list" subsys=datapath-loader
2023-09-21T12:31:05.196514235Z level=warning msg="+ '[' -z '9:\tfrom all fwmark 0x200/0xf00 lookup 2004" subsys=datapath-loader
2023-09-21T12:31:05.196532945Z level=warning msg="100:\tfrom all lookup local" subsys=datapath-loader
2023-09-21T12:31:05.196538237Z level=warning msg="32766:\tfrom all lookup main" subsys=datapath-loader
2023-09-21T12:31:05.196540237Z level=warning msg="32767:\tfrom all lookup default' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196542446Z level=warning msg="+ ip -4 rule list" subsys=datapath-loader
2023-09-21T12:31:05.196543904Z level=warning msg="+ grep 100" subsys=datapath-loader
2023-09-21T12:31:05.196553572Z level=warning msg="+ grep 'lookup local'" subsys=datapath-loader
2023-09-21T12:31:05.196562406Z level=warning msg="100:\tfrom all lookup local" subsys=datapath-loader
2023-09-21T12:31:05.196564156Z level=warning msg="+ ip -4 rule del from all lookup local pref 0" subsys=datapath-loader
2023-09-21T12:31:05.196565615Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.196571407Z level=warning msg="++ ip -4 rule list" subsys=datapath-loader
2023-09-21T12:31:05.196577282Z level=warning msg="++ grep 'lookup local'" subsys=datapath-loader
2023-09-21T12:31:05.196603910Z level=warning msg="++ wc -l" subsys=datapath-loader
2023-09-21T12:31:05.196607035Z level=warning msg="+ '[' 1 -eq 0 ']'" subsys=datapath-loader
2023-09-21T12:31:05.196610036Z level=warning msg="+ '[' '<nil>' '!=' '<nil>' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196618703Z level=warning msg="+ setup_proxy_rules" subsys=datapath-loader
2023-09-21T12:31:05.196637496Z level=warning msg="+ from_ingress_rulespec='fwmark 0xA00/0xF00 pref 10 lookup 2005 proto 2'" subsys=datapath-loader
2023-09-21T12:31:05.196669291Z level=warning msg="+ to_proxy_rulespec='fwmark 0x200/0xF00 pref 9 lookup 2004 proto 2'" subsys=datapath-loader
2023-09-21T12:31:05.196684501Z level=warning msg="+ '[' 10.0.3.196 '!=' '<nil>' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196698669Z level=warning msg="++ ip -4 rule list" subsys=datapath-loader
2023-09-21T12:31:05.196713254Z level=warning msg="+ '[' -n '9:\tfrom all fwmark 0x200/0xf00 lookup 2004" subsys=datapath-loader
2023-09-21T12:31:05.196726838Z level=warning msg="100:\tfrom all lookup local" subsys=datapath-loader
2023-09-21T12:31:05.196743798Z level=warning msg="32766:\tfrom all lookup main" subsys=datapath-loader
2023-09-21T12:31:05.196757674Z level=warning msg="32767:\tfrom all lookup default' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196771884Z level=warning msg="++ ip -4 rule list fwmark 0x200/0xF00 pref 9 lookup 2004 proto 2" subsys=datapath-loader
2023-09-21T12:31:05.196787427Z level=warning msg="+ '[' -z '9:\tfrom all fwmark 0x200/0xf00 lookup 2004' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196801679Z level=warning msg="+ ip -4 rule delete fwmark 0xA00/0xF00 pref 10 lookup 2005 proto 2" subsys=datapath-loader
2023-09-21T12:31:05.196815596Z level=warning msg="RTNETLINK answers: No such file or directory" subsys=datapath-loader
2023-09-21T12:31:05.196848266Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.196865059Z level=warning msg="+ ip route replace table 2004 local 0.0.0.0/0 dev lo proto 2" subsys=datapath-loader
2023-09-21T12:31:05.196878852Z level=warning msg="+ ip route delete table 2005 10.0.3.196/32 dev cilium_host" subsys=datapath-loader
2023-09-21T12:31:05.196892062Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.196905772Z level=warning msg="+ ip route delete table 2005 default via 10.0.3.196" subsys=datapath-loader
2023-09-21T12:31:05.196919106Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.196932441Z level=warning msg="+ '[' '<nil>' '!=' '<nil>' ']'" subsys=datapath-loader
2023-09-21T12:31:05.196946067Z level=warning msg="+ ip -6 rule del fwmark 0x200/0xF00 pref 9 lookup 2004 proto 2" subsys=datapath-loader
2023-09-21T12:31:05.196959277Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.196972736Z level=warning msg="+ ip -6 rule del fwmark 0xA00/0xF00 pref 10 lookup 2005 proto 2" subsys=datapath-loader
2023-09-21T12:31:05.196985779Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.197000322Z level=warning msg="+ '[' tunnel = ipip ']'" subsys=datapath-loader
2023-09-21T12:31:05.197014740Z level=warning msg="+ ip link del cilium_ipip4" subsys=datapath-loader
2023-09-21T12:31:05.197027658Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.197040868Z level=warning msg="+ ip link del cilium_ipip6" subsys=datapath-loader
2023-09-21T12:31:05.197053869Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.197067287Z level=warning msg="+ ip link del cilium_sit" subsys=datapath-loader
2023-09-21T12:31:05.197080205Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.197093456Z level=warning msg="+ case \"${TUNNEL_PROTOCOL}\" in" subsys=datapath-loader
2023-09-21T12:31:05.197106540Z level=warning msg="+ ip link del cilium_vxlan" subsys=datapath-loader
2023-09-21T12:31:05.197119917Z level=warning msg="+ true" subsys=datapath-loader
2023-09-21T12:31:05.197133168Z level=warning msg="+ '[' geneve '!=' '<nil>' ']'" subsys=datapath-loader
2023-09-21T12:31:05.197232302Z level=warning msg="+ ENCAP_DEV=cilium_geneve" subsys=datapath-loader
2023-09-21T12:31:05.197264972Z level=warning msg="+ ip link show cilium_geneve" subsys=datapath-loader
2023-09-21T12:31:05.197285307Z level=warning msg="Device \"cilium_geneve\" does not exist." subsys=datapath-loader
2023-09-21T12:31:05.197299058Z level=warning msg="+ create_encap_dev" subsys=datapath-loader
2023-09-21T12:31:05.197312268Z level=warning msg="+ TUNNEL_OPTS=external" subsys=datapath-loader
2023-09-21T12:31:05.197325436Z level=warning msg="+ '[' 6081 '!=' '<nil>' ']'" subsys=datapath-loader
2023-09-21T12:31:05.197338854Z level=warning msg="+ TUNNEL_OPTS='dstport 6081 external'" subsys=datapath-loader
2023-09-21T12:31:05.197352105Z level=warning msg="++ rnd_mac_addr" subsys=datapath-loader
2023-09-21T12:31:05.197365440Z level=warning msg="+++ od /dev/urandom -N5 -t x1 -An" subsys=datapath-loader
2023-09-21T12:31:05.197406235Z level=warning msg="+++ sed 's/ /:/g'" subsys=datapath-loader
2023-09-21T12:31:05.197433029Z level=warning msg="++ local lower=:48:4d:c9:fe:80" subsys=datapath-loader
2023-09-21T12:31:05.197517704Z level=warning msg="+++ od /dev/urandom -N1 -t x1 -An" subsys=datapath-loader
2023-09-21T12:31:05.197526121Z level=warning msg="+++ cut '-d ' -f2" subsys=datapath-loader
2023-09-21T12:31:05.197527621Z level=warning msg="++ local upper=142" subsys=datapath-loader
2023-09-21T12:31:05.197529122Z level=warning msg="++ printf %02x%s 142 :48:4d:c9:fe:80" subsys=datapath-loader
2023-09-21T12:31:05.197531080Z level=warning msg="+ ip link add name cilium_geneve address 8e:48:4d:c9:fe:80 type geneve dstport 6081 external" subsys=datapath-loader
2023-09-21T12:31:05.197532539Z level=warning msg="Error: Unknown device type." subsys=datapath-loader
2023-09-21T12:31:05.197534039Z level=warning msg="+ encap_fail" subsys=datapath-loader
2023-09-21T12:31:05.197535914Z level=warning msg="+ echo 'ERROR: Setup of encapsulation device cilium_geneve has failed. Is another program using a tunnel device?'" subsys=datapath-loader
2023-09-21T12:31:05.197537581Z level=warning msg="ERROR: Setup of encapsulation device cilium_geneve has failed. Is another program using a tunnel device?" subsys=datapath-loader
2023-09-21T12:31:05.197539164Z level=warning msg="+ echo 'Configured tunnel devices on the system:'" subsys=datapath-loader
2023-09-21T12:31:05.197540623Z level=warning msg="Configured tunnel devices on the system:" subsys=datapath-loader
2023-09-21T12:31:05.197542123Z level=warning msg="+ ip link show type tunnel" subsys=datapath-loader
2023-09-21T12:31:05.197543415Z level=warning msg="+ exit 1" subsys=datapath-loader
2023-09-21T12:31:05.197562041Z level=error msg="Start hook failed" error="daemon creation failed: error while initializing daemon: failed while reinitializing datapath: exit status 1" function="cmd.newDaemonPromise.func1 (daemon_main.go:1645)" subsys=hive
```

**Comment by joestringer** [comment] 2023-10-11 17:49
```
2023-09-21T12:31:05.197531080Z level=warning msg="+ ip link add name cilium_geneve address 8e:48:4d:c9:fe:80 type geneve dstport 6081 external" subsys=datapath-loader
2023-09-21T12:31:05.197532539Z level=warning msg="Error: Unknown device type." subsys=datapath-loader
```

The above suggests that the kernel might not have support for geneve. Uname from sysdump shows this:

```
Linux test-worker 6.4.16-orbstack-00103-g02b40eb69695 #1 SMP Wed Sep 13 10:13:30 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by joestringer** [comment] 2023-10-11 17:55
Cilium could do a better job of autodetecting the availability of geneve support in the kernel and more gracefully reporting the error. To get this to work though you'll likely need to reach out to your Linux kernel vendor to get them to add support for Geneve.

**Comment by darox** [comment] 2023-10-12 09:56
Sorry, I didn't check the sysdump more carefully when creating the issue. I reran a few tests and could see the indicators that the kernel of the backing VM apparently doesn't support geneve.

**Closed as completed** 2023-12-06 12:03 UTC
Labels: kind/bug, needs/triage, kind/community-report, area/agent
