### ISSUE TITLE
Cilium Client Commands in Admin Guide 

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#1311] opened 2017-08-14 22:48 UTC
For Cilium v0.10 release announcement.

Update Admin guide section on Endpoint Management, Policy, & Loadbalancing/Services.
http://docs.cilium.io/en/latest/admin/#cilium-client-commands

**Comment by tgraf** [comment] 2017-11-02 15:38
Duplicate of #1586

**Closed as completed by tgraf** 2017-11-02 15:38 UTC
Labels: kind/duplicate, area/documentation
