### ISSUE TITLE
CI: Travis CI - Pull Request (github.com/cilium/cilium/clustermesh-apiserver)

### ISSUE THREAD

**Issue by mhofstetter** [cilium/cilium#24668] opened 2023-03-31 08:28 UTC
## CI failure

Check `Travis CI - Pull Request` is failing in the package `github.com/cilium/cilium/clustermesh-apiserver`

PR: https://github.com/cilium/cilium/pull/24665

Travis Job: https://app.travis-ci.com/github/cilium/cilium/builds/261940384

Log Output

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/clustermesh-apiserver   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                
--- FAIL: TestUsersManagement (0.10s)
                                     
level=info msg=Invoked duration="24.295µs" function="github.com/cilium/cilium/clustermesh-apiserver.registerUsersManager (users_mgmt.go:69)" subsys=hive
level=info msg=Starting subsys=hive
level=info msg="Starting managing etcd users based on configuration" file-path=/tmp/clustermesh-config3689702238/users.yaml subsys=clustermesh-apiserver
level=info msg="Start hook executed" duration="49.812µs" function="*main.usersManager.Start" subsys=hive
level=info msg="User successfully configured" subsys=clustermesh-apiserver user=foo
level=info msg="User successfully configured" subsys=clustermesh-apiserver user=bar
level=info msg="User successfully configured" subsys=clustermesh-apiserver user=qux
level=info msg="User successfully removed" subsys=clustermesh-apiserver user=foo
level=info msg="User successfully removed" subsys=clustermesh-apiserver user=bar
level=info msg="User successfully removed" subsys=clustermesh-apiserver user=qux
level=info msg="User successfully configured" subsys=clustermesh-apiserver user=baz
level=info msg="User successfully configured" subsys=clustermesh-apiserver user=foo
level=info msg="User successfully configured" subsys=clustermesh-apiserver user=qux
    users_mgmt_test.go:123: 
        	Error Trace:	/home/travis/gopath/src/github.com/cilium/cilium/clustermesh-apiserver/users_mgmt_test.go:123
        	Error:      	"map[baz:r3 foo:r1 qux:r4]" should have 2 item(s), but has 3
        	Test:       	TestUsersManagement
level=info msg=Stopping subsys=hive
level=info msg="Stopping managing etcd users based on configuration" file-path=/tmp/clustermesh-config3689702238/users.yaml subsys=clustermesh-apiserver
level=info msg=Closing subsys=clustermesh-apiserver
level=info msg="Stop hook executed" duration="67.452µs" function="*main.usersManager.Stop" subsys=hive
```

**Comment by joestringer** [comment] 2023-03-31 21:49
Duplicate of https://github.com/cilium/cilium/issues/24653. Please search issues for the test failure before filing issues.

**Closed as not planned by joestringer** 2023-03-31 21:49 UTC
Labels: area/CI, ci/flake
