### ISSUE TITLE
CI: failure due to panic found in logs during removal from idpool

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6348] opened 2018-11-30 17:39 UTC
Link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4951/testReport/junit/k8s-1/8/K8sServicesTest_External_services_To_Services_first_endpoint_creation/

Output: 

```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
Error creating resource /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/external-policy.yaml: cannot get the revision 
Expected
    <*errors.errorString | 0xc42044b420>: {
        s: "cannot get the revision ",
    }
to be nil
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/Services.go:288
Standard Output

⚠️  Found a 'panic:' in logs
Number of 'context deadline exceeded' in logs: 0
Number of 'level=error' in logs: 0
Number of 'level=warning' in logs: 1
Number of 'Cilium API handler panicked' in logs: 0
Number of 'Goroutine took lock for more than' in logs: 3
Cilium pods: [cilium-bcl7m cilium-bwbzg]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::cnp-second-namespace 
Endpoint Policy Enforcement:
     app2-75f77ffdbf-x7dvs              =>   none
     cilium-etcd-h4fm9vqnwv             =>   none
     kube-dns-6f4c8dbcd4-jvkfw          =>   none
     prometheus-core-5c9fbf5cc6-ljlr6   =>   none
     app3-bf49c776d-qbk4b               =>   none
     toservices                         =>   
     cilium-etcd-kwv5ltxgm7             =>   none
     cilium-etcd-mvhhc2x6lh             =>   none
     etcd-operator-8b5cbb6d6-z7j7n      =>   none
Cilium agent 'cilium-bcl7m': Status: Ok  Health:  Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 4 Failed 0
Cilium agent 'cilium-bwbzg': Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 43 Failed 0
```

Logs: [78f778d3_K8sServicesTest_External_services_To_Services_first_endpoint_creation.zip](https://github.com/cilium/cilium/files/2634405/78f778d3_K8sServicesTest_External_services_To_Services_first_endpoint_creation.zip)

Panic from logs in `pod-kube-system-cilium-bcl7m-cilium-agent-previous.log` from the attached archive:

```
2018-11-28T19:00:46.590947704Z panic: runtime error: index out of range
2018-11-28T19:00:46.590981705Z 
2018-11-28T19:00:46.591091784Z goroutine 240 [running]:
2018-11-28T19:00:46.591203026Z github.com/cilium/cilium/pkg/idpool.(*idCache).doRemove(0xc000aff6b0, 0x3d30, 0xee5364f124)
2018-11-28T19:00:46.59129593Z 	/go/src/github.com/cilium/cilium/pkg/idpool/idpool.go:293 +0x144
2018-11-28T19:00:46.591399409Z github.com/cilium/cilium/pkg/idpool.(*idCache).remove(0xc000aff6b0, 0x3d30, 0xc000397a40)
2018-11-28T19:00:46.591488816Z 	/go/src/github.com/cilium/cilium/pkg/idpool/idpool.go:272 +0x35
2018-11-28T19:00:46.591629579Z github.com/cilium/cilium/pkg/idpool.(*IDPool).Remove(0xc000397a40, 0x3d30, 0xc0044f8400)
2018-11-28T19:00:46.591720366Z 	/go/src/github.com/cilium/cilium/pkg/idpool/idpool.go:170 +0x78
2018-11-28T19:00:46.591850076Z github.com/cilium/cilium/pkg/kvstore/allocator.(*cache).start.func1(0xc0004de740, 0xc0004de680, 0xc0007de540, 0xc0003866e0)
2018-11-28T19:00:46.591939452Z 	/go/src/github.com/cilium/cilium/pkg/kvstore/allocator/cache.go:186 +0x8c7
2018-11-28T19:00:46.591983467Z created by github.com/cilium/cilium/pkg/kvstore/allocator.(*cache).start
2018-11-28T19:00:46.592072361Z 	/go/src/github.com/cilium/cilium/pkg/kvstore/allocator/cache.go:139 +0x176
2018-11-28T19:00:46.596353292Z level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
```

**Comment by tgraf** [comment] 2019-01-28 02:51
Duplicate of #6632

**Closed as completed by tgraf** 2019-01-28 02:51 UTC
Labels: kind/bug, area/CI
