### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15580] opened 2021-04-06 22:15 UTC
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/92/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR/
[30f61d63_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR.zip](https://github.com/cilium/cilium/files/6267556/30f61d63_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR.zip)

It failed a couple other times recently:
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/72/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR/
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/101/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR/

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Can not connect to service "http://192.168.36.11:32149" from outside cluster (3/10)
Expected command: kubectl exec -n kube-system log-gatherer-gtzhz -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:32149 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" | grep client_address= 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:943
```
### Standard Output
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 50
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 3 errors/warnings:
Deleting no longer present service
Unable to update ipcache map entry on pod add
DSR might not work for requests sent to other than enp0s8 device. Run 'sysctl -w net.ipv4.conf.enp0s8.rp_filter=2' (or set to '0') on each node to fix
Cilium pods: [cilium-n5m89 cilium-vhpv8]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
testclient-tg4jb                       
testds-g8x8s                           
testds-pglkr                           
coredns-5495c8f48d-h42sp               
grafana-7fd557d749-sv66c               
prometheus-d87f8f984-8vkj7             
test-k8s2-5b756fd6c5-9rmgh             
testclient-lb6xc                       
Cilium agent 'cilium-n5m89': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 41 Failed 0
Cilium agent 'cilium-vhpv8': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 40 Failed 0
```
### Standard Error
<details><summary>Click here to see.</summary>

```
13:26:06 STEP: Installing Cilium
13:26:07 STEP: Waiting for Cilium to become ready
13:26:38 STEP: Validating if Kubernetes DNS is deployed
13:26:38 STEP: Checking if deployment is ready
13:26:38 STEP: Checking if kube-dns service is plumbed correctly
13:26:38 STEP: Checking if pods have identity
13:26:38 STEP: Checking if DNS can resolve
13:26:39 STEP: Kubernetes DNS is up and operational
13:26:39 STEP: Validating Cilium Installation
13:26:39 STEP: Performing Cilium controllers preflight check
13:26:39 STEP: Performing Cilium status preflight check
13:26:39 STEP: Performing Cilium health check
13:26:41 STEP: Performing Cilium service preflight check
13:26:41 STEP: Performing K8s service preflight check
13:26:43 STEP: Waiting for cilium-operator to be ready
13:26:43 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
13:26:43 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
13:26:43 STEP: Making 10 HTTP requests from outside cluster to "http://192.168.36.11:32149"
FAIL: Can not connect to service "http://192.168.36.11:32149" from outside cluster (3/10)
Expected command: kubectl exec -n kube-system log-gatherer-gtzhz -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:32149 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" | grep client_address= 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 command terminated with exit code 28
	 

=== Test Finished at 2021-04-06T13:26:49Z====
13:26:49 STEP: Running JustAfterEach block for EntireTestsuite K8sServicesTest
===================== TEST FAILED =====================
13:26:49 STEP: Running AfterFailed block for EntireTestsuite K8sServicesTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-7fd557d749-sv66c           1/1     Running   0          84m   10.0.0.4        k8s1   <none>           <none>
	 cilium-monitoring   prometheus-d87f8f984-8vkj7         1/1     Running   0          84m   10.0.0.16       k8s1   <none>           <none>
	 default             test-k8s2-5b756fd6c5-9rmgh         2/2     Running   0          23m   10.0.1.239      k8s2   <none>           <none>
	 default             testclient-lb6xc                   1/1     Running   0          23m   10.0.1.243      k8s2   <none>           <none>
	 default             testclient-tg4jb                   1/1     Running   0          23m   10.0.0.227      k8s1   <none>           <none>
	 default             testds-g8x8s                       2/2     Running   0          12m   10.0.0.67       k8s1   <none>           <none>
	 default             testds-pglkr                       2/2     Running   0          13m   10.0.1.16       k8s2   <none>           <none>
	 kube-system         cilium-n5m89                       1/1     Running   0          45s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-747fc799b9-ttbbt   1/1     Running   0          45s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-747fc799b9-wsn5w   1/1     Running   0          45s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-vhpv8                       1/1     Running   0          45s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         coredns-5495c8f48d-h42sp           1/1     Running   0          78m   10.0.1.149      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          88m   192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          88m   192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          88m   192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          88m   192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-4mvhn                 1/1     Running   0          85m   192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-4szv5                 1/1     Running   0          85m   192.168.36.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-gtzhz                 1/1     Running   0          85m   192.168.36.13   k8s3   <none>           <none>
	 kube-system         registry-adder-5kzjj               1/1     Running   0          85m   192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-c7fpd               1/1     Running   0          85m   192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-cd5hs               1/1     Running   0          85m   192.168.36.13   k8s3   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-n5m89 cilium-vhpv8]
cmd: kubectl exec -n kube-system cilium-n5m89 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID    Frontend                Service Type   Backend                   
	 1     10.96.0.1:443           ClusterIP      1 => 192.168.36.11:6443   
	 2     10.96.0.10:53           ClusterIP      1 => 10.0.1.149:53        
	 3     10.96.0.10:9153         ClusterIP      1 => 10.0.1.149:9153      
	 4     10.104.37.246:3000      ClusterIP      1 => 10.0.0.4:3000        
	 5     10.103.20.166:9090      ClusterIP      1 => 10.0.0.16:9090       
	 6     10.96.90.194:69         ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 7     10.96.90.194:80         ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 8     10.97.43.180:10069      ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 9     10.97.43.180:10080      ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 10    192.168.36.12:32149     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 11    10.0.2.15:8080          HostPort       1 => 10.0.1.239:80        
	 12    0.0.0.0:32149           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 13    192.168.36.12:31968     NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 15    0.0.0.0:31968           NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 16    10.98.173.67:10080      ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 17    10.98.173.67:10069      ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 18    192.168.36.12:31061     NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 19    10.0.2.15:6969          HostPort       1 => 10.0.1.239:69        
	 20    0.0.0.0:31061           NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 22    0.0.0.0:31147           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 23    192.168.36.12:31147     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 24    10.106.245.234:10069    ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 25    10.106.245.234:10080    ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 26    192.168.36.12:31304     NodePort       1 => 10.0.1.16:69         
	 27    192.168.36.12:31304/i   NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 30    0.0.0.0:31304           NodePort       1 => 10.0.1.16:69         
	 31    0.0.0.0:31304/i         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 32    192.168.36.12:30406     NodePort       1 => 10.0.1.16:80         
	 33    192.168.36.12:30406/i   NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 34    0.0.0.0:30406           NodePort       1 => 10.0.1.16:80         
	 35    0.0.0.0:30406/i         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 36    10.0.2.15:31304         NodePort       1 => 10.0.1.16:69         
	 37    10.0.2.15:31304/i       NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 38    10.109.138.11:10080     ClusterIP      1 => 10.0.1.239:80        
	 39    10.109.138.11:10069     ClusterIP      1 => 10.0.1.239:69        
	 40    0.0.0.0:31522           NodePort       1 => 10.0.1.239:80        
	 41    0.0.0.0:31522/i         NodePort       1 => 10.0.1.239:80        
	 42    192.168.36.12:31522     NodePort       1 => 10.0.1.239:80        
	 43    192.168.36.12:31522/i   NodePort       1 => 10.0.1.239:80        
	 44    10.0.2.15:30406         NodePort       1 => 10.0.1.16:80         
	 45    10.0.2.15:30406/i       NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 46    192.168.36.12:30280     NodePort       1 => 10.0.1.239:69        
	 47    192.168.36.12:30280/i   NodePort       1 => 10.0.1.239:69        
	 50    0.0.0.0:30280           NodePort       1 => 10.0.1.239:69        
	 51    0.0.0.0:30280/i         NodePort       1 => 10.0.1.239:69        
	 52    10.103.95.92:10080      ClusterIP      1 => 10.0.1.239:80        
	 53    10.103.95.92:10069      ClusterIP      1 => 10.0.1.239:69        
	 54    192.168.36.12:31011     NodePort       1 => 10.0.1.239:80        
	 55    10.0.2.15:31011         NodePort       1 => 10.0.1.239:80        
	 56    0.0.0.0:31011           NodePort       1 => 10.0.1.239:80        
	 57    192.168.36.12:31596     NodePort       1 => 10.0.1.239:69        
	 59    0.0.0.0:31596           NodePort       1 => 10.0.1.239:69        
	 60    10.105.44.236:80        ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 61    0.0.0.0:30532           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 62    192.168.36.12:30532     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 63    10.0.2.15:31596         NodePort       1 => 10.0.1.239:69        
	 64    10.96.198.76:80         ClusterIP      1 => 10.0.1.239:80        
	 65    192.168.36.12:30046     NodePort       1 => 10.0.1.239:80        
	 66    192.168.36.12:30046/i   NodePort       1 => 10.0.1.239:80        
	 68    10.0.2.15:32449         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 69    0.0.0.0:30046           NodePort       1 => 10.0.1.239:80        
	 70    0.0.0.0:30046/i         NodePort       1 => 10.0.1.239:80        
	 71    10.98.73.0:20080        ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 72    10.98.73.0:20069        ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 73    192.0.2.233:20080       ExternalIPs    1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 74    192.0.2.233:20069       ExternalIPs    1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 75    192.168.36.12:30996     NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 77    0.0.0.0:30996           NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 78    192.168.36.12:32449     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 79    10.0.2.15:30996         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 80    0.0.0.0:32449           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 81    192.168.36.12:8080      HostPort       1 => 10.0.1.239:80        
	 83    0.0.0.0:8080            HostPort       1 => 10.0.1.239:80        
	 84    192.168.36.12:6969      HostPort       1 => 10.0.1.239:69        
	 85    10.0.2.15:31147         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 86    0.0.0.0:6969            HostPort       1 => 10.0.1.239:69        
	 87    192.168.36.11:20080     ExternalIPs    1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 88    192.168.36.11:20069     ExternalIPs    1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 111   10.0.2.15:31061         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 114   10.0.2.15:30532         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 115   10.0.2.15:30046         NodePort       1 => 10.0.1.239:80        
	 116   10.0.2.15:30046/i       NodePort       1 => 10.0.1.239:80        
	 119   10.0.2.15:32149         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 122   10.0.2.15:31968         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 123   10.0.2.15:31522         NodePort       1 => 10.0.1.239:80        
	 124   10.0.2.15:31522/i       NodePort       1 => 10.0.1.239:80        
	 127   10.0.2.15:30280         NodePort       1 => 10.0.1.239:69        
	 128   10.0.2.15:30280/i       NodePort       1 => 10.0.1.239:69        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-n5m89 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                             
	 43         Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                 ready   
	                                                            reserved:host                                                                      
	 918        Disabled           Disabled          11291      k8s:io.cilium.k8s.policy.cluster=default          fd02::11b   10.0.1.239   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:zgroup=test-k8s2                                                               
	 1211       Disabled           Disabled          44342      k8s:io.cilium.k8s.policy.cluster=default          fd02::150   10.0.1.243   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:zgroup=testDSClient                                                            
	 2574       Disabled           Disabled          43865      k8s:io.cilium.k8s.policy.cluster=default          fd02::10f   10.0.1.16    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:zgroup=testDS                                                                  
	 2592       Disabled           Disabled          27139      k8s:io.cilium.k8s.policy.cluster=default          fd02::1da   10.0.1.149   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                        
	                                                            k8s:k8s-app=kube-dns                                                               
	 3231       Disabled           Disabled          4          reserved:health                                   fd02::1b8   10.0.1.100   ready   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-vhpv8 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID    Frontend                Service Type   Backend                   
	 1     10.96.0.10:53           ClusterIP      1 => 10.0.1.149:53        
	 2     10.96.0.10:9153         ClusterIP      1 => 10.0.1.149:9153      
	 3     10.104.37.246:3000      ClusterIP      1 => 10.0.0.4:3000        
	 4     10.103.20.166:9090      ClusterIP      1 => 10.0.0.16:9090       
	 5     10.96.0.1:443           ClusterIP      1 => 192.168.36.11:6443   
	 6     10.96.90.194:80         ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 7     10.96.90.194:69         ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 8     10.97.43.180:10080      ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 9     10.97.43.180:10069      ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 10    192.168.36.11:32149     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 11    10.0.2.15:30046         NodePort                                 
	 12    0.0.0.0:32149           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 13    10.0.2.15:30046/i       NodePort       1 => 10.0.1.239:80        
	 14    192.168.36.11:31968     NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 15    0.0.0.0:31968           NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 16    10.98.173.67:10080      ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 17    10.98.173.67:10069      ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 19    192.168.36.11:31147     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 20    0.0.0.0:31147           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 21    0.0.0.0:31061           NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 23    192.168.36.11:31061     NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 24    10.106.245.234:10080    ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 25    10.106.245.234:10069    ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 26    10.0.2.15:32149         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 28    192.168.36.11:30406     NodePort       1 => 10.0.0.67:80         
	 29    192.168.36.11:30406/i   NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 30    0.0.0.0:30406           NodePort       1 => 10.0.0.67:80         
	 31    0.0.0.0:30406/i         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 32    10.0.2.15:31968         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 34    192.168.36.11:31304     NodePort       1 => 10.0.0.67:69         
	 35    192.168.36.11:31304/i   NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 36    0.0.0.0:31304           NodePort       1 => 10.0.0.67:69         
	 37    0.0.0.0:31304/i         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 38    10.109.138.11:10069     ClusterIP      1 => 10.0.1.239:69        
	 39    10.109.138.11:10080     ClusterIP      1 => 10.0.1.239:80        
	 40    10.0.2.15:31147         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 42    192.168.36.11:31522     NodePort                                 
	 43    192.168.36.11:31522/i   NodePort       1 => 10.0.1.239:80        
	 44    0.0.0.0:31522           NodePort                                 
	 45    0.0.0.0:31522/i         NodePort       1 => 10.0.1.239:80        
	 46    10.0.2.15:31061         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 48    192.168.36.11:30280     NodePort                                 
	 49    192.168.36.11:30280/i   NodePort       1 => 10.0.1.239:69        
	 50    0.0.0.0:30280           NodePort                                 
	 51    0.0.0.0:30280/i         NodePort       1 => 10.0.1.239:69        
	 52    10.103.95.92:10069      ClusterIP      1 => 10.0.1.239:69        
	 53    10.103.95.92:10080      ClusterIP      1 => 10.0.1.239:80        
	 54    10.0.2.15:30280         NodePort                                 
	 55    192.168.36.11:31596     NodePort       1 => 10.0.1.239:69        
	 56    0.0.0.0:31596           NodePort       1 => 10.0.1.239:69        
	 57    10.0.2.15:30280/i       NodePort       1 => 10.0.1.239:69        
	 58    192.168.36.11:31011     NodePort       1 => 10.0.1.239:80        
	 59    0.0.0.0:31011           NodePort       1 => 10.0.1.239:80        
	 60    10.105.44.236:80        ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 61    0.0.0.0:30532           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 63    192.168.36.11:30532     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 64    10.96.198.76:80         ClusterIP      1 => 10.0.1.239:80        
	 67    192.168.36.11:30046     NodePort                                 
	 68    192.168.36.11:30046/i   NodePort       1 => 10.0.1.239:80        
	 69    0.0.0.0:30046           NodePort                                 
	 70    0.0.0.0:30046/i         NodePort       1 => 10.0.1.239:80        
	 71    10.98.73.0:20080        ClusterIP      1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 72    10.98.73.0:20069        ClusterIP      1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 73    192.0.2.233:20080       ExternalIPs    1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 74    192.0.2.233:20069       ExternalIPs    1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 75    192.168.36.11:32449     NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 77    0.0.0.0:32449           NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 78    10.0.2.15:31522         NodePort                                 
	 79    192.168.36.11:30996     NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 80    0.0.0.0:30996           NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 81    192.168.36.11:20080     ExternalIPs    1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 82    192.168.36.11:20069     ExternalIPs    1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 102   10.0.2.15:31522/i       NodePort       1 => 10.0.1.239:80        
	 103   10.0.2.15:32449         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 106   10.0.2.15:30996         NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 107   10.0.2.15:31304         NodePort       1 => 10.0.0.67:69         
	 108   10.0.2.15:31304/i       NodePort       1 => 10.0.1.16:69         
	                                              2 => 10.0.0.67:69         
	 111   10.0.2.15:30406         NodePort       1 => 10.0.0.67:80         
	 112   10.0.2.15:30406/i       NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 115   10.0.2.15:31011         NodePort       1 => 10.0.1.239:80        
	 117   10.0.2.15:31596         NodePort       1 => 10.0.1.239:69        
	 119   10.0.2.15:30532         NodePort       1 => 10.0.1.16:80         
	                                              2 => 10.0.0.67:80         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-vhpv8 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                   
	 41         Disabled           Disabled          4          reserved:health                                          fd02::b5   10.0.0.72    ready   
	 122        Disabled           Disabled          59825      k8s:app=grafana                                          fd02::59   10.0.0.4     ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 137        Disabled           Disabled          53023      k8s:app=prometheus                                       fd02::ba   10.0.0.16    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                   
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 468        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                       ready   
	                                                            k8s:node-role.kubernetes.io/master                                                       
	                                                            reserved:host                                                                            
	 1136       Disabled           Disabled          43865      k8s:io.cilium.k8s.policy.cluster=default                 fd02::b0   10.0.0.67    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                  
	                                                            k8s:zgroup=testDS                                                                        
	 2916       Disabled           Disabled          44342      k8s:io.cilium.k8s.policy.cluster=default                 fd02::4d   10.0.0.227   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                  
	                                                            k8s:zgroup=testDSClient                                                                  
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
13:27:19 STEP: Running AfterEach for block EntireTestsuite K8sServicesTest
13:27:19 STEP: Running AfterEach for block EntireTestsuite
```
</details>

**Comment by brb** [comment] 2021-04-07 06:37
Looks like yet another duplicate of https://github.com/cilium/cilium/issues/12511 (I'm planning to tackle it post v1.10).

**Closed as completed by brb** 2021-04-07 06:37 UTC
Labels: area/CI, ci/flake

**Comment by pchaigno** [comment] 2021-04-07 07:33
@brb Then we need to update #12511 so that folks stop opening new issues every week. I've attempted to update the title to better reflect the affected tests and added a comment for the DSR test. Please have a look and fix if incorrect.

**Comment by brb** [comment] 2021-04-07 07:44
@pchaigno Thanks. I fine-tuned it a bit.
