### ISSUE TITLE
CI: Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#14330] opened 2020-12-09 14:13 UTC
```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.36.240" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-rw5kr -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.240 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000018()', Connect: '0.000000',Transfer '0.000000', total '5.001644'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:752
```

[ce4f18e1_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip](https://github.com/cilium/cilium/files/5666414/ce4f18e1_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip)

cc @brb

**Comment by brb** [comment] 2021-01-14 05:39
This is a duplicate of https://github.com/cilium/cilium/issues/12511.

**Closed as completed by brb** 2021-01-14 05:39 UTC
Labels: area/CI, needs/triage, ci/flake
