### ISSUE TITLE
CI: TestEndpointAddNoLabels: metrics assertion failed

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11955] opened 2020-06-08 13:39 UTC
```
FAIL: <autogenerated>:1: DaemonEtcdSuite.TestEndpointAddNoLabels
endpoint_test.go:150:
    c.Errorf("Metrics assertion failed on line %d for Endpoint state %s: obtained %d, expected %d",
        line, state, obtained, expected)
... Error: Metrics assertion failed on line 104 for Endpoint state waiting-to-regenerate: obtained 0, expected 1
```

```
	// Create the endpoint without any labels.
	epTemplate := getEPTemplate(c, ds.d)
	_, _, err := ds.d.createEndpoint(context.TODO(), epTemplate)
	c.Assert(err, IsNil)

	// Endpoint enters WaitingToRegenerate as it has its labels updated during
	// creation.
->	assertOnMetric(c, string(models.EndpointStateWaitingToRegenerate), 1)
```
@christarazi createEndpoint will regenerate the endpoint in the background so line 104 might fail depending on the machine load. I would suggest to add a function that waits until the metric with that particular value similar to:

https://github.com/cilium/cilium/blob/3c9c9709cf6a82da9060fa824119c24463e18c0a/pkg/kvstore/allocator/allocator_test.go#L174-L182

**Comment by christarazi** [comment] 2020-06-08 16:12
Working on fix, should have PR soon. Thanks for the pointer.

**Comment by jrajahalme** [comment] 2020-06-09 23:23
Still failing (https://travis-ci.com/github/cilium/cilium/jobs/346843289):
```
FAIL: <autogenerated>:1: DaemonConsulSuite.TestEndpointAddNoLabels
endpoint_test.go:160:
    // We are printing the map here to show every unique obtained metrics
    // value because these values change rapidly and it may be misleading
    // to only show the last obtained value.
    c.Errorf("Metrics assertion failed on line %d for Endpoint state %s: obtained %v, expected %d",
        line, state, obtainedValues, expected)
... Error: Metrics assertion failed on line 105 for Endpoint state waiting-to-regenerate: obtained map[0:{}], expected 1
```

**Comment by jrajahalme** [comment] 2020-06-09 23:24
Endpoint is still waiting to be regenerated.

**Comment by christarazi** [comment] 2020-06-09 23:26
If I recall correctly, the fix above waits for up to 10 seconds. It sounds like that's not enough? Do we know what a good timeout value would be?

**Comment by christarazi** [comment] 2020-06-10 02:39
I was able to reproduce locally using docker with cpu usage limits, running in a loop, similar to this:

```
docker run --volume "$(pwd):/work" --workdir "/work" --net host --cpus ".1" golang:latest ./cmd.test -test.count=1 -check.v -check.f DaemonEtcdSuite.TestEndpointAddNoLabels
```

It only failed once in ~1500 runs...
It might be worth seeing how often we run into this flake before going in to bump the timeout value.

**Comment by christarazi** [comment] 2020-06-13 03:56
Update on this bug:

Increasing the timeout won't fix the bug as there's some raciness / weirdness happening. 

1) What I found is that this bug occurs with `-race` **92/100 runs**. 
2) Without `-race` it occurs **2/100 times** on average, when the machine is under load (to simulate Travis conditions). (It is difficult to reproduce when the machine is free of load.)
3) When setting the env var `GOMAXPROCS=1` the test **consistently passes**, regardless of `-race`. 

This indicates some weirdness with the interaction between the goroutine the implementation metrics code runs and the goroutine that executes test. Running with `-race` doesn't show that there's a data race with this code, so it's not simply a data race.

**Comment by christarazi** [comment] 2020-06-18 22:41
Update on this bug:

Found the root cause of the flakiness. It is a race between the checking for the state metric change and the endpoint builder state transition-er. 

For context, we have two places where the state of the endpoint can transition:

[`(*Endpoint).SetState`](https://github.com/cilium/cilium/blob/10f4e2ce3664fecc6c30cb971a5ed7924bcea692/pkg/endpoint/endpoint.go#L1320)

and
 
[`(*Endpoint).BuilderSetState`](https://github.com/cilium/cilium/blob/10f4e2ce3664fecc6c30cb971a5ed7924bcea692/pkg/endpoint/endpoint.go#L1422)

During the flake, the following events would occur in order:

1) Endpoint created; transitions from `""` -> `waiting-for-identity`
2) Endpoint controller acknowledges this and signals a label to be attached
3) Controller attaches the default initial label: `reserved:init`; transitions from `waiting-for-identity` -> `ready`
4) Another controller acknowledges the endpoint has had a new label attached and signals regeneration
5) Controller enqueues endpoint regeneration due to updated security labels; transitions from `ready` -> `waiting-to-regenerate`
6) Another controller picks up the regeneration work from the queue; transitions from `waiting-to-regenerate` -> `regenerating`

Between steps 5 and 6, the test was polling on the endpoint state metric, checking if it the endpoint ever reached the `waiting-to-regenerate` state. The interval of the polling was `10ms`. When the flake occurs, step 6 happens immediately, causing the `waiting-to-regenerate` metric to be decremented back to `0` because it is transitioning to `regenerating`. 

Thus, the test incorrectly thought that the endpoint never entered the `waiting-to-regenerate` state. Working on a fix.

**Comment by Jianlin-lv** [comment] 2020-06-23 05:24
Similar error on Arm64:
https://travis-ci.com/github/cilium/cilium/jobs/352248455
https://travis-ci.com/github/cilium/cilium/jobs/352275556
https://travis-ci.com/github/cilium/cilium/jobs/352405609

**Comment by gandro** [comment] 2020-06-24 16:25
Another occurrence (includes log) https://github.com/cilium/cilium/pull/12262#issuecomment-648924776

**Closed as completed** 2020-06-26 18:27 UTC
Labels: kind/bug/CI, area/CI, ci/flake
