### ISSUE TITLE
CI: unable to acquire identity from etcd-operator / cilium-etcd never achieves quorum

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7797] opened 2019-04-19 19:35 UTC
Tests which suffer from this sort of behavior:

* K8sDatapathConfig IPv4Only Check connectivity with IPv6 disabled

List of failures:
* https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2731/
* https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6667/

**Comment by tgraf** [comment] 2019-05-14 20:23
I was able to make a lot of progress tracking this down after we added several additional visibility pieces.

The pieces:

1. Cilium fails eventually and restarts because of:
```
level=error msg="Unable to initialize local node. Retrying..." error="timeout while retrieving initial list of objects from kvstore" subsys=nodediscovery
```

2. This happens because the allocator is never able to complete a list of all identities. The suspicion is that the etcd cluster never achieves quorum.

3. This is confirmed in the new status:
```
KVStore:                Ok   etcd: 1/1 connected, has-quorum=false: https://cilium-etcd-client.kube-system.svc:2379 - 3.3.12
```

4. This is no in line with what etcd itself reports:
```
member 391d881dddd8ef6e is healthy: got healthy result from https://cilium-etcd-2kkm998tqc.cilium-etcd.kube-system.svc:2379
member 80d2ced9ea89e2f9 is healthy: got healthy result from https://cilium-etcd-zpth67hvf2.cilium-etcd.kube-system.svc:2379
member daedae90c871045c is healthy: got healthy result from https://cilium-etcd-ncxr5hdxsb.cilium-etcd.kube-system.svc:2379
cluster is healthy
```

**Comment by tgraf** [comment] 2019-05-14 20:26
Filed https://github.com/cilium/cilium/issues/8025

**Comment by raybejjani** [comment] 2019-05-27 14:12
https://github.com/cilium/cilium/pull/8114 fixed #8025. I'll lower the priority in https://github.com/cilium/cilium/projects/49 and close this if no one sees it this week.

**Comment by raybejjani** [comment] 2019-05-27 16:04
Alas, no, this just showed up in CI-pipeline :(
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7131

**Comment by nebril** [comment] 2019-07-02 13:53
Haven't seen this any time lately, closing

**Closed as completed by nebril** 2019-07-02 13:53 UTC
Labels: area/CI
