### ISSUE TITLE
BGP announcements not occurring on single-node cluster

### ISSUE THREAD

**Issue by shosti** [cilium/cilium#16967] opened 2021-07-21 23:48 UTC
## Bug report

**General Information**

- Cilium version: 1.10.3
- Kernel version: 5.10.43-flatcar
- Orchestration system version in use: 1.20.0
- Generate and upload a system zip:
[cilium-sysdump-20210721-162754.zip](https://github.com/cilium/cilium/files/6859260/cilium-sysdump-20210721-162754.zip)

**How to reproduce the issue**

I'm trying to deploy cilium on a single-node bare-metal cluster with BGP load balancer announcements enabled. I'm deploying with using helm with the following values.yaml file:

```yaml
debug:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: "10.101.0.0/16"
l7Proxy: false
encryption:
  enabled: true
  type: wireguard
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
operator:
  replicas: 1
```

The BGP configmap is as as follows:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.51.60.1
        peer-asn: 65500
        my-asn: 65501
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 172.16.16.0/24
```
My BGP setup on the external router is VyOS with the following configuration:

```
protocols {
    bgp 65500 {
        neighbor 10.51.60.82 {
            description "Kubernetes load balancer"
            remote-as 65501
        }
        parameters {
            router-id 10.51.60.1
        }
    }
```
I confirmed that this setup seems to work perfectly with MetalLB (and BGP disabled in Cilium), but with the Cilium there are no BGP announcements happening. tcpdump shows periodic `KEEPALIVE` messages but no other updates. The logs for the cilium pod show a fair number of:
```
level=debug msg="event startUpdate msg start of service update" subsys=bgp-speaker
level=debug msg="event endUpdate msg end of service update" subsys=bgp-speaker
```
but that's the only indication of anything happening.

The LoadBalancer I'm trying to deploy is:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-test-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    svc: test-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      svc: test-lb
  template:
    metadata:
      labels:
        svc: test-lb
    spec:
      containers:
      - name: web
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
```
(Pretty much straight from the documentation.)

**Comment by christarazi** [comment] 2021-07-26 19:58
I tried to reproduce this with a 1 node cluster, but it is working fine. 

I noticed in the sysdump that there were a lot of msgs such as:
```
2021-07-21T23:13:25.164175766Z level=debug msg="event startUpdate msg start of service update" subsys=bgp-manager
2021-07-21T23:13:25.164242016Z level=debug msg="event serviceDeleted msg service deleted" subsys=bgp-manager
2021-07-21T23:13:25.164290021Z level=debug msg="event endUpdate msg end of service update" subsys=bgp-manager
2021-07-21T23:13:25.164312216Z level=debug msg="event startUpdate msg start of service update" subsys=bgp-manager
2021-07-21T23:13:25.164332561Z level=debug msg="event clearAssignment reason notLoadBalancer msg not a LoadBalancer" subsys=bgp-manager
2021-07-21T23:13:25.164375261Z level=debug msg="event noChange msg service converged, no change" subsys=bgp-manager
2021-07-21T23:13:25.164400341Z level=debug msg="event endUpdate msg end of service update" subsys=bgp-manager
```

Is there something that's deleting your service? 

Later on, I then see:
```
2021-07-21T23:13:44.595450593Z level=debug msg="event startUpdate msg start of service update" subsys=bgp-manager
2021-07-21T23:13:44.595574143Z level=debug msg="event clearAssignment reason differentIPRequested msg user requested a different IP than the one currently assigned" subsys=bgp-manager
2021-07-21T23:13:44.595615638Z level=debug msg="event ipAllocated ip 172.16.16.5 msg IP address assigned by controller" subsys=bgp-manager
2021-07-21T23:13:44.595633913Z level=info msg="Assigned IP \"172.16.16.5\"" event=IPAllocated
```

It looks like BGP is working as the IP was eventually assigned but the `differentIPRequested` is curious? Could that be related with the service deletes? Is there something messing with the services in general in your cluster?

Also, it seems that BGP was working for a period of time since there are previous logs from a previous cilium-agent which have:
```
2021-07-21T23:11:00.687982751Z level=debug msg="event startUpdate msg start of service update" subsys=bgp-speaker
2021-07-21T23:11:00.688113721Z level=debug msg="ip 172.16.16.0 pool default protocol event updatedAdvertisements numAds msg making advertisements using BGP" subsys=bgp-speaker
2021-07-21T23:11:00.688168715Z level=debug msg="ip 172.16.16.0 pool default protocol event serviceAnnounced msg service has IP, announcing" subsys=bgp-speaker
2021-07-21T23:11:00.688247005Z level=debug msg="event endUpdate msg end of service update" subsys=bgp-speaker
```

The current instance of cilium-agent is unable to announce the LB IP because of the service flapping mentioned earlier.

**Comment by ldelossa** [comment] 2021-11-15 14:00
@schizo99 @shosti  

Can you please attempt your same deployments with the latest Cilium build? For example with a cilium install equivalent to:
```
	cilium install \
	--agent-image "quay.io/cilium/cilium-ci" \
	--version "latest" \
	--operator-image "quay.io/cilium/operator-generic-ci" \
	--config="bgp-announce-lb-ip=true" \
	--config="bgp-announce-pod-cidr=true" \
	--config="debug=true" \
```

We've merged in some changes to the BGP package which may solve some of these issues.

If they do not, we'll begin troubleshooting.

**Comment by schizo99** [comment] 2021-11-16 07:33
Tried running with the cilium-ci image.
Same behaviour as before. Have to kill the cilium pod for updates to be sent to the router.

I.e. I add a `LoadBalancer` then no updates are sent. Restart the pod then the updates are sent.
Worth noting is that if I remove the `LoadBalancer` the route is withdrawn immediately.

I've attached a cilium 
[cilium-sysdump-20211116-083157.zip](https://github.com/cilium/cilium/files/7544170/cilium-sysdump-20211116-083157.zip)
sysdump

**Comment by ldelossa** [comment] 2021-12-01 18:26
I can reproduce this. Will be working on a fix. Stay tuned.

**Comment by ldelossa** [comment] 2021-12-01 19:56
# Test Reproduction
Cluster Flavor:                 Kind (locally deployed on workstation)
Cilium Agent Version:       Current HEAD (8fd2bb9ba8)
Cilium Operator Version:  Current HEAD (8fd2bb9ba8)

# Observations 

On Pod Restart the MetalLB logger produces debug messages indicating an IP has been allocated from it's pool and advertised to the downstream client. 

```
2021-12-01T19:21:25.023366656Z level=debug msg="announcing load balancer from endpoint" component=MetalLBSpeaker.do endpoint-id=default/my-test-lb subsys=bgp-speaker
2021-12-01T19:21:25.023369656Z level=debug msg="event startUpdate msg start of service update" subsys=bgp-speaker
2021-12-01T19:21:25.023506787Z level=debug msg="ip 192.168.32.0 pool default protocol event updatedAdvertisements numAds msg making advertisements using BGP" subsys=bgp-speaker
2021-12-01T19:21:25.023510218Z level=debug msg="ip 192.168.32.0 pool default protocol event serviceAnnounced msg service has IP, announcing" subsys=bgp-speaker
2021-12-01T19:21:25.023513257Z level=debug msg="event endUpdate msg end of service update" subsys=bgp-speaker
```

When the cilium pod is idle, and a new load balancer is created, Cilium business logic does indeed forward the event to MetalLB, however the MetalLB code performs seemingly no action. 

```
2021-12-01T19:55:31.408800615Z level=info msg="processing new event." component=MetalLBSpeaker.run subsys=bgp-speaker
2021-12-01T19:55:31.408806879Z level=debug msg="announcing load balancer from endpoint" component=MetalLBSpeaker.do endpoint-id=default/my-test-lb-2 subsys=bgp-speaker
2021-12-01T19:55:31.408811580Z level=debug msg="event startUpdate msg start of service update" subsys=bgp-speaker
2021-12-01T19:55:31.408815372Z level=debug msg="event endUpdate msg end of service update" subsys=bgp-speaker
``` 

We can tell the former two log lines are from inside MetalLB code since there is no "component" field indicating where the log messages are sourced from. 

Will be updating this issue further once I dig into why MetalLB thinks no work should be done.

**Comment by christarazi** [comment] 2021-12-01 22:22
@ldelossa `Ingress` will be empty if there are no backends (`Endpoints`) for the frontend.

**Comment by ldelossa** [comment] 2021-12-02 01:27
@christarazi yes, MetalLB has nothing to announce, I'd expect it to however. These tests are creating and destroying the Service deployment mentioned above. On re-creation, and without a restart, we receive an empty `Ingress` field and MetalLB performs no work.

**Comment by christarazi** [comment] 2021-12-02 21:49
@ldelossa Not sure what you are referring to exactly by "recreation", but would it be accurate to say that Cilium is receiving a K8s event which as the `Ingress` empty, or that something is somehow emptying it?

**Comment by ldelossa** [comment] 2021-12-03 00:09
@christarazi by recreation I just mean a delete of the service and its deployment followed by a recreation. 

I'll debug further up the stack (into the watcher code) next and update  https://github.com/cilium/cilium/issues/16967#issuecomment-984004545

Not sure if we are receiving it with the missing details or if Cilium business logic is stripping off the details we need to fill in our own Ingress info on the "svcEvent" object.

**Closed as completed** 2022-01-12 22:41 UTC
Labels: kind/bug, area/datapath, kind/community-report
