### ISSUE TITLE
Endpoint is regenerated after container died

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1583] opened 2017-09-24 21:35 UTC
```
time="2017-09-24T21:31:55Z" level=debug msg="Processing docker event die for container 00d90c5349518b695cb55c37649c603d944012eb832d95537b0c6c03f302b10c"
time="2017-09-24T21:31:55Z" level=debug msg="Processing deletion event for docker container 00d90c5349518b695cb55c37649c603d944012eb832d95537b0c6c03f302b10c"
time="2017-09-24T21:31:55Z" level=warning msg="Command execution failed: exit status 1"
time="2017-09-24T21:31:55Z" level=warning msg="Join EP id=/var/run/cilium/state/62605_next ifname=lxcb718d"
time="2017-09-24T21:31:55Z" level=warning msg="kernel version:  Linux ip-172-0-52-109.us-west-2.compute.internal 4.11.9-coreos #1 SMP Thu Jul 6 00:54:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
time="2017-09-24T21:31:55Z" level=warning msg="clang version:  clang version 3.8.1 (tags/RELEASE_381/final) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /usr/local/clang+llvm/bin"
time="2017-09-24T21:31:55Z" level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
time="2017-09-24T21:31:55Z" level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
time="2017-09-24T21:31:55Z" level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
time="2017-09-24T21:31:55Z" level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
time="2017-09-24T21:31:55Z" level=warning msg="Cannot find device \"lxcb718d\""
```

**Comment by nebril** [comment] 2017-12-13 14:24
Can't reproduce it, I tried killing containers in various manners, none of the kills resulted in regenerating endpoint. Closing.

**Closed as completed by nebril** 2017-12-13 14:24 UTC
Labels: kind/bug, needs/triage
