### ISSUE TITLE
CI: TestConformance/HTTPRouteTimeoutRequest 

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#29013] opened 2023-11-06 19:50 UTC
## CI failure

```
     --- FAIL: TestConformance/HTTPRouteTimeoutRequest (0.04s)
        --- PASS: TestConformance/HTTPRouteTimeoutRequest/0_request_to_'/request-timeout'_should_receive_a_200 (1.01s)
        --- FAIL: TestConformance/HTTPRouteTimeoutRequest/1_request_to_'/request-timeout?delay=1s'_should_receive_a_504 (30.07s)
```

https://github.com/cilium/cilium/actions/runs/6774695366/job/18412350792

[conformance-gateway-flake.zip](https://github.com/cilium/cilium/files/13271905/conformance-gateway-flake.zip)

**Comment by tommyp1ckles** [comment] 2023-11-06 20:44
It's failed a few times on my branch, but it's occuring on https://github.com/cilium/cilium/actions/runs/6774105607/job/18410451032.  

Could be related to: https://github.com/cilium/cilium/commit/e72677d83e146f96e3cbc7fe56f12cbc47dd4002?

**Comment by sayboras** [comment] 2023-11-08 09:48
as pointed out by @mhofstetter, it seems like the issue is due to mismatch codebase version and CI job, which is fixed with rebase with main branch.

**Closed as completed by sayboras** 2023-11-08 09:48 UTC
Labels: area/CI, ci/flake
