### ISSUE TITLE
Race condition with ipallocator/allocator.go hyperkube v1.6.7

### ISSUE THREAD

**Issue by ntaylor1781** [cilium/cilium#2339] opened 2017-12-14 18:46 UTC
### Title

Race condition with ipallocator/allocator.go hyperkube v1.6.7

### General Information

- Cilium version: 0.13.90
- Orchestration system version in use:

`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}`

OS: CoreOS version: 1576.4.0

### How to reproduce the issue
Additional notes: This cluster was setup a while ago using matchbox. There were some interesting settings that are not, and weren't at the time, the normal options. For instance kubelet (and the flannel deploy that cilium is replacing) used /var/lib/cni/ for their cni-bin directory. Due to some of these differences, the deploy had to be rolled out alongside a restart of the kubelet service. 

1. Set the cilium ds with a nodeSelector option
2. Have kubelet running with image tag version 1.6.4
3. Set the kubelet_image_tag enviroment variable to 1.6.7 so kubelet will upgrade on next restart
4. Restart kubelet while properly labeling the node so that cilium will be setup when kubelet comes back up.
5. Kubelet and cilium will get into a ready state.
6. Attempt to put a pod on the node that requires the cni networking. (kube-dns, kubernetes-dashboard). 
 
The errors will be shown in the kubelet journalctl logs. Here is a snippet of my own logs:

```
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: time="2017-12-12T18:13:55Z" level=debug msg="Agent is not aware of endpoint" endpointID="container-id:55b442915862d26c81e5d28b83caebaadc154b24730ecd20c1b42973fcd40df1" error="[GET /endpoint/{id}][404] getEndpointIdNotFound "
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: time="2017-12-12T18:13:55Z" level=debug msg="Processing CNI ADD request" args="&{1c72e7cf1ec36626b423abce2e20a407cc7520d0b1cecc64c0d4d3de2809e92a /proc/458/ns/net eth0 IgnoreUnknown=1;K8S_POD_NAMESPACE=pipe;K8S_POD_NAME=thebest.a-339424807-dztsb;K8S_POD_INFRA_CONTAINER_ID=1c72e7cf1ec36626b423abce2e20a407cc7520d0b1cecc64c0d4d3de2809e92a /opt/cni/bin:/opt/cilium-cni/bin [123 10 32 32 32 32 34 110 97 109 101 34 58 32 34 99 105 108 105 117 109 34 44 10 32 32 32 32 34 116 121 112 101 34 58 32 34 99 105 108 105 117 109 45 99 110 105 34 44 10 32 32 32 32 34 109 116 117 34 58 32 49 52 53 48 10 125 10]}"
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: time="2017-12-12T18:13:55Z" level=debug msg="Created veth pair" vethPair="[tmp1c72e lxc1c72e]"
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: E1212 18:13:55.681528 26525 cni.go:260] Error adding network: [POST /ipam][502] postIpAMFailure range is full
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: E1212 18:13:55.681557 26525 cni.go:211] Error while adding to cni network: [POST /ipam][502] postIpAMFailure range is full
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: E1212 18:13:55.749297 26525 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "thebest.a-339424807-dztsb_pipe" network: [POST /ipam][502] postIpAMFailure range is full
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: E1212 18:13:55.749357 26525 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "thebest.a-339424807-dztsb_pipe(121e6483-df68-11e7-bc06-00163e0140a5)" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "thebest.a-339424807-dztsb_pipe" network: [POST /ipam][502] postIpAMFailure range is full
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: E1212 18:13:55.749378 26525 kuberuntime_manager.go:619] createPodSandbox for pod "thebest.a-339424807-dztsb_pipe(121e6483-df68-11e7-bc06-00163e0140a5)" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "thebest.a-339424807-dztsb_pipe" network: [POST /ipam][502] postIpAMFailure range is full
Dec 12 18:13:55 cloudlab02-worker01 kubelet-wrapper[26525]: E1212 18:13:55.749436 26525 pod_workers.go:182] Error syncing pod 121e6483-df68-11e7-bc06-00163e0140a5 ("thebest.a-339424807-dztsb_pipe(121e6483-df68-11e7-bc06-00163e0140a5)"), skipping: failed to "CreatePodSandbox" for "thebest.a-339424807-dztsb_pipe(121e6483-df68-11e7-bc06-00163e0140a5)" with CreatePodSandboxError: "CreatePodSandbox for pod \"thebest.a-339424807-dztsb_pipe(121e6483-df68-11e7-bc06-00163e0140a5)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"thebest.a-339424807-dztsb_pipe\" network: [POST /ipam][502] postIpAMFailure range is full"
```

The error states that the range is full, but there were only 6 pods on this node. If you delete the cilium pod and allow the ds to recreate it, any currently failing pods will start to succeed, and new pods do not exhibit the same errors.

**Comment by raybejjani** [comment] 2017-12-19 21:05
Sorry for the slow reply @ntaylor1781 . I'm trying to reproduce this on my end to debug further. In the meantime do you happen to have the logs from the cilium agent while this was happening? The kubelet logs show the CNI plugin side of things, but I'm hoping the agent printed a warning of some sort as it came up.

**Comment by ntaylor1781** [comment] 2017-12-19 23:56
Unfortunately I did not grab those logs. I had to get the system working so I did the workaround on all of my nodes. I will have time to revert one of them tomorrow so I can get those logs for you.

**Comment by raybejjani** [comment] 2017-12-20 10:06
That would be fantastic, thank you. If you could enable debug that would also help. To do that, see this toggle, https://github.com/cilium/cilium/blob/master/examples/kubernetes/cilium.yaml#L26,  in the sample spec we have or just add `--debug=true` in the arguments to cilium-agent.

**Comment by ntaylor1781** [comment] 2017-12-21 23:00
Well unfortunately I can't get it to occur again after reverting to it's previous state. I even made sure to clear /var/run/cilium, I'm not sure if there could be anything else left behind that could help it avoid this error. At this point I don't have any new hosts I can test this on. I regret not saving one for future testing now.

**Comment by tgraf** [comment] 2017-12-22 11:34
@ntaylor1781 No problem, we keep this open and start reviewing the allocator init code. The symptom is very clear and the location of the race condition seems obvious.

@raybejjani I suspect that either the initialization overlaps with starting the API and start handing out IPs or a bug in the reservation of locally used IPs which causes depletion of all available IPs.

**Comment by tgraf** [comment] 2018-01-12 17:14
@ntaylor1781 We can't reproduce this. We'll close this for now and will reopen when it reappears. Please yell whenever you see it again.

**Closed as completed by tgraf** 2018-01-12 17:14 UTC
Labels: kind/bug, priority/high

**Comment by raybejjani** [comment] 2018-02-01 09:51
@ntaylor1781 Is there any chance that, in your setup, you had another network overlap with the node CIDR range? perhaps a network from docker (which defaults to using 172.17.0.0/16)? I saw another user report with the same range full behaviour and in that case it was due to a docker network that contained the range given to cilium. cilium-agent then attempts to not use these overlapping IPs, starving itself.

**Comment by ntaylor1781** [comment] 2018-02-01 16:10
Node CIDR range is 10.8.0.0/24, Docker is default 172.17.0.0/16, pod CIDR range is 10.2.0.0/16, service CIDR is 10.3.0.0/16, and finally we are using AVI load balancing which uses 172.18.0.0/16. No overlap. I do find it interesting that a simple restart of the cilium pod fixed it. It's also interesting that I couldn't get it to happen again after clearing all cilium files and settings off a host.

**Comment by raybejjani** [comment] 2018-02-02 10:57
Bummer. It definitely sounds like a race, as you said, I just don't know how it's happening. If I do, I'll post here again. Thanks!
