### ISSUE TITLE
cilium kernel check no match

### ISSUE THREAD

**Issue by JornShen** [cilium/cilium#14843] opened 2021-02-03 01:45 UTC
## Bug report

I used `Ubuntu 18.04.2 LTS` to install a k8s cluster with cilium(v1.9.3).  
But cilium start failed, logs say that it should run in kernel >=4.17.  
Then I upgrade the kernel to v5.6.15 with https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.6.15/.(pkg without suffix lowlantency)

And cilium start success. But when I run  the `cilium kernel check` it get output like this

```
> cilium kernel-check 
FEATURE                       SUPPORTED                     REQUIRED
CONFIG_BPF_JIT                false                         true
CONFIG_HAVE_EBPF_JIT          false                         true
CONFIG_BPF                    false                         true
CONFIG_BPF_SYSCALL            false                         true
CONFIG_NET_SCH_INGRESS        false                         true
CONFIG_NET_CLS_BPF            false                         true
CONFIG_NET_CLS_ACT            false                         true
CONFIG_LWTUNNEL_BPF           false                         false
CONFIG_BPF_EVENTS             false                         false
CONFIG_CGROUP_BPF             false                         false
```

eBPF filesystem mount is ok
```
mount | grep bpf
none on /sys/fs/bpf type bpf (rw,relatime)
```

from the kernel check output. seems that ebpf can not use. But service traffice balance looks ok.
```
> curl   http://10.96.9.250:30080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

is this normal?
And Can I see other place to judge cilium use ebpf detail ?

**General Information**

- Cilium version (run `cilium version`) 1.9.3 ae8661f14
- Kernel version (run `uname -a`)   5.6.15-050615-generic

**Comment by brb** [comment] 2021-02-03 07:50
>  used Ubuntu 18.04.2 LTS to install a k8s cluster with cilium(v1.9.3).
But cilium start failed, logs say that it should run in kernel >=4.17.

What was the error?

The problem reported by `cilium kernel-check` is false positive, see https://github.com/cilium/cilium/issues/14314.

**Comment by JornShen** [comment] 2021-02-03 08:04
> > used Ubuntu 18.04.2 LTS to install a k8s cluster with cilium(v1.9.3).
> > But cilium start failed, logs say that it should run in kernel >=4.17.
> 
> What was the error?
> 
> The problem reported by `cilium kernel-check` is false positive, see #14314.

@brb  you mean `false`  is a bug?

**Comment by brb** [comment] 2021-02-03 08:19
Most likely the kernel config was not available in your case, so therefore `cilium kernel-check` was reporting `false`.

**Comment by JornShen** [comment] 2021-02-03 08:20
> > used Ubuntu 18.04.2 LTS to install a k8s cluster with cilium(v1.9.3).
> > But cilium start failed, logs say that it should run in kernel >=4.17.
> 
> What was the error?
> 
> The problem reported by `cilium kernel-check` is false positive, see #14314.

the error I not save it. But when I upgrade the kernel version.  cilium start success. 👀 @brb

**Comment by brb** [comment] 2021-02-03 08:26
Let's close it as it's a duplicate of #14314.

**Closed as completed by brb** 2021-02-03 08:26 UTC
Labels: kind/bug, need-more-info, kind/community-report

**Comment by JornShen** [comment] 2021-02-03 08:29
> Most likely the kernel config was not available in your case, so therefore `cilium kernel-check` was reporting `false`.

My kernel config like this
```
root@kwephisprb14130:/boot#  grep CONFIG_BPF= /boot/config-`uname -r`
CONFIG_BPF=y
root@kwephisprb14130:/boot# grep CONFIG_BPF_SYSCALL= /boot/config-`uname -r` 
CONFIG_BPF_SYSCALL=y
root@kwephisprb14130:/boot# grep CONFIG_NET_CLS_BPF= /boot/config-`uname -r` 
CONFIG_NET_CLS_BPF=m
root@kwephisprb14130:/boot# grep CONFIG_NET_ACT_BPF= /boot/config-`uname -r` 
CONFIG_NET_ACT_BPF=m
root@kwephisprb14130:/boot#  grep CONFIG_BPF_JIT= /boot/config-`uname -r`
CONFIG_BPF_JIT=y
root@kwephisprb14130:/boot# grep CONFIG_HAVE_BPF_JIT= /boot/config-`uname -r`
root@kwephisprb14130:/boot# grep CONFIG_BPF_EVENTS= /boot/config-`uname -r` 
CONFIG_BPF_EVENTS=y
```
https://www.tecmint.com/bcc-best-linux-performance-monitoring-tools/

@brb

**Comment by brb** [comment] 2021-02-03 08:31
Yes, it was unavailable because `/boot` was not mounted into the cilium container.

**Comment by JornShen** [comment] 2021-02-03 09:01
> Most likely the kernel config was not available in your case, so therefore `cilium kernel-check` was reporting `false`.

what do you recommand to do ? upgrade the kernel ? @brb

**Comment by brb** [comment] 2021-02-03 09:03
Nothing. This warning is false positive in your case, so just ignore it.

**Comment by JornShen** [comment] 2021-02-03 09:07
> Nothing. This warning is false positive in your case, so just ignore it.
 
is there anything(like some comand) I can see cilium probe the ebpf success ? @brb

**Comment by brb** [comment] 2021-02-03 09:14
`cilium status` should give you a good overview whether your system is functioning.

**Comment by JornShen** [comment] 2021-02-03 09:18
> `cilium status` should give you a good overview whether your system is functioning.

ok, thanks !
