### ISSUE TITLE
Compile errors with llvm/clang 4.0 + musl libc

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#890] opened 2017-06-02 15:18 UTC
Reported by @jpds

```
make[1]: Leaving directory '/tmp/cilium-net-build/src/github.com/cilium/cilium/plugins'
make[1]: Entering directory '/tmp/cilium-net-build/src/github.com/cilium/cilium/bpf'
clang -DUNKNOWN -Iinclude -D__NR_CPUS__=4 -O2 -target bpf -I. -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lxc.c -o /dev/null;  clang -DDROP_ALL -Iinclude -D__NR_CPUS__=4 -O2 -target bpf -I. -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lxc.c -o /dev/null;
In file included from bpf_lxc.c:32:
./lib/maps.h:80:8: error: unknown type name '__always_inline'
static __always_inline void ep_tail_call(struct __sk_buff *skb, uint32_t index)
       ^
./lib/maps.h:80:24: error: expected identifier or '('
static __always_inline void ep_tail_call(struct __sk_buff *skb, uint32_t index)
                       ^
In file included from bpf_lxc.c:33:
In file included from ./lib/arp.h:25:
./lib/drop.h:42:41: error: comparison of distinct pointer types ('typeof (128ULL) *' (aka 'unsigned long long *') and 'typeof (skb_len) *' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
        uint64_t skb_len = skb->len, cap_len = min(128ULL, skb_len);
                                               ^~~~~~~~~~~~~~~~~~~~
./lib/utils.h:27:14: note: expanded from macro 'min'
        (void) (&_x == &_y);    \
                ~~~ ^  ~~~
In file included from bpf_lxc.c:33:
In file included from ./lib/arp.h:25:
./lib/drop.h:84:3: error: implicit declaration of function 'ep_tail_call' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ep_tail_call(skb, CILIUM_CALL_ERROR_NOTIFY);
                ^
./lib/drop.h:95:41: error: comparison of distinct pointer types ('typeof (64ULL) *' (aka 'unsigned long long *') and 'typeof (skb_len) *' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
        uint64_t skb_len = skb->len, cap_len = min(64ULL, skb_len);
                                               ^~~~~~~~~~~~~~~~~~~
./lib/utils.h:27:14: note: expanded from macro 'min'
        (void) (&_x == &_y);    \
                ~~~ ^  ~~~
5 errors generated.
In file included from bpf_lxc.c:32:
./lib/maps.h:80:8: error: unknown type name '__always_inline'
static __always_inline void ep_tail_call(struct __sk_buff *skb, uint32_t index)
       ^
./lib/maps.h:80:24: error: expected identifier or '('
static __always_inline void ep_tail_call(struct __sk_buff *skb, uint32_t index)
                       ^
In file included from bpf_lxc.c:33:
In file included from ./lib/arp.h:25:
./lib/drop.h:42:41: error: comparison of distinct pointer types ('typeof (128ULL) *' (aka 'unsigned long long *') and 'typeof (skb_len) *' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
        uint64_t skb_len = skb->len, cap_len = min(128ULL, skb_len);
                                               ^~~~~~~~~~~~~~~~~~~~
./lib/utils.h:27:14: note: expanded from macro 'min'
        (void) (&_x == &_y);    \
                ~~~ ^  ~~~
In file included from bpf_lxc.c:33:
In file included from ./lib/arp.h:25:
./lib/drop.h:84:3: error: implicit declaration of function 'ep_tail_call' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ep_tail_call(skb, CILIUM_CALL_ERROR_NOTIFY);
                ^
./lib/drop.h:95:41: error: comparison of distinct pointer types ('typeof (64ULL) *' (aka 'unsigned long long *') and 'typeof (skb_len) *' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
        uint64_t skb_len = skb->len, cap_len = min(64ULL, skb_len);
                                               ^~~~~~~~~~~~~~~~~~~
./lib/utils.h:27:14: note: expanded from macro 'min'
        (void) (&_x == &_y);    \
                ~~~ ^  ~~~
5 errors generated.
make[1]: *** [Makefile:37: bpf_lxc.o] Error 1
make[1]: Leaving directory '/tmp/cilium-net-build/src/github.com/cilium/cilium/bpf'
make: *** [Makefile:10: bpf] Error 2
```

**Comment by aanm** [comment] 2017-06-02 16:12
@borkmann  @jrfastab  Some of the bpf errors were fixed by this commit: https://github.com/cilium/cilium/commit/fe3f7dff917ad225858c83aba55a1f3b677cd465

**Comment by jrfastab** [comment] 2017-06-05 15:08
I'm not able to reproduce this with the clang below and latest cilium master branch. Its also not obvious to me why clang 4.0 would have issues with `__always_inline`:

`./lib/maps.h:80:8: error: unknown type name '__always_inline'`

@aanm, did you have any other specific setup to reproduce?

$ clang --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/john/kernels/llvm-4.0.0.src/build/bin

**Comment by aanm** [comment] 2017-06-05 15:31
I thought this was implicit in the first post. Those errors happen on this branch https://github.com/cilium/cilium/commits/alpine-image

The difference is the Dockerfile, where the compilation errors appear, since it's based on alpine. I've talked with @borkmann a while ago and we conclude it was likely due to different libc as they use musl.

**Comment by tgraf** [comment] 2017-06-05 15:33
My bad, I didn't notice the musl dependency of this error. I'm not sure we can support musl.

**Comment by joestringer** [comment] 2018-07-31 08:17
This issue looks stale and it doesn't look like we have any plans currently to support musl.

**Closed as completed by joestringer** 2018-07-31 08:17 UTC
Labels: kind/bug, area/llvm
