### ISSUE TITLE
Dangling CiliumNodes cause cluster pool CIDR ranges to get exhausted

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#17837] opened 2021-11-09 23:47 UTC
## Bug report

**General Information**

- Cilium version: 1.9.9

# How to reproduce

Roughly speaking, scale up and down the k8s cluster, and observe that sometimes CiliumNodes do not get deleted. Once cilium-operator runs out of CIDR ranges to give out to new nodes, cilium-agent fails with a message `required IPv4 PodCIDR not available`.
```
    ipam:
      operator-status:
        error: allocator full
```
a workaround would be to delete those dangling CiliumNodes manually.

**Comment by joestringer** [comment] 2021-11-10 01:39
Seems like the underlying problem here is that the CiliumNodes are dangling; shouldn't the operator garbage-collect those?

**Comment by timoreimann** [comment] 2021-11-13 21:25
We ran into this problem as well: a cluster with currently 5 nodes had 500+ CiliumNodes. Restarting just cilium-operator did not seem to help: we had to delete the dangling CiliumNodes and delete/restart cilium-operator again before affected agents were able to finish bootstrapping.

We run Cilium v1.10.1.

**Comment by aanm** [comment] 2021-11-22 16:58
@timoreimann I forgot to update this issue. It seems this is not a Cilium bug. Kubernetes is programmed to delete CiliumNodes if the Kubernetes node is deleted. In order to do it so the GC Kubernetes controller requires synced informers for all resources before it will proceed deleting stuff. does `echo -n $(kubectl api-resources --verbs=list -o name) | tr ' ' ',' | xargs -t kubectl get -A -l selectnone=true` return any errors? (it should return "No resources found" for all)

**Comment by aanm** [comment] 2022-01-07 21:46
Closing as this was not a Cilium issue.

**Closed as completed by aanm** 2022-01-07 21:46 UTC
Labels: need-more-info

**Comment by timoreimann** [comment] 2022-01-08 08:18
@aanm apologies, I somehow missed your latest comment.

>Kubernetes is programmed to delete CiliumNodes if the Kubernetes node is deleted.

We saw the issue again very recently on a cluster of ours running Cilium 1.9. I don't think the informers were unsynced since the CiliumNode object were dangling for more than 10 days while the cluster and Cilium were running fine in general.

I noticed that ownership relationship handling was improved somewhat in #17329 -- prior to that, I think it was possible for the owner to be missing on the object. Perhaps the issue was due to that?

We're going to upgrade to the latest Cilium patch release (1.9.11) to see if it prevents the issue for good. Happy to report back with the results if that's still considered useful on this closed issue.

**Comment by aanm** [comment] 2022-01-11 00:10
> We're going to upgrade to the latest Cilium patch release (1.9.11) to see if it prevents the issue for good. Happy to report back with the results if that's still considered useful on this closed issue.

@timoreimann if the issue is happening that often and if it's not fixed in 1.9.11 please do open a new issue or mention my username on this one so I can re-open it. Thank you!

**Comment by timoreimann** [comment] 2022-01-27 21:43
We have now observed this on Cilium 1.10.1 as well. There have been a few patch releases since then, however, so probably not worth reopening this ticket prior to seeing the matter on a more recent Cilium version.

Leaving a note here just in case and for record keeping.

**Comment by shalev123d** [comment] 2022-11-23 12:39
We're experiencing this issue, although what is mentioned above regarding that the node has been deleted - not in our case.
The node is not deleted, and we get the `allocator full` error.
when deleting the CiliumNode object and restarting the cilium agent, it seems to work again.

**Comment by mfyuce** [comment] 2024-04-19 09:10
If restart does not solve, then reinstalling cilium with `clusterPoolIPv4MaskSize` and `clusterPoolIPv6MaskSize` similar values  according to your needs;

```yaml

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 2400
    clusterPoolIPv4PodCIDR: 10.0.0.0/8
    clusterPoolIPv4PodCIDRList: []
    clusterPoolIPv6MaskSize: 12000
    clusterPoolIPv6PodCIDR: fd00::/104
    clusterPoolIPv6PodCIDRList: []

```
