### ISSUE TITLE
Print LPM warning message if unable to dump contents of maps

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15936] opened 2021-04-29 15:04 UTC
Since some maps are not able to be printed for older kernels, we should put that notification after printing the error message in [1]. This will be more clear to users than simply printing this helper message in the help section [2].

[1]
```
$ cilium bpf ipcache list
error dumping contents of map: Unable to get next key from map with file descriptor 7: errno 524
```

[2] https://github.com/cilium/cilium/blob/a9374b5db0223752364829f9c0b827f413d2903b/cilium/cmd/bpf_ipcache_list.go#L41

**Comment by MUzairS15** [comment] 2021-05-01 17:16
Hey can you help me starting with this, as i am completely new can you tell me what tech stack i should. Know in order to contribute??

**Comment by oneiro-naut** [comment] 2021-05-12 11:17
Can I work on this issue?

**Comment by oneiro-naut** [comment] 2021-05-13 14:11
Can this issue be assigned to me?

**Comment by oneiro-naut** [comment] 2021-05-14 09:15
Would I need an older kernel image to test my change?

**Comment by pchaigno** [comment] 2021-05-14 10:10
> Would I need an older kernel image to test my change?

Yes, you can use the development VM as per the contributing documentation.

> Also should this notification be given only if the error code is 524?

Yes.

**Comment by oneiro-naut** [comment] 2021-05-14 11:48
I do not get the error message on the development VM cilium/ubuntu-dev.

**Comment by pchaigno** [comment] 2021-05-14 12:21
> I do not get the error message on the development VM cilium/ubuntu-dev

How did you start it?

**Comment by oneiro-naut** [comment] 2021-05-14 13:13
I started it with `K8S=1 NWORKER=1 ./contrib/vagrant/start.sh k8s1`.

**Comment by pchaigno** [comment] 2021-05-14 14:33
I'm also unable to reproduce with a 4.9.258 kernel. @aanm Do you remember with which kernel and Cilium version you had that error message? I also tried v1.8.0 and v1.9.0 (which ship with different bpftool versions) without luck.

**Comment by aanm** [comment] 2021-05-14 16:08
@pchaigno any kernel between 4.11 and 4.15

**Comment by pchaigno** [comment] 2021-05-14 16:12
@aanm Ah, I see. Doesn't this code fix the present issue then? https://github.com/cilium/cilium/blob/a9374b5db0223752364829f9c0b827f413d2903b/cilium/cmd/bpf_ipcache_list.go#L59-L60

**Comment by aanm** [comment] 2021-05-14 16:35
no because it fails on line 47: https://github.com/cilium/cilium/blob/a9374b5db0223752364829f9c0b827f413d2903b/cilium/cmd/bpf_ipcache_list.go#L47

**Comment by oneiro-naut** [comment] 2021-05-14 17:31
I thought of adding a check for error code to filter error 524(operation not permitted) here:
https://github.com/cilium/cilium/blob/a9374b5db0223752364829f9c0b827f413d2903b/pkg/bpf/bpf_linux.go#L243

**Comment by joestringer** [comment] 2022-10-03 18:45
We are looking to drop support for kernels with this issue in the upcoming v1.13.0 release, so I don't think we need to keep this issue around.

**Closed as not planned by joestringer** 2022-10-03 18:45 UTC
Labels: kind/bug, help-wanted, good-first-issue
