### ISSUE TITLE
Unable to reach L2 Loadbalancer services from outside the cluster or from host

### ISSUE THREAD

**Issue by davmin** [cilium/cilium#26468] opened 2023-06-23 21:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After deploying cilium L2 loadbalancer I expect to be able to reach services from outside the cluster. Instead I am able to curl the service successfully from pods inside the cluster but I am unable to successfully curl from pods with host networking, or from hosts outside the cluster.

I initially was also having issues getting leases but that no longer seems to be the case after an uninstall/reinstall with helm.

### Cilium Version

v1.14.0-snapshot.4

### Kernel Version

6.1.30-talos

### Kubernetes Version

v1.27.2

### Sysdump

[cilium-sysdump-20230623-152416.zip](https://github.com/cilium/cilium/files/11853159/cilium-sysdump-20230623-152416.zip)

### Anything else?

This is a bare metal single node talos cluster with a wireguard interface.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davmin** [comment] 2023-07-02 17:30
After a reinstall this issue seems to be limited cilium-ingress. I am able to access a service directly assigned an lb ip but am not able to access any ingresses.

**Comment by p1c2u** [comment] 2023-07-02 19:42
I found out it's the same issue as described here https://github.com/cilium/cilium/issues/25021

**Comment by YutaroHayakawa** [comment] 2023-07-03 00:43
CC: @dylandreimerink

**Comment by YutaroHayakawa** [comment] 2023-07-03 01:44
Ok, so looks like this is a duplicate of #25021. Closing...

**Closed as completed by YutaroHayakawa** 2023-07-03 01:44 UTC
Labels: kind/bug, area/datapath, kind/community-report, feature/l2-announcement
