### ISSUE TITLE
Visibility redirections disappear on Cilium restart ("Unable to enqueue endpoint policy visibility event")

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#16349] opened 2021-05-28 05:20 UTC
## Bug report

Cilium logs "Unable to enqueue endpoint policy visibility event" messages on restart if a pod had visibility annotations before restart. Visibility redirections do not work after restart

**General Information**

- Cilium versions affected: 1.8.10, 1.9.7., 1.10.0, works on 1.7.16
- Kernel version: 5.10.25-linuxkit
- Orchestration system version in use: 1.19.1 (via Kind)

[cilium-agent.log](https://github.com/cilium/cilium/files/6558399/cilium-agent.log)

**How to reproduce the issue**

1. `cilium install`
2. `cilium connectivity test`
3. `kubectl annotate pod client-xxxxx-yyyyy -n cilium-test io.cilium.proxy-visibility="<Egress/53/UDP/DNS>"`
4. `kubectl get pods --all-namespaces -o wide` (pick cilium-zzzzz from the same node as client-xxxxx-yyyyy)
5. `kubectl get cep -n cilium-test` (pick <ENDPOINT ID> for `client-xxxxx-yyyyy`)
6. `kubectl exec -it -n kube-system cilium-zzzzz -- cilium bpf policy get <ENDPOINT ID>
```
DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     reserved:unknown              ANY          NONE         2193    12        
Ingress     reserved:host                 ANY          NONE         0       0         
Egress      reserved:unknown              53/UDP       43969        1142    12        
Egress      reserved:unknown              ANY          NONE         0       0         
```
7. Restart cilium node: `kubectl delete pod -n kube-system cilium-zzzz`
8. `cilium status --wait`
9. Repeat steps 4 & 5 to find the new cilium-z2z2z2 
10. `kubectl exec -it -n kube-system cilium-z2z2z2 -- cilium bpf policy get <ENDPOINT ID>
```
DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     reserved:unknown              ANY          NONE         0       0         
Ingress     reserved:host                 ANY          NONE         0       0         
Egress      reserved:unknown              ANY          NONE         0       0
```
Note the missing proxy redirection for port 53/UDP!

**Comment by romanspb80** [comment] 2021-06-10 22:23
Can I kindly ask to assign this issue to me?

**Comment by pchaigno** [comment] 2021-06-11 13:21
@romanspb80 Did you figure out where the issue is? (Note AFAIK it's not marked as `good-first-issue` because the root cause wasn't found yet.)

**Comment by romanspb80** [comment] 2021-06-11 14:10
> @romanspb80 Did you figure out where the issue is? (Note AFAIK it's not marked as `good-first-issue` because the root cause wasn't found yet.)

I reproduced the problem on the version 1.10.0. I think I'd be interested in investigation it.

**Comment by romanspb80** [comment] 2021-06-20 20:47
This issue is not reproducible in the version 1.10.1
The reason was the loss of the agent configuration:

`
root@roman-pc:/home/roman/cilium-master/install/kubernetes# kubectl -n kube-system exec -it cilium-6z9vp -- cilium bpf policy get 2012
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
Allow    Ingress     reserved:host                 ANY          NONE         0       0         
Allow    Egress      reserved:unknown              ANY          NONE         0       0         

root@roman-pc:/home/roman/cilium-master/install/kubernetes# kubectl -n kube-system exec -it cilium-6z9vp -- ps aux | grep cilium-agent
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
root           1  2.0  0.5 778676 91860 ?        Ssl  20:41   0:05 cilium-agent 
`

**Comment by aanm** [comment] 2022-01-07 17:22
@jrajahalme it seems the issue is no longer present, can we close this GH issue?

**Closed as completed** 2022-08-10 10:47 UTC
Labels: kind/bug, kind/regression
