### ISSUE TITLE
 Unsupported protocol for NAT masquerade causing drops in Cilium monitor logs

### ISSUE THREAD

**Issue by siddjellali** [cilium/cilium#29250] opened 2023-11-18 16:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When running the Cilium monitor in a Kubernetes environment using the following command:
```
kubectl -n kube-system exec -ti cilium-5qrcv -- cilium monitor --type drop
```
The logs indicate the following error:
```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 2, file
```

or with the following command :  
```
[root@k8s01 tmp]# hubble observe -f | grep DROPPED
Nov 18 16:45:34.703: 192.168.252.12 (host) <> 192.168.252.11 (remote-node) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 TimeExceeded(TTLExceeded))
Nov 18 16:45:35.319: 192.168.252.14 (host) <> 192.168.252.10 (kube-apiserver) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 TimeExceeded(TTLExceeded))
Nov 18 16:45:35.726: 192.168.252.12 (host) <> 192.168.252.11 (remote-node) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 TimeExceeded(TTLExceeded))
Nov 18 16:45:36.345: 192.168.252.14 (host) <> 192.168.252.10 (kube-apiserver) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 TimeExceeded(TTLExceeded))
```

I am experiencing intermittent service disruptions in my environment, where services are randomly getting disconnected. This issue is impacting the reliability and availability of our applications.

### Cilium Version

```
cilium-cli: v0.15.8 compiled with go1.21.0 on linux/amd64
cilium image (default): v1.14.1
cilium image (stable): v1.14.4
cilium image (running): 1.14.4****
```

### Kernel Version

`Linux k8s01 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 16 09:55:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
[root@k8s01 ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7", GitCommit:"07a61d861519c45ef5c89bc22dda289328f29343", GitTreeState:"clean", BuildDate:"2023-10-18T11:33:23Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

```

### Sysdump

[cilium-sysdump-20231118-172610.zip](https://github.com/cilium/cilium/files/13400866/cilium-sysdump-20231118-172610.zip)

### Relevant log output

```shell
[root@k8s01 ~]# kubectl -n kube-system exec -ti cilium-5qrcv -- cilium monitor --type drop
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Listening for events on 128 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 2, file nodeport.h:2943, , identity unknown->unknown: 192.168.252.12 -> 192.168.252.11 TimeExceeded(TTLExceeded)
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 2, file nodeport.h:2943, , identity unknown->unknown: 192.168.252.12 -> 192.168.252.11 TimeExceeded(TTLExceeded)
```

### Anything else?

```
# INSTALLATION

API_SERVER_IP="192.168.252.10"
API_SERVER_PORT=6443
helm install cilium cilium/cilium \
    --version 1.14.4 \
    --namespace kube-system \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT} \
    --set kubeProxyReplacement=true \
    --set prometheus.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true
    --set operator.prometheus.enabled=true \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}"

# BGP ENABLE
cilium config set --restart=true enable-bgp-control-plane true
cilium config view | grep -i bgp
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by siddjellali** [comment] 2023-11-18 16:49
I attempted to address intermittent service disruptions by adding  `mtu: "1500"` using the `kubectl edit configmap -n kube-system cilium-config` command. Despite making the modification within the Cilium configuration, the issue persisted. 

The MTU adjustment seemingly did not take effect, and I am seeking assistance in successfully configuring the MTU or identifying alternative solutions to resolve the ongoing service disruptions. 
Any insights or support in diagnosing and rectifying this matter would be greatly appreciated.

**Comment by nijich** [comment] 2023-11-20 00:56
Hi, you can disable bpf-masquerade by modifying cilium-config `enable-bpf-masquerade: "false". Currently cilium ebpf NAT only supports limited ICMP types.

**Comment by nijich** [comment] 2023-11-20 03:37
#27616

**Comment by lmb** [comment] 2023-11-21 14:52
Closing this as a duplicate since there is a workaround and a CFP exists. Please provide your input there.

**Closed as completed by lmb** 2023-11-21 14:52 UTC
Labels: kind/bug, kind/duplicate, needs/triage, kind/community-report

**Comment by siddjellali** [comment] 2023-11-21 20:15
Thanks a lot !
I confirm the workarround

**Comment by haribhusal2025** [comment] 2024-01-22 22:30
@siddjellali Hi Sid, I am having same issue and wondering what was the work around ? which you have confirmed above ? Thank you,

**Comment by haribhusal2025** [comment] 2024-01-22 22:34
> Closing this as a duplicate since there is a workaround and a CFP exists. Please provide your input there.

Please point me to workaround.
