### ISSUE TITLE
CI:  ConformanceIngress (Shared LB): expected status code 200 but 503 was returned

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#21710] opened 2022-10-12 19:05 UTC
## CI failure

```
--- Failed steps:

  Scenario Outline: An Ingress with no rules should send all requests to the default backend # features/default_backend.feature:21
    Then the response status-code must be 200 # features/default_backend.feature:23
      Error: expected status code 200 but 503 was returned
```

https://github.com/cilium/cilium/actions/runs/3221405223

Sysdump: https://github.com/cilium/cilium/suites/8703041754/artifacts/392928973

**Comment by sayboras** [comment] 2022-10-27 09:14
This might be fixed as part of https://github.com/cilium/cilium/pull/21749.

**Comment by sayboras** [comment] 2022-10-31 13:03
As #21749 is merged, we can monitor this issue for some more time.

**Comment by sayboras** [comment] 2022-11-01 03:21
the issue is still happening in below run.

https://github.com/cilium/cilium/actions/runs/3364280585/jobs/5578447338

**Comment by youngnick** [comment] 2022-11-01 03:28
I agree there's a good chance of a collision here with the Gateway API logic which dictates 503s for no match.

**Closed as completed** 2022-12-13 00:42 UTC
Labels: area/CI, ci/flake, area/servicemesh
