### ISSUE TITLE
Upgrading from 1.13.2 -> 1.14.0-snapshot.3 : Operator in CrashLoopBackoff due to null-pointer panic

### ISSUE THREAD

**Issue by justenwalker** [cilium/cilium#26142] opened 2023-06-12 21:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium operator failed to start after upgrading to `1.14.0-snapshot.3`

### Cilium Version

1.14.0-snapshot.3

### Kernel Version

N/A

### Kubernetes Version

1.27

### Relevant log output

```shell
level=info msg="Establishing connection to apiserver" host="https://172.20.0.1:443" subsys=k8s-client
level=info msg="Connected to apiserver" subsys=k8s-client
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11007c4]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0x40004c1260, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:69 +0x434
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0x40004c0348, 0x15}, {0x40008a7560, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:35 +0xfc
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x40009ed088?)
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:310 +0x380
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x0?)
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:198 +0x44
k8s.io/client-go/discovery.ServerGroupsAndResources({0x28ff1e8, 0x400078d860})
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:392 +0x4c
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:356 +0x28
k8s.io/client-go/discovery.withRetries(0x2, 0x4000ac9458)
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:621 +0x90
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x2916640?)
    /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:355 +0x38
github.com/cilium/cilium/pkg/k8s/version.Update({0x2916640, 0x400002d970}, 0x1)
    /go/src/github.com/cilium/cilium/pkg/k8s/version/version.go:309 +0x50
github.com/cilium/cilium/pkg/k8s/client.(*compositeClientset).onStart(0x400002d970, {0xffff70cd8b98?, 0x4000725b30})
    /go/src/github.com/cilium/cilium/pkg/k8s/client/cell.go:223 +0x100
github.com/cilium/cilium/pkg/hive.Hook.Start(...)
    /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:35
github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start(0x40007ed710, {0x28f0e30?, 0x400081ad20?})
    /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:104 +0x278
github.com/cilium/cilium/pkg/hive.(*Hive).Start(0x40007eb9a0, {0x28f0e30, 0x400081ad20})
    /go/src/github.com/cilium/cilium/pkg/hive/hive.go:281 +0xd0
github.com/cilium/cilium/pkg/hive.(*Hive).Run(0x40007eb9a0)
    /go/src/github.com/cilium/cilium/pkg/hive/hive.go:178 +0x64
github.com/cilium/cilium/operator/cmd.init.4.func1(0x40fe000?, {0x24fa1e9?, 0x2?, 0x2?})
    /go/src/github.com/cilium/cilium/operator/cmd/root.go:220 +0x68
github.com/spf13/cobra.(*Command).execute(0x40fe000, {0x400006e130, 0x2, 0x2})
    /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:944 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x40fe000)
    /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
    /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:992
github.com/cilium/cilium/operator/cmd.Execute()
    /go/src/github.com/cilium/cilium/operator/cmd/root.go:151 +0x24
main.main()
    /go/src/github.com/cilium/cilium/operator/main.go:9 +0x1c
```

### Anything else?

I ran the pre-flight checks and they all passed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2023-06-14 01:39
Thanks for the report! This seems like a pretty invasive bug, though I don't yet know the root cause. I've added some labels to attract attention from other core Cilium developers.

**Comment by nebril** [comment] 2023-06-15 08:11
Thanks for reporting this!

Seems like we hit https://github.com/kubernetes/kubernetes/issues/118361

Snapshot 1.14.0 uses `client-go` version 0.26.0, which is affected by the bug:
https://github.com/cilium/cilium/blob/v1.14.0-snapshot.3/go.mod#L117
https://github.com/kubernetes/kubernetes/issues/118361#issuecomment-1579198407

We already upgraded `client-go` in `main`, so this change will get in 1.14 branch.
https://github.com/cilium/cilium/blob/231e65aac1855f9334ef3c9746bccb6889f6d7af/go.mod#L118

I didn't find any reports about this error happening in `client-go` v0.27.2 or later, so I don't think any additional action is necessary. Closing the issue.

**Closed as completed by nebril** 2023-06-15 08:11 UTC
Labels: kind/bug, kind/community-report, area/agent
