### ISSUE TITLE
Cilium Agent couldn't listen on internal node ip for CEW nodes

### ISSUE THREAD

**Issue by tamilmani1989** [cilium/cilium#27200] opened 2023-08-02 01:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Updated cilium health server to listen on internal node IP instead of all address with this PR https://github.com/cilium/cilium/pull/26845 but somehow cilium agent not listening on node ip for external workload node. If cilium agent is running on external workload node, then this config `join-cluster` is enabled. So in above PR skipped for cilium agents running with this config enabled. Need some investigation on why cilium agent couldn't listen on internal node ip for external workload environment.

### Cilium Version

latest

### Kernel Version

Any

### Kubernetes Version

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pippolo84** [comment] 2023-08-02 14:59
I think this is working as intended, since Cilium is running on an external-workload (such as a VM) so there is no concept of internal IP. Closing this.

**Closed as completed by pippolo84** 2023-08-02 14:59 UTC
Labels: kind/bug, needs/triage, kind/community-report
