### ISSUE TITLE
CI: ConformanceAKS (ci-aks) - Clanup error

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#26228] opened 2023-06-14 13:32 UTC
## CI failure

Job: https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046

Error:
```
Run pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
  pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
  cilium uninstall --chart-directory=install/kubernetes/cilium --wait
  shell: /usr/bin/bash -e {0}
  env:
    name: cilium-cilium-5[2](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:2)67491922
    location: westeurope
    cost_reduction: --node-vm-size Standard_B2s --node-osdisk-size [3](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:3)0
    cilium_cli_version: v0.1[4](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:4).[5](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:5)
    cilium_cli_ci_version: 
    check_url: https://github.com/cilium/cilium/actions/runs/52[6](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:6)[7](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:7)4[9](https://github.com/cilium/cilium/actions/runs/5267491922/jobs/9522825046#step:20:9)1922
    job_name: Installation and Connectivity Test
    QUAY_ORGANIZATION: cilium
    QUAY_ORGANIZATION_DEV: cilium
    QUAY_CHARTS_ORGANIZATION_DEV: cilium-charts-dev
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Error: Process completed with exit code 1.
```

Sysdumps:
- [cilium-sysdumps (3).zip](https://github.com/cilium/cilium/files/11746247/cilium-sysdumps.3.zip)

**Comment by mhofstetter** [comment] 2023-06-14 17:39
also hit in https://github.com/cilium/cilium/actions/runs/5270083003/jobs/9529130350

**Comment by giorio94** [comment] 2023-06-15 09:03
Seems a duplicate of https://github.com/cilium/cilium/issues/26075

**Closed as completed by giorio94** 2023-06-15 09:03 UTC
Labels: area/CI, ci/flake
