### ISSUE TITLE
Wireguard Allowed IPs not propagated correctly after node restart

### ISSUE THREAD

**Issue by m-sarti** [cilium/cilium#35644] opened 2024-10-30 09:57 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Restarting a node it happens that it cannot reach any kubernetes address. Investigating I saw that it is due to the fact that, after the restart of the node, the other Wireguard peers do not receive the correct list of allowed ips and in particular the host address is missing.
The situation can only be restored by doing a rolling restart of the daemonset.

### How can we reproduce the issue?

* Check the status of wg of a peer:

```
root@vin-54:~# wg show | grep "172.16.6.39" -B 1 -A 2
peer: 2aU6+YDRxbJGAWevAisNMpGf+7ouC5LMxF8p1L7oHAc=
  endpoint: 172.16.6.39:51871
  allowed ips: 172.16.6.39/32, 10.6.30.52/32, 10.6.30.20/32, 10.6.30.90/32
```
 
* Restart the peer
* Check the status again and assert that the host address missing

```
root@vin-54:~# wg show | grep "172.16.6.39" -B 1 -A 4
peer: 2aU6+YDRxbJGAWevAisNMpGf+7ouC5LMxF8p1L7oHAc=
  endpoint: 172.16.6.39:51871
  allowed ips: 10.6.30.68/32, 10.6.30.228/32
```

### Cilium Version

Client: 1.16.3 f2217191 2024-10-09T15:17:46+00:00 go version go1.22.8 linux/amd64
Daemon: 1.16.3 f2217191 2024-10-09T15:17:46+00:00 go version go1.22.8 linux/amd64

### Kernel Version

Linux vin-53 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.10", GitCommit:"0fa26aea1d5c21516b0d96fea95a77d8d429912e", GitTreeState:"clean", BuildDate:"2024-01-17T13:38:41Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by predakanga** [comment] 2024-10-30 12:45
I'm also experiencing this issue.

Cilium version: 1.16.3
Kubernetes version: 1.31.2
Linux kernel: 5.14.0-427.40.1.el9_4.x86_64

Running with these encryption settings:
```
  encryption:
    enabled: true
    nodeEncryption: true
    type: wireguard
```

Disabling nodeEncryption does not fix the issue, but downgrading to Cilium v1.15.10 does.

**Comment by cyanidium** [comment] 2024-10-31 03:31
I have also been troubleshooting something very similar

Cilium version: 1.17.0-pre.1
Kubernetes version: 1.31.2
Linux kernel: 6.11.5

Running with these settings using the CLI install method:
```text
  --set ipam.mode=kubernetes
  --set cni.exclusive=false
  --set k8s.requireIPv4PodCIDR=true
  --set devices=kube0
  --set encryption.enabled=true
  --set encryption.type=wireguard
  --set encryption.nodeEncryption=true
  --set envoy.enabled=true
  --set kubeProxyReplacement=true
  --set hostPort.enabled=true
  --set ingressController.enabled=true
  --set ingressController.default=true
  --set ingressController.loadbalancerMode=dedicated
  --set gatewayAPI.enabled=true
  --set l2announcements.enabled=true
  --set externalIPs.enabled=true
  --set ipv4.enabled=true
  --set bandwidthManager.enabled=true
  --set bandwidthManager.bbr=true
  --set bpf.masquerade=true
  --set bpf-lb-sock-hostns-only=true
  --set hubble.peerService.clusterDomain=k8s.internal
  --set hubble.relay.enabled=true
  --set hubble.ui.enabled=true
```

Results:
1. Restart worker node, confirm it is back to `Ready`
2. Check `cilium status` from `cilium` pods on all other nodes: all report the restarted node as unreachable
3. Check `cilium status` from `cilium`  on the restarted node: Node 1/1 for each control plane node (node encryption bypassed as expected from [this warning](https://docs.cilium.io/en/v1.15/security/network/encryption-wireguard/#node-to-node-encryption-beta)), 0/1 for all Endpoints and all other Nodes
4. Delete `cilium` pod on another worker node, ensure a new pod is created and `Running`
5. Check `cilium status` from `cilium`  on all other nodes (not rebooted and not deleted): all report the restarted node and the node with the deleted pod as unreachable
6. `kubectl rollout restart -n kube-system ds/cilium deploy/cilium-operator` **both** are needed to restore full connectivity

Remove `nodeEncryption` from the settings and restarting both rollouts (_note the operator doesn't automatically restart the rollouts to apply the change for some reason_):
1. Restart worker node, confirm it is back to `Ready`
2. Check `cilium status` from `cilium`  on all nodes: all report good connectivity

**Comment by cyanidium** [comment] 2024-10-31 05:03
Correction to something I removed from the post above:

If I remove `nodeEncryption` from the settings and restart both rollouts (_note the operator doesn't automatically restart the rollouts to apply the change for some reason_):
1. Check `cilium status` from `cilium`  on all nodes: all report good connectivity
2. Restart worker node, confirm it is back to `Ready`
3. Check `cilium status` from `cilium` pods on all other nodes: all report the restarted node as reachable but endpoints as unreachable
4. Check `cilium status` from `cilium`  on the restarted node: Node 1/1 for all nodes, 0/1 for all Endpoints
5. `kubectl rollout restart -n kube-system ds/cilium deploy/cilium-operator` **both** are needed to restore full connectivity, wait for rollouts to finish
6. Check `cilium status` from `cilium`  on all nodes: all report good connectivity

It seems that removing `nodeEncryption` alone doesn't fully resolve the issue.

**Comment by jschwinger233** [comment] 2024-11-01 08:23
Bug confirmed on main HEAD, but not for v1.15

**Comment by bimmlerd** [comment] 2024-11-01 15:24
Given it's 1.16 and above, could be related to https://github.com/cilium/cilium/pull/33278.

**Comment by jschwinger233** [comment] 2024-11-04 04:04
@bimmlerd Just did a local test at b855b2575f7ae718290b29288b244930c7a223ec (b855b2575f7ae718290b29288b244930c7a223ec), all good.

Maybe https://github.com/cilium/cilium/pull/34612?

**Comment by jschwinger233** [comment] 2024-11-04 04:37
Turned out to be 3ebfa4d636af626c7484209a512bfefa6e027c93 (wireguard: Use dummy peer for allowed IP removal). Cilium built from 3ebfa4d636af626c7484209a512bfefa6e027c93 can reproduce, while 3ebfa4d636af626c7484209a512bfefa6e027c93~ can't.

**Comment by pchaigno** [comment] 2024-11-04 09:05
cc @jrife

**Comment by jrife** [comment] 2024-11-04 15:18
> cc @jrife 

Thanks, I can take a look today. Is there any way to reproduce this in kind? Otherwise, I'll set up a real cluster and restart one of the nodes to reproduce.

**Comment by jrife** [comment] 2024-11-04 20:30
It looks like with https://github.com/cilium/cilium/pull/34612 `UpdatePeer()` fails to sync the node IPs after a public key change which happens after a node restart. I'm working on https://github.com/cilium/cilium/pull/35750 to fix this.

**Comment by m-sarti** [comment] 2024-11-04 20:38
@jrife This is a key point. If the public key of a node changes when the node is rebooted, I confirm that the public key remains the same in the other nodes. This was a fact that I had observed in various tests conducted.

**Comment by jrife** [comment] 2024-11-04 21:17
> If the public key of a node changes when the node is rebooted, I confirm that the public key remains the same in the other nodes

Just to clarify are saying the public key for the node that gets rebooted remains the same in the output of `wg show` on the other nodes even after that node comes back up and is `Ready`? In my testing the public key does *not* remain the same on the other nodes following a reboot. See my example above: "wg show before and after the reboot of the peer at 10.13.106.161".

**Comment by m-sarti** [comment] 2024-11-04 21:42
Correct. You can see by scrolling to the top of my report, I indicated the state detected by "wg show" before and after the peer restart. I had observed that allowed IPs were missing, but also that the public key is unchanged. I do not know if this is correct behavior, certainly the missing allowed IPs does not allow the node to communicate with others.

**Comment by m-sarti** [comment] 2024-11-04 21:44
I have now rolled back to version 1.15.10 and cannot test further, this version is not affected by the problem.

**Comment by jrife** [comment] 2024-11-04 22:12
Looking a bit closer, I think the state directory (`/var/run/cilium`) where Cilium stores the generated WireGuard key on my node gets deleted after a reboot triggering the regeneration. This may be an artifact of my environment (GKE). It's possible there are two issues here and I've found one. The public key changing is key to the fix in https://github.com/cilium/cilium/pull/35750. I will continue to poke around to see if I can get some symptoms closer to what you saw.

**Comment by jrife** [comment] 2024-11-04 23:00
@jschwinger233 @cyanidium Since you also reproduced this issue, I'm wondering if you observed the node key change or not after the reboot in your environment.

**Comment by cyanidium** [comment] 2024-11-05 00:33
I've got 3 control planes and 5 workers, so I've restarted 1 worker and trimmed the data so that only the restarted worker, 1x cp, and 1x worker are shown. On my servers, `/run` is mounted as `tmpfs` and `/var/run` symlinks to `../run`, so it isn't preserved across reboots. This is exactly what is documented for [systemd's fire-hierarchy](https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html), so it should be common to almost all distros at this point.

Before reboot:
```text
restarted_node >>
interface: cilium_wg0
  public key: LwNVI3hEwnnBzcyUD/ImyC3wX7Xs0fPUkwLG3drsEjY=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: xBf5ULZzDmQwG+8m5fnWYTzH8o2bxTKtD3+UXNrwTHw=
  endpoint: 10.0.0.10:51871
  allowed ips: 10.0.0.10/32, 10.128.0.141/32, 10.128.0.67/32, 10.128.0.4/32, 10.128.0.199/32, 10.128.0.219/32
  latest handshake: 1 minute, 38 seconds ago
  transfer: 1.43 MiB received, 1.22 MiB sent

peer: 3WlSezrSwSzBD4JeftqHd23nEHzQpA7Tf4OCaWJ5GVQ=
  endpoint: 10.0.0.13:51871
  allowed ips: 10.0.0.13/32, 10.128.3.69/32, 10.128.3.93/32, 10.128.3.115/32, 10.128.3.36/32, 10.128.3.10/32, 10.128.3.29/32, 10.128.3.32/32, 10.128.3.33/32, 10.128.3.133/32, 10.128.3.64/32, 10.128.3.186/32, 10.128.3.222/32, 10.128.3.200/32, 10.128.3.132/32, 10.128.3.233/32, 10.128.3.126/32, 10.128.3.174/32, 10.128.3.9/32, 10.128.3.42/32, 10.128.3.231/32, 10.128.3.12/32, 10.128.3.159/32, 10.128.3.140/32, 10.128.3.61/32, 10.128.3.131/32, 10.128.3.235/32, 10.128.3.142/32, 10.128.3.201/32, 10.128.3.157/32, 10.128.3.22/32, 10.128.3.90/32, 10.128.3.130/32, 10.128.3.184/32
  latest handshake: 1 minute, 57 seconds ago
  transfer: 15.10 MiB received, 4.54 MiB sent

master >>
interface: cilium_wg0
  public key: xBf5ULZzDmQwG+8m5fnWYTzH8o2bxTKtD3+UXNrwTHw=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: 3WlSezrSwSzBD4JeftqHd23nEHzQpA7Tf4OCaWJ5GVQ=
  endpoint: 10.0.0.13:51871
  allowed ips: 10.0.0.13/32, 10.128.3.69/32, 10.128.3.93/32, 10.128.3.36/32, 10.128.3.29/32, 10.128.3.32/32, 10.128.3.33/32, 10.128.3.64/32, 10.128.3.186/32, 10.128.3.222/32, 10.128.3.200/32, 10.128.3.132/32, 10.128.3.233/32, 10.128.3.126/32, 10.128.3.174/32, 10.128.3.9/32, 10.128.3.42/32, 10.128.3.231/32, 10.128.3.12/32, 10.128.3.159/32, 10.128.3.140/32, 10.128.3.61/32, 10.128.3.131/32, 10.128.3.235/32, 10.128.3.142/32, 10.128.3.201/32, 10.128.3.157/32, 10.128.3.22/32, 10.128.3.130/32, 10.128.3.184/32, 10.128.3.90/32, 10.128.3.133/32, 10.128.3.10/32, 10.128.3.115/32
  latest handshake: 1 minute, 40 seconds ago
  transfer: 304.47 KiB received, 336.03 KiB sent

peer: LwNVI3hEwnnBzcyUD/ImyC3wX7Xs0fPUkwLG3drsEjY=
  endpoint: 10.0.0.17:51871
  allowed ips: 10.0.0.17/32, 10.128.7.202/32, 10.128.7.210/32, 10.128.7.73/32, 10.128.7.213/32, 10.128.7.224/32, 10.128.7.197/32, 10.128.7.47/32, 10.128.7.80/32, 10.128.7.64/32
  latest handshake: 1 minute, 39 seconds ago
  transfer: 1.22 MiB received, 1.43 MiB sent

worker >>
interface: cilium_wg0
  public key: 3WlSezrSwSzBD4JeftqHd23nEHzQpA7Tf4OCaWJ5GVQ=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: xBf5ULZzDmQwG+8m5fnWYTzH8o2bxTKtD3+UXNrwTHw=
  endpoint: 10.0.0.10:51871
  allowed ips: 10.128.0.4/32, 10.128.0.141/32, 10.128.0.219/32, 10.128.0.67/32, 10.128.0.199/32, 10.0.0.10/32
  latest handshake: 1 minute, 39 seconds ago
  transfer: 336.03 KiB received, 304.47 KiB sent

peer: LwNVI3hEwnnBzcyUD/ImyC3wX7Xs0fPUkwLG3drsEjY=
  endpoint: 10.0.0.17:51871
  allowed ips: 10.0.0.17/32, 10.128.7.202/32, 10.128.7.210/32, 10.128.7.73/32, 10.128.7.213/32, 10.128.7.224/32, 10.128.7.197/32, 10.128.7.47/32, 10.128.7.80/32, 10.128.7.64/32
  latest handshake: 1 minute, 57 seconds ago
  transfer: 4.54 MiB received, 15.25 MiB sent
```

After reboot:
```text
restarted_node >>
interface: cilium_wg0
  public key: S+hKootRtgnTjuOFuJY/pu6B5Vg1o16w4Ebig2ydnTY=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: xBf5ULZzDmQwG+8m5fnWYTzH8o2bxTKtD3+UXNrwTHw=
  endpoint: 10.0.0.10:51871
  allowed ips: 10.0.0.10/32, 10.128.0.141/32, 10.128.0.67/32, 10.128.0.4/32, 10.128.0.199/32, 10.128.0.219/32
  latest handshake: 33 seconds ago
  transfer: 124 B received, 1.11 KiB sent

peer: 3WlSezrSwSzBD4JeftqHd23nEHzQpA7Tf4OCaWJ5GVQ=
  endpoint: 10.0.0.13:51871
  allowed ips: 10.0.0.13/32, 10.128.3.69/32, 10.128.3.93/32, 10.128.3.115/32, 10.128.3.36/32, 10.128.3.10/32, 10.128.3.29/32, 10.128.3.32/32, 10.128.3.33/32, 10.128.3.133/32, 10.128.3.64/32, 10.128.3.186/32, 10.128.3.222/32, 10.128.3.200/32, 10.128.3.132/32, 10.128.3.233/32, 10.128.3.126/32, 10.128.3.174/32, 10.128.3.9/32, 10.128.3.42/32, 10.128.3.231/32, 10.128.3.12/32, 10.128.3.159/32, 10.128.3.140/32, 10.128.3.61/32, 10.128.3.131/32, 10.128.3.235/32, 10.128.3.142/32, 10.128.3.201/32, 10.128.3.157/32, 10.128.3.22/32, 10.128.3.90/32, 10.128.3.130/32, 10.128.3.184/32
  latest handshake: 33 seconds ago
  transfer: 124 B received, 356 B sent

master >>
interface: cilium_wg0
  public key: xBf5ULZzDmQwG+8m5fnWYTzH8o2bxTKtD3+UXNrwTHw=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: 3WlSezrSwSzBD4JeftqHd23nEHzQpA7Tf4OCaWJ5GVQ=
  endpoint: 10.0.0.13:51871
  allowed ips: 10.0.0.13/32, 10.128.3.69/32, 10.128.3.93/32, 10.128.3.36/32, 10.128.3.29/32, 10.128.3.32/32, 10.128.3.33/32, 10.128.3.64/32, 10.128.3.186/32, 10.128.3.222/32, 10.128.3.200/32, 10.128.3.132/32, 10.128.3.233/32, 10.128.3.126/32, 10.128.3.174/32, 10.128.3.9/32, 10.128.3.42/32, 10.128.3.231/32, 10.128.3.12/32, 10.128.3.159/32, 10.128.3.140/32, 10.128.3.61/32, 10.128.3.131/32, 10.128.3.235/32, 10.128.3.142/32, 10.128.3.201/32, 10.128.3.157/32, 10.128.3.22/32, 10.128.3.130/32, 10.128.3.184/32, 10.128.3.90/32, 10.128.3.133/32, 10.128.3.10/32, 10.128.3.115/32
  latest handshake: 11 seconds ago
  transfer: 471.66 KiB received, 544.19 KiB sent

peer: S+hKootRtgnTjuOFuJY/pu6B5Vg1o16w4Ebig2ydnTY=
  endpoint: 10.0.0.17:51871
  allowed ips: 10.128.7.134/32, 10.128.7.83/32, 10.128.7.216/32, 10.128.7.87/32, 10.128.7.196/32, 10.128.7.58/32, 10.128.7.10/32
  latest handshake: 34 seconds ago
  transfer: 148 B received, 124 B sent

worker >>
interface: cilium_wg0
  public key: 3WlSezrSwSzBD4JeftqHd23nEHzQpA7Tf4OCaWJ5GVQ=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: xBf5ULZzDmQwG+8m5fnWYTzH8o2bxTKtD3+UXNrwTHw=
  endpoint: 10.0.0.10:51871
  allowed ips: 10.128.0.4/32, 10.128.0.141/32, 10.128.0.219/32, 10.128.0.67/32, 10.128.0.199/32, 10.0.0.10/32
  latest handshake: 10 seconds ago
  transfer: 543.00 KiB received, 471.38 KiB sent

peer: S+hKootRtgnTjuOFuJY/pu6B5Vg1o16w4Ebig2ydnTY=
  endpoint: 10.0.0.17:51871
  allowed ips: 10.128.7.134/32, 10.128.7.83/32, 10.128.7.216/32, 10.128.7.87/32, 10.128.7.196/32, 10.128.7.58/32, 10.128.7.10/32
  latest handshake: 33 seconds ago
  transfer: 148 B received, 124 B sent
```

Results:
- The key changes on reboot
- Each node is aware that the key has changed on the rebooted node
- `allowed_ips` are updated on all nodes, but the endpoint address is missing after reboot

Possibly a different issue. I can create a separate ticket if needed.

**Comment by cyanidium** [comment] 2024-11-05 00:54
One more note: in my environment the nodes have static IP addresses. I am not able to test what happens if the node reboots with a different IP address.

**Comment by jrife** [comment] 2024-11-05 02:36
@cyanidium Thanks for the detailed info. This seems consistent with my observations.

> On my servers, /run is mounted as tmpfs and /var/run symlinks to ../run, so it isn't preserved across reboots. This is exactly what is documented for [systemd's file-hierarchy](https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html), so it should be common to almost all distros at this point.

This is what I see in the environments where I tested as well. `/var/run` points to `/run` which is a `tmpfs` mount, so `/var/run/cilium/state` is cleared after reboot resulting in a fresh WireGuard key being generated each time. This scenario would be fixed by https://github.com/cilium/cilium/pull/35750.

> Possibly a different issue. I can create a separate ticket if needed.

Possibly. I kind of want to see if we can reproduce the symptoms as described before creating a new issue. @m-sarti what does `ls -al /var/run` and `df` show on your nodes? Is `/var/run` pointing to a `tmpfs` mount?

**Comment by jschwinger233** [comment] 2024-11-05 04:28
> [@jschwinger233](https://github.com/jschwinger233) [@cyanidium](https://github.com/cyanidium) Since you also reproduced this issue, I'm wondering if you observed the node key change or not after the reboot in your environment.

I reproduced issue using local kind-based cilium cluster. Indeed key changes after `docker restart -t0 kind-worker`.

**Closed as completed** 2024-11-06 11:03 UTC
Labels: kind/bug, needs/triage, kind/community-report, kind/regression, area/encryption, area/agent, feature/wireguard, affects/v1.16
