### ISSUE TITLE
[v1.9] CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#14485] opened 2020-12-23 18:24 UTC
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.36.11:31902" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-5b4m7 -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:31902 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" | grep client_address= 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:752
```

[d7ae0298_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR.zip](https://github.com/cilium/cilium/files/5736587/d7ae0298_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR.zip)

Seen in https://github.com/cilium/cilium/pull/14480.

**Comment by brb** [comment] 2021-01-04 08:16
A duplicate of https://github.com/cilium/cilium/issues/12511.

**Closed as completed** 2021-01-04 17:55 UTC
Labels: area/CI, ci/flake
