### ISSUE TITLE
Memory leak with FQDN policies

### ISSUE THREAD

**Issue by yuriydzobak** [cilium/cilium#16300] opened 2021-05-25 12:08 UTC
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
Daemon: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd6
```
- Kernel version (run `uname -a`)
```
Linux 5.8.0-40-lowlatency #45~20.04.1-Ubuntu SMP PREEMPT Fri Jan 15 12:34:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
v1.20.4+k3s1
```

- Generate and upload a system zip:
[cilium-sysdump-20210525-150354.zip](https://github.com/cilium/cilium/files/6539133/cilium-sysdump-20210525-150354.zip)

**Description**

One pod has memory leak. It happened a few days ago with another node(pod), restart pod had help
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/70581130/119495045-a48fc280-bd6a-11eb-805e-a63efdadccee.png">

**Comment by yuriydzobak** [comment] 2021-05-25 12:32
[heap_profile639032979.zip](https://github.com/cilium/cilium/files/6539248/heap_profile639032979.zip)

**Comment by yuriydzobak** [comment] 2021-05-25 12:32
[cilium-pprof.tar.zip](https://github.com/cilium/cilium/files/6539253/cilium-pprof.tar.zip)

**Comment by yuriydzobak** [comment] 2021-05-25 12:36
[fqdn-cache-list.txt](https://github.com/cilium/cilium/files/6539275/fqdn-cache-list.txt)

**Comment by yuriydzobak** [comment] 2021-05-25 12:46
```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.4+k3s1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens5 (Direct Routing)]
Cilium:                 Ok       OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 12/255 allocated from 10.12.41.0/24,
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF   [ens5]   10.12.41.0/24
Controller Status:      68/68 healthy
  Name                                          Last success      Last error   Count   Message
  cilium-health-ep                              34s ago           never        0       no error
  dns-garbage-collector-job                     53s ago           never        0       no error
  endpoint-1117-regeneration-recovery           never             never        0       no error
  endpoint-1172-regeneration-recovery           never             never        0       no error
  endpoint-1252-regeneration-recovery           never             never        0       no error
  endpoint-1458-regeneration-recovery           never             never        0       no error
  endpoint-247-regeneration-recovery            never             never        0       no error
  endpoint-290-regeneration-recovery            never             never        0       no error
  endpoint-2966-regeneration-recovery           never             never        0       no error
  endpoint-3815-regeneration-recovery           never             never        0       no error
  endpoint-428-regeneration-recovery            never             never        0       no error
  endpoint-523-regeneration-recovery            never             never        0       no error
  endpoint-862-regeneration-recovery            never             never        0       no error
  endpoint-987-regeneration-recovery            never             never        0       no error
  k8s-heartbeat                                 19s ago           never        0       no error
  mark-k8s-node-as-available                    1323h44m10s ago   never        0       no error
  metricsmap-bpf-prom-sync                      1s ago            never        0       no error
  neighbor-table-refresh                        30s ago           never        0       no error
  resolve-identity-1117                         50s ago           never        0       no error
  resolve-identity-1172                         50s ago           never        0       no error
  resolve-identity-1252                         3m44s ago         never        0       no error
  resolve-identity-1458                         50s ago           never        0       no error
  resolve-identity-247                          55s ago           never        0       no error
  resolve-identity-290                          2m21s ago         never        0       no error
  resolve-identity-2966                         4m4s ago          never        0       no error
  resolve-identity-3815                         3m50s ago         never        0       no error
  resolve-identity-428                          55s ago           never        0       no error
  resolve-identity-523                          55s ago           never        0       no error
  resolve-identity-987                          3m49s ago         never        0       no error
  restoring-ep-identity (1117)                  1323h44m12s ago   never        0       no error
  restoring-ep-identity (1172)                  1323h44m12s ago   never        0       no error
  restoring-ep-identity (1458)                  1323h44m12s ago   never        0       no error
  restoring-ep-identity (247)                   1323h44m12s ago   never        0       no error
  restoring-ep-identity (428)                   1323h44m12s ago   never        0       no error
  restoring-ep-identity (862)                   1323h44m12s ago   never        0       no error
  sync-endpoints-and-host-ips                   40s ago           never        0       no error
  sync-lb-maps-with-k8s-services                1323h44m11s ago   never        0       no error
  sync-policymap-1117                           41s ago           never        0       no error
  sync-policymap-1172                           41s ago           never        0       no error
  sync-policymap-1252                           41s ago           never        0       no error
  sync-policymap-1458                           41s ago           never        0       no error
  sync-policymap-247                            41s ago           never        0       no error
  sync-policymap-290                            41s ago           never        0       no error
  sync-policymap-2966                           41s ago           never        0       no error
  sync-policymap-3815                           41s ago           never        0       no error
  sync-policymap-428                            41s ago           never        0       no error
  sync-policymap-523                            41s ago           never        0       no error
  sync-policymap-862                            41s ago           never        0       no error
  sync-policymap-987                            41s ago           never        0       no error
  sync-to-k8s-ciliumendpoint (1117)             0s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (1172)             10s ago           never        0       no error
  sync-to-k8s-ciliumendpoint (1252)             8s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (1458)             10s ago           never        0       no error
  sync-to-k8s-ciliumendpoint (247)              6s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (290)              5s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (2966)             9s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (3815)             4s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (428)              0s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (523)              4s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (862)              2s ago            never        0       no error
  sync-to-k8s-ciliumendpoint (987)              9s ago            never        0       no error
  template-dir-watcher                          never             never        0       no error
  update-k8s-node-annotations                   1323h44m32s ago   never        0       no error
  waiting-initial-global-identities-ep (1117)   1323h44m12s ago   never        0       no error
  waiting-initial-global-identities-ep (1172)   1323h44m12s ago   never        0       no error
  waiting-initial-global-identities-ep (1458)   1323h44m12s ago   never        0       no error
  waiting-initial-global-identities-ep (247)    1323h44m12s ago   never        0       no error
  waiting-initial-global-identities-ep (428)    1323h44m12s ago   never        0       no error
Proxy Status:     OK, ip 10.12.41.53, 22 redirects active on ports 10000-20000
Hubble:           Ok                Current/Max Flows: 4096/4096 (100.00%), Flows/s: 51.91   Metrics: Ok
Cluster health:   16/16 reachable   (2021-05-25T12:45:33Z)
```

**Comment by aanm** [comment] 2021-05-29 15:11
@yuriydzobak can you provide the output of `gops stack 1` for the cilium container with the highest memory?

**Comment by yuriydzobak** [comment] 2021-05-31 09:54
> @yuriydzobak can you provide the output of `gops stack 1` for the cilium container with the highest memory?

[stack.txt](https://github.com/cilium/cilium/files/6569446/stack.txt)

**Comment by aanm** [comment] 2021-06-01 15:58
@yuriydzobak and a heap profile of that same cilium container?

**Comment by yuriydzobak** [comment] 2021-06-02 07:12
> @yuriydzobak and a heap profile of that same cilium container?

[heap_profile.zip](https://github.com/cilium/cilium/files/6582679/heap_profile.zip)

**Comment by yuriydzobak** [comment] 2021-06-02 12:39
@aanm As you told me provide stack and heap at the same time range
[Archive.zip](https://github.com/cilium/cilium/files/6584555/Archive.zip)

**Comment by aanm** [comment] 2021-06-02 13:51
@yuriydzobak please upgrade to at least 1.9.7 (or 1.9.8) and see if the issue persists. This will help to rule out any ARP-related bugs fixed in these newer versions. Otherwise we will need to wait until https://github.com/cilium/cilium/issues/16236 is fixed.

**Comment by yuriydzobak** [comment] 2021-06-02 13:53
> @yuriydzobak please upgrade to at least 1.9.7 (or 1.9.8) and see if the issue persists. This will help to rule out any ARP-related bugs fixed in these newer versions. Otherwise we will need to wait until #16236 is fixed to see if the issue also persists.

ok, thank you
I'll provide you feedback when i'll do it

**Comment by yuriydzobak** [comment] 2021-06-03 07:14
I updated сшдшгь to version 1.9.8 on two clusters, I think we need to wait a couple of days

**Comment by yuriydzobak** [comment] 2021-06-04 07:41
@aanm 
seems, but exsits in 1.9.8
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/70581130/120764849-43fa4580-c521-11eb-81cc-69f091cc34a1.png">

**Comment by aanm** [comment] 2021-06-04 15:51
Let's wait until #16236 is also fixed then

**Comment by aanm** [comment] 2021-07-05 13:07
@yuriydzobak can you check with 1.10.2 to see if the issue still persists?

**Comment by yuriydzobak** [comment] 2021-07-15 09:48
> @yuriydzobak can you check with 1.10.2 to see if the issue still persists?

I've upgrade cilium to 1.10.2, seems the issue is still present. I'll wait a few day, then check again if memory is raising up
<img width="1603" alt="image" src="https://user-images.githubusercontent.com/70581130/125767911-04d99ad4-f17e-4112-a216-7858ff5c0540.png">

**Comment by yuriydzobak** [comment] 2021-07-21 09:21
I've upgrade to 1.10.3 version but seems, the issue is still existing
first cluster
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/70581130/126464812-2984aada-edc1-489f-adda-6d3a9731d8fe.png">

second cluster
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/70581130/126464866-ad39d67a-0b17-4973-a82a-59ae3a5b8bc0.png">

3th cluster
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/70581130/126464945-4b62d0b3-f7a5-46f6-b348-4e6841af1da3.png">

**Comment by yuriydzobak** [comment] 2021-07-22 08:08
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/70581130/126607831-aaeb4c86-9300-435f-98b9-df5159b7f2b9.png">
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/70581130/126607888-54fa7d93-5999-49e4-8880-5b894ccfa6db.png">
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/70581130/126607928-aeb02eb2-2975-4495-a485-0bd80d17ccd5.png">

**Comment by christarazi** [comment] 2021-08-04 01:39
What sort of activity is happening on the cluster to potentially cause this? Can you point to anything?

**Comment by yuriydzobak** [comment] 2021-08-04 11:05
> What sort of activity is happening on the cluster to potentially cause this? Can you point to anything?

i saw just only errors on PODs that unstable,
 and those pods have error `level=error msg="Timed out waiting for datapath updates of FQDN IP information; returning response" subsys=daemon`
 I increased `--tofqdns-proxy-response-max-delay` from 100ms to 200ms and the issue didn't show up on other PODs but it still appires on memory leak PODs
 I think, it ca cause the issue

**Comment by christarazi** [comment] 2021-08-04 15:27
@yuriydzobak Thanks, so I'm assuming you're using at least DNS policies?

**Comment by yuriydzobak** [comment] 2021-08-04 15:45
> @yuriydzobak Thanks, so I'm assuming you're using at least DNS policies? How many policies and what does the application activity look like in terms of DNS?

Yes, and coredns-nodecache with local-redirect
```
---
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: kube-dns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```
and
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: 07-allow-kube-dns
specs:
  - description: "Policy for ingress allow to kube-dns from all PODs in the cluster"
    endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    ingress:
      - fromEndpoints:
          - {}
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
  - description: "Policy for ingress allow to coredns-nodecache from all PODs in the cluster"
    endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: coredns-nodecache
    ingress:
      - fromEndpoints:
          - {}
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
  - description: "Policy for egress allow from any PODs in the cluster to kube-dns"
    endpointSelector: {}
    egress:
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: kube-system
              k8s:k8s-app: kube-dns
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
            rules:
              dns:
                - matchPattern: "*"
  - description: "Policy for egress allow from any PODs in the cluster to coredns-nodecache"
    endpointSelector: {}
    egress:
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: kube-system
              k8s:k8s-app: coredns-nodecache
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
            rules:
              dns:
                - matchPattern: "*"
  - description: "Policy for egress allow from any PODs in the cluster to node-local-dns"
    endpointSelector: {}
    egress:
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: kube-system
              k8s:k8s-app: node-local-dns
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
            rules:
              dns:
```
application CNP
```
      - toFQDNs:
          - matchName: "example.domain.com"
        toPorts:
          - ports:
              - port: "80"
                protocol: TCP
              - port: "443"
                protocol: TCP
````
Also, application uses s3 and service with exteranalName
```
logstash                                         ExternalName   <none>          logstash.domain.com
```
i see, time to time but i think it's ok
```
....
....
level=info msg="FQDN garbage collector work deleted N name entries: echo-a.monitoring.svc.cluster.local.,www.google.com.,google.com..,logstash.dc01.lf.,logstash.monitoring.svc.cluster.local.,notification-controller.gotk-system.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
......
......
```

**Comment by audrey-bond** [comment] 2021-08-18 23:27
I believe this issue is hitting me as well. 


cilium status
```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20+ (v1.20.7-eks-d88609) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled   
Cilium:                 Ok   1.10.3 (v1.10.3-4145278)
NodeMonitor:            Listening for events on 16 CPUs with 64x4096 of shared memory
                        1165 events lost, 0 unknown notifications
Cilium health daemon:   Ok   
IPAM:                   IPv4: 25/45 allocated, 
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      119/119 healthy
Proxy Status:           OK, ip 10.8.5.229, 32 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 4796.86   Metrics: Ok
Encryption:             Disabled
Cluster health:         5/5 reachable   (2021-08-18T23:11:05Z)
```

![profile001](https://user-images.githubusercontent.com/86928684/129984260-fa0b8ff6-801c-47d7-81e6-20c9a60b3db4.png)

<img width="965" alt="Screen Shot 2021-08-18 at 4 15 52 PM" src="https://user-images.githubusercontent.com/86928684/129984702-2135dd1d-ee53-416d-b6cf-454c80f5d563.png">

**Comment by yuriydzobak** [comment] 2021-08-25 12:46
when i removed from network policy
```
            rules:
              dns:
                - matchPattern: "*"
``` 
Memory leak's gone.
@christarazi @aanm do you have an idea how i can re-use DNS, to see outgoing request in hubble and see in metrics?                
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/70581130/130792627-c1964cc3-a9fd-4d81-8bf8-90cd3159ae40.png">

**Comment by christarazi** [comment] 2021-08-31 07:24
@yuriydzobak You need to keep the portion mentioned above in order get see DNS flows in hubble

**Comment by yuriydzobak** [comment] 2021-09-02 10:58
i guess, it's not critical for us but without that rule,
policydoesn't work which uses  `toFQDNs ` 
```
        - toFQDNs:
             - matchName: domain.com
```

**Comment by aditighag** [comment] 2021-09-03 16:26
@yuriydzobak Thanks for reporting the issue. 

>do you have an idea how i can re-use DNS, to see outgoing request in hubble 

If I understand your question correctly, you want to get visibility into DNS flows such that you don't run into the memory leak issue, right? You should be able to enable policy visibility - https://docs.cilium.io/en/v1.10/policy/visibility/. 

> when i removed from network policy
> 
> ```
>             rules:
>               dns:
>                 - matchPattern: "*"
> ```
> 
> Memory leak's gone.

Yeah, the memory leak seems to be coming from FQDN related code. `addNameToCleanup` looks like a potential culprit.

**Comment by yuriydzobak** [comment] 2021-09-06 12:31
> @yuriydzobak Thanks for reporting the issue.
> 
> > do you have an idea how i can re-use DNS, to see outgoing request in hubble
> 
> If I understand your question correctly, you want to get visibility into DNS flows such that you don't run into the memory leak issue, right? You should be able to enable policy visibility - https://docs.cilium.io/en/v1.10/policy/visibility/.

yes, thanks, bit this think isn't necessary for me so much
I have more troubles with 
         
when i removed   
```
            rules:
              dns:
                - matchPattern: "*"
``` 
policy stoped to work
```
        - toFQDNs:
             - matchName: domain.com
``` 
and i have to add `rules.dns.*` patter to policies that has  ` toFQDNs ` rule

**Comment by aditighag** [comment] 2021-09-07 06:24
@yuriydzobak That rule is required to allow all DNS queries egressing on port 53 so that they are forwarded to the DNS proxy. It's documented here - https://docs.cilium.io/en/v1.10/gettingstarted/dns/#apply-dns-egress-policy. 

Based on the heap profile you shared, we suspect that entries from the map clean-up map aren't getting GC'd correctly, the relevant code path - https://github.com/cilium/cilium/blob/master/pkg/fqdn/cache.go#L224.

**Comment by aditighag** [comment] 2021-09-07 06:53
@yuriydzobak I checked the sysdump shared in the commit description, but I don't see output of `cilium fqdn cache list `. Is it possible for you to get the output from a cluster where you are seeing the memory leak problem? You can redact any sensitive information, or share it with me privately on Slack.

**Comment by yuriydzobak** [comment] 2021-09-17 15:46
> @yuriydzobak I checked the sysdump shared in the commit description, but I don't see output of `cilium fqdn cache list `. Is it possible for you to get the output from a cluster where you are seeing the memory leak problem? You can redact any sensitive information, or share it with me privately on Slack.

https://github.com/cilium/cilium/issues/16300#issuecomment-847832134

**Comment by yuriydzobak** [comment] 2021-09-17 16:02
i'll provide you sysdump

**Comment by aditighag** [comment] 2021-09-17 16:13
@yuriydzobak Based on the graph you shared above, it looks like the memory build-up is happening over a week or so. If you end up reproducing the issue, it would be helpful to get multiple traces so that we can do pprof diff against a base profile. Could you collect a base heap profile before the problem starts, and then collect 2-3 traces separated by a couple of days as the memory leak issue is occurring? 
/cc @aanm in case he is looking for additional information.

**Closed as completed** 2021-09-22 05:53 UTC
Labels: kind/bug, needs/triage, kind/community-report
