### ISSUE TITLE
"ICMP rules can only be applied when the "enable-icmp-rules" flag is set" in CiliumClusterwideNetworkPolicy status, but --enable-icmp-rules='true' is applied

### ISSUE THREAD

**Issue by agrevtsev** [cilium/cilium#35214] opened 2024-10-03 22:52 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

 I have a CiliumClusterwideNetworkPolicy which also includes ICMP rule
```
    - fromEntities:
        - all
      icmps:
        - fields:
            - family: IPv4
              type: 3
            - family: IPv4
              type: 8
            - family: IPv4
              type: 11
```
in status i see such
```
status:
  conditions:
  - lastTransitionTime: "2024-09-22T06:55:26Z"
    message: ICMP rules can only be applied when the "enable-icmp-rules" flag is set
    status: "False"
    type: Valid
```
but in cilium-agent log i see the flag is actually enabled
```
k logs -n kube-system cilium-pwn5s cilium-agent | grep icmp
time="2024-09-22T06:35:40Z" level=info msg="  --allow-icmp-frag-needed='true'" subsys=daemon
time="2024-09-22T06:35:40Z" level=info msg="  --enable-icmp-rules='true'" subsys=daemon
```

### How can we reproduce the issue?

Install RKE2 v1.30.4+rke2r1 cluster with Cilium CNI, add CiliumClusterwideNetworkPolicy with ICMP rule.

### Cilium Version

Client: 1.16.0 82999990 2024-07-23T22:22:14-07:00 go version go1.22.5 linux/amd64
Daemon: 1.16.0 82999990 2024-07-23T22:22:14-07:00 go version go1.22.5 linux/amd64

### Kernel Version

Linux worker-01 5.15.0-121-generic #131-Ubuntu SMP Fri Aug 9 08:29:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4+rke2r1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2024-10-03 23:41
It looks like the validation is occurring in the `cilium-operator`, but the Cilium operator doesn't have this flag so there's no way for it to know whether the feature is enabled or not:

```
$ git grep AllowICMPFragNeeded
daemon/cmd/daemon_main.go:      flags.Bool(option.AllowICMPFragNeeded, defaults.AllowICMPFragNeeded, "Allow ICMP Fragmentation Needed type packets for purposes like TCP Path MTU.")
daemon/cmd/daemon_main.go:      option.BindEnv(vp, option.AllowICMPFragNeeded)
pkg/datapath/linux/config/config.go:    if option.Config.AllowICMPFragNeeded {
pkg/defaults/defaults.go:       // AllowICMPFragNeeded is the default value for option.AllowICMPFragNeeded flag.
pkg/defaults/defaults.go:       AllowICMPFragNeeded = true
pkg/option/config.go:   // AllowICMPFragNeeded allows ICMP Fragmentation Needed type packets in policy.
pkg/option/config.go:   AllowICMPFragNeeded = "allow-icmp-frag-needed"
pkg/option/config.go:   // AllowICMPFragNeeded allows ICMP Fragmentation Needed type packets in
pkg/option/config.go:   AllowICMPFragNeeded bool
pkg/option/config.go:           AllowICMPFragNeeded:             defaults.AllowICMPFragNeeded,
pkg/option/config.go:   c.AllowICMPFragNeeded = vp.GetBool(AllowICMPFragNeeded)
```

Two possible solutions:
1. Add the same flag also to the cilium-operator, or
2. Modify the operator to validate the policy assuming this flag is enabled. This would mark the policy as valid, but then the individual agents could still reject the policy because they can't implement a feature that's disabled on the commandline.

**Comment by chez-shanpu** [comment] 2024-10-04 04:42
As another solution, I think `enable-icmp-rules` can be deleted.
I left this flag to be able to disable it when a bug happens. (https://github.com/cilium/cilium/pull/20174#discussion_r895208523)
If this feature seems stable, we can delete this option.

**Comment by julianwiedmann** [comment] 2024-10-04 10:53
@cilium/sig-policy fyi, this looks like a regression from the network policy validation changes. I _think_ the suggestion above makes sense (removing this additional config option) - but you might want to consider whether v1.16 needs a different fix.

**Comment by roth-wine** [comment] 2024-10-18 09:01
Any updates on this issue?

**Comment by squeed** [comment] 2024-10-18 18:50
(For posterity's sake I will leave this as a regression, but it's not *really* a regression since policies continue to work unchanged).

**Comment by squeed** [comment] 2024-10-29 10:10
I've filed a PR to fix this; once landed, it will automatically be backported to v1.16 as needed.

**Closed as completed** 2024-10-31 09:19 UTC
Labels: kind/bug, sig/policy, kind/community-report, kind/regression, area/agent
