### ISSUE TITLE
NACK found in logs

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#4347] opened 2018-06-04 08:47 UTC
Test: k8s-1.10.K8sValidatedServicesTest Bookinfo Demo Tests bookinfo demo
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/2693/testReport/k8s-1/10/K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo/
Stacktrace: 

```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:303
Found a "NACK received for version" in Cilium logs
Expected
Too long. Logs attached! 

```

Standard Output
```
STEP: Creating objects in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1.yaml"
STEP: Creating objects in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2.yaml"
STEP: Waiting for pods to be ready
STEP: Waiting for services to be ready
STEP: Validating DNS without Policy
STEP: All pods should be able to connect without policy
STEP: Checking that "reviews-v1-5d8c9f4d5b-mnsrt" can connect to "ratings.default.svc.cluster.local:9080/health"
STEP: Checking that "reviews-v1-5d8c9f4d5b-mnsrt" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
STEP: Checking that "productpage-v1-c4d87f5d7-dr76h" can connect to "details.default.svc.cluster.local:9080/health"
STEP: Checking that "productpage-v1-c4d87f5d7-dr76h" can connect to "ratings.default.svc.cluster.local:9080/health"
STEP: Checking that "productpage-v1-c4d87f5d7-dr76h" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
STEP: Importing policy
STEP: Checking that policies were correctly imported into Cilium
STEP: Validating DNS with Policy loaded
STEP: After policy import
STEP: Checking that "reviews-v1-5d8c9f4d5b-mnsrt" can connect to "ratings.default.svc.cluster.local:9080/health"
STEP: Checking that "reviews-v1-5d8c9f4d5b-mnsrt" cannot connect to "ratings.default.svc.cluster.local:9080/ratings/0"
STEP: Checking that "productpage-v1-c4d87f5d7-dr76h" can connect to "details.default.svc.cluster.local:9080/health"
STEP: Checking that "productpage-v1-c4d87f5d7-dr76h" cannot connect to "ratings.default.svc.cluster.local:9080/health"
STEP: Checking that "productpage-v1-c4d87f5d7-dr76h" cannot connect to "ratings.default.svc.cluster.local:9080/ratings/0"
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE       IP              NODE
default       details-v1-c67b456b7-gjz7w       1/1       Running   0          2m        10.10.1.117     k8s2
default       productpage-v1-c4d87f5d7-dr76h   1/1       Running   0          2m        10.10.1.170     k8s2
default       ratings-v1-8474bf59-wnhl5        1/1       Running   0          2m        10.10.0.172     k8s1
default       reviews-v1-5d8c9f4d5b-mnsrt      1/1       Running   0          2m        10.10.1.141     k8s2
default       reviews-v2-59459c7bf4-kvrwc      1/1       Running   0          2m        10.10.0.179     k8s1
kube-system   cilium-vg9td                     1/1       Running   0          14m       192.168.36.12   k8s2
kube-system   cilium-wj8qs                     1/1       Running   0          14m       192.168.36.11   k8s1
kube-system   etcd-k8s1                        1/1       Running   0          31m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1              1/1       Running   0          30m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1     1/1       Running   0          30m       192.168.36.11   k8s1
kube-system   kube-dns-59d8c5f9b5-wj989        3/3       Running   3          31m       10.10.1.243     k8s2
kube-system   kube-proxy-x2bdw                 1/1       Running   0          24m       192.168.36.12   k8s2
kube-system   kube-proxy-zrb4c                 1/1       Running   0          31m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1              1/1       Running   0          30m       192.168.36.11   k8s1

cmd: kubectl exec -n kube-system cilium-vg9td -- cilium service list
ID   Frontend               Backend                   
1    10.96.0.10:53          1 => 10.10.1.243:53       
2    10.98.148.32:80        1 => 10.10.0.99:80        
                            2 => 10.10.1.205:80       
3    10.108.109.243:10080   1 => 10.10.0.99:80        
                            2 => 10.10.1.205:80       
4    10.96.0.1:443          1 => 192.168.36.11:6443   
5    10.107.250.60:10080    1 => 10.10.0.134:80       
                            2 => 10.10.1.157:80       
6    10.97.216.104:80       1 => 10.10.0.134:80       
                            2 => 10.10.1.157:80       
16   10.99.72.188:9080      1 => 10.10.1.117:9080     
17   10.109.130.153:9080    1 => 10.10.1.141:9080     
                            2 => 10.10.0.179:9080     
18   10.111.220.116:9080    1 => 10.10.1.170:9080     
19   10.110.145.29:9080     1 => 10.10.0.172:9080     

cmd: kubectl exec -n kube-system cilium-vg9td -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                   IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                     
5329       Disabled           Disabled          54257      k8s:app=productpage                           f00d::a0a:100:0:14d1   10.10.1.170   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:track=stable                                                                           
                                                           k8s:version=v1                                                                             
                                                           k8s:zgroup=bookinfo                                                                        
15780      Disabled           Disabled          18255      k8s:app=reviews                               f00d::a0a:100:0:3da4   10.10.1.141   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:track=stable                                                                           
                                                           k8s:version=v1                                                                             
                                                           k8s:zgroup=bookinfo                                                                        
26743      Disabled           Disabled          6044       k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:100:0:6877   10.10.1.243   ready   
                                                           k8s:k8s-app=kube-dns                                                                       
38675      Enabled            Disabled          7622       k8s:app=details                               f00d::a0a:100:0:9713   10.10.1.117   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:track=stable                                                                           
                                                           k8s:version=v1                                                                             
                                                           k8s:zgroup=bookinfo                                                                        
63703      Disabled           Disabled          4          reserved:health                               f00d::a0a:100:0:f8d7   10.10.1.61    ready   

cmd: kubectl exec -n kube-system cilium-wj8qs -- cilium service list
ID   Frontend               Backend                   
1    10.96.0.10:53          1 => 10.10.1.243:53       
2    10.98.148.32:80        1 => 10.10.0.99:80        
                            2 => 10.10.1.205:80       
3    10.108.109.243:10080   1 => 10.10.1.205:80       
                            2 => 10.10.0.99:80        
4    10.96.0.1:443          1 => 192.168.36.11:6443   
5    10.107.250.60:10080    1 => 10.10.0.134:80       
                            2 => 10.10.1.157:80       
6    10.97.216.104:80       1 => 10.10.0.134:80       
                            2 => 10.10.1.157:80       
16   10.99.72.188:9080      1 => 10.10.1.117:9080     
17   10.109.130.153:9080    1 => 10.10.0.179:9080     
                            2 => 10.10.1.141:9080     
18   10.111.220.116:9080    1 => 10.10.1.170:9080     
19   10.110.145.29:9080     1 => 10.10.0.172:9080     

cmd: kubectl exec -n kube-system cilium-wj8qs -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])               IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                               
6952       Disabled           Disabled          43152      k8s:app=reviews                           f00d::a0a:0:0:1b28   10.10.0.179   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                              
                                                           k8s:version=v2                                                                       
                                                           k8s:zgroup=bookinfo                                                                  
41898      Disabled           Disabled          4          reserved:health                           f00d::a0a:0:0:a3aa   10.10.0.242   ready   
43363      Enabled            Disabled          52596      k8s:app=ratings                           f00d::a0a:0:0:a963   10.10.0.172   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                              
                                                           k8s:version=v1                                                                       
                                                           k8s:zgroup=bookinfo                                                                  

===================== EXITING REPORT GENERATION =====================
STEP: Deleting resource /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1.yaml
STEP: Deleting resource /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2.yaml
```

[10cd9672_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip](https://github.com/cilium/cilium/files/2067465/10cd9672_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip)

**Comment by jrajahalme** [comment] 2018-06-04 16:04
Duplicate of #4277

**Closed as completed by jrajahalme** 2018-06-04 16:05 UTC
Labels: priority/high, area/CI
