### ISSUE TITLE
Found a 'JoinEP: ' in Cilium Logs

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#6086] opened 2018-10-29 13:32 UTC
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1825/consoleFull

```
[ATTACHMENT|ad7af576_K8sTunnelTest_Geneve_Check_Geneve_mode.zip]]
23:42:55 [K8s-1.8] 
23:42:55 [K8s-1.8] • Failure in Spec Teardown (AfterEach) [1042.330 seconds]
23:42:55 [K8s-1.8] K8sTunnelTest
23:42:55 [K8s-1.8] /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
23:42:55 [K8s-1.8]   Geneve
23:42:55 [K8s-1.8]   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
23:42:55 [K8s-1.8]     Check Geneve mode [AfterEach]
23:42:55 [K8s-1.8]     /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
23:42:55 [K8s-1.8] 
23:42:55 [K8s-1.8]     Found a 'JoinEP: ' in Cilium Logs
23:42:55 [K8s-1.8] 
23:42:55 [K8s-1.8]     /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:474
```
First time I ever saw it

**Comment by aanm** [comment] 2018-10-29 15:05
Duplicate of https://github.com/cilium/cilium/issues/6059

**Closed as completed by aanm** 2018-10-29 15:05 UTC
