### ISSUE TITLE
init cilium with  multi-pool will create the wrong pod-cidr router with k8s node cidr ,not ciliumnode cidr

### ISSUE THREAD

**Issue by hanji-cn** [cilium/cilium#34446] opened 2024-08-19 04:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

A bug happened!
i use helm to init cilium, when i use the default cluster-pool (172.31.0.0/16, maskSize 26), it works fine.
but if i change the value.yaml to  multi-pool with autoCreateCiliumPodIPPools:   default , the k8s work failed.
After i check, it was cause be the wrong cilium pod-cidr router in each nodes.
Such as my cilium master node, its pod cidr is - 172.31.0.128/26, pod internal ip is 172.31.0.139.

Cilium should create a router as :  172.31.0.128/26 via 172.31.0.139 dev cilium_host proto kernel src 172.31.0.139 

But in fact , it create a wrong router as: 172.31.0.0/24 via 172.31.0.139 dev cilium_host proto kernel src 172.31.0.139 
after i checked, the 172.31.0.0/24 is my k8s node podCIDR: 172.31.0.0/24. (when init k8s, i didn't assign the podmask, it use defautl /24).
(k8s assign the first cidr to the first node-master node, but cilium assgin the fir cidr to its first node, one of my work node, it cause the network also not match)

### How can we reproduce the issue?

1. init k8s v1.30.1 with pod subnet 172.31.0.0/16 (k8s will auto assign /24 podCIDR to each k8s nodes)
2. install cilium v1.16.1 with helm, change ipam  part as below:
ipam:
  #mode: "cluster-pool"
  mode: multi-pool
  # -- Maximum rate at which the CiliumNode custom resource is updated.
  ciliumNodeUpdateRate: "15s"
  operator:
    #clusterPoolIPv4PodCIDRList: ["172.31.0.0/16"]
    #clusterPoolIPv4MaskSize: 26
    #clusterPoolIPv6PodCIDRList: ["fd00::/104"]
    #clusterPoolIPv6MaskSize: 120
    #autoCreateCiliumPodIPPools: {}
    autoCreateCiliumPodIPPools:
      default:
        ipv4:
          cidrs:
            - 172.31.0.0/17
          maskSize: 26
4. after cilium work, check each node's route table, will find the pod-cidr router is wrong.

### Cilium Version

cilium-cli: v0.16.15 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.16.0
cilium image (stable): v1.16.1
cilium image (running): 1.16.1

### Kernel Version

Linux k8s-0-01 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1

### Sysdump

[cilium-sysdump-20240817-124741.zip](https://github.com/user-attachments/files/16655898/cilium-sysdump-20240817-124741.zip)

### Relevant log output

```shell
k8s@k8s-0-01:~/20240815/cilium/cilium-v1.16.1$ k get nodes k8s-0-01 -oyaml | grep 172
  podCIDR: 172.31.0.0/24
 - 172.31.0.0/24
k8s@k8s-01:~$ k get ciliumnode k8s-0-01 -oyaml | grep 172
  - ip: 172.31.0.139
    ipv4: 172.31.0.143
        - 172.31.0.128/26
k8s@k8s-0-01:~/20240815/cilium$ k logs -n kube-system  cilium-dlkzl | grep 172.31.0.0/24
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), clean-cilium-state (init), install-cni-binaries (init)
time="2024-08-17T04:43:11Z" level=info msg="Received own node information from API server" ipAddr.ipv4=11.3.10.89 ipAddr.ipv6="<nil>" k8sNodeIP=11.3.10.89 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:k8s-0-01 kubernetes.io/os:linux node-role.kubernetes.io/control-plane: node.kubernetes.io/exclude-from-external-load-balancers:]" nodeName=k8s-0-01 subsys=daemon v4Prefix=172.31.0.0/24 v6Prefix="<nil>"
time="2024-08-17T04:43:11Z" level=info msg="  IPv4 allocation prefix: 172.31.0.0/24" subsys=daemon
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2024-08-31 13:46
Hi, does the same happen if you install with multi-pool configuration from the initial install of Cilium, or does this only happen when changing the IPAM mode after installation?

**Comment by hanji-cn** [comment] 2024-09-01 02:45
It happened in the follow 2 scene:
1. when install with multi-pool configuration from the initial install of Cilium with auto-create default pool.
2. change mode from cluster-pool to muliti-pool with follow step
1)cilium config set ipam multi-pool
2)then create the different default pool (make sure each ciliumnode cidr is different with the cluster-pool mode cidr, if it is same)
3)delete all ciliumnode
4) restart cilium to auto recreate the ciliumnode

PS: Its seems cilium create the ciliumnode route with the k8s-node cidr, not cilium-node cidr
when initial with cluster-pool, the route of cilium pod is right, and if i change the mode from cluster-pool to muliti-pool,  the multi-pool default pool will not auto-create, and if i create

**Comment by gandro** [comment] 2024-09-03 08:00
Please note: It is currently not possible to change the IPAM mode after installation. This is documented here: https://docs.cilium.io/en/stable/network/concepts/ipam/#address-management

**Comment by hanji-cn** [comment] 2024-09-04 08:32
> Please note: It is currently not possible to change the IPAM mode after installation. This is documented here: https://docs.cilium.io/en/stable/network/concepts/ipam/#address-management

The issue was hit first in the installation.
and just for answer joestringer question to confirm is it be hit "when changing the IPAM mode after installation".
if it is not support change the IPAM mode, please focus on the installation issue.

**Comment by gandro** [comment] 2024-09-04 08:40
Thanks for the update. Maybe I'm missing something, but I don't see any reproduction steps for "the installation issue". Both the reproduction steps in the original post and the one posted later do change the IPAM mode at some point.

Could you share the exact reproduction steps to reproduce "the installation issue"? Thank you!

**Comment by hanji-cn** [comment] 2024-09-04 08:53
> Thanks for the update. Maybe I'm missing something, but I don't see any reproduction steps for "the installation issue". Both the reproduction steps in the original post and the one posted later do change the IPAM mode at some point.
> 
> Could you share the exact reproduction steps to reproduce "the installation issue"? Thank you!
please see the first tips
"How can we reproduce the issue?"

**Comment by gandro** [comment] 2024-09-04 10:04
Thanks!

>  edit value.yaml, change to multi-pool

Yes, this is _not supported_ as per the documentation. You cannot enable multi-pool after Cilium has already been installed. 

We have discussed implementing a migration from cluster-pool to multi-pool in the future, but this functionality does not exist yet.

**Comment by gandro** [comment] 2024-09-04 12:59
I see. Did you delete all CiliumNode objects before the new installation?

**Comment by hanji-cn** [comment] 2024-09-04 13:04
> I see. Did you delete all CiliumNode objects before the new installation?

this first time i create this issue in a new k8s cluster (not install any CNI before), the only thing before install Cilium is all k8s node had added into this cluster .
(It seems this issue was cilium use the k8s-node's pod cidr to create the wrong route, and k8s assign the cidr with order: master, node1,node2, but cilium assign cidr with node2/node1/master, and maybe i also change the netmask not equal 24--k8s default netmask)
And i also can re-produce it in same situation (revert 3 node to the original snopshot to reproduce it )

**Comment by gandro** [comment] 2024-09-04 13:19
Understood, if it also fails on a clean cluster then this clearly is not the issue.

I did notice another problem with your configuration though. The [documentation says](https://docs.cilium.io/en/v1.16/network/concepts/ipam/multi-pool/#limitations) 

> Multi-Pool IPAM does not support local node routes (enable-local-node-route) and requires the use of per-endpoint routes (see [Native-Routing](https://docs.cilium.io/en/v1.16/network/concepts/routing/#native-routing)) instead.

I do not see the use of per-endpoint routes in your configuration. It could be that the wrong pod CIDRs you are seeing are due to the local node routes. Please make sure to set `endpointRoutes.enabled=true` in your Helm configuration.

**Comment by hanji-cn** [comment] 2024-09-04 13:33
> Understood, if it also fails on a clean cluster then this clearly is not the issue.
> 
> I did notice another problem with your configuration though. The [documentation says](https://docs.cilium.io/en/v1.16/network/concepts/ipam/multi-pool/#limitations)
> 
> > Multi-Pool IPAM does not support local node routes (enable-local-node-route) and requires the use of per-endpoint routes (see [Native-Routing](https://docs.cilium.io/en/v1.16/network/concepts/routing/#native-routing)) instead.
> 
> I do not see the use of per-endpoint routes in your configuration. It could be that the wrong pod CIDRs you are seeing are due to the local node routes. Please make sure to set `endpointRoutes.enabled=true` in your Helm configuration.

thank you. it works now in a new installation with endpointRoutes.enabled.

**Comment by gandro** [comment] 2024-09-04 13:47
Awesome! I'm closing this issue as completed then. 

We do hope we can eventually lift this restriction and support local-node-routes with multi-pool too, but at the moment most developers working on IPAM seem to lack the cycles to work on this.

**Closed as completed by gandro** 2024-09-04 13:47 UTC
Labels: kind/bug, needs/triage, kind/community-report, area/multipool
