### ISSUE TITLE
Panic observed on etcd restart

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3520] opened 2018-04-04 19:32 UTC
```
level=debug msg="Waiting for endpoint representing container to appear" containerID=418ae5c8f0 maxRetry=20 retry=9 subsys=containerd-watcher
2018/04/04 19:23:14 http: panic serving @: write unix /var/run/cilium/cilium.sock->@: write: broken pipe
goroutine 1786 [running]:
net/http.(*conn).serve.func1(0xc4201a70e0)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x1b6d280, 0xc421bcdc70)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthzOK).WriteResponse(0xc4202d7978, 0x2dfbd80, 0xc4238990a0, 0x2ddc500, 0x1e9fde0)
	/go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz_responses.go:54 +0xed
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc4240fa600, 0x2dfbd80, 0xc4238990a0, 0xc423897000, 0xc421a45c70, 0x1, 0x1, 0xc42343cd20, 0x1b63180, 0xc4202d7978)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/context.go:472 +0x5ef
github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthz).ServeHTTP(0xc423fba0a0, 0x2dfbd80, 0xc4238990a0, 0xc4244c2500)
	/go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz.go:61 +0x1d0
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x2dfbd80, 0xc4238990a0, 0xc4244c2500)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc423db96a0, 0x2dfbd80, 0xc4238990a0, 0xc4244c2500)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:73 +0x364
net/http.HandlerFunc.ServeHTTP(0xc423064180, 0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x94
net/http.HandlerFunc.ServeHTTP(0xc4218a6f00, 0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x73
net/http.HandlerFunc.ServeHTTP(0xc4218a6f40, 0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc4230645e0, 0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:36 +0x92
net/http.serverHandler.ServeHTTP(0xc4214dd1e0, 0x2dfbd80, 0xc4238990a0, 0xc422114f00)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4201a70e0, 0x2dfd800, 0xc4236f4080)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by joestringer** [comment] 2018-04-04 19:37
Here's the inner function:

https://github.com/cilium/cilium/blob/a0ea93372d8a3040f19db257ee998c925900d1c2/api/v1/server/restapi/daemon/get_healthz_responses.go#L48-L57

Here's the metrics middleware outer caller:
https://github.com/cilium/cilium/blob/a0ea93372d8a3040f19db257ee998c925900d1c2/pkg/metrics/middleware.go#L32-L37

@raybejjani Perhaps we need to add some exception handling in the metrics middleware?

**Comment by tgraf** [comment] 2018-04-05 02:06
Observed again:
```
oroutine 2420 [running]:
net/http.(*conn).serve.func1(0xc421d032c0)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x1b6dda0, 0xc421c3d9a0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthzOK).WriteResponse(0xc421d73e10, 0x2dfcda0, 0xc423ddd180, 0x2ddd520, 0x1ea0a88)
	/go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz_responses.go:54 +0xed
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc4220ffaa0, 0x2dfcda0, 0xc423ddd180, 0xc423664e00, 0xc421c63bf0, 0x1, 0x1, 0xc421f2a1e0, 0x1b63ca0, 0xc421d73e10)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/context.go:472 +0x5ef
github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthz).ServeHTTP(0xc420cd4d20, 0x2dfcda0, 0xc423ddd180, 0xc4233da000)
	/go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz.go:61 +0x1d0
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x2dfcda0, 0xc423ddd180, 0xc4233da000)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc422ee4150, 0x2dfcda0, 0xc423ddd180, 0xc4233da000)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:73 +0x364
net/http.HandlerFunc.ServeHTTP(0xc4218b2620, 0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x94
net/http.HandlerFunc.ServeHTTP(0xc422187f00, 0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x73
net/http.HandlerFunc.ServeHTTP(0xc422187f40, 0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc4218b2aa0, 0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:36 +0x92
net/http.serverHandler.ServeHTTP(0xc4213fdc70, 0x2dfcda0, 0xc423ddd180, 0xc423359f00)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc421d032c0, 0x2dfe820, 0xc421926fc0)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by raybejjani** [comment] 2018-04-05 11:09
This is a duplicate of https://github.com/cilium/cilium/issues/3294 (and probably https://github.com/cilium/cilium/issues/649). I think we decided it was because the remote peer had closed the connection and we were still writing. I'm not sure why swagger decided to panic on error, since this situation is quite common on the internet (this is setting aside that it's not the way the language intended for panics to be used nor is it appropriate for a library to do this).
To be clear, though, this panic is caught and the agent does not restart. It's caught by net/http at https://golang.org/src/net/http/server.go?s=0:0#L1723 which is where the `http: panic serving` is put in. We can do what @joestringer suggests and catch the panic sooner so that we can format it as we please. The question then becomes: Should it log as an error, warn or debug?

**Comment by tgraf** [comment] 2018-04-10 00:38
Hit again:
```
2018-04-09T13:39:35.29405646Z 2018/04/09 13:39:35 http: panic serving @: write unix /var/run/cilium/cilium.sock->@: write: broken pipe
2018-04-09T13:39:35.294138415Z goroutine 1730 [running]:
2018-04-09T13:39:35.294152156Z net/http.(*conn).serve.func1(0xc42148d7c0)
2018-04-09T13:39:35.294159631Z 	/usr/local/go/src/net/http/server.go:1697 +0xd0
2018-04-09T13:39:35.294166297Z panic(0x1b6dda0, 0xc422f245a0)
2018-04-09T13:39:35.294172692Z 	/usr/local/go/src/runtime/panic.go:491 +0x283
2018-04-09T13:39:35.294179475Z github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthzOK).WriteResponse(0xc424ade188, 0x2dfcda0, 0xc423b65260, 0x2ddd520, 0x1ea0a88)
2018-04-09T13:39:35.29418668Z 	/go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz_responses.go:54 +0xed
2018-04-09T13:39:35.294193979Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc424965b90, 0x2dfcda0, 0xc423b65260, 0xc4220f8400, 0xc4243c5f90, 0x1, 0x1, 0xc42475a1e0, 0x1b63ca0, 0xc424ade188)
2018-04-09T13:39:35.294201274Z 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/context.go:472 +0x5ef
2018-04-09T13:39:35.294208149Z github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthz).ServeHTTP(0xc423969c00, 0x2dfcda0, 0xc423b65260, 0xc423b28600)
2018-04-09T13:39:35.294215066Z 	/go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz.go:61 +0x1d0
2018-04-09T13:39:35.29422176Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x2dfcda0, 0xc423b65260, 0xc423b28600)
2018-04-09T13:39:35.294228563Z 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x6e
2018-04-09T13:39:35.294235384Z net/http.HandlerFunc.ServeHTTP(0xc4244fef60, 0x2dfcda0, 0xc423b65260, 0xc423b28600)
2018-04-09T13:39:35.294242043Z 	/usr/local/go/src/net/http/server.go:1918 +0x44
2018-04-09T13:39:35.294248539Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.294255211Z 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:73 +0x364
2018-04-09T13:39:35.294262591Z net/http.HandlerFunc.ServeHTTP(0xc421d78ce0, 0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.294269184Z 	/usr/local/go/src/net/http/server.go:1918 +0x44
2018-04-09T13:39:35.294275788Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.294306798Z 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x94
2018-04-09T13:39:35.294317873Z net/http.HandlerFunc.ServeHTTP(0xc424c8bbc0, 0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.294324582Z 	/usr/local/go/src/net/http/server.go:1918 +0x44
2018-04-09T13:39:35.294330936Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.29433752Z 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x73
2018-04-09T13:39:35.294344326Z net/http.HandlerFunc.ServeHTTP(0xc424c8bc00, 0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.29435081Z 	/usr/local/go/src/net/http/server.go:1918 +0x44
2018-04-09T13:39:35.294357267Z github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc421d79160, 0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.294363986Z 	/go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:36 +0x92
2018-04-09T13:39:35.294370357Z net/http.serverHandler.ServeHTTP(0xc4218cac30, 0x2dfcda0, 0xc423b65260, 0xc423b28500)
2018-04-09T13:39:35.294376593Z 	/usr/local/go/src/net/http/server.go:2619 +0xb4
2018-04-09T13:39:35.294383329Z net/http.(*conn).serve(0xc42148d7c0, 0x2dfe820, 0xc4247d5a00)
2018-04-09T13:39:35.294389694Z 	/usr/local/go/src/net/http/server.go:1801 +0x71d
2018-04-09T13:39:35.294396094Z created by net/http.(*Server).Serve
2018-04-09T13:39:35.294402295Z 	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Closed as completed** 2018-04-10 15:59 UTC
Labels: kind/bug, area/metrics
