### ISSUE TITLE
cilium-health status returns outdated results.

### ISSUE THREAD

**Issue by Ian-Greene** [cilium/cilium#18559] opened 2022-01-20 14:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've been working on debugging what at first looked like an issue with node endpoint connectivity. However after debugging it seems like that's not the case. Running `kubectl exec -ti <cilium_agent> -- cilium-health status` returns among other things
```Endpoint connectivity to <old_ip>:
 ICMP to stack: Connection timed out
 HTTP to agent: Get "http://<old_ip>:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

while running `kubectl exec -ti <cilium_agent> -- cilium-health status —probe` returns

```Endpoint connectivity to <new_ip>:
 ICMP to stack: OK, RTT=611.012µs
 HTTP to agent: OK, RTT=924.653µs
```

If I query the cilium agent on the node that allegedly can’t be reached with` kubectl exec -ti <agent_with_endpoint_I_want_to_reach> -- cilium endpoint list` I see

```ENFORCEMENT    ENFORCEMENT
22    Disabled     Disabled     4     reserved:health                                               <new_ip>  ready
```

We are not observing this issue on all cilium agents, but at least one agent is stuck like this. I've left it up for days but what seems to be the cached health check results are not updated.

I asked for help with my issue in the Cilium slack channel and it seems like perhaps there is some cached data here that is not bing cleared out?

### Cilium Version

1.11.0

### Kernel Version

5.4.156-83.273.amzn2.x86_64

### Kubernetes Version

v1.19.15-eks-9c63c4

### Sysdump

Too large to upload it seems?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment] 2022-01-20 14:50
Please try upgrading to [v1.11.1](https://github.com/cilium/cilium/releases/tag/v1.11.1). It has the fix for the stale health checks issue which might resolve your issue too.

**Comment by aigarm** [comment] 2022-01-22 12:14
@Ian-Greene did You tried to upgrade to the latest v1.11.1?
I upgraded directly from v1.10.4 to v1.11.1 and i can see same behavior.

**Comment by Ian-Greene** [comment] 2022-01-24 18:33
@aigarm we tried upgrading to v1.11.1 and created a new cluster. So far no issues but we will be on the lookout for this behavior re-appearing. Thanks for the advice @brb

**Comment by brb** [comment] 2022-01-24 19:23
>  I upgraded directly from v1.10.4 to v1.11.1 and i can see same behavior.

I guess the upgrade path is still broken.

@aigarm Could you attach the sysdump? Also, cc @aanm and @christarazi who fixed the previously mentioned issue.

**Comment by aigarm** [comment] 2022-01-25 07:28
@brb You where right. I upgraded to latest v1.10.7 and then to v1.11.1 - now everything seems nice.
Thanks!

**Comment by brb** [comment] 2022-01-25 08:30
Great. Then let's close this issue. If the issue persists, please comment it so we can reopen it.

**Closed as completed by brb** 2022-01-25 08:30 UTC
Labels: kind/bug, area/datapath, needs/triage, kind/community-report, area/agent

**Comment by ileixe** [comment] 2022-02-16 13:04
What's the exact PR to resolve this issue? As we've seen this issue for a while, I'm curious what was the root cause.
