### ISSUE TITLE
CI: K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#13236] opened 2020-09-21 14:51 UTC
There seems to be a rare port conflict in this test:

```
/home/jenkins/workspace/cilium-master-K8s-all/1.15-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
cannot install connectivity-check
Expected command: kubectl apply --force=false -f /home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes/connectivity-check/connectivity-check-proxy.yaml 
To succeed, but it failed:
Exitcode: 1 
Err: Process exited with status 1
Stdout:
 	 deployment.apps/echo-c created
	 deployment.apps/echo-c-host created
	 deployment.apps/pod-to-a-intra-node-proxy-egress-policy created
	 deployment.apps/pod-to-a-multi-node-proxy-egress-policy created
	 deployment.apps/pod-to-c-intra-node-proxy-ingress-policy created
	 deployment.apps/pod-to-c-multi-node-proxy-ingress-policy created
	 deployment.apps/pod-to-c-intra-node-proxy-to-proxy-policy created
	 deployment.apps/pod-to-c-multi-node-proxy-to-proxy-policy created
	 service/echo-c created
	 service/echo-c-headless created
	 service/echo-c-host-headless created
	 ciliumnetworkpolicy.cilium.io/pod-to-a-intra-node-proxy-egress-policy created
	 ciliumnetworkpolicy.cilium.io/pod-to-a-multi-node-proxy-egress-policy created
	 ciliumnetworkpolicy.cilium.io/pod-to-c-intra-node-proxy-to-proxy-policy created
	 ciliumnetworkpolicy.cilium.io/pod-to-c-multi-node-proxy-to-proxy-policy created
	 ciliumnetworkpolicy.cilium.io/echo-c created
	 deployment.apps/echo-a created
	 service/echo-a created
	 deployment.apps/echo-b created
	 deployment.apps/echo-b-host created
	 service/echo-b-host-headless created
	 deployment.apps/echo-c configured
	 service/echo-c unchanged
	 ciliumnetworkpolicy.cilium.io/echo-c unchanged
	 deployment.apps/echo-c-host configured
	 service/echo-c-host-headless configured
	 
Stderr:
 	 The Service "echo-b" is invalid: spec.ports[0].nodePort: Invalid value: 31313: provided port is already allocated
	 

/home/jenkins/workspace/cilium-master-K8s-all/1.15-gopath/src/github.com/cilium/cilium/test/k8sT/Policies.go:1490
```

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/5663/testReport/junit/Suite-k8s-1/12/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/

https://jenkins.cilium.io/job/cilium-master-K8s-all/435/testReport/junit/Suite-k8s-1/15/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/

**Comment by pchaigno** [comment] 2020-10-12 13:47
Duplicate of #13071.

**Closed as completed** 2020-10-12 13:48 UTC
Labels: area/CI
