### ISSUE TITLE
Gateway API and EKS (recent regression): upstream connection timeout

### ISSUE THREAD

**Issue by Smana** [cilium/cilium#32616] opened 2024-05-19 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey,

Recently **Gateway API stopped working on EKS** with this error:

```sh
curl https://grafana-mycluster-0.priv.cloud.ogenki.io 
upstream connect error or disconnect/reset before headers. reset reason: connection timeout
```

At firstt I thought this was caused by recent changes in my [demo repo](https://github.com/Smana/demo-cloud-native-ref), so I tried  a [branch](https://github.com/Smana/demo-cloud-native-ref/tree/demo_gapi) that I already used for demo purposes (with Gateway API working perfectly). Unfortunately, even without any changes in the code there's a regression. That's probably on AWS side but I didn't find the culprit so far:
Note that the traffic **reaches the envoy service** and there are no TLS issues, but envoy returns a **503**.

```sh
curl https://capacitor-mycluster-0.priv.cloud.ogenki.io/ -vvv
* Host capacitor-mycluster-0.priv.cloud.ogenki.io:443 was resolved.
...
* Server certificate:
*  subject: C=France; O=Ogenki; CN=private-gateway.priv.cloud.ogenki.io
*  start date: May 18 11:20:19 2024 GMT
*  expire date: Aug 16 11:20:49 2024 GMT
*  subjectAltName: host "capacitor-mycluster-0.priv.cloud.ogenki.io" matched cert's "capacitor-mycluster-0.priv.cloud.ogenki.io"
*  issuer: O=Ogenki; CN=Private PKI - Vault Issuer
*  SSL certificate verify ok.
...
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Sat, 18 May 2024 16:07:04 GMT
< server: envoy
< 
* Connection #0 to host capacitor-mycluster-0.priv.cloud.ogenki.io left intact
upstream connect error or disconnect/reset before headers. reset reason: connection timeout
```

Everything seems ok from the Gateway API resources perspective

**httproute**

```sh
kubectl get httproute  -n flux-system -o yaml capacitor| yq .status
parents:
  - conditions:
      - lastTransitionTime: "2024-05-18T11:07:08Z"
        message: Accepted HTTPRoute
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-05-18T11:05:42Z"
        message: Service reference is valid
        observedGeneration: 1
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: platform-private
      namespace: infrastructure
```

**gateway**

```sh
kubectl get gateway -n infrastructure platform-private -o yaml | yq .status
addresses:
  - type: Hostname
    value: ae49855e1f64942b49d15fdf501b7cc3-45206332.eu-west-3.elb.amazonaws.com
conditions:
  - lastTransitionTime: "2024-05-18T11:07:08Z"
    message: Gateway successfully scheduled
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2024-05-18T11:07:12Z"
    message: Gateway successfully reconciled
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
listeners:
  - attachedRoutes: 3
    conditions:
      - lastTransitionTime: "2024-05-18T11:20:49Z"
        message: Listener Programmed
        observedGeneration: 1
        reason: Programmed
        status: "True"
        type: Programmed
      - lastTransitionTime: "2024-05-18T11:20:49Z"
        message: Listener Accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-05-18T11:20:49Z"
        message: Resolved Refs
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
    name: http
    supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
```

Of course, I checked obvious things such as the service being reachable using port-forward.

Regards,
Smana

### Cilium Version

Tested with
v1.15.5
v1.15.3
v1.15.0

### Kernel Version

The one provided in the AMI `bottlerocket-aws-k8s-1.29-x86_64-v1.20.0-fcf71a47`

### Kubernetes Version

v1.29.4

### Regression

That seems to be a regression but not related directly to Cilium changes.
Indeed using a branch that has already been used for GAPI purposes does not work anymore. (Same behavior)

### Sysdump

[cilium-sysdump-20240519-112239.zip](https://github.com/cilium/cilium/files/15368848/cilium-sysdump-20240519-112239.zip)

### Anything else?

I've search for similar issues but they are pretty old:
https://github.com/cilium/cilium/issues/23906
https://github.com/cilium/cilium/issues/20942

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by audacioustux** [comment] 2024-05-20 04:55
Facing probably the same issue, but with Ingress resource. Getting approximately 6-10% of 503 errors randomly.
![Screenshot 2024-05-20 at 10 11 26 AM](https://github.com/cilium/cilium/assets/7238675/9cbc9bb1-afc3-40ea-b9aa-cf8e8d11163a)

helm values:
```js
    values: {
      kubeProxyReplacement: 'strict',
      k8sServiceHost: cluster.endpoint.apply((endpoint) => endpoint.replace('https://', '')),
      ingressController: {
        enabled: true,
        loadbalancerMode: 'shared',
        default: true,
      },
      hubble: {
        relay: {
          enabled: true,
        },
        ui: {
          enabled: true,
        },
      },
      loadBalancer: {
        algorithm: 'maglev',
        l7: {
          backend: 'envoy',
        },
      },
      envoy: {
        enabled: true,
      },
      routingMode: 'native',
      bpf: {
        masquerade: true,
      },
      ipam: {
        mode: 'eni',
      },
      eni: {
        enabled: true,
        awsEnablePrefixDelegation: true,
      },
    }
 ```

**Comment by bhm-kyndryl** [comment] 2024-05-20 09:39
Hi there,

Having the same problem with AWS EKS 1.27. Created an issue for this few days ago:

"Gateway API backend PODs intermittent timeouts in hostNetwork mode"
[https://github.com/cilium/cilium/issues/32592](https://github.com/cilium/cilium/issues/32592)

On my side, if the backend webserver POD and the envoy receiving the HTTP request from ALB are on the same workernode, it is 100% success. Otherwise, 100% failure.


Bye

**Comment by sayboras** [comment] 2024-05-21 14:02
@Smana Thanks for your issue, we didn't have any test coverage right now for bottlerocket,  just curious if you are facing the same issue with Amazon Linux.

@audacioustux @bhm-kyndryl It's hard to tell if the issue is the same, however, we have a couple of fixes merged recently in main, appreciate if you can test it out with main branch.

Again, thanks a lot for your  issue and comment.

**Comment by audacioustux** [comment] 2024-05-21 15:34
I've moved to AL2023 image from Bottlerocket, and it somehow got fixed completely. I'll try out the latest changes with Bottlerocket soon hopefully.

**Comment by Smana** [comment] 2024-05-21 16:14
Same here: that indeed fixed my issues by switching to AL2023.

**Comment by Smana** [comment] 2024-05-22 12:26
I still have networking issues with AL2023, but that's probably another issue (maybe related to [this](https://github.com/cilium/cilium/issues/24397)) . I'm gonna try again with AL2

**Comment by sayboras** [comment] 2024-05-22 14:45
I don't think we have any issue to track the work for supporting bottlerocket though.

**Comment by aleksanderaleksic** [comment] 2024-05-23 00:48
We were upgrading cilium from `v1.14.6` (working) to `v1.14.11` where it stopped working for us.
Hope that helps with scoping down the changes.

Switched from bottlerocket  to AL2023 and it worked for us, not ideal but will do it for now.

**Comment by sayboras** [comment] 2024-05-23 06:32
It seems like the underlying issue is due to bottlerocket, but not related to Ingress/Gateway API implementation. 

I am closing this issue as we are already having a couple of bottlerocket related issue (e.g. https://github.com/cilium/cilium/issues/32610). Feel free to re-open if you think otherwise. Thanks all.

**Closed as completed by sayboras** 2024-05-23 06:32 UTC
Labels: kind/question, kind/community-report, area/agent, feature/k8s-gateway-api

**Comment by Smana** [comment] 2024-05-23 06:57
Yes thank you @sayboras . I'm working on figure out how AL2023 isn't working properly too. But indeed, this is not related and I'll open an issue if necessary.
