### ISSUE TITLE
ENI: aws/eni unit test fails sporadically due to race condition

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#9604] opened 2019-11-13 13:47 UTC
**How to reproduce the issue**

1. `cd cilium/pkg/aws/eni`
2. `while true;do go test ./... -count=1 >> /tmp/eni-test.result;sleep 1;done`

Most of the time the tests would succeed, but after running it for a while, test failure occurs.

**Comment by jaffcheng** [comment] 2019-11-13 13:59
In order to make it closer to the root cause, I tested on commit `c831888f5e6426ca44086e762912c572340e45ec`, which excludes some recent relevant changes.
These are some of the test FAILs I have seen:
```
1. 

FAIL: node_manager_test.go:331: ENISuite.TestNodeManagerManyNodes

node_manager_test.go:378:
    c.Assert(metricsapi.Nodes("in-deficit"), check.Equals, 0)
... obtained int = 1
... expected int = 0

----------------------------------------------------------------------------------------

2. 

fatal error: concurrent map iteration and map write

goroutine 41 [running]:
runtime.throw(0x184174d, 0x26)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00001d598 sp=0xc00001d568 pc=0x431372
runtime.mapiternext(0xc00001d688)
        /usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc00001d620 sp=0xc00001d598 pc=0x4110c9
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*IPAMSpec).DeepCopyInto(0xc0002fd860, 0xc0003013e0)
        /root/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:574 +0x116 fp=0xc00001d6f8 sp=0xc00001d620 pc=0x147a356
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*NodeSpec).DeepCopyInto(0xc0002fd798, 0xc000301318)
        /root/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:669 +0xd6 fp=0xc00001d750 sp=0xc00001d6f8 pc=0x147ac76
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopyInto(0xc0002fd680, 0xc000301200)
        /root/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:343 +0xbc fp=0xc00001d778 sp=0xc00001d750 pc=0x147892c
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopy(...)
        /root/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:354
github.com/cilium/cilium/pkg/aws/eni.(*Node).ResourceCopy(0xc0000c28f0, 0x0)
        /root/cilium/pkg/aws/eni/node.go:244 +0xc1 fp=0xc00001d7e8 sp=0xc00001d778 pc=0x14c5161
github.com/cilium/cilium/pkg/aws/eni.(*Node).SyncToAPIServer(0xc0000c28f0, 0x23e52af1, 0x72a28346acc20)
        /root/cilium/pkg/aws/eni/node.go:617 +0xba fp=0xc00001dea0 sp=0xc00001d7e8 pc=0x14c8fba
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Update.func2(0xc000246210, 0x1, 0x1)
        /root/cilium/pkg/aws/eni/node_manager.go:165 +0x2a fp=0xc00001dec8 sp=0xc00001dea0 pc=0x14d8afa
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc000143220)
        /root/cilium/pkg/trigger/trigger.go:210 +0x2e1 fp=0xc00001dfd8 sp=0xc00001dec8 pc=0x14861c1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00001dfe0 sp=0xc00001dfd8 pc=0x460631
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
        /root/cilium/pkg/trigger/trigger.go:133 +0x129

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0002b0500, 0x1815a00, 0x4, 0x18c3388, 0x48b3b6)
        /usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0002b0400)
        /usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0002b0400, 0xc000587dc0)
        /usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc000343e40, 0x263a8d0, 0x1, 0x1, 0x0)
        /usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc000240500, 0x0)
        /usr/local/go/src/testing/testing.go:1117 +0x176


----------------------------------------------------------------------------------------

3. 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x14c4625]

goroutine 637 [running]:
github.com/cilium/cilium/pkg/aws/eni.(*Node).recalculateLocked(0xc0003f1810)
        /root/cilium/pkg/aws/eni/node.go:188 +0x95
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).resyncNode(0xc000444380, 0x1a6bae0, 0xc0000bc018, 0xc0003f1810, 0xc00036c0c0, 0xbf6b13db69c5c4df, 0x132a40ac0, 0x2660740)
        /root/cilium/pkg/aws/eni/node_manager.go:248 +0xaf
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Resync.func1(0xc000444380, 0x1a6bae0, 0xc0000bc018, 0xbf6b13db69c5c4df, 0x132a40ac0, 0x2660740, 0xc000f720a0, 0xc0003f1810, 0xc00036c0c0)
        /root/cilium/pkg/aws/eni/node_manager.go:292 +0x7b
created by github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Resync
        /root/cilium/pkg/aws/eni/node_manager.go:291 +0x174
FAIL    github.com/cilium/cilium/pkg/aws/eni    5.156s


```

**Comment by aanm** [comment] 2019-11-26 12:23
```
goroutine 39 [running]:
runtime.throw(0x18add5b, 0x26)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0xc00001f5c8 sp=0xc00001f598 pc=0x431a02
runtime.mapiternext(0xc00001f6d8)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/map.go:858 +0x579 fp=0xc00001f650 sp=0xc00001f5c8 pc=0x411759
runtime.mapiterinit(0x167ac00, 0xc000461350, 0xc00001f6d8)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/map.go:848 +0x1c3 fp=0xc00001f670 sp=0xc00001f650 pc=0x4110f3
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*IPAMSpec).DeepCopyInto(0xc00045d1a0, 0xc00049daa0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:637 +0x11c fp=0xc00001f748 sp=0xc00001f670 pc=0x14c571c
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*NodeSpec).DeepCopyInto(0xc00045d0d8, 0xc00049d9d8)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:732 +0xde fp=0xc00001f7a0 sp=0xc00001f748 pc=0x14c614e
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopyInto(0xc00045cfc0, 0xc00049d8c0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:406 +0xc2 fp=0xc00001f7c8 sp=0xc00001f7a0 pc=0x14c3cc2
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopy(0xc00045cfc0, 0xc0000e33b0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:417 +0x5b fp=0xc00001f7f0 sp=0xc00001f7c8 pc=0x14c3d9b
github.com/cilium/cilium/pkg/aws/eni.(*Node).ResourceCopy(0xc000538780, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:281 +0x83 fp=0xc00001f850 sp=0xc00001f7f0 pc=0x1513d23
github.com/cilium/cilium/pkg/aws/eni.(*Node).SyncToAPIServer(0xc000538780, 0x1c0c0686, 0x76a6a682ea)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:737 +0xc0 fp=0xc00001fea0 sp=0xc00001f850 pc=0x1519450
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Update.func2(0xc0004e7190, 0x1, 0x1)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:167 +0x30 fp=0xc00001fec8 sp=0xc00001fea0 pc=0x152a9b0
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc000141860)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:210 +0x319 fp=0xc00001ffd8 sp=0xc00001fec8 pc=0x14d3e09
runtime.goexit()
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00001ffe0 sp=0xc00001ffd8 pc=0x460cc1
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000f4400, 0x18817cb, 0x4, 0x1939a98, 0x48ba46)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0000f4300)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0000f4300, 0xc000535d88)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0xc9
testing.runTests(0xc000385680, 0x271a4e0, 0x1, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0003ef080, 0x0)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:950 +0x1d4
goroutine 20 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2740a60)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:411 +0xd6
goroutine 21 [chan receive]:
gopkg.in/check%2ev1.(*suiteRunner).runTest(...)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:819
gopkg.in/check%2ev1.(*suiteRunner).run(0xc0003ef200, 0x275e588)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:624 +0x11d
gopkg.in/check%2ev1.Run(0x18223c0, 0x275e588, 0xc00056a708, 0xd0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x4d
gopkg.in/check%2ev1.RunAll(0xc00007ff08, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x96
gopkg.in/check%2ev1.TestingT(0xc0000f4400)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x395
github.com/cilium/cilium/pkg/aws/eni.Test(0xc0000f4400)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/eni_test.go:26 +0x2b
testing.tRunner(0xc0000f4400, 0x1939a98)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:960 +0x350
goroutine 22 [select]:
gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc0000f2bd0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:470 +0xc4
created by gopkg.in/check%2ev1.(*resultTracker).start
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:450 +0x3f
goroutine 37 [select]:
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc000141360)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:218 +0x157
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
goroutine 30 [sleep]:
runtime.goparkunlock(...)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/proc.go:310
time.Sleep(0x944fd3)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/time.go:105 +0x157
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0001405a0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:197 +0x3f0
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
goroutine 36 [semacquire]:
sync.runtime_SemacquireMutex(0xc000538788, 0xf2700, 0x0)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).Lock(0xc000538780)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/sync/rwmutex.go:103 +0x88
github.com/cilium/cilium/pkg/aws/eni.(*Node).updatedResource(0xc000538780, 0xc00045cfc0, 0x188245a)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:196 +0x37
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Update(0xc000422200, 0xc00045cfc0, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:184 +0xd2
github.com/cilium/cilium/pkg/aws/eni.(*ENISuite).TestNodeManagerDefaultAllocation(0x275e588, 0xc000180780)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager_test.go:188 +0x6ee
reflect.Value.call(0x18223c0, 0x275e588, 0x3a13, 0x1881633, 0x4, 0xc00007ef30, 0x1, 0x1, 0x2760480, 0xc00056ddd0, ...)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x18223c0, 0x275e588, 0x3a13, 0xc00056df30, 0x1, 0x1, 0x0, 0xc0003cb2f0, 0xc00056de58)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/reflect/value.go:321 +0xb4
gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc000180780)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0x5e4
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc0003ef200, 0xc000180780, 0xc0004726e0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xa2
created by gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:672 +0x1fb
goroutine 33 [select]:
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc000140e60)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:218 +0x157
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
goroutine 34 [select]:
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0001410e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:218 +0x157
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
goroutine 38 [select]:
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0001415e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:218 +0x157
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
FAIL	github.com/cilium/cilium/pkg/aws/eni	0.080s
```

**Comment by jaffcheng** [comment] 2019-11-27 04:36
Do we have a plan for `go test -race` in the future? I think it would be a good idea to detect and eliminate as many issues as possible early.

**Comment by aanm** [comment] 2020-01-23 09:15
@jrajahalme it seems @gandro saw this again in #9940 which AFAIK it contained the fixed made in https://github.com/cilium/cilium/pull/9893

**Comment by jrajahalme** [comment] 2021-07-15 09:21
This is still happening, at least for Arm64 builds:
```
level=info msg="Resolving IP deficit of node" available=0 availableForAllocation=0 availableInterfaces=3 instanceID=i-testNodeManagerManyNodes-99 maxIPsToAllocate=10 name=node99 neededIPs=10 remainingInterfaces=3 selectedInterface= selectedPoolID= subsys=ipam used=0
level=info msg="No more IPs available, creating new ENI" addresses=10 instanceID=i-testNodeManagerManyNodes-99 name=node99 securityGroupIDs="[sg1 sg2]" subnetID=s-3 subsys=ipam
level=info msg="Created new ENI" addresses=10 eniID=f7680b4b-e4b2-11eb-83f2-023933df020d instanceID=i-testNodeManagerManyNodes-99 name=node99 securityGroupIDs="[sg1 sg2]" subnetID=s-3 subsys=ipam
level=info msg="Attached ENI to instance" addresses=10 attachmentID= eniID=f7680b4b-e4b2-11eb-83f2-023933df020d index=1 instanceID=i-testNodeManagerManyNodes-99 name=node99 securityGroupIDs="[sg1 sg2]" subnetID=s-3 subsys=ipam
level=info msg="Synchronized ENI information" numInstances=100 numSecurityGroups=2 numSubnets=4 numVPCs=1 subsys=eni
----------------------------------------------------------------------
FAIL: node_manager_test.go:574: ENISuite.TestNodeManagerManyNodes
node_manager_test.go:613:
    c.Errorf("Node %s allocation shortage. expected at least: %d, allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)
... Error: Node node99 allocation shortage. expected at least: 10, allocated: 0
node_manager_test.go:625:
    c.Assert(metricsapi.Nodes("in-deficit"), check.Equals, 0)
... obtained int = 1
... expected int = 0
```
Since this is happening on an unprivileged unit test this looks like a race condition in either the package or the test code.

**Comment by errordeveloper** [comment] 2021-09-10 11:38
This is duplicate of #11560.

**Closed as completed by errordeveloper** 2021-09-10 11:38 UTC
Labels: need-more-info, area/eni
