### ISSUE TITLE
http-route with empty service port brakes cilium-controller pods

### ISSUE THREAD

**Issue by janip81** [cilium/cilium#28716] opened 2023-10-21 20:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Creating a http-route and forgetting to type in port for the service

`---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-ui
  namespace: grafana
spec:
  parentRefs:
  - name: internal-shared
    namespace: cilium
    group: gateway.networking.k8s.io	
    kind: Gateway	
  hostnames:
  - grafana.domain.com
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: grafana
      port: 
      weight: 1
    matches:
      - path:
          type: PathPrefix
          value: /`
          
 2. Cilium operator pods start crashing with error:
 
 `level=info msg="Reconciling Gateway" controller=gateway resource=cilium/internal-shared subsys=gateway-controller
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 522 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc0017c7200, {0xc00072d600, 0x2, 0x2})
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:168 +0x54
github.com/go-logr/logr.Logger.WithValues(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-logr/logr/logr.go:323
sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doController.func1(0xc00072d5e0)
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go:398 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a3720, {0x30932a0, 0xc000660b40}, {0x293d120?, 0xc00072d5c0?})
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:305 +0x18b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a3720, {0x30932a0, 0xc000660b40})
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0x587`

### Cilium Version

v1.14.1

### Kernel Version

Linux prod-k8s-md-0-p92wd-br5sh 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28

### Sysdump

[cilium-sysdump-20231021-220818.zip](https://github.com/cilium/cilium/files/13061749/cilium-sysdump-20231021-220818.zip)

### Relevant log output

```shell
level=info msg="Reconciling Gateway" controller=gateway resource=cilium/internal-shared subsys=gateway-controller
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 522 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc0017c7200, {0xc00072d600, 0x2, 0x2})
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:168 +0x54
github.com/go-logr/logr.Logger.WithValues(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-logr/logr/logr.go:323
sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doController.func1(0xc00072d5e0)
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go:398 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a3720, {0x30932a0, 0xc000660b40}, {0x293d120?, 0xc00072d5c0?})
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:305 +0x18b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a3720, {0x30932a0, 0xc000660b40})
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0x587
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment] 2023-10-23 02:03
please assign to me.

**Comment by dylandreimerink** [comment] 2023-10-23 09:05
The log you are citing looks like a red herring, its complaining about a logger missing but not the cause of the crash it seems.  The logger error has since been fixed by #27961 but has not been backpacked (yet). The sysdump show this:

```
023-10-20T05:59:36.535726976Z level=info msg="Reconciling Gateway" controller=gateway resource=cilium/internal-shared subsys=gateway-controller
2023-10-20T05:59:36.541950542Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2023-10-20T05:59:36.543958559Z 	panic: runtime error: invalid memory address or nil pointer dereference
2023-10-20T05:59:36.544036908Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x243edfa]
2023-10-20T05:59:36.544100325Z 
2023-10-20T05:59:36.544123815Z goroutine 531 [running]:
2023-10-20T05:59:36.544145702Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
2023-10-20T05:59:36.544167440Z 	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:115 +0x1fa
2023-10-20T05:59:36.544188938Z panic({0x27dea00, 0x48ec370})
2023-10-20T05:59:36.544210372Z 	/usr/local/go/src/runtime/panic.go:884 +0x213
2023-10-20T05:59:36.544231015Z github.com/cilium/cilium/operator/pkg/model.(*BackendPort).GetPort(...)
2023-10-20T05:59:36.544252366Z 	/go/src/github.com/cilium/cilium/operator/pkg/model/model.go:336
2023-10-20T05:59:36.544273101Z github.com/cilium/cilium/operator/pkg/model/translation.getNamespaceNamePortsMap(0xc000bfc7c8)
2023-10-20T05:59:36.555866980Z 	/go/src/github.com/cilium/cilium/operator/pkg/model/translation/translator.go:302 +0x4fa
2023-10-20T05:59:36.555931550Z github.com/cilium/cilium/operator/pkg/model/translation.(*defaultTranslator).getBackendServices(0x3093348?, 0xc000b12ab0?)
2023-10-20T05:59:36.555956204Z 	/go/src/github.com/cilium/cilium/operator/pkg/model/translation/translator.go:96 +0x31
2023-10-20T05:59:36.555978181Z github.com/cilium/cilium/operator/pkg/model/translation.(*defaultTranslator).Translate(0xc001245f78, 0xc0012467c8)
2023-10-20T05:59:36.555999242Z 	/go/src/github.com/cilium/cilium/operator/pkg/model/translation/translator.go:70 +0xad
2023-10-20T05:59:36.556020316Z github.com/cilium/cilium/operator/pkg/model/translation/gateway-api.(*translator).Translate(0xc000bfc6c0, 0xc000bfc7c8)
2023-10-20T05:59:36.556087838Z 	/go/src/github.com/cilium/cilium/operator/pkg/model/translation/gateway-api/translator.go:59 +0x5a7
2023-10-20T05:59:36.556119597Z github.com/cilium/cilium/operator/pkg/gateway-api.(*gatewayReconciler).Reconcile(0xc000322460, {0x3093348, 0xc000b12ab0}, {{{0xc00089f036, 0x6}, {0xc00089f040, 0xf}}})
2023-10-20T05:59:36.556141160Z 	/go/src/github.com/cilium/cilium/operator/pkg/gateway-api/gateway_reconcile.go:122 +0x1630
2023-10-20T05:59:36.556163008Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3093348?, {0x3093348?, 0xc000b12ab0?}, {{{0xc00089f036?, 0x268dfc0?}, {0xc00089f040?, 0x30790b8?}}})
2023-10-20T05:59:36.556183932Z 	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0xc8
2023-10-20T05:59:36.556205493Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00083e960, {0x30932a0, 0xc0003221e0}, {0x293d120?, 0xc0008b1580?})
2023-10-20T05:59:36.556226560Z 	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314 +0x377
2023-10-20T05:59:36.556290619Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00083e960, {0x30932a0, 0xc0003221e0})
2023-10-20T05:59:36.556327777Z 	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265 +0x1d9
2023-10-20T05:59:36.556351141Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
2023-10-20T05:59:36.556372136Z 	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226 +0x85
2023-10-20T05:59:36.556392853Z created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
2023-10-20T05:59:36.556413567Z 	/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0x587
```

**Comment by ardikabs** [comment] 2023-11-03 03:11
hi @dylandreimerink , I've submitted the [PR](https://github.com/cilium/cilium/pull/28957) for the fix, kindly take a look if you have a chance. Thanks!

**Comment by ardikabs** [comment] 2023-11-03 03:12
oops my bad, didn't realize about your comment @chaunceyjiang. Have you worked on this?

**Comment by ardikabs** [comment] 2023-11-06 14:48
hi @janip81 , turns out that this issue will be solved on the upcoming version of the Cilium (might be on v1.15), that's because the gateway-api project, since v0.8.1 has been enabling CEL for validation so that the default behavior of `backendRef` which is `Service` will enforce the presence of a port.

**Comment by janip81** [comment] 2023-11-06 14:54
> hi @janip81 , turns out that this issue will be solved on the upcoming version of the Cilium (might be on v1.15), that's because the gateway-api project, since v0.8.1 has been enabling CEL for validation so that the default behavior of `backendRef` which is `Service` will enforce the presence of a port.

This is ok for me, for myself this is not so much of an issue anymore. Just have implemented checks before i merge PRs that port is configured.

**Comment by sayboras** [comment] 2023-11-12 12:55
I am closing this issue, feel free to let us know if you think otherwise.

**Closed as completed by sayboras** 2023-11-12 12:55 UTC
Labels: kind/bug, kind/community-report, area/agent, feature/k8s-gateway-api
