### ISSUE TITLE
CI: Suite-k8s-1.21.K8sChaosTest Connectivity demo application Endpoint can still connect while Cilium is not running: exit status 28

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15630] opened 2021-04-09 22:01 UTC
## Suite-k8s-1.21.K8sChaosTest Connectivity demo application Endpoint can still connect while Cilium is not running

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/155/testReport/junit/Suite-k8s-1/21/K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running/
[8fe9a754_K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running.zip](https://github.com/cilium/cilium/files/6288692/8fe9a754_K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running.zip)

In particular, the following occurred during test setup:

```
10:04:20 STEP: Cilium is not ready yet: cilium services are not set up correctly: Error validating Cilium service on pod {cilium-dlvvd [{0xc0009e37d0 0xc0002fc1c8} {0xc0009e3830 0xc0002fc1d0} {0xc0009e3890 0xc0002fc1d8} {0xc0009e38f0 0xc0002fc1e0} {0xc0009e3950 0xc0002fc1e8}] map[10.104.6.219:3000:[0.0.0.0:0 (1) [ClusterIP] 10.0.0.7:3000 (1)] 10.106.50.254:9090:[10.0.0.248:9090 (2) 0.0.0.0:0 (2) [ClusterIP]] 10.96.0.10:53:[0.0.0.0:0 (4) [ClusterIP] 10.0.0.127:53 (4)] 10.96.0.10:9153:[10.0.0.127:9153 (5) 0.0.0.0:0 (5) [ClusterIP]] 10.96.0.1:443:[192.168.36.11:6443 (3) 0.0.0.0:0 (3) [ClusterIP]]]}: Could not match cilium service backend address 10.0.0.7:3000 with k8s endpoint
```

Also saw these error messages:
Failed to remove route
Unable to update ipcache map entry on pod add
discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
Waiting for k8s node information
Command execution failed

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Cannot curl from "testclient-4bkzw" to testds-service via ClusterIP
Expected command: kubectl exec -n default testclient-4bkzw -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.102.141.22:80/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000026()', Connect: '0.000000',Transfer '0.000000', total '5.000667'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/Chaos.go:129
```
### Standard Output
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 2
⚠️  Number of "level=warning" in logs: 40
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Failed to remove route
Unable to update ipcache map entry on pod add
discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
Waiting for k8s node information
Command execution failed
Cilium pods: [cilium-dlvvd cilium-q8prx]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
grafana-5747bcc8f9-5z9w5                
prometheus-655fb888d7-8lmcc             
test-k8s2-7f96d84c65-cz458              
testclient-4bkzw                        
testclient-5g24h                        
testds-5cz46                            
testds-pfcnb                            
coredns-755cd654d4-p2q7f                
Cilium agent 'cilium-dlvvd': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 30 Failed 0
Cilium agent 'cilium-q8prx': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 38 Failed 0

```
### Standard Error
```
10:03:25 STEP: Running BeforeAll block for EntireTestsuite K8sChaosTest
10:03:25 STEP: Ensuring the namespace kube-system exists
10:03:25 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
10:03:26 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
10:03:26 STEP: Installing Cilium
10:03:26 STEP: Waiting for Cilium to become ready
10:03:47 STEP: Restarting unmanaged pods coredns-755cd654d4-bp5tm in namespace kube-system
10:03:47 STEP: Validating if Kubernetes DNS is deployed
10:03:47 STEP: Checking if deployment is ready
10:03:47 STEP: Kubernetes DNS is not ready: only 0 of 1 replicas are available
10:03:47 STEP: Restarting Kubernetes DNS (-l k8s-app=kube-dns)
10:04:03 STEP: Waiting for Kubernetes DNS to become operational
10:04:03 STEP: Checking if deployment is ready
10:04:03 STEP: Checking if kube-dns service is plumbed correctly
10:04:03 STEP: Checking if DNS can resolve
10:04:03 STEP: Checking if pods have identity
10:04:04 STEP: Validating Cilium Installation
10:04:04 STEP: Performing Cilium controllers preflight check
10:04:04 STEP: Performing Cilium status preflight check
10:04:04 STEP: Performing Cilium health check
10:04:12 STEP: Performing Cilium service preflight check
10:04:13 STEP: Cilium is not ready yet: cilium services are not set up correctly: Error validating Cilium service on pod {cilium-dlvvd [{0xc00024e390 0xc000610120} {0xc00024e420 0xc000610128} {0xc00024e4b0 0xc000610130} {0xc00024e5d0 0xc000610138} {0xc00024e630 0xc000610140}] map[10.104.6.219:3000:[0.0.0.0:0 (1) [ClusterIP]] 10.106.50.254:9090:[10.0.0.248:9090 (2) 0.0.0.0:0 (2) [ClusterIP]] 10.96.0.10:53:[0.0.0.0:0 (4) [ClusterIP] 10.0.0.127:53 (4)] 10.96.0.10:9153:[10.0.0.127:9153 (5) 0.0.0.0:0 (5) [ClusterIP]] 10.96.0.1:443:[192.168.36.11:6443 (3) 0.0.0.0:0 (3) [ClusterIP]]]}: Could not match cilium service backend address 10.0.0.248:9090 with k8s endpoint
10:04:13 STEP: Performing Cilium status preflight check
10:04:13 STEP: Performing Cilium controllers preflight check
10:04:13 STEP: Performing Cilium health check
10:04:18 STEP: Performing Cilium service preflight check
10:04:20 STEP: Cilium is not ready yet: cilium services are not set up correctly: Error validating Cilium service on pod {cilium-dlvvd [{0xc0009e37d0 0xc0002fc1c8} {0xc0009e3830 0xc0002fc1d0} {0xc0009e3890 0xc0002fc1d8} {0xc0009e38f0 0xc0002fc1e0} {0xc0009e3950 0xc0002fc1e8}] map[10.104.6.219:3000:[0.0.0.0:0 (1) [ClusterIP] 10.0.0.7:3000 (1)] 10.106.50.254:9090:[10.0.0.248:9090 (2) 0.0.0.0:0 (2) [ClusterIP]] 10.96.0.10:53:[0.0.0.0:0 (4) [ClusterIP] 10.0.0.127:53 (4)] 10.96.0.10:9153:[10.0.0.127:9153 (5) 0.0.0.0:0 (5) [ClusterIP]] 10.96.0.1:443:[192.168.36.11:6443 (3) 0.0.0.0:0 (3) [ClusterIP]]]}: Could not match cilium service backend address 10.0.0.7:3000 with k8s endpoint
10:04:20 STEP: Performing Cilium controllers preflight check
10:04:20 STEP: Performing Cilium status preflight check
10:04:20 STEP: Performing Cilium health check
10:04:21 STEP: Performing Cilium service preflight check
10:04:21 STEP: Performing K8s service preflight check
10:04:22 STEP: Waiting for cilium-operator to be ready
10:04:22 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
10:04:22 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
10:04:22 STEP: Running BeforeEach block for EntireTestsuite K8sChaosTest Connectivity demo application
10:04:23 STEP: WaitforPods(namespace="default", filter="-l zgroup=testDS")
10:04:43 STEP: WaitforPods(namespace="default", filter="-l zgroup=testDS") => <nil>
10:04:43 STEP: Waiting for deployed pods to be ready
10:04:43 STEP: WaitforPods(namespace="default", filter="-l zgroup=testDSClient")
10:04:43 STEP: WaitforPods(namespace="default", filter="-l zgroup=testDSClient") => <nil>
10:04:44 STEP: Checking connectivity before restarting Cilium
10:04:45 STEP: Waiting for kube-dns entry for service testds-service
10:04:45 STEP: Getting ClusterIP For testds-service
10:04:45 STEP: Pinging testds pod with IP "10.0.0.220" from client pod "testclient-4bkzw"
10:04:49 STEP: Pinging testds pod with IP "10.0.1.124" from client pod "testclient-4bkzw"
10:04:54 STEP: Curling testds-service via ClusterIP "10.102.141.22"
FAIL: Cannot curl from "testclient-4bkzw" to testds-service via ClusterIP
Expected command: kubectl exec -n default testclient-4bkzw -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.102.141.22:80/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000026()', Connect: '0.000000',Transfer '0.000000', total '5.000667'
Stderr:
 	 command terminated with exit code 28
	 

=== Test Finished at 2021-04-09T10:04:59Z====
10:04:59 STEP: Running JustAfterEach block for EntireTestsuite K8sChaosTest
===================== TEST FAILED =====================
10:04:59 STEP: Running AfterFailed block for EntireTestsuite K8sChaosTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-5z9w5           1/1     Running   0          2m45s   10.0.0.7        k8s1   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-8lmcc        1/1     Running   0          2m45s   10.0.0.248      k8s1   <none>           <none>
	 default             test-k8s2-7f96d84c65-cz458         2/2     Running   0          40s     10.0.1.50       k8s2   <none>           <none>
	 default             testclient-4bkzw                   1/1     Running   0          40s     10.0.1.181      k8s2   <none>           <none>
	 default             testclient-5g24h                   1/1     Running   0          40s     10.0.0.67       k8s1   <none>           <none>
	 default             testds-5cz46                       2/2     Running   0          40s     10.0.0.220      k8s1   <none>           <none>
	 default             testds-pfcnb                       2/2     Running   0          40s     10.0.1.124      k8s2   <none>           <none>
	 kube-system         cilium-dlvvd                       1/1     Running   0          97s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-8445c6f9fd-79rdp   1/1     Running   1          97s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-8445c6f9fd-sg5cm   1/1     Running   0          97s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-q8prx                       1/1     Running   0          97s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         coredns-755cd654d4-p2q7f           1/1     Running   0          76s     10.0.0.127      k8s1   <none>           <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          6m52s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          6m52s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   2          6m52s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-9wgf7                   1/1     Running   0          3m55s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-proxy-l47wk                   1/1     Running   0          5m3s    192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   2          6m52s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-2n52q                 1/1     Running   0          2m56s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-ksj8q                 1/1     Running   0          2m56s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-4w8b9               1/1     Running   0          3m51s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-nt6rp               1/1     Running   0          3m51s   192.168.36.11   k8s1   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-dlvvd cilium-q8prx]
cmd: kubectl exec -n kube-system cilium-dlvvd -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend               Service Type   Backend                   
	 1    10.104.6.219:3000      ClusterIP      1 => 10.0.0.7:3000        
	 2    10.106.50.254:9090     ClusterIP      1 => 10.0.0.248:9090      
	 3    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443   
	 4    10.96.0.10:53          ClusterIP      1 => 10.0.0.127:53        
	 5    10.96.0.10:9153        ClusterIP      1 => 10.0.0.127:9153      
	 6    10.102.141.22:80       ClusterIP                                
	 7    10.102.141.22:69       ClusterIP                                
	 8    10.101.104.59:10069    ClusterIP                                
	 9    10.101.104.59:10080    ClusterIP                                
	 10   10.110.10.146:10080    ClusterIP                                
	 11   10.110.10.146:10069    ClusterIP                                
	 12   10.105.114.43:10080    ClusterIP                                
	 13   10.105.114.43:10069    ClusterIP                                
	 14   10.106.152.238:10080   ClusterIP                                
	 15   10.106.152.238:10069   ClusterIP                                
	 16   10.96.205.50:10080     ClusterIP                                
	 17   10.96.205.50:10069     ClusterIP                                
	 18   10.110.226.56:80       ClusterIP                                
	 19   10.99.127.9:80         ClusterIP                                
	 20   10.96.154.34:20080     ClusterIP                                
	 21   10.96.154.34:20069     ClusterIP                                
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-dlvvd -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                              IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                    
	 130        Disabled           Disabled          4          reserved:health                                                          fd02::1ab   10.0.1.244   ready   
	 575        Disabled           Disabled          47524      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default   fd02::1e8   10.0.1.50    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=test-k8s2                                                                                      
	 768        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                                        ready   
	                                                            reserved:host                                                                                             
	 1163       Disabled           Disabled          35172      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default   fd02::1d1   10.0.1.124   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testDS                                                                                         
	 3465       Disabled           Disabled          37768      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default   fd02::131   10.0.1.181   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testDSClient                                                                                   
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-q8prx -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend               Service Type   Backend                   
	 1    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53          ClusterIP      1 => 10.0.0.127:53        
	 3    10.96.0.10:9153        ClusterIP      1 => 10.0.0.127:9153      
	 4    10.104.6.219:3000      ClusterIP      1 => 10.0.0.7:3000        
	 5    10.106.50.254:9090     ClusterIP      1 => 10.0.0.248:9090      
	 6    10.102.141.22:80       ClusterIP                                
	 7    10.102.141.22:69       ClusterIP                                
	 8    10.101.104.59:10080    ClusterIP                                
	 9    10.101.104.59:10069    ClusterIP                                
	 10   10.110.10.146:10080    ClusterIP                                
	 11   10.110.10.146:10069    ClusterIP                                
	 12   10.105.114.43:10080    ClusterIP                                
	 13   10.105.114.43:10069    ClusterIP                                
	 14   10.106.152.238:10080   ClusterIP                                
	 15   10.106.152.238:10069   ClusterIP                                
	 16   10.96.205.50:10080     ClusterIP                                
	 17   10.96.205.50:10069     ClusterIP                                
	 18   10.110.226.56:80       ClusterIP                                
	 19   10.99.127.9:80         ClusterIP                                
	 20   10.96.154.34:20080     ClusterIP                                
	 21   10.96.154.34:20069     ClusterIP                                
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-q8prx -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                        IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                             
	 5          Disabled           Disabled          38985      k8s:app=grafana                                                                    fd02::13   10.0.0.7     ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                  
	 237        Disabled           Disabled          38706      k8s:app=prometheus                                                                 fd02::39   10.0.0.248   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                             
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                  
	 410        Disabled           Disabled          35172      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default             fd02::c7   10.0.0.220   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                            
	                                                            k8s:zgroup=testDS                                                                                                  
	 471        Disabled           Disabled          37768      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default             fd02::9f   10.0.0.67    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                            
	                                                            k8s:zgroup=testDSClient                                                                                            
	 477        Disabled           Disabled          7315       k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system         fd02::3a   10.0.0.127   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                        
	                                                            k8s:k8s-app=kube-dns                                                                                               
	 1740       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                                                 ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                                          
	                                                            k8s:node-role.kubernetes.io/master                                                                                 
	                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers                                                        
	                                                            reserved:host                                                                                                      
	 3085       Disabled           Disabled          4          reserved:health                                                                    fd02::e3   10.0.0.246   ready   
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

===================== Exiting AfterFailed =====================
10:05:17 STEP: Running AfterEach for block EntireTestsuite K8sChaosTest Connectivity demo application
10:05:18 STEP: Running AfterEach for block EntireTestsuite
```

**Comment by joestringer** [comment] 2021-04-09 22:04
There's a bunch of errors in the logs here that we should address before shipping v1.10, marking blocker to investigate.

**Comment by nathanjsweet** [comment] 2021-04-14 15:08
[This is the part of the test](https://github.com/cilium/cilium/blob/master/test/k8sT/Chaos.go#L129) that is failing ([specifically this line](https://github.com/cilium/cilium/blob/master/test/k8sT/Chaos.go#L107) of the connectivity test).   I don't know if this is exactly the problem, but there are logs in the test dump that indicated that there were ipcache upsert issues ([tied to this line](https://github.com/cilium/cilium/blob/master/pkg/ipcache/ipcache.go#L271), based on careful reading of the logs) for the test-ds pod IP that the test failed on. Investigating whether or not this is actually the cause.

**Comment by pchaigno** [comment] 2021-04-15 08:09
@nathanjsweet With [this CI dashboard report](https://datastudio.google.com/s/tdqhod3QK4g), I checked occurrences over the past week. I couldn't find any other occurrence (same test fails but for different reasons). So I think we can remove `release-blocker/1.10` assuming we already have opened issues for each of the weird log messages spotted by Joe:
- [ ] Failed to remove route
- [ ] Unable to update ipcache map entry on pod add
- [ ] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
- [ ] Waiting for k8s node information
- [ ] Command execution failed

**Comment by nathanjsweet** [comment] 2021-04-20 21:03
So regarding all the errors that were commented on:
1. ["Failed to remove route"](https://github.com/cilium/cilium/search?q=%22Failed+to+remove+route%22&type=issues) seems like it could be the culprit, but is affecting other tests as well. We should continue to investigate
2. "Unable to update ipcache map entry on pod add" does not appear to be a relevant error/warning and is mostly a coincidence, and actually can reasonably happen.
3. The endpoint slice deprecation was covered [by a PR](https://github.com/cilium/cilium/pull/15631)
4. ["Waiting for k8s node information"](https://github.com/cilium/cilium/search?q=%22Waiting+for+k8s+node+information%22&type=issues) comes up for other CI issues, though I am doubtful it is related to the error here, as both nodes were active and other tests worked.
5.  ["Command execution failed"](https://github.com/cilium/cilium/search?q=%22Command+execution+failed%22&type=issues), again, appears on many other issues, but, again, I am doubtful this is the issue causing this curl failure.

**Comment by pchaigno** [comment] 2021-04-20 21:09
> "Failed to remove route" seems like it could be the culprit, but is affecting other tests as well. We should continue to investigate

I expect https://github.com/cilium/cilium/pull/15730 fixed that one. We shouldn't see it anymore now.

**Comment by nathanjsweet** [comment] 2021-05-03 14:25
If I'm reading the CI dashboard correctly it doesn't look like this issue has crept up in a week. It is very possible that there aren't any original errors to this issue. I'm going to leave it open a bit longer in case it comes up again.

**Comment by pchaigno** [comment] 2023-04-18 10:51
This was fixed by https://github.com/cilium/cilium/pull/15730.

**Closed as completed by pchaigno** 2023-04-18 10:51 UTC
Labels: area/CI, ci/flake
