### ISSUE TITLE
Linter throws a spelling error on "virtualized"

### ISSUE THREAD

**Issue by zacharysarah** [cilium/cilium#23655] opened 2023-02-09 22:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In #23599, the linter throws an error for "virtualized". This spelling is correct and shouldn't trigger an error.

### Cilium Version

n/a

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

n/a

### Relevant log output

```shell
Running linter...
Validating documentation (syntax, spelling)...

Please fix the following spelling mistakes:
* Documentation/security/restrict-pod-access.rst:13: (priveleged)  This page shows you how to restrict priveleged access to Cilium pods by limiting access from the Kubernetes API, specifically from 
* Documentation/security/restrict-pod-access.rst:24: (virtualized)   filesystem, which includes host and machine configurations that can't be virtualized or namespaced.

If the words are not misspelled, run:
Documentation/update-spelling_wordlist.sh priveleged virtualized
```

### Anything else?

https://github.com/cilium/cilium/actions/runs/4138700930/jobs/7155423594#step:5:10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qmonnet** [comment] 2023-02-10 10:17
As I understand it, this is not a bug currently affecting the documentation, but new exceptions for the spell checker, to declare as such at the same time as we add the actual contents containing these terms.

I'm closing this issue for now.

**Closed as completed by qmonnet** 2023-02-10 10:17 UTC
Labels: kind/bug, area/CI, needs/triage, kind/community-report
