### ISSUE TITLE
CI: Encapsulation Check iptables masquerading with random-fully

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#17867] opened 2021-11-12 16:35 UTC
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
Pods are not ready in time: timed out waiting for pods with filter  to be ready: 4m0s timeout expired
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:647
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/6910/testReport/junit/Suite-k8s-1/20/K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random_fully/

[d6cbbd7f_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip](https://github.com/cilium/cilium/files/7529034/d6cbbd7f_K8sDatapathConfig_Encapsulation_Check_iptables_masquerading_with_random-fully.zip)

I see that all the test pods are in the `ready` state though.

```
 NAMESPACE                                                         NAME                                                   READY   STATUS    RESTARTS   AGE     IP            NODE                                        NOMINATED NODE   READINESS GATES
	 202111121050k8sdatapathconfigencapsulationcheckiptablesmasquera   test-k8s2-79ff876c9d-phrpx                             2/2     Running   0          4m14s   10.84.1.63    gke-cilium-ci-4-cilium-ci-4-c4057c3c-m75q   <none>           <none>
	 202111121050k8sdatapathconfigencapsulationcheckiptablesmasquera   testclient-45ghw                                       1/1     Running   0          4m15s   10.84.2.31    gke-cilium-ci-4-cilium-ci-4-c4057c3c-7fsm   <none>           <none>
	 202111121050k8sdatapathconfigencapsulationcheckiptablesmasquera   testclient-q5r4s                                       1/1     Running   0          4m15s   10.84.1.180   gke-cilium-ci-4-cilium-ci-4-c4057c3c-m75q   <none>           <none>
	 202111121050k8sdatapathconfigencapsulationcheckiptablesmasquera   testds-7cwf4                                           1/2     Running   0          4m15s   10.84.1.1     gke-cilium-ci-4-cilium-ci-4-c4057c3c-m75q   <none>           <none>
	 202111121050k8sdatapathconfigencapsulationcheckiptablesmasquera   testds-hctmc                                           2/2     Running 
```

**Comment by pchaigno** [comment] 2021-11-12 16:41
This is a duplicate of https://github.com/cilium/cilium/issues/17307.

**Closed as completed by pchaigno** 2021-11-12 16:41 UTC
Labels: area/CI, ci/flake
