### ISSUE TITLE
IPAM Deadlock ?

### ISSUE THREAD

**Issue by Richard-Joe** [cilium/cilium#32247] opened 2024-04-30 07:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The phenomenon is that cilium-cni times out when accessing cilium-agent, which looks like a deadlock in the IPAM allocation module.

### Cilium Version

v1.13.2

### Kernel Version

4.18.0

### Kubernetes Version

v1.25.0

### Relevant log output

```shell
goroutine 1498478 [semacquire, 26 minutes]:
sync.runtime_SemacquireMutex(0xc001deb3f8?, 0xbf?, 0x1000000000000?)
    /usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000531080)
    /usr/local/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
    /usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xc000918400?)
    /usr/local/go/src/sync/rwmutex.go:147 +0x36
github.com/cilium/cilium/pkg/ipam.(*IPAM).AllocateNextFamily(0xc000531030, {0x32ce227, 0x4}, {0xc001519560, 0x2c})
    /go/src/github.com/cilium/cilium/pkg/ipam/allocator.go:180 +0x73
github.com/cilium/cilium/pkg/ipam.(*IPAM).AllocateNext(0xc000531030, {0x0?, 0xc0016e4410?}, {0xc001519560?, 0xc001deb5c8?})
    /go/src/github.com/cilium/cilium/pkg/ipam/allocator.go:213 +0xf8
github.com/cilium/cilium/pkg/ipam.(*IPAM).AllocateNextWithExpiration(0x0?, {0x0?, 0x20?}, {0xc001519560?, 0x0?}, 0x8bb2c97000)
    /go/src/github.com/cilium/cilium/pkg/ipam/allocator.go:229 +0x3a
github.com/cilium/cilium/daemon/cmd.(*postIPAM).Handle(0xc0017bcab0, {0xc0043b3e00?, 0xc00243bffa?, 0x0?, 0xc0032b7260?})
    /go/src/github.com/cilium/cilium/daemon/cmd/ipam.go:48 +0xca
github.com/cilium/cilium/api/v1/server/restapi/ipam.(*PostIpam).ServeHTTP(0xc001a6b590, {0x38763b0, 0xc00143ac48}, 0xc0043b3e00)
    /go/src/github.com/cilium/cilium/api/v1/server/restapi/ipam/post_ipam.go:56 +0x16d
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x38763b0, 0xc00143ac48}, 0xc0043b3e00)
    /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x59
net/http.HandlerFunc.ServeHTTP(0x203001?, {0x38763b0?, 0xc00143ac48?}, 0xc004321b80?)
    /usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x38763b0, 0xc00143ac48}, 0xc0043b3c00)
    /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:78 +0x257
net/http.HandlerFunc.ServeHTTP(0x40d9bf?, {0x38763b0?, 0xc00143ac48?}, 0x3?)
    /usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/go-openapi/runtime/middleware.Redoc.func1({0x38763b0, 0xc00143ac48}, 0xc0043b3c00?)
    /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x242
net/http.HandlerFunc.ServeHTTP(0xc0006689b0?, {0x38763b0?, 0xc00143ac48?}, 0x40?)
    /usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/go-openapi/runtime/middleware.Spec.func1({0x38763b0, 0xc00143ac48}, 0xc000668901?)
    /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x18c
net/http.HandlerFunc.ServeHTTP(0xc003388900?, {0x38763b0?, 0xc00143ac48?}, 0x7efd34d67328?)
    /usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc001458b10, {0x38872a0?, 0xc0043888c0}, 0xc0043b3c00)
    /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:64 +0x1d4
github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0xc001ab3a4e?, {0x38872a0?, 0xc0043888c0?}, 0x46c8ee?)
    /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 +0x76
net/http.serverHandler.ServeHTTP({0xc002c61830?}, {0x38872a0, 0xc0043888c0}, 0xc0043b3c00)
    /usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc003e9c460, {0x3888f00, 0xc001459dd0})
    /usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:3102 +0x4db
```

### Anything else?

cilium-cni.log

level=warning msg="Errors encountered while deleting endpoint" error="Cilium API client timeout exceeded" subsys=cilium-cni

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment] 2024-05-03 04:44
Thanks for this issue @Richard-Joe. As this is an old version of Cilium, this will be difficult for anyone to troubleshoot. I recommend following the process at https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection to upload a sysdump, and then we can assign this to a team for prioritization.

**Comment by joestringer** [comment] 2024-07-18 19:45
Thanks again for the report. Due to lack of response, I'll close this out. If you are able to reproduce this on the latest Cilium version and share a sysdump or full gops output (including all stacks, not just the one stack that is stuck), then please respond with that information and we can reopen the issue.

**Closed as not planned by joestringer** 2024-07-18 19:45 UTC
Labels: kind/bug, need-more-info, kind/community-report, area/agent, area/ipam
