### ISSUE TITLE
/var/lib/cilium/bpf/init.sh failing and making pods not scheduling

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#9322] opened 2019-10-02 13:34 UTC
## Bug report

**General Information**

- Cilium version (run `cilium version`) 1.5.3
- Kernel version (run `uname -a`) 4.12.14-197.18.1
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) Kubernetes 1.15.2

It might be specific to SUSE CaaSP...

**How to reproduce the issue**

1. Deploy Kubernetes cluster by https://github.com/SUSE/skuba
2. There is a chance that some pod trying to contact Cilium through UNIX socket will fail.

Failures were observed during cilium-operator pod creation:

```
Warning  FailedCreatePodSandBox  62s                 kubelet, kiubit-4-dev-worker-1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_cilium-operator-7d6ddddbf5-4bq6b_kube-system_e99f61c8-ffd4-43e5-952f-d4528da1b7ba_0(b2e63c859ca9bf7c3e93f740ecad8e1a1cc4382e910980b52593666163543783): unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)cilium%!F(MISSING)cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

On the same environment, there was the following error of cilium-agent:

```
level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.244.0.1 fc00::10ca:1 vxlan    1450 false false ]" error="exit status 2" subsys=daemon
```

But on the other environment, it was observed during kured pod creation, with the same error:

```
  Warning  FailedCreatePodSandBox  19m                 kubelet, master03  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_kured-9zwk6_kube-system_7646f3d8-3b7c-4106-a3d6-e3ba0cd965f4_0(a21b39295d3c5fc8a16d244d2bc548d75b2356092984cf97c2b2756005e3167c): Unable to create endpoint: Put http:///var/run/cilium/cilium.sock/v1/endpoint/cilium-local:0: context deadline exceeded
```

**Comment by brb** [comment] 2019-10-02 13:50
Are there any cilium-agent logs? `bpf/init.sh` has `set -x`, so there should be exact cmd, which failed, in the logs.

Also, v1.5.3 is quite ancient (v1.5.8 is the latest release from v1.5).

**Comment by mrostecki** [comment] 2019-11-18 14:17
I can't reproduce anymore on newer versions, closing.

**Closed as completed by mrostecki** 2019-11-18 14:17 UTC
Labels: kind/bug
