### ISSUE TITLE
Nil pointer dereference in eni.NodeManager unit test

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#9940] opened 2020-01-22 18:13 UTC
Observed during `make unit-tests` in Travis CI in an unrelated PR (on commit https://github.com/cilium/cilium/commit/62175a7066a22856ecd4fc9f8cb9482606173b8c).
Unfortunately I don't have more details than the stack trace:

```
 panic: runtime error: invalid memory address or nil pointer dereference
 
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x18b286b]
 
 goroutine 613 [running]:
 
 github.com/cilium/cilium/pkg/aws/eni.(*Node).recalculateLocked(0xc0005498c0)
 
     /home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:237 +0x9b
 
 github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).resyncNode(0xc00041d480, 0x2158de0, 0xc0000441e0, 0xc0005498c0, 0xc00032c380, 0xbf823c4aafcf51af, 0x13485f2a6, 0x3202d40)
 
     /home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:261 +0xbe
 
 github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Resync.func1(0xc00041d480, 0x2158de0, 0xc0000441e0, 0xbf823c4aafcf51af, 0x13485f2a6, 0x3202d40, 0xc00187c410, 0xc0005498c0, 0xc00032c380)
 
     /home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:309 +0x81
 
 created by github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Resync
 
     /home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:308 +0x1b2
 
 FAIL    github.com/cilium/cilium/pkg/aws/eni    5.187s
 
 FAIL
 
 make: *** [unit-tests] Error 1
 
 The command "./.travis/build.sh" exited with 2.
```

**Comment by aanm** [comment] 2020-01-23 09:14
Duplicate of https://github.com/cilium/cilium/issues/9604

**Closed as completed by aanm** 2020-01-23 09:14 UTC
Labels: kind/bug/CI, area/eni
