### ISSUE TITLE
Certain logs not parsing correctly in Google Logs Explorer

### ISSUE THREAD

**Issue by AlHood77** [cilium/cilium#27006] opened 2023-07-22 17:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I run cilium in a GKE managed cluster (deployed via helm) and I noticed that all my cilium-agent and cilium-operator info logs were being parsed as errors in GCP.  I then changed the logOptions format to json and re-started the cilium pods. This worked for the most part but it seems certain logs are still being parsed as errors. The screen shot shows a sample of what appears to be info level logs being parsed as errors. For some reason they all seem to be coming from 1 pod but sometimes that pod parses messages correctly and other times it doesn't. I'm not sure what else to try. An hours worth of logs contains about 500 incorrectly parsed error messages.

<img width="965" alt="Screenshot 2023-07-22 at 17 49 04" src="https://github.com/cilium/cilium/assets/45075866/75d16b48-e9e8-453d-8fd8-fe3c33e7796f">

### Cilium Version

cilium-cli: v0.15.0 compiled with go1.20.4 on darwin/arm64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): 1.13.0

### Kernel Version

Linux  5.10.147+ #1 SMP Thu Nov 10 10:14:30 UTC 2022 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux

### Kubernetes Version

v1.24.12-gke.500

### Sysdump

[cilium-sysdump-20230722-180113.zip](https://github.com/cilium/cilium/files/12136876/cilium-sysdump-20230722-180113.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment] 2023-07-24 04:09
Thanks for this @AlHood77, from your screenshot it looks like this is caused by #26942. Do you think that makes sense?

**Comment by AlHood77** [comment] 2023-07-24 05:50
@youngnick Yes it is. Apologies, I didn't notice this current issue in my search for an existing issue.

**Comment by youngnick** [comment] 2023-07-24 06:22
Thanks again for the report though @AlHood77, better to have a duplicate than to not have a report of something.

I'll close this one, but you should subscribe to #26942 and see if we can get any movement there.

**Closed as not planned by youngnick** 2023-07-24 06:22 UTC
Labels: kind/bug, need-more-info, needs/triage, kind/community-report
