### ISSUE TITLE
Failed to expose service when use Cilium and Kubernetes Gateway API

### ISSUE THREAD

**Issue by hongbo-miao** [cilium/cilium#34111] opened 2024-07-31 17:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

I am using Cilium and Kubernetes Gateway API in Amazon EKS.

I am trying to expose one of my service (Goldilocks in this case at hm-goldilocks-dashboard.production-hm-goldilocks.svc:80) at hm-goldilocks.internal.mydomain.com

Here is my setup: 

```yaml
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-lets-encrypt-cluster-issuer
  namespace: production-hm-cert-manager
spec:
  acme:
    email: me@mydomain.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-lets-encrypt-cluster-issuer-account-secret
    solvers:
      - selector:
          dnsZones:
            - internal.mydomain.com
        dns01:
          route53:
            region: us-west-2
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-hm-cilium-gateway-certificate
  namespace: production-hm-gateway-api
spec:
  commonName: "*.internal.mydomain.com"
  secretName: staging-hm-cilium-gateway-certificate
  dnsNames:
    - "*.internal.mydomain.com"
  issuerRef:
    kind: ClusterIssuer
    name: staging-lets-encrypt-cluster-issuer
  # https://letsencrypt.org/certificates
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hm-cilium-gateway
  namespace: production-hm-gateway-api
  labels:
    app.kubernetes.io/name: hm-cilium-gateway
    app.kubernetes.io/part-of: production-hm-gateway-api
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations
      # https://cloud-provider-aws.sigs.k8s.io/service_controller
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xx,subnet-xx,subnet-xx,subnet-xx
  listeners:
    - name: http
      protocol: HTTP
      hostname: "*.internal.mydomain.com"
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      hostname: "*.internal.mydomain.com"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: staging-hm-cilium-gateway-certificate
            namespace: production-hm-gateway-api
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hm-goldilocks-http-httproute
  namespace: production-hm-goldilocks
spec:
  parentRefs:
    - name: hm-cilium-gateway
      namespace: production-hm-gateway-api
      sectionName: http
  hostnames:
    - hm-goldilocks.internal.mydomain.com
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hm-goldilocks-https-httproute
  namespace: production-hm-goldilocks
spec:
  parentRefs:
    - name: hm-cilium-gateway
      namespace: production-hm-gateway-api
      sectionName: https
  hostnames:
    - hm-goldilocks.internal.mydomain.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: hm-goldilocks-dashboard
          namespace: production-hm-goldilocks
          kind: Service
          port: 80
```

I can see that External DNS successfully registered with Route 53.

![image](https://github.com/user-attachments/assets/c9037522-cf20-4a8f-9262-97a1c235a0c3)

And Gateway's corresponding Load Balancer:

![image](https://github.com/user-attachments/assets/e6af64eb-3840-429e-9a22-dfda4ef739cb)

Here is my Gateway status:

```sh
➜ kubectl describe gateway hm-cilium-gateway -n production-hm-gateway-api
Name:         hm-cilium-gateway
Namespace:    production-hm-gateway-api
Labels:       app.kubernetes.io/name=hm-cilium-gateway
              app.kubernetes.io/part-of=production-hm-gateway-api
              argocd.argoproj.io/instance=hm-gateway-api
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2024-08-01T21:07:08Z
  Generation:          1
  Resource Version:    1237234
  UID:                 c17f7a60-38ff-462a-90c6-b725066068c5
Spec:
  Gateway Class Name:  cilium
  Infrastructure:
    Annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal:    true
      service.beta.kubernetes.io/aws-load-balancer-subnets:     subnet-xx,subnet-xx,subnet-xx,subnet-xx
      service.beta.kubernetes.io/aws-load-balancer-type:        nlb
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  *.internal.mydomain.com
    Name:      http
    Port:      80
    Protocol:  HTTP
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  *.internal.mydomain.com
    Name:      https
    Port:      443
    Protocol:  HTTPS
    Tls:
      Certificate Refs:
        Group:
        Kind:       Secret
        Name:       staging-hm-cilium-gateway-certificate
        Namespace:  production-hm-gateway-api
      Mode:         Terminate
Status:
  Addresses:
    Type:   Hostname
    Value:  aa3ff376273144bd089a876b9417e2fd-3fadba626fbed2b5.elb.us-west-2.amazonaws.com
  Conditions:
    Last Transition Time:  2024-08-01T21:07:08Z
    Message:               Gateway successfully scheduled
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2024-08-01T21:07:12Z
    Message:               Gateway successfully reconciled
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    http
    Supported Kinds:
      Group:          gateway.networking.k8s.io
      Kind:           HTTPRoute
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    https
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
Events:       <none>
```

My http HTTPRoute status:

```sh
➜ kubectl describe httproute hm-goldilocks-http-httproute -n production-hm-goldilocks
Name:         hm-goldilocks-http-httproute
Namespace:    production-hm-goldilocks
Labels:       app.kubernetes.io/name=hm-goldilocks-http-httproute
              app.kubernetes.io/part-of=production-hm-goldilocks
              argocd.argoproj.io/instance=hm-goldilocks
Annotations:  argocd.argoproj.io/hook: PostSync
API Version:  gateway.networking.k8s.io/v1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2024-08-01T21:41:06Z
  Generation:          1
  Resource Version:    1237228
  UID:                 33184787-1469-473f-85f7-4e2d5df491d4
Spec:
  Hostnames:
    hm-goldilocks.internal.mydomain.com
  Parent Refs:
    Group:         gateway.networking.k8s.io
    Kind:          Gateway
    Name:          hm-cilium-gateway
    Namespace:     production-hm-gateway-api
    Section Name:  http
  Rules:
    Filters:
      Request Redirect:
        Port:         443
        Scheme:       https
        Status Code:  302
      Type:           RequestRedirect
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Service reference is valid
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:         gateway.networking.k8s.io
      Kind:          Gateway
      Name:          hm-cilium-gateway
      Namespace:     production-hm-gateway-api
      Section Name:  http
Events:              <none>
```

My https HTTPRoute status:

```sh
➜ kubectl describe httproute hm-goldilocks-https-httproute -n production-hm-goldilocks
Name:         hm-goldilocks-https-httproute
Namespace:    production-hm-goldilocks
Labels:       app.kubernetes.io/name=hm-goldilocks-https-httproute
              app.kubernetes.io/part-of=production-hm-goldilocks
              argocd.argoproj.io/instance=hm-goldilocks
Annotations:  argocd.argoproj.io/hook: PostSync
API Version:  gateway.networking.k8s.io/v1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2024-08-01T21:41:06Z
  Generation:          1
  Resource Version:    1237227
  UID:                 af2c2c67-4ff4-4c5d-963f-0c2c6222b04f
Spec:
  Hostnames:
    hm-goldilocks.internal.mydomain.com
  Parent Refs:
    Group:         gateway.networking.k8s.io
    Kind:          Gateway
    Name:          hm-cilium-gateway
    Namespace:     production-hm-gateway-api
    Section Name:  https
  Rules:
    Backend Refs:
      Group:
      Kind:       Service
      Name:       hm-goldilocks-dashboard
      Namespace:  production-hm-goldilocks
      Port:       80
      Weight:     1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-08-01T21:41:06Z
      Message:               Service reference is valid
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:         gateway.networking.k8s.io
      Kind:          Gateway
      Name:          hm-cilium-gateway
      Namespace:     production-hm-gateway-api
      Section Name:  https
Events:              <none>
```

I can see `http` redirects to `https`, however, the `https` failed to point the Service in the Kubernetes:

![image](https://github.com/user-attachments/assets/34f93a5e-ecad-44a5-a06e-1a58a2b8e9c1)

Any guide would be appreciate, thanks!

### How can we reproduce the issue?

Here is my Cilium Helm values.yaml
```yaml
eni:
  enabled: true
ipam:
  mode: eni
egressMasqueradeInterfaces: eth0
routingMode: native
kubeProxyReplacement: true
k8sServiceHost: xx.gr7.us-west-2.eks.amazonaws.com
k8sServicePort: 443
rollOutCiliumPods: true
operator:
  enabled: true
  rollOutPods: true
l7Proxy: true
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
```

### Cilium Version

```
➜ cilium version --helm-release-name=hm-cilium --namespace=production-hm-cilium
cilium-cli: v0.16.13 compiled with go1.22.5 on darwin/arm64
cilium image (default): v1.15.6
cilium image (stable): v1.16.0
cilium image (running): 1.15.7
```

### Kernel Version

(Hmm, I am not sure where I should run this `uname -a`, in cilium-operator pod in EKS cluster?)

### Kubernetes Version

```sh
➜ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hongbo-miao** [comment] 2024-08-02 17:03
I tested a brand new Kubernetes 1.30 cluster with Cilium 1.16.0 with 1.1.0 experimental CRDs

- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml

But still get same result.

I saw [Cilium CRD schema validation](https://docs.cilium.io/en/latest/network/kubernetes/compatibility/#cilium-crd-schema-validation), which shows 1.16.0 supports Kubernetes 1.29.9.
I am wondering does Cilium 1.16.0 support Kubernetes 1.30?

**Comment by hongbo-miao** [comment] 2024-08-05 18:28
Joe Stringer answered me on Slack 

> The schema validation isn't k8s versions, that's Cilium resource versions. The top of the page points out that k8s 1.30 is tested in CI and should work: https://docs.cilium.io/en/latest/network/kubernetes/compatibility/#kubernetes-compatibility
> Probably an issue with the gateway API integration, but I'm not sure what.

So Cilium 1.6 does support Kubernetes 1.30 today.

So still something else is wrong currently.

**Comment by julian-perge** [comment] 2024-08-08 13:33
+1 to this issue as well. `GatewayClass` shows `Unknown` for the `Accepted` field. New or long-living existing AWS EKS cluster produces the same result, the `GatewayClass` is never accepted.

**Comment by sayboras** [comment] 2024-08-09 12:18
Thanks for your issue., 

Just curious if you are having issue with GatewayClass status (same as Jullian) as well :thinking:. Appreciate if you can attach sysump as well.

**Comment by hongbo-miao** [comment] 2024-08-10 01:23
Hi @sayboras in my case, Cilium GatewayClass `Accepted` is `True`, which is why `Gateway` and  `HTTPRoute` also in `Accepted` states.
Hmm what do you mean `sysump`? Thanks!

**Comment by julian-perge** [comment] 2024-08-12 12:47
> Thanks for your issue.,
> 
> Just curious if you are having issue with GatewayClass status (same as Jullian) as well 🤔. Appreciate if you can attach sysump as well.

Coming back to this, if I restart my single EC2 instance I'm testing with on my AWS EKS cluster, the LoadBalancer reports as healthy for about 15-30 minutes, and then shows as unhealthy. I looked at the [firewall rules section](https://docs.cilium.io/en/stable/operations/system_requirements/#firewall-rules), and I'm a little lost on where/if to add the ports in my security group as I use the [terraform-aws-eks module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) to provision my EKS cluster, which creates 3 security groups: the control plane cluster group, the cluster group itself, and one for the cluster nodes.

For example:
- `eks-cluster-sg-mycustomname-123` -> control-plane cluster security group
  - Allows all ingress traffic on itself, allows all egress on `0.0.0.0/0`
- `mycustomname-cluster` -> the cluster security group
  - Allows ingress port 443 to node security group, no egress.
-  `mycustomname-node` -> cluster node security group
  - Allows all egress, and a bunch of default ports for the ingress added by the module (plus the ones mentioned in the firewall rules section that I added, with the source being the `eks-cluster-sg-mycustomname-123` security group.

Here's a screenshot of a shortened list of rules for the node security group:

<img width="1317" alt="image" src="https://github.com/user-attachments/assets/52fd6310-43ce-4fce-a9c2-27d9e949dbe5">

**Comment by julian-perge** [comment] 2024-08-13 20:33
Okay, I found the problem.

The problem is that after deploying a Gateway that creates an external LoadBalancer service, if you restart the `cilium-envoy`, `cilium`, and `cilium-operator` pods (like the cilium docs suggest in certain sections), it fails to update the `Endpoint` resource in the cluster. If I then manually delete the `Endpoint` resource that targets the `Gateway`, the LB shortly-thereafter shows as healthy again.

Not sure if I'm missing a configuration somewhere to fix this, but I saw this in the logs:

```json
{"level":"info","msg":"Envoy: Starting access log server listening on /var/run/cilium/envoy/sockets/access_log.sock","subsys":"envoy-manager"}
{"level":"info","msg":"Envoy: Starting xDS gRPC server listening on /var/run/cilium/envoy/sockets/xds.sock","subsys":"envoy-manager"}
{"level":"info","msg":"Kernel config file not found: if the agent fails to start, check the system requirements at https://docs.cilium.io/en/stable/operations/system_requirements","subsys":"probes"}
{"level":"info","msg":"Restored node IDs from the BPF map","module":"agent.datapath","count":2}
{"level":"info","msg":"Auto-enabling \"enable-node-port\", \"enable-external-ips\", \"bpf-lb-sock\", \"enable-host-port\", \"enable-session-affinity\" features","subsys":"daemon"}
{"level":"info","msg":"Datapath signal listener running","subsys":"signal"}
{"count":2,"file-path":"/var/run/cilium/state/local_allocator_state.json","level":"info","msg":"Restoring checkpointed local identities","subsys":"identity-cache"}
{"level":"info","msg":"regenerating all endpoints","reason":"one or more identities created or deleted","subsys":"endpoint-manager"}
{"ingress":"<node_IP>/32","level":"info","msg":"Restored ingress IP","subsys":"daemon"}
{"level":"info","msg":"restored 2 out of 3 possible prefixes in the ipcache","subsys":"daemon"}
{"file-path":"/sys/fs/bpf/tc/globals/cilium_ipcache","level":"info","msg":"Removed map pin at /sys/fs/bpf/tc/globals/cilium_ipcache, recreating and re-pinning map cilium_ipcache","name":"cilium_ipcache","subsys":"bpf"}
{"failedServices":0,"level":"info","msg":"Restored services from maps","restoredServices":19,"subsys":"service"}
{"failedBackends":0,"level":"info","msg":"Restored backends from maps","restoredBackends":12,"skippedBackends":0,"subsys":"service"}
{"level":"info","msg":"Reading old endpoints...","subsys":"daemon"}
{"endpointID":"272","error":"open /var/run/cilium/state/272/ep_config.h: no such file or directory","file-path":"/var/run/cilium/state/272","level":"warning","msg":"Couldn't find state, ignoring endpoint","subsys":"endpoint"}

... bunch more `Couldn't find state, ignoring endpoint`
```

**Comment by julian-perge** [comment] 2024-08-20 01:03
Coming back to this, cilium 1.16.1 seems to have fixed the Gateway / Service endpoint reconciliation error, but I'd rather have someone else confirm as such.

**Comment by sayboras** [comment] 2024-08-20 08:30
> Coming back to this, cilium 1.16.1 seems to have fixed the Gateway / Service endpoint reconciliation error, but I'd rather have someone else confirm as such.

Thanks, it was my hunch at first, here is the related PR https://github.com/cilium/cilium/pull/34131

@hongbo-miao appreciate if you can test it out with 1.16.1 as well. Sysdump is the utility to capture details for troubleshooting.

https://docs.cilium.io/en/stable/operations/troubleshooting/#sysdump

**Comment by hongbo-miao** [comment] 2024-08-23 01:08
Thank you @sayboras ! I will try again and report back soon!

**Comment by sayboras** [comment] 2024-08-28 08:56
thanks, feel free to share your testing result here.

**Comment by hongbo-miao** [comment] 2024-08-28 12:05
Hi @sayboras I haven't forgot this. I will test it on Sep 14 or 15, and post result here. Thanks!

**Comment by sayboras** [comment] 2024-10-03 01:49
Seems like there is no other user facing the same issue, let's close it out. 

Feel free to re-open if it's not working with v1.16.2. Thanks for reporting.

**Closed as completed by sayboras** 2024-10-03 01:49 UTC
Labels: kind/bug, needs/triage, kind/community-report, area/agent, area/servicemesh, feature/k8s-gateway-api, info-completed

**Comment by hongbo-miao** [comment] 2024-10-03 02:25
Thanks @sayboras , still haven't got time on this, but will report back when I test in future, thanks!

**Comment by hongbo-miao** [comment] 2024-10-03 02:31
Thanks @sayboras , sorry, I still haven't got time on this, but will report back when I test in future, thanks!

**Comment by somnathbm** [comment] 2024-12-12 10:28
> +1 to this issue as well. `GatewayClass` shows `Unknown` for the `Accepted` field. New or long-living existing AWS EKS cluster produces the same result, the `GatewayClass` is never accepted.
> 
> EDIT: apparently setting `loadBalancer.l7.backend` to `envoy` showed the gateway as accepted :|

I wish that would have helped me. But it didn't.

The Gateway class is adamant to be on UNKNOWN state no matter what I do!

I'm on cilium 1.16.4.
K8s version 1.30
Tried downgrading to 1.15.8 and setting `loadBalancer.l7.backend=envoy`

I'm battling with this for almost 7 days. :( :(
