### ISSUE TITLE
Monitor Aggregation for connections does not work with host firewall

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12561] opened 2020-07-17 00:05 UTC
The host firewall does not respect the `monitor` parameter to the `ct_lookup[46]()` functions, it simply gathers it and discards, for example:

https://github.com/cilium/cilium/blob/f55ec9066e3a23461a0d14e20b3be8ab49a04c97/bpf/lib/host_firewall.h#L268
https://github.com/cilium/cilium/blob/f55ec9066e3a23461a0d14e20b3be8ab49a04c97/bpf/lib/host_firewall.h#L300-L301

This means that even with `monitorAggregationLevel=medium`, aggregation of monitor notifications based on connections does not occur correctly for packets from the host towards the networks, meaning that notifications are generated once per packet rather than once every 5s per connection.

The `monitor` argument should be handled similarly to how it is used in `bpf/bpf_lxc.c` in the `bpf_host.c`.

**Comment by ti-mo** [comment] 2020-10-05 15:00
Hi @joestringer 

After investigating this specific case (connecting to an `iperf` container from the host) thoroughly, I can't reproduce the behaviour you described by

> aggregation of monitor notifications based on connections does not occur correctly for packets from the host towards the networks

All `TRACE_FROM_*` obs points are simply dropped by `emit_trace_notify()` when aggregation is enabled, so this includes `TRACE_FROM_HOST`.https://github.com/cilium/cilium/blob/037bef5260918fba7fac19971593c80ff020485c/bpf/lib/trace.h#L129-L133

From what I can see, only 2 host-FW code paths could currently generate floods:
1. Packets that fail `validate_ethertype()` when the host firewall is _disabled_, although this gets ignored when aggregation is enabled. https://github.com/cilium/cilium/blob/b9e44f3feec5e7fc3b8a34d61b6b0d4226201281/bpf/bpf_host.c#L1035-L1036
1. Outbound packets towards other cluster nodes. https://github.com/cilium/cilium/blob/b9e44f3feec5e7fc3b8a34d61b6b0d4226201281/bpf/bpf_host.c#L1002-L1003

---

Is it possible that the case you described is caused by the latter? A simple `ping` flood can cause this (eg. from k8s1->k8s2 test VMs):

```
~ sudo ping 192.168.33.12 -i 0.01
...

~ cilium monitor
-> network flow 0x0 identity 1->0 state new ifindex 0 orig-ip 0.0.0.0: 192.168.33.11 -> 192.168.33.12 EchoRequest
-> network flow 0x0 identity 1->0 state new ifindex 0 orig-ip 0.0.0.0: 192.168.33.11 -> 192.168.33.12 EchoRequest
-> network flow 0x0 identity 1->0 state new ifindex 0 orig-ip 0.0.0.0: 192.168.33.11 -> 192.168.33.12 EchoRequest
```

Note how these events are wrongly labeled as 'to network'. There is no traffic to/from container networks here,
but rather between two cluster nodes directly. There doesn't seem to be any other kind of traffic that hits this
`send_trace_notify()` call. It looks like a fall-through and as such I would suggest we remove it to avoid future
regressions.

Instead, we could add new trace notifications with the correct observation points in the routines in `host_firewall.h`
where the `monitor` values are actually in scope. Otherwise, we'd need to declare+init it in `to_host()` for each packet
that hits the interface, including ones that don't use CT, which sounds like a bad idea. Additionally, we'd have to
plumb `monitor` into all ingress/egress routines, which I'd rather avoid.

@pchaigno @joestringer WDYT?

**Comment by pchaigno** [comment] 2020-10-05 17:11
> From what I can see, only 2 host-FW code paths could currently generate floods:

I think that's the two cases Joe had in mind (the second at least would be `aggregation of monitor notifications based on connections does not occur correctly for packets from the host towards the networks`). 

> Note how these events are wrongly labeled as 'to network'.

Why is that wrong? `network` here refers to anything outside the node.

**Comment by joestringer** [comment] 2020-10-05 21:09
> All TRACE_FROM_* obs points are simply dropped by emit_trace_notify() when aggregation is enabled, so this includes TRACE_FROM_HOST.

This is true, assuming a high enough aggregation level (which is also the default).

But yes, in general I am more concerned with the `TRACE_TO_*` cases for this issue.

> Instead, we could add new trace notifications with the correct observation points in the routines in host_firewall.h
where the monitor values are actually in scope.

I don't understand the "correct observation points" angle. As @pchaigno mentions, "network" here is considered the 'physical' network outside the host, not anything within the node. In general there are typically two observation points for any given flow which may originate from the network, the host, an endpoint, or a tunnel and may be destined to one of these. One observation point represents the source of the packet and one represents the destination.

>  Otherwise, we'd need to declare+init it in to_host() for each packet that hits the interface, including ones that don't use CT, which sounds like a bad idea. 

Are you worried about the cost of initializing a register to a default value? This should be cheap compared to the rest of the logic in the datapath, I don't think we're at the point of optimizing instructions like this yet. Furthermore, the goal here is to avoid preparing monitor messages and transmitting them to userspace, which will otherwise cause a bunch of other processing to occur both in the BPF packet handling and in the userspace side to handle the event for every single packet.

> Additionally, we'd have to plumb monitor into all ingress/egress routines, which I'd rather avoid.

I think it's tedious implementation-wise, but it will improve CPU usage as well as just the usability of `cilium monitor` if it isn't flooded by per-packet events but instead is more like "1 event per flow each 5s".

**Comment by ti-mo** [comment] 2020-10-06 07:35
> I don't understand the "correct observation points" angle.

I misinterpreted the `from the host towards the networks` (plural S) you mentioned in the issue description as `from the host towards container networks`, since there was no mention of host-to-host traffic triggering the monitor spam. I was also given a repro example on Slack that involved connecting to an iperf/netperf container from the host, which does not take this host-to-host code path either.

> One observation point represents the source of the packet and one represents the destination.

I think that's what I was trying to get at with my previous point. :sweat_smile: Being new to the codebase (unless you know what `TRACE_TO_NETWORK` means), it wasn't immediately obvious which conditions lead to that trace being generated. The explanation you gave makes sense, traces are added at each entry/exit point in the datapath.

> Are you worried about the cost of initializing a register to a default value?

No, of course not. :slightly_smiling_face: For example, looking at `bpf_lxc.c`, we don't declare `monitor` in `handle_xgress` or `handle_to_container` either, they are only declared in functions where CTs are looked up.

I understand it a bit better now, will do some more digging and think of a solution. These messages need to be aggregated for sure, since they even clutter up the monitor during development. :slightly_smiling_face: Did I understand correctly that there currently is no CT for these outbound packets/flows? We might have to track them in order to store their rate limit counters.

**Comment by joestringer** [comment] 2020-10-06 19:37
> Did I understand correctly that there currently is no CT for these outbound packets/flows? We might have to track them in order to store their rate limit counters.

Technically, it's possible to run CT in the service handling (eg from the `ENABLE_NODEPORT` section of `handle_ipv4()`), but the monitor aggregation logic doesn't hook in there. For the bpf_lxc progs we only add this monitor aggregation logic when running through the CT for firewalling purposes.

I think it's a reasonable first step to only enable this aggregation if the host firewall is enabled, and I think that's consistent with this issue title/description.

Adding CT to the host devices even in the case where host firewall is disabled seems a bit heavy-handed and the ramifications are less clear if we were to take that path, so I would suggest avoiding that for now.

**Comment by ti-mo** [comment] 2020-10-07 10:12
I forgot I made local changes to my tree, so turns out the `TRACE_TO_NETWORK` trace at the end of `to-netdev` also has its `monitor` argument set to 0. As long as aggregation is enabled. host-to-host traffic shouldn't cause any spam either. I'll leave that trace untouched for now.

> Adding CT to the host devices

Indeed, no need to do this.

> in general I am more concerned with the `TRACE_TO_*` cases

I've just checked all `TRACE_TO_*` traces in the codebase, and all of them are either `monitor`ed or disabled under aggregation. `TRACE_FROM_*` are also disabled under aggregation, so that's fine as well. :ok_hand: 

So, at the risk of sounding like a broken record, what's the goal here? :slightly_smiling_face: Adding traces for making use of those `monitor` variables? Or getting rid of them? I haven't been able to find any obvious defects, at least not with aggregation enabled.

**Comment by pchaigno** [comment] 2020-10-07 10:29
> I've just checked all `TRACE_TO_*` traces in the codebase, and all of them are either `monitor`ed or disabled under aggregation. `TRACE_FROM_*` are also disabled under aggregation, so that's fine as well. ok_hand

AFAICS, when the host firewall and monitor aggregation are enabled, `TRACE_TO` messages are simply discarded. That should not be the case; they should be rate-limited.

**Comment by ti-mo** [comment] 2020-10-07 13:44
@pchaigno did you mean `TRACE_FROM_` messages? Those are discarded under aggregation indeed: https://github.com/cilium/cilium/blob/ada53a91a98618d24dad2abda97dd9c60923003c/bpf/lib/trace.h#L130-L138

**Comment by joestringer** [comment] 2020-10-07 17:38
> I've just checked all `TRACE_TO_*` traces in the codebase, and all of them are either monitored or disabled under aggregation. `TRACE_FROM_*` are also disabled under aggregation, so that's fine as well. :ok_hand:

I think the "disabled under aggregation" is the key problem here:

https://github.com/cilium/cilium/blob/d068162c9c8525aa66f2ccbbaf3bc05abad274bc/bpf/bpf_host.c#L1002-L1003

Currently, we never generate the `TRACE_TO_NETWORK` events in this case. This limits our visibility into outbound connections from the host.

What I think we should do is if host firewall is disabled, keep this the same. However if host firewall is enabled, then the `monitor` pointer that we pass to the connection tracker should be declared at this level and then the value of `monitor` should be passed as the final parameter to this line. This will mean that if you enable host firewall, we can see monitor messages for traffic from the host, but they will be aggregated using the same logic that applies to endpoints.

**Comment by ti-mo** [comment] 2020-10-09 12:40
I believe I've addressed this in https://github.com/cilium/cilium/pull/13485. Please have a look, let's continue any discussion there.

**Comment by navarrothiago** [comment] 2021-05-05 14:26
I am planning take-up this issue
Please, could you assign it to me?

**Closed as completed** 2021-05-28 22:15 UTC
Labels: good-first-issue, area/datapath, area/monitor, area/host-firewall
