### ISSUE TITLE
Pod to ingress with backend hosted on the same node not working in certain configurations 

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#31653] opened 2024-03-28 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running an [extended version of the connectivity tests](https://github.com/cilium/cilium-cli/pull/2414) to validate pod to ingress service with both the backend pod hosted on the same or a different node highlighted connectivity issues when the backend is hosted on the same node in certain configurations. In particular, this issue occurred on the Conformance Cluster Mesh E2E tests, although not clustermesh related (as the backend is hosted in the local cluster as well), and more specifically in the following configurations:

```
          - name: '2'
            tunnel: 'disabled'
            ipfamily: 'dual'
            encryption: 'wireguard'
            kube-proxy: 'none' (KPR + BPF masquerade)

          - name: '4'
            tunnel: 'disabled'
            ipfamily: 'ipv6'
            encryption: 'disabled'
            kube-proxy: 'none' (KPR + BPF masquerade)
```

```
❌ 3/63 tests failed (5/654 actions), 12 tests skipped, 0 scenarios skipped:
connectivity test failed: 3 tests failed
Test [pod-to-ingress-service]:
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client-69748f45d8-vbwdx (10.242.1.231) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-2: cilium-test/client2-ccd7b8bdf-z8fmw (10.242.1.100) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
Test [pod-to-ingress-service-allow-ingress-identity]:
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-1: cilium-test/client-69748f45d8-vbwdx (10.242.1.231) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-2: cilium-test/client2-ccd7b8bdf-z8fmw (10.242.1.100) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
Test [outside-to-ingress-service]:
  ❌ outside-to-ingress-service/outside-to-ingress-service/curl-ingress-service-0: cilium-test/host-netns-non-cilium-nz9t8 (172.18.0.3) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)

❌ 3/57 tests failed (5/342 actions), 18 tests skipped, 8 scenarios skipped:
Test [pod-to-ingress-service]:
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-1: cilium-test/client-69748f45d8-r8rpj (fd00:10:242:2::20b0) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-2: cilium-test/client2-ccd7b8bdf-mjxhv (fd00:10:242:2::d899) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
Test [pod-to-ingress-service-allow-ingress-identity]:
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-0: cilium-test/client-69748f45d8-r8rpj (fd00:10:242:2::20b0) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-2: cilium-test/client2-ccd7b8bdf-mjxhv (fd00:10:242:2::d899) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
Test [outside-to-ingress-service]:
  ❌ outside-to-ingress-service/outside-to-ingress-service/curl-ingress-service-0: cilium-test/host-netns-non-cilium-x5zz8 (fc00:f853:ccd:e793::4) -> cilium-test/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test:80)
```

Differently, it didn't occur when ~~KPR was disabled~~ (the ingress controller is not enabled in that case), or Cilium was configured in tunnel mode. I'm not sure why it didn't happen in the Conformance E2E tests.

Link: https://github.com/cilium/cilium/actions/runs/8456333159

### Cilium Version

Tip of main

### Sysdump

[cilium-sysdump-20240327-180128.zip](https://github.com/cilium/cilium/files/14788229/cilium-sysdump-20240327-180128.zip)
[cilium-sysdump-20240327-180201.zip](https://github.com/cilium/cilium/files/14788230/cilium-sysdump-20240327-180201.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment] 2024-03-28 13:11
> Ingress controller is having one requirement of kpr enabled (or at least nodeport enabled). The above configurations didn't seem to satisfy such requirement 🤔

`kube-proxy: none` corresponds to KPR enabled. Sorry for not being clear there, that's the setting for kind which disables the kube-proxy daemonset, and then Cilium is configured with KPR enabled.

**Comment by sayboras** [comment] 2024-05-13 03:05
Copied the comment here so that it will not get lost. 

In short, with the re-introduce of _from proxy route_ 2005, there is still issue on the return traffic if bpf.masquerade is enabled, the workaround is to enable bpf.hostLegacyRouting as well.

https://github.com/cilium/cilium/pull/32367#discussion_r1593535000

**Comment by jspaleta** [comment] 2024-05-14 23:15
Just fyi, I'm seeing similar reproducible behavior in a Kind cluster environment but bpf.hostLegacyRouting doesn't appear to be a viable workaround for me...so far.  I'll continue testing in #32525

**Comment by zviratko** [comment] 2024-08-02 06:02
Just chiming in (as it has finally been ackowledged in the known issues)
this is an issue in my cluster as well
Talos Linux (1.7.5 ATM)
Cilium 1.15-1.16
Native Routing enabled
bpf enabled
kpr enabled
I have multiple VLANs on each host, Loadbalancer ExternalIPs on those and native routing over an internal interface

My workaround so far has been to create dedicated networking nodes to which all ExternalIPs are pinned (and I also had to create source routing rules for the VLANs which is a different issue)

**Comment by plutocholia** [comment] 2024-08-17 06:01
Is there a planned fix for this issue soon? The native Cilium eBPF datapath was a key factor in our decision to migrate to Cilium as the CNI, but this problem is undermining our ability to rely on the entire gateway-api and the ingress.

**Comment by julianwiedmann** [comment] 2024-10-11 10:38
> Differently, it didn't occur when [...] Cilium was configured in tunnel mode

FWIW, I believe the reason for this is https://github.com/cilium/cilium/issues/35023 - with overlay mode the IPv4 path is currently not using BPF-based host routing. Hence the backend's replies are delivered into the stack as expected.

**Closed as completed** 2024-10-28 14:53 UTC
Labels: kind/bug, area/agent, area/servicemesh, feature/k8s-ingress
