### ISSUE TITLE
restart cilium pod, cilium-health status is not normal

### ISSUE THREAD

**Issue by Charlottell** [cilium/cilium#19438] opened 2022-04-14 06:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1、restart the cilium pod of master1, cilium pod status is running, but i check the cilium status in the master1 and master2, status of master1 is normal , but status of master2 ,cilium endpoints unreachable.

```
root@master2:~# kubectl get pod -nkube-system -owide| grep cilium
cilium-757d5                                1/1     Running     0          3h46m   192.168.122.50   fd00::20c:29ff:fe9f:52bb   master3   <none>           <none>
cilium-9w4bf                                1/1     Running     0          3h16m   192.168.122.51   fd00::20c:29ff:fe9f:52dd   slave1    <none>           <none>
cilium-mjt88                                1/1     Running     0          3h8m    192.168.122.49   fd00::20c:29ff:fe9f:52ee   master2   <none>           <none>
cilium-operator-6978449bcd-r4n8h            1/1     Running     1          154m    192.168.122.50   fd00::20c:29ff:fe9f:52bb   master3   <none>           <none>
cilium-rb2mc                                1/1     Running     0          175m    192.168.122.48   fd00::20c:29ff:fe9f:52be   master1   <none>           <none>
```

```
root@master1:~# cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.13-30) [linux/arm64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [enp1s0 192.168.122.48 fd00::20c:29ff:fe9f:52be (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.0 (v1.11.0-27e0848)
NodeMonitor:            Listening for events on 4 CPUs with 64x65536 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 3/254 allocated from 100.101.2.0/24, IPv6: 3/65534 allocated from fd05::2:0/112
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Enabled]
Controller Status:      27/27 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 2.31   Metrics: Disabled
Encryption:             Disabled
Cluster health:         4/4 reachable   (2022-04-13T22:04:50Z)
```

```
root@master2:~# cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.13-30) [linux/arm64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [enp1s0 192.168.122.49 fd00::20c:29ff:fe9f:52ee (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.0 (v1.11.0-27e0848)
NodeMonitor:            Listening for events on 4 CPUs with 64x65536 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 3/254 allocated from 100.101.0.0/24, IPv6: 3/65534 allocated from fd05::/112
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Enabled]
Controller Status:      27/27 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 2.41   Metrics: Disabled
Encryption:             Disabled
Cluster health:         3/4 reachable    (2022-04-13T21:57:58Z)
  Name                  IP               Node        Endpoints
  master1               192.168.122.48   reachable   unreachable
```

2、 I  checkout the cilium-health status of master1 and master2, find the endpoint ip of master1 is changed ,but endpoint ip of master2 also use previous ip.

```
root@master1:~# cilium-health status
Probe time:   2022-04-13T22:05:50Z
Nodes:
  master1 (localhost):
    Host connectivity to 192.168.122.48:
      ICMP to stack:   OK, RTT=1.062039ms
      HTTP to agent:   OK, RTT=365.9µs
    Endpoint connectivity to 100.101.2.54:
      ICMP to stack:   OK, RTT=675.019µs
      HTTP to agent:   OK, RTT=1.788079ms
  master2:
    Host connectivity to 192.168.122.49:
      ICMP to stack:   OK, RTT=1.832419ms
      HTTP to agent:   OK, RTT=1.140539ms
    Endpoint connectivity to 100.101.0.8:
      ICMP to stack:   OK, RTT=2.329719ms
      HTTP to agent:   OK, RTT=2.750859ms
  master3:
    Host connectivity to 192.168.122.50:
      ICMP to stack:   OK, RTT=1.924339ms
      HTTP to agent:   OK, RTT=1.26648ms
    Endpoint connectivity to 100.101.3.156:
      ICMP to stack:   OK, RTT=2.116899ms
      HTTP to agent:   OK, RTT=880.02µs
  slave1:
    Host connectivity to 192.168.122.51:
      ICMP to stack:   OK, RTT=1.822239ms
      HTTP to agent:   OK, RTT=807.879µs
    Endpoint connectivity to 100.101.1.136:
      ICMP to stack:   OK, RTT=1.947979ms
      HTTP to agent:   OK, RTT=2.741099ms
```

```
root@master2:~# cilium-health status
Probe time:   2022-04-13T22:04:58Z
Nodes:
  master2 (localhost):
    Host connectivity to 192.168.122.49:
      ICMP to stack:   OK, RTT=712.02µs
      HTTP to agent:   OK, RTT=545.1µs
    Endpoint connectivity to 100.101.0.8:
      ICMP to stack:   OK, RTT=1.31942ms
      HTTP to agent:   OK, RTT=1.39874ms
  master1:
    Host connectivity to 192.168.122.48:
      ICMP to stack:   OK, RTT=758.76µs
      HTTP to agent:   OK, RTT=1.00418ms
    Endpoint connectivity to 100.101.2.114:
      ICMP to stack:   OK, RTT=17.795455ms
      HTTP to agent:   Get "http://100.101.2.114:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  master3:
    Host connectivity to 192.168.122.50:
      ICMP to stack:   OK, RTT=1.56044ms
      HTTP to agent:   OK, RTT=5.108498ms
    Endpoint connectivity to 100.101.3.156:
      ICMP to stack:   OK, RTT=1.71282ms
      HTTP to agent:   OK, RTT=1.013799ms
  slave1:
    Host connectivity to 192.168.122.51:
      ICMP to stack:   OK, RTT=792.16µs
      HTTP to agent:   OK, RTT=1.016739ms
    Endpoint connectivity to 100.101.1.136:
      ICMP to stack:   OK, RTT=982.26µs
      HTTP to agent:   OK, RTT=1.19706ms
```

3、 check the ciliumnode master1

```
root@master2:~# kubectl get ciliumnode master1 -o yaml
apiVersion: cilium.io/v2
kind: CiliumNode
metadata:
  creationTimestamp: "2022-04-13T18:12:21Z"
  generation: 5
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: master1
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: "true"
    node-role.kubernetes.io/node: "true"
    node.kubernetes.io/master: "true"
    node.kubernetes.io/node: "true"
  name: master1
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: master1
    uid: 21ca5ec1-3330-42cd-be14-0e0e55150bde
  resourceVersion: "12934"
  selfLink: /apis/cilium.io/v2/ciliumnodes/master1
  uid: c20f3118-f285-4972-af53-9ba01484c502
spec:
  addresses:
  - ip: 192.168.122.48
    type: InternalIP
  - ip: fd00::20c:29ff:fe9f:52be
    type: InternalIP
  - ip: 100.101.2.49
    type: CiliumInternalIP
  - ip: fd05::2:e51d
    type: CiliumInternalIP
  alibaba-cloud: {}
  azure: {}
  encryption: {}
  eni: {}
  health:
    ipv4: 100.101.2.54
    ipv6: fd05::2:19ac
  ipam:
    podCIDRs:
    - 100.101.2.0/24
    - fd05::2:0/112
status:
  alibaba-cloud: {}
  azure: {}
  eni: {}
  ipam:
    operator-status: {}
```
4、ping endpoint of master1, 

```
root@master2:~# ping 100.101.2.54
PING 100.101.2.54 (100.101.2.54) 56(84) bytes of data.
64 bytes from 100.101.2.54: icmp_seq=1 ttl=62 time=0.932 ms
64 bytes from 100.101.2.54: icmp_seq=2 ttl=62 time=0.496 ms
64 bytes from 100.101.2.54: icmp_seq=3 ttl=62 time=7.33 ms

```

5、 check cilium health status of other nodes,  other nodes are the same as mater2.

6、How change the health endpoints ip to make the cilium status is normal?

Thank you in advance.
 

### Cilium Version

root@master1:~# cilium version
Client: 1.11.0 27e0848 2021-12-05T15:34:41-08:00 go version go1.17.3 linux/arm64
Daemon: 1.11.0 27e0848 2021-12-05T15:34:41-08:00 go version go1.17.3 linux/arm64

### Kernel Version

root@master1:~# uname -a
Linux master1 4.19.0-arm64-server #4117 SMP Mon Nov 29 17:15:47 CST 2021 aarch64 GNU/Linux

### Kubernetes Version

root@master1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13-30", GitCommit:"d61ce5ace40fc44e807bb0f7214d8b022669ad8f", GitTreeState:"archive", BuildDate:"2022-03-12T01:09:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13-30", GitCommit:"d61ce5ace40fc44e807bb0f7214d8b022669ad8f", GitTreeState:"archive", BuildDate:"2022-03-12T01:10:46Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment] 2022-05-23 11:29
@Charlottell did the issue resolve by itself after a while?

**Comment by gandro** [comment] 2022-05-25 12:33
@Charlottell I'm investigating a similar issue at the moment. It would be helpful to tell us if

1. The issue is persistent or resolves after a while
2. If it is persistent, is it fixed by a invocation of `cilium-health status --probe` on e.g. `master2`

**Comment by gandro** [comment] 2022-07-26 12:20
@Charlottell Thanks for the report. Given that it affected kubeapi server nodes in your report as well, I believe this has been fixed with https://github.com/cilium/cilium/pull/20210 in the latest v1.11.7 release. Closing, please let me know if you feel otherwise.

**Closed as completed by gandro** 2022-07-26 12:20 UTC
Labels: kind/bug, needs/triage
