### ISSUE TITLE
Concurrency issues around `n.localNode`

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#21085] opened 2022-08-25 11:41 UTC
With https://github.com/cilium/cilium/commit/e52fe1d59d1c6f51a76993641ea9412e0f44f749, the `n.localNode` variable is not being protected on all places. For example https://github.com/cilium/cilium/blob/88e683528e92e20fe9557520a869030f234738a5/pkg/nodediscovery/nodediscovery.go#L373, which is inside `UpdateCiliumNodeResource`, is being executed from a public function where the `n.localNodeLock` is being held sometimes but not everytime.

cc @gandro

**Comment by gandro** [comment] 2022-08-25 12:00
I think this is a duplicate of https://github.com/cilium/cilium/issues/19884?

But the code might have changed since.

**Comment by aanm** [comment] 2022-08-25 12:16
Oh, it might be related but it looks like #19884 references different places :thinking:

**Comment by gandro** [comment] 2024-06-20 14:05
NodeStore no longer has a `n.localNode` and instead is using the node store instead. Closing as fixed.

**Closed as completed by gandro** 2024-06-20 14:05 UTC
Labels: kind/bug
