### ISSUE TITLE
cilium endpoint regenerate broken

### ISSUE THREAD

**Issue by briantopping** [cilium/cilium#15158] opened 2021-03-02 00:54 UTC
## Bug report

Not sure what's going on here. This is from a Gardener cluster running Cilium in the parent/seed cluster. I was having a problem with k8s `Endpoint` being generated improperly by the cloud-controller-manager, so I removed a `.subsets.addresses` entry and regenerated. The pod was reachable up to the point that the datapath-loader job ran, but not after the failure noted in the section "Then a few seconds later in the logs".

Please ping me on Slack as I can help interactively with this! Cheers...

```
# cilium endpoint list
546        Disabled           Disabled          23233      k8s:cloud.kubevirt.io/a5dae486185904444b97b5247fe54b3f=vpn-shoot                                              10.16.0.222   not-ready   
                                                           k8s:cloud.kubevirt.io/a66fcb83d1c5f4854882c1f82ad1c93f=ingress-nginx-controller                                                         
                                                           k8s:cloud.kubevirt.io/aa1794bbdbecc49f8be4471646da9942=mailu-front                                                                      
                                                           k8s:io.cilium.k8s.namespace.labels.gardener.cloud/role=project                                                                          
                                                           k8s:io.cilium.k8s.namespace.labels.project.gardener.cloud/name=example                                                                
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                         
                                                           k8s:io.kubernetes.pod.namespace=garden-example                                                                                        
                                                           k8s:kubevirt.io/created-by=0342adce-699c-4ec5-8e27-512b9369b723                                                                         
                                                           k8s:kubevirt.io/vm=shoot--example--public-worker-z1-5d877-hdmpg                                                                       
                                                           k8s:kubevirt.io=virt-launcher                                                                                                           
...
```

(log output while regenerate running is shown with `>`...)
```
# cilium endpoint regenerate 546
> level=info msg="Processing API request with rate limiter" maxWaitDuration=15s name=endpoint-patch parallelRequests=3 subsys=rate uuid=6fdf4780-7aee-11eb-b289-5a6143839430
> level=info msg="API request released by rate limiter" burst=4 limit=0.50/s maxWaitDuration=15s maxWaitDurationLimiter=14.99987943s name=endpoint-patch parallelRequests=3 subsys=rate uuid=6fdf4780-7aee-11eb-b289-5a6143839430 waitDurationLimiter=0s waitDurationTotal="139.602µs"
> level=info msg="API call has been processed" name=endpoint-patch processingDuration=1.000198835s subsys=rate totalDuration=1.000382737s uuid=6fdf4780-7aee-11eb-b289-5a6143839430 waitDurationTotal="139.602µs"

Endpoint 546 successfully regenerated
```
### Then a few seconds later in the logs:
```
level=error msg="Command execution failed" cmd="[tc filter replace dev lxcae4b10f44cbb ingress prio 1 handle 1 bpf da obj 546_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
level=warning msg="Tail call key 65535 for map 1 out of bounds?" subsys=datapath-loader
level=warning msg="Error filling program arrays!" subsys=datapath-loader
level=warning msg="Unable to load program" subsys=datapath-loader
level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=45914 desiredPolicyRevision=45914 endpointID=546 error="Failed to load tc filter: exit status 1" file-path=546_next/bpf_lxc.o identity=23233 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxcae4b10f44cbb
level=info msg="Regenerated endpoint BPF program" containerID= datapathPolicyRevision=45914 desiredPolicyRevision=45914 endpointID=546 error="Failed to load tc filter: exit status 1" identity=23233 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=45914 desiredPolicyRevision=45914 endpointID=546 file-path=546_next_fail identity=23233 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="Regeneration of endpoint failed" bpfCompilation=3.162175725s bpfLoadProg=1.638423983s bpfWaitForELF=0s bpfWriteELF=0s containerID= datapathPolicyRevision=45914 desiredPolicyRevision=45914 endpointID=546 error="Failed to load tc filter: exit status 1" identity=23233 ipv4= ipv6= k8sPodName=/ mapSync="9.679µs" policyCalculation="178.022µs" prepareBuild=1.810284ms proxyConfiguration="27.261µs" proxyPolicyCalculation="156.627µs" proxyWaitForAck=0s reason="endpoint was manually regenerated via API" subsys=endpoint total=4.803272905s waitingForCTClean=943ns waitingForLock="2.566µs"
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=45914 desiredPolicyRevision=45914 endpointID=546 error="Failed to load tc filter: exit status 1" identity=23233 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

### Additional info patterned from #12005
```
# cilium config
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  Medium
PolicyAuditMode          Disabled
PolicyTracing            Disabled
PolicyVerdictNotification Enabled
TraceNotification        Enabled
k8s-configuration        
k8s-endpoint             
PolicyEnforcement        never
MonitorNumPages          64
```

```
# cilium endpoint config 546
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DebugPolicy              Disabled
DropNotification         Enabled
MonitorAggregationLevel  Medium
NAT46                    Disabled
PolicyAuditMode          Disabled
PolicyVerdictNotification Enabled
TraceNotification        Enabled
```

**General Information**

- Cilium version (run `cilium version`) 1.9.4 07b62884c
- Kernel version (run `uname -a`) 5.10.4-051004-generic #202012301142
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) k8s v1.19.8, Gardener 1.16.3
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: [cilium-sysdump-20210302-005049.zip](https://github.com/cilium/cilium/files/6065378/cilium-sysdump-20210302-005049.zip)

**Comment by brb** [comment] 2021-03-02 05:26
Seems to be a duplicate of https://github.com/cilium/cilium/issues/15071.

**Comment by briantopping** [comment] 2021-03-02 05:40
@brb You would have a far better idea on that than me. If it's better to close this or add a "fixes" notation over there, please do.

**Comment by pchaigno** [comment] 2021-03-02 15:21
I'll close and link from the other issue. Thanks for the additional info! :pray:

**Closed as completed by pchaigno** 2021-03-02 15:21 UTC
Labels: kind/bug, kind/community-report
