### ISSUE TITLE
cilium version in json shows empty values

### ISSUE THREAD

**Issue by spiarh** [cilium/cilium#11218] opened 2020-04-29 11:53 UTC
## Bug report

**General Information**

`cilium version -ojson` shows empty values. FI, this is already the case with `1.5.3`.

- Cilium version: `1.6.6`
- Kernel version: `Linux 010084073053 4.12.14-197.37-default #1 SMP Fri Mar 20 14:56:51 UTC 2020 (e98f980) x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: Kubernetes `1.17.4`

**How to reproduce the issue**

```
sh-4.4# cilium version
Client: 1.6.6  go version go1.12.12 linux/amd64
Daemon: 1.6.6  go version go1.12.12 linux/amd64

sh-4.4# cilium version -ojson
{
  "Client": {
    "Version": "",
    "Revision": "",
    "GoRuntimeVersion": "",
    "Arch": "",
    "AuthorDate": ""
  },
  "Daemon": {
    "Version": "",
    "Revision": "",
    "GoRuntimeVersion": "",
    "Arch": "",
    "AuthorDate": ""
  }
}
```

**Comment by Rolinh** [comment] 2020-04-29 14:51
I am unable to reproduce this issue with either cilium `master` and `1.6.8` (on a `1.17.4` cluster):
```
# cilium version
Client: 1.6.8 f534e98df 2020-03-25T13:32:35+01:00 go version go1.12.17 linux/amd64
Daemon: 1.6.8 f534e98df 2020-03-25T13:32:35+01:00 go version go1.12.17 linux/amd64
# cilium version -ojson
{
  "Client": {
    "Version": "1.6.8",
    "Revision": "f534e98df",
    "GoRuntimeVersion": "go1.12.17",
    "Arch": "linux/amd64",
    "AuthorDate": "2020-03-25T13:32:35+01:00"
  },
  "Daemon": {
    "Version": "1.6.8",
    "Revision": "f534e98df",
    "GoRuntimeVersion": "go1.12.17",
    "Arch": "linux/amd64",
    "AuthorDate": "2020-03-25T13:32:35+01:00"
  }
}
```
Could you please provide more information about how you deployed cilium?

**Comment by lcavajani** [comment] 2020-04-29 16:02
cilium is part of our Kubernetes platform at `SUSE`, I first thought this would be an upstream bug but it might not be.

Let's ping @mrostecki to see if he has an idea :wink:

**Comment by mrostecki** [comment] 2020-04-29 17:22
Seems like problem on our side. I see the same issue with Cilium 1.7 on openSUSE Tumbleweed.

```
 ~                                                                                                                                                                                                                                                                                                                                                  19:15:02  mrostecki 
❯ cilium version
Client: 1.7.0  go version go1.13.9 linux/amd64
Daemon: Not responding
 ~                                                                                                                                                                                                                                                                                                                                                  19:15:07  mrostecki 
❯ cilium version -ojson
{
  "Client": {
    "Version": "",
    "Revision": "",
    "GoRuntimeVersion": "",
    "Arch": "",
    "AuthorDate": ""
  },
  "Daemon": {
    "Version": "",
    "Revision": "",
    "GoRuntimeVersion": "",
    "Arch": "",
    "AuthorDate": ""
  }
```

I'm closing this issue and opening SUSE bugs:

https://bugzilla.suse.com/show_bug.cgi?id=1170857
https://bugzilla.opensuse.org/show_bug.cgi?id=1170859

**Closed as completed by mrostecki** 2020-04-29 17:22 UTC
Labels: needs/triage, kind/community-report
