### ISSUE TITLE
Cluster Mesh loses connection after pods restarting. Is this a bug or the default state?

### ISSUE THREAD

**Issue by JWebDev** [cilium/cilium#35975] opened 2024-11-14 01:55 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Hi, I don't understand yet if this is a bug or the default state. Or is there something wrong with my default settings.

The situation is simple, I have 2 clusters and I connect them using Clustermesh. Both clusters have the same Kubernetes versions, linux systems, settings and different CIDRs.
After installing and connecting the clusters everything is ok. But when I restartthe cilium pods, the Clustermesh connection disappears. Also accordingly it disappears if I do helm upgrade. For example, to turn off some prometheus endpoint.
Doesn't help neither operator restart nor apiserver. Only creating a new connection helps.

1. My question is this a bug or default state? 
2. What settings should I have and what should I pay attention to in order to prevent future loss of Clustermesh connection?
3. Or does it happen only if all cilium agents in the cluster are simultaneously restarted at the same time?

And yes, thanks for a good product that works. ))

### How can we reproduce the issue?

1. Install cilium with Helm
2. `helm upgrade -i cilium cilium/cilium --namespace kube-system -f app/cilium/values.yaml`
3. `cilium clustermesh connect --context cluster1--destination-context cluster2`
4. Default values for both cluster:
```
cluster:
  name: app
  id: 2

cni:
  install: false

certgen:
  generateCA: false

hubble:
  tls:
    enabled: false
  relay:
    enabled: true
    prometheus:
      enabled: true
  ui:
    enabled: true
    standalone:
      enabled: true

prometheus:
  enabled: true

envoy:
  enabled: false
  prometheus:
    enabled: false

clustermesh:
  useAPIServer: true
  enableEndpointSliceSynchronization: true

authentication:
  enabled: false
```

### Cilium Version

1.16.3

### Kernel Version

`Linux app 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

v1.31.1

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment] 2024-11-14 14:32
Restarting cilium agent should be safe. Would you be able to provide a sysdump of a cluster in the affected state?

**Comment by JWebDev** [comment] 2024-11-17 02:22
@squeed Thanks for the answer. Unfortunately, not at this time, because I just updated and reinstalled/redo the clusters connection.

Perhaps you can describe in a nutshell how the connection is checked? What should I pay attention to? Maybe when the helm chart is updated some secrets are replaced where the data about the connection is stored? For example, certificates or something relevant.

**Comment by giorio94** [comment] 2024-11-25 18:05
The list of clusters each agent needs to connect to is normally configured via the [dedicated Helm values section](https://github.com/cilium/cilium/blob/21ad13700b0f295e4997ffe4d204a9dbcd4cf309/install/kubernetes/cilium/values.yaml#L3029-L3056) (either manually or via the Cilium CLI), which in turn populates the `cilium-clustermesh` secret (and the `cilium-kvstoremesh` one when kvstoremesh is enabled). Cilium agents (and KVStoreMesh) then leverage these secrets to retrieve the etcd configuration to connect to each remote cluster.

The restart of Cilium pods cannot impact on this configuration, because the secrets cannot be modified in the process. Differently, Helm upgrade operations can potentially reset the configuration, depending on the flags that are specified. However, without a sysdump it is not possible to be completely confirm that this was indeed the problem you experienced.

**Comment by JWebDev** [comment] 2024-11-26 00:57
@giorio94 Okay. Thanks for the explanation. I'll keep an eye on it. 
I posted with what configuration I am upgrading cilium with. Doesn't it give you any ideas? As I wrote, unfortunately I can't provide sysdump right now.

**Comment by giorio94** [comment] 2024-11-26 07:37
> I posted with what configuration I am upgrading cilium with. Doesn't it give you any ideas? As I wrote, unfortunately I can't provide sysdump right now.

Not necessarily, because it depends on the helm command (and especially on ``--reset-values`` and ``--reuse-values``, which have different defaults in different contexts) whether that resets the previously configured values or not. If it resets the values then yes, that would cause undoing the clustermesh configuration performed with the Cilium CLI.

**Comment by JWebDev** [comment] 2024-11-26 08:25
@giorio94 Actually, this was my question. I posted my installation and values. What is default value in Cilium? Can I configure these values in helm chart?

**Comment by giorio94** [comment] 2024-11-26 09:22
> Actually, this was my question. I posted my installation and values.

Not sure I'm understanding. The last command in the "How can we reproduce the issue?" section is the connection of the clusters.

> What is default value in Cilium? 

Which default are you talking about?

> Can I configure these values in helm chart?

Sure. The CLI just automates it for you. The easiest way to figure out what to configure is looking at how the CLI sets them.

**Comment by JWebDev** [comment] 2024-11-26 10:04
> Not sure I'm understanding. The last command in the "How can we reproduce the issue?" section is the connection of the clusters.
Yes it is. I had connected clusters and do helm upgrade, then clustermesh connection was disappeared. And after that I should do the `cilium clustermesh connect --context cluster1--destination-context cluster2` again to create the connection.

> Which default are you talking about?
Helm chart default values. If I reinstall the Cilium with helm. What is default Helm behavior? `--reset-values` or `--reuse-values`?

> Sure. The CLI just automates it for you. The easiest way to figure out what to configure is looking at how the CLI sets them.
OK.

**Comment by giorio94** [comment] 2024-11-26 11:25
> > Not sure I'm understanding. The last command in the "How can we reproduce the issue?" section is the connection of the clusters.
>
> Yes it is. I had connected clusters and do helm upgrade, then clustermesh connection was disappeared. And after that I should do the cilium clustermesh connect --context cluster1--destination-context cluster2 again to create the connection.

I'm still not getting it. The "How can we reproduce the issue?" section reports the following, and there's a single clustermesh connection step there:

> 1. Install cilium with Helm
>  2. helm upgrade -i cilium cilium/cilium --namespace kube-system -f app/cilium/values.yaml
>  3. cilium clustermesh connect --context cluster1--destination-context cluster2


>>  Which default are you talking about?
>
> Helm chart default values. If I reinstall the Cilium with helm. What is default Helm behavior? --reset-values or --reuse-values?

It depends on the rest of the command actually, which makes it even more confusing. Some resources: https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e, https://github.com/helm/helm/issues/8085

**Comment by JWebDev** [comment] 2024-11-29 05:31
@giorio94 
I understand your confusion. I just wanted to say that just after the usual cilium update, the connectin between clusters fell off for me. But there were probably some other things going on that I just didn't notice. 

Did some reading about `--reuse-values` and `--reset-values`. I'm not setting either of those values, so that means `--reuse-values` is used. 

If this happens again, I'll try to come up with more input on how to reproduce this.
Thanks for trying to help.

**Comment by giorio94** [comment] 2024-11-29 07:46
> I'm not setting either of those values, so that means --reuse-values is used.

Not necessarily, it does use `--reset-values` if you specify any new value via `--set` or `--values`. This is the most likely explanation for the clustermesh configuration having been reset.

> If this happens again, I'll try to come up with more input on how to reproduce this.

:+1: I'm going to close this issue for the moment. Feel free to reopen it if you manage to reproduce it again.

**Closed as completed by giorio94** 2024-11-29 07:46 UTC
Labels: kind/bug, area/datapath, needs/triage, kind/community-report, area/clustermesh, info-completed
