### ISSUE TITLE
CI: Network performance GKE

### ISSUE THREAD

**Issue by brlbil** [cilium/cilium#33159] opened 2024-06-14 16:15 UTC
Network performance GKE is failing for wireguard jobs all the time

Example run:
https://github.com/cilium/cilium/actions/runs/9457833052/job/26052335517

**Comment by jrife** [comment] 2024-08-22 20:26
I found a reliable way to reproduce the failure causing the flakes manually for easier investigation.

1. Set up a GKE cluster using the same configuration as the `Network performance GKE` test. For this I just copied the `gcloud container clusters create` command from [this test](https://github.com/cilium/cilium/actions/runs/10258407191/job/28381180414#step:17:72).
2. Run `cilium connectivity perf --duration=30s --host-net=true --pod-net=true` on the cluster (again I just copied this from the failed test). This may or may not fail, but it leaves all the test pods up and running for the next steps.
4. Get the IP of the `perf-server-*` pod. This will be used when running the `netperf` commands below. Mine was `10.102.73.72` for reference.
5. Open up a shell into the `perf-client-other-node-*` pod.
    ```
    $ kubectl exec -it -n cilium-test-1 perf-client-other-node-849f4b458b-7rjfg -- bash
    ```
6. Run `netperf` with a `10m` test duration. This seems long enough for whatever the issue is to eventually happen reliably. If this is a `UDP_STREAM` test you will eventually see a `No route to host` error. If this is a `TCP_CRR` test you will eventually get `Connection reset by peer`.
    ```
    [root@perf-client-other-node-849f4b458b-7rjfg netperf]# /usr/local/bin/netperf -H 10.102.73.72 -l 10m -t UDP_STREAM -- -R 1 -m 1024 -o MIN_LATENCY,MEAN_LATENCY,MAX_LATENCY,P50_LATENCY,P90_LATENCY,P99_LATENCY,TRANSACTION_RATE,THROUGHPUT,THROUGHPUT_UNITS
    MIGRATED UDP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.102.73.72 () port 0 AF_INET
    send_data: data send error: No route to host (errno 113)
    netperf: send_omni: send_data failed: No route to host
    ```
    ```
    [root@perf-client-other-node-849f4b458b-7rjfg netperf]# /usr/local/bin/netperf -H 10.102.73.72 -l 10m -t TCP_CRR -- -R 1 -m 1024 -o MIN_LATENCY,MEAN_LATENCY,MAX_LATENCY,P50_LATENCY,P90_LATENCY,P99_LATENCY,TRANSACTION_RATE,THROUGHPUT,THROUGHPUT_UNITS
    MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.102.73.72 () port 0 AF_INET
    netperf: send_omni: recv_data failed: Connection reset by peer
    ```

**Comment by jrife** [comment] 2024-08-23 00:20
Just wanted to add a few more observations. Digging a little further into this I enabled debugging for wireguard on the node where the `perf-client-other-node-*` pod was running.

```
root@gke-cilium-10481617798-1-5-jrife-pool-93cec72a-j1r6:/home/jrife# echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control
```

I ran `netperf` again from the pod and tailed the kernel log on that node watching for wireguard logs.

```
root@gke-cilium-10481617798-1-5-jrife-pool-93cec72a-j1r6:/home/jrife# journalctl -k -f
...
...
Aug 22 23:59:29 gke-cilium-10481617798-1-5-jrife-pool-93cec72a-j1r6 kernel: wireguard: cilium_wg0: Receiving keepalive packet from peer 2 (10.13.106.132:51871)
Aug 22 23:59:39 gke-cilium-10481617798-1-5-jrife-pool-93cec72a-j1r6 kernel: wireguard: cilium_wg0: No peer has allowed IPs matching 10.102.73.72
```

Every time `netperf` fails I saw a message like `cilium_wg0: No peer has allowed IPs matching 10.102.73.72` where `10.102.73.72` is the IP of the pod where I'm sending traffic. Looking at the driver code for wireguard this error comes from [here](https://github.com/torvalds/linux/blob/aa0743a229366e8c1963f1b72a1c974a9d15f08f/drivers/net/wireguard/device.c#L157).

```c
	peer = wg_allowedips_lookup_dst(&wg->peer_allowedips, skb);
	if (unlikely(!peer)) {
		ret = -ENOKEY;
		if (skb->protocol == htons(ETH_P_IP))
			net_dbg_ratelimited("%s: No peer has allowed IPs matching %pI4\n",
					    dev->name, &ip_hdr(skb)->daddr);
		else if (skb->protocol == htons(ETH_P_IPV6))
			net_dbg_ratelimited("%s: No peer has allowed IPs matching %pI6\n",
					    dev->name, &ipv6_hdr(skb)->daddr);
		goto err_icmp;
	}
```

At the same time as that message is visible in the kernel logs and the `netperf` job fails I also see this in the Cilium agent logs.

```
time="2024-08-22T23:59:39Z" level=debug msg="Updating peer config" endpoint="10.13.106.132:51871" ipAddrs="[{10.13.106.132 ffffffff} {10.102.73.80 ffffffff} {10.102.73.72 ffffffff} {10.102.73.199 ffffffff} {10.102.73.119 ffffffff} {10.102.73.115 ffffffff} {10.102.73.4 ffffffff} {10.102.73.216 ffffffff} {10.102.73.76 ffffffff} {10.102.73.208 ffffffff} {10.102.73.120 ffffffff} {10.102.73.71 ffffffff} {10.102.73.113 ffffffff}]" pubKey="8us1FgGDeqDOOQNTwyFTxggAXl8gu2oV/6B5BhRzHQI=" subsys=wireguard
```

This message comes from [here](https://github.com/cilium/cilium/blob/82962533c31fd4d0a7839cfd09e4cb08658c658e/pkg/wireguard/agent/agent.go#L515).

```go
	log.WithFields(logrus.Fields{
		logfields.Endpoint: p.endpoint,
		logfields.PubKey:   p.pubKey,
		logfields.IPAddrs:  p.allowedIPs,
	}).Debug("Updating peer config")

	return a.wgClient.ConfigureDevice(types.IfaceName, cfg)
}
```
which under the hood is [configuring](https://github.com/cilium/cilium/blob/82962533c31fd4d0a7839cfd09e4cb08658c658e/vendor/golang.zx2c4.com/wireguard/wgctrl/internal/wglinux/client_linux.go#L139) the wireguard device.

```go
// ConfigureDevice implements wginternal.Client.
func (c *Client) ConfigureDevice(name string, cfg wgtypes.Config) error {
	// Large configurations are split into batches for use with netlink.
	for _, b := range buildBatches(cfg) {
		attrs, err := configAttrs(name, b)
		if err != nil {
			return err
		}

		// Request acknowledgement of our request from netlink, even though the
		// output messages are unused.  The netlink package checks and trims the
		// status code value.
		if _, err := c.execute(unix.WG_CMD_SET_DEVICE, netlink.Request|netlink.Acknowledge, attrs); err != nil {
			return err
		}
	}

	return nil
}
```

When that happens [this function](https://github.com/torvalds/linux/blob/aa0743a229366e8c1963f1b72a1c974a9d15f08f/drivers/net/wireguard/allowedips.c#L181) is called inside the wireguard driver which manipulates the same data structure used by `wg_allowedips_lookup_dst`.

My theory is that there is a race condition here where [`lookup()`](https://github.com/torvalds/linux/blob/aa0743a229366e8c1963f1b72a1c974a9d15f08f/drivers/net/wireguard/allowedips.c#L127) returns `NULL` if called concurrently with [`add()`](https://github.com/torvalds/linux/blob/aa0743a229366e8c1963f1b72a1c974a9d15f08f/drivers/net/wireguard/allowedips.c#L181). In other words, if you transmit a packet at the same time you are configuring the wireguard device the packet won't be sent and the caller sees `No route to host`. I can do a bit more experimentation to test this theory and then either explore the wireguard code a bit to see if there is an easy fix or contact the driver maintainers.

**Comment by marseel** [comment] 2024-08-23 09:27
Very nice investigation, thanks!

`ConfigureDevice` call probably comes from `ConfigureDevice -> updatePeerByConfig -> UpdatePeer -> nodeUpsert -> NodeValidateImplementation -> backgroundSyncManager` from here: https://github.com/cilium/cilium/blob/b855b2575f7ae718290b29288b244930c7a223ec/pkg/node/manager/manager.go#L450
as during the test, we are not changing anything within the cluster. 

It seems like a bug in `UpdatePeer` where we update the device, even if nothing changes. 
cc @cilium/sig-encryption for insights.

**Comment by jrife** [comment] 2024-08-23 16:53
> It seems like a bug in UpdatePeer where we update the device, even if nothing changes.

We could mitigate the test flake issue by only updating the peer's allowed IP list when it changes (which as you point out shouldn't happen at all during the `netperf` test). Still, I imagine there are still scenarios out there where `UpdatePeer` might be triggered often as might be the case when clusters have high pod churn and the allowed IPs list changes frequently. Until a kernel-side fix is in place we could document this as a known issue [here](https://docs.cilium.io/en/latest/security/network/encryption-wireguard/) as well.

**Comment by jrife** [comment] 2024-09-03 20:14
I wanted to give an update on the status here.

The `UDP_STREAM` failures should be mitigated by #34612 and eventually the root cause should be addressed with the kernel patch I sent upstream (hopefully the WireGuard maintainers are receptive to the change). Just to add a little more detail here about what causes the failure, when the allowed IPs list gets updated for a peer it is first completely cleared before being rebuilt. Any calls to [`wg_xmit()`](https://github.com/torvalds/linux/blob/67784a74e258a467225f0e68335df77acd67b7ab/drivers/net/wireguard/device.c#L137) made during this time for one of the temporarily removed allowed IPs will end up jumping to [this line](https://github.com/torvalds/linux/blob/67784a74e258a467225f0e68335df77acd67b7ab/drivers/net/wireguard/device.c#L227). 

```c
	if (skb->protocol == htons(ETH_P_IP))
		icmp_ndo_send(skb, ICMP_DEST_UNREACH, ICMP_HOST_UNREACH, 0);
```

which triggers [`__udp4_lib_err`](https://github.com/torvalds/linux/blob/67784a74e258a467225f0e68335df77acd67b7ab/net/ipv4/udp.c#L719C5-L719C19) setting `sk->sk_err` to `EHOSTUNREACH`.

Upon further investigation it seems the `TCP_CRR` test failures have a different root cause. It seems connected to WireGuard somehow, since I only see the failure occur in the WireGuard-enabled environments judging by a spot check of the failed test jobs. However, there doesn't seem to be any correlation between when a `TCP_CRR` test fails and debug logs from the WireGuard module as was the case with the `UDP_STREAM` failures. This one seems harder to reproduce reliably. The only way I've found is to run `netperf` with a long timeout (e.g. `10m`) and wait. Even so, there are caveats.

* The time to failure is wildly variable. Sometimes it fails within seconds, sometimes within minutes.
* I spun up a new node pool with the same instance size and could not reproduce the issue after moving the workloads there. I don't know if this was just bad luck, if there needs to be some "warm up time" before the issue occurs, or if something about these instances was different.
* I spun up a new node pool with a larger instance size and could not reproduce the issue (more on this below).
* I could not reproduce this in a kind cluster.

Running `tcpdump` inside the server Pod's network namespace I was able to capture this when `netperf` stops and prints `Connection reset by peer`.

```
2024-08-30 16:42:33.828892 IP 10.102.76.71.33019 > 10.102.75.64.34735: Flags [S], seq 1176326533, win 42880, options [mss 1340,sackOK,TS val 972224961 ecr 0,nop,wscale 7], length 0
2024-08-30 16:42:33.828899 IP 10.102.75.64.34735 > 10.102.76.71.33019: Flags [S.], seq 2113493556, ack 1176326534, win 42496, options [mss 1340,sackOK,TS val 4258832221 ecr 972224961,nop,wscale 7], length 0
2024-08-30 16:42:33.829455 IP 10.102.76.71.33019 > 10.102.75.64.34735: Flags [.], ack 1, win 335, options [nop,nop,TS val 972224961 ecr 4258832221], length 0
2024-08-30 16:42:33.829477 IP 10.102.76.71.33019 > 10.102.75.64.34735: Flags [P.], seq 1:2, ack 1, win 335, options [nop,nop,TS val 972224962 ecr 4258832221], length 1
2024-08-30 16:42:33.829488 IP 10.102.75.64.34735 > 10.102.76.71.33019: Flags [R], seq 2113493557, win 0, length 0
```

The server is still running when the `RST` is sent to the client and is just waiting for a message from the client (i.e. blocked waiting on `recv`, which I confirmed using `strace` on the server process. For reasons unknown, the system just decides to send a `RST` packet immediately upon receiving the PSH+ACK. These observations are repeatable whenever the failure occurs. Some Googling turned up [this thread](https://www.spinics.net/lists/netdev/msg957074.html), which though sparse on detail did raise my suspicions that maybe this was a kernel bug of some sort.

Within the node pool where I could reliably produce the issue I tried a few different kernels on the Ubuntu hosts. I encountered the failure with `5.15.0-119-generic`, `5.15.0-1061-gke`, and `6.2.0-39-generic`. I could not reproduce the issue on `6.5.0-45-generic` or above. I thought maybe something had been fixed in later kernels, so I decided to try doing a bisect. This is when I spun up the second node pool with larger instances that I could use to build kernels from source. However, as mentioned above I couldn't reproduce the issue at all on this node pool.

I can come back to it when I get some time. My next step here is probably to try reproducing the issue again and doing the bisect to see if it leads to anything. This takes a long time, since there are about 15 iterations in the bisect and each iteration takes a while to test.

**Closed as completed** 2024-09-26 11:20 UTC
Labels: area/CI, ci/flake
