### ISSUE TITLE
Unable to add karpenter provisioner with Cilium IPAM : Cluster-Pool

### ISSUE THREAD

**Issue by spalan479** [cilium/cilium#31536] opened 2024-03-21 07:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have EKS cluster with Cilium installed (IPAM: cluster-pool ). Installed karpenter and when I tried to add provisioner I am getting the following error "Error from server (InternalError): error when creating "./karpenter/test_provisioner.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:8443/default/karpenter.k8s.aws?timeout=10s": Address is not allowed".

**Everything works file with ENI mode**

### Cilium Version

1.15.1

### Kernel Version

Linux 4.14.330-250.540.amzn2.x86_64 

### Kubernetes Version

EKS - 1.29

### Relevant log output

```shell
Karpenter Log:

{"level":"ERROR","time":"2024-03-21T06:56:09.326Z","logger":"webhook.ConfigMapWebhook","message":"Reconcile error","commit":"50f60fb","knative.dev/traceid":"faf23233-b480-4618-95d5-89eca6759567","knative.dev/key":"karpenter/karpenter-cert","duration":"74.050652ms","error":"failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"validation.webhook.config.karpenter.sh\": the object has been modified; please apply your changes to the latest version and try again"}
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment] 2024-03-27 11:25
This is, sadly, a known issue with EKS and tunneling mode. Because the control-plane does not have access to the overlay network, it cannot reach the pods.

There are 3 possible solutions:
- Use ENI mode instead
- Deploy your webhooks as HostNetwork pods
- Try and configure Konnectivity in EKS (this may not be possible)

I'm sorry, and I wish I had a better answer.

**Comment by squeed** [comment] 2024-03-27 12:00
This is almost certainly a duplicate of https://github.com/cilium/cilium/issues/30111, in which case I'll close this in favor of that.

**Comment by spalan479** [comment] 2024-04-02 23:31
> This is, sadly, a [known issue](https://github.com/aws/containers-roadmap/issues/2227) with EKS and tunneling mode. Because the control-plane does not have access to the overlay network, it cannot reach the pods.
> 
> There are 3 possible solutions:
> 
> * Use ENI mode instead
> * Deploy your webhooks as HostNetwork pods
> * Try and configure Konnectivity in EKS (this may not be possible)
> 
> I'm sorry, and I wish I had a better answer.

Thank you the karpenter and provisioner worked by updating the hostNetwork = true while installing karpenter. 
After installation, the setting can be verified in Karpenter deployment:
 kubectl get deployment karpenter -n karpenter -o yaml|grep hostNetwork
      hostNetwork: true

**Comment by julianwiedmann** [comment] 2024-04-05 12:04
Sounds like @squeed's guess was spot-on then :). Duping to #30111.

**Closed as not planned by julianwiedmann** 2024-04-05 12:04 UTC
Labels: kind/bug, needs/triage, kind/community-report

**Comment by sujeetkp** [comment] 2024-12-05 16:01
I was facing the same issue and adding host network does make karpenter pods run, but the cilium agent pod never gets scheduled on the new node created by karpenter. Karpenter creates an ec2 instance, but it never gets recognised by the EKS Cluster. Any idea what could be the issue. I tried adding startupTaints, kubectl.maxPods, but still the same issue. Am I missing something?
