### ISSUE TITLE
After 1.11 upgrade the endpoint are unreachable.

### ISSUE THREAD

**Issue by necipakca** [cilium/cilium#18351] opened 2022-01-03 06:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrade from 1.10.4 to 1.11 the host endpoints are unreachable.
The problem is the endpoint address not exist. Probably it is old address.
For example the blow  there is no address like "http://10.0.14.228:4240/hello" the right address of node11 is 10.0.14.67 currently.

    Host connectivity to 10.101.35.30:
      ICMP to stack:   OK, RTT=853.451µs
      HTTP to agent:   OK, RTT=693.879µs
    Endpoint connectivity to 10.0.14.228:
      ICMP to stack:   OK, RTT=845.533µs
      HTTP to agent:   Get "http://10.0.14.228:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Cilium Version

1.11.0

### Kernel Version

Linux node11 5.10.77-flatcar 

### Kubernetes Version

1.21.5

### Sysdump

https://drive.google.com/file/d/1cPyOvOUW2ecKpKShty0WHnLs0FXKasZM/view?usp=sharing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment] 2022-01-03 13:29
This issue seems to be the duplicate of https://github.com/cilium/cilium/issues/18302.

**Closed as completed by brb** 2022-01-03 13:29 UTC
Labels: kind/bug, needs/triage
