### ISSUE TITLE
Kube-proxy-replacement incorrectly detects aws-cni pod interfaces as host interfaces (1.15 regression)

### ISSUE THREAD

**Issue by cdenneen** [cilium/cilium#30563] opened 2024-01-31 22:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Namespaces with NetworkPolicies began having trouble reaching kube-dns service 172.20.0.10 but could reach kube-dns endpoints (which aren't what's in resolv.conf)
cilium agents showed:
```
cilium-wx7n5 cilium-agent level=error msg="Unable to assert if endpoint BPF programs need to be reloaded" endpoint=eni141776be69e endpointID=499 error="unable to find endpoint link by name: Link not found" subsys=daemon
```

### Cilium Version

1.150.0

### Kernel Version

5.10.205-195.804.amzn2.aarch64

### Kubernetes Version

1.28.5 EKS

### Anything else?

Rolled back to 1.14.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2024-01-31 23:02
Hi @cdenneen, thanks for the report. Can you expand a bit more around things like examples of the services where you experience this issue vs. not experiencing this issue, any detail about the Pods you used to reproduce the issue and whether for instance those Pods experience the issue on the same node or a different node from the target DNS Pods? Did you follow the [upgrade guide](https://docs.cilium.io/en/stable/operations/upgrade/#admin-upgrade) and was there any notable change that you made other than the version update? Also is Cilium's kube-proxy-replacement responsible for services here or is kube-proxy?

To best dig to the bottom of this issue and understand the root cause, ideally we can narrow this down to a simple set of steps such as, (1) Deploy Cilium with _____ configuration (share this) (2) deploy the star wars app (eg from [this guide](https://docs.cilium.io/en/stable/gettingstarted/demo/#starwars-demo)), (3) apply policy ____ (show example policy), (4) run command from a Pod to demonstrate the problem.

Attaching a sysdump (filtered by node to a node with the problem if it's too big) and listing the relevant apps/IPs for the Pod experiencing issues and the targets can also help others to investigate the issue.

**Comment by cdenneen** [comment] 2024-01-31 23:36
Had clusters running with 1.14.6. Flux did an automatic upgrade to 1.15.0 (I do no have anything that should cause issues based on upgrade docs).
Flux is installed with default NetworkPolicies (not CiliumNetworkPolicy). I was able to hit kube-dns endpoint IPs for nslookup from test pod in default namespace and flux-system namespace. I was only able to hit kube-dns service ip from default namespace (not flux-system where there are NetworkPolicies). 
Once I rolled back I could hit both again.

**Comment by joestringer** [comment] 2024-01-31 23:41
Is kube-dns running as a hostNetwork Pod? Can you share a link or a copy of the related policies? Also is kube-proxy running?

**Comment by sayboras** [comment] 2024-01-31 23:46
Might not be the same, but error log is similar with https://github.com/cilium/cilium-cli/issues/1894

**Comment by rsavage-nozominetworks** [comment] 2024-02-01 00:39
Seeing similar behavior as well.   I had to revert back to `1.14.6`.

**Comment by alexandermarston** [comment] 2024-02-01 10:38
Also a user of Flux here who had our cluster upgraded this morning. We observed a number of pods being unable to talk to the Kubernetes API server. We have no Network Policies (of any kind) deployment across the cluster, apart from the default Flux ones.

```
➜  ~ k logs kustomize-controller-6fd87586bc-q28lk
{"level":"error","ts":"2024-02-01T10:22:53.351Z","logger":"setup","msg":"unable to start manager","error":"failed to determine if *v1.Kustomization is namespaced: failed to get restmapping: failed to get server groups: Get \"https://172.20.0.1:443/api\": dial tcp 172.20.0.1:443: connect: connection refused"}
➜  ~ k logs helm-controller-54d9c5d544-b2hff
{"level":"error","ts":"2024-02-01T10:23:23.268Z","logger":"setup","msg":"unable to start manager","error":"failed to determine if *v2beta2.HelmRelease is namespaced: failed to get restmapping: failed to get server groups: Get \"https://172.20.0.1:443/api\": dial tcp 172.20.0.1:443: connect: connection refused"}
```

Network Tests seemed pretty unhappy too..

```
[=] Test [no-unexpected-packet-drops] [1/64]

  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  🟥 Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Is a ClusterIP"
  },
  "name": "cilium_drop_count_total",
  "value": 14299
```

Rolled back to 1.14.6 and all working fine again.

**Comment by ekarlso** [comment] 2024-02-01 14:01
I can second these issues, been having to manually apply a CNP instead of the NP to get it to work.

**Comment by julianwiedmann** [comment] 2024-02-01 14:46
Just to emphasize, adding context along @joestringer's questions in this issue (https://github.com/cilium/cilium/issues/30563#issuecomment-1920137690 and https://github.com/cilium/cilium/issues/30563#issuecomment-1920185397) is key to getting a better picture of what's happening.

**Comment by alexandermarston** [comment] 2024-02-01 16:46
Deployed Cilium (1.14.6) on a fresh cluster using the following values:

```
helm install cilium cilium/cilium --version 1.14.6 \
  --namespace kube-system \
  --set cni.chainingMode=aws-cni \
  --set cni.exclusive=false \
  --set enableIPv4Masquerade=false \
  --set routingMode=native \
  --set endpointRoutes.enabled=true \
  --set socketLB.hostNamespaceOnly=true \
  --set loadBalancer.algorithm=maglev \
  --set kubeProxyReplacement=true \
  --set k8sServiceHost=xxx.yl4.eu-west-1.eks.amazonaws.com \
  --set k8sServicePort=443
```

At this point, everything is working fine and Cilium connectivity tests are passing.

```
➜  ~ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium             Desired: 3, Ready: 3/3, Available: 3/3
Containers:            cilium             Running: 3
                       cilium-operator    Running: 2
                       hubble-relay       Running: 1
                       hubble-ui          Running: 1
Cluster Pods:          25/25 managed by Cilium
Helm chart version:    1.14.6
Image versions         cilium             quay.io/cilium/cilium:v1.14.6@sha256:37a49f1abb333279a9b802ee8a21c61cde9dd9138b5ac55f77bdfca733ba852a: 3
                       cilium-operator    quay.io/cilium/operator-generic:v1.14.6@sha256:2f0bf8fb8362c7379f3bf95036b90ad5b67378ed05cd8eb0410c1afc13423848: 2
                       hubble-relay       quay.io/cilium/hubble-relay:v1.14.6@sha256:adeb90adae481bb952211483f511afee40825707953ed7ac118902d3bc8dd37f: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe: 1
```

I then upgraded Cilium to 1.15.0

```
➜  ~ helm get values cilium --namespace=kube-system -o yaml > old-values.yaml

➜  ~ helm upgrade cilium cilium/cilium --version 1.15.0 \
  --namespace=kube-system \
  --set upgradeCompatibility=1.14.6 \
  -f old-values.yaml
Release "cilium" has been upgraded. Happy Helming!
NAME: cilium
LAST DEPLOYED: Thu Feb  1 16:40:18 2024
NAMESPACE: kube-system
STATUS: deployed
REVISION: 6
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble Relay and Hubble UI.

Your release version is 1.15.0.

For any further help, visit https://docs.cilium.io/en/v1.15/gettinghelp
```

Immediately after upgrade, things stop working....

```
➜  ~ k logs hubble-relay-55497d6df9-d9wxm --tail 50 -f
level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.cluster.local:443 dialTimeout:5000000000 retryTimeout:30000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress: log:0xc00036e1c0 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc000794c00 clusterName:default insecureClient:false observerOptions:[0x1f02b40 0x1f02c20] grpcMetrics:<nil> grpcUnaryInterceptors:[] grpcStreamInterceptors:[]}" subsys=hubble-relay
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
```

```
➜  ~ k logs cilium-8l9ln --tail 5 -f
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eni3542e19f5f3 ipAddr=10.0.1.246 subsys=node-neigh-debug
level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eni3542e19f5f3 ipAddr=10.0.116.89 subsys=node-neigh-debug
level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=pod-id-link0 ipAddr=10.0.1.246 subsys=node-neigh-debug
level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.0.1.246 subsys=node-neigh-debug
level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eni3542e19f5f3 ipAddr=10.0.1.246 subsys=node-neigh-debug
```

```
root@ip-10-0-171-105:/home/cilium# hubble observe -f | grep -v FORWARDED
Feb  1 16:45:20.086: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) policy-verdict:none INGRESS DENIED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:20.086: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) Policy denied DROPPED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.080: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) policy-verdict:none INGRESS DENIED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.080: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) Policy denied DROPPED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.080: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) policy-verdict:none INGRESS DENIED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.080: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) Policy denied DROPPED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.112: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) policy-verdict:none INGRESS DENIED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.112: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) Policy denied DROPPED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.112: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) policy-verdict:none INGRESS DENIED (ICMPv4 DestinationUnreachable(Port))
Feb  1 16:45:21.112: 172.20.116.161 (world) <> flux-system/helm-controller-58d5cc6f5b-8dz9g (ID:44513) Policy denied DROPPED (ICMPv4 DestinationUnreachable(Port))
```

```
➜  ~ k get service -A | grep 172.20.116.161
flux-system    source-controller                                ClusterIP   172.20.116.161   <none>        80/TCP                                  40m
```

Let me know if I can provide any more information

**Comment by julianwiedmann** [comment] 2024-02-02 08:39
The drops for `ICMPv4 DestinationUnreachable(Port)` make me think about https://github.com/cilium/cilium/pull/28157. Which would indicate that the service translation for `172.20.116.161` failed. Time for a sysdump, to understand what backends we believe are behind that service?

**Comment by alexandermarston** [comment] 2024-02-02 09:15
> The drops for `ICMPv4 DestinationUnreachable(Port)` make me think about #28157. Which would indicate that the service translation for `172.20.116.161` failed. Time for a sysdump, to understand what backends we believe are behind that service?

I could understand the backends being available, because the pods had crashed as they were unable to contact kube API server. Will try to get a sysdump this morning

**Comment by alexandermarston** [comment] 2024-02-02 10:21
[cilium-sysdump-20240202-102016.zip](https://github.com/cilium/cilium/files/14138660/cilium-sysdump-20240202-102016.zip)

sysdump attached from 1.15.0 installation on new cluster

**Comment by squeed** [comment] 2024-02-07 09:34
@alexandermarston I tried to reproduce this on a kind cluster, but I wasn't able to. Here's what I did:

1. Install v1.14 cluster
2. Apply the same network policies from your sysdump. Confirm that I could reach the apiserver
3. Upgrade to v1.15, not restarting anything besides cilium
4. Confirm that my pod could still reach the apiserver
5. downgrade and upgrade one more time, just to try and trigger this :-)

Looking at your sysdump, it seems that the state of the policy engine - both userland and bpf - is correct. Can you confirm that the sysdump captures pods in a broken state? Any other tricks for reproducing this? I'd really like to pin this down.

**Comment by cdenneen** [comment] 2024-02-07 12:31
It might be the aws-cni chaining that’s causing the problem? Have you tried
this on EKS?

**Comment by squeed** [comment] 2024-02-08 13:23
I was able to reproduce this; the key was using kube-proxy-replacement. Investigating.

**Comment by squeed** [comment] 2024-02-08 14:19
OK, I think I've figured this out. I created a v1.29 cluster with kube-proxy-replacement, installed v1.14, and created 10 pods. They were able to access service IPs just fine.

I then upgraded the node to v1.15, and some of the pods were not able to access service IPs.

I then noticed that broken pods have the wrong tc filter installed:
```
filter protocol all pref 1 bpf chain 0 handle 0x1 cil_to_netdev-enia7ba38102ff direct-action not_in_hw id 935 tag cf11e1331957c9fb jited 
```

And looking at the same file for v1.14:

```
filter protocol all pref 1 bpf chain 0 handle 0x1 cil_to_container-enia7ba38102ff direct-action not_in_hw id 411 tag 77b211f045fef4d3 jited 
```

The key mistake: it now has the program `cil_to_netdev`. And the final bit: we're incorrectly detecting these veth's as host net devices.

The output of `cilium status` from v1.14:

```
KubeProxyReplacement:   True   [eth0 192.168.40.168 (Direct Routing)]
```

And from v1.15:
```
KubeProxyReplacement:   True   [eth0   192.168.40.168 fe80::b6:a4ff:fe36:3df1 (Direct Routing), eth1   192.168.61.218 fe80::5b:c1ff:fe07:10d, enib330a6f9655  fe80::c059:31ff:fe54:7d17, enic013794f2eb  fe80::58f8:62ff:fed5:aa0, eni6eee2206b48  fe80::9868:4bff:fe05:8735, eni9f3bbf45a88  fe80::50b7:81ff:fea3:74ec, enia7ba38102ff  fe80::48bb:89ff:fec3:c5b4, enida1659a9e3b  fe80::24c9:c4ff:fe79:83b3, eth2   192.168.35.120 fe80::68:ceff:fec8:ca67]
```

Oops, those are pod interfaces, not host interfaces.

**Comment by squeed** [comment] 2024-02-08 14:39
[This is likely the buggy line](https://github.com/cilium/cilium/blob/v1.15/pkg/datapath/linux/devices_controller.go#L569). Assigning to @dylandreimerink, who touched it last :-).

**Comment by joamaki** [comment] 2024-02-08 16:43
Here's the bug: https://github.com/cilium/cilium/blob/main/pkg/datapath/tables/route.go#L57
It should construct a compound key of `table+link index+destination`, but it's accidentally using `table + table + destination`.
Here's the fix:
```
diff --git a/pkg/datapath/tables/route.go b/pkg/datapath/tables/route.go
 index 3f4fbc2d37a7..0d8c2ba41972 100644
 --- a/pkg/datapath/tables/route.go 
 +++ b/pkg/datapath/tables/route.go 
 @@ -56,7 +56,7 @@ type RouteID struct {
  
  func (id RouteID) Key() index.Key {
         key := append(index.Uint64(uint64(id.Table)), '+')
 -       key = append(key, index.Uint64(uint64(id.Table))...) 
 +       key = append(key, index.Uint64(uint64(id.LinkIndex))...) 
         key = append(key, '+')
         key = append(key, index.NetIPPrefix(id.Dst)...)
         key = append(key, 0 /* termination */)
```

**Comment by squeed** [comment] 2024-02-08 18:12
Good find!

It does make me curious, though: how was this non-deterministic? Are we attaching BPF programs before we know all the routes?

**Comment by joamaki** [comment] 2024-02-08 19:12
It’s non-deterministic probably because the primary index key was wrong and the route entries thus overlapped and older entries were overwritten.

**Closed as completed** 2024-02-21 16:05 UTC
Labels: kind/bug, priority/high, kind/community-report, kind/regression, area/loadbalancing
