### ISSUE TITLE
CI: TestPeerManager panic: close of closed channel

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16239] opened 2021-05-20 09:52 UTC
```
goroutine 44 [running]:
github.com/cilium/cilium/pkg/hubble/relay/pool.TestPeerManager.func7.1.1(0x0, 0xc000061500, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager_test.go:255 +0x86
github.com/cilium/cilium/pkg/hubble/testutils.(*FakePeerNotifyClient).Recv(0xc0002dd610, 0xc0000615c0, 0xc0000edf00, 0x1)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/testutils/fake.go:160 +0x3c
github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).watchNotifications(0xc0002bb5e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:125 +0x7b6
github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).Start.func1(0xc0002bb5e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:74 +0x5a
created by github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).Start
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:72 +0x67
FAIL	github.com/cilium/cilium/pkg/hubble/relay/pool	1.051s
```

/cc @rolinh

**Comment by rolinh** [comment] 2021-05-20 11:36
This is a duplicate of #15442, closing.

**Closed as completed by rolinh** 2021-05-20 11:36 UTC
Labels: kind/bug/CI, area/CI
