### ISSUE TITLE
CI: Cilium Cleanup (ConformanceGKE)

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#22573] opened 2022-12-06 13:27 UTC
## CI failure

Got a [failure](https://github.com/cilium/cilium/actions/runs/3628789905/jobs/6120562134) of the cleanup step on the GKE Conformance test. It gets stuck and is killed by the CI runner after a while.

```
Run pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
🔥 Deleting pods in cilium-test namespace...
🔥 Deleting cilium-test namespace...
⌛ Waiting for cilium-test namespace to be terminated...
Error: The operation was canceled.
```

[cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/10166847/cilium-sysdump-out.zip.6.zip)

**Comment by pchaigno** [comment] 2022-12-12 22:38
Duplicate of https://github.com/cilium/cilium/issues/22368.

**Closed as completed by pchaigno** 2022-12-12 22:38 UTC
Labels: area/CI, ci/flake
