### ISSUE TITLE
IPSec does not clean up stale xfrm policies

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#26298] opened 2023-06-16 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

IPSec does not clean up xfrm policies for nodes that have been deleted during cilium-agent upgrade.

Test case:
- Create cluster with Cilium and IPSec enabled (tested on EKS) with at least 2 nodes.
- Observe number of xfrm policies on node A
- Simulate cilium-agent being down by changing nodeSelector to nonexistent
- Delete node B from cluster
- Modify nodeSelector of cilium-agent daemonset back to normal
- Observe number of xfrm policies on node A (it doesn't decrease)

### Cilium Version

v1.13.4

### Kernel Version

N/A

### Kubernetes Version

v1.25.10-eks-c12679a

### Sysdump

[cilium-sysdump-20230616-104346.zip](https://github.com/cilium/cilium/files/11768193/cilium-sysdump-20230616-104346.zip)

### Relevant log output

```shell
Xfrm policies before node deletion:

ip xfrm policy | grep src | wc
13
```
After deleting node and restarting cilium-agent:
```
ip xfrm policy | grep src | wc
13
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgo3** [comment] 2023-11-29 14:40
As far as I can see it's not an IPsec-specific issue, but rather a `linuxNodeHandler` issue.

To reproduce, I create a kind cluster (`./contrib/scripts/kind.sh "" 3 "" "" "iptables" "ipv4"`) and install cilium with IPsec enabled. Before deleting a node, lets investigate some state in the cluster on the `kind-worker` node.
```
root@kind-worker:/home/cilium# cilium node list
Name                           IPv4 Address   Endpoint CIDR   IPv6 Address   Endpoint CIDR   Source
kind-kind/kind-control-plane   172.18.0.5     10.244.0.0/24                                  custom-resource
kind-kind/kind-worker          172.18.0.2     10.244.1.0/24                                  local
kind-kind/kind-worker2         172.18.0.4     10.244.3.0/24                                  custom-resource
kind-kind/kind-worker3         172.18.0.3     10.244.2.0/24                                  custom-resource
```
The `cilium node list` results are populated by the daemon status API, not the linuxNodeHandler. As expected we see 4 nodes.

```
root@kind-worker:/home/cilium# cilium nodeid list
NODE ID   IP ADDRESSES
0x2ae3    172.18.0.4
          10.244.3.61
0x64f2    172.18.0.3
          10.244.2.98
0xf10     10.244.1.27
          172.18.0.2
0xc91d    172.18.0.5
          10.244.0.59
```
The `cilium nodeid list` results are populated by the `linuxNodeHandler`. As expected we see 4 node IDs mapping to the respective node IPs.
```
root@kind-worker:/home/cilium# ip x s | grep proto | wc -l
4
```
Based on node events (`NodeAdd`, `NodeDelete`) in the `linuxNodeHandler` the IPsec subsystem adds and removes XFRM states. We have 4 states for every PodCIDR in the cluster.


Then I run the following commands to simulate a node being deleted during an upgrade of the agent as suggested by @marseel:
```
kubectl -n kube-system patch daemonset cilium -p '{"spec": {"template": {"spec": {"nodeSelector": {"non-existing": "true"}}}}}'
kubectl drain kind-worker3 --ignore-daemonsets
kubectl delete node kind-worker3
kubectl -n kube-system patch daemonset cilium --type json -p='[{"op": "remove", "path": "/spec/template/spec/nodeSelector/non-existing"}]'
```

Now if I check the state on `kind-worker` again, these are the results:
```
root@kind-worker:/home/cilium# cilium node list
Name                           IPv4 Address   Endpoint CIDR   IPv6 Address   Endpoint CIDR   Source
kind-kind/kind-control-plane   172.18.0.5     10.244.0.0/24                                  custom-resource
kind-kind/kind-worker          172.18.0.2     10.244.1.0/24                                  local
kind-kind/kind-worker2         172.18.0.4     10.244.3.0/24                                  custom-resource
```
`kind-worker-3` is missing from the output now.
```
root@kind-worker:/home/cilium# cilium nodeid list
NODE ID   IP ADDRESSES
0xf10     10.244.1.27
          172.18.0.2
0x64f2    10.244.2.98
          172.18.0.3
0x2ae3    172.18.0.4
          10.244.3.61
0xc91d    172.18.0.5
          10.244.0.59
```
Node ID `0x64f2` still exists mapping to `172.18.0.3` (`kind-worker-3`). Should be removed, but we missed the `NodeDelete` event.
```
root@kind-worker:/home/cilium# ip x s | grep proto | wc -l
4
```
The respective XFRM state also still exists for the same reason.

I checked the agent logs after it's restarted, and no `NodeDelete` events are logged. I can only see `NodeUpdate` events. I think the `linuxNodeHandler` might need some garbage collection logic to clean up nodes that it doesn't receive updates for anymore. Similar to the authmap garbage collector, assuming I understand that code correctly.

Sorry for the _very_ verbose output, however I thought this makes it easy to follow along without having to reproduce locally.

**Comment by pchaigno** [comment] 2023-11-29 14:47
> Sorry for the _very_ verbose output, however I thought this makes it easy to follow along without having to reproduce locally.

Perfect level of verbosity!

> The `cilium node list` results are populated by the daemon status API, not the linuxNodeHandler. As expected we see 4 nodes.

What do you mean by this? Is it querying for the information reactively or is there some garbage collection happening?

> I think the `linuxNodeHandler` might need some garbage collection logic to clean up nodes that it doesn't receive updates for anymore.

How often would that run? On a timer + on agent startup?

In terms of impact for the bug, we're only looking at a leak, right? AFAICT, there's no risk of reusing a node ID that's still in use since the bug is the other way around: we don't release an ID that we should release.

**Comment by marseel** [comment] 2023-11-29 15:01
> As far as I can see it's not an IPsec-specific issue, but rather a linuxNodeHandler issue.

Makes sense! Thanks for your investigation. 

> I checked the agent logs after it's restarted, and no NodeDelete events are logged. I can only see NodeUpdate events. I think the linuxNodeHandler might need some garbage collection logic to clean up nodes that it doesn't receive updates for anymore. Similar to the authmap garbage collector, assuming I understand that code correctly.

I just want to add, that I have seen such issues multiple times with different subsystems (basically missing delete event) - clustermesh, kvstore, now linuxNodeHandler, and as you mentioned authmap. Seems to me that we should have a systematic way of testing such cases, but also possibly a generic way of dealing with them. Maybe worth discussing that during the Cilium weekly meeting, WDYT?

**Comment by rgo3** [comment] 2023-11-29 15:10
> Is it querying for the information reactively or is there some garbage collection happening?

`cilium node list` queries the daemon status API, which I think is backed by the [clusterNodesClient](https://github.com/cilium/cilium/blob/82dbff8e5a5f7ced99e96cd85997fae90e035aac/daemon/cmd/status.go#L471), another implementation of the [NodeHandler](https://github.com/cilium/cilium/blob/82dbff8e5a5f7ced99e96cd85997fae90e035aac/pkg/datapath/types/node.go#L93) interface. I think here the difference is that it populates an internal list with available nodes on every startup of the agent and doesn't rebuild any state from previous runs. But I need to investigate more to be 100% sure.

> How often would that run? On a timer + on agent startup?

I don't know if running on startup is sufficient, because I'm not familiar as to when cilium knows about all nodes that are currently in the cluster.

> we don't release an ID that we should release.

As far as I can tell this is the only impact, but I'm not aware if keeping this kind of state around can cause any other issues long-term.

**Comment by pchaigno** [comment] 2023-11-29 15:22
> I don't know if running on startup is sufficient, because I'm not familiar as to when cilium knows about all nodes that are currently in the cluster.

We learn that at some point during the startup (after connecting to kube-apiserver). I'm mostly suggesting agent startup in addition to timer because the most-likely case for this bug to happen is what you tested: a node is deleted during an agent restart. But if the only impact is this slow leak of resources, then we're probably not in a hurry and can wait for the GC timer to trigger.

> I'm not aware if keeping this kind of state around can cause any other issues long-term.

A very large list of IPsec XFRM policies can cause performance degradations on ENI and Azure IPAM modes. I don't think this leak is big enough for that to be a real concern here.

**Comment by msune** [comment] 2024-05-14 15:44
@rgo3 wondering if you are actively working on this, given that you are assigned.

**Comment by rgo3** [comment] 2024-05-16 11:01
Currently not working on this. After my initial investigation, I opened #29822 and since then it has been "shelved" since the urgency wasn't super high and it wasn't purely IPsec related.

**Comment by bimmlerd** [comment] 2024-08-02 08:52
Yes this should be mostly solved. I don't like the solution from an architectural point of view, and there's an intentional race window (to ensure performance does not suffer too much), but I'll close this for now.

**Closed as completed by bimmlerd** 2024-08-02 08:52 UTC
Labels: kind/bug, area/datapath, area/encryption, pinned, feature/ipsec
