### ISSUE TITLE
Cilium can't handle pods massive creation on high scale Kubernetes cluster

### ISSUE THREAD

**Issue by luanguimaraesla** [cilium/cilium#5913] opened 2018-10-16 22:50 UTC
### Title

On a Kubernetes cluster with 200+ nodes, Cilium can't handle the creation of 4000+ pods.

### General Information

- __Cilium version__: v1.2.3
- __Kernel version__: Linux 4.14.67
- __Orchestration system version in use__: Kubernetes 1.10.7
- __etcd version__: 3.1.11

### Cluster Configuration

|       | Instances | CPU per Instance | Memory per Instance |
| --- | --- | --- | --- |
| Masters | 3 | 4 | 16GB |
| Nodes | 200 | 8 | 15GB |

### How to reproduce the issue

1. Deploy a Kubernetes cluster with 3 master nodes and 200 worker nodes
2. Create 800 servers and 5200 clients making 10 requests per second each one.

### Results
The following chart shows how does the cluster behave under this test scenario.
![pods](https://user-images.githubusercontent.com/11253021/47047526-2c060580-d16e-11e8-848c-2939516d000a.png)
The gray line counts how many Ready nodes the cluster has. It is extremally unstable due metrics-server outages during the tests.

After reaching 3000 pods, the cluster starts to behave unexpectedly, with some pods dying, and the rate of pod creation declining until no more was created. 1500 pods were no longer created, and the cluster was practically unusable. Check this section of the chart above.

![zoom_pods](https://user-images.githubusercontent.com/11253021/47049189-ff082180-d172-11e8-9402-5ef3e5e13f54.png)

The most recurrent error was:
```
Warning   FailedCreatePodSandBox   kubelet, ip-172-151-106-95.ec2.internal    Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "ubuntu-curl-5b9f864c79-mtdj6_ubuntu-curl" network: add cmd: failed to assign an IP address to container
```
Also, we collected some resource usage metrics before metrics-server crashing. The blue, red and orange lines represent the master nodes.

![resources](https://user-images.githubusercontent.com/11253021/47048946-3e823e00-d172-11e8-96d4-485a7ead3e71.png)

CPU usage critically increased during the test, making the Kubernetes API unavailable. We believe that this behavior may be due to some misconfiguration, since performing the same test with two other CNI plugins, Calico and Amazon VPC, there was a big difference in the results.

| | Calico | Amazon VPC | Cilium |
|-- | -- | -- | -- |
|Masters Max CPU usage | 80% | 80% | 93%* |
|Masters Max Memory usage | 25% | 25% | 28%* |
|Nodes Max CPU usage | 14% | 35% | 43%* |
|Nodes Max Memory usage | 14% | 16% | 16%* |
|Test duration | 5 min | 12 min | interrupted |

\* reported before metrics-server breaking

Do we have to make any specific configuration for a high scale cluster to work with a big number of pods and a high load networking traffic?

**Comment by tgraf** [comment] 2018-10-16 23:00
@luanguimaraesla I'll write a longer response but the get things started: What PodCIDR configuration are you putting Kubernetes in? It seems that Cilium is running out of IP addresses to allocate.

**Comment by luanguimaraesla** [comment] 2018-10-16 23:13
Thank you for your attention. The PodCIDR is 100.64.0.0/10.

**Comment by tgraf** [comment] 2018-10-16 23:36
@luanguimaraesla Thanks for the quick response.

We suspect that frequent Pod annotations plus the updates to the CRD that mirrors each pod as performed by Cilium are the cause for the increased CPU usage in the apiserver which causes the breakage at +3K pods. We'll confirm this theory and provide a fix.

The increased CPU usage on the worker is caused by the BPF program generation right now. Cilium 1.3 will already bring some relief and the upcoming BPF templating will remove the need to compile programs entirely when pods are bootstrapped.

@luanguimaraesla Do you have Cilium and apiserver logs by any change? We would love to dig through them to confirm the above theories.

**Comment by luanguimaraesla** [comment] 2018-10-17 18:56
Yes. I had to make another test to collect the logs. The files are attached.

[cilium.zip](https://github.com/cilium/cilium/files/2488812/cilium.zip)

**Comment by luanguimaraesla** [comment] 2018-10-17 20:03
> The increased CPU usage on the worker is caused by the BPF program generation right now.

We also collected some data from the moment we instantiate 200 nodes. Knowing that the use of resources would increase in the workers during the generation of the BPF program, we thought that after the stabilization of the cluster, the use of CPU would normalize, which did not happen. Take a look at the following chart.

![pods](https://user-images.githubusercontent.com/11253021/47111477-0d654480-d22a-11e8-8572-8cf0136c3dc8.png)
![resources](https://user-images.githubusercontent.com/11253021/47111478-0dfddb00-d22a-11e8-9cd8-bb3ee28c27fb.png)

26% of CPU usage per node with no workloads running, except by the default ones, is too high for production nodes. So, why do you think the cluster still using too many resources? Could we normalize the resource usage after BPF program generation with any configuration?

The master nodes are more critical, perhaps the high CPU usage causes Kubernetes API outages and then the Cilium bad behavior, which we can see on the following error on cilium-node.

```
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumEndpoint subsys=k8s
level=error msg="Unable to update CRD" error="Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io \"ciliumendpoints.cilium.io\": the object has been modified; please apply your changes to the latest version and try again" name=v2.CiliumEndpoint subsys=k8s
level=fatal msg="Unable to establish connection to Kubernetes apiserver" error="Unable to create custom resource definition: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io \"ciliumendpoints.cilium.io\": the object has been modified; please apply your changes to the latest version and try again" subsys=daemon
level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
``` 

Regards

**Comment by aanm** [comment] 2018-10-17 22:28
@luanguimaraesla thanks for the given zip file, 2 of the cilium issues in that file will be fixed and backported to v1.2 with this PR https://github.com/cilium/cilium/pull/5926

**Comment by tgraf** [comment] 2018-10-18 00:10
@luanguimaraesla Thanks for the excellent data. This is awesome. The data confirm the previous suspicion that this is not related to pod creation workload itself but to the interaction with the apiserver  with respect to the CiliumEndpoint CRD. The log indicates over 200 interactions with the apiserver per second. We'll fix this right away.

**Comment by luanguimaraesla** [comment] 2018-10-19 18:46
@tgraf @aanm Thank you guys for this excellent work. The `--disable-endpoint-crd` flag and the other fixes you quickly made resulted in a significant improvement in the results.

Now it is possible to see the CRD sync disabled.

```
level=warning msg="Not running controller. CEP CRD synchronization is disabled" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (21530)" endpointID=21530 ipv4= ipv6= k8sPodName=/ policyRevision=2
```

This really caused an excessive load on Kubernetes API. Now we can see the CPU usage decrease after the BPF programs generation. Look at the following charts from this test.

![pods](https://user-images.githubusercontent.com/11253021/47236454-9a3b0a00-d3b2-11e8-9ef8-63b685d597d9.png)

We successfully reached almost 6500 running pods on 200 Kubernetes nodes. The temporary unavailability of the metrics-server is normal and also happened in the load-test with other technologies.

![resources](https://user-images.githubusercontent.com/11253021/47236463-a030eb00-d3b2-11e8-9623-fb46544779c7.png)

Here we can see the tendency to decrease the use of resources after creating all pods. I think it's still significantly high especially in the worker nodes, but this is a matter of future enhancements. I also collected again the cilium and apiserver logs for the comparison with the old logs.

[cilium2.zip](https://github.com/cilium/cilium/files/2496967/cilium2.zip)

Now, things are looking good. Thanks for all the work.

**Comment by joestringer** [comment] 2019-03-26 18:10
Looks like the original reporter is happy with where Cilium got to after the first few fixes, and furthermore the project https://github.com/cilium/cilium/projects/18 is tracking further scale improvements. Will close, feel free to re-open/file new aissue if you hit additional issues with Cilium scale.

Thanks.

**Closed as completed by joestringer** 2019-03-26 18:10 UTC
Labels: kind/bug, kind/community-report
