### ISSUE TITLE
Endpoint generation failed: Unable to rename current endpoint directory

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4652] opened 2018-06-26 15:09 UTC
Seen the following warning when restarting Cilium. It seems related to restoring the health endpoint.

```
level=warning msg="Regeneration of endpoint program failed" containerID=cilium-loc endpointID=22465 error="Unable to rename current endpoint directory: rename /var/run/cilium/state/22465 /var/run/cilium/state/22465_stale: no such file or directory" ipv4=10.2.3.247 ipv6="f00d::a02:300:0:57c1" k8sPodName=":" policyRevision=0
```

**Comment by nebril** [comment] 2018-07-19 11:08
@tgraf I was unable to reproduce it on minikube or dev cluster, please let me know if you have any specific reproduction steps. Closing for now.

**Closed as completed by nebril** 2018-07-19 11:08 UTC
Labels: kind/bug, priority/high
