### ISSUE TITLE
cilium operator CRDs not in sync with k8s?

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#21657] opened 2022-10-11 01:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a installation scenario below using cilium cli to install cilium

1, install cilium v1.12.0

`[root@cilium-dev home]# cilium install --version=v1.12.0 --kube-proxy-replacement strict --helm-set-string=k8sServiceHost=10.3.72.239,k8sServicePort=6443`

CRDs gets created

```
[root@cilium-dev home]# kubectl get crds -A
NAME                                         CREATED AT
ciliumclusterwidenetworkpolicies.cilium.io   2022-10-11T01:06:10Z
ciliumendpoints.cilium.io                    2022-10-11T01:06:10Z
ciliumexternalworkloads.cilium.io            2022-10-11T01:06:10Z
ciliumidentities.cilium.io                   2022-10-11T01:06:10Z
ciliumnetworkpolicies.cilium.io              2022-10-11T01:06:10Z
ciliumnodes.cilium.io                        2022-10-11T01:06:10Z
```
2, uninstall cilium 1.12.0

```
[root@cilium-dev home]# cilium uninstall
🔥 Deleting Hubble UI...
🔥 Deleting Relay...
🔥 Deleting Relay certificates...
🔥 Deleting Peer Service...
✨ Patching ConfigMap cilium-config to disable Hubble...
🚀 Creating ConfigMap for Cilium version 1.12.0...
♻️  Restarted Cilium pods
ℹ️  Storing helm values file in kube-system/cilium-cli-helm-values Secret
✅ Hubble was successfully disabled.
🔥 Deleting cilium-test namespace...
🔥 Deleting cilium-secrets namespace...
🔥 Deleting Service accounts...
🔥 Deleting ConfigMap...
🔥 Deleting Cluster roles...
🔥 Deleting agent DaemonSet...
🔥 Deleting operator Deployment...
🔥 Deleting IngressClass...
🔥 Deleting clustermesh-apiserver...
🔥 Deleting ClusterMesh certificates...
✅ ClusterMesh disabled.
🔥 Deleting certificates...
🔥 Deleting secret with the helm values configuration...
✅ Cilium was successfully uninstalled.
```
CRDs is intact after cilium uninstall

```
[root@cilium-dev home]# kubectl get crds -A
NAME                                         CREATED AT
ciliumclusterwidenetworkpolicies.cilium.io   2022-10-11T01:06:10Z
ciliumendpoints.cilium.io                    2022-10-11T01:06:10Z
ciliumexternalworkloads.cilium.io            2022-10-11T01:06:10Z
ciliumidentities.cilium.io                   2022-10-11T01:06:10Z
ciliumnetworkpolicies.cilium.io              2022-10-11T01:06:10Z
ciliumnodes.cilium.io                        2022-10-11T01:06:10Z
```

3, install cilium v1.12.2 with custom cluster pool ipv4 CIDR `ipam.operator.clusterPoolIPv4PodCIDR="10.42.0.0/16"`

`[root@cilium-dev home]# cilium install --version=v1.12.2 --kube-proxy-replacement strict --helm-set-string=k8sServiceHost=10.3.72.239,k8sServicePort=6443,ipam.operator.clusterPoolIPv4PodCIDR="10.42.0.0/16"`

cilium operator has log below, presumably CRDs is updated and `clusterPoolIPv4PodCIDR` should be updated

```
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumIdentity/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumExternalWorkload/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumEndpoint/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumNode/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumIdentity/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumExternalWorkload/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumEndpoint/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNode/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s

level=info msg="attempting to acquire leader lease kube-system/cilium-operator-resource-lock..." subsys=klog
level=info msg="Leader re-election complete" newLeader=centos-dev.localdomain-BqjcifodOZ operatorID=centos-dev.localdomain-HySnLucjCa subsys=cilium-operator-generic
level=info msg="successfully acquired lease kube-system/cilium-operator-resource-lock" subsys=klog
level=info msg="Leading the operator HA deployment" subsys=cilium-operator-generic
level=info msg="Initializing IPAM" mode=cluster-pool subsys=cilium-operator-generic
```
**level=info msg="Starting ClusterPool IP allocator" ipv4CIDRs="[10.42.0.0/16]" ipv6CIDRs="[]" subsys=ipam-allocator-clusterpool**
```
level=info msg="Removing Cilium Node Taints or Setting Cilium Is Up Condition for Kubernetes Nodes" k8sNamespace=kube-system label-selector="k8s-app=cilium" remove-cilium-node-taints=true set-cilium-is-up-condition=true subsys=cilium-operator-generic

level=info msg="Starting to synchronize CiliumNode custom resources" subsys=cilium-operator-generic
level=info msg="Starting to garbage collect stale CiliumNode custom resources" subsys=watchers
level=info msg="Starting to garbage collect stale CiliumEndpoint custom resources" subsys=cilium-operator-generic
level=info msg="Starting CRD identity garbage collector" interval=15m0s subsys=cilium-operator-generic
level=info msg="CiliumNodes caches synced with Kubernetes" subsys=cilium-operator-generic
level=info msg="Starting CNP derivative handler" subsys=cilium-operator-generic
level=info msg="Starting CCNP derivative handler" subsys=cilium-operator-generic
level=info msg="Initialization complete" subsys=cilium-operator-generic
```
4, now deploy a new pod, presumably the new pod should get new pod CIDR ip within `"10.42.0.0/16"`

```
[root@cilium-dev home]# kubectl apply -f busybox-master.yaml 
deployment.apps/busybox-master created
[root@cilium-dev home]# kubectl get po -o wide
NAME                             READY   STATUS    RESTARTS   AGE    IP              NODE                     NOMINATED NODE   READINESS GATES
busybox-master-f97ff47c5-xxk86   1/1     Running   0          5s     10.0.0.121      cilium-dev               <none>           <none>
```
but the new pod still get pod ip from the first cilium install default pod CIDR `10.0.0.0/8` range, not `10.42.0.0/16` range.

this issue could be worked around by `cilium uninstall` and remove cilium CRDs manually `kubectl get crds | awk '{print $1;}' | xargs kubectl delete crd`

```
customresourcedefinition.apiextensions.k8s.io "ciliumclusterwidenetworkpolicies.cilium.io" deleted
customresourcedefinition.apiextensions.k8s.io "ciliumendpoints.cilium.io" deleted
customresourcedefinition.apiextensions.k8s.io "ciliumexternalworkloads.cilium.io" deleted
customresourcedefinition.apiextensions.k8s.io "ciliumidentities.cilium.io" deleted
customresourcedefinition.apiextensions.k8s.io "ciliumnetworkpolicies.cilium.io" deleted
customresourcedefinition.apiextensions.k8s.io "ciliumnodes.cilium.io" deleted
customresourcedefinition.apiextensions.k8s.io "tracingpolicies.cilium.io" deleted
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "NAME" not found
```
then install cilium again, note the ` Restarted unmanaged pod` occurs 

```
[root@cilium-dev home]# cilium install --version=v1.12.2 --kube-proxy-replacement strict --helm-set-string=k8sServiceHost=10.3.72.239,k8sServicePort=6443,ipam.operator.clusterPoolIPv4PodCIDR="10.42.0.0/16"
Flag --kube-proxy-replacement has been deprecated, This can now be overridden via `helm-set` (Helm value: `kubeProxyReplacement`).
ℹ️  Using Cilium version 1.12.2
🔮 Auto-detected cluster name: kubernetes
🔮 Auto-detected datapath mode: tunnel
🔮 Auto-detected kube-proxy has not been installed
ℹ️ Cilium will fully replace all functionalities of kube-proxy
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.12.2 --set cluster.id=0,cluster.name=kubernetes,encryption.nodeEncryption=false,ipam.operator.clusterPoolIPv4PodCIDR=10.42.0.0/16,k8sServiceHost=10.3.72.239,k8sServicePort=6443,kubeProxyReplacement=strict,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
ℹ️  Storing helm values file in kube-system/cilium-cli-helm-values Secret
🔑 Created CA in secret cilium-ca
🔑 Generating certificates for Hubble...
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium version 1.12.2...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed and ready...
♻️  Restarting unmanaged pods...
♻️  Restarted unmanaged pod default/busybox-master-f97ff47c5-xxk86
♻️  Restarted unmanaged pod default/deathstar-6f87496b94-2xff6
♻️  Restarted unmanaged pod default/deathstar-6f87496b94-9n5k8
♻️  Restarted unmanaged pod default/f5-hello-world-7bb546899-9tvc4
♻️  Restarted unmanaged pod kube-system/cis-34-5cd78f4f8-4csps
✅ Cilium was successfully installed! Run 'cilium status' to view installation health
```

so it looks we could improve cilium cli to remove CRDs when run `cilium uninstall`?  is there some hidden bug between cilium operator and k8s in regard to CRDs syncing? 

### Cilium Version

cilium 1.12.2

### Kernel Version

5.18

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment] 2022-10-11 01:38
by the way, this was found while helping user  in https://github.com/cilium/cilium/issues/21647

**Comment by xiaods** [comment] 2022-10-16 03:05
yes, this bug is always occurs in cilium-ctl tools.

**Comment by xiaods** [comment] 2022-10-16 03:43
with my testing, as above describe steps. the cilium core functional feature is ok. just cilium ctl tools behavior need a consistent way to handle the cidr ip range update case. I have raised the issue on cilium-cli repo. 
I think this isssue can close and moving to talk about this issue on cilium-cli repo

**Comment by xiaods** [comment] 2022-10-16 03:43
@vincentmli FYI

**Comment by vincentmli** [comment] 2022-10-16 15:16
> with my testing, as above describe steps. the cilium core functional feature is ok. just cilium ctl tools behavior need a consistent way to handle the cidr ip range update case. I have raised the issue on cilium-cli repo. I think this isssue can close and moving to talk about this issue on cilium-cli repo

Could you explain more in detail how cilium cli need a consistent way to handle the cidr ip range update

**Comment by xiaods** [comment] 2022-10-17 02:07
> > with my testing, as above describe steps. the cilium core functional feature is ok. just cilium ctl tools behavior need a consistent way to handle the cidr ip range update case. I have raised the issue on cilium-cli repo. I think this isssue can close and moving to talk about this issue on cilium-cli repo
> 
> Could you explain more in detail how cilium cli need a consistent way to handle the cidr ip range update

cilium cli uninstall behavior have not add a step to clean crd resource. it caused the CRD is not in sync with k8s

**Comment by xiaods** [comment] 2022-10-18 05:08
> > cilium cli uninstall behavior have not add a step to clean crd resource. it caused the CRD is not in sync with k8s
> 
> if CRDs include cluster pool cidr, and require sync between k8s and cilium agent and for some reason k8s and cilium agent not in sync, I view cilium cli uninstall to remove all CRDs as kind of workaround to resolve the issue, not the root cause.

yes, I double check your above steps on validate pod CIDR syncing issue. This error is a problem that is bound to occur. thanks for your clarify. it should be fix asap.

**Comment by aanm** [comment] 2022-11-08 16:39
@vincentmli the cilium cli uninstall does not remove all CRDs since they might lead to the removal of CiliumNetworkPolicies, which is might not be intended. Cilium does not allow changing podCIDR on existing clusters, you would have to reprovision all nodes that had the old CIDR in place.

**Comment by christarazi** [comment] 2022-12-15 05:01
@vincentmli To be clear, removing the CRDs will remove all objects created under those resources, like all CNPs, CiliumNodes, CEPs, etc. The issue is that there is leftover state in the CiliumNode object which contains the CIDR range for pods. The fix would be to, as @aanm mentioned, to delete that node (along with the CiliumNode) for it, and recreate with the new CIDR.

This is why uninstalling the CRDS resolves the issue, because it deletes all of the CiliumNodes.

**Comment by xiaods** [comment] 2023-02-15 14:03
any update on it?

**Comment by vincentmli** [comment] 2023-02-15 18:42
> any update on it?

from what I understand from above reply, this is work as intended, not an issue.

**Comment by christarazi** [comment] 2023-02-16 00:44
@vincentmli If there's nothing further needed on this issue, feel free to close it.

**Comment by xiaods** [comment] 2023-02-17 23:43
please close it. /close

**Closed as not planned** 2023-03-06 23:38 UTC
Labels: kind/bug, area/k8s, needs/triage, area/agent
