### ISSUE TITLE
Cilium stops the LB IP announcement during the kube-apiserver outage

### ISSUE THREAD

**Issue by 0xmeyer** [cilium/cilium#33755] opened 2024-07-12 05:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.15.6 or higher

### What happened?

We have several Kubernetes clusters running with Cilium as CNI and announcing LB IPs peer BGP. This works without a problem until the API servers can no longer be reached.

As soon as the Kubernetes API servers have an outage, e.g. due to a network problem and connectivity to the external etcd backend, the LB IPs are no longer announced to the peer via BGP.

### How it happened?

1. Install Cilium with Helm

    ```yaml
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: "true"
    ipv4NativeRoutingCIDR: 10.0.0.0/16
    k8sServiceHost: $APISERVER
    k8sServicePort: $PORT
    kubeProxyReplacement: strict
    loadBalancer:
      mode: dsr
    routingMode: native
    tunnel: disabled
    ```

2. Apply CR `CiliumBGPPeeringPolicy` and `CiliumLoadBalancerIPPool`
3. Configure the BGP peer (bird) and check BGP sessions
    ```
    bird> show protocols "dev_worker*"
    Name       Proto      Table      State  Since         Info
    dev_worker01 BGP        ---        up     2024-07-12 06:37:51  Established   
    dev_worker02 BGP        ---        up     2024-07-12 06:37:30  Established   %
    dev_worker03 BGP        ---        up     2024-07-12 06:37:01  Established
    ```
4. Outage of the Kubernetes API Server 
    ```bash
    mv /etc/kubernetes/manifests/kube-apiserver.yaml /tmp/kubernetes-manifests-bak/
    ```
    ```
    # logs cilium agent (as expected)
    ...
    time="2024-07-12T04:54:00Z" level=warning msg="/healthz returning unhealthy" error="1.15.7 (v1.15.7-de06bcfb)    Kubernetes service is not ready: Get \"https://$APISERVER:$PORT/version\": EOF" state=Failure subsys=daemon
    ...
    ```
    ```
    # cilium-agents will be restarted after 5min endlessly
    # bgp routes will not be announced
    bird> show protocols "dev_worker*"
    Name       Proto      Table      State  Since         Info
    dev_worker01 BGP        ---        start  2024-07-12 06:59:55  Active        Socket: Connection refused
    dev_worker02 BGP        ---        start  2024-07-12 06:59:28  Active        Socket: Connection refused
    dev_worker03 BGP        ---        start  2024-07-12 06:59:35  Active        Socket: Connection refused
    ```

5. Re-apply API server manifest
    ```bash
    mv /tmp/kubernetes-manifests-bak/kube-apiserver.yaml /etc/kubernetes/manifests/
    ```
    ```
    bird> show protocols "dev_worker*"
    Name       Proto      Table      State  Since         Info
    dev_worker01 BGP        ---        up     2024-07-12 07:04:18  Established   
    dev_worker02 BGP        ---        up     2024-07-12 07:05:37  Established   
    dev_worker03 BGP        ---        up     2024-07-12 07:05:02  Established
    ```

### Kernel Version

```bash
$ uname -r
6.1.0-22-amd64
```

### Kubernetes Version

```
$ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.9", GitCommit:"587f5fe8a69b0d15b578eaf478f009247d1c5d47", GitTreeState:"clean", BuildDate:"2024-04-16T14:59:08Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment] 2024-07-12 21:42
Hello, thanks for opening the GH issue, please provide a cilium sysdump as well. Thank you.

**Comment by 0xmeyer** [comment] 2024-07-14 07:15
Hello @aanm,

sysdump is attached.

best regards

[cilium-sysdump-20240714-091342.zip](https://github.com/user-attachments/files/16215901/cilium-sysdump-20240714-091342.zip)

**Comment by aanm** [comment] 2024-07-15 07:46
It's a duplicate of https://github.com/cilium/cilium/issues/31702. Feel free to subscribe to https://github.com/cilium/cilium/issues/31702 to receive updates once that issue is fixed. Thank you for creating the GH issue.

**Closed as not planned by aanm** 2024-07-15 07:46 UTC
Labels: kind/bug, needs/triage, kind/community-report
