### ISSUE TITLE
Fix `cni-install.sh`  and `cni-uninstall.sh`

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#7983] opened 2019-05-10 19:05 UTC
It seems whenever the cilium pod can't be initialized, for example starting it with an undefined flag, `kubectl get pods -o wide` will wrongly show `PostStartHookError` which can be misleading as that is not the reason why cilium pod can't initialize.
```
cilium-44jxn                       0/1     PostStartHookError: command '/cni-install.sh' exited with 126:    2          35s   10.200.0.3    a-wings-0-0m26   <none>           <none>
```

It might help triggering this bug by using the daemonset from 1.5.0 and using the latest cilium image from master

**Comment by tgraf** [comment] 2019-05-14 11:20
@aanm I tried to reproduce this:

```
minikube start --network-plugin=cni --memory=4096
wget https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.14/cilium-minikube.yaml
[ change image to :latest]
ks apply -f cilium-minikube.yaml
```

It came up fine:
```
cilium-bn7gl                       1/1     Running   0          115s
```

**Comment by tgraf** [comment] 2019-05-14 11:37
Checked offline with @aanm, can reproduce after adding unknown option to `args:`

```
cilium-7xqtq                       0/1     PostStartHookError: command '/cni-install.sh' exited with 137:    0          3s
```

postStart container is getting killed as main container exits. A change in 1.5 may have made this more likely but it's unlikely a net new problem.

**Comment by tgraf** [comment] 2019-08-05 16:22
This could be resolved by adding a sleep in the fatal.

**Comment by raybejjani** [comment] 2019-08-07 16:34
I've been trying to add the sleep. I'm not 100% sure that the sleep is triggering, but I'm just sleeping during init and exiting. I still can't seem to get it to do the right thing. I'll keep trying (maybe I'm blocking the cni-install script? I'll try an async kill next).

**Comment by tgraf** [comment] 2019-08-09 08:02
@raybejjani Is it that the sleep didn't help to expose the log?

**Comment by raybejjani** [comment] 2019-08-09 10:36
@tgraf yes. From what I could tell, I had the sleep but the error showing in the pod events was for cni-install (well, the `postStart` hook). I originally thought I was doing something wrong because I was passing in a bad cilium argument (the case I often see this with) but the options parsing happens before the logger is setup (so the fatal handler). Still, even bypassing that and just exiting cilium after a delay, nothing changes.
I wonder if there is one more call made to cilium-cni after the hook. That doesn't work because cilium-agent is down and that is the cause here. I'll chat with aanm some more.

**Closed as completed** 2019-08-12 16:10 UTC
Labels: kind/regression
