### ISSUE TITLE
CI: Privileged runtime failure: "context deadline exceeded"

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12381] opened 2020-07-02 10:50 UTC
## CI failure
```
	 START: loader_test.go:66: LoaderTestSuite.SetUpSuite
	 PASS: loader_test.go:66: LoaderTestSuite.SetUpSuite	0.001s
	 
	 START: loader_test.go:183: LoaderTestSuite.TestCompileAndLoadDefaultEndpoint
	 level=error msg="Command execution failed" cmd="[llc -march=bpf -mcpu=v1 -filetype=obj -o /tmp/cilium_429516104/bpf_lxc.o]" error="signal: killed" subsys=datapath-loader
	 level=error msg="Failed to compile bpf_lxc.o: Command execution failed for [llc -march=bpf -mcpu=v1 -filetype=obj -o /tmp/cilium_429516104/bpf_lxc.o]: context deadline exceeded" compiler-pid=20560 linker-pid=20561 subsys=datapath-loader
	 loader_test.go:184:
	     s.testCompileAndLoad(c, &ep)
	 loader_test.go:178:
	     c.Assert(err, IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"Failed to compile bpf_lxc.o: Command execution failed for [llc -march=bpf -mcpu=v1 -filetype=obj -o /tmp/cilium_429516104/bpf_lxc.o]: context deadline exceeded"} ("Failed to compile bpf_lxc.o: Command execution failed for [llc -march=bpf -mcpu=v1 -filetype=obj -o /tmp/cilium_429516104/bpf_lxc.o]: context deadline exceeded")
	 
	 START: loader_test.go:94: LoaderTestSuite.TearDownTest
	 PASS: loader_test.go:94: LoaderTestSuite.TearDownTest	0.000s
	 
	 FAIL: loader_test.go:183: LoaderTestSuite.TestCompileAndLoadDefaultEndpoint
```

PR https://github.com/cilium/cilium/pull/11528

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/1046/

[b8101752_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/4863704/b8101752_RuntimePrivilegedUnitTests_Run_Tests.zip)

**Comment by pchaigno** [comment] 2020-07-02 11:06
It's a duplicate of #11862.

**Closed as completed** 2020-07-02 11:08 UTC
Labels: area/CI, needs/triage, ci/flake
