### ISSUE TITLE
[FYI] Cilium not working on bottlerocket-v1.20

### ISSUE THREAD

**Issue by hubertbits** [cilium/cilium#32610] opened 2024-05-17 17:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Just letting you know so you may join the discussion over at https://github.com/bottlerocket-os/bottlerocket/issues/3968

Something in bottlerocket-v1.20 seems to have changed preventing using cilium for now. Worked in v1.19.5. Seems to be a netfilter/module load issue resulting in DNS resolving issues on node where coredns is running.

### Cilium Version

v1.14.9

### Kernel Version

bottlerocket-v1.20

### Kubernetes Version

v1.27.11-eks

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vigh-m** [comment] 2024-05-17 17:56
Too add more detail on this issue, Bottlerocket moved from `xz` compressed kernel modules to `gz` compression. From what I can tell, Cilium brings its own [modprobe](https://github.com/cilium/cilium/blob/a0825318517dac8c51d902823e34eda0281afbf0/images/runtime/install-runtime-deps.sh#L18) which is essentially Ubuntu 22.04's kmod which does not have gzip support

```
# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# apt-cache madison kmod
      kmod | 29-1ubuntu1 | http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages

# ldd /usr/sbin/modprobe
	linux-vdso.so.1 (0x00007ffcc07f7000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fb9dde40000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb9dde15000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fb9dd9d1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb9dd7a8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb9ddf3e000)
```

This breaks module loading for Cilium between Bottlerocket versions. 

Is it possible for Cilium to use the host OS’s modprobe when it exists vs always using their own?

**Comment by arthur1542** [comment] 2024-05-21 08:54
We have the same issue with Cilium 1.15.3

**Comment by maodahua** [comment] 2024-05-30 03:13
Same issue like https://github.com/cilium/cilium/issues/32616
I spend so many time to invegist, found the envoy node dns have issue. Then I see this issue, I think I found the root cause.

**Comment by obirhuppertz** [comment] 2024-06-07 10:22
@vigh-m just posted a temporary fix for the latest bottlerocket release v1.20.1 at https://github.com/bottlerocket-os/bottlerocket/issues/3968#issuecomment-2153547818 . Can confirm that adding the following lines to `values.yaml` fixes the module loading issue for now.

```
extraVolumeMounts:
  - name: kmod-static
    mountPath: /usr/local/sbin/modprobe
    readOnly: true
  - name: kernel-modules
    mountPath: /lib/modules/
    readOnly: true

extraVolumes:
  - name: kmod-static
    hostPath:
      path: /usr/bin/kmod
    type: File
  - name: kernel-modules
    hostPath:
      path: /lib/modules/
```

Maybe someone from cilium may track the issue over at bottlerocket? Its currently only a temp workaround and its said there will be a more permanent solution coming soon.

**Comment by project-administrator** [comment] 2024-06-07 11:40
@obirhuppertz We applied the fix, thanks for the hint! 
We had to roll all of our EKS k8s nodes to apply the change..
Unfortunately, if we do `curl` in a loop we are still failing about 5% of the requests with the following error:
```
GET /details/1 HTTP/1.1
Host: k8s-gwapites-ciliumga-xxxxxxxxx-yyyyyyyyyyyyy.elb.eu-west-2.amazonaws.com
User-Agent: curl/8.7.1
Accept: application/json, */*

* Request completely sent off
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Fri, 07 Jun 2024 11:34:37 GMT
server: envoy

curl: (22) The requested URL returned error: 503
upstream connect error or disconnect/reset before headers. reset reason: connection timeout
```
So, there is smth else missing I guess, not sure how to troubleshoot it further.

**Comment by ese** [comment] 2024-06-07 16:13
I applied @obirhuppertz fix in cilium helm and all my tests for our cilium ingresses worked fine with bottlerocket 1.20.1 and cilium 1.14.1

**Comment by obirhuppertz** [comment] 2024-06-14 10:26
Can confirm that latest bottlerocket-1.20.2 release the workaround is no longer possible and cilium is up and running again. For me the issue is fixed.

FYI @ese @arthur1542 

For reference:
Fixed PR in bottlerocket repo:  https://github.com/bottlerocket-os/bottlerocket/issues/3968

**Comment by obirhuppertz** [comment] 2024-06-19 14:59
Since 1.20.2 was released that fixes the issue i would like to close this issue if no one else has anything to add here.

**Comment by julianwiedmann** [comment] 2024-06-19 15:13
thank you for following up!

**Closed as completed by julianwiedmann** 2024-06-19 15:13 UTC
Labels: kind/bug, needs/triage, kind/community-report, area/agent
