### ISSUE TITLE
CrashLoopBackOff in node with GRE tunnel after upgrading from Cilium 1.7 to 1.8

### ISSUE THREAD

**Issue by Boca13** [cilium/cilium#13746] opened 2020-10-26 00:21 UTC
## Bug report

I'm having trouble with Cilium in one of the nodes of my cluster after upgrading from 1.7.x to 1.8.4 (using Kubespray). The special thing about this node is that it's connected to the rest of the node private network through a GRE tunnel. It worked well with Cilium 1.7.2 and Kubernetes 1.16.

**General Information**

- Cilium version:
```
Client: 1.8.4 17d623853 2020-09-30T17:31:44-07:00 go version go1.14.9 linux/amd64
Daemon: 1.8.4 17d623853 2020-09-30T17:31:44-07:00 go version go1.14.9 linux/amd64
```
- Kernel version: **5.4.0-52-generic**
- Orchestration system version in use: **Kubernetes 1.17.9 (previously 1.16)**
- Link to relevant artifacts (policies, deployments scripts, ...) -
- Generate and upload a system zip: (too big to be attached) [see](https://assets.libnamic.com/issues/cilium-sysdump-20201026-003033.zip)

**How to reproduce the issue**

1. Create a GRE tunnel to connect the faulty node to the private network where the rest of nodes are:
```
ip tunnel add tunnel0 remote x.x.x.x local y.y.y.y mode gre
ip link set tunnel0 up
ip addr add 172.16.128.101/20 dev tunnel0
ip route add 172.16.0.0/20 dev tunnel0
```
2. Update Kubernetes and Cilium (in my case, using Kubespray)

Result: Cilium works on all nodes but the one with the tunnel interface, where the pod (cilium-5jst9 in he dump) enters CrashLoopBackOff. Other cilium pods are restarted periodically due to a livingProbe failure (I think related to one failing), but networking works in those nodes. The failing cilium pod's log contains an error line that mentions the GRE tunnel interface on that server:
```
level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.233.70.246 <nil> vxlan enp35s0;tunnel0 <nil> <nil> 1500 false <nil> true true false /var/run/cilium/cgroupv2 /sys/fs/bpf true true v2 enp35s0=0xce2477a8;tunnel0=0x658010ac <nil> 32]" error="exit status 1" subsys=datapath-loader
```

Thank you.

**Comment by aanm** [comment] 2020-10-26 09:34
@Boca13 thanks for opening the issue, what's the output of `ip a s` from the node running `cilium-5jst9`?

**Comment by Boca13** [comment] 2020-10-26 13:39
Thank you for your reply, @aanm.
The output of `ip a s` is:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp35s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a8:a1:59:38:e6:3b brd ff:ff:ff:ff:ff:ff
    inet 168.119.36.206/32 scope global enp35s0
       valid_lft forever preferred_lft forever
    inet6 2a01:4f8:242:2317::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::aaa1:59ff:fe38:e63b/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:2b:c7:fc:7c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
5: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
8: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether b2:d7:b5:2c:12:52 brd ff:ff:ff:ff:ff:ff
    inet 169.254.25.10/32 brd 169.254.25.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
11: tunnel0@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1476 qdisc noqueue state UNKNOWN group default qlen 1000
    link/gre 168.119.36.206 peer 88.198.109.203
    inet 172.16.128.101/20 scope global tunnel0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:5efe:a877:24ce/64 scope link 
       valid_lft forever preferred_lft forever
18: lxcc49345b3acbd@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 8a:94:b6:e9:58:b8 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::8894:b6ff:fee9:58b8/64 scope link 
       valid_lft forever preferred_lft forever
24: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 3a:49:bd:92:d8:e4 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3849:bdff:fe92:d8e4/64 scope link 
       valid_lft forever preferred_lft forever
25: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 56:18:ae:c7:02:e0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5418:aeff:fec7:2e0/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by aanm** [comment] 2020-10-26 14:27
@Boca13 and `ip route show`?

**Comment by Boca13** [comment] 2020-10-26 15:13
```
root@dedicated-1 ~ # ip route show
default via x.x.x.x dev enp35s0 proto static onlink 
172.16.0.0/20 dev tunnel0 scope link 
172.16.128.0/20 dev tunnel0 proto kernel scope link src 172.16.128.101 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
```

**Comment by aanm** [comment] 2020-10-27 10:29
I did an initial triage to this issue. It seems `tunnel0` is being considered as part of the list of nodeport devices by the automatic discovery introduced in 1.8.

**Comment by Boca13** [comment] 2020-10-27 10:39
Thank you, @aanm, it seems so. I wonder if there's any parameter that I could change in the configmap to exclude or limit the list of devices to the pertinent interfaces.

Thank you again for your help.

**Comment by brb** [comment] 2020-10-30 13:27
The problem is that `tunnel0` doesn't have L2 addr:  You can set devices via `devices: ...` which will disable the auto-detection. Anyway, if you are using `tunnel0` to connect to other k8s nodes, then BPF NodePort won't work when accessed from outside (you might need to disable it).

Closing, as it is a duplicate of https://github.com/cilium/cilium/issues/12317.

**Closed as completed by brb** 2020-10-30 13:27 UTC
Labels: kind/bug
