### ISSUE TITLE
IPv6 packets falsely dropped; conntrack issue

### ISSUE THREAD

**Issue by jonasbadstuebner** [cilium/cilium#26886] opened 2023-07-18 08:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Set up cilium on a dual stack cluster
2. Enable firewall (`CiliumClusterwideNetworkPolicy`) with rules allowing http or ping access to external sources, but no explicit ingress rule
3. Watch dropped packages with the command I provided

On outgoing traffic the identity of the pod is resolved correctly. But on incoming traffic/the response to the outgoing traffic, the packets are dropped because the target identity can not be figured out.
If `::/0` is a explicitly allowed in the firewall, the traffic comes through though.
This seems like a problem with the conntrack table where the lookup of the conntrack table would be done after the traffic is let through, which it isn't because of the firewall setup. Therefore the packets are dropped, despite a conntrack entry existing.
I tried to find a hint in the code, but I am not familiar enough with this code base to give any specific information on that.

### Cilium Version

Client: 1.14.0-snapshot.4 6c8db759 2023-06-16T12:17:20-07:00 go version go1.20.5 linux/amd64
Daemon: 1.14.0-snapshot.4 6c8db759 2023-06-16T12:17:20-07:00 go version go1.20.5 linux/amd64

### Kernel Version

5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:24Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
# root@server:/home/cilium# cilium monitor --type drop | grep 2a06:98c1:3120::3
Listening for events on x CPUs with x of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK

# root@server:/home/cilium# cilium monitor --from 408 
Listening for events on x CPUs with x of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> stack flow 0xb26c28d7 , identity 3625->world state new ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
-> stack flow 0x31790a5b , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
-> stack flow 0x571bc5f7 , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
-> stack flow 0x5a1e7b5f , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
```

### Anything else?

`bpf_host.c:379` from the logs: https://github.com/cilium/cilium/blob/v1.14.0-snapshot.4/bpf/bpf_host.c#L378 I think

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DrBu7cher** [comment] 2023-07-18 08:53
With `::/0` allowed as `fromCIDR`:
```
# root@server:/home/cilium# cilium monitor --from 408
-> stack flow 0x5ed1a7f9 , identity 3625->world state new ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:43616 -> [2a06:98c1:3120::3]:80 tcp SYN
-> endpoint 408 flow 0x981deefc , identity world->3625 state reply ifindex lxc729085005591 orig-ip 2a06:98c1:3120::3: [2a06:98c1:3120::3]:80 -> [fdxx:ffxx:2xx1:xx::exxe]:43616 tcp SYN, ACK
-> stack flow 0x5ed1a7f9 , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:43616 -> [2a06:98c1:3120::3]:80 tcp AC
```

**Comment by DrBu7cher** [comment] 2023-07-18 09:21
As you can see above, the identity is resolved correctly and the traffic comes back to the pod if the firewall is allowing all IPv6 Ingress traffic, which is also true if there is no firewall in place at all.

**Comment by DrBu7cher** [comment] 2023-07-18 09:23
Only allowing the specific `2a06:98c1:3120::3/128` is enough too.

**Comment by aditighag** [comment] 2023-07-18 21:42
>But on incoming traffic/the response to the outgoing traffic, the packets are dropped because the target identity can not be figured out.

Your configured CiliumClusterwideNetworkPolicy allows ingress traffic only from `cluster` entities. Is this CIDR `2a06:98c1:3120::3/128` external to your cluster? See how the `cluster` entity is defined in the policy spec - https://docs.cilium.io/en/latest/security/policy/language/#entities-based.

**Comment by DrBu7cher** [comment] 2023-07-18 21:48
Thank you for your answer.
This IP is external to the cluster, but I'm pinging it from within. So the answer to this ping is supposed to be let through the firewall with no problems, since it is a connection established by a pod inside the cluster and therefore allowed.
Egress traffic is allowed to wherever.
If I ping/curl an IPv4 it works. The answer from the host gets through to the pod. But for IPv6 the statefulness of the firewall is broken.

**Comment by DrBu7cher** [comment] 2023-07-18 21:49
The dropped packages I showed in the logs are the answer from the external host to a ping issued from a pod within the cluster. They should be shoved through to the pod, not dropped.

**Comment by DrBu7cher** [comment] 2023-07-18 21:57
I updated the issue to show that it doesn't have to be this particular rule.

**Comment by Hayajiro** [comment] 2023-07-19 10:01
We can confirm this issue on Cilium 1.14.0-rc.1, but are experiencing the exact same behavior and log entries since 1.13.3. On 1.13.0 - 1.13.2, the issue is not present and IPv6 traffic works just fine. Perhaps it's related to  #24875?

**Comment by Hayajiro** [comment] 2023-07-19 14:42
Traced it back to the following commit: https://github.com/cilium/cilium/commit/d2301cbbf8672f1fb96421f5118c095a6c81d42e (https://github.com/cilium/cilium/commit/13719312269a2ea618f6a612abac5898a9c721f8 in 1.13)

**Comment by youngnick** [comment] 2023-07-24 01:50
Thanks for the detective work @Hayajiro, I'm marking this for datapath folks to check out.

**Comment by margamanterola** [comment] 2023-07-24 08:20
@pchaigno Apparently your PR #25024 is causing host fw to misbehave with IPv6. Could you take a look?

**Comment by Hayajiro** [comment] 2023-08-18 12:28
@margamanterola @pchaigno Any update on this? This is forcing us to stick with 1.12 for now (1.13.2 and earlier are not an option for us due to another bug) and I don't think my simple revert is the correct fix here.

**Comment by DrBu7cher** [comment] 2023-08-18 12:44
It is a shame that this has been open for so long and noone took a look as far as I can tell.
This is a show stopper and should get higher priority.

**Comment by Hayajiro** [comment] 2023-10-04 09:37
For the record: Just tested with v1.14.2 and the issue is still present.

**Comment by ti-mo** [comment] 2023-10-05 15:02
@DrBu7cher @Hayajiro Would you be able to provide a sysdump from an affected node? If you don't want to share the whole thing, that's fine, I'm only interested in `node_config.h` (don't censor the `DEFINE_IPV6()`, unfortunately this matters) and a bpf_lxc.o template (there should only be one per node).

We found an issue that breaks multiple areas of Cilium's v6 handling that should be fixed by this patch: https://github.com/cilium/cilium/pull/28417. Unfortunately, it only pops up on specific deployments with v6 addresses that fall within a specific range (so, depending on which prefix is assigned to you by your ISP/cloud), making this really tricky to reproduce. Naturally, we would've preferred to ship 1.14 without this bug, but due to the nature of it, this didn't blow up in CI.

If you can't build your own image, here's a 1.15-dev CI agent image that contains the patch: `quay.io/cilium/cilium-ci:0a28eb945e98a4729f5b580a28b5e346def975db`. If you have a non-critical cluster or test environment, you could give that a try. Note that you may need a Helm chart from the main branch, I haven't tested this with 1.14 charts.

If you could confirm whether or not this fixes your issue, that would allow us to track the impact this has caused. Thank you.

**Comment by Hayajiro** [comment] 2023-10-05 15:05
Hi @ti-mo, as I'e already mentioned in #27898, we are not affected by this bug. So this is a separate bug. We've already bisected it and are still waiting for it to be fixed - in the meantime we are using a patched build with the change mentioned a few comments above reverted. Maybe @pchaigno or @youngnick could chime in again?

**Comment by ti-mo** [comment] 2023-10-05 15:20
Okay, thanks for the quick turnaround. The first 4 bytes of the address don't matter. Things break if either the 5th or 13th byte of the router or host address are between `0x80` and `0xff`. So, `a:b:8000::`-`a:b:ff00::` or `::8000:c`-`::ff00:c`.

**Comment by DrBu7cher** [comment] 2023-10-10 17:34
@pchaigno Seems to not be aware of this issue, as he didn't contribute to the conversation yet and did not confirm he is on it.
Would it be possible to assign someone else? The problem is present for almost 3 months now without someone even checking how much work it would be to fix it.

**Comment by margamanterola** [comment] 2023-10-11 15:25
Paul is currently focused on other issues, so unassigning this.

**Comment by oblazek** [comment] 2023-10-25 06:36
got the same problem on 1.15-pre1, taking a look

**Comment by oblazek** [comment] 2023-10-26 06:16
found it folks.. @DrBu7cher can you tell if you are using `--install-iptables-rules=false` ? Because that's the reason of our troubles.. this code here https://github.com/cilium/cilium/blob/main/bpf/bpf_host.c#L462 doesn't work properly in our case because there are no iptables rules that would set that mark for traffic leaving host itself.

**Comment by Hayajiro** [comment] 2023-10-26 06:21
@oblazek I can't speak for him, but at least in our environments, I'm quite sure we're not using that option, but I'll double-check once I'm in the office (which should be within the next two hours).

**Comment by oblazek** [comment] 2023-10-26 10:32
@Hayajiro any update?

**Comment by polarroyo** [comment] 2023-10-26 11:57
> found it folks.. @DrBu7cher can you tell if you are using `--install-iptables-rules=false` ? Because that's the reason of our troubles.. this code here https://github.com/cilium/cilium/blob/main/bpf/bpf_host.c#L462 doesn't work properly in our case because there are no iptables rules that would set that mark for traffic leaving host itself.

I work with @DrBu7cher and I can confirm that we are not using `--install-iptables-rules=false`.

From cilium agent logs: `level=info msg="  --install-iptables-rules='true'" subsys=daemon`

In case it can be useful to replicate the issue, here are the `values.yaml` from our current cilium:
```
kubeProxyReplacement: strict
tunnel: "disabled"
k8sServiceHost: [REDACTED]
k8sServicePort: [REDACTED]
ipv4NativeRoutingCIDR: [REDACTED]
ipv6NativeRoutingCIDR: [REDACTED]
enableIPv6Masquerade: false
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
hostFirewall:
  enabled: true
ipam:
  mode: "kubernetes"
ipv6:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
```
Also, important note @oblazek, our traffic can leave the nodes with IPv6 but is dropped by on the way in because cilium loses the identity of that traffic and `hostFirewall` feature is dropping it.

**Comment by Hayajiro** [comment] 2023-10-26 11:59
@oblazek Sorry for the late response, I was busy with with a bunch of other tasks, so I only got to it now.

The same applies to us, according to the agent logs, that option is set to `true`.

**Comment by oblazek** [comment] 2023-10-26 12:07
> Also, important note @oblazek, our traffic can leave the nodes with IPv6 but is dropped by on the way in because cilium loses the identity of that traffic and hostFirewall feature is dropping it.

Yeah, we had exactly the same issue. SYN was sent out by the node and SYN/ACK was dropped.

**Comment by oblazek** [comment] 2023-10-26 12:09
can you guys verify, that on the affected  node you see something like `"-m", "comment", "--comment", "cilium: host->any mark as from host",` in `iptables -L -t filter` ?

**Comment by Hayajiro** [comment] 2023-10-26 12:14
```
12:13:16-m1: ~ # iptables -L -t filter | grep mark
MARK       all  --  anywhere             anywhere             /* cilium: host->any mark as from host */ MARK xset 0xc00/0xf00
```

**Comment by oblazek** [comment] 2023-10-26 12:24
can you also check what's in `cilium bpf ct list global | grep OUT | grep TCP | grep 2a0` ?

**Comment by Hayajiro** [comment] 2023-10-26 12:46
> can you also check what's in `cilium bpf ct list global | grep OUT | grep TCP | grep 2a0` ?

There are entries, and it looks pretty much exactly the same between my patched build of 1.14 (with working IPv6, using the revert etc) and upstream 1.14, where IPv6 is broken.

**Comment by oblazek** [comment] 2023-10-26 13:29
can you try capturing the debug output with `cilium monitor --related-to <epID> -v` (you have to enable `--debug` and `--debug-verbose=datapath`
you should see something like this:
```
<- network flow 0x0 , identity unknown->unknown state unknown ifindex eth0 orig-ip 0.0.0.0: [2a02:598:64::4636]:2379 -> [2a02:598:64::e30]:38906 tcp SYN, ACK
CPU 02: MARK 0x0 FROM 2547 DEBUG: Successfully mapped addr.p4=[::0:4636] to identity=10
CPU 02: MARK 0x0 FROM 2547 DEBUG: Successfully mapped addr.p4=[::0:e30] to identity=1
CPU 02: MARK 0x0 FROM 2547 DEBUG: Conntrack lookup 1/2: src=[::0:4636]:2379 dst=[::0:e30]:38906
CPU 02: MARK 0x0 FROM 2547 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0 dir=1 scope=2
CPU 02: MARK 0x0 FROM 2547 DEBUG: CT entry found lifetime=3726740, revnat=0
CPU 02: MARK 0x0 FROM 2547 DEBUG: CT verdict: Reply, revnat=0
```

**Comment by oblazek** [comment] 2023-10-26 13:32
there has to be something wrong with the ct lookup

**Comment by Hayajiro** [comment] 2023-10-26 14:20
@oblazek As we already debugged, we don't get the SYN ACK, same issue occurs with the debug monitor.

Additionally, we see the following in the log:
```
CPU 01: MARK 0x0 FROM 246 DEBUG: Successfully mapped addr.p4=[::0:1] to identity=2
CPU 01: MARK 0x0 FROM 246 DEBUG: Successfully mapped addr.p4=[::0:1] to identity=1
CPU 01: MARK 0x0 FROM 246 DEBUG: Conntrack lookup 1/2: src=[::0:1]:443 dst=[::0:1]:46600
CPU 01: MARK 0x0 FROM 246 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0 dir=1 scope=2
CPU 01: MARK 0x0 FROM 246 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x0 FROM 246 DEBUG: Successfully mapped addr.p4=[::0:1] to identity=2
CPU 01: MARK 0x0 FROM 246 DEBUG: Policy evaluation would deny packet from 2 to 1
Policy verdict log: flow 0x0 local EP ID 246, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, [EXTERNAL_IPV6::1]:443 -> [HOST_IPV6::1]:46600 tcp SYN, ACK
xx drop (Policy denied) flow 0x0 to endpoint 0, ifindex 2, file bpf_host.c:378, , identity world->unknown: [EXTERNAL_IPV6::1]:443 -> [HOST_IPV6::1]:46600 tcp SYN, ACK
```

939 would be the endpoint id of the pod making the request, 246 is the host endpoint id

**Comment by oblazek** [comment] 2023-10-27 09:20
I wonder if you could try https://github.com/cilium/cilium/pull/28813 .. just tried patching 1.14.3 and there was only a simple conflict in 1 line

**Comment by Hayajiro** [comment] 2023-10-27 10:24
@oblazek I'm somewhat busy right now, I'll see if I can have a look at this sometime in the afternoon

**Comment by Hayajiro** [comment] 2023-10-27 14:14
@oblazek I'm somewhat busy right now, I won't be able to get to this before Monday.

**Comment by oblazek** [comment] 2023-10-27 14:21
no worries, let me know then ;)

**Comment by Hayajiro** [comment] 2023-11-07 14:51
@oblazek Sorry again, after that busy week, I got hit with a pretty bad cold. Now that I'm back in office, I managed to test your changes just now in one of our test clusters, and IPv6 connectivity seems to be working just fine. I'll give it a more thorough test in the next days, but so far it looks promising.

I've backported your patch to 1.14.2 to make sure no other changes could affect the test.

**Comment by oblazek** [comment] 2023-11-15 08:12
> but so far it looks promising.

awesome to hear that.

@Hayajiro had to split the PR into two.. I don't think the current version of the PR will fix your issue (but the followup should), I will ping you when the second one is done..

**Closed as completed** 2023-11-24 06:43 UTC
Labels: kind/bug, area/datapath, needs/triage, kind/community-report, area/host-firewall, feature/ipv6
