### ISSUE TITLE
CI: Panic of closed channel

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16665] opened 2021-06-26 03:24 UTC
```
panic: close of closed channel
goroutine 74 [running]:
github.com/cilium/cilium/pkg/hubble/relay/pool.TestPeerManager.func19(0x4000055eb0, 0xe, 0x0, 0x0, 0x4000055e3c, 0x0, 0x0, 0x4000055ea0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager_test.go:585 +0x2c
github.com/cilium/cilium/pkg/hubble/relay/pool.FakeClientConnBuilder.ClientConn(0x400055b090, 0x4000055eb0, 0xe, 0x0, 0x0, 0x2716280, 0x4000077501, 0x9bfd4, 0x400004f278)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager_test.go:711 +0x50
github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).connect(0x40001cedc0, 0x4000166540, 0x17bf001)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:332 +0x324
github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).manageConnections.func1(0x40001cedc0, 0x4000166540)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:169 +0x80
created by github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).manageConnections
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:166 +0x720
FAIL	github.com/cilium/cilium/pkg/hubble/relay/pool	3.046s
FAIL
make: *** [Makefile:209: unit-tests] Error 1
```

full logs (arm64) https://travis-ci.com/github/cilium/cilium/jobs/519303160

**Comment by gandro** [comment] 2021-06-28 08:15
Might be worth treating this as a duplicate of https://github.com/cilium/cilium/issues/15442 - it's not exactly the same error, but very likely has the same root cause (test channel reference is leaked between tests somehow)

**Comment by rolinh** [comment] 2021-06-28 08:42
Agree with @gandro. It's interesting that these tests are almost a year old and they started flaking only recently.

**Closed as completed by rolinh** 2021-06-28 08:42 UTC
Labels: kind/bug, kind/duplicate, area/CI, ci/flake
