### ISSUE TITLE
k8s setup failure in CI test

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1339] opened 2017-08-18 13:03 UTC
```
12:25:19 ==> k8s1-build-PR-1337-1: Preparing to unpack .../kubernetes-cni_0.5.1-00_amd64.deb ...
12:25:19 ==> k8s1-build-PR-1337-1: Unpacking kubernetes-cni (0.5.1-00) ...
12:25:20 ==> k8s1-build-PR-1337-1: Selecting previously unselected package socat.
12:25:20 ==> k8s1-build-PR-1337-1: Preparing to unpack .../socat_1.7.3.1-1_amd64.deb ...
12:25:20 ==> k8s1-build-PR-1337-1: Unpacking socat (1.7.3.1-1) ...
12:25:21 ==> k8s1-build-PR-1337-1: Selecting previously unselected package kubelet.
12:25:21 ==> k8s1-build-PR-1337-1: Preparing to unpack .../kubelet_1.6.6-00_amd64.deb ...
12:25:21 ==> k8s1-build-PR-1337-1: Unpacking kubelet (1.6.6-00) ...
12:25:25 ==> k8s1-build-PR-1337-1: Selecting previously unselected package kubectl.
12:25:25 ==> k8s1-build-PR-1337-1: Preparing to unpack .../kubectl_1.6.6-00_amd64.deb ...
12:25:25 ==> k8s1-build-PR-1337-1: Unpacking kubectl (1.6.6-00) ...
12:25:27 ==> k8s1-build-PR-1337-1: Selecting previously unselected package kubeadm.
12:25:27 ==> k8s1-build-PR-1337-1: Preparing to unpack .../kubeadm_1.6.6-00_amd64.deb ...
12:25:27 ==> k8s1-build-PR-1337-1: Unpacking kubeadm (1.6.6-00) ...
12:25:29 ==> k8s1-build-PR-1337-1: Setting up kubernetes-cni (0.5.1-00) ...
12:25:29 ==> k8s1-build-PR-1337-1: Setting up socat (1.7.3.1-1) ...
12:25:29 ==> k8s1-build-PR-1337-1: Setting up kubelet (1.6.6-00) ...
12:25:30 ==> k8s1-build-PR-1337-1: Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service -> /lib/systemd/system/kubelet.service.
12:25:31 ==> k8s1-build-PR-1337-1: Setting up kubectl (1.6.6-00) ...
12:25:31 ==> k8s1-build-PR-1337-1: Processing triggers for man-db (2.7.5-1) ...
12:25:31 ==> k8s1-build-PR-1337-1: Setting up kubeadm (1.6.6-00) ...
12:25:37 ==> k8s1-build-PR-1337-1: [kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
12:25:37 ==> k8s1-build-PR-1337-1: [init] Using Kubernetes version: v1.6.6
12:25:37 ==> k8s1-build-PR-1337-1: [init] Using Authorization mode: RBAC
12:25:37 ==> k8s1-build-PR-1337-1: [preflight] Running pre-flight checks
12:25:37 ==> k8s1-build-PR-1337-1: [preflight] Some fatal errors occurred:
12:25:37 ==> k8s1-build-PR-1337-1: 	/var/lib/kubelet is not empty
12:25:37 ==> k8s1-build-PR-1337-1: [preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
12:25:37 ==> k8s1-build-PR-1337-1: cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
12:25:37 ==> k8s1-build-PR-1337-1: cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
12:25:37 ==> k8s1-build-PR-1337-1: chown: cannot access '/home/vagrant/.kube/config': No such file or directory
12:25:37 ==> k8s1-build-PR-1337-1: cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
12:25:37 ==> k8s1-build-PR-1337-1: cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
12:25:37 ==> k8s1-build-PR-1337-1: Waiting for healthy k8s cluster with 1 nodes
12:25:37 ==> k8s1-build-PR-1337-1: The connection to the server localhost:8080 was refused - did you specify the right host or port?
12:25:37 ==> k8s1-build-PR-1337-1: The connection to the server localhost:8080 was refused - did you specify the right host or port?
12:25:37 ==> k8s1-build-PR-1337-1: K8S Components ready: [0/3]
12:25:39 ==> k8s1-build-PR-1337-1: The connection to the server localhost:8080 was refused - did you specify the right host or port?
12:25:39 ==> k8s1-build-PR-1337-1: The connection to the server localhost:8080 was refused - did you specify the right host or port?
12:25:39 ==> k8s1-build-PR-1337-1: K8S Components ready: [0/3]
12:25:42 ==> k8s1-build-PR-1337-1: The connection to the server localhost:8080 was refused - did you specify the right host or port?
12:25:42 ==> k8s1-build-PR-1337-1: The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Example of faild CI run:
https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-1337/1/execution/node/29/log/

**Comment by aanm** [comment] 2017-08-18 13:57
Duplicate of https://github.com/cilium/cilium/issues/1279

**Closed as completed by aanm** 2017-08-18 13:57 UTC
Labels: kind/bug, priority/high
