### ISSUE TITLE
CI: K8sPolicyTest Namespaces policies Tests the same Policy in different namespaces

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15758] opened 2021-04-18 00:09 UTC
```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
"app3-5d69599cdd-5nl8m" can curl to "10.106.15.53"
Expected command: kubectl exec -n default app3-5d69599cdd-5nl8m -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.106.15.53/public -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '5.002925'
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/Policies.go:2013
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/236/testReport/junit/Suite-k8s-1/21/K8sPolicyTest_Namespaces_policies_Tests_the_same_Policy_in_different_namespaces/

[803966b4_K8sPolicyTest_Namespaces_policies_Tests_the_same_Policy_in_different_namespaces.zip](https://github.com/cilium/cilium/files/6330273/803966b4_K8sPolicyTest_Namespaces_policies_Tests_the_same_Policy_in_different_namespaces.zip)

**Comment by pchaigno** [comment] 2021-05-01 12:50
This is a duplicate of https://github.com/cilium/cilium/issues/15724.

**Closed as completed by pchaigno** 2021-05-01 12:50 UTC
Labels: kind/bug, ci/flake
