### ISSUE TITLE
Linux Conntrack table has UNREPLIED entries

### ISSUE THREAD

**Issue by epollia** [cilium/cilium#25229] opened 2023-05-02 13:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!

When we connection by nodeport to node with pod(pod lives on this node) , firewalld drop connection

`[Tue May  2 10:50:57 2023] STATE_INVALID_DROP: IN=eth0 OUT=cilium_host MAC=fa:16:3e:ed:88:8f:fa:16:3e:8d:f6:86:08:00 SRC=172.18.200.4 DST=10.142.0.58 LEN=52 TOS=0x00 PREC=0x00 TTL=58 ID=38511 DF PROTO=TCP SPT=43924 DPT=80 WINDOW=502 RES=0x00 ACK URGP=0 `

Cilium configuration

```
kubectl -n kube-system get configmaps cilium-config -o yaml
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  annotate-k8s-node: "true"
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.142.0.0/18
  cluster-pool-ipv4-mask-size: "24"
  conntrack-gc-interval: 5s
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-hubble-open-metrics: "false"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-sctp: "false"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-metrics: dns drop tcp flow icmp http port-distribution
  hubble-metrics-server: :9965
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: vxlan
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
kind: ConfigMap

```

Pods
```
kubectl -n ingress-nginx get po -o wide
NAME                                                              READY   STATUS      RESTARTS   AGE    IP              
internal-only-ingress-nginx-controller-748b456fc7-6tcrn           1/1     Running     0          13d    10.142.0.58     
internal-only-ingress-nginx-controller-748b456fc7-9r6zg           1/1     Running     0          11d    10.142.12.98    
internal-only-ingress-nginx-controller-748b456fc7-m2zsw           1/1     Running     0          4d9h   10.142.1.247    
internal-only-ingress-nginx-defaultbackend-7c68f66dfb-8jgqf       1/1     Running     0          78d    10.142.12.220   
```

SVC
```
NAME                                     TYPE             CLUSTER-IP      EXTERNAL-IP                         PORT(S)                      AGE
internal-only-ingress-nginx-controller   LoadBalancer   10.142.65.171   10.200.145.124.k8s.lcl   80:30244/TCP,443:30021/TCP   158d
```

Dump from node
```
08:31:13.926406 eth0  In  IP 172.18.4.7.49830 > 10.200.144.135.30244: Flags [S], seq 1958641177, win 65280, options [mss 1330,sackOK,TS val 2868617995 ecr 0,nop,wscale 7], length 0
08:31:13.926488 lxc9101806650fa Out IP 172.18.4.7.49830 > 10.142.0.58.http: Flags [S], seq 1958641177, win 65280, options [mss 1330,sackOK,TS val 2868617995 ecr 0,nop,wscale 7], length 0
08:31:13.926525 lxc9101806650fa In  IP 10.142.0.58.http > 172.18.4.7.49830: Flags [S.], seq 214818403, ack 1958641178, win 64308, options [mss 1410,sackOK,TS val 1315840436 ecr 2868617995,nop,wscale 7], length 0
08:31:13.926537 eth0  Out IP 10.200.144.135.30244 > 172.18.4.7.49830: Flags [S.], seq 214818403, ack 1958641178, win 64308, options [mss 1410,sackOK,TS val 1315840436 ecr 2868617995,nop,wscale 7], length 0
08:31:14.006565 eth0  In  IP 172.18.4.7.49830 > 10.200.144.135.30244: Flags [.], ack 1, win 510, options [nop,nop,TS val 2868618075 ecr 1315840436], length 0
08:31:14.006565 eth0  In  IP 172.18.4.7.49830 > 10.200.144.135.30244: Flags [P.], seq 1:6, ack 1, win 510, options [nop,nop,TS val 2868618075 ecr 1315840436], length 5
08:31:14.016832 eth0  In  IP 172.18.4.7.49830 > 10.200.144.135.30244: Flags [F.], seq 6, ack 1, win 510, options [nop,nop,TS val 2868618075 ecr 1315840436], length 0
08:31:14.172949 eth0  In  IP 172.18.4.7.49830 > 10.200.144.135.30244: Flags [F.], seq 6, ack 1, win 510, options [nop,nop,TS val 2868618241 ecr 1315840436], length 0
08:31:14.459442 eth0  In  IP 172.18.4.7.49830 > 10.200.144.135.30244: Flags [FP.], seq 1:6, ack 1, win 510, options [nop,nop,TS val 2868618528 ecr 1315840436], length 5
```

Connatrack table on linux node
```
conntrack -L -s 172.18.4.7
tcp      6 119 SYN_SENT src=172.18.4.7 dst=10.142.0.58 sport=54414 dport=80 [UNREPLIED] src=10.142.0.58 dst=172.18.4.7 sport=80 dport=54414 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1
conntrack v1.4.6 (conntrack-tools): 1 flow entries have been shown.
```

### Cilium Version

1.13.2

### Kernel Version

6.0.7-301

### Kubernetes Version

v1.24.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2023-05-05 22:30
You might experience some change to this with `enable-endpoint-routes` since that is more likely to make the paths symmetric for different directions.

In general though I'm not sure exactly what it achieves to have firewalld enforce policies on the cilium_host device, since Cilium enforces network policies for Pods already and the cilium_host device is an internal detail of Cilium's implementation.

**Comment by ti-mo** [comment] 2023-06-21 09:03
About the unreplied conntrack messages specifically, this is sort of expected behavior. I think this has been discussed on and off, but iirc we currently don't install NOTRACK rules for every path a packet could take to avoid it ending up in the host's conntrack table. The result is a bunch of unreplied flows. I'll close this with a reference to https://github.com/cilium/cilium/issues/12879 in case others land here with the same question.

**Closed as completed** 2023-06-21 09:03 UTC
Labels: kind/bug, needs/triage, kind/community-report
