### ISSUE TITLE
Cilium status is missing host reachable services status

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14927] opened 2021-02-10 16:57 UTC
I can't find the status of host-reachable-services in the cilium status.

```
# cilium status --verbose
...
KubeProxyReplacement Details:
  Status:             Partial
  Session Affinity:   Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled
  - LoadBalancer:   Disabled
  - externalIPs:    Disabled
  - HostPort:       Disabled
...
```

Should it be visible in this section?

**Comment by gaurang2001** [comment] 2021-03-13 21:17
Can I take this up?

**Comment by pchaigno** [comment] 2021-03-13 22:41
@gaurang2001 I assigned you. Don't hesitate to reach out on Slack (#gsoc or #development) if you have any question.

**Comment by brb** [comment] 2021-03-14 05:54
@gaurang2001 @pchaigno The issue is going to be resolved by #14977.

**Comment by pchaigno** [comment] 2021-03-14 09:12
@brb AFAICS, there's still nothing shown if host-reachable services are disabled. Should we explicitly state it's disabled as we do for others?

**Comment by brb** [comment] 2021-03-14 17:05
The suggestion to include a dedicated field to indicate enabled/disabled was nack'd, please see https://github.com/cilium/cilium/pull/14977#discussion_r576650522.

**Comment by pchaigno** [comment] 2021-03-15 10:08
I've removed the `good-first-issue` label until we resolve this.

> The suggestion to include a dedicated field to indicate enabled/disabled was nack'd, please see #14977 (comment).

I've read the discussion at https://github.com/cilium/cilium/pull/14977#discussion_r576650522, but I don't think the new status quo makes sense.
- AFAICS, socket-level load balancing is the only subfeature of our kube-proxy replacement whose disabled status isn't explicit. When e.g. `Session Affinity` is disabled, we don't hide the line. I think that inconsistency is confusing.
- I don't see drawbacks to changing the line to `Socket LB Protocols:   TCP, UDP` or `Socket LB Protocols:   None` depending on the status (we could also drop `Protocol`). We only print it in verbose mode, so verbosity isn't really an issue.

/cc @borkmann

**Comment by borkmann** [comment] 2021-03-15 13:55
> I've removed the `good-first-issue` label until we resolve this.
> 
> > The suggestion to include a dedicated field to indicate enabled/disabled was nack'd, please see #14977 (comment).
> 
> I've read the discussion at [#14977 (comment)](https://github.com/cilium/cilium/pull/14977#discussion_r576650522), but I don't think the new status quo makes sense.
> 
> * AFAICS, socket-level load balancing is the only subfeature of our kube-proxy replacement whose disabled status isn't explicit. When e.g. `Session Affinity` is disabled, we don't hide the line. I think that inconsistency is confusing.
> * I don't see drawbacks to changing the line to `Socket LB Protocols:   TCP, UDP` or `Socket LB Protocols:   None` depending on the status (we could also drop `Protocol`). We only print it in verbose mode, so verbosity isn't really an issue.
> 
> /cc @borkmann

My $0.02 I think it was fine as it was before, given for `strict` and `disabled`, the situation is very clear. I actually think for that case, it could be moved back to its original output, fwiw.

The `partial` corner case is the only one that is interesting since there we would want to know whether socket LB is involved or not. For example, only in partial case we could state:

- `Protocols:   TCP, UDP`
- `Socket Acceleration: TCP`

Wdyt?

**Comment by pchaigno** [comment] 2021-03-15 14:38
> My $0.02 I think it was fine as it was before, given for strict and disabled, the situation is very clear.

Because you know that socket-level LB is included in the kube-proxy replacement and everything is disabled (resp. enabled) when `kubeProxyReplacement` is set to `disabled` (resp. `strict`). Unfortunately, I don't think everyone knows that. Even some Cilium contributors don't know that socket-level LB is part of our kube-proxy replacement. The fact that it's not listed when disabled doesn't help here.

I'm not sure I understand why you're so keen to save one output line for socket-level LB. Why are `Session Affinity` or `NodePort` treated differently?

**Comment by christarazi** [comment] 2021-03-17 22:26
Just to synchronize the different threads of discussion around this. On March 17, it was decided to create a CFP around this: https://docs.google.com/document/d/1IZZ-FTM_U3zN06-M_mDOgep_DcDM0Oe3YOFVM1BTIt8/edit#heading=h.xjrodg7ovb1b

**Comment by borkmann** [comment] 2021-09-30 10:08
Closing as this should be resolved already.

**Closed as completed by borkmann** 2021-09-30 10:08 UTC
Labels: kind/bug, pinned
