### ISSUE TITLE
CI: K8sHealthTest checks cilium-health status between nodes

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10345] opened 2020-02-26 14:49 UTC
## CI failure

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:384
Cilium cannot be installed
Expected
    <*errors.errorString | 0xc00027ac60>: {
        s: "Failed to exec \"ip -j a s  | jq -r '.[] | select(.addr_info[] | .local == \\\"192.168.36.11\\\") | .ifname'\" cmd on \"k8s1\" node",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/assertionHelpers.go:99
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17497/testReport/junit/Suite-k8s-1/11/K8sHealthTest_checks_cilium_health_status_between_nodes/

[c9761207_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/4256336/c9761207_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by brb** [comment] 2020-02-26 14:52
Another instance of https://github.com/cilium/cilium/issues/10277.

**Comment by aanm** [comment] 2020-02-26 14:53
Please leave it open so people find it by the test title

**Comment by brb** [comment] 2020-02-26 14:54
People should search by the error msg which is not related to the suite.

**Comment by aanm** [comment] 2020-02-26 15:22
There is another GH issue with this same title but different reason.

**Comment by joestringer** [comment] 2020-02-26 18:29
@aanm do you think there is a different cause here?

Looking at the failure message, even though the test is different, this particular failure looks the same as #10277.

In the past, I have linked this issue to the original report and then closed and added the `kind/duplicate` label to issues like this if there is a strong likelihood that they're the same issue. Maybe it's a little easier for developers to find issues like this if the issue is open, but it's also more annoying to make sure all the relevant issues are closed when it gets fixed; I feel like in this case it's probably worth adding the test name into the other issue just so that developers can find that issue via the test name as well.

**Comment by aanm** [comment] 2020-02-26 18:48
>I feel like in this case it's probably worth adding the test name into the other issue just so that developers can find that issue via the test name as well.

That would be perfect!

**Comment by joestringer** [comment] 2020-02-26 18:54
Done, closing. If you find this issue, please refer to #10277 for latest status.

**Closed as completed by joestringer** 2020-02-26 18:54 UTC
Labels: kind/duplicate, area/CI
