### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with vxlan Tests with secondary NodePort devices

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#13275] opened 2020-09-24 07:52 UTC
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.36.11:32519" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-fcmsl -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:32519 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000023()', Connect: '0.000000',Transfer '0.000000', total '5.000407'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:559
```
[72fba333_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/5274350/72fba333_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device.zip)

**Comment by jrajahalme** [comment] 2020-12-10 16:08
Same failure here, but with K8s 1.13 & netnext: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/119/testReport/junit/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device/

```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.37.11:32710" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-4hn8j -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.37.11:32710 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 7 
Err: exit status 7
Stdout:
 	 time-> DNS: '0.000024()', Connect: '0.000000',Transfer '0.000000', total '0.000126'
Stderr:
 	 command terminated with exit code 7
```

**Comment by brb** [comment] 2021-01-14 05:39
This is a duplicate of #12511.

**Closed as completed by brb** 2021-01-14 05:39 UTC
Labels: area/CI, ci/flake
