### ISSUE TITLE
Remove attached bpf_sock.o when doing cilium cleanup

### ISSUE THREAD

**Issue by brb** [cilium/cilium#10067] opened 2020-02-05 15:38 UTC
`bpf/init.sh` (grep for `bpf_load_cgroup`) might attach (depending on a configuration) BPF programs to the root cgroup.

`cilium cleanup` should detect and remove those programs.

**Comment by aanm** [comment] 2020-02-07 16:38
@brb should we consider this a blocker for 1.7?

**Comment by brb** [comment] 2020-02-07 17:40
> should we consider this a blocker for 1.7?
IMHO noup, as bpf_sock programs are unloaded by cilium-agent during bootstrap when a user disables the host-reachable services feature.

**Comment by brandshaide** [comment] 2020-06-26 14:44
@brb I'd like to work on this, can you assign me? Thanks.

**Comment by borkmann** [comment] 2020-07-07 20:33
(The same/similar cleanup would be needed for XDP side.)

**Comment by borkmann** [comment] 2020-07-07 20:35
@brandshaide Do you have a rough ETA for when you plan to work on it? Thx

**Comment by brandshaide** [comment] 2020-07-08 11:26
@borkmann i planned to start on this the next week (13.07. - ...) , would that be OK...?

**Comment by borkmann** [comment] 2020-07-08 12:23
> @borkmann i planned to start on this the next week (13.07. - ...) , would that be OK...?

Sounds good thanks!

**Comment by borkmann** [comment] 2020-09-04 09:08
> @borkmann i planned to start on this the next week (13.07. - ...) , would that be OK...?

Hello @brandshaide, just wondering was there any progress on this since July? Thanks

**Comment by brandshaide** [comment] 2020-09-07 07:33
> Hello @brandshaide, just wondering was there any progress on this since July? Thanks

Hi, @borkmann I've already put something togehter, but due to day-job and some personal stuff I won't be able to get this finished anytime soon. Very sorry for that 😞 ! You might want to unassign me from this, so it's not kinda blocked anymore. sorry again!

**Comment by elfadel** [comment] 2020-12-07 09:48
Hi @borkmann, I would like to work on this issue. Could you assign it to me? Thanks.

**Comment by pchaigno** [comment] 2021-02-03 14:36
Hey @elfadel :wave: Did you find time to work on this? Do you need any help/pointers?

**Comment by elfadel** [comment] 2021-02-03 15:08
Hi @pchaigno, I send message about that to @borkmann since mid december. Just transfer you the message on cilium slack. Not sure, maybe I am missing something here

**Comment by elfadel** [comment] 2021-02-21 10:23
It seems there is no real issue with this issue.

The “issue” could be reproduced/checked by using two cmds: `sudo bpftool cgroup show` or `sudo bpftool cgroup tree`.
Let first consider the `sudo bpftool cgroup show` cmd.

The default cgroup root location is set to `/var/run/cilium/cgroupv2`.

First, check that bpf_sock progs are attached. Make sure cilium is installed and correctly set up.

`sudo bpftool cgroup show /var/run/cilium/cgroupv2`
> ID       AttachType      AttachFlags     Name           
1538     connect4                                       
1534     connect6                                       
1540     sendmsg4                                       
1536     sendmsg6                                       
1541     recvmsg4                                       
1537     recvmsg6                                       
1539     getpeername4                                   
1535     getpeername6

Now, clean up. You should stop the cilium daemon first.
`sudo systemctl stop cilium`
`sudo cilium cleanup`

Finally, check again if there are always attached bpf_sock progs to the root cgroup.
`sudo bpftool cgroup show /var/run/cilium/cgroupv2`
> Error: can't open cgroup /var/run/cilium/cgroupv2

Normal output. Indeed, the cleanup unmounts and deletes the cgroupv2 directory. It also deletes the /var/run/cilium by the way.
However, if we issue the `sudo bpftool cgroup tree` cmd, we get the following output (cut):
> CgroupPath
ID       AttachType      AttachFlags     Name           
/sys/fs/cgroup/unified
1538     connect4                                       
1534     connect6                                       
1540     sendmsg4                                       
1536     sendmsg6                                       
1541     recvmsg4                                       
1537     recvmsg6                                       
1539     getpeername4                                   
1535     getpeername6  
…

The bpf_sock progs are not attached only to the default cilium cgroup root (i.e. /var/run/cilium/cgroupv2) but also to the /sys/fs/cgroup/unified 

So we have three alternatives to fix and close this “issue”:
1. Ignore and close it
2. Detach the bpf_sock progs from the /sys/fs/cgroup/unified during cleaning in cleanup.go (it looks a hard-coded solution IMO)
3. Others???

@pchaigno @borkmann your opinion.

Knows issues: 
- sudo bpftool prog will not work with the default kernel built-in vagrant VM. Unless you build the vagrant VM with net-next kernel.
- sudo bpftool net can print only attached tc and xdp programs. It can not print attached sock_ops programs.

**Comment by pchaigno** [comment] 2021-02-22 10:14
> Detach the bpf_sock progs from the /sys/fs/cgroup/unified during cleaning in cleanup.go (it looks a hard-coded solution IMO)

I think we should do that :point_up:

**Comment by brb** [comment] 2021-02-22 10:16
@elfadel

> The bpf_sock progs are not attached only to the default cilium cgroup root (i.e. /var/run/cilium/cgroupv2) but also to the /sys/fs/cgroup/unified

https://github.com/cilium/cilium/pull/14951/files will complicate it even more - the same cgroup program will be attached to multiple cgroups.

We could set a name for each program (as suggested by @qmo and @pchaigno) prefixed with `cilium_`, and then upon `cilium cleanup` consider only programs with the `cilium_` prefix.

**Comment by brb** [comment] 2021-02-22 10:22
> > Detach the bpf_sock progs from the /sys/fs/cgroup/unified during cleaning in cleanup.go (it looks a hard-coded solution IMO)

> I think we should do that point_up

I think it's no longer viable solution because of #14951. Also, we don't want to detach programs installed by non-Cilium agents.

**Comment by johngv2** [comment] 2021-04-19 17:01
Hi @brb, I'm planning to work on this issue. The thread gave me a good understand. Planing to raise the pr soon.

**Comment by johngv2** [comment] 2021-06-23 15:44
> We could set a name for each program (as suggested by @qmo and @pchaigno) prefixed with cilium_, and then upon cilium cleanup consider only programs with the cilium_ prefix.

Hey Folks, I'm having problems trying to implement this suggestion (very appropriated, btw) and I would like to discuss about the options we have. 

1. It's seems not possible to use `iproute2` tools to assign names to bpf programs (feature not implemented so far).
2. `bpftool` uses the function names (from symbol table) to identify the bpf programs, thus we need to change some func names in bpf_sock.c (including the common prefix). E.g.: `int sock4_connect(struct bpf_sock_addr *ctx)` can be declared as `int cilium_sock4_connect(struct bpf_sock_addr *ctx)`.
2.1 The bpf syscall limits the size of program names to 16 chars, so well explained constructions like the one above will be automatically truncated by `bpftool`. Even so, we can use short names like `cilium_connect4`, `cilium_getpeer4`.
2.2 `bpftool` relies on BTF to properly create map-in-maps, but for now (since we mostly use `iproute2`) none of the map-in-maps are using BTF-like definitions. We have to include them.
2.3 As a test, I was able to use `bpftool` on `init.sh`, but only after substantial changes.

I thought of other options besides the common prefix name: how about keeping the progs pinned and identify them the same way as the maps? Or, on cleanup function, enumerate all programs that are using any cilium map (can I assume that all those progs belongs to cilium?).

I appreciate any suggestion ;)

**Comment by pchaigno** [comment] 2021-09-08 11:35
Hey @johngv2 :wave: Sorry for the delay.

> It's seems not possible to use `iproute2` tools to assign names to bpf programs (feature not implemented so far).

We are now using a newer iproute2 version. Maybe it supports setting names now? If not, we could add that support.

>     2\. `bpftool` uses the function names (from symbol table) to identify the bpf programs, thus we need to change some func names in bpf_sock.c (including the common prefix).

`bpftool` is only used to load the sockops programs, right? We can explicitly set the BPF program types when we load, with `bpftool prog load OBJ PATH type TYPE`.

>  2.3 As a test, I was able to use `bpftool` on `init.sh`, but only after substantial changes.

That's not the direction we want to take in the long term. We've transitioned to a newer iproute2 version with libbpf support, are going to move the map definitions to the libbpf format at some point, and the longer term is to use cilium/ebpf.

**Comment by johngv2** [comment] 2021-10-30 23:39
Hey folks, so sorry for the delay. 
I'm gonna check the current version of iproute2. I'll be back here in few days. Thanks so much!

**Comment by johngv2** [comment] 2021-12-01 11:05
Folks, sorry taking too much time to solve this. I'll have to unassign me :/

**Comment by YutaroHayakawa** [comment] 2022-01-21 07:36
I assigned myself to this issue. Let me first catch up. If I understand correctly, there are two problems discussed in this issue.

**1. Multiple cgroup BPF programs can be attached to the same cgroup root**

The latest state of the KPR and cgroup is summarized in [here](https://github.com/cilium/cilium/pull/16259). According to that, the cilium init container always attaches the cgroup programs to the root of the host cgroup ns (by nsenter'ing to it). Thus, at least in the cgroup v2 only environment, the problem of multiple cgroup programs won't happen anymore. 

**2. How to make sure the programs are attached by cilium**

The only solution suggested here is to prefix the BPF programs with `cilium_`.

For 1. I'm wondering if we still need to take care of this problem or not. If I understand correctly, the problem is still there in cgroup v1 environment. Should we consider such an environment? @brb @pchaigno 

For 2. I +1 to `cilium_` prefix. If there's no objection, I'll go with this plan.

**Comment by pchaigno** [comment] 2022-01-26 08:51
If we can identify the Cilium BPF programs by their name, we won't need to consider the cgroup attachment points, no?

**Comment by YutaroHayakawa** [comment] 2022-01-28 12:48
Yep, I think it works. I tried prefixing the program name and found we exceed the BPF_OBJ_NAME_LEN limit :(

It's just a cosmetic issue I believe but looks bad...

```
root@kpr-control-plane:/home/cilium# bpftool cgroup tree | grep cilium
251739   connect4                        cilium_sock4_co
251699   connect6                        cilium_sock6_co
251755   post_bind4                      cilium_sock4_po
251715   post_bind6                      cilium_sock6_po
251763   sendmsg4                        cilium_sock4_se
251723   sendmsg6                        cilium_sock6_se
251767   recvmsg4                        cilium_sock4_re
251731   recvmsg6                        cilium_sock6_re
251747   getpeername4                    cilium_sock4_ge
251707   getpeername6                    cilium_sock6_ge
```

**Comment by pchaigno** [comment] 2022-01-28 15:21
Ah, right. I noticed that as well for our tc programs. Maybe using something shorter like `cil_` would be good enough?

**Comment by YutaroHayakawa** [comment] 2022-01-31 04:49
Yep, I think that shold be enough.

**Comment by brb** [comment] 2023-02-22 10:38
@markpash are you still on it? If not, let's unassign the issue.

**Comment by rgo3** [comment] 2023-03-01 09:21
@brb once we land #23557  `cilium cleanup` could leverage `Disable()` in the `socketlb` pkg to detach all socketlb progs

**Closed as completed** 2023-05-10 11:48 UTC
Labels: help-wanted, good-first-issue, area/datapath, kind/feature
