### ISSUE TITLE
CI: ConformanceAKS: echo-ingress-l7-named-port succeeded while it should have failed

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#23929] opened 2023-02-22 08:15 UTC
## CI failure

```
[=] Test [echo-ingress-l7-named-port]
..
  ℹ️  📜 Applying CiliumNetworkPolicy 'echo-ingress-l7-http-named-port' to namespace 'cilium-test'..
  [-] Scenario [echo-ingress-l7-named-port/pod-to-pod-with-endpoints]
  [.] Action [echo-ingress-l7-named-port/pod-to-pod-with-endpoints/curl-0-public: cilium-test/client-755fb678bd-v56hq (10.0.0.130) -> curl-0-public (10.0.0.49:8080)]
  [.] Action [echo-ingress-l7-named-port/pod-to-pod-with-endpoints/curl-0-private: cilium-test/client-755fb678bd-v56hq (10.0.0.130) -> curl-0-private (10.0.0.49:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 5 --max-time 20 http://10.0.0.49:8080/private" succeeded while it should have failed: 
  ℹ️  curl output:
  
  
  📄 No flows recorded during action curl-0-private
  📄 No flows recorded during action curl-0-private
```

**Comment by pchaigno** [comment] 2023-02-22 11:33
Duplicate of https://github.com/cilium/cilium/issues/22162.

**Closed as completed by pchaigno** 2023-02-22 11:33 UTC
Labels: area/CI, ci/flake
