### ISSUE TITLE
 cilium-node-init CrashLoopBackOff when running on Bottlerocket OS

### ISSUE THREAD

**Issue by mmochan** [cilium/cilium#15393] opened 2021-03-19 02:54 UTC
## Bug report

**General Information**

- Cilium version
```
Client: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
Daemon: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
```
- EKS Cluster version
```
v1.18.9
``` 

- Kernel version
```
Bottlerocket OS
Linux ip-10-95-107-127.ap-southeast-2.compute.internal 5.4.95 #1 SMP Wed Mar 17 19:08:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

AMI:  bottlerocket-aws-k8s-1.18-x86_64-v1.0.7-099d3398
```

- Orchestration system version in use 
```
kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
cilium-node-init logs

│nsenter: failed to execute bash: No such file or directory                                                                                                                                                               
!!! startup-script failed! exit code '127'                                                                                                                                                                                 
stream closed
```

**How to reproduce the issue**

1. Deployed Cilium 1.9.5 with the following configuration
```
cni.chainingMode=aws-cni
masquerade=false
tunnel=disabled
nodeinit.enabled=true
hubble.relay.enabled=true
hubble.listenAddress=:4244
hubble.ui.enabled=true
```
2. Added a worker node ( Autoscaling group / Launch Template with Bottlerocket AMI )
3. cilium-operator pod starts successfully
4. cilium pod start successfully
5. cilium-node-init fails with
```
nsenter: failed to execute bash: No such file or directory                                                                                                                                                               
!!! startup-script failed! exit code '127'                                                                                                                                                                                 
stream closed
```

<img width="868" alt="Screen Shot 2021-03-19 at 12 16 11 pm" src="https://user-images.githubusercontent.com/80488/111722115-eb65c580-88ac-11eb-8d0f-08bb7f355d73.png">

[https://github.com/bottlerocket-os/bottlerocket/issues/1405](https://github.com/bottlerocket-os/bottlerocket/issues/1405)

The working node is an Amazon Linux 2 AMI

**Comment by Smana** [comment] 2021-07-07 15:41
Having the same issue here, did you managed to get it work @mmochan please ?

**Comment by aditighag** [comment] 2021-07-07 16:36
I think should be fixed by - https://github.com/cilium/cilium/pull/16656.

**Comment by mmochan** [comment] 2021-07-07 22:55
@Smana - I haven't had a chance to test this yet.

**Comment by aanm** [comment] 2021-07-07 23:01
@Smana the error you are getting is probably this one https://github.com/cilium/cilium/issues/16771 which will be fixed in 1.10.3

Everything should work as fine in 1.10.1 if you deploy Cilium following these instructions: https://github.com/bottlerocket-os/bottlerocket/issues/1405#issuecomment-855085306

**Comment by aditighag** [comment] 2021-07-07 23:10
> @Smana the error you are getting is probably this one #16771 which will be fixed in 1.10.3
> 

@aanm It's not the same issue. The error is coming from node-init script.

>cilium-node-init fails with
nsenter: failed to execute bash: No such file or directory                                                                                                                                                               
!!! startup-script failed! exit code '127'                                                                                                                                                                                 
stream closed

**Comment by aanm** [comment] 2021-07-08 01:50
> > @Smana the error you are getting is probably this one #16771 which will be fixed in 1.10.3
> 
> @aanm It's not the same issue. The error is coming from node-init script.
> 
> > cilium-node-init fails with
> > nsenter: failed to execute bash: No such file or directory
> > !!! startup-script failed! exit code '127'
> > stream closed

@aditighag that error is from the PR description, we don't know which error @Smana actually saw.

**Comment by Smana** [comment] 2021-07-08 07:11
> > > @Smana the error you are getting is probably this one #16771 which will be fixed in 1.10.3
> > 
> > 
> > @aanm It's not the same issue. The error is coming from node-init script.
> > > cilium-node-init fails with
> > > nsenter: failed to execute bash: No such file or directory
> > > !!! startup-script failed! exit code '127'
> > > stream closed
> 
> @aditighag that error is from the PR description, we don't know which error @Smana actually saw.


Hello, yes this is  related to the init pod

```console
❯ kubectl logs cilium-node-init-b4ppm -n kube-system 
nsenter: failed to execute bash: No such file or directory
!!! startup-script failed! exit code '127'
```

**Comment by aanm** [comment] 2021-07-08 12:55
> > > > @Smana the error you are getting is probably this one #16771 which will be fixed in 1.10.3
> > > 
> > > 
> > > @aanm It's not the same issue. The error is coming from node-init script.
> > > > cilium-node-init fails with
> > > > nsenter: failed to execute bash: No such file or directory
> > > > !!! startup-script failed! exit code '127'
> > > > stream closed
> > 
> > 
> > @aditighag that error is from the PR description, we don't know which error @Smana actually saw.
> 
> Hello, yes this is related to the init pod
> 
> ```
> ❯ kubectl logs cilium-node-init-b4ppm -n kube-system 
> nsenter: failed to execute bash: No such file or directory
> !!! startup-script failed! exit code '127'
> ```

@Smana did you deploy Cilium following these instructions: https://github.com/bottlerocket-os/bottlerocket/issues/1405#issuecomment-855085306?

**Comment by bryanasdev000** [comment] 2021-11-11 04:26
Just in case someone else needs it, I can confirm that this snippet works:

```
helm install cilium cilium/cilium --version 1.10.5 \                                                                                         
  --namespace kube-system \                                                                                                                  
  --set eni.enabled=true \                                                                                                                   
  --set ipam.mode=eni \                                                                                                                      
  --set egressMasqueradeInterfaces=eth0 \                                                                                                    
  --set tunnel=disabled \                                                                                                                    
  --set nodeinit.enabled=false
```

Plus if you want to replace kube-proxy:

```
helm install cilium cilium/cilium --version 1.10.5 \                                                                                         
  --namespace kube-system \                                                                                                                  
  --set eni.enabled=true \                                                                                                                   
  --set ipam.mode=eni \                                                                                                                      
  --set egressMasqueradeInterfaces=eth0 \                                                                                                    
  --set tunnel=disabled \                                                                                                                    
  --set nodeinit.enabled=false \                                                                                                             
  --set loadBalancer.algorithm=maglev \                                                                                                      
  --set hubble.enabled=true \                                                                                                                
  --set hubble.relay.enabled=true \                                                                                                          
  --set hubble.ui.enabled=true \                                                                                                             
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \                                                           
  --set kubeProxyReplacement="strict" \                                                                                                      
  --set k8sServiceHost=$API_SERVER_IP \                                                                                                      
  --set k8sServicePort=443                     
  ```

Both without aws cni chaining and passing in `cilium connectivity test`.

**Comment by alex-berger** [comment] 2021-11-24 15:41
Here some context why this issue was reopened. All the details are available in a Slack discussion at https://cilium.slack.com/archives/C53TG4J4R/p1637669818398900 (see screenshot below).

<img width="982" alt="image" src="https://user-images.githubusercontent.com/1087375/143264662-3f9fabcb-40f4-4037-b8e2-b365f0dc4428.png">

**Comment by bryanasdev000** [comment] 2021-11-24 23:25
> Here some context why this issue was reopened. All the details are available in a Slack discussion at https://cilium.slack.com/archives/C53TG4J4R/p1637669818398900 (see screenshot below).
> 
> <img alt="image" width="982" src="https://user-images.githubusercontent.com/1087375/143264662-3f9fabcb-40f4-4037-b8e2-b365f0dc4428.png">

Indeed, cilium-node-init does not run in Bottlerocket, but may I ask if is needed?

From what I know about it, it does make some specific cloud checks (see https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium/files) not too relevant for AWS + Bottlerocket.

I did some PoCs with Bottlerocket and Cilium replacing kube-proxy, not production ready workload, but I did not find any issues besides cilium-node-init not working, i.e. "basic" features were working perfectly.

**Comment by alex-berger** [comment] 2021-11-25 07:34
@bryanasdev000 Same here, I am running a test cluster with Cilium (on EKS with Bottlerocket nodes) without the `cilium-node-init` DaemonSet and so far everything seems to work (but that needs more thorough testing). However, I don't want to build my clusters, which have to last for years (thinking of day two operations), on something that "accidentally" works today, but stops working with a future Cilium version in which `cilium-node-init` DaemonSet might have become mandatory.
Therefore, with this issue we should

- (a) either fix `cilium-node-init` such that it also runs on minimal, immutable container operating systems (like Bottlerocket) 
- or (b) make it clear that `cilium-node-init` is a work-around for some setups and that it will never be needed for other setups (e.g. Bottlerocket)

Obviously, option (b) is unrealistic as we cannot predict how things evolve and thus I am strongly inclined towards option (a).

**Comment by alex-berger** [comment] 2021-11-26 16:29
Maybe we can bake all the needed tools (bash, nsenter, ...) into the image and just omit the `-m` flag on the `nsenter` call. If we still need to read/write to host paths (files on the host) we could mount those specific paths using a [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volumes. 

However, writing to the host filesystem, might not work, as most directories on Bottlerocket are read-only (for security reasons).

**Comment by bryanasdev000** [comment] 2021-11-26 16:56
> Maybe we can bake all the needed tools (bash, nsenter, ...) into the image and just omit the `-m` flag on the `nsenter` call. If we still need to read/write to host paths (files on the host) we could mount those specific paths using a [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volumes.
> 
> However, writing to the host filesystem, might not work, as most directories on Bottlerocket are read-only (for security reasons).

I am not yet too much familiar with Bottlerocket, but it sounds a bit like NixOS (immutability part). In this case I think `cilium-node-init` will have a big IF for edge cases like it, for now I think with the current code (AWS based) we can just invoke iptables directly, but I understand your previous point, I think we need a word from Cilium team about support status or possible rough edges that we need to be aware.

**Comment by ryanmt** [comment] 2022-01-07 19:34
I commented in the referenced slack thread as well, but I have a related question which ties to the "is node-init necessary" which is that if it is necessary, it would be nice to be captured as part of the single DS rather than a secondary pod on every single host.  Just thinking that it consumes limited resources (EKS... so mostly pod count per instance type) which would be nice to avoid. 

Obviously, if node-init can just be simplified into core functionality or very clearly captured as "not required in these circumstances" that would also clarify that.

**Comment by bryanasdev000** [comment] 2022-01-13 17:42
> I commented in the referenced slack thread as well, but I have a related question which ties to the "is node-init necessary" which is that if it is necessary, it would be nice to be captured as part of the single DS rather than a secondary pod on every single host. Just thinking that it consumes limited resources (EKS... so mostly pod count per instance type) which would be nice to avoid.
> 
> Obviously, if node-init can just be simplified into core functionality or very clearly captured as "not required in these circumstances" that would also clarify that.

Oh boy, I remember an issue with same question (can't seem to find now) but the answers was basically about different privileges needed for each component.

**Comment by zhujik** [comment] 2022-05-03 08:27
Is there any update here? The workaround by disableing node-init is not viable since it re-introduces all bugs that node-init actually solves. Also ciliumc li does not support node-init, which requires to change setup builds

**Closed as completed** 2023-05-11 12:22 UTC
Labels: kind/bug, good-first-issue, kind/community-report, integration/cloud
