### ISSUE TITLE
IPv6: LB6: FIB cache wrongly assumes dmac

### ISSUE THREAD

**Issue by Frankkkkk** [cilium/cilium#17693] opened 2021-10-25 13:11 UTC
Everything is explained here : https://github.com/cilium/cilium/issues/17693#issuecomment-951987464

## Bug report

On IPv6 clusters with DSR activated, a bug arises when a node on the same subnet communicates with an SVC. The outbound IPv6 packet generated from the pod's worker node doesn't use the target's mac address (because it's on the same subnet), but the one from the ingress frame instead. This creates communication problems on some cases detailed below.

**General Information**

- Cilium version: `1.10.5 b0836e8`
- Kernel version: `5.4.0-81-generic`
- Orchestration system version in use: `v1.21.5`

**How to reproduce the issue**

First of all, you need a cluster the following properties:
- IPv6 stack
- cilium with the following config options:
  - `enable-ipv6: "true"`
  - `enable-ipv6-masquerade: "false"`
  - `kube-proxy-replacement: strict`
  - `node-port-mode: dsr`
  - `tunnel: disabled`

Then apply the following setup:
```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: hashicorp/http-echo
        name: echo
        args:
          - -listen=:5678
          - -text=foobar
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: echo
  type: LoadBalancer
```

which gives the following indicative results:
```
$ kl get pod -o wide
NAME                    READY   STATUS    RESTARTS   AGE     IP                                     NODE                
echo-696db4945b-4pgcd   1/1     Running   0          8m32s   2001:1600:caca:1001:19:12f:ffff:ccb    worker
$ kl get svc
NAME         TYPE           CLUSTER-IP                           EXTERNAL-IP                       PORT(S)          AGE
echo         LoadBalancer   2001:1600:caca:50da:19:fffe:0:f7c4   2001:1600:caca:50da:19:ffff:0:5   5678:38831/TCP   13m37s
```

Also, here's the worker's routing table:
```
worker:~# ip -6 r sh
---cut---
2001:1600:4:23::/64 dev ens3 proto ra metric 100 expires 2591926sec pref medium
default via fe80::200:5eff:fe00:231 dev ens3 proto ra metric 100 expires 1726sec pref medium

worker:~# ip -6 n sh | grep 231
fe80::200:5eff:fe00:231 dev ens3 lladdr 00:00:5e:00:02:31 router REACHABLE
```

When making a request to the service from the outside, everything works: the outbound packet uses the router mac as a dmac:
```
13:37:42.560177 1c:34:da:91:39:1a > fa:16:3e:8b:1d:fa, ethertype IPv6 (0x86dd), length 118: 2001:1600:0:cccc:1234::37c > 2001:1600:caca:1001:19:12f:ffff:ccb: DSTOPT 52892 > 5678: Flags [S], seq 3418328310, win 64800, options [mss 1240,sackOK,TS val 1375449827 ecr 0,nop,wscale 7], length 0
13:37:42.560298 fa:16:3e:8b:1d:fa > 00:00:5e:00:02:31, ethertype IPv6 (0x86dd), length 94: 2001:1600:caca:50da:19:ffff:0:5.5678 > 2001:1600:0:cccc:1234::37c.52892: Flags [S.], seq 664381651, ack 3418328311, win 64260, options [mss 1440,sackOK,TS val 3576139037 ecr 1375449827,nop,wscale 7], length 0
```

However, when making the request from a machine on the same subnet as the worker, the inbound packet comes from the router (the machine on the same subnet doesn't know that the SVC range is on the same subnet, which is normal). But, in this case, the reply frame is not sent to the machine's mac, but to the router mac instead:
```
13:37:42.285451 1c:34:da:91:3c:1a > fa:16:3e:8b:1d:fa, ethertype IPv6 (0x86dd), length 94: 2001:1600:4:23:f816:3eff:feb7:fbb8.59730 > 2001:1600:caca:50da:19:ffff:0:5.5678: Flags [S], seq 3449427809, win 64800, options [mss 1440,sackOK,TS val 3081382917 ecr 0,nop,wscale 7], length 0
13:37:42.285584 fa:16:3e:8b:1d:fa > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 94: 2001:1600:caca:50da:19:ffff:0:5.5678 > 2001:1600:4:23:f816:3eff:feb7:fbb8.59730: Flags [S.], seq 4152751712, ack 3449427810, win 64260, options [mss 1440,sackOK,TS val 1957909208 ecr 3081382917,nop,wscale 7], length 0
```

- `1c:34:da:91:3c:1a` : router mac
- `2001:1600:4:23:f816:3eff:feb7:fbb8` : client v6
- `fa:16:3e:b7:fb:b8` : client mac
- `2001:1600:4:23:f816:3eff:fe8b:1dfa` : worker node v6
- `fa:16:3e:8b:1d:fa` : worker node mac
- `2001:1600:caca:50da:19:ffff:0:5` : SVC ip

however, the kernel uses the correct mac:
```
worker:~# ip -6 n sh | grep 2001:1600:4:23:f816:3eff:feb7:fbb8
2001:1600:4:23:f816:3eff:feb7:fbb8 dev ens3 lladdr fa:16:3e:b7:fb:b8 router REACHABLE

worker:~# ip -6 r get 2001:1600:4:23:f816:3eff:feb7:fbb8
2001:1600:4:23:f816:3eff:feb7:fbb8 from :: dev ens3 proto ra src 2001:1600:4:23:f816:3eff:fe8b:1dfa metric 100 pref medium
```

Strangely, when querying the pod's IP directly, the correct mac is used, which points me to the DSR implementation:
```
13:37:42.000553 1c:34:da:91:3c:1a > fa:16:3e:8b:1d:fa, ethertype IPv6 (0x86dd), length 94: 2001:1600:4:23:f816:3eff:feb7:fbb8.52742 > 2001:1600:caca:1001:19:12f:ffff:ccb.5678: Flags [S], seq 714071772, win 64800, options [mss 1440,sackOK,TS val 1904279158 ecr 0,nop,wscale 7], length 0
13:37:42.000676 fa:16:3e:8b:1d:fa > fa:16:3e:b7:fb:b8, ethertype IPv6 (0x86dd), length 94: 2001:1600:caca:1001:19:12f:ffff:ccb.5678 > 2001:1600:4:23:f816:3eff:feb7:fbb8.52742: Flags [S.], seq 468790261, ack 714071773, win 64260, options [mss 1440,sackOK,TS val 1958215923 ecr 1904279158,nop,wscale 7], length 0
```

**The problem**
Our setup is like so:
```
                          ┌──────────┐
  ┌─────────────┐ ┌───────┤ Switch 1 │
  │Hypervisor   │ │       └─┬────────┘
  ├──────────┐ ┌┼─┤Bonding  │Peerlink
  │Worker A  ├─┘│ │       ┌─┴────────┐
  └──────────┴──┘ └───────┤ Switch 2 │
                          └──────────┘
```
Each worker resides inside an hypervisor and has a dedicated provider network attached to it.

In our case, when the pod receives a query from a node on the same subnet, the mac address can either be from `Switch 1` or from `Switch 2` (they work on l3 too). For simplicity stake, let's say `Switch 1` Indeed the smac is not the node's mac because the target IP is an LB SVC and thus not on the same subnet.

When the pod replies, cilium uses the the `Switch 1` mac as a dmac (instead of the node's mac). However, as there is an underneath bonding linking the worker to the switches, the packet could arrive to `Switch 2` instead with a dmac of `Switch 1`. The packet thus goes through the peerlink and is then dropped by the `Switch 1` (as it should've arrived by the other link instead). This is [expected an normal](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-37/Layer-2/Multi-Chassis-Link-Aggregation-MLAG/#large-packet-drops-on-the-peer-link-interface)

The problem wouldn't arise if the SVI mac (i.e. the default route) was used instead. Thus I really think that this is a bug.

My hypothesis is https://github.com/cilium/cilium/blob/aed4798a42ec1a0d3dc5c02e795c8a30333e3030/bpf/lib/nodeport.h where we store the mac from the inbound packet. However this is not always true if the src IP is in the same subnet has the host.

Thanks and don't hesitate if you need more information !

**Comment by brb** [comment] 2021-11-03 14:41
@Frankkkkk Thanks for the detailed report!

Indeed, the problem is the neigh cache implemented as the BPF map. We introduced it first to work around the case when BPF NodePort doesn't know the client L2 addr, and we don't do the ARP resolution from the BPF prog. Later on it's usage evolved for the performance reasons.

Anyway, we are currently reevaluating the usage of it, and https://github.com/cilium/cilium/pull/17713 should drop it for some cases.

**Comment by borkmann** [comment] 2021-11-05 08:19
@Frankkkkk thanks a lot for reporting! https://github.com/cilium/cilium/pull/17713 has been merged now and the cache removed. Please test latest master image if you have a chance. (For probing IPv6 node addresses, that next on my list.)

**Comment by Frankkkkk** [comment] 2021-11-08 10:27
Hi @borkmann , thanks for the follow up !

I tried running cilium from `latest` and  when doing `Client -> SVC LB6 -> Node` (both are on the same subnet) some cache seem still present. It worked fine with the `--bpf-lb-bypass-fib-lookup` flag on 1.10.5 but not on master.

- The client: `2001:1600:4:23:f816:3eff:feb7:fbb8`
- The v6 lb ip: `2001:1600:caca:50da:1b:ffff:0:4`
- The node: `2001:1600:4:23:f816:3eff:fe1e:b790`

The tcpdump:
```
10:04:59.653655 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 94: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [S], seq 3954923664, win 65136, options [mss 1416,sackOK,TS val 451528721 ecr 0,nop,wscale 7], length 0
10:04:59.653811 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 94: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [S.], seq 1303710587, ack 3954923665, win 64260, options [mss 1440,sackOK,TS val 1201943941 ecr 451528721,nop,wscale 7], length 0
10:04:59.654038 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 1, win 509, options [nop,nop,TS val 451528721 ecr 1201943941], length 0
10:04:59.654086 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 183: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [P.], seq 1:98, ack 1, win 509, options [nop,nop,TS val 451528721 ecr 1201943941], length 97: HTTP: GET / HTTP/1.1
10:04:59.654110 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 86: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [.], ack 98, win 502, options [nop,nop,TS val 1201943941 ecr 451528721], length 0
10:04:59.654450 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 324: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [P.], seq 1:239, ack 98, win 502, options [nop,nop,TS val 1201943941 ecr 451528721], length 238: HTTP: HTTP/1.1 200 OK
10:04:59.654524 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 701: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [P.], seq 239:854, ack 98, win 502, options [nop,nop,TS val 1201943941 ecr 451528721], length 615: HTTP
10:04:59.654652 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 239, win 508, options [nop,nop,TS val 451528722 ecr 1201943941], length 0
10:04:59.654695 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 854, win 504, options [nop,nop,TS val 451528722 ecr 1201943941], length 0
10:04:59.654833 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [F.], seq 98, ack 854, win 504, options [nop,nop,TS val 451528722 ecr 1201943941], length 0
10:04:59.654890 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 86: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [F.], seq 854, ack 99, win 502, options [nop,nop,TS val 1201943942 ecr 451528722], length 0
10:04:59.655065 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 855, win 504, options [nop,nop,TS val 451528722 ecr 1201943942], length 0
```
The used dmac for the reply back is `1c:34:da:91:3c:1a`, but however the kernel still seems the client on the same subnet and thus should use its mac addr:
```
node:~# ip -6 r get 2001:1600:4:23:f816:3eff:feb7:fbb8
2001:1600:4:23:f816:3eff:feb7:fbb8 from :: dev ens3 proto ra src 2001:1600:4:23:f816:3eff:fe1e:b790 metric 100 pref medium
```

However it works OK on client that are outside the subnet.

Here's the dump on 1.10.5 with the `--bpf-lb-bypass-fib-lookup` flag:
```
10:24:25.370873 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 94: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [S], seq 1051190006, win 65136, options [mss 1416,sackOK,TS val 452694438 ecr 0,nop,wscale 7], length 0
10:24:25.371027 fa:16:3e:1e:b7:90 > fa:16:3e:b7:fb:b8, ethertype IPv6 (0x86dd), length 94: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56900: Flags [S.], seq 1027837158, ack 1051190007, win 64260, options [mss 1440,sackOK,TS val 1203109658 ecr 452694438,nop,wscale 7], length 0
10:24:25.371315 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 1, win 509, options [nop,nop,TS val 452694438 ecr 1203109658], length 0
10:24:25.371316 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 183: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [P.], seq 1:98, ack 1, win 509, options [nop,nop,TS val 452694438 ecr 1203109658], length 97: HTTP: GET / HTTP/1.1
10:24:25.371411 fa:16:3e:1e:b7:90 > fa:16:3e:b7:fb:b8, ethertype IPv6 (0x86dd), length 86: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56900: Flags [.], ack 98, win 502, options [nop,nop,TS val 1203109658 ecr 452694438], length 0
10:24:25.371607 fa:16:3e:1e:b7:90 > fa:16:3e:b7:fb:b8, ethertype IPv6 (0x86dd), length 324: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56900: Flags [P.], seq 1:239, ack 98, win 502, options [nop,nop,TS val 1203109658 ecr 452694438], length 238: HTTP: HTTP/1.1 200 OK
10:24:25.371695 fa:16:3e:1e:b7:90 > fa:16:3e:b7:fb:b8, ethertype IPv6 (0x86dd), length 701: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56900: Flags [P.], seq 239:854, ack 98, win 502, options [nop,nop,TS val 1203109659 ecr 452694438], length 615: HTTP
10:24:25.371826 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 239, win 508, options [nop,nop,TS val 452694439 ecr 1203109658], length 0
10:24:25.372390 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 854, win 504, options [nop,nop,TS val 452694440 ecr 1203109659], length 0
10:24:25.373016 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [F.], seq 98, ack 854, win 504, options [nop,nop,TS val 452694440 ecr 1203109659], length 0
10:24:25.373132 fa:16:3e:1e:b7:90 > fa:16:3e:b7:fb:b8, ethertype IPv6 (0x86dd), length 86: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56900: Flags [F.], seq 854, ack 99, win 502, options [nop,nop,TS val 1203109660 ecr 452694440], length 0
10:24:25.373347 1c:34:da:91:39:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56900 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 855, win 504, options [nop,nop,TS val 452694440 ecr 1203109660], length 0
```



I'm running:
```
# cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.21 (v1.21.6) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens3 2001:1600:4:23:f816:3eff:fe1e:b790 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.10.90 (v1.10.90-f5609ee32704)
NodeMonitor:            Disabled
Cilium health daemon:   Ok   
IPAM:                   , IPv6: 9/65534 allocated from 2001:1600:caca:1001:1b:12e:ffff:0/112
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           Disabled
Controller Status:      54/54 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Disabled
Encryption:             Disabled
Cluster health:         12/12 reachable   (2021-11-08T09:54:53Z)
```

and the cm:
```yaml
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: dsr
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: ""
  cluster-name: default
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-reachable-services: "true"
  enable-ipv4: "false"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "true"
  enable-ipv6-masquerade: "false"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "false"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: kubernetes
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: '[::]:10256'
  monitor-aggregation: low
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: '[::1]:9234'
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
```

do you want me to create a separate issue ?

**Comment by borkmann** [comment] 2021-11-08 13:12
> Hi @borkmann , thanks for the follow up !
> 
> I tried running cilium from `latest` and when doing `Client -> SVC LB6 -> Node` (both are on the same subnet) some cache seems still present. It worked fine with the `--bpf-lb-bypass-fib-lookup` flag on 1.10.5 but not on master.

Thanks for testing!

> * The client: `2001:1600:4:23:f816:3eff:feb7:fbb8`
> * The v6 lb ip: `2001:1600:caca:50da:1b:ffff:0:4`
> * The node: `2001:1600:4:23:f816:3eff:fe1e:b790`
> 
> The tcpdump:
> 
> ```
> 10:04:59.653655 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 94: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [S], seq 3954923664, win 65136, options [mss 1416,sackOK,TS val 451528721 ecr 0,nop,wscale 7], length 0
> 10:04:59.653811 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 94: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [S.], seq 1303710587, ack 3954923665, win 64260, options [mss 1440,sackOK,TS val 1201943941 ecr 451528721,nop,wscale 7], length 0
> 10:04:59.654038 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 1, win 509, options [nop,nop,TS val 451528721 ecr 1201943941], length 0
> 10:04:59.654086 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 183: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [P.], seq 1:98, ack 1, win 509, options [nop,nop,TS val 451528721 ecr 1201943941], length 97: HTTP: GET / HTTP/1.1
> 10:04:59.654110 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 86: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [.], ack 98, win 502, options [nop,nop,TS val 1201943941 ecr 451528721], length 0
> 10:04:59.654450 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 324: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [P.], seq 1:239, ack 98, win 502, options [nop,nop,TS val 1201943941 ecr 451528721], length 238: HTTP: HTTP/1.1 200 OK
> 10:04:59.654524 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 701: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [P.], seq 239:854, ack 98, win 502, options [nop,nop,TS val 1201943941 ecr 451528721], length 615: HTTP
> 10:04:59.654652 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 239, win 508, options [nop,nop,TS val 451528722 ecr 1201943941], length 0
> 10:04:59.654695 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 854, win 504, options [nop,nop,TS val 451528722 ecr 1201943941], length 0
> 10:04:59.654833 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [F.], seq 98, ack 854, win 504, options [nop,nop,TS val 451528722 ecr 1201943941], length 0
> 10:04:59.654890 fa:16:3e:1e:b7:90 > 1c:34:da:91:3c:1a, ethertype IPv6 (0x86dd), length 86: 2001:1600:caca:50da:1b:ffff:0:4.80 > 2001:1600:4:23:f816:3eff:feb7:fbb8.56624: Flags [F.], seq 854, ack 99, win 502, options [nop,nop,TS val 1201943942 ecr 451528722], length 0
> 10:04:59.655065 1c:34:da:91:3c:1a > fa:16:3e:1e:b7:90, ethertype IPv6 (0x86dd), length 86: 2001:1600:4:23:f816:3eff:feb7:fbb8.56624 > 2001:1600:caca:50da:1b:ffff:0:4.80: Flags [.], ack 855, win 504, options [nop,nop,TS val 451528722 ecr 1201943942], length 0
> ```
> 
> The used dmac for the reply back is `1c:34:da:91:3c:1a`, but however the kernel still sees the client on the same subnet and thus should use its mac addr:
> 
> ```
> node:~# ip -6 r get 2001:1600:4:23:f816:3eff:feb7:fbb8
> 2001:1600:4:23:f816:3eff:feb7:fbb8 from :: dev ens3 proto ra src 2001:1600:4:23:f816:3eff:fe1e:b790 metric 100 pref medium
> ```
> 
> However it works OK on client that are outside the subnet.
> 
[...]

Ok, strange. For the Cilium `latest` image, when the situation happens, could you provide a sysdump so I can investigate further? (You could also send it as DM via slack, my nic is 'daniel').

Thanks a lot!

**Comment by Frankkkkk** [comment] 2021-11-08 14:09
Indeed, the neighbour entry was empty (even during traffic from the client via the lb6). Manually adding the entry makes it reply with the correct dmac

I've sent you the sysdump via slack
Cheers !

**Comment by borkmann** [comment] 2021-11-08 14:39
> Indeed, the neighbour entry was empty (even during traffic from the client via the lb6). Manually adding the entry makes it reply with the correct dmac
> 
> I've sent you the sysdump via slack Cheers !

Ok, sounds good. That basically means for the 1.10.5 case you just accidentally had that neighbor entry in the kernel with the `--bpf-lb-bypass-fib-lookup` disabled. E.g. instead of manually adding the entry a ping to the node from the LB node would also add it.

Anyway, for IPv6 neighbor resolution out of the same L2, I'm currently working on addressing it this was exactly my next step. Thanks for confirming! We can leave this one in here open until it's addressed.

**Closed as completed** 2021-11-11 21:17 UTC
Labels: kind/bug, area/datapath, kind/community-report

**Comment by borkmann** [comment] 2021-11-11 21:20
@Frankkkkk just merged IPv6 neighbor discovery https://github.com/cilium/cilium/pull/17842 . Should be fixed now, please test again with latest image.

Could you also do a dump of `ip -4 n` and `ip -6 n` once you run the tests? Just for confirmation on the neigh entries on your side that you see them marked as externally learned.

Thanks a lot!
