### ISSUE TITLE
clustermesh: agent leaks memory when remote cluster connection is restarted 

### ISSUE THREAD

**Issue by oblazek** [cilium/cilium#22988] opened 2023-01-09 14:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We started to see memory increase when remote cluster connection was restarted. And each time the remote connection was restarted the more memory it leaked. The problematic cluster had around 20k identities which was fantastic because otherwise we would not see the leak so early.   

The memory should stay the same before and after the restart. (also the memory was not released when we totally removed the cluster from clustermesh). 

I can easily reproduce this if I manually update a selected remote cluster config (to trigger fsnotify) each time I do this, some memory is leaked.

### Cilium Version

```
Client: 1.12.4 ac046c95eb 2022-11-16T14:51:11+01:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 ac046c95eb 2022-11-16T14:51:11+01:00 go version go1.18.8 linux/amd64
```

### Kernel Version

`Linux tt-os2-n1.ko.iszn.cz 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

but it's not related to k8s as it happens also on nodes outside of k8s 

### Relevant log output

```shell
level=info msg="etcd configuration has changed, re-creating connection" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus="etcd: 1/1 connected, lease-ID=3b2a847f52738930, lock lease-ID=3b2a847f52738935, has-quorum=true: https://uacl-test-labrador-test.ko.iszn.cz:31007 - 3.5.4" subsys=clustermesh
level=info msg="Creating etcd client" ConfigPath=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test KeepAliveHeartbeat=15s KeepAliveTimeout=25s RateLimit=20 subsys=kvstore
level=info msg="Connecting to etcd server..." config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" subsys=kvstore
level=info msg="Got lease ID 10df847f53140be2 and the session TTL is 15m0s" subsys=kvstore
level=info msg="Got lock lease ID 10df847f53140be7" subsys=kvstore
level=info msg="Initial etcd session established" config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" etcdEndpoint="https://uacl-test-labrador-test.ko.iszn.cz:31007" subsys=kvstore version=3.5.4
level=info msg="Connection to remote cluster established" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
level=info msg="Established connection to remote etcd" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus="etcd: 1/1 connected, lease-ID=10df847f53140be2, lock lease-ID=10df847f53140be7, has-quorum=true: https://uacl-test-labrador-test.ko.iszn.cz:31007 - 3.5.4" subsys=clustermesh
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
```

### Anything else?

related slack thread https://cilium.slack.com/archives/C1MATJ5U5/p1672811968057149

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment] 2023-01-09 18:22
Hi! Do you have any pprof traces collected from an affected cluster/node when the agent is exhibiting memory leaks?

**Comment by aanm** [comment] 2023-01-09 19:15
Looks a duplicate of https://github.com/cilium/cilium/issues/13446

**Comment by oblazek** [comment] 2023-01-09 19:37
> Looks a duplicate of #13446

 ah yes, totally missed that one :( .. looks like it might be the same.. in both cases the code runs `restartRemoteConnection`

**Comment by oblazek** [comment] 2023-01-09 21:25
I can simulate the connection restart as many times as you want, if that helps anything.. Currently agent is consuming around 1G of memory.
[heap-profile.zip](https://github.com/cilium/cilium/files/10377021/heap-profile.zip)

**Comment by oblazek** [comment] 2023-01-10 07:30
![profile001](https://user-images.githubusercontent.com/15906154/211488747-bd1d85e3-9ca5-494e-9873-a3971c97af8e.svg)

**Comment by oblazek** [comment] 2023-01-31 07:03
ok, found the culprit.. [this](https://github.com/cilium/cilium/blob/41d30efcf4d7214270bb0299a44e0251162c6f9b/pkg/allocator/allocator.go#L902) is run each time the connection is restarted and is never cleaned up. I.e. each time a new RemoteCache is instantiated and keeps all the remote identities etc.. This is kept in the map and as this saved by its address the GC doesn't clean it up (edited)

**Comment by squeed** [comment] 2023-02-02 08:48
hey @oblazek, awesome find! Do you have time to work on a fix? If not, I'd be happy to help.

**Comment by oblazek** [comment] 2023-02-02 09:08
hey @squeed yeah, I am able to fix the main part.. but something is still leaking..

**Comment by oblazek** [comment] 2023-02-15 09:47
:tada:  I have found the remaining bit.. will send a PR shortly with the profile results (before/after) :)

**Comment by squeed** [comment] 2023-02-16 08:23
There is still a leak; @oblazek is on it :-)

**Closed as completed** 2023-02-28 21:34 UTC
Labels: kind/bug, needs/triage, kind/community-report, area/clustermesh, area/agent
