### ISSUE TITLE
Incorrect masquerade rule set

### ISSUE THREAD

**Issue by mskrocki** [cilium/cilium#10939] opened 2020-04-10 23:30 UTC
Bug report

The created iptable rule for masquerade is incorrect. Found this (for node CIDR 172.28.0.0/24 and podCIDR 172.28.0.0/16, and node IP in 172.16.3.0/24):
`-A CILIUM_POST_nat -s 172.28.0.0/24 ! -d 172.0.0.0/8 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE`

But according to http://docs.cilium.io/en/latest/_images/kubernetes_iptables.svg it should be:
`-A CILIUM_POST_nat -s NODE_CIDR ! -d NODE_CIDR ! -o cilium_+ -j MASQUERADE`

**General Information**

- Cilium version v1.6.5
Cilium config:
  auto-direct-node-routes: "true"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "false"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  tofqdns-enable-poller: "false"
  tunnel: disabled
  wait-bpf-mount: "false"

**How to reproduce the issue**

1. create a cluster with podCIDR similar to node IPs e.g. node IPs in 172.16.3.x/24 and podCIDR in 172.28.x.x/16
2. from any Pod try to ping some local IP (e.g 172.16.3.x/24), that is not part of the cluster in anyway (the ping will fail)

**Comment by mskrocki** [comment] 2020-04-14 19:40
Verified, and same issue is still present with cilium v1.7.2.

**Comment by joestringer** [comment] 2020-04-14 21:18
@mskrocki I believe there was some discussion today on the nuance of this issue, is there a brief summary that would be useful to note down on this issue here to help guide a developer to resolving this issue?

**Comment by mskrocki** [comment] 2020-04-14 22:59
It probably boils down to why this: https://github.com/cilium/cilium/blob/ae4fbbed82e2e759dc68a83aa0365e26cfe61d7e/pkg/datapath/iptables/iptables.go#L886
ends up being `! -d 172.0.0.0/8` when node podCIDR is `172.28.0.0/24` (from the _node.spec.podCIDR_).
From the discussion I learned that cilium does not have access to the cluster-wide podCIDR (which is 172.28.0.0/16), but here I don't think it matters.

**Comment by tgraf** [comment] 2020-04-21 14:35
have been trying to reproduce this for a while. I wasn’t able to do so.

I suspect the cause is the missing flag `--set global.k8s.requireIPv4PodCIDR=true`

I’ve created a PR to improve the GKE guide: https://github.com/cilium/cilium/pull/11079

It disables tunneling, enables native routing, enables endpoint routes and instructs Cilium to wait until Node.Spec.PodCIDR[s] is populated.

For a node with:
```
  podCIDR: 10.68.0.0/24
```
the iptables rule is:
```
-A CILIUM_POST_nat -s 10.68.0.0/24 ! -d 10.68.0.0/24 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
```

**Comment by mskrocki** [comment] 2020-04-21 18:58
I have tried the `requireIPv4PodCIDR` flag and it did not help.

Additionally, I have tried to re-produce this issue on a cluster created with kubeadm v1.17. Using the default https://github.com/cilium/cilium/blob/master/install/kubernetes/quick-install.yaml config from 1.7.2. With `tunnel: vxlan`, the iptable rule is correct, but when changed to `tunnel: disabled`, the rule ends with /8 mask (here as well the  `requireIPv4PodCIDR` flag does not help).

**Comment by mskrocki** [comment] 2020-04-28 20:57
Setting `native-routing-cidr` fixes this issue.

**Comment by brb** [comment] 2020-08-06 09:02
@mskrocki Can we close this issue?

**Comment by mskrocki** [comment] 2020-08-06 14:40
Yes.

**Closed as completed** 2020-08-07 07:27 UTC
Labels: kind/bug, priority/high, area/datapath
