### ISSUE TITLE
CI: K8sServicesTest (checks service across nodes Supports IPv4 fragments)

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#10950] opened 2020-04-13 21:31 UTC
## [CI: K8sServicesTest (checks service across nodes Supports IPv4 fragments)](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18699/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments/)

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Failed to account for IPv4 fragments (in)
Expected
    <[]int | len:2, cap:2>: [5, 0]
To satisfy at least one of these matchers: [%!s(*matchers.EqualMatcher=&{[0 4]}) %!s(*matchers.EqualMatcher=&{[4 0]})]
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:548
```
[Test failure link](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18699/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments/)

[Test failure log link](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18699/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments/attachments/dcc7ec39_K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments.zip)

**Comment by pchaigno** [comment] 2020-04-14 05:16
Duplicate of #10929.

**Closed as completed** 2020-04-14 05:17 UTC
Labels: area/CI
