### ISSUE TITLE
Cilium agent stuck with high disk read

### ISSUE THREAD

**Issue by jenoOvchi** [cilium/cilium#29081] opened 2023-11-09 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Periodically on some worker nodes in Kubernetes cluster Cilium agent stuck. When it happens memory usage of this pod of this agent a little bit decreased, but CPU usage increases in hundreds of times. Example:
![StuckedPod](https://github.com/cilium/cilium/assets/33250618/49f19b50-ebdd-471e-bb81-36bc1ecf9d30)

On this screenshot we can see that up to 21 o'clock the pod was in the normal state and use around 20 millicores and 900 Mb RAM (that in two times more, than on other nodes). But after 21 o'clock RAM usage decreased to around 400 Mb and CPU usage increased to around 4 cores. As you can see, pod has a lot of restarts (32).

At the same time on that worker node Cilium agent starts to generate a lot of Disk Reads:
![CiliumHighRead](https://github.com/cilium/cilium/assets/33250618/7ab767e6-184a-482f-9e1a-26500c4b2ac4)

On other nodes we can see stable CPU and RAM consumption and disk reads:
![HealthyNode](https://github.com/cilium/cilium/assets/33250618/631af744-e2e9-4a6c-9199-9bd4f6d73c3e)
<img width="541" alt="HealthyNodeDisk" src="https://github.com/cilium/cilium/assets/33250618/b8d9e86c-fe8a-4e1c-9ec5-be6270c07c4e">

After pod deleating new pod starts with normal CPU and RAM consumptions and low disk read.

What could be causing this problem and what is the best way to prevent and debug it in the future?

Environment:
Three master and four worker nodes Kubernetes cluster

### Cilium Version

1.12.12

### Kernel Version

RHEL 8.8

### Kubernetes Version

1.21.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment] 2023-11-10 11:14
Interesting. The high disk reads are caused by the bpf compiler (llc), presumably due to a number of endpoint regenerations.

Can you please capture some logs from when this happens? You can get them with `kubectl get logs -p ...`, which will include the logs from the previous pod. Alternatively, you can use [sysdump](https://docs.cilium.io/en/latest/operations/troubleshooting/#reporting-a-problem) to do this automatically. (sysdump has an option to only gather data from a single node).

When this happens, could you please post the sysdumps? Alternatively, reach out if you would like to share them privately.

**Comment by squeed** [comment] 2023-11-10 11:21
You may wish to upgrade to the latest version of v1.12 (v1.12.15 currently). I don't see any smoking-gun issues, but there have been some changes in endpoint management.

**Comment by jenoOvchi** [comment] 2023-11-20 11:45
We was update our Cilium version to 1.14.2 and repair kubelet filesystem on worker nodes with xfs_repair -n and now all works fine. Maybe CIlium problems has been related to filesystem errors too.

**Comment by lmb** [comment] 2023-11-21 14:54
Sounds like this was resolved, closing. Please reopen the issue if I misunderstood.

**Closed as completed by lmb** 2023-11-21 14:54 UTC
Labels: kind/bug, needs/triage, kind/community-report, info-completed
