### ISSUE TITLE
Containers can't connect after L3-L4 Policy has been applied

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#3493] opened 2018-04-03 15:10 UTC
Issue: 
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1950/testReport/junit/(root)/runtime/RuntimeValidatedPolicies_L3_L4_Checks/

```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:270
"app3" expects curl public URL on httpd2 (10.15.131.27) to succeed
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:522
```

Containers were ready:
```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
13233      Disabled           Enabled           26838      container:id.app3             f00d::a0f:0:0:33b1   10.15.113.22    ready   
17607      Enabled            Disabled          6036       container:id.httpd1           f00d::a0f:0:0:44c7   10.15.195.104   ready   
                                                           container:id.service1                                                      
22252      Disabled           Disabled          40574      container:id.app1             f00d::a0f:0:0:56ec   10.15.18.90     ready   
29898      Disabled           Disabled          39330      reserved:health               f00d::a0f:0:0:74ca   10.15.242.54    ready   
33922      Disabled           Disabled          41062      container:id.httpd3           f00d::a0f:0:0:8482   10.15.0.250     ready   
                                                           container:id.service1                                                      
38593      Disabled           Enabled           32880      container:id.app2             f00d::a0f:0:0:96c1   10.15.125.138   ready   
52066      Enabled            Disabled          54644      container:id.httpd2           f00d::a0f:0:0:cb62   10.15.131.27    ready   
                                                           container:id.service1                                                      
```

I saw a lot of this messages in the cilium agent log: 

```
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.250.189 entryDstPort=80 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.28.238 entrySrcSecID=51497 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.250.189 entryDstPort=2048 entryFlags=1 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.129.91 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.250.189 entryDstPort=2048 entryFlags=1 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.129.91 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.155.111 entryDstPort=2048 entryFlags=1 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.197.39 entrySrcSecID=39530 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.155.111 entryDstPort=2048 entryFlags=1 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.197.39 entrySrcSecID=39530 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.42.252 entryDstPort=40459 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.42.252 entryDstPort=40459 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.42.252 entryDstPort=39769 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.42.252 entryDstPort=39769 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.42.252 entryDstPort=34401 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.42.252 entryDstPort=34401 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.42.252 entryDstPort=12865 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.42.252 entryDstPort=12865 entryFlags=1 entryProto=6 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Apr 03 13:51:19 runtime cilium-agent[2980]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.42.252 entryDstPort=2048 entryFlags=1 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.148.173 entrySrcSecID=5354 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
```

The weird thing, is that the bpf proxy list was empty.

**Comment by ianvernon** [comment] 2018-04-03 16:15
If only L3-L4 policy is applied, I believe it is expected that the `bpf proxy list` is empty because there the proxy isn't involved with L3-L4 traffic.

**Comment by joestringer** [comment] 2018-04-03 23:49
Duplicate of #3491.

**Closed as completed by joestringer** 2018-04-03 23:49 UTC
Labels: kind/bug/CI, area/CI
