### ISSUE TITLE
CI: K8sDatapathConfig IPv4Only Check connectivity with IPv6 disabled

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7128] opened 2019-02-18 19:47 UTC
Link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2392/testReport/junit/k8s-1/8/K8sDatapathConfig_IPv4Only_Check_connectivity_with_IPv6_disabled/

Output: 
```
Stacktrace

/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:409
Pods are not ready after timeout
Expected
    <*errors.errorString | 0xc4227ba890>: {
        s: "Timeout reached: timed out waiting for pods with filter  to be ready",
    }
to be nil
/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:156
Standard Output

Number of 'context deadline exceeded' in logs: 0
Number of 'level=error' in logs: 0
⚠️  Number of 'level=warning' in logs: 8
Number of 'Cilium API handler panicked' in logs: 0
Number of 'Goroutine took lock for more than' in logs: 0
Cilium pods: [cilium-4zrrq cilium-tkjj2]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::cnp-second-namespace 
Endpoint Policy Enforcement:
Pod                             Ingress   Egress
testclient-s7dzw                false     false
testclient-z6tkw                false     false
testds-rtqnp                    false     false
cilium-etcd-bhcd8zbn2p          false     false
etcd-operator-696fb6d99-rqtkk   false     false
testclient-qnzkq                false     false
testclient-s7zdx                false     false
testclient-2hdtc                false     false
testclient-5k9nn                false     false
testclient-5t4ls                false     false
testclient-jdxlb                false     false
testds-hxkxm                    false     false
cilium-etcd-2phzbpjsv9          false     false
cilium-etcd-rz6hwtkd74          false     false
kube-dns-6f4c8dbcd4-bqwtn       false     false
Cilium agent 'cilium-4zrrq': Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 30 Failed 0
Cilium agent 'cilium-tkjj2': Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 46 Failed 0

Standard Error

STEP: Performing Cilium preflight check
STEP: Checking that cilium status is healthy
STEP: Checking that no controllers in Cilium have failed
STEP: Checking that cilium-health status is healthy
STEP: Checking that Kubernetes services are correctly plumbed by Cilium
STEP: Checking that the default/kubernetes service is correctly plumbed by Cilium
STEP: Waiting for all etcd-operator pods are ready
=== Test Finished at 2019-02-18T11:48:26Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE       IP              NODE
	 default       testclient-5k9nn                        1/1       Running             0          5m        10.10.1.8       k8s2
	 default       testclient-s7dzw                        0/1       ContainerCreating   0          5m        <none>          k8s1
	 default       testds-hxkxm                            1/1       Running             0          5m        10.10.0.107     k8s1
	 default       testds-rtqnp                            1/1       Running             0          5m        10.10.1.39      k8s2
	 kube-system   cilium-4zrrq                            1/1       Running             0          5m        192.168.36.11   k8s1
	 kube-system   cilium-etcd-2phzbpjsv9                  1/1       Running             0          28m       10.10.0.182     k8s1
	 kube-system   cilium-etcd-bhcd8zbn2p                  1/1       Running             0          29m       10.10.1.55      k8s2
	 kube-system   cilium-etcd-operator-5dd7fbcf75-qxrsz   1/1       Running             0          29m       192.168.36.12   k8s2
	 kube-system   cilium-etcd-rz6hwtkd74                  1/1       Running             0          28m       10.10.1.81      k8s2
	 kube-system   cilium-tkjj2                            1/1       Running             0          5m        192.168.36.12   k8s2
	 kube-system   etcd-k8s1                               1/1       Running             0          33m       192.168.36.11   k8s1
	 kube-system   etcd-operator-696fb6d99-rqtkk           1/1       Running             0          29m       10.10.1.3       k8s2
	 kube-system   kube-apiserver-k8s1                     1/1       Running             0          32m       192.168.36.11   k8s1
	 kube-system   kube-controller-manager-k8s1            1/1       Running             0          32m       192.168.36.11   k8s1
	 kube-system   kube-dns-6f4c8dbcd4-bqwtn               3/3       Running             0          33m       10.10.1.177     k8s2
	 kube-system   kube-proxy-29r8r                        1/1       Running             0          29m       192.168.36.12   k8s2
	 kube-system   kube-proxy-z7mx7                        1/1       Running             0          33m       192.168.36.11   k8s1
	 kube-system   kube-scheduler-k8s1                     1/1       Running             0          32m       192.168.36.11   k8s1
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-4zrrq -- cilium bpf tunnel list
Exitcode: 0 
Stdout:
 	 TUNNEL      VALUE           
	 10.10.1.0   192.168.36.12   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-4zrrq -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                            
	 2243       Disabled           Disabled          4               reserved:health                                                        10.10.0.192   ready                  
	 2485       Unknown            Unknown           <no label id>   k8s:io.cilium.k8s.policy.cluster=default                               10.10.0.153   waiting-for-identity   
	                                                                 k8s:io.cilium.k8s.policy.serviceaccount=default                                                             
	                                                                 k8s:io.kubernetes.pod.namespace=default                                                                     
	                                                                 k8s:zgroup=testDSClient                                                                                     
	 2878       Disabled           Disabled          101             k8s:app=etcd                                      f00d::a0a:0:0:7e3c   10.10.0.182   ready                  
	                                                                 k8s:etcd_cluster=cilium-etcd                                                                                
	                                                                 k8s:io.cilium.k8s.policy.cluster=default                                                                    
	                                                                 k8s:io.cilium.k8s.policy.serviceaccount=default                                                             
	                                                                 k8s:io.cilium/app=etcd-operator                                                                             
	                                                                 k8s:io.kubernetes.pod.namespace=kube-system                                                                 
	 3011       Disabled           Disabled          2649            k8s:io.cilium.k8s.policy.cluster=default                               10.10.0.107   ready                  
	                                                                 k8s:io.cilium.k8s.policy.serviceaccount=default                                                             
	                                                                 k8s:io.kubernetes.pod.namespace=default                                                                     
	                                                                 k8s:zgroup=testDS                                                                                           
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-tkjj2 -- cilium bpf tunnel list
Exitcode: 0 
Stdout:
 	 TUNNEL      VALUE           
	 10.10.0.0   192.168.36.11   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-tkjj2 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                   IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                
	 214        Disabled           Disabled          4          reserved:health                                                                 10.10.1.22    ready   
	 270        Disabled           Disabled          37678      k8s:io.cilium.k8s.policy.cluster=default                                        10.10.1.8     ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                                               
	                                                            k8s:zgroup=testDSClient                                                                               
	 2284       Disabled           Disabled          102        k8s:io.cilium.k8s.policy.cluster=default                 f00d::a0a:100:0:2ec    10.10.1.177   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                      
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                           
	                                                            k8s:k8s-app=kube-dns                                                                                  
	 2285       Disabled           Disabled          101        k8s:app=etcd                                             f00d::a0a:100:0:d436   10.10.1.81    ready   
	                                                            k8s:etcd_cluster=cilium-etcd                                                                          
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                              
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
	                                                            k8s:io.cilium/app=etcd-operator                                                                       
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                           
	 3126       Disabled           Disabled          101        k8s:app=etcd                                             f00d::a0a:100:0:a517   10.10.1.55    ready   
	                                                            k8s:etcd_cluster=cilium-etcd                                                                          
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                              
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
	                                                            k8s:io.cilium/app=etcd-operator                                                                       
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                           
	 3151       Disabled           Disabled          100        k8s:io.cilium.k8s.policy.cluster=default                 f00d::a0a:100:0:f559   10.10.1.3     ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=cilium-etcd-sa                                                
	                                                            k8s:io.cilium/app=etcd-operator                                                                       
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                           
	 3934       Disabled           Disabled          2649       k8s:io.cilium.k8s.policy.cluster=default                                        10.10.1.39    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
	                                                            k8s:io.kubernetes.pod.namespace=default                                                               
	                                                            k8s:zgroup=testDS                                                                                     
	 
Stderr:
 	 

===================== Existing AfterFailed =====================
```

Logs:  
[b7ce6fc8_K8sDatapathConfig_IPv4Only_Check_connectivity_with_IPv6_disabled.zip](https://github.com/cilium/cilium/files/2877198/b7ce6fc8_K8sDatapathConfig_IPv4Only_Check_connectivity_with_IPv6_disabled.zip)

**Comment by tgraf** [comment] 2019-03-06 11:20
I've hit this as well. All required etcd pods are up:

```
Name:           cilium-etcd-cftmdh5nf4
Status:         Running
Events:
[...]
  Normal   Started                25m   kubelet, k8s2      Started container
  Warning  Unhealthy              7m    kubelet, k8s2      Readiness probe failed: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
```

```
Name:           cilium-etcd-dn9msnjdp2
Status:         Running
Events:
  Normal   Started                26m                kubelet, k8s2      Started container
  Warning  Unhealthy              25m (x2 over 25m)  kubelet, k8s2      Readiness probe failed: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
```

```
Name:           cilium-etcd-ljr7dwqsnc
Status:         Running
Events:
  Normal   Started                25m   kubelet, k8s1      Started container
  Warning  Unhealthy              7m    kubelet, k8s1      Readiness probe failed: https://localhost:2379 is unhealthy: failed to commit proposal: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Error: unhealthy cluster
  Warning  Unhealthy  7m  kubelet, k8s1  Readiness probe failed: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
```

All of them had some health checks fail, likely during an upgrade test or similar. All of them recovered.

```
Name:           cilium-etcd-operator-6d5bbdc7f8-xmfl2
Status:         Running
Events:
  Normal   Started                27m                kubelet, k8s1      Started container
```

```
Name:           etcd-operator-7bc6d4fc6-n8wwg
Status:         Running
Events:
  Normal   Started                 26m                kubelet, k8s2      Started container
```

**Comment by tgraf** [comment] 2019-03-06 11:21
Both cilium pods have etcd connectivity:
```
$  cat bugtool-cilium-k6bhv/cmd/cilium-status---verbose.md
KVStore:                Ok   etcd: 1/1 connected: https://cilium-etcd-client.kube-system.svc:2379 - 3.3.11 (Leader)
ContainerRuntime:       Ok   docker daemon: OK
Kubernetes:             Ok   1.9 (v1.9.11) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
Cilium:                 Ok   OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPv4 address pool:      6/255 allocated from 10.10.0.0/24
  10.10.0.1
  10.10.0.59
  10.10.0.74
  10.10.0.172
  10.10.0.210
  10.10.0.244
Controller Status:   25/25 healthy
  Name                                        Last success   Last error   Count   Message
  cilium-health-ep                            14s ago        never        0       no error
  dns-garbage-collector-job                   18s ago        never        0       no error
  ipcache-bpf-garbage-collection              18s ago        never        0       no error
  k8s-sync-ciliumnetworkpolicies              17s ago        never        0       no error
  k8s-sync-endpoints                          17s ago        never        0       no error
  k8s-sync-networkpolicies                    17s ago        never        0       no error
  k8s-sync-nodes                              16s ago        never        0       no error
  k8s-sync-pods                               16s ago        never        0       no error
  k8s-sync-services                           17s ago        never        0       no error
  kvstore-etcd-session-renew                  never          never        0       no error
  kvstore-sync-store-cilium/state/nodes/v1    20s ago        never        0       no error
  lxcmap-bpf-host-sync                        5s ago         never        0       no error
  metricsmap-bpf-prom-sync                    5s ago         never        0       no error
  propagating local node change to kv-store   5m20s ago      never        0       no error
  resolve-identity-0                          16s ago        never        0       no error
  sync-IPv4-identity-mapping (0)              16s ago        never        0       no error
  sync-IPv4-identity-mapping (2371)           16s ago        never        0       no error
  sync-IPv6-identity-mapping (0)              16s ago        never        0       no error
  sync-IPv6-identity-mapping (2371)           16s ago        never        0       no error
  sync-lb-maps-with-k8s-services              5m16s ago      never        0       no error
  sync-policymap-1540                         14s ago        never        0       no error
  sync-policymap-2371                         15s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (2371)           6s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (309)            11s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (3388)           10s ago        never        0       no error
Proxy Status:   OK, ip 10.10.0.1, port-range 10000-20000
Cluster health:      2/2 reachable   (2019-03-06T10:11:17Z)
  Name               IP              Reachable   Endpoints reachable
  k8s1 (localhost)   192.168.36.11   true        false
  k8s2               192.168.36.12   true        false
```

```
$  cat bugtool-cilium-sq7gw/cmd/cilium-status---verbose.md
KVStore:                Ok   etcd: 1/1 connected: https://cilium-etcd-client.kube-system.svc:2379 - 3.3.11
ContainerRuntime:       Ok   docker daemon: OK
Kubernetes:             Ok   1.9 (v1.9.11) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
Cilium:                 Ok   OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPv4 address pool:      9/255 allocated from 10.10.1.0/24
  10.10.1.1
  10.10.1.19
  10.10.1.27
  10.10.1.52
  10.10.1.128
  10.10.1.136
  10.10.1.142
  10.10.1.200
  10.10.1.216
Controller Status:   45/45 healthy
  Name                                        Last success   Last error   Count   Message
  cilium-health-ep                            26s ago        never        0       no error
  dns-garbage-collector-job                   37s ago        never        0       no error
  ipcache-bpf-garbage-collection              33s ago        never        0       no error
  k8s-sync-ciliumnetworkpolicies              34s ago        never        0       no error
  k8s-sync-endpoints                          34s ago        never        0       no error
  k8s-sync-networkpolicies                    34s ago        never        0       no error
  k8s-sync-nodes                              34s ago        never        0       no error
  k8s-sync-pods                               34s ago        never        0       no error
  k8s-sync-services                           34s ago        never        0       no error
  kvstore-etcd-session-renew                  never          never        0       no error
  kvstore-sync-store-cilium/state/nodes/v1    38s ago        never        0       no error
  lxcmap-bpf-host-sync                        4s ago         never        0       no error
  metricsmap-bpf-prom-sync                    4s ago         never        0       no error
  propagating local node change to kv-store   5m38s ago      never        0       no error
  resolve-identity-0                          33s ago        never        0       no error
  resolve-identity-2281                       33s ago        never        0       no error
  resolve-identity-3660                       33s ago        never        0       no error
  sync-IPv4-identity-mapping (0)              32s ago        5m33s ago    0       no error
  sync-IPv4-identity-mapping (1444)           32s ago        5m33s ago    0       no error
  sync-IPv4-identity-mapping (2281)           33s ago        never        0       no error
  sync-IPv4-identity-mapping (2324)           32s ago        5m33s ago    0       no error
  sync-IPv4-identity-mapping (3660)           33s ago        never        0       no error
  sync-IPv4-identity-mapping (3964)           32s ago        5m33s ago    0       no error
  sync-IPv4-identity-mapping (420)            32s ago        5m33s ago    0       no error
  sync-IPv6-identity-mapping (0)              32s ago        5m33s ago    0       no error
  sync-IPv6-identity-mapping (1444)           32s ago        5m33s ago    0       no error
  sync-IPv6-identity-mapping (2281)           33s ago        never        0       no error
  sync-IPv6-identity-mapping (2324)           32s ago        5m33s ago    0       no error
  sync-IPv6-identity-mapping (3660)           33s ago        never        0       no error
  sync-IPv6-identity-mapping (3964)           32s ago        5m33s ago    0       no error
  sync-IPv6-identity-mapping (420)            32s ago        5m33s ago    0       no error
  sync-lb-maps-with-k8s-services              5m33s ago      never        0       no error
  sync-policymap-1444                         32s ago        never        0       no error
  sync-policymap-1800                         26s ago        never        0       no error
  sync-policymap-2281                         27s ago        never        0       no error
  sync-policymap-2324                         30s ago        never        0       no error
  sync-policymap-3660                         28s ago        never        0       no error
  sync-policymap-3964                         31s ago        never        0       no error
  sync-policymap-420                          29s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (1444)           13s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (2281)           12s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (2324)           13s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (3660)           12s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (3964)           13s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (420)            13s ago        never        0       no error
Proxy Status:   OK, ip 10.10.1.1, port-range 10000-20000
Cluster health:      2/2 reachable   (2019-03-06T10:10:11Z)
  Name               IP              Reachable   Endpoints reachable
  k8s2 (localhost)   192.168.36.12   true        false
  k8s1               192.168.36.11   true        false
```

**Comment by tgraf** [comment] 2019-03-06 11:42
Workload pods remain in ContainerCreating state in one of the two nodes:
```
00:46:04.904  	 default       testclient-m4mkg                        0/1       ContainerCreating   0          5m        <none>          k8s1

00:46:04.904  	 default       testds-p66fr                            0/1       ContainerCreating   0          5m        <none>          k8s1
```

The other node is fine:
```
00:46:04.904  	 default       testds-k4ksr                            1/1       Running             0          5m        10.10.1.200     k8s2
00:46:04.904  	 default       testclient-9txsn                        1/1       Running             0          5m        10.10.1.142     k8s2
```

The failing node struggles to get the endpoints up:
```
00:46:04.904  	 309        Unknown            Unknown           <no label id>   k8s:io.cilium.k8s.policy.cluster=default                              10.10.0.74    waiting-for-identity   

00:46:04.904  	 3388       Unknown            Unknown           <no label id>   k8s:io.cilium.k8s.policy.cluster=default                              10.10.0.210   waiting-for-identity   
```

**Comment by tgraf** [comment] 2019-03-06 11:55
When the endpoint in question is added, the following log message is printed:
```
cilium-test.log:2019-03-06T10:10:51.598370861Z level=debug msg="Endpoint has reserved identity, changing synchronously" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpoint
```

The respective code block is:
```
        // If we are certain we can resolve the identity without accessing the KV
        // store, do it first synchronously right now. This can reduce the number
        // of regenerations for the endpoint during its initialization.
        if blocking || cache.IdentityAllocationIsLocal(newLabels) {
                scopedLog.Debug("Endpoint has reserved identity, changing synchronously")
                err := e.identityLabelsChanged(owner, myChangeRev)
```

`blocking` is true due to `createEndpoint()` setting it.

This leads to the kvstore being queried before connectivity is reached:
```
2019-03-06T10:10:51.598348683Z level=info msg="New endpoint" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpoint
[...]
2019-03-06T10:10:51.598370861Z level=debug msg="Endpoint has reserved identity, changing synchronously" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpoint
[...]
2019-03-06T10:11:16.685469074Z level=warning msg="Timeout while waiting for lock, forcefully unlocking..." path="cilium/state/identities/v1/locks/k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:zgroup=testDS;" subsys=kvstore
```

**Comment by tgraf** [comment] 2019-03-06 11:58
As seen in the entire log of the endpoint in question, the identity is never resolved:
```
2019-03-06T10:10:51.598348683Z level=info msg="New endpoint" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpoint
2019-03-06T10:10:51.598351189Z level=debug msg="Refreshing labels of endpoint" containerID=16391b8c87 endpointID=3388 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" infoLabels="k8s:controller-revision-hash=3749195971,k8s:pod-template-generation=1" subsys=endpoint
2019-03-06T10:10:51.598353991Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:pod-template-generation Value:1 Source:k8s}" subsys=endpoint
2019-03-06T10:10:51.598356444Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:controller-revision-hash Value:3749195971 Source:k8s}" subsys=endpoint
2019-03-06T10:10:51.598358835Z level=debug msg="Assigning security relevant label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.cilium.k8s.policy.serviceaccount Value:default Source:k8s}" subsys=endpoint
2019-03-06T10:10:51.598362953Z level=debug msg="Assigning security relevant label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.cilium.k8s.policy.cluster Value:default Source:k8s}" subsys=endpoint
2019-03-06T10:10:51.598365934Z level=debug msg="Assigning security relevant label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:zgroup Value:testDS Source:k8s}" subsys=endpoint
2019-03-06T10:10:51.598368316Z level=debug msg="Assigning security relevant label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.kubernetes.pod.namespace Value:default Source:k8s}" subsys=endpoint
2019-03-06T10:10:51.598370861Z level=debug msg="Endpoint has reserved identity, changing synchronously" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpoint
2019-03-06T10:10:51.598386235Z level=debug msg="Resolving identity for labels" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpoint
2019-03-06T10:10:53.470964185Z level=debug msg="Associated container event with endpoint" containerID=16391b8c87 containerName=/k8s_POD_testds-p66fr_default_6c6922aa-3ff7-11e9-8048-080027051dad_7 endpointID=3388 maxRetry=20 retry=2 subsys=workload-watcher willRetry=true
2019-03-06T10:10:53.478027947Z level=debug msg="Refreshing labels of endpoint" containerID=16391b8c87 endpointID=3388 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" infoLabels="container:annotation.kubernetes.io/config.seen=2019-03-06T10:05:51.983740119Z,container:annotation.kubernetes.io/config.source=api,container:io.kubernetes.container.name=POD,container:io.kubernetes.docker.type=podsandbox,container:io.kubernetes.pod.name=testds-p66fr,container:io.kubernetes.pod.uid=6c6922aa-3ff7-11e9-8048-080027051dad,k8s:controller-revision-hash=3749195971,k8s:pod-template-generation=1" subsys=endpoint
2019-03-06T10:10:53.478091862Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.kubernetes.docker.type Value:podsandbox Source:container}" subsys=endpoint
2019-03-06T10:10:53.478172299Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:annotation.kubernetes.io/config.seen Value:2019-03-06T10:05:51.983740119Z Source:container}" subsys=endpoint
2019-03-06T10:10:53.478217688Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.kubernetes.container.name Value:POD Source:container}" subsys=endpoint
2019-03-06T10:10:53.478281765Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.kubernetes.pod.name Value:testds-p66fr Source:container}" subsys=endpoint
2019-03-06T10:10:53.478325882Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:annotation.kubernetes.io/config.source Value:api Source:container}" subsys=endpoint
2019-03-06T10:10:53.478391275Z level=debug msg="Assigning information label" containerID=16391b8c87 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr obj="{Key:io.kubernetes.pod.uid Value:6c6922aa-3ff7-11e9-8048-080027051dad Source:container}" subsys=endpoint
2019-03-06T10:11:01.621961702Z level=debug msg="Deleting CEP on first run" containerID=16391b8c87 controller="sync-to-k8s-ciliumendpoint (3388)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpointsynchronizer
2019-03-06T10:11:21.642926412Z level=debug msg="Skipping CiliumEndpoint update because it has not changed" containerID=16391b8c87 controller="sync-to-k8s-ciliumendpoint (3388)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpointsynchronizer
2019-03-06T10:11:31.645149409Z level=debug msg="Skipping CiliumEndpoint update because it has not changed" containerID=16391b8c87 controller="sync-to-k8s-ciliumendpoint (3388)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpointsynchronizer
2019-03-06T10:11:33.830000777Z level=debug msg="GET /endpoint/{id} request" endpointID=3388 subsys=daemon
2019-03-06T10:11:33.885565953Z level=debug msg="GET /endpoint/{id}/log request" endpointID=3388 subsys=daemon
2019-03-06T10:11:33.94123384Z level=debug msg="GET /endpoint/{id}/log request" endpointID=3388 subsys=daemon
2019-03-06T10:11:41.646667686Z level=debug msg="Skipping CiliumEndpoint update because it has not changed" containerID=16391b8c87 controller="sync-to-k8s-ciliumendpoint (3388)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3388 ipv4=10.10.0.210 ipv6= k8sPodName=default/testds-p66fr subsys=endpointsynchronizer
```

**Comment by tgraf** [comment] 2019-03-06 12:02
The local kvstore lock was already acquired and required forceful unlocking
```
2019-03-06T10:11:16.685469074Z level=warning msg="Timeout while waiting for lock, forcefully unlocking..." path="cilium/state/identities/v1/locks/k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:zgroup=testDS;" subsys=kvstore
```

It does not succeed afterwards though

**Comment by tgraf** [comment] 2019-03-06 12:19
etcd connectivity is achieved *before* the endpoint is created:
```
2019-03-06T10:06:11.708565458Z level=debug msg="Session received" config=/var/lib/etcd-config/etcd.config endpoints="[https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
```

The fact that the local kvstore lock is contended means that a kvstore write is failing for a long time even though kvstore connectivity is there. This may indicate lack of quorum.

**Comment by tgraf** [comment] 2019-03-06 12:26
So I think we have several problems:
- We don’t cancel the identity allocation when the API call times out. This causes continued identity resolution due to the allocator retrying.
- It’s unclear why the kvstore operation doesn’t succeed eventually as the other node is using the kvstore successfully. It is possible that this is just bad luck in the sense that because we have several identity resolution go routines in place that are not getting cancelled, the latest create API call *always* blocks on the local kvstore lock and thus can’t complete in time.

**Comment by jrfastab** [comment] 2019-03-06 16:18
With transparent encryption enabled I also hit this consistently, maybe interestingly I don't see it in k8s version 1.13.
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10505/

**Comment by jrfastab** [comment] 2019-03-19 20:26
Got a similar trace from recent CI failures today.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10861/testReport/junit/k8s-1/13/K8sDatapathConfig_Transparent_encryption_with_IPv4Only_Check_connectivity_with_transparent_encryption_enabled_and_IPv6_disabled/

**Comment by borkmann** [comment] 2019-04-04 11:30
Seen in #7583 recently

**Comment by tgraf** [comment] 2019-04-09 16:34
Duplicate of #7598

**Closed as completed by tgraf** 2019-04-09 16:34 UTC
Labels: priority/high, area/CI
