### ISSUE TITLE
Configuring dns-based egress network rules causes dns resolution failure when this pod accesses any address.

### ISSUE THREAD

**Issue by pretty66** [cilium/cilium#18900] opened 2022-02-23 08:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Here is my rule config file
I turned on nodelocaldns, so I did not configure toEndpoint, so that he can use all dns address resolution

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn-pprof"
  namespace: msp
spec:
  endpointSelector:
    matchLabels:
      app: pprof
  egress:
  - toFQDNs:
    - matchPattern: '*.baidu.com'
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
```
### pprof pod log
```shell
$ curl www.baidu.com
curl: (6) Could not resolve host: www.baidu.com
```

### cilium monitor
```shell
$ cilium monitor --related-to 798 -vv
Listening for events on 4 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
CPU 01: MARK 0x7fba2619 FROM 798 DEBUG: Conntrack lookup 1/2: src=10.0.1.138:36225 dst=169.254.25.10:53
CPU 01: MARK 0x7fba2619 FROM 798 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1
CPU 01: MARK 0x7fba2619 FROM 798 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x7fba2619 FROM 798 DEBUG: Successfully mapped addr=169.254.25.10 to identity=2
level=info msg="Initializing dissection cache..." subsys=monitor
Policy verdict log: flow 0x7fba2619 local EP ID 798, remote ID world, proto 17, egress, action redirect, match L4-Only, 10.0.1.138:36225 -> 169.254.25.10:53 udp
CPU 01: MARK 0x7fba2619 FROM 798 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=61914 lb=0.0.0.0
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=1e:ce:69:ff:58:b5 DstMAC=8a:cb:e2:9e:93:a4 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..66..] Version=4 IHL=5 TOS=0 Length=86 Id=64123 Flags=DF FragOffset=0 TTL=64 Protocol=UDP Checksum=29065 SrcIP=10.0.1.138 DstIP=169.254.25.10 Options=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..58..] SrcPort=36225 DstPort=53(domain) Length=66 Checksum=52965}
  Failed to decode layer: No decoder for layer type DNS
CPU 01: MARK 0x7fba2619 FROM 798 to-proxy: 100 bytes (100 captured), state new, , identity 61914->unknown, orig-ip 0.0.0.0, to proxy-port 28385
CPU 01: MARK 0x7fba2619 FROM 798 DEBUG: CT entry found lifetime=57710, revnat=0
CPU 03: MARK 0x7fba2619 FROM 798 DEBUG: Conntrack lookup 1/2: src=10.0.1.138:36225 dst=169.254.25.10:53
CPU 03: MARK 0x7fba2619 FROM 798 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1
CPU 03: MARK 0x7fba2619 FROM 798 DEBUG: CT entry found lifetime=8922686, revnat=0
CPU 03: MARK 0x7fba2619 FROM 798 DEBUG: CT verdict: Established, revnat=0
CPU 03: MARK 0x7fba2619 FROM 798 DEBUG: Successfully mapped addr=169.254.25.10 to identity=2
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=1e:ce:69:ff:58:b5 DstMAC=8a:cb:e2:9e:93:a4 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..66..] Version=4 IHL=5 TOS=0 Length=86 Id=64124 Flags=DF FragOffset=0 TTL=64 Protocol=UDP Checksum=29064 SrcIP=10.0.1.138 DstIP=169.254.25.10 Options=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..58..] SrcPort=36225 DstPort=53(domain) Length=66 Checksum=52965}
  Failed to decode layer: No decoder for layer type DNS
CPU 03: MARK 0x7fba2619 FROM 798 to-proxy: 100 bytes (100 captured), state established, , identity 61914->unknown, orig-ip 0.0.0.0, to proxy-port 28385
CPU 03: MARK 0x7fba2619 FROM 798 DEBUG: CT entry found lifetime=57710, revnat=0
CPU 03: MARK 0x0 FROM 798 DEBUG: Conntrack lookup 1/2: src=169.254.25.10:53 dst=10.0.1.138:36225
CPU 03: MARK 0x0 FROM 798 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=0
CPU 03: MARK 0x0 FROM 798 DEBUG: CT entry found lifetime=8922686, revnat=0
CPU 03: MARK 0x0 FROM 798 DEBUG: CT verdict: Reply, revnat=0
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..198..] SrcMAC=8a:cb:e2:9e:93:a4 DstMAC=1e:ce:69:ff:58:b5 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..174..] Version=4 IHL=5 TOS=0 Length=194 Id=44272 Flags=DF FragOffset=0 TTL=63 Protocol=UDP Checksum=49064 SrcIP=169.254.25.10 DstIP=10.0.1.138 Options=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..166..] SrcPort=53(domain) DstPort=36225 Length=174 Checksum=53073}
  Failed to decode layer: No decoder for layer type DNS
CPU 03: MARK 0x0 FROM 798 to-proxy: 208 bytes (208 captured), state new, interface lxcfa238b33932b, , identity world->61914, orig-ip 169.254.25.10
CPU 03: MARK 0x0 FROM 798 DEBUG: CT entry found lifetime=0, revnat=0
CPU 03: MARK 0x0 FROM 798 DEBUG: Conntrack lookup 1/2: src=169.254.25.10:53 dst=10.0.1.138:36225
CPU 03: MARK 0x0 FROM 798 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=0
CPU 03: MARK 0x0 FROM 798 DEBUG: CT entry found lifetime=8922686, revnat=0
CPU 03: MARK 0x0 FROM 798 DEBUG: CT verdict: Reply, revnat=0
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..198..] SrcMAC=8a:cb:e2:9e:93:a4 DstMAC=1e:ce:69:ff:58:b5 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..174..] Version=4 IHL=5 TOS=0 Length=194 Id=44273 Flags=DF FragOffset=0 TTL=63 Protocol=UDP Checksum=49063 SrcIP=169.254.25.10 DstIP=10.0.1.138 Options=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..166..] SrcPort=53(domain) DstPort=36225 Length=174 Checksum=53073}
  Failed to decode layer: No decoder for layer type DNS
CPU 03: MARK 0x0 FROM 798 to-proxy: 208 bytes (208 captured), state new, interface lxcfa238b33932b, , identity world->61914, orig-ip 169.254.25.10
CPU 03: MARK 0x0 FROM 798 DEBUG: CT entry found lifetime=0, revnat=0
------------------------------------------------------------------------------
CPU 03: MARK 0x0 FROM 798 DEBUG: 42 bytes, Delivery to ifindex 122301
Ethernet        {Contents=[..14..] Payload=[..30..] SrcMAC=8a:cb:e2:9e:93:a4 DstMAC=1e:ce:69:ff:58:b5 EthernetType=ARP Length=0}
  Failed to decode layer: No decoder for layer type ARP
```

### Cilium Version

v1.11.1

### Kernel Version

5.4.0-73-generic

### Kubernetes Version

v1.17.12-18+005664a3058b3a

### Sysdump

file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment] 2022-03-03 01:10
Hi, this seems to be duplicate of https://github.com/cilium/cilium/issues/18644 please see https://github.com/cilium/cilium/issues/18644#issuecomment-1041230699 with a proposed solution.

**Comment by pretty66** [comment] 2022-03-04 06:27
> Hi, this seems to be duplicate of #18644 please see [#18644 (comment)](https://github.com/cilium/cilium/issues/18644#issuecomment-1041230699) with a proposed solution.

Thanks for your reply, his scheme didn't work for me. My problem is that domain name resolution fails as long as it passes through cilium-agent dns proxy.

- My configuration, allow access to all domains
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn-pprof"
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app: pprof
  egress:
  - toFQDNs: 
    - matchPattern: "*"  
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
```

**Comment by pretty66** [comment] 2022-03-12 04:35
I have found the reason for this problem. The reason is that calico has been installed in the cluster before, and the iptables rule remains after uninstalling calico, which leads to the problem of the cilium DNS policy;

After I cleaned up all the calico related iptables rules, it returned to normal

**Closed as completed** 2022-03-14 06:50 UTC
Labels: kind/bug, needs/triage, kind/community-report
