### ISSUE TITLE
Ever increasing Xfrm error count when ipsec is enabled

### ISSUE THREAD

**Issue by isala404** [cilium/cilium#26954] opened 2023-07-20 11:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We recently deployed Cilium with IPsec enabled in a cluster comprising approximately 250 pods. Based on the service-level testing we conducted, everything appears to be functioning as expected. Additionally, when we inspected the `cilium_vxlan` interface using `tcpdump`, we could observe the proper flow of `esp` packets.

However, during our assessment of the encryption status using `cilium encrypt status`, we encountered a somewhat concerning number of Xfrm errors, particularly `XfrmOutPolBlock`. In one of the nodes with a higher number of pods, we observed this specific error to be at 709,924. Notably, this number increases every time we execute the `cat /proc/net/xfrm_stat` command on the Cilium agent daemonset.

For the installation of Cilium on our AKS cluster, we utilized the following Helm command in conjunction with the bring your own CNI mode:

```sh
helm upgrade --install cilium cilium/cilium --version 1.13.4 \
  --namespace kube-system \
  --set aksbyocni.enabled=true \
  --set nodeinit.enabled=true \
  --set encryption.enabled=true \
  --set encryption.type=ipsec \
  --set hubble.enabled=true \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true 
```

The error counter stop as soon as we set the `encryption.enabled` false. So any insight on this issue would be appreciated.  

### Cilium Version

1.13.2 and 1.13.4

### Kernel Version

5.4.0-1106-azure

### Kubernetes Version

1.24.9

### Anything else?

cilium encrypt status
```
Encryption: IPsec                     
Keys in use: 1                         
Max Seq. Number: 0x8b194/0xffffffff
Errors: 710577                    
	XfrmInNoStates: 646                       
	XfrmOutPolBlock: 709930                    
	XfrmInError: 1   
```

/proc/net/xfrm_stat
```
XfrmInError             	1
XfrmInBufferError       	0
XfrmInHdrError          	0
XfrmInNoStates          	646
XfrmInStateProtoError   	0
XfrmInStateModeError    	0
XfrmInStateSeqError     	0
XfrmInStateExpired      	0
XfrmInStateMismatch     	0
XfrmInStateInvalid      	0
XfrmInTmplMismatch      	0
XfrmInNoPols            	0
XfrmInPolBlock          	0
XfrmInPolError          	0
XfrmOutError            	0
XfrmOutBundleGenError   	0
XfrmOutBundleCheckError 	0
XfrmOutNoStates         	0
XfrmOutStateProtoError  	0
XfrmOutStateModeError   	0
XfrmOutStateSeqError    	0
XfrmOutStateExpired     	0
XfrmOutPolBlock         	709930
XfrmOutPolDead          	0
XfrmOutPolError         	0
XfrmFwdHdrError         	0
XfrmOutStateInvalid     	0
XfrmAcquireError        	0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment] 2023-07-20 22:43
Hi, Can you check if this PR resolves your issue - https://github.com/cilium/cilium/pull/25735?

**Comment by MrSupiri** [comment] 2023-07-21 09:07
Hi @aditighag, we actually did a fresh install of version `1.13.4`, and we even tried refreshing all the nodes. However, the `XfrmOutPolBlock` error counter never stops, even days after the installation. We scaled up the node pool and tested as well. Interestingly, we noticed that the newer nodes also immediately start to collect `XfrmOutPolBlock` errors as soon as some pods are scheduled on the node, and this issue never seems to stop.

**Comment by pchaigno** [comment] 2023-07-21 09:54
We don't recommend using this release for IPsec. See the big warning in release notes: https://github.com/cilium/cilium/releases/tag/v1.13.4.

If you want to enable IPsec, I would suggest to use v1.13.0 or v1.12.7. We are actively working on fixes and will update here once we have them ready.

**Comment by MrSupiri** [comment] 2023-07-22 12:24
Hi @pchaigno,

We were originally using version `v1.13.2`, and we completely purged it to install version `v1.13.4`. The main reason for upgrading to `v1.13.4` was because it included numerous fixes related to ipsec. Additionally, in the release notes, we were unsure if there was a warning about upgrading from a lower version, so we decided to avoid that release if ipsec was being used. Meanwhile would test out `v1.13.0` and get back to you as well.

**Comment by MrSupiri** [comment] 2023-07-24 11:57
Hi @pchaigno,

We removed the existing Helm release and deployed version `1.13.0` today. As soon as it was deployed, the error counters stopped increasing. So, we performed a node refresh to check if all the newer nodes would have an error count of 0. However, I noticed that during the refreshing period, the error count seemed to be increasing again. But as soon as all the nodes were up and running, and all the pods were scheduled, the error count stopped increasing.

Thank you for assisting with this. I hope the issue we saw on versions `1.13.2` and above will be fixed in a future release.

**Comment by pchaigno** [comment] 2023-07-24 12:01
> I hope the issue we saw on versions `1.13.2` and above will be fixed in a future release.

We're working on it. Those `XfrmOutPolBlock` errors have proved trickier to fix than other bugs we hit (cf. https://github.com/cilium/cilium/pull/26725).

**Comment by MrSupiri** [comment] 2023-07-24 15:23
Ah right good to know, let me know if there is anything I can do help!

**Comment by pchaigno** [comment] 2023-08-02 09:39
@MrSupiri We expect #27029 fixed this issue with XfrmOutPolBlock errors. If you can confirm with [that PR's image builds](https://github.com/cilium/cilium/actions/runs/5668133022/job/15358612171), that would be great!

**Comment by MrSupiri** [comment] 2023-08-11 06:39
Hi @pchaigno sorry about the delay, I tried using the ci images and running cilium but this lead to a `CrashLoopBackOff` of cilium agent pods.

Command I used to install cilium
```
helm install cilium cilium/cilium --version 1.13.5   --namespace kube-system   --set aksbyocni.enabled=true   --set nodeinit.enabled=true   --set encryption.enabled=true   --set encryption.type=ipsec   --set hubble.enabled=true   --set hubble.relay.enabled=true   --set hubble.ui.enabled=true --set image.repository="quay.io/cilium/cilium-ci" --set image.tag="ffb1591ffca925599e253a1ddf84b280a44c2c4a" --set image.useDigest=false
```

Log:
```
$ kubectl -n kube-system get pods | grep cilium
cilium-49b4x                                       0/1     CrashLoopBackOff    4 (24s ago)      22m
cilium-4wrlg                                       0/1     CrashLoopBackOff    13 (2m12s ago)   22m
cilium-node-init-5kjkx                             1/1     Running             0                22m
cilium-node-init-bhtwb                             1/1     Running             1 (5m16s ago)    22m
cilium-operator-7f8b898b56-czc8k                   1/1     Running             0                22m
$ 
$ kubectl -n kube-system logs cilium-49b4x --previous
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init), install-cni-binaries (init)
$ 
$ kubectl -n kube-system logs cilium-49b4x -c config
Running
level=info msg=Invoked duration="387.656µs" function="cmd.glob..func36 (build-config.go:32)" subsys=hive
level=info msg=Starting subsys=hive
level=info msg="Establishing connection to apiserver" host="https://172.19.0.1:443" subsys=k8s-client
level=info msg="Connected to apiserver" subsys=k8s-client
level=info msg="Start hook executed" duration=31.269037ms function="client.(*compositeClientset).onStart" subsys=hive
level=info msg="Reading configuration from config-map:kube-system/cilium-config" configSource="config-map:kube-system/cilium-config" subsys=option-resolver
level=info msg="Got 85 config pairs from source" configSource="config-map:kube-system/cilium-config" subsys=option-resolver
level=info msg="Reading configuration from cilium-node-config:kube-system/" configSource="cilium-node-config:kube-system/" subsys=option-resolver
level=info msg="Got 0 config pairs from source" configSource="cilium-node-config:kube-system/" subsys=option-resolver
level=info msg="Start hook executed" duration=14.13608ms function="cmd.(*buildConfig).onStart" subsys=hive
level=info msg=Stopping subsys=hive
level=info msg="Stop hook executed" duration="22.013µs" function="client.(*compositeClientset).onStop" subsys=hive
$ 
$ kubectl -n kube-system logs cilium-49b4x -c mount-cgroup
level=info msg="Mounted cgroupv2 filesystem at /run/cilium/cgroupv2" subsys=cgroups
$ 
$ kubectl -n kube-system logs cilium-49b4x -c apply-sysctl-overwrites
sysctl config created/updated
systemd unit 'systemd-sysctl.service' restarted
$ 
$ kubectl -n kube-system logs cilium-49b4x -c mount-bpf-fs
$ 
$ kubectl -n kube-system logs cilium-49b4x -c wait-for-node-init
$ 
$ kubectl -n kube-system logs cilium-49b4x -c clean-cilium-state
$ 
$ kubectl -n kube-system logs cilium-49b4x -c install-cni-binaries
Installing cilium-cni to /host/opt/cni/bin/ ...
wrote /host/opt/cni/bin/cilium-cni
$
```

Did I do something wrong here while installing?

**Comment by margamanterola** [comment] 2023-08-18 09:39
1.13.6 has been released and it includes the fix that Paul mentioned above. You could try upgrading to that release and verify if you still see the increasing errors or not. Please note that even with 1.13.6 there are still some problems with the IPSec stack, in particular there's a chance that during key rotations packets get dropped and ongoing connections get interrupted.

**Comment by pchaigno** [comment] 2023-08-21 14:58
@MrSupiri The error you hit is likely because you are trying to use the images from the PR (built for unreleased main) with a v1.13 release. Testing v1.13.6 as suggested by Marga above is likely the easiest way to test the fix now.

**Comment by MrSupiri** [comment] 2023-08-21 15:53
Hi @margamanterola and @pchaigno,

I just tested this issue in the same cluster with v1.13.6 and it seems to have resolved the issue.

Still there are some Xfrm errors as soon as cilium was deployed but upon rechecking it after about 40 minutes, I noticed the error counts stayed the same. I assume this is the expected behaviour.

example encryption status of a pod:
```
Encryption: IPsec                     
Keys in use: 1                         
Max Seq. Number: 0xbb488c6/0xffffffff
Errors: 101                       
	XfrmOutNoStates: 78                        
	XfrmFwdHdrError: 6                         
	XfrmInError: 1                         
	XfrmInNoStates: 16  
```

**Comment by pchaigno** [comment] 2023-08-21 16:22
Thanks for checking!

> Still there are some Xfrm errors as soon as cilium was deployed but upon rechecking it after about 40 minutes, I noticed the error counts stayed the same. I assume this is the expected behaviour.

Depending on what you upgraded from, what the state of IPsec (enabled/disabled) was before, and what XFRM errors were already present, it may be expected, yes.

**Closed as completed** 2023-08-22 04:08 UTC
Labels: kind/bug, area/datapath, kind/community-report, area/encryption
