### ISSUE TITLE
RTNETLINK answers: Invalid argument We have an error talking to the kernel

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#987] opened 2017-06-15 03:34 UTC
I am trying to load bpf instrument via "tc filter add dev $DEV prio 1 handle 1 bpf da obj $OUT sec $5"

**output:**
RTNETLINK answers: Invalid argument
We have an error talking to the kernel

**I verified dmesg:**  [1724588.845950] IPv6: ADDRCONF(NETDEV_UP): cilium_host: link is not ready
[1724588.846210] IPv6: ADDRCONF(NETDEV_CHANGE): cilium_host: link becomes ready
[1724589.592157] cilium_net: Caught tx_queue_len zero misconfig
but I don't think it is caused by this.

**I compile by hand:**  clang -D__NR_CPUS__=4 -O2 -target bpf -I/var/run/cilium/state/globals -I. -I/var/lib/cilium/bpf/include -DENABLE_ARP_RESPONDER -DHANDLE_NS -Wno-address-of-packed-member -Whon-unknown-warning-option -DFIXED_SRC_SECCTX=1 -DSECLABEL=1 -DPOLICY_MAP=cilium_policy_reserved_1 -DCALLS_MAP=cilium_calls_netdev_ns_1 -DNODE_MAC={.addr={0x76,0xf4,0x80,0x4c,0xac,0x89}} -c /var/lib/cilium/bpf/bpf_netdev.c -o bpf_netdev.o

**output:**
 /var/run/cilium/state/globals/bpf_features.h:1:2: error: unterminated conditional directive
#ifndef BPF_FEATURES_H_
 ^
7 warnings and 1 error generated.

**Here is my bpf_features.h file:**

#ifndef BPF_FEATURES_H_
#define BPF_FEATURES_H_

#define HAVE_SKB_CHANGE_TAIL

#define HAVE_SET_HASH_INVALID

// #define HAVE_LPM_MAP_TYPE

#if 0
HAVE_LPM_MAP_TYPE failed due to load error: Invalid argument
fd 0 is not pointing to valid bpf_map
#endif

#define HAVE_LRU_MAP_TYPE

#define HAVE_MAP_VAL_ADJ

#define HAVE_MARK_MAP_VALS

#endif /* BPF_FEATURES_H_ */

I found this bpf features file is updated continuously... 

This is all I collected, do you have any idea about it ? @aanm @tgraf

**Comment by tgraf** [comment] 2017-06-15 12:05
> /var/run/cilium/state/globals/bpf_features.h:1:2: error: unterminated conditional directive
> #ifndef BPF_FEATURES_H_

Based on this error, it looks like you have an `#ifdef` `#endif` mismatch before you include `bpf_features.h`

**Comment by tgraf** [comment] 2017-06-15 12:50
@peiqi-caicloud I'm seeing this issue as well now, looking into it.

**Comment by borkmann** [comment] 2017-06-15 13:42
With regards to the netlink error, were you missing the `ingress` keyword?

Should say: `tc filter add dev $DEV ingress prio 1 handle 1 bpf da obj $OUT sec $5`

If you do a `tc qdisc show dev $DEV` by hand, do you see a line that looks like `qdisc clsact ffff: parent ffff:fff1`? If not, you would need a prior `tc qdisc add dev $DEV clsact`.

The netlink error is definitely triggered in case of a missing `ingress` in the command line.

**Comment by borkmann** [comment] 2017-06-15 13:53
The `cilium_net: Caught tx_queue_len zero misconfig` is harmless, by the way.

**Comment by tgraf** [comment] 2017-06-15 13:54
> output:
> /var/run/cilium/state/globals/bpf_features.h:1:2: error: unterminated conditional directive
> #ifndef BPF_FEATURES_H_
> ^
> 7 warnings and 1 error generated.

I saw this error as well. Rebooting my VM resolved the issue for me. I was not able to track it down further.

**Comment by borkmann** [comment] 2017-06-15 14:42
@peiqi-caicloud Do you by any chance have a reliable way to reproduce the `BPF_FEATURES_H_` related compilation error?

**Comment by tgraf** [comment] 2017-06-20 21:21
Closing this for now, please reopen when it occurs again

**Closed as completed by tgraf** 2017-06-20 21:21 UTC
Labels: kind/question
