### ISSUE TITLE
Connection RST on pod -> remote pod with host firewall and kube-proxy in native routing mode

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14859] opened 2021-02-04 15:37 UTC
Running on Linux 4.9 (thus using kube-proxy), with native routing and the host firewall enabled, connections between pods across nodes are failing due to some masquerading issue:

Command run:
```
k8s1$ curl http://10.0.1.8:4240/hello
```
On k8s1:
```
-> network flow 0xf231cb6 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp SYN
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
-> network flow 0xf231cb6 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
-> network flow 0xf231cb6 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.12:4240 -> 192.168.36.11:40298 tcp ACK
-> network flow 0x0 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 192.168.36.12:4240 tcp RST
```
On k8s2:
```
-> network flow 0xe436ad37 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: [fd04::12]:59446 -> [fd02::7c]:4240 tcp SYN
-> network flow 0x1412a947 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: [fd04::12]:59446 -> [fd02::7c]:4240 tcp SYN
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp SYN
-> endpoint 1188 flow 0x0 identity world->health state new ifindex lxc_health orig-ip 192.168.36.11: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp SYN
<- endpoint 1188 flow 0xc14d6817 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
-> stack flow 0xc14d6817 identity health->remote-node state reply ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
-> network flow 0xc14d6817 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
-> endpoint 1188 flow 0x0 identity world->health state established ifindex lxc_health orig-ip 192.168.36.11: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
-> endpoint 1188 flow 0x0 identity world->health state established ifindex lxc_health orig-ip 192.168.36.11: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
<- endpoint 1188 flow 0xc14d6817 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp ACK
-> stack flow 0xc14d6817 identity health->remote-node state reply ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp ACK
-> network flow 0xc14d6817 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.12:4240 -> 192.168.36.11:40298 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 192.168.36.12:4240 tcp RST
```

The part I don't understand yet is: why is the ACK packet from 10.0.1.8 to 192.168.36.11 SNATed if the previous SYN+ACK with same origin/dest. wasn't SNATed??

**Comment by pchaigno** [comment] 2021-03-19 17:12
Might be related to https://github.com/cilium/cilium/issues/15403.

**Comment by nam-jaehyun** [comment] 2021-04-18 15:20
The key point is that the IP addresses assigned to pods are considered non-cluster IP addresses in the direct routing mode. That's why the SNAT was applied in inter-container communications.
If we add something like the following rules, I think this problem can be solved.

MASK all -- [allocRange] [Pod network CIDR] MASK or 0xAA00
MASK all -- [allocRange] ![snatDstExclusionCIDR] MASK or 0x00BB
MASQUERADE all -- [allocRange] 0.0.0.0/0 mark match (!0xAA00|0x00BB)

Do I correctly understand the issue? and do you think this approach covers the issue?

**Comment by pchaigno** [comment] 2021-04-19 07:46
> The key point is that the IP addresses assigned to pods are considered non-cluster IP addresses in the direct routing mode.

No, IP addresses assigned to pods are considered in-cluster IP addresses of course.

> the IP addresses assigned to pods are considered non-cluster IP addresses in the direct routing mode. That's why the SNAT was applied in inter-container communications.

I suspect k8s2's pod IP was SNATed because of https://github.com/cilium/cilium/issues/15403, but it's a bit weird that it didn't happen for the TCP SYN+ACK packet.

**Comment by jibi** [comment] 2021-05-04 10:41
I am not able to reproduce this.

So far I spawned a couple of 4.9 VMs:
```
$ KERNEL=49 KUBEPROXY=1 NFS=1 K8S=1 NWORKERS=1 VM_CPUS=8 VM_MEMORY=6144 ./contrib/vagrant/start.sh
```

configured Cilium to use direct routing and host firewall:
```
CILIUM_OPTS="      --debug --pprof --enable-hubble --hubble-listen-address :4244 --enable-k8s-event-handover       --k8s-require-ipv4-pod-cidr --enable-bandwidth-manager --kube-proxy-replacement disabled       --enable-remote-node-identity --enable-ipv6-ndp --ipv6-mcast-device enp0s8 --k8s-kubeconfig-path /var/lib/cilium/cilium.kubeconfig --kvstore etcd --kvstore-opt etcd.config=/var/lib/cilium/etcd-config.yml -t disabled --native-routing-cidr 10.11.0.0/16 --auto-direct-node-routes --enable-host-firewall true --devices enp0s8"
```

Deployed a couple of pods on 2 different nodes:
```
vagrant@k8s1:~$ k get pods -o wide
NAME            READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
ubuntu-1        1/1     Running   0          7m17s   10.11.0.204     k8s1   <none>           <none>
ubuntu-2        1/1     Running   0          7m17s   10.11.1.30      k8s2   <none>           <none>
```

and tested the connectivity with netcat. Traffic is flowing back and forth and I'm not seeing anything unusual on tcpdump:

```
vagrant@k8s1:~$ sudo tcpdump -i enp0s8 port 1234 -n
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp0s8, link-type EN10MB (Ethernet), capture size 262144 bytes
10:38:51.595458 IP 10.11.1.30.40354 > 10.11.0.204.1234: Flags [S], seq 1841402351, win 29200, options [mss 1460,sackOK,TS val 1240145 ecr 0,nop,wscale 7], length 0
10:38:51.596645 IP 10.11.0.204.1234 > 10.11.1.30.40354: Flags [S.], seq 3686521199, ack 1841402352, win 28960, options [mss 1460,sackOK,TS val 1358765 ecr 1240145,nop,wscale 7], length 0
10:38:51.598229 IP 10.11.1.30.40354 > 10.11.0.204.1234: Flags [.], ack 1, win 229, options [nop,nop,TS val 1240146 ecr 1358765], length 0
10:38:52.893294 IP 10.11.1.30.40354 > 10.11.0.204.1234: Flags [P.], seq 1:4, ack 1, win 229, options [nop,nop,TS val 1240470 ecr 1358765], length 3
10:38:52.894130 IP 10.11.0.204.1234 > 10.11.1.30.40354: Flags [.], ack 4, win 227, options [nop,nop,TS val 1359090 ecr 1240470], length 0
10:38:54.495076 IP 10.11.1.30.40354 > 10.11.0.204.1234: Flags [F.], seq 4, ack 1, win 229, options [nop,nop,TS val 1240870 ecr 1359090], length 0
10:38:54.495998 IP 10.11.0.204.1234 > 10.11.1.30.40354: Flags [F.], seq 1, ack 5, win 227, options [nop,nop,TS val 1359490 ecr 1240870], length 0
10:38:54.497690 IP 10.11.1.30.40354 > 10.11.0.204.1234: Flags [.], ack 2, win 229, options [nop,nop,TS val 1240871 ecr 1359490], length 0
^C
8 packets captured
8 packets received by filter
0 packets dropped by kernel
```

I'm not sure if I'm using the wrong configuration or maybe the issue got somehow fixed in the past couple of months?

**Comment by pchaigno** [comment] 2021-05-04 12:13
:thinking: 

I initially hit this while working on test `K8sDatapathConfig Host firewall With native routing`: https://github.com/cilium/cilium/blob/dfb822001f63fac4a5cc38240367f5a16bb8782f/test/k8sT/DatapathConfiguration.go#L794-L795
If it looks like it's solved, let's maybe reenable that test?

**Comment by jibi** [comment] 2021-05-04 13:28
OK, now I can reproduce the failure:
```15:24:34 STEP: Checking host policies on egress to remote pod
15:24:34 STEP: WaitforPods(namespace="202105041523k8sdatapathconfighostfirewallwithnativerouting", filter="-l zgroup=testClientHost")
15:24:34 STEP: WaitforPods(namespace="202105041523k8sdatapathconfighostfirewallwithnativerouting", filter="-l zgroup=testClientHost") => <nil>
15:24:34 STEP: WaitforPods(namespace="202105041523k8sdatapathconfighostfirewallwithnativerouting", filter="-l zgroup=testServer")
15:24:34 STEP: WaitforPods(namespace="202105041523k8sdatapathconfighostfirewallwithnativerouting", filter="-l zgroup=testServer") => <nil>
FAIL: Failed to reach 10.0.0.9:80 from testclient-host-4xmqj
Expected command: kubectl exec -n 202105041523k8sdatapathconfighostfirewallwithnativerouting testclient-host-4xmqj -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.0.0.9:80/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To succeed, but it failed:
Exitcode: 28

```
potentially something related to the policies that the test uses, looking into it

**Comment by jibi** [comment] 2021-05-04 15:20
I managed to reproduce this on the dev VM. Worth nothing that the problem:
* does not involve any host firewall policy:
  ```
  vagrant@k8s1:~$ k get ccnp
  No resources found
  ```
* does only happen when the client pod is attached to the host network:
  ```
  vagrant@k8s1:~$ k exec -it testclient-xsq5d -- curl -s 10.11.0.57:80/ > /dev/null
  vagrant@k8s1:~$
  ```
  ```
  vagrant@k8s1:~$ k exec -it testclient-host-6dgdq -- curl -s 10.11.0.57:80/ > /dev/null
  command terminated with exit code 56
  ```

**Comment by jibi** [comment] 2021-05-07 07:17
Quick update: the scope of this issue is probably larger than we anticipated as:
* it doesn't involve host-fw
* it's not relegated to just 4.9 (I was able to reproduce it also on net-next)

This is the conf I'm currently using to investigate the bug:
```
CILIUM_OPTS="      --debug --pprof --enable-hubble --hubble-listen-address :4244 --enable-k8s-event-handover       --k8s-require-ipv4-pod-cidr --enable-bandwidth-manager --kube-proxy-replacement disabled       --enable-remote-node-identity --enable-ipv6-ndp --ipv6-mcast-device enp0s8 --k8s-kubeconfig-path /var/lib/cilium/cilium.kubeconfig --kvstore etcd --kvstore-opt etcd.config=/var/lib/cilium/etcd-config.yml -t disabled --native-routing-cidr 10.11.0.0/16 --auto-direct-node-routes"
```

**Comment by jibi** [comment] 2021-05-07 11:52
It seems like the culprit is indeed the rule mentioned in https://github.com/cilium/cilium/issues/15403:
```
MASQUERADE  all  --  10.11.0.0/24        !10.11.0.0/16         /* cilium masquerade non-cluster */
```

which is responsible for masquerading the reply traffic `remote pod` -> `k8s2`.

As a first attempt I replaced that with:
```
iptables -t nat -I CILIUM_POST_nat 1 -s 10.11.0.0/24 ! -d 10.11.0.0/16 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -m conntrack --ctorigsrc 10.11.0.0/24 -j MASQUERADE
```

to exclude from masquerading all traffic which is not originating from the node's pods, but for some reason this is not working (missing CT entry perhaps?)

**Comment by jibi** [comment] 2021-05-07 16:02
The previous attempt does not work because the CT entry for the connection is stored in the _pod_ netns rather than in the host netns (and so `-m conntrack --ctorigsrc 10.11.0.0/24` would not match anything since this rule lives in the host netns). 

A possible approach to tackle this (which would fix also #15403) would be to extend the masquerade rule to match both pods and nodes IPs. This could be achieved with the help of an ipset.

I quickly tested this (manually) with:

```
vagrant@k8s1:~$ sudo ipset create cilium_pods_nodes hash:net
vagrant@k8s1:~$ sudo ipset add cilium_pods_nodes 10.11.0.0/16
vagrant@k8s1:~$ sudo ipset add cilium_pods_nodes 192.168.33.11/32
vagrant@k8s1:~$ sudo ipset add cilium_pods_nodes 192.168.33.12/32
```

```
vagrant@k8s1:~$ sudo iptables -t nat -D CILIUM_POST_nat 1
vagrant@k8s1:~$ sudo iptables -t nat -I CILIUM_POST_nat 1 -s 10.11.0.0/24
    -m set ! --match-set cilium_pods_nodes dst ! -o cilium_+
    -m comment --comment "cilium masquerade non-cluster"
    -j MASQUERADE
```

And with this change, pod -> world connectivity keeps working:
```
vagrant@k8s1:~$ k exec -it testclient-k6nch  -- curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

and host -> remote pod connectivity starts working again:
```
vagrant@k8s2:~$ curl 10.11.0.101:80


Hostname: testserver-l65ns

Pod Information:
	-no pod information available-
..
```

**Comment by tgraf** [comment] 2021-05-11 16:32
I think the required work for this it larger than we can still take for the current release. Removing the release blocker.

**Comment by jibi** [comment] 2021-05-12 08:22
Latest findings: the masquerading issue shows up whenever Cilium auto derives the device for either KPR, host-firewall or bandwidth manager, causing:

* the `bpf_host` to be attached to that device
* ingress traffic directed to a pod to go through `bpf_host` and to be redirected to the pod's lxc device with `bpf_redirect()`
* by using `bpf_redirect()`, traffic will not be tracked by CT in the host ns
* this in turn causes the masquerade rule to (incorrectly) masquerade the reply traffic from the pod

**Closed as completed** 2021-06-22 12:42 UTC
Labels: kind/bug, needs/triage, area/kube-proxy, area/host-firewall
