### ISSUE TITLE
Stop annonsed to bgp peer podCidrs after creating Service LoadBalanser type

### ISSUE THREAD

**Issue by epollia** [cilium/cilium#17922] opened 2021-11-17 16:15 UTC
## Bug report
**General Information**

- Cilium version 1.11.0-rc1
- Kernel version 5.15.0-1
- Orchestration system version in use kubectl v1.22.3

```
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
    podCIDR: true

```
```
    address-pools:
      - name: default
        protocol: bgp
        avoid-buggy-ips: true
        addresses:
          - 10.60.250.0/24
```
**How to reproduce the issue**

1. Configure BGP, enable bgp.announce.podCIDR = true and loadbalancerIP = true
2. Create Service LoadBalancer

**Comment by gandro** [comment] 2021-11-18 10:24
Thanks for the report. Are you able to provide a sysdump with debug logs (Helm: `debug.enabled=true`)?

cc @ldelossa

**Comment by ldelossa** [comment] 2021-12-01 18:27
dupe of: https://github.com/cilium/cilium/issues/16967
please track in the aforementioned issue.

**Closed as completed by ldelossa** 2021-12-01 18:27 UTC
Labels: kind/bug, need-more-info, needs/triage, kind/community-report
