### ISSUE TITLE
LB BPF map with configurable size

### ISSUE THREAD

**Issue by Lyt99** [cilium/cilium#12815] opened 2020-08-07 13:17 UTC
Hi there, recently I'm testing scalability of cilium with 2000 services * 50 endpoints, and I've encountered a problem that a part of  services cannot be accessed properly. 

Then I found the log below:
> level=error msg="Error while inserting service in LB map" error="Unable to update service entry 172.21.2.0:80 => 69 (2001) [FLAGS: 0x0]: Unable to update element for map with file descriptor 13: argument list too long" k8sNamespace=stress-service k8sSvcName=nginx-service-1691 subsys=k8s-watcher

It seems that LB map cilium_lb4_services_v2 has exceed its limit, with a value of 65535.
I try to find out how to get it larger,  but there is no option to change this in the [document](https://docs.cilium.io/en/v1.8/concepts/ebpf/maps/).

And then I got [this](https://github.com/cilium/cilium/blob/master/pkg/datapath/linux/config/config.go#L133) in code refers to a const lbmap.MaxEntries, which is immutable.

Is there any way or plan to solve the problem?

**Comment by aanm** [comment] 2020-08-14 12:49
@Lyt99 @BSWANG the issue is fixed and merged on master. Thanks for reporting it.

**Closed as completed** 2020-08-14 12:49 UTC
Labels: help-wanted, good-first-issue, kind/feature, kind/community-report
