### ISSUE TITLE
CI: unit-test flake in services_test.go: ClusterMeshServicesTestSuite

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12807] opened 2020-08-07 10:14 UTC
https://travis-ci.com/github/cilium/cilium/jobs/369647899

```
----------------------------------------------------------------------
FAIL: services_test.go:217: ClusterMeshServicesTestSuite.TestClusterMeshServicesUpdate
services_test.go:272:
    s.expectEvent(c, k8s.DeleteService, svcID, nil)
services_test.go:129:
    c.Assert(event.Action, Equals, action)
... obtained k8s.CacheAction = 0 ("service-updated")
... expected k8s.CacheAction = 1 ("service-deleted")
OOPS: 5 passed, 1 FAILED
--- FAIL: Test (90.60s)
FAIL
coverage: 5.3% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/clustermesh	90.702s
FAIL
Makefile:209: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
Done. Your build exited with 1.
```

commit where the test failed: https://github.com/cilium/cilium/commit/b5f53047228eb205108ed13335cdd98d274a40b5

**Comment by christarazi** [comment] 2020-08-07 19:02
This is a duplicate of https://github.com/cilium/cilium/issues/12756

**Closed as completed** 2020-08-11 23:20 UTC
Labels: kind/duplicate, area/CI, ci/flake
