### ISSUE TITLE
kind support M1

### ISSUE THREAD

**Issue by adamzhoul** [cilium/cilium#18016] opened 2021-11-26 03:01 UTC
## Proposal / RFE

kind should be supported in M1 Mac.

**Is your feature request related to a problem?**

follow the instruct here: https://docs.cilium.io/en/v1.10/gettingstarted/kind/
and leads to :
```
kube-system          cilium-ldtw9                                   0/1     CrashLoopBackOff    124        18h
```

check the log:
```
level=fatal msg="BPF NodePort services needs kernel 4.17.0 or newer." subsys=daemon
```

check kernel:
```
docker exec -ti cilium-worker /bin/bash
root@cilium-worker:/# uname -a
Linux cilium-worker 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

the kernel is 5.10.47 and higher than 4.17.0.
anything I can do manually to make all this work?

**other background info**

recheck the config:
```
cat kind-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
```

see containers:
```
docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED        STATUS          PORTS                       NAMES
2e875f18a029   kindest/node:v1.21.1   "/usr/local/bin/entr…"   19 hours ago   Up 58 minutes   127.0.0.1:53490->6443/tcp   cilium-control-plane
635046d89c60   kindest/node:v1.21.1   "/usr/local/bin/entr…"   19 hours ago   Up 58 minutes                               cilium-worker3
55b2428e74d6   kindest/node:v1.21.1   "/usr/local/bin/entr…"   19 hours ago   Up 58 minutes                               cilium-worker
c222db8e2c7e   kindest/node:v1.21.1   "/usr/local/bin/entr…"   19 hours ago   Up 58 minutes                               cilium-worker2
```

docker version:
```
docker version
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:10 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Describe the solution you'd like**

is the `kind` image node missing some bpf tools or settings or files?
should we mention it in the doc or QA?

**Comment by pchaigno** [comment] 2021-11-26 10:36
```
level=fatal msg="BPF NodePort services needs kernel 4.17.0 or newer." subsys=daemon
```

That's probably because the kernel is missing config `CONFIG_CGROUP_BPF`. You can work around that by disabling kube-proxy-replacement.

**Comment by adamzhoul** [comment] 2021-11-26 10:58
thanks for answering.

can I manually add that config?
I wish to experience as many features of cilium as possible.

**Comment by pchaigno** [comment] 2021-11-26 11:01
Yes, but you'll need to recompile the kernel.

**Comment by adamzhoul** [comment] 2021-11-26 11:13
so we should ask for the docker team to support this?
Recompiling the kernel seems too heavy for end users like us. 
and I don't know how to for desktop docker either.

**Comment by pchaigno** [comment] 2021-11-26 11:28
I don't know where Kind gets their kernel image, but yes, you could try to ask for that config to be enabled in the image.

I'll close this issue given it's not a bug in Cilium and the original question has been answered. Feel free to ask if you have any other questions regarding Cilium.

**Closed as completed by pchaigno** 2021-11-26 11:28 UTC
Labels: kind/question
