### ISSUE TITLE
Agent can't start up: msg="Error while creating daemon" error="listen tcp :40457: bind: address already in use"

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#13400] opened 2020-10-05 06:59 UTC
The agent is trying over and over before it fails:
```
test-output.log:2020-10-04T21:29:56.420565028Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :40457: bind: address already in use" subsys=fqdn/dnsproxy
test-output.log:2020-10-04T21:30:00.420875556Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :40457: bind: address already in use" subsys=fqdn/dnsproxy
test-output.log:2020-10-04T21:30:04.42116714Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :40457: bind: address already in use" subsys=fqdn/dnsproxy
test-output.log:2020-10-04T21:30:08.421419711Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :40457: bind: address already in use" subsys=fqdn/dnsproxy
test-output.log:2020-10-04T21:30:12.42518694Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :40457: bind: address already in use" subsys=fqdn/dnsproxy
test-output.log:2020-10-04T21:30:16.42229825Z level=fatal msg="Error while creating daemon" error="listen tcp :40457: bind: address already in use" subsys=daemon
```

Example of failed CI run: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2645/

[bf78dc42_K8sIdentity_Identity_expiration_Expiration_of_CiliumIdentity.zip](https://github.com/cilium/cilium/files/5325737/bf78dc42_K8sIdentity_Identity_expiration_Expiration_of_CiliumIdentity.zip)

**Comment by joestringer** [comment] 2020-10-12 15:43
From community meeting:

* Should not happen since cilium-agent uses SO_REUSEPORT.
* Possible hang of previous cilium-agent process?

**Comment by joestringer** [comment] 2020-10-15 22:58
Hit in Suite-k8s-1.18.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with vxlan With host policy Tests NodePort:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/3483/testReport/junit/Suite-k8s-1/18/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_With_host_policy_Tests_NodePort/

[1442c9ce_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_With_host_policy_Tests_NodePort.zip](https://github.com/cilium/cilium/files/5388290/1442c9ce_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_With_host_policy_Tests_NodePort.zip)

**Comment by aanm** [comment] 2020-10-20 08:52
Hit in https://github.com/cilium/cilium/pull/13592

**Comment by aanm** [comment] 2020-11-05 16:15
Still happening

**Comment by jrajahalme** [comment] 2020-11-05 22:58
Still happening https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1092/testReport/junit/Suite-k8s-1/12/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Maybe we should try another port if we get the address already in use error?

**Comment by aanm** [comment] 2020-11-27 18:09
Hit in https://github.com/cilium/cilium/pull/14200

**Comment by aanm** [comment] 2020-11-30 16:24
hit https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/6196/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_TC__direct_routing_and_Hybrid/

**Comment by jrajahalme** [comment] 2020-12-06 21:03
Hit in GKE: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3523/

**Comment by tklauser** [comment] 2020-12-17 10:29
It's possible that the port collision happened because of the `gops` agent using the same port as the proxy. Unfortunately, the port to which gops agent `bind()`s is not reported in the sysdump.

This behavior was fixed in #14329 for #14218, i.e. `gops` will now `bind()` to a fixed port and should no longer claim arbitrary other ports. Leaving this issue open for a while to confirm whether this was fixed by #14329.

**Comment by jrajahalme** [comment] 2021-02-21 16:08
Happened on kernel 4.9/k8s 1.14 on v1.8, gops fixed port fix not backported to v1.8.

**Comment by tklauser** [comment] 2021-04-10 12:51
In the last ~2 months the only re-occurrence of this flake was on v1.8 where #14329 wasn't backported. So it indeed looks like this was caused by `gops` using the same port as the proxy. I'll send a manual backport of #14329 targeting v1.8, so this issue can be closed.

**Comment by tklauser** [comment] 2021-04-10 13:55
#15634 is the backport PR which should also fix this for v1.8.

**Comment by tklauser** [comment] 2021-04-19 08:34
#15634 now fixed this in v1.8 as well.

**Comment by jrajahalme** [comment] 2021-07-15 08:46
Still happening on v1.8:
```
2021-07-14T15:22:35.894902883Z level=info msg="  --gops-port='9890'" subsys=daemon
2021-07-14T15:22:35.895312533Z level=info msg="  --tofqdns-proxy-port='0'" subsys=daemon
2021-07-14T15:22:37.126736948Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :41755: bind: address already in use" subsys=fqdn/dnsproxy
2021-07-14T15:22:41.127131777Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :41755: bind: address already in use" subsys=fqdn/dnsproxy
2021-07-14T15:22:45.128042903Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :41755: bind: address already in use" subsys=fqdn/dnsproxy
2021-07-14T15:22:49.128237550Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :41755: bind: address already in use" subsys=fqdn/dnsproxy
2021-07-14T15:22:53.128641472Z level=warning msg="Attempt to bind DNS Proxy failed, retrying in 4s" error="listen tcp :41755: bind: address already in use" subsys=fqdn/dnsproxy
2021-07-14T15:22:57.128845126Z level=fatal msg="Error while creating daemon" error="listen tcp :41755: bind: address already in use" subsys=daemon
```

Unfortunately no bugtool info for the node where Cilium agent failed, even though a lot of it could be collected even without Cilium agent running :-(

Happened on: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.19/232/testReport/junit/Suite-k8s-1/17/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device/

[3b5f48aa_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/6821646/3b5f48aa_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device.zip)

**Comment by jrajahalme** [comment] 2021-07-15 08:53
Verified that also v1.8 uses SO_REUSEPORT, so some other process must be is grabbing the port. May if this happens in the CI then this presumably could happen in production as well. May need to mitigate by retrying with a random port after this fail?

**Comment by brb** [comment] 2022-02-17 10:38
Haven't seen this in awhile. Closing.

**Closed as completed by brb** 2022-02-17 10:38 UTC
Labels: kind/bug, area/CI, ci/flake
